### ISSUE TITLE
API/UI:  invalid cursor position in cmdline_show message

### ISSUE THREAD

**Issue by vhakulinen** [neovim/neovim#10000]
With [vim-multiple-cursors](https://github.com/terryma/vim-multiple-cursors), neovim sends invalid `cmdline_show` message where the cursor position is out of bounds.

To reproduce this issue, use [gnvim](https://github.com/vhakulinen/gnvim) (or other GUI for that manner) and vim-multiple-cursor plugin. Once the GUI is running with vim-multiple-cursor, press `C-n C-n` (gnvim will crash at this point because of invalid message from neovim).

Here is a related neovim log: https://gist.github.com/vhakulinen/5137e113800762a53169d49ae8ab1fb9

Related gnvim issue: https://github.com/vhakulinen/gnvim/issues/29

**Comment by bfredl** [comment]
(Unrelated issue when tracking down this bug: the `ccline` in `ui_call_cmdline_show` should be `line->`. Inside the password branch, so probably not causing this particular issue)

**Comment by smolck** [comment]
An invalid `cmdline_show` message also appears to be sent when `esc` is pressed during a `cmap` command.

To reproduce, create a `cmap` command in gnvim (only tried it with gnvim, probably same for other GUIs) and then after typing the first letter of the command in the cmdline quickly press `esc` while gnvim is still waiting for the rest of the command. GNvim will then crash due to Neovim's invalid message. (Typing the first and second, first second and third, etc. letters of the command will work too, so long as you don't actually execute the command and hit `esc` while gnvim is still waiting for the rest of the command.)

**Comment by bfredl** [comment]
Most of these bugs seems to be in "intermediate" flush events, where the correct state is sent immediately after. Probably we are calling `ui_flush()` in weird places where the cmdline state is not yet self-consistent. Ideally we should eliminate such superfluous flushes, but for now we could just enforce that the sent position is less than the length of the cmdline.

**Comment by bfredl** [comment]
I think the fix is even simpler actually:

```diff
diff --git a/src/nvim/ex_getln.c b/src/nvim/ex_getln.c
index 479d19596..1c1bfcad3 100644
--- a/src/nvim/ex_getln.c
+++ b/src/nvim/ex_getln.c
@@ -1978,6 +1978,7 @@ static int command_line_changed(CommandLineState *s)
 static void abandon_cmdline(void)
 {
   XFREE_CLEAR(ccline.cmdbuff);
+  ccline.redraw_state = kCmdRedrawNone;
   if (msg_scrolled == 0) {
     compute_cmdrow();
   }

```

seems to work when I test with python-gui at least.
