### ISSUE TITLE
No nightly release since 22 May

### ISSUE THREAD

**Issue by dimbleby** [neovim/neovim#10080]
Not clear to me how the nightly releases work or I'd try harder to investigate / fix ... but there hasn't been a nightly release since 22nd May.

I suppose something has gone wrong?

**Comment by justinmk** [comment]
Yep, it's a bug in the CI script. I plan to fix it soon. And then hopefully it's fixed forever :)

**Comment by justinmk** [comment]
For reference, the problem was that the stable branch was missing some changes needed to produce the appimage in the way expected by the [bot](https://github.com/neovim/bot-ci).

To fix that (as well as an unrelated Vim security patch), we've pushed a new release:

https://github.com/neovim/neovim/commits/release-0.3

The `nightly` _and_ `stable` releases should be updated in the next 24 hours. Leave a comment if not.
