### ISSUE TITLE
tests: windows: executable_spec: failed with defined GCOV_ERROR_FILE

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10200]
With #10198 I've noticed that https://github.com/blueyed/neovim/blob/c56ee98a46c910efbc36e1a3c005bbd4fe5c3764/test/functional/eval/executable_spec.lua#L53 would fail with `GCOV_ERROR_FILE: "$(APPVEYOR_BUILD_FOLDER)/libgcov-errors.log"` in the environment.

Changing it to be in the temporary directory appears to have fixed it.

This might indicate some issue with `executable` on Windows in general, or some flakyness.

Failing build: https://ci.appveyor.com/project/neovim/neovim/builds/25234643

_Originally posted by @blueyed in https://github.com/neovim/neovim/pull/10198#issuecomment-501380919_

**Comment by erw7** [comment]
The same test failure occurs in https://ci.appveyor.com/project/neovim/neovim/builds/25214830/job/q043dp1k5k6ah692. I think that there is a problem with `executable()` on Windows regardless of GCOV_ERROR_FILE. I do not know if it is related to this phenomenon, but I fixed it with #10209 because there was a bug in `is_executable_ext()`.

**Comment by blueyed** [comment]
Thanks!
Closing in favor of https://github.com/neovim/neovim/pull/10209 for now.
