### ISSUE TITLE
ci: AppVeyor: use bash / shared shell scripts

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10271]
In #8124 (https://github.com/neovim/neovim/commit/e24e98534bbb915d484eca0056ff8b57a2eb2a1d) the .bat script was replaced with a PowerShell one.

But in general we should make it use the shared bash/shell scripts.

Not too sure about this, but it certainly is bad that e.g. ci/build.ps1 has no syntax highlighting etc.

**Comment by justinmk** [comment]
Vim powershell syntax highlighting exists, it was never submitted to Bram though. We could add it since the authors never did. https://github.com/PProvost/vim-ps1

`build.ps1` may someday be used outside of CI (@janlazo worked on this https://github.com/neovim/neovim/pull/8405), so requiring bash is not an option.
