### ISSUE TITLE
Update Install Docs on Wiki

### ISSUE THREAD

**Issue by rotated8** [neovim/neovim#10347]
I'd like to update the [Installing Neovim](https://github.com/neovim/neovim/wiki/Installing-Neovim) page in the wiki with the following goals:

- There should be a table of contents so users can skip right to their platform.
- The platforms should be alphabetized so there is no confusion over whether a platform is supported.
- The Ubuntu section should be updated to note Neovim is available through apt, since bionic 18.04.

Are there any concerns or other changes that should go into this?

**Comment by justinmk** [comment]
> There should be a table of contents so users can skip right to their platform.

Not in favor of that. It requires the ToC to be maintained, and it makes the much longer . And it puts the ToC at the top of the page instead of the stuff that's currently there which is more important.

> The platforms should be alphabetized so there is no confusion over whether a platform is supported.

It already is, mostly. If you find one that's out of place, sure. But if it requires re-arranging the whole page, then no, someone else will just re-arrange it again later for some other reason.

> The Ubuntu section should be updated to note Neovim is available through apt, since bionic 18.04.

Sure. Please be brief, avoid long verbose explanations and quickly-outdated information/links.
