### ISSUE TITLE
reltimestr(reltime(newer_time, older_time)) does not return negative number

### ISSUE THREAD

**Issue by tpope** [neovim/neovim#10452]
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-tWk8pe/neovim-0.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wn
o-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-tWk8pe/neovim-0.3.4/build/confi
g -I/build/neovim-tWk8pe/neovim-0.3.4/src -I/usr/include -I/build/neovim-tWk8pe/neovim-0.3.4/build/src/nvim/auto -I/build/neovim-tWk8pe/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Steps to reproduce using `nvim -u NORC`

```
let older_time = reltime()
sleep 1m
let newer_time = reltime()
echo reltimestr(reltime(newer_time, older_time))
```

### Actual behaviour
 Very large positive number.

### Expected behaviour
Very small negative number.

I see other issues around the handling of a single `reltime()` which have been correctly closed as wontfix, but the end result of a comparison should be the same for all Vim implementations, no?

**Comment by blueyed** [comment]
I am seeing `0.000000` on master (but a large number with 0.3.7).
When switching `newer_time` and `older_time` in the call to `reltime` (to match the `start, end` signature) it seems to make more sense (in both cases).

**Comment by justinmk** [comment]
> I am seeing `0.000000` on master (but a large number with 0.3.7).

In e5ff9d6168de0ffaf59d6bf20f20631a34a2d I changed `profile_sub` to avoid negative values, thinking it would only happen if the system clock goes backwards. That can be reverted.

The negative vs large-number is most likely because because `proftime_T` is unsigned, which was changed long ago. We can probably change it to be signed. cc @aktau

**Comment by aktau** [comment]
> In e2ce5ff I changed profile_sub to avoid negative values, thinking it would only happen if the system clock goes backwards. That can be reverted.

I think that entire patch should be reverted. We want to use monotonic time for `reltime()`: https://github.com/neovim/neovim/issues/10328#issuecomment-510386392.

However, there _is_ a problem here (even with the patch reverted): the large values as observed by @tpope. I'm trying to recall if there were any other reasons I made this `uint64_t` back in the day. https://github.com/neovim/neovim/pull/10453 changes it to be `int64_t`.

Note that I already had to do a cast to signed for doing correct before/after comparisons:

```c
/// Calculates the sign of a 64-bit integer.
///
/// @return -1, 0, or +1
static inline int sgn64(int64_t x) FUNC_ATTR_CONST
{
  return (int) ((x > 0) - (x < 0));
}

/// Compares profiling times.
///
/// Times `tm1` and `tm2` must be less than 150 years apart.
///
/// @return <0, 0 or >0 if `tm2` < `tm1`, `tm2` == `tm1` or `tm2` > `tm1`
int profile_cmp(proftime_T tm1, proftime_T tm2) FUNC_ATTR_CONST
{
  return sgn64((int64_t)(tm2 - tm1));
}
```

(Side note: that cast could in principle be removed now that the value is signed and if we decide to keep it that way).

I *think* I made this unsigned because:

  - Unsigned overflow is defined, whereas signed overflow is UB.
  - The OS/libuv time functions returns `uint64_t`.

I think I would still prefer altering the output functions `f_reltimestr` and `f_reltimefloat` to deal with this properly, rather than changing the underlying type.

**Comment by justinmk** [comment]
> I think that entire patch should be reverted.

Reverted in https://github.com/neovim/neovim/pull/10488 .

> Unsigned overflow is defined, whereas signed overflow is UB.

Yes. But we don't handle overflow, so it is semantically undefined in any case.  E.g. `profile_msg` casts `profile_T` to `double`.

`STRICT_ADD` can be used to guard against  overflow. This is done in #10488.

> I think I would still prefer altering the output functions `f_reltimestr` and `f_reltimefloat` to deal with this properly, rather than changing the underlying type.

Should `profile_sub` be allowed to return negative value?

**Comment by aktau** [comment]
> STRICT_ADD can be used to guard against overflow. This is done in #10488.

The problem is that overflow is a natural part of these types.

(After looking at patch #10488, more memories of my thoughts when I implemented neovims version of the profiling functions come back to me. Which reminded me of another reason I chose `uint64_t`, and is relevant for the `INT64_MAX` and `STRICT_ADD` checks.)

I see two things in that patch which are different from the pre-reverted-commit state:

- A check that the result of `os_hrtime()` is < INT64_MAX (in `profile_start`, `profile_end` and `profile_passed_limit`). 
- A check that the result of `profile_add` and `profile_setlimit` are less than `INT64_MAX`.

An example of each case:

```c
proftime_T profile_start(void) FUNC_ATTR_WARN_UNUSED_RESULT {
  uint64_t now = os_hrtime();
  assert(now <= INT64_MAX); // New.
  return (proftime_T)now;
}

proftime_T profile_add(proftime_T tm1, proftime_T tm2) FUNC_ATTR_CONST {
  int64_t rv;
  STRICT_ADD(tm1, tm2, &rv, int64_t); // New.
  return rv;
}
```

Thinking on it, it seems harmful:

1. The interfaces of nearly all platforms return `uint64_t`. `INT64_MAX` is only half of that.
2. All low-level interfaces like this I've seen define that there is no fixed starting point for the number that's returned. The only guarantees are that it's (a) monotonically increasing at a rate that (b) matches real time.

Ergo, it would be valid for Windows to return `INT64_MAX` one second, and `INT64_MAX+1000000000` the next. It would even be valid for it to return `UINT64_MAX`. 

OK, so the starting point is not specified. What's the implementation really like? The number returned is often the value of the TSC (processor cycles since reset) adjusted for clock rate (to normalize time passage to SI units). Which implies it basically starts at 0 when the computer starts up and increases by 10^9 each second. Since there's about ~584 years worth of nanoseconds to fill up a uint64_t (and ~292 years to fill up a int64_t), it's more of a theoretical problem. Unless of course an OS decides to salt its timers to prevent misconceptions about the API contract. I have a vague recollection of Linux at least considering this. We shouldn't rely on operating systems not doing this.

All of this undefined starting location business is fine, because functions dealing with this should only take the relative passage of time into account (Vim itself also defines `reltime` as relative time). The original functions do. Implicitly by reusing `uint64_t` which has good, defined semantics for performing addition and subtraciton, and explicitly. Note the comment on `profile_cmp`:

```c
/// Compares profiling times.
///
/// Times `tm1` and `tm2` must be less than 150 years apart.
///
/// @return <0, 0 or >0 if `tm2` < `tm1`, `tm2` == `tm1` or `tm2` > `tm1`
int profile_cmp(proftime_T tm1, proftime_T tm2) FUNC_ATTR_CONST { return sgn64((int64_t)(tm2 - tm1)); }
```

Suppose `proftime_T` is changed back to `uint64_t` and overflow allowed to take its course (perhaps explicitly documented this time), we're still not there for returning values from `reltimestr()` and `reltimefloat()` that users like @tpope expect.

I'd basically use the same approach as `profile_cmp`: 

- Value is `<= INT64_MAX`: positive
- Value is `> INT64_MAX`: negative 

Which would only be wrong if the duration measured is hundred of years.

This sounds like it could be done by just casting the `uint64_t` AKA `proftime_T` to `int64_t` just before rendering it as a string. However, I was surprised to learn that unsigned -> signed conversion is undefined when both types have the same number of bits. See https://unspecified.wordpress.com/category/c-3 and https://stackoverflow.com/a/50632). This also means that `profile_cmp` currently has undefined behaviour. It works fine on 2s-complement machines (basically all machines currently in use), but it wouldn't work as well on 1s-complement machines.

Reading the rules on that blogpost, it seems like the following would be standards compliant defined behaviour:

```c
int64_t signed_ns = (unsigned_ns <= INT64_MAX) ? (int64_t) unsigned_ns : - (int64_t) (unsigned_ns - INT64_MAX);
```

Which is really ugly, and effectively what `(int64_t) unsigned_ns` does on 2s-complement machines. Oh well.

**Comment by justinmk** [comment]
@aktau makes sense. Do you plan to send a PR?

**Comment by aktau** [comment]
`reltimestr` is indeed fixed, but `reltimefloat` still interpret it as float. Technically this bug is fixed, since it only asks for `reltimestr`, but I think it'd be weird to people to have it be so different:

```vim
:echo reltimestr(reltime(newer_time, older_time)) 
-4.708678
:echo reltimefloat(reltime(newer_time, older_time)) 
1.844674e10
```

**Comment by aktau** [comment]
Thanks Justin!
