### ISSUE TITLE
matchit error when used the latest neovim nightly

### ISSUE THREAD

**Issue by taigacute** [neovim/neovim#10680]
- `nvim --version`:  NVIM v0.4.0-1534-g24fb7eefa
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: macos 10.13.6
- Terminal name/version: iterm2
- `$TERM`: xterm-256colors

### Steps to reproduce using `nvim -u NORC`

i often used the nightly version. But I have stayed in this version`NVIM v0.4.0-1426-g0e23ee3cc` recently, it has been working very well, I updated `NVIM v0.4.0-1534-g24fb7eefa` today, when I started nvim I got this error, tried to reproduce it with minimal configuration, but I failed.  
### Actual behaviour
![image](https://user-images.githubusercontent.com/41671631/62410885-b39a0380-b61e-11e9-9666-3ab131fdfa60.png)

### Expected behaviour
works well

**Comment by zgpio** [comment]
You should check option `packpath`.

**Comment by taigacute** [comment]
the value of `packpath` should be same as `runtimepath`.  
I used it for a long time and nightly worked very well without setting up the packpath, so it suddenly appeared this error. Is very strange

**Comment by justinmk** [comment]
the machit plugin lives in pack/ directory now. Why are you setting packpath to empty?

**Comment by taigacute** [comment]
@justinmk   i think its not empty,i just not set it.  the machit lives in pack. so must set packpath?

**Comment by zgpio** [comment]
You should realize that he `plugin/matchit.vim` will be loaded.

**Comment by taigacute** [comment]
I think you should realize that the problem is that matchit has been moved. You don't need to set set packpath before this move because it has the same value as the runtimepath. by check this commit [5342342](https://github.com/neovim/neovim/commit/5342342426777160300a431ef8c9200fb151f793) i know why .

**Comment by justinmk** [comment]
@taigacute the move shouldn't provoke that error. Does it happen with `nvim -u NORC`? Compare the output of : 

    :set packpath?

with `nvim -u NORC` and with `nvim` (i.e. your normal config)

**Comment by taigacute** [comment]
@justinmk   nvim with my config  i got `packpath=` both `NVIM v0.4.0-1426-g0e23ee3cc` and `NVIM v0.4.0-1544-g0bb1008e7` . `nvim -u NORC` got correctly path value . but  i want know why can `NVIM v0.4.0-1426-g0e23ee3cc` work.  i tried the latest nightly doesnt work.

**Comment by justinmk** [comment]
@taigacute could you mention what exactly was the problem, in case other users run into this (or we can add a workaround to avoid it)?

**Comment by taigacute** [comment]
@justinmk  by check my config i found the reason that   i disable the default plugins by use `set packpath=` to improve my neovim . but the rencently version of nightly cant use `set packpath`.

**Comment by justinmk** [comment]
@taigacute `:set packpath=` doesn't really do anything because the default packages are in `/pack/*/opt/` (instead of `/pack/*/start/`), which means they aren't loaded by default. However, matchit.vim is force-loaded by `plugin/matchit.vim` because that's how it was even before it was moved to `/pack/*/opt/`.

**Comment by murchu27** [comment]
Just adding a quick note on the offchance anyone arrives here after getting this issue on Raspberry Pi (or I guess any ARM device that uses `apt` as its package manager).

As of this writing, installing via `apt` installs v0.3.4, which predated [05712d4](https://github.com/neovim/neovim/commit/05712d4b20fbc260134b9e5b6f816cfee90c1ab2); so if you've installed neovim through `apt`, you might see this error. Apparently `apt` doesn't do a great job at keeping up with the stable releases (see #11615). 

As @justinmk [mentions in that issue](https://github.com/neovim/neovim/issues/11615#issuecomment-568965708), installing via `snap` will get you a daily version. See [here](https://snapcraft.io/install/nvim/raspbian). This issue is gone with that release.
