### ISSUE TITLE
shape and color of cursor are changed in linux console

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#10750]
- `nvim --version`:        NVIM v0.4.0-1664-g48dc6344d Build type: Release
 - Vim (version:  8.1 Included patches: 1-1830) behaves differently? Yes
 - Operating system:     Ubuntu 16.04.6 LTS
 - `$TERM`:                linux
 - Shell:                zsh 5.7.1 (x86_64-pc-linux-gnu)

### Steps to reproduce

On Ubuntu 16.04, switch to a virtual console by pressing `Ctrl-Alt-F1`, and log in.
The cursor is a black blinking underscore.

Start Nvim with:

    $ nvim -Nu NONE --cmd 'set gcr='

### Actual behaviour

The color of the cursor becomes red, and its shape becomes a steady block.
After quitting Nvim, the shape and the color of the cursor are not restored; i.e. the cursor remains a red steady block.

### Expected behaviour

The shape and color of the cursor are not changed when starting Nvim, and when quitting Nvim the cursor keeps its original appearance.

I bisected the issue to fcf6bfd3601acc28ae3d116670928f82db949b30.

**Comment by blueyed** [comment]
Thanks for the report and bisect!
/cc @erw7 (via https://github.com/neovim/neovim/commit/fcf6bfd3601acc28ae3d116670928f82db949b30)

**Comment by erw7** [comment]
When I checked it, it was `cnorm=\E[?25h\E?0c` result of `infocmp`, but `cnorm=<Esc>[?25h` result of  `nvim -u NORC -V3log`. I think this is the cause(After nvim is finished, `echo -n "\x1b[?25h\x1b?0c"` will restore the cursor). I don't know why fcf6bfd causes this problem. I'll investigate a little more, so please give me some time.

**Comment by justinmk** [comment]
Likely this is because we now initialize the TUI before sourcing user config:

```c
  // Execute --cmd arguments.
  exe_pre_commands(&params);

  // Source startup scripts.
  source_startup_scripts(&params);
```

But if we source user config before starting the TUI, then we regress #7967 : hit-enter prompts will be displayed before the UI exists to serve them.

We shouldn't revert #7967. Instead, maybe the TUI needs to handle the change of 'guicursor' or maybe it needs to re-initialize some part of `patch_terminfo_bugs`() or `augment_terminfo()`.

> I bisected the issue to [fcf6bfd](https://github.com/neovim/neovim/commit/fcf6bfd3601acc28ae3d116670928f82db949b30).

@lacygoill before that commit, _without_ `set gcr=`, does the behavior also happen?

**Comment by lacygoill** [comment]
@justinmk Yes, on the previous commit 16b1e8f9c070ad853c6c63b43591e297bf512662 if I start Nvim with `$ nvim -Nu NONE`, the cursor is also altered.

**Comment by justinmk** [comment]
> Does that mean that I was wrong using `$ nvim -Nu NONE --cmd 'set gcr='` during the bisect?

No. I just wanted to confirm the issue specifically is a matter of respecting `set gcr=`.

**Comment by erw7** [comment]
> Instead, maybe the TUI needs to handle the change of 'guicursor' or maybe it needs to re-initialize some part of `patch_terminfo_bugs()` or `augment_terminfo()`.

Since it is called before the cursor is set by `tui_set_mode()` called from `tui_mode_info_set()`, reinitialization with `patch_terminfo_bugs()` or `augment_terminfo()` will not work. If we want to reinitialize, we should use `tui_mode_info_set()`. In that case, I think that the behavior when `set gcr =` after setting `gcr` changes(Instead of the cursor that was initially set with gcr, it will return to the terminal default).

There is one more problem. What is the intent of the following code? Because of that, even if `cnorm` is output, the cursor does not return to the default.

https://github.com/neovim/neovim/blob/90e44ecf1144cb32195da00e24d23afb111ea680/src/nvim/tui/tui.c#L1544-L1553

**Comment by justinmk** [comment]
> There is one more problem. What is the intent of the following code?

I don't know :(

> `tui_set_mode()` called from `tui_mode_info_set()`, reinitialization with `patch_terminfo_bugs()` or `augment_terminfo()` will not work

- Q: Would it work to delay `tui_mode_info_set` during startup (similar to `set_bg_deferred`)?
- A: No, because the delayed `tui_mode_info_set` will override whatever was done by user config. 
    - Main problem: `set_init_2()` initializes 'guicursor'. 
        - Maybe we can move that later (e.g. into `set_init_3`)?

This seems to fix the problem AFAICT:

```diff
diff --git a/src/nvim/option.c b/src/nvim/option.c index 55b69edba086..953479fdd05f 100644
--- a/src/nvim/option.c
+++ b/src/nvim/option.c
@@ -1001,7 +1001,6 @@ void set_init_2(bool headless)
     p_window = Rows - 1;
   }
   set_number_default("window", Rows - 1);
-  parse_shape_opt(SHAPE_CURSOR);   // set cursor shapes from 'guicursor'
   (void)parse_printoptions();      // parse 'printoptions' default value
 }
-
@@ -1010,6 +1009,8 @@ void set_init_2(bool headless)
  */
 void set_init_3(void)
 {
+  parse_shape_opt(SHAPE_CURSOR);   // set cursor shapes from 'guicursor'
+
   // Set 'shellpipe' and 'shellredir', depending on the 'shell' option.
   // This is done after other initializations, where 'shell' might have been
   // set, but only if they have not been set before.
```
