### ISSUE TITLE
shada: random highlighting at startup

### ISSUE THREAD

**Issue by markuspeloquin** [neovim/neovim#10945]
I first noticed this issue yesterday (I pull & build every morning). Randomly at startup (maybe 5% of the time, made more likely to occur if I search for something in the previous nvim invocation), all text is highlighted as if I typed `/.` (if I look through search history by typing `/`+UP, but nothing that would cause this).

I did a binary search through the commits and found that the problem must be with this commit, which looks harmless to me (but I'm not familiar with neovim internals at all):
https://github.com/neovim/neovim/commit/8b8ecf44f2cda43bbd710ec22ef99439b71888cd

- `nvim --version`
  - NVIM v0.4.0-1943-g8b8ecf44f
- `vim -u DEFAULTS` (version: ) behaves differently?
  - No. I also moved `~/.vim` (sourced by `~/.config/nvim/init.vim`) and `~/.vimrc` out of the way, still occurs
- Operating system/version:
  - 5.2.9-200.fc30.x86_64 (Fedora 30, Linux 5.2.9)
- Terminal name/version:
  - GNOME Terminal 3.32.2
- `$TERM`:
  - screen-256color

### Steps to reproduce using `nvim -u NORC`

I think I need `set hlseach` for it to manifest, so it doesn't reproduce.

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

### Actual behaviour
Random highlighting at startup ~5% of the time.

Highlights from previous session are gone or have changed.

### Expected behaviour
No random highlights at startup.

In the previous commit, if I searched for `include`, it would highlight. If I restart nvim, it would remain highlighted. That is no longer the case.

**Comment by justinmk** [comment]
cc @abdelhakeem

**Comment by abdelhakeem** [comment]
I'm unable to reproduce this. Also ran `v:hlsearch`-related tests from `test/functional/shada/history_spec.lua` in a loop and can't get them to fail.

What is the value of `'shada'`?

**Comment by blueyed** [comment]
> 'hlseach ' is stored in shada, it is tricky

Not the setting itself though, is it?

@markuspeloquin 
> I think I need set hlseach for it to manifest, so it doesn't reproduce.

You can adjust it like e.g. `nvim -u NORC -c 'set hlsearch'`.

If it happens, what does `:echo getreg('/')` give you then?

Do I understand it correctly that the behavior is as if "." was used with `/`?

**Comment by blueyed** [comment]
@markuspeloquin 
Also worth checking if you can reproduce it with a separate/new shada file (use `nvim -i /tmp/shada.nvim …` to use it).

**Comment by markuspeloquin** [comment]
I cannot reproduce with `nvim -u NORC -c 'set hlsearch'`.

I **can** reproduce with `nvim -i /tmp/shada.nvim`. The new file looks nothing like the old one (`~/.local/share/nvim/shada/main.shada`). It is some sort of binary encoding, while the one in `~/.local` is plain text. Also note that I install neovim with prefix `$HOME/.local`.

**Comment by justinmk** [comment]
> I cannot reproduce with `nvim -i /tmp/shada.nvim`. The new file looks nothing like the old one (`~/.local/share/nvim/shada/main.shada`). It is some sort of binary encoding, while the one in `~/.local` is plain text. 

shada has always been "binary" encoded (msgpack, specifically). If `~/.local/share/nvim/shada/main.shada` is "plain text" then it's not a valid shada file; I would expect it to be skipped or raise an error in that case. Can you post the "plain text" file? 

Are you able to reproduce the issue by specifically targeting the "plain text" file:

    nvim -i ~/.local/share/nvim/shada/main.shada

**Comment by markuspeloquin** [comment]
Sorry, neovim interprets the file and shows me a textual representation. It showed binary for `/tmp/shada.nvim`, but it showed a textual representation with `/tmp/main.shada`.

**Comment by abdelhakeem** [comment]
@markuspeloquin What does `:set shada?` output?

**Comment by markuspeloquin** [comment]
`shada='20,"50`. This should be the default, I haven't changed it.

**Comment by abdelhakeem** [comment]
Well, the default on non-Win32 platforms is `!,'100,<50,s10,h` (see `:h 'shada'`).

I suspect some plugin is in the scene. The mentioned commit doesn't (directly) touch `'hlsearch'`, so it'd be more helpful to provide a way to reproduce the "issue" with `-u NONE` or `-u NORC`.

Also with `shada='20,"50`, `'hlsearch'` is not supposed to be restored, this is the expected behavior.

**Comment by justinmk** [comment]
Cannot reproduce with (using current master 8b06231612cd608b2dce5e0a09bf40192a4803cb ):

    nvim --cmd "set shada-=h" -i foo.shada CONTRIBUTING.md

In that case (`h` flag removed), the highlighting is restored correctly. In the converse case (`h` flag added) highlighting is not restored after exiting and starting again.

**Comment by markuspeloquin** [comment]
So I actually have `set viminfo='20,"50` in my .vimrc (which I tried to make compatible with both vim & neovim). Removing that line and I still have the problem.

I went through my plugins again. I swear I did this before but oh well. I found that https://github.com/jlanzarotta/bufexplorer is the one. A quick look through the source and I don't see anything (really) about highlighting or viminfo.

I don't know if there's anything special about my main.shada file. I can share it privately with you if you like. But this is definitely a bug in neovim/bufexplorer and it did not manifest before https://github.com/neovim/neovim/commit/8b06231612cd608b2dce5e0a09bf40192a4803cb .

**Comment by justinmk** [comment]
bufexplorer [loads buffers and changes tabpages](https://github.com/jlanzarotta/bufexplorer/blob/ff3c8a1adaac7a443338a8310f50f1f26046f23e/plugin/bufexplorer.vim#L137-L153) on startup (`autocmd VimEnter`).

**Comment by abdelhakeem** [comment]
I think I can reproduce the issue, thanks to @bfredl for [this trace](https://gist.github.com/bfredl/877084bb2b3dd026d918dda3be17d39f).

Reproduction steps (on [master: 158b780](https://github.com/neovim/neovim/tree/158b78062e9daa65203b4591dae733dd6c11ad2c)):

```
$ nvim -u NONE -i /tmp/shada
:edit src/nvim/main.c
/include
:q
$ nvim -u NONE -i /tmp/shada
:au BufNew * echo
:q
```
_(crashes)_

Since https://github.com/neovim/neovim/commit/8b8ecf44f2cda43bbd710ec22ef99439b71888cd loads buffers for all files in the jump list before writing shada, this can trigger some autocommands (e.g.: `BufNew`), and `apply_autocmds_group()` calls `restore_search_patterns()` [here](https://github.com/neovim/neovim/blob/158b78062e9daa65203b4591dae733dd6c11ad2c/src/nvim/fileio.c#L6975) which frees [`spats`](https://github.com/neovim/neovim/blob/158b78062e9daa65203b4591dae733dd6c11ad2c/src/nvim/search.c#L76-L87) and restores the original patterns from [`saved_spats`](https://github.com/neovim/neovim/blob/158b78062e9daa65203b4591dae733dd6c11ad2c/src/nvim/search.c#L97-L98), so the value stored in `wms->search_pattern` [here](https://github.com/neovim/neovim/blob/158b78062e9daa65203b4591dae733dd6c11ad2c/src/nvim/shada.c#L2712-L2714) is no longer valid (i.e.: freed). The solution is to move the [jump list initialization logic](https://github.com/neovim/neovim/blob/158b78062e9daa65203b4591dae733dd6c11ad2c/src/nvim/shada.c#L2739-L2742) before [this line](https://github.com/neovim/neovim/blob/158b78062e9daa65203b4591dae733dd6c11ad2c/src/nvim/shada.c#L2712).
