### ISSUE TITLE
How do I disable Python2 provider check in checkhealth?

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/neovim#11040]
init.vim
```
let g:loaded_python_provider = 0
let g:python_host_prog = ''
```

Checkhealth message.
```
## Python 2 provider (optional)
 - INFO: Disabled (g:loaded_python_provider=0).  This might be due to some previous error.
 - INFO: Using: g:python_host_prog = ""
 - WARNING: No Python executable found that can import neovim. Using the first available executable for diagnostics.
 - ERROR: Python provider error:
   - ADVICE:
     - provider/pythonx: Could not load Python 2:
         python2 not found in search path or not executable.
         /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
         python2.6 not found in search path or not executable.
         /usr/bin/python does not have the "neovim" module. :help |provider-python|
 - INFO: Executable: Not foun
```

How can I disable this error message without installing Python2?

**Comment by blueyed** [comment]
Maybe we should skip it with an empty host prog?
(I assume it is useful to get information with `let g:loaded_python_provider = 0`, since we do not know if it was set due to an error (easily), right?)

Code ref: https://github.com/neovim/neovim/blob/0b71bb73e8431400c870dcd458f322dc50da96d1/runtime/autoload/health/provider.vim#L270-L278

But apart from that I'd just ignore it for now - it is only a cosmetical problem, isn't it?
(and you are not using `:checkhealth` often, are you)?

**Comment by nabezokodaikon** [comment]
I simply think it would be strange to get an error with `let g: loaded_python_provider = 0` when python2 is not installed.
If ruby or node.js is disabled, it only takes one line of `INFO: Disabled. g: loaded_ruby_provider = 0`.

**Comment by blueyed** [comment]
Good point, makes sense then.

**Comment by h-michael** [comment]
@blueyed related with #8047

**Comment by justinmk** [comment]
> If ruby or node.js is disabled, it only takes one line of `INFO: Disabled. g: loaded_ruby_provider = 0`.

That seems reasonable.  Waiting for a PR.
