### ISSUE TITLE
`sudo ls | nvim -R -` is broken in 0.4

### ISSUE THREAD

**Issue by yan12125** [neovim/neovim#11065]
- `nvim --version`:
```
NVIM v0.5.0-23-gafd576ee9
Build type: Debug
LuaJIT 2.0.5
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/yen/tmp/neovim/build/config -I/home/yen/tmp/neovim/src -I/usr/include -I/home/yen/tmp/neovim/build/src/nvim/auto -I/home/yen/tmp/neovim/build/include
Compiled by yen@PC951

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
0.4.2 has a similar issue.
- `vim -u DEFAULTS` (version: ) behaves differently? yes, but it's broken in another way
- Operating system/version: Arch Linux up-to-date
- Terminal name/version:
  * qterminal 0.14.1 on Arch Linux
  * iTerm2 3.3.4 on macOS Mojave - I ssh to my Arch Linux box to test it
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

The issue does not appear without a configuration file. Here is a minimal `~/.config/nvim/init.vim` to reproduce the issue:
```
set title
```
With that the issue can be reproduced with:
```
sudo ls | nvim -R -
```

### Actual behaviour
The screen is cleared first and then the sudo prompt is shown in the first line.
```
[sudo] password for yen:
```
If I hit Ctrl+C now, the terminal is in a broken state
```
$ ls
CMakeCache.txt     CPackSourceConfig.cmake  bin                    config            include  src
                                                                                                 CMakeFiles         Makefile                 cmake_install.cmake    errors            lib      test
                                                                                                                                                                                                   CPackConfig.cmake  api_metadata.mpack       compile_commands.json  funcs_data.mpack  runtime  touches
```

### Expected behaviour
The sudo prompt is shown first, before the screen is cleared.
```
$ sudo ls | nvim -R -
[sudo] password for yen: 
```
And everything is fine if I hit Ctrl+C now.

This is how nvim works in 0.3.8.

---

I tried `git bisect`, which points to https://github.com/neovim/neovim/pull/9829
```
fcf6bfd3601acc28ae3d116670928f82db949b30 is the first bad commit
commit fcf6bfd3601acc28ae3d116670928f82db949b30
Author: erw7 <erw7.github@gmail.com>
Date:   Tue Apr 2 04:08:09 2019 +0900

    main.c: fixes #7967

 src/nvim/main.c | 13 ++++++++-----
 1 file changed, 8 insertions(+), 5 deletions(-)
```

**Comment by justinmk** [comment]
Shell pipe `|` starts processes in parallel. How could this possibly work?

**Comment by yan12125** [comment]
Thank you for the explanations. I guess I've understood it all.

> BTW I cannot reproduce this on macOS

sudo on macOS is in general much older than those on Linux distributions. Mojave has sudo 1.8.17p1 and Arch Linux has sudo 1.8.27. Maybe there are differences in how stderr/stdout are handled in different versions of sudo.

As an alternative approach, I created a zsh script:
```zsh
sudo-to-nvim() {
    local tempfile

    tempfile=$(mktemp "$XDG_RUNTIME_DIR/sudo-to-nvim.XXXXXX")
    sudo "$@" >> "$tempfile"
    nvim -R "$tempfile"
    command rm -f "$tempfile"
}

compdef '_dispatch sudo sudo' sudo-to-nvim
```

**Comment by blueyed** [comment]
> BTW I cannot reproduce this on macOS with 10c983f (which includes fcf6bfd).

For me it looks like this on master: I can barely see the sudo prompt, and then Neovim clears the screen. After typing the password blindly (without the prompt) it displays the file list.

However, using "-u NONE" makes Neovim not clear the screen already, i.e. it works as expected (`sudo -k; sudo ls | build/bin/nvim -u NONE -R -`).

With fcf6bfd (the bisected commit) it indeed looks broken though: Neovim opens / displays a buffer already, and "sudo" does not accept the password (likely part of it gets consumed by Neovim?!).
This was fixed in commit 5fced444b ("tui/input.c: Fix problem when stdin is not TTY") directly after - i.e. that's why it cannot be reproduced with  10c983f (@justinmk).

The new behavior of not clearing the screen was done in 66f4e8ae ("screen: initialize screen properly with early `set display-=msgsep`").

So it looks OK on master, but only when using `-u NONE/NORC`.

As for this issue
1. I think it should work without "-u NONE/NORC" also.  Have not investigated what's causing this (something in my config, and/or just Neovim's default behavior in that case, e.g. syntax highlighting)
2. on master with "-u NONE/NORC" it looks like the terminal is still configured in some way.
   This is how it looks after quitting nvim:
   ```
   % sudo ls | build/bin/nvim -u NONE -R -
   [sudo] password for user:
                             % 
   ```
   (the trailing "%" is an indicator from Zsh that there is no newline, and it
   shows up on a new line)
 
   Whereas with something else it would look like this:
   ```
   % sudo echo 123 | cat -
   [sudo] password for user:
   123
   ```

btw: when testing/bisecting this, make sure to call "sudo k; reset" (in a
command by itself between tests).

**Comment by bfredl** [comment]
>  The new behavior of not clearing the screen was done in 66f4e8a ("screen: initialize screen properly with early set display-=msgsep"). So it looks OK on master, but only when using -u NONE/NORC.

Nvim needs to clear the screen in the first` ui_flush()`. So basically it should work as long as no messages are displayed during the `:h startup` steps (first buffer is loaded in step 12, which I think implies waiting on stdin in the same place), which could be hard to ensure in practice. Refactoring Nvim to load/wait on stdin earlier might be difficult (because init.vim options is expected to apply to this buffer reading also).

**Comment by blueyed** [comment]
Some more info/input: with an `init.vim` like this it will clear the screen already, but the sudo
prompt is visible:

```vim
let foo = system("echo foo")
```

Also with `-u NONE` it can be seen that the terminal is reconfigured already
with `echo "$(read -E)" | build/bin/nvim -u NONE -R -` in zsh: input
during the read is not echoed, and you need to use `ctrl-j` instead of
`Return/<CR>`.

Note that `echo "$(read; echo $REPLY)" | build/bin/nvim -u NONE -R -` in bash
results in nvim starting directly, and the following error being
displayed/visible when quitting it:
```
[prompt]$ echo "$(read; echo $REPLY)" | build/bin/nvim -u NONE -R -
bash: read: read error: 0: Resource temporarily unavailable
                                                           [prompt]$
```

**Comment by bfredl** [comment]
> Some more info/input: with an init.vim like this it will clear the screen already, but the sudo
prompt is visible

It is fundamentally racy because two processes are writing to the same terminal at the same time

**Comment by yan12125** [comment]
> It is fundamentally racy

Thank you all for great explanations! I totally agree now, so I turn to a shell function that ensures sudo ends before nvim starts.
