### ISSUE TITLE
Lua stdlib enhancement suggestions

### ISSUE THREAD

**Issue by norcalli** [neovim/neovim#11167]
Based on my work rewriting my `init.vim` into an `init.lua` and inspired by the python methods, I wrote https://github.com/norcalli/nvim.lua.

This was originally derived from https://github.com/norcalli/nvim_utils (which is a larger collection of utility methods I've created as part of exploring what plugins in lua might look like), but I found myself wanting to use that snippet more than anything else and it was easy to contain in a non-invasive module. So far it's been fantastic for me. I've managed to take my startuptime down to ~75ms from the ~260ms before and improved the configuration's robustness greatly.

The speed of luajit makes the overhead from using magic methods trivial compared to anything else in the rendering/evaluation pipeline as well.

Existing design discussion with @justinmk from irc:

```irc
20:17 < JustinMKeyesGitt> ashkan_kiani: I think your `.o`, `.g`, etc stuff could go directly on the `vim.` module. I would rename `.ex` to `.cmd` maybe. I don't think we can do `nvim.$method`, it risks collisons. How about `nvim.a` ("API") ?
```

I agree that the variable access parts would go well on `vim` itself. As far as the others go, I don't have a particularly strong opinion on the naming of `cmd` vs `ex`. `cmd` is probably better.

The api method shortcuts make the most sense being on an object named `nvim` because you are just swapping a single character to make the equivalent call, e.g. `nvim_command` becomes `nvim.command` instead of `vim.api.nvim_command`, but I'm not sure that adding it as a shortcut on `vim` would make much sense.

**Comment by norcalli** [comment]
I also can think of quite a few methods that would be useful outside of neovim specific functionality, like `string.startswith`, `string.endswith` and path manipulation functions like `join/split/dirname/basename`.

**Comment by norcalli** [comment]
I'll also be happy to turn this into a PR if someone points me in the right direction to start.

**Comment by justinmk** [comment]
> I'll also be happy to turn this into a PR if someone points me in the right direction to start.

- Add code to `src/nvim/lua/vim.lua`, unless it's pure-Lua (i.e. doesn't depend on `nvim`), then add it to `runtime/lua/vim/shared.lua` (so the tests can use those functions too, instead of duplicating in `test/.../helpers.lua`). [Explanation](https://github.com/neovim/neovim/blob/8e25cf3881bbc3d65645d1b2abc6fa46863b1765/src/nvim/lua/vim.lua#L1-L9)
- Use lua docstrings, then we can auto-generate docs. [Example](https://github.com/neovim/neovim/blob/8e25cf3881bbc3d65645d1b2abc6fa46863b1765/src/nvim/lua/vim.lua#L165-L176) (yields [generated doc](https://github.com/neovim/neovim/blob/8e25cf3881bbc3d65645d1b2abc6fa46863b1765/runtime/doc/if_lua.txt#L636-L653); after running `scripts/gen_vimdoc.py`)
- Put tests in `test/functional/lua/utility_functions_spec.lua` (should be renamed to `vim_spec.lua`)

> The api method shortcuts make the most sense being on an object named `nvim` because you are just swapping a single character to make the equivalent call, e.g. `nvim_command` becomes `nvim.command` instead of `vim.api.nvim_command`

We're stuck with `vim.` module, trying to avoid another module (`nvim.`) because it's confusing. Let's go with `vim.a` for now and maybe revisit later.

**Comment by justinmk** [comment]
> `string.startswith`, `string.endswith` and path manipulation functions like `join/split/dirname/basename`,

In those cases I recommend creating 1 PR per function, at least initially.

**Comment by zgpio** [comment]
dict-like table filter

**Comment by stellarhoof** [comment]
The first thing I reach out for whenever I use a new language is some sort of functional library that offers things like `map`, `filter`, `reduce`, etc...

**Comment by runiq** [comment]
@stellarhoof Have you seen [this](https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/functional.lua)?

**Comment by stellarhoof** [comment]
I have seen plenary yes, but I think this is a discussion on what to ship with nvim right?

**Comment by gpanders** [comment]
`vim.g`, `vim.o`, and `vim.cmd` are implemented now. I agree that having `vim.a.*` alias to `vim.api.nvim_*` would be nice.

**Comment by clason** [comment]
(And `vim.a.*` can even do https://github.com/neovim/neovim/pull/15302.)

**Comment by justinmk** [comment]
This is mostly done. "Improve the API" is a forever-task.
