### ISSUE TITLE
Please update rust.vim

### ISSUE THREAD

**Issue by joshtriplett** [neovim/neovim#11219]
The version of rust.vim bundled with vim is very outdated, and needs updating. (Among other things, formatting no longer works with current rustfmt.) Please consider updating from the latest version at https://github.com/rust-lang/rust.vim .

- `nvim --version`: 
```
NVIM v0.3.8
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-zItjhS/neovim-0.3.8=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-zItjhS/neovim-0.3.8/build/config -I/build/neovim-zItjhS/neovim-0.3.8/src -I/usr/include -I/build/neovim-zItjhS/neovim-0.3.8/build/src/nvim/auto -I/build/neovim-zItjhS/neovim-0.3.8/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: 8.1 + patches 1-2136) behaves differently? No, the same applies to vim.
- Operating system/version: Latest Debian unstable
- Terminal name/version: gnome-terminal 3.34.2
- `$TERM`: xterm-256color

**Comment by h-michael** [comment]
@joshtriplett 
Neovim basically does not modify runtime files.
Please issue to Vim.
If runtime files are changed on the Vim side, the patch will be imported into Neovim.

**Comment by avalonv** [comment]
https://github.com/vim/vim/issues/5049

**Comment by XVilka** [comment]
It's easier to send the email to corresponding maintainers @joshtriplett, this is how it works in the Vim universe, sadly.

**Comment by chrisbra** [comment]
> this is how it works in the Vim universe, sadly.

See the mentioned upstream runtime file repository linked from the vim issue.

There is not a really better way that works. As there are literally hundreds of computer languages, we can't neither provide official syntax/ftplugin/indent scripts for each language, simply because we do not have the manpower to follow the development of all different languages and adjust the corresponding scripts. That's why there exist runtime file maintainers. They should know the language better and do also know when the scripts are considered stable (and be relatively safe to include).

If we just copy a snapshot from a random internet repository, we don't even know if the current snapshot does contain some experimental features that need to be fleshed out. (In addition just copying from the internet somewhere may have copyright/license issues).

**Comment by wsdjeg** [comment]
why just simply use vim-plug to use language specific file from language team?

**Comment by XVilka** [comment]
@wsdjeg everyone does exactly this. It makes sense to update the embedded runtime files from time to time.

**Comment by bfredl** [comment]
Tracked upstream at https://github.com/rust-lang/rust.vim/issues/326
