### ISSUE TITLE
Neovim does not support Windows DOS short filenames

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#11250]
I am using Neovim on windows and see this error message:

> E482: Can't open file C:\Users\ADMINI~1\AppData\Local\Temp\nvimlFpq84\189.vim for writing: no such file or directory

According to https://github.com/junegunn/vim-plug/issues/852, this is because Neovim can not handle DOS short filenames.

**Comment by blueyed** [comment]
Please provide more information about the Windows version being used etc.

**Comment by jdhao** [comment]
I really do not how to reproduce this reliably. It seems random.

I am using Windows 10 version 1803.

**Comment by janlazo** [comment]
It happens when the filepath is too long or needs to be escaped. Normalizing `$TEMP` may help although it's better to restore 8.3 filename support, at least for `expand` and `fnamemodify`.

**Comment by erw7** [comment]
Is this really caused by a DOS short filename? As you can see from the source, `tempname()` does not return the filename unless the parent directory of the file is successfully created on the first call. Also, `writefile()` can handle DOS short filenames normally.

The parent directory of the file returned by `tempname()` is cached, and that cache is used for subsequent calls. I think that for some reason the parent directory is deleted and this problem occurs.

#9833 is similar to this problem.

The problem that `expand()` and `fnamemodify()` doesn't expand DOS short filename seems to be unrelated to this issue, so I think we should create another issue.

**Comment by erw7** [comment]
@jdhao It is highly likely that your environment is a problem such as Windows temporary file cleanup processing of anti-virus software. Please check those settings once.

nvim also removes the temporary directory with `preserve_exit()`, but the corresponding function call is only for fatal problems such as memory allocation failure. Therefore, the possibility is low. In that case, some log may remain in the log file (default `%USERPROFILE%\nvim-data\log`?).

**Comment by jdhao** [comment]
I am using Windows 10 and I have not installed anti-virus software. This issue only happens after I open nvim-qt for a while and disappears after a restart of nvim-qt.

I looked at the log file in `%userprofile%/nvim-data` and found a lot of errors like the following:

```
ERROR 2019-09-06T14:58:42.000 9600  os_getenv:78: uv_os_getenv(LC_ALL) failed: -4075 EEXIST
ERROR 2019-09-06T15:33:16.000 9600  os_getenv:78: uv_os_getenv(LC_ALL) failed: -4075 EEXIST
ERROR 2019-09-06T15:44:12.000 9600  os_getenv:78: uv_os_getenv(LC_ALL) failed: -4075 EEXIST
ERROR 2019-09-06T17:08:15.000 9600  os_getenv:78: uv_os_getenv(LC_ALL) failed: -4075 EEXIST
ERROR 2019-09-06T17:34:35.000 9600  os_getenv:78: uv_os_getenv(LC_ALL) failed: -4075 EEXIST
ERROR 2019-09-12T09:19:43.000 29308 libuv_process_spawn:79: uv_spawn failed: no such file or directory
ERROR 2019-09-20T19:44:00.000 10320 call_set_error:622: RPC: ch 1: stream write failed. RPC canceled; closing channel
ERROR 2019-09-20T22:11:03.000 23780 call_set_error:622: RPC: ch 1: stream write failed. RPC canceled; closing channel
ERROR 2019-10-10T04:05:42.000 6500  libuv_process_spawn:79: uv_spawn failed: no such file or directory
ERROR 2019-10-10T04:05:43.000 6500  libuv_process_spawn:79: uv_spawn failed: no such file or directory
ERROR 2019-10-10T04:05:43.000 6500  libuv_process_spawn:79: uv_spawn failed: operation not permitted
ERROR 2019-10-12T04:35:42.000 18116 libuv_process_spawn:79: uv_spawn failed: no such file or directory
ERROR 2019-10-12T04:35:43.000 18116 libuv_process_spawn:79: uv_spawn failed: no such file or directory
ERROR 2019-10-12T04:35:43.000 18116 libuv_process_spawn:79: uv_spawn failed: operation not permitted
ERROR 2019-10-14T10:53:50.000 18012 libuv_process_spawn:79: uv_spawn failed: no such file or directory
ERROR 2019-10-14T10:53:50.000 18012 libuv_process_spawn:79: uv_spawn failed: no such file or directory
ERROR 2019-10-14T10:53:50.000 18012 libuv_process_spawn:79: uv_spawn failed: operation not permitted
ERROR 2019-10-15T03:13:46.000 11016 libuv_process_spawn:79: uv_spawn failed: no such file or directory
ERROR 2019-10-15T03:13:47.000 11016 libuv_process_spawn:79: uv_spawn failed: no such file or directory
ERROR 2019-10-15T03:13:47.000 11016 libuv_process_spawn:79: uv_spawn failed: operation not permitted
ERROR 2019-10-22T16:29:55.000 13580 call_set_error:622: RPC: ch 1: stream write failed. RPC canceled; closing channel
```

As you can see, there are a lot of `no such file or directory` errors which may be related to this issue. But I am not sure.

**Comment by jdhao** [comment]
It seems that vim-plug is using `tempname()` to create tmp file to write some command, as shown [here](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L369).  But somehow, the folder containing the temp file does not exist.  When using `writefile()` command to write to the temp file, an error E482 occurs.

**Comment by erw7** [comment]
> As you can see, there are a lot of no such file or directory errors which may be related to this issue. But I am not sure.

From the log, it seems that `preserve_exit()` has not been called.

The reason why an error occurs in `vim-plug` is as https://github.com/neovim/neovim/issues/11250#issuecomment-547281422. With #11284 or https://github.com/junegunn/vim-plug/issues/852#issuecomment-545714772, no error occurs in `vim-plug`. However, as explained in https://github.com/neovim/neovim/pull/11284#issuecomment-546411510
, `vim-plug` does not generate an error, but something may still be broken. Therefore, in order to solve this problem fundamentally, it is necessary to find out what is deleting the temporary directory.

It may be difficult to determine the root cause, but if you can help, try the following methods to isolate the problem.

Please create a non-zero size file in `C:\Users\ADMINI~1\AppData\Local\Temp`. Next, check if the file created when this problem occurs again is also lost. If the file you created is gone, it is likely that the cause is something other than `neovim`. If the file remains, `neovim` or `plugin` may be the cause.

**Comment by jdhao** [comment]
Do I need to create a folder under `C:\Users\ADMINI~1\AppData\Local\Temp` and then create a file or just create a file under `C:\Users\ADMINI~1\AppData\Local\Temp`?

**Comment by erw7** [comment]
Either way is fine, but I think it is enough to just create a file under `C:\Users\ADMINI~1\AppData\Local\Temp`.

**Comment by jdhao** [comment]
@erw7  I created a file named `nvim_test.txt` under `C:\Users\ADMINI~1\AppData\Local\Temp` five day ago. After all these days, it is still there.

On the other hand, there are several folders whose name starting with `nvim` when I created the temp file, now it seems that several these folders have been deleted by I-do-not-know-what tool.

Does Neovim delete these temp folders create by itself?

**Comment by justinmk** [comment]
> Does Neovim delete these temp folders create by itself?

When exiting, yes `ml_close_all` deletes the temp dir. Never before exit.

**Comment by jdhao** [comment]
Another plugin which shows error related to this issue: https://github.com/majutsushi/tagbar/issues/562.  I think the underlying cause is the same.

@justinmk , function `tempname()` only creates a string that looks like a valid path, but the actual file is not created. Is that correct?

**Comment by erw7** [comment]
> function `tempname()` only creates a string that looks like a valid path, but the actual file is not created. Is that correct?

As I wrote in https://github.com/neovim/neovim/issues/11250#issuecomment-545261166, the first call to `tempname()` creates a folder with a name like `C:\Users\ADMINI~1\AppData\Local\Temp\nvimXXXXXX` (XXXXXX is random). After that, the directory is deleted for some reason and this problem occurs.

Does `nvim_test.txt` still exist? If so, the problem is presumed to exist in nvim or plugin.

**Comment by jdhao** [comment]
@erw7  Yes, the file still exists.

![image](https://user-images.githubusercontent.com/16662357/68359700-db39c400-0157-11ea-8f99-68b575863e32.png)

Why does nvim use a cached dir instead of creating a new one so that it is sure that the dir exists?

**Comment by erw7** [comment]
> Why does nvim use a cached dir instead of creating a new one so that it is sure that the dir exists?

Perhaps it is for performance reasons. By the way, the existence of the directory has not been confirmed.

**Comment by jdhao** [comment]
> the existence of the directory has not been confirmed.

Which directory are you referring to?

**Comment by erw7** [comment]
> Which directory are you referring to?
 
It is `nvimXXXXXX`.

**Comment by jdhao** [comment]
Previously, I only created `nvim_test.txt` under `C:\Users\ADMINI~1\AppData\Local\Temp`.

Now, I create a dir named `nvimJBYV0N` and also create a file under it. I will report after a few days later whether the folder and file still exist.

**Comment by jdhao** [comment]
>  Previously, I only created nvim_test.txt under C:\Users\ADMINI~1\AppData\Local\Temp.
Now, I create a dir named nvimJBYV0N and also create a file under it

Today, when I check the directory, I find that it has been deleted. Maybe it is cleaned by the system? I am not sure.

**Comment by dundargoc** [comment]
@jdhao are you still having this problem?

**Comment by jdhao** [comment]
> @jdhao are you still having this problem?

No, I have not observed this behavior for a long time. Maybe it is because I have switched my plugin manager.

**Comment by dundargoc** [comment]
I see. Good to hear :). I assume the underlying problem fixed then. We can always reopen if it comes back again.
