### ISSUE TITLE
Lua stdlib: guidelines for raising errors

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#11311]
@norcalli suggested:

> Do we have any style guides for Lua on returning nil vs asserting inside
> a function? Idiomatic lua would return nil and maybe a message as a second
> parameter so that the caller can do `local value = assert(fn())`, which is what
> I would recommend

We should:

- Document the `local value = assert(fn())` idiom in `:help lua`
- Document guidelines in `:help lua` and/or `:help dev-lua`
- Consider this policy/guideline for the project:
  - ~~"Library functions" should "return `nil` + message". Examples: `trim()`, `first()`~~
  - **Guideline:** `assert()` or `error()` ("fail early", avoid silent/distant failure) for invalid usage (analogous to syntax error)
  - Return `nil` + message for expected failure modes (failed requests, etc.): when caller is expected to handle the failure (control-flow)

**Comment by bfredl** [comment]
> "Library functions" should "return nil + message"  Examples: trim(), first(), ...

Using `if err != nil` error handling in every single utility function would just turn the code into a mess for no gain. In general, these functions will fail because there was something wrong with the arguments the caller sent in. There is nothing a plugin really can do about such an error than fix their code so it won't happen again in the first place, so adding explicit `assert()` at every call site is just redundant.

Rather, I think should use `value, err` return for functions where we explicitly "expect the unexpected", for instance when we communicate with the external world. When doing a LSP request it is _expected_ that the server might return an error (especially when dealing with multiple unknown servers) even if we did every thing right locally.

Also, errors should not be used in lua for expected sentinel conditions. @norcalli mentioned `nvim.api.nvim_get_var` throwing an error on missing var, which is not idomatic lua for sure but rather a mismatch of API conventions (in the API every error is already "value, err" internally) with lua conventions. A new `vim.g.my_var` interface should instead return `vim.NIL` (from #11310 ) for `g:my_var = v:null` and `nil` when it is missing.

**Comment by justinmk** [comment]
updated

**Comment by norcalli** [comment]
For the record I agree with @bfredl on his refinement of the conditions and would add the summary of `If the user is using the library function wrong, that's a fatal error` as a guideline. This would include things like type errors which could go silently undetected otherwise.

**Comment by justinmk** [comment]
> add the summary of `If the user is using the library function wrong, that's a fatal error` as a guideline

I did: see "invalid usage".

**Comment by ilan-schemoul** [comment]
Hey,

I hate to be the guy not bringing much to the discussion but as it hasn't been updated in almost 5 years so I was wondering if there was any de-facto standard. I apologize if I am just adding noise but I felt that it was possible something became the de-facto standard during the 5 years.

**Comment by lewis6991** [comment]
Not sure if there's anything to be done here. Errors are called with `error` or `assert`. API's that work with an external interface (e.g. `uv`) usually return something like `nil, err` as they should be specifically handled.

**Comment by justinmk** [comment]
`:help dev-lua` now mentions:

```
  - when a result-or-error interface is needed, return `result|nil, nil|errmsg`: >
    ---@return Foo|nil # Result object, or nil if not found.
    ---@return nil|string # Error message on failure, or nil on success.
<
    - Examples: |vim.ui.open()| |io.open()| |luv-error-handling|
```

however we don't mention the `foo = assert(...)` idiom anywhere (`:help lua-guide` or `:help lua-concepts`).

**Comment by lewis6991** [comment]
Do we really need to? Our codebase uses a lot of common Lua idioms and `foo = assert(...)` is one. Why is this one special enough to document specifically?

**Comment by justinmk** [comment]
:help lua-guide or :help lua-concepts exist to introduce users to Lua idioms that we recommend.

I will address this in https://github.com/neovim/neovim/pull/30240

**Comment by telemachus** [comment]
In relation to this, can I ask here about the API for `vim.system`? Unlike `uv`, `vim.system` potentially throws an error rather than returning `result|nil, nil|errmsg`. As a result, it's a bit more complicated to use since plugin authors (I think) have to wrap any call to `vim.system` in `pcall`. (I can show an example if this isn't clear.)

Is it possible to revisit the API of `vim.system` so that it doesn't throw errors (but rather returns error messages)? Or is it too late now?

**Comment by justinmk** [comment]
> Is it possible to revisit the API of `vim.system` so that it doesn't throw errors (but rather returns error messages)?

Open a new issue. We absolutely want to get vim.system in good shape to avoid yet another variant in the future.

**Comment by lewis6991** [comment]
`vim.system` only errors if setup logic in the function itself fails for some reason. If the process launched and errors, then the return code is set. This is intentional.

**Comment by lewis6991** [comment]
It will error because the invocation of `uv.spawn` fails, and no process is spawned.

**Comment by telemachus** [comment]
> It will error because the invocation of `uv.spawn` fails, and no process is spawned.

Okay, but in the parallel case `uv.spawn` does *not* error, right? This is (for me) the sticking point. Because `vim.system` can error, it seems like many (most?) uses of it must be wrapped in `pcall`. I think that's not ideal, but I may not be seeing the larger issues or choices. In any case, it sounds like I should open a new issue to discuss this. I'll do that.

**Comment by justinmk** [comment]
> If, for example, I try to run a command that does not exist (say, I typo the name) ... that forced me to wrap everything in pcall

typos and validation errors are essentially "syntax errors" or compile-time errors. They should not be handled by pcall unless you are passing user input, but that's again a validation issue.

**Comment by lewis6991** [comment]
> Okay, but in the parallel case uv.spawn does not throw an error, right?

No it doesn't. That's a lower level function. `vim.system` is a higher level function with a different interface and specifically never returns `nil, err`. The default handlers will also cause an error if they fail to setup correctly and `obj:write` can also throw an error.

> it seems like many (most?) uses of it must be wrapped in pcall

I've used it in a large handful of plugins and never once required to use it with `pcall`. The Nvim codebase also never does this.

I'm not sure why using `pcall` is a sticking point anyway. And why can't you check if an executable is present by using `vim.fn.executable`? Then you don't have to worry about parsing whatever you get back from an error string.

**Comment by telemachus** [comment]
> typos and validation errors are essentially "syntax errors" or compile-time errors. They should not be handled by pcall unless you are passing user input, but that's again a validation issue.

> I've used it in a large handful of plugins and never once required to use it with `pcall`. The Nvim codebase also never does this.

Okay, this is helpful for me to think about. As a (prospective) plugin author, I assumed that I had to use `pcall` because otherwise the error that reaches the user is ugly and hard to decipher. What both of you say good sense to me though. If I handle the potential problem as validation (e.g., checking with `vim.fn.executable`, I should be able to catch the problem early and present it to the user more clearly.

> I'm not sure why using `pcall` is a sticking point anyway.

Probably this is subjective, but I find the `vim.system` call *already* complicated. To my eyes, the version wrapped by `pcall` is even worse. E.g.,

```lua
    local ok = pcall(
        vim.system,
        cmd,
        { text = true },
        vim.schedule_wrap(function(o)
            local stream = nil
            if l_cfg.stream == "stdout" then
                stream = o.stdout
            elseif l_cfg.stream == "stderr" then
                stream = o.stderr
            end
            on_exit(stream, title, efm)
        end)
    )

    if not ok then
        -- ...
    end
```

In any case, this sounds like it is working as intended, and I need to rethink how I handle (potential) error cases. Thanks for the feedback.
