### ISSUE TITLE
API: extmarks: unconventional indexing/inclusion

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#11456]
`:help api-indexing` says:

> Most of the API uses 0-based indices, and ranges are end-exclusive. For the end of a range, -1 denotes the last line/column.

But `nvim_buf_get_extmarks` (and `extmark_get`) follow yet another model: 0-indexed, end-_inclusive_.

If this wasn't intentional, it should be "end-exclusive" as described in `:h api-indexing`.

**Comment by bfredl** [comment]
I think the intention was that if you pass in two marks, you get all the marks in the range out, including any more marks that happen to be on the same positions as the start and the end. 

But rather than column indexing being "end-inclusive" or "end-inclusive" with marks, I prefer to think that  extmarks are on the space _between_ chars (i e they behave more like a insert mode cursor than a normal mode cursor "covering" one char). so col=0 refers to point before the first char and col=2 just after the second char. then it is clear that `text[col=0:col=2]` contains two bytes of text, and reasonable (if perhaps not necessary) that `get_extmarks(.., [line,0], [line,2])` also returns marks at offset `col=2`.

**Comment by norcalli** [comment]
The "space between chars" explanation is the only thing that has made it make sense to me this whole time and I wish I read it before I started using them.

**Comment by bfredl** [comment]
Yeah. My mindset there was a bit different than Tim's, and also the implementation is quite messy because of this. I hope to make it clearer in my next refactor (which also will properly support mark "graivity" and the like)

**Comment by justinmk** [comment]
> rather than column indexing being "end-inclusive" or "end-exclusive" with marks, I prefer to think that extmarks are on the space _between_ chars

So we can't avoid this extra "indexing model". Then just need to express this at `:h api-indexing`
