### ISSUE TITLE
b:undo_ftplugin settings breaks plugin using it

### ISSUE THREAD

**Issue by hupfdule** [neovim/neovim#11478]
- `nvim --version`: NVIM v0.4.2
- `vim -u DEFAULTS` (version: 8.1 (1-2135) and 8.1 from Debian Buster) behaves differently? yes
- Operating system/version: Debian Buster
- Terminal name/version: urxvt-256color
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"

```

- Install and enable [the vim-asciidoc-ng plugin](https://github.com/hupfdule/vim-asciidoc-ng) (still in development)
- Open an asciidoc file (e.g. the README.adoc in the plugins homedirectory).

### Actual behaviour

You will get the following error messages:
![nvim-errors](https://user-images.githubusercontent.com/36069345/69860449-973d6900-1296-11ea-89f2-b7ee1464d8a0.png)

So apparently neovim tries to load the vim-asciidoc-ng ftplugin twice. The second time it fails to define the commands as they are already defined.¹ 

What is causing that problem is the variable `b:undo_ftplugin`. See https://github.com/hupfdule/vim-asciidoc-ng/blob/2aa6fbe9c9996a1d33df99909984ba1b20f042b1/ftplugin/asciidoc.vim#L110-L114

If `b:undo_ftplugin` at line 114 is set (whether empty or with a valid content), the problem described above appears. If I remove that line, the errors don't show up.

This problem doesn't exist in vim.

[¹] Interestingly if I try to verify this via `echom "vim-asciidoc-ng ftplugin loaded"` command, the output of this command doesn't appear at all. Not before the above mentioned error list and not when calling `:messages`. It doesn't even make a difference, whether the errors, that are caused by `b:undo_ftplugin`, appear or not (meaning: whether `b:undo_ftplugin` is set or not).

### Expected behaviour

The ftplugin should load once as expected and don't throw any errors about commands being already defined as the plugin sets and checks the `b:did_ftplugin` variable.

**Comment by blueyed** [comment]
JFI already:
> Interestingly if I try to verify this via `echom "vim-asciidoc-ng ftplugin loaded"` command, the output of this command doesn't appear at all.

You can use `unsilent echom` for that or `set shortmess-=F` (IIRC).

**Comment by hupfdule** [comment]
Thank you!

`unsilent echom` didn't work, but `set shortmess-=F` did.

And I can see now that the plugin is loaded only once when `b:did_ftplugin` is unset.
If I set it, the plugin is loaded twice.

**Comment by justinmk** [comment]
> So apparently neovim tries to load the vim-asciidoc-ng ftplugin twice. The second time it fails to define the commands as they are already defined.¹

What do you mean by "load"? ftplugins, and plugins in general, are explicitly required to handle redundant loads. This is in Vim's own `:help :packloadall`:

>  when using :packloadall in the vimrc file, the 'runtimepath' option is updated, and later all plugins in 'runtimepath' will be loaded, which means they are loaded again.  Plugins are expected to handle that.

Typically this is done by a `g:loaded_foo` variable.

**Comment by hupfdule** [comment]
> > So apparently neovim tries to load the vim-asciidoc-ng ftplugin twice. The second time it fails to define the commands as they are already defined.¹
> 
> What do you mean by "load"? 

Apparently the same as you do.

> ftplugins, and plugins in general, are explicitly required to handle redundant loads. This is in Vim's own `:help :packloadall`:
> 
> > when using :packloadall in the vimrc file, the 'runtimepath' option is updated, and later all plugins in 'runtimepath' will be loaded, which means they are loaded again.  Plugins are expected to handle that.
> 
> Typically this is done by a `g:loaded_foo` variable.

And this is done: https://github.com/hupfdule/vim-asciidoc-ng/blob/2aa6fbe9c9996a1d33df99909984ba1b20f042b1/ftplugin/asciidoc.vim#L8-L11
And as mentioned the problem only appears, when the plugin defines `b:undo_ftplugin`. 
 
> > This problem doesn't exist in vim.
> 
> Nvim enables plugins/syntax automatically, perhaps your vimrc has a redundant `:filetype ...` command in it. 

I don't think it has anything to do with my `.vimrc`. After all, as is mentioned in the above issue, the same problem exists with `nvim -u NORC`.
 
> Without minimal repro steps, I can only guess.

Actually I gave those. The above mentioned plugin clearly shows the problem. Comment line 114 out and the problem is gone. Comment it in and the problem is back again.

As long as you have the above mentioned plugin downloaded to your packpath, do:

```
nvim -u NORC
:packadd vim-asciidoc-ng
:e {PATH_TO_vim-asciidoc-ng}/README.adoc
```

**Comment by lacygoill** [comment]
> So apparently neovim tries to load the vim-asciidoc-ng ftplugin twice.

That's because you set the filetype [unconditionally](https://github.com/hupfdule/vim-asciidoc-ng/blob/2aa6fbe9c9996a1d33df99909984ba1b20f042b1/ftdetect/asciidoc.vim#L12):

    au BufRead,BufNewFile *.asciidoc,*.adoc,*.ad set filetype=asciidoc
                                                 ^^^^^^^^^^^^

Nvim already sets the filetype here:

https://github.com/neovim/neovim/blob/bc879dd1f163b8eac3955baee5ed5792d906e98c/runtime/filetype.vim#L128

If you set the filetype a second time, then the filetype plugins are sourced twice.

You need to set the filetype on the condition that it has not already been done:

    au BufRead,BufNewFile *.asciidoc,*.adoc,*.ad setf asciidoc
                                                 ^^^^

> What is causing that problem is the variable b:undo_ftplugin.

When `b:undo_ftplugin` is set, (N)Vim automatically removes `b:did_ftplugin` as soon as the filetype is set. It's necessary to allow the new filetype plugins to be sourced when you change the filetype from A to B. If `b:did_ftplugin` was not removed, the B filetype plugins could not be sourced.

You can remove the commands which raise an error by including a `:delcommand MyCmd` for each command defined in your filetype plugin.

> This problem doesn't exist in vim.

The error messages were still raised in Vim up to [8.1.0573](https://github.com/vim/vim/releases/tag/v8.1.0573). Starting from this patch, it's allowed to redefine a user command without appending a `!` to the command name.

The patch has not been ported to Nvim yet:

    $ ./scripts/vim-patch.sh -l 2>/dev/null | grep 8.1.0573
      • v8.1.0573: cannot redefine user command without ! in same script

But it will be, as soon as the [PR 11318](https://github.com/neovim/neovim/pull/11318) is merged.
In the meantime, you need to append a `!` to each of your command names.

**Comment by hupfdule** [comment]
OK. Thanks.

Didn't know about `setf`, actually.
