### ISSUE TITLE
Vim patches: window-toolbar (winbar)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#11513]
I've noticed that https://github.com/vim/vim/commit/1b9645de3c05f37b5c30e78f999351b0cf486ade (v8.0.1123) has not been merged yet, and wondered if that is something we a) want, and b) how difficult it is to port/merge?  /cc @bfredl

**Comment by bfredl** [comment]
I don't think it collides too much with things we have changed. I remember discussing with @justinmk if we wanted this but I don't recall exactly our conclusion.

But disregarding vim compat for a moment, the underlying implementation code for tabline/statusline already allows you to define a line region with arbitrary clickable "fieds" (though we haven't enabled it for statusline), an option would be to use that instead to define an additional window "bar" that both can display information and accept clicks (would be usable for floats also).

**Comment by justinmk** [comment]
> the underlying implementation code for tabline/statusline already allows you to define a line region with arbitrary clickable "fields" (though we haven't enabled it for statusline)

good idea, forgot about that (Nvim-only feature). For reference: #3871 

Regarding https://github.com/vim/vim/commit/1b9645de3c05f37b5c30e78f999351b0cf486ade :

- There might be some useful stuff there, e.g. the non-winbar changes to `menu.c` (`ex_emenu`, execute menu). But the `screen.c` changes should be skipped IMO.
- WinBar is a feature that no one will use because it's so incomplete (similar to 'ballooneval'). So we don't need to imitate it. 

## Proposal 

Instead, a _very_ high-value feature we should focus on is the ability to generate graphical menus from a `:menu` definition. We already have all of the pieces needed to do this **in Lua**:

1. Vim's `:menu` allows defining hierarchical menus
2. `menu_get()` returns a dict of any `:menu` tree
3. The `menu_get()` result can be walked by some Lua logic which builds floating-windows that imitate graphical menus.
4. ???
5. profit

**Comment by bfredl** [comment]
> But the screen.c changes should be skipped IMO. WinBar is a feature that no one will use because it's so incomplete (similar to 'ballooneval'). So we don't need to imitate it.

Though what I had in mind was to _do_ screen.c changes, but a much smaller (as in: reuse existing code) and more powerful one: We could add a `winbarline` option with the same "syntax" as generic 'tabline' (i e arbitary clickable functions instead of actual tabs). This would be the _complete_ feature instead of imitating the incomplete one. We might even be able to "polyfill" the `amenu WinBar` command back to 'winbarline' changes, if we have a lua listener to menu definition changes, which would compliment lua building floats for submenus quite nicely. (though chances are plugins will rather want to `has('nvim')` our more powerful interface directly then).

**Comment by Vftdan** [comment]
Floating window sounds like a good solution, but it will overlay either the first line of text or the tabline/statusline above the split. It could be a good idea to create a strut inside the split (maybe something like `'signcolumn'`, but line).

**Comment by bfredl** [comment]
sure, as the "inner" size of a window is now fully decoupled from the size it occupies in the split hierarchy, allocating space for floats (or perhaps a separate "docked" relative positioning mode?) on any size of the window should be feasible.

**Comment by justinmk** [comment]
for reference: https://github.com/neovim/neovim/issues/12925
