### ISSUE TITLE
:tabnew will auto enter insert mode in some circumstances

### ISSUE THREAD

**Issue by epheien** [neovim/neovim#11518]
- `nvim --version`: NVIM v0.4.2
- `vim -u DEFAULTS` (version: ) behaves differently? no
- Operating system/version: macOS 10.13.6
- Terminal name/version: iTerm2 3.2.8
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:terminal<CR>
:autocmd WinEnter <buffer> startinsert<CR>
:tabnew<CR>
```

### Actual behaviour
enter insert mode
### Expected behaviour
in normal mode

screenshots: https://asciinema.org/a/285451

**Comment by justinmk** [comment]
related: https://github.com/neovim/neovim/issues/7254

**Comment by justinmk** [comment]
> vim -u DEFAULTS (version: ) behaves differently? no

It's tricky.  `:help WinEnter ` says:

> If the window is for another buffer, Vim executes the BufEnter autocommands after the WinEnter autocommands.

`:startinsert` is invoked on the new tab because because `:tabnew` switches to a blank/new buffer after first visiting the original `<buffer>`. (Notice what `:echo @#` reports after `:tabnew`.)

This isn't really a bug. Feel free to report it to https://github.com/vim/vim , we aren't going to change subtle order-of-operations like this without a strong motivation.
