### ISSUE TITLE
Escape sequence sent from iTerm interpreted incorrectly

### ISSUE THREAD

**Issue by badfilms** [neovim/neovim#11554]
- `nvim --version`:  v0.4.3
- `vim -u DEFAULTS` (version: 8.1.2400) behaves differently? Yes.
- Operating system/version: macOS 10.15.2
- Terminal name/version: iTerm 3.3.7
- `$TERM`: xterm-256color

I have my `vimrc` set to map a custom escape sequence sent from iTerm to allow both `<TAB>` and `<C-i>` to have appropriate functionality. In porting to Nvim, this no longer works without an additional mapping.

### Steps to reproduce using `nvim -u NORC`

- Map _Key Combination `^i` : Send Escape Sequence `^[i`_ in iTerm.
- `nnoremap <C-[>i <C-i>`

### Actual behaviour
`<C-v><C-i>` is `<M-i>` when ran in insert mode in Nvim.
`<C-v><C-i>` is `^[i` when ran from Nvim's `:terminal`.

### Expected behaviour
The sequence should be `^[i`, as it is in Vim, iTerm, and the Nvim `:terminal`.

There are similar, albeit old, discussions: https://github.com/neovim/neovim/issues/2673 https://github.com/neovim/neovim/issues/2048.

**Comment by justinmk** [comment]
> The sequence should be `^[i`, as it is in Vim, iTerm, and the Nvim `:terminal`.

No it shouldn't. It should be META/ALT. Otherwise META/ALT would require the opposite workaround, which is a far more common scenario than the sequence you happened to choose in iTerm2 (you could choose literally anything, why choose ESC-i ?).

Meanwhile, you could also do this:

    nnoremap <M-i> <C-i>

Related: https://github.com/neovim/neovim/issues/6279 is more robust solution.
