### ISSUE TITLE
getchar() can not detect cmd-v on MacOS

### ISSUE THREAD

**Issue by Yggdroot** [neovim/neovim#11551]
- `nvim --version`: 0.43
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version:
- Terminal name/version:
- `$TERM`:

**Describe the bug**

getchar() can not detect cmd-v on MacOS

**To Reproduce**

1. vim
2. `:echom getchar() == "\<D-v>"`
3. press cmd+v

**Expected behavior**
outputs 1

**Comment by justinmk** [comment]
The terminal is relevant ..

**Comment by obxhdx** [comment]
Terminal is iTerm2, Build 3.3.7. Value of `$TERM` is `xterm-256color`.

**Comment by justinmk** [comment]
cmd-v is never sent to Nvim nor Vim, it is handled by the terminal which then simply streams raw input to stdin.

>  `vim -u DEFAULTS` (version: ) behaves differently? yes

That's not possible, unless you have your terminal configured to send a special sequence, or _possibly_ if this is somehow supported by S8C1T mode https://github.com/neovim/neovim/issues/6279 .

Closing since no one provided the above details.
