### ISSUE TITLE
load gui colors from xresources

### ISSUE THREAD

**Issue by Kyle-Thompson** [neovim/neovim#11569]
All the colors I use in neovim are defined in my .Xresources file. As a result I currently define highlight groups with cterm{fg,bg}. This setup works well until I try to use it with the pumblend option. This option seems to only function properly if termguicolors is enabled which is something I don't have at the moment. As a result, is it possible to enable termguicolors and still load values from my Xresources file? Or perhaps force the cterm options to be used when specified in a highlight group.

**Comment by bfredl** [comment]
`Xresources` support in core is out of scope. You can write a vimL or lua plugin which parses your Xresources and changes your `:hi` definitions.

>  Or perhaps force the cterm options to be used when specified in a highlight group.

This would require some kind of translation. We could use the libvterm internal table for this. Unfortunately there are two different 255 color schemes which are competing for being the "standard" one (linear vs scaled color ramp), so regardless what we do, half of the users wanting this feature will think nvim uses objectively wrong colors and open a neverending stream of duplicate issues like "nvim is broken because it does not use correct terminal colors". So I think this usecase is also better served by a plugin. We could add a lua API for reading and setting `:highlight` groups, then such a plugin can be written in a few lines.
