### ISSUE TITLE
apt-get is installing an old version.

### ISSUE THREAD

**Issue by extremepayne** [neovim/neovim#11615]
- `nvim --version`: `0.1.7`
- Operating system/version: Chrome OS 79.0.3945.86
- Terminal name/version: Default terminal on chrome with Linux beta enabled, don't know how to check the version. It's probably interdependent on the ChromeOS version anyway.
- `$TERM`: xterm-256color

### Steps to reproduce <del>using `nvim -u NORC`</del>
Enable linux. Start the terminal.
```
apt-get install neovim
nvim --version
```

### Actual behaviour
Version 0.1.7 installed
### Expected behaviour
Version  0.4.3 installed

I need a newer version of neovim for obvious reasons. Most pressing is I use ALE, which requires a new-ish version. 

What really worries me is a previous issue (not by me) (https://github.com/neovim/neovim/issues/9370) was closed with 
> We don't manage your OS package manager, not to mention you didn't say the version of your OS, nor even what OS you're using.

1. This issue states an OS and version.
2. Correct me if I'm wrong, but maintainers have _some_ sort of control over what version is shipped? At least with `apt`? I know some package managers are controlled by a separate entity who updates at their own whims, but is that really how `apt` works?

Please offer some help. 

(Or, alternatively, building an ARM AppImage would suffice for my use case.)

**Comment by justinmk** [comment]
>  maintainers have _some_ sort of control over what version is shipped? At least with `apt`?

No. Same response as #9370.

Note that we push daily updates to "snap":

https://github.com/neovim/neovim/wiki/Installing-Neovim#snap

There is also "flatpak": 

https://github.com/neovim/neovim/wiki/Installing-Neovim#flatpak

There is also AppImage:

https://github.com/neovim/neovim/releases

**Comment by extremepayne** [comment]
Okay, thanks for clarifying. Is there any chance you'll build for ARM
architecture?

**Comment by extremepayne** [comment]
Oh sorry looks like you edited and it didn't show in the email. Yeah, I'll try that, and perhaps flatpak as well, though it looks like I can't use snap.

**Comment by Espenol** [comment]
So if I get the appimage doing so: 
```
curl -L https://github.com/neovim/neovim/releases/download/stable/nvim.appimage /tmp/nvim.appimage
sudo mv /tmp/nvim.appimage /usr/local/bin/nvim
chmod u+x /usr/local/bin/nvim
```
then when I run `nvim` in shell I get the following error message:
```
/usr/local/bin/nvim: line 1: Not: command not found
```
Does anyone have an idea what is causing this? If I get neovim using `apt install neovim` I can start it just fine, but it is a too old version for my needs.

Running ubuntu 18.04

**Comment by glacambre** [comment]
First, make sure `nvim` is `/usr/local/bin/nvim` by running `which 
nvim`. If this doesn't result in `/usr/local/bin/nvim` being printed, 
you have a $PATH issue and should move `/usr/local/bin/nvim` to 
somewhere else, like `/usr/bin` for example.

Then, make sure `nvim` is a binary by running `file 
/usr/local/bin/nvim`. If this doesn't print `ELF 64-bit LSB executable, 
x86-64`, the binary is corrupted. Try downloading again by clicking on 
the link here: https://github.com/neovim/neovim/releases/tag/stable .

Make sure it was downloaded in its entirety by running `ls -lh 
/usr/local/bin/nvim`, this should tell you that `/usr/local/bin/nvim` is 
around 10 MB, if it isn't, download neovim again by clicking on the link 
here: https://github.com/neovim/neovim/releases/tag/stable .

Make sure the problem doesn't come from your configuration by running 
`/usr/local/bin/nvim -u NORC -i NONE`. If neovim works fine with NORC, 
the problem is in your init.vim and you should remove lines from it 
until neovim can start again.
