### ISSUE TITLE
virtualtext: right align

### ISSUE THREAD

**Issue by pwntester** [neovim/neovim#11634]
Follow up from https://github.com/neovim/neovim/issues/11630:

> I think we should implement this natively in screen.c. I'm currently working on refactoring the implementation, after that we should add new display modes for virtual text.

**Comment by AdamWagner** [comment]
I'm sure other folks have realized this, but I was able to right-align virtualtext locally by changing [line 776 in diagnostic.lua](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/diagnostic.lua#L776) from `local spacing = opts.spacing or 4` to the simple function below:

```
local spacing = (function()
    local current_line = vim.api.nvim_buf_get_lines(bufnr, line, line +1, false)[1]
    return 80 - #current_line
end)()
```
<img width="1074" alt="Screenshot 2021-06-05 at 13 28 20@2x" src="https://user-images.githubusercontent.com/1683979/120904613-ec7fd680-c601-11eb-8cbc-aacaea5c49f5.png">

**Comment by bfredl** [comment]
There's also the `right_align` flag in the API :D

**Comment by AdamWagner** [comment]
> There's also the right_align flag in the API :D
Well, gee, thanks! Clearly _that's_ better than modding the runtime! 
I'll dig closer next time ;-)

**Comment by f-person** [comment]
> There's also the right_align flag in the API :D

@bfredl Is it not documented?

**Comment by andersevenrud** [comment]
@f-person This only seems to be available for [`nvim_buf_set_extmark`](https://github.com/neovim/neovim/blob/68d40388f356587726ea7db83f87846dfaecf9d9/runtime/doc/api.txt#L2259) and not [`nvim_buf_set_virtual_text`](https://github.com/neovim/neovim/blob/68d40388f356587726ea7db83f87846dfaecf9d9/runtime/doc/api.txt#L2426)

@bfredl An issue with the `right_align` flag is that when the virutal text becomes very long it can actually overlap the text:

One issue 
![2021-06-07-012304_3840x2160_scrot](https://user-images.githubusercontent.com/161548/120943760-387d6900-c731-11eb-984c-42717a160a6f.png)

I feel like there should be an option where it aligns as far to the right as possible, but crops the text in order to avoid this overlapping. I was about to file another issue on this, but maybe just re-opening and editing this would be better ?

**Comment by danielyli** [comment]
@AdamWagner What Unicode character is that prefix? (The X in a filled circle)

**Comment by awused** [comment]
I think this should be reopened since the right_align flag isn't exposed on the [nvim_buf_set_virtual_text](https://github.com/neovim/neovim/blob/68d40388f356587726ea7db83f87846dfaecf9d9/runtime/doc/api.txt#L2426) method. Additionally it doesn't work correctly with longer text.

**Comment by awused** [comment]
That label change seems incorrect, since this is an issue primarily with `virtualtext` and `extmarks` only tangentially.

**Comment by clason** [comment]
Those are the same thing.

**Comment by awused** [comment]
They may be implemented the same way under the hood, but the APIs are separate and only one of them exposes the flag (which doesn't fully work).
