### ISSUE TITLE
shada with const

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#11681]
- `nvim --version`:v0.5.0-297-g83b0054b8
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version:macos
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

t_const.vim
```
const g:FOO = 1
```
1. `nvim -u t_const.vim`
2. `:q`
3. `nvim -u t_const.vim`

### Actual behaviour
`E741: Value is locked: FOO`

### Expected behaviour
`no error`

**Comment by justinmk** [comment]
Cannot reproduce in Vim 8.2.96 and I don't see a related patch. 

This happens because shada is loaded _after_ user config (`-u`, `:help startup`).  So this patch doesn't help:

```diff
diff --git a/src/nvim/shada.c b/src/nvim/shada.c
index 2306da94c6d9..561477fb8607 100644
--- a/src/nvim/shada.c
+++ b/src/nvim/shada.c
@@ -1339,6 +1339,7 @@ static void shada_read(ShaDaReadDef *const sd_reader, const int flags)
         break;
       }
       case kSDItemVariable: {
+        cur_entry.data.global_var.value.v_lock = VAR_UNLOCKED;
         var_set_global(cur_entry.data.global_var.name,
                        cur_entry.data.global_var.value);
         cur_entry.data.global_var.value.v_type = VAR_UNKNOWN;
```

That `var_set_global` call does  `set_var_const ... tv_check_lock`.

Not sure what to do here. Imagine if a plugin sets such a variable to const, should shada/viminfo just bulldoze it?

**Comment by zgpio** [comment]
It seems no error when change `const g:FOO = 1` to `const g:Foo = 1`.

**Comment by justinmk** [comment]
> It seems no error when change `const g:FOO = 1` to `const g:Foo = 1`.

That's because `g:Foo` is not stored in shada, see `:help shada-!`.
