### ISSUE TITLE
startup: wait for stdioopen() ?

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#11718]
Normally with `--embed` Nvim waits for the UI, in order to avoid the issue reported here. 

- https://github.com/neovim/neovim/wiki/Following-HEAD#20180922 
- `:help --embed`

And with `--headless` Nvim does _not_ to wait for UI to connect (because "headless" implies "no UI"). 

But some UIs like [firenvim](https://github.com/glacambre/firenvim/issues/350) use `--headless` + `stdioopen()`.

Maybe it makes sense for `--embed --headless` to wait for `stdioopen()`?

**Comment by glacambre** [comment]
If I'm understanding things correctly, `stdioopen()` would be to `--embed --headless` what `nvim_ui_attach()` is to `--embed`. Is that right?

If it is, I'm not sure this would help with the issue that spawned this discussion (`Press enter to continue` messages blocking startup). From what I gathered, `--embed` makes Neovim wait until `nvim_ui_attach()` is called before loading `init.vim`. But the Firenvim Neovim plugin needs to be loaded by `init.vim` in order to be able to call `stdioopen()`, so we have a circular dependency.

One solution to this problem could be to have Firenvim bypass the user's plugin manager and load itself with `-c 'set rtp+=/path/to/firenvim'`. It could set up a `VimEnter` autocommand, use `stdioopen()` to make Neovim load `init.vim` and then on `VimEnter` read the user's config and write an appropriate answer to `stdout`. But will `VimEnter` ever be triggered if a `Press enter to continue` message is triggered in `init.vim`? Also, I don't like the idea of bypassing the user's plugin manager.

I think a proper solution would be to have a way to tell Neovim "I can't press Enter for now, please don't block on errors and messages and treat `:confirm` and other messages that require user input as an error". Users could then use `:messages` to see what happened in their `init`.vim. I don't know how complex implementing such a feature would be and if it's worth it.

**Comment by bfredl** [comment]
@justinmk I do not think this makes any sense. The difference between `--embed` and `--embed --headless` that was introduced is that `--embed` does wait for the embedder and `--embed --headless` does not wait. Also `nvim_ui_attach` is an RPC event, whine `stdioopen()` is just an internal function call. It does not make any sense to "wait" for it because it will be invoked by synchronous in-process initialization code (like `--cmd` anyway).

**Comment by bfredl** [comment]
@glacambre I think firenvim should try to set up its communication earlier than `VimEnter`. What I would suggest is to change `-c 'call firenvim#run()'` to `--cmd 'call firenvim#run()'` effectively (which will require more changes). If you don't want to change the rtp, you could source the relevant .vim and .lua files manually (though the cmdline will be longer then). This will ensure `server_start()` and the rest of it is run _before_ any user errors from init.vim.

**Comment by glacambre** [comment]
>This will ensure server_start() and the rest of it is run before any user errors from init.vim

I think I can't do this because `server_start()` needs configuration options that are set by users in their init.vim.

**Comment by bfredl** [comment]
@glacambre are you sure about this? I don't see where options come in in `firenvim#run()` or `firenvim_start_server`. Could these options be specified somewhere else? Everything becomes much simpler if we can start the UI before sourcing `init.vim` ...

Though what I suggested might not work directly either, because `OnStdin` callback will be blocked. It would require opening stdio from lua/luv instead and processing the json in a luv callback. (I think this should work, if `stdioopen()` is not called, then nvim should not read stdin by itself. But if it doesn't we will fix this for 0.5).

**Comment by glacambre** [comment]
>are you sure about this?

Yes. Firenvim currently needs to return settings along with the [port number](https://github.com/glacambre/firenvim/blob/master/autoload/firenvim.vim#L100-L113) opened by `server_start`. The new [persistent server](https://github.com/glacambre/firenvim/blob/1975faa582113b0784812eef12cc3a8b56ac94db/lua/firenvim.lua#L96) feature that isn't merged yet will also require `g:firenvim_config` to exist.

>Could these options be specified somewhere else?

The way they're currently specified is ideal from a user point of view in my opinion. They could be specified in another file (e.g. `firenvim_init.vim`) sourced by the plugin but this would make setting up Firenvim worse than the current way of doing things.

>Everything becomes much simpler if we can start the UI before sourcing init.vim

In Firenvim, writing to stdout is different from starting the UI. We write to stdout to let Firefox know what port it can connect on, and then wait for Firefox to connect a UI (this might happen hours later). So even if Firenvim was loaded before `init.vim`, Neovim wouldn't be able to assume a UI exists.

**Comment by bfredl** [comment]
Ok, so we need to collect messages in `init.vim` then. Probably we could use `ext_messages` internally in `--headless` mode and collect messages, and provide some mechanism the embedder can use to check if there was any startup messages (and display them to the user in some reasonable way).
