### ISSUE TITLE
Syntax highlighting error with initializer lists in CUDA

### ISSUE THREAD

**Issue by gridley** [neovim/neovim#11767]
### Actual behaviour

Should not get error-style highlighting on initializer lists when writing cuda code. This appears as follows:

![2020-01-26-134042_563x103_scrot](https://user-images.githubusercontent.com/18088906/73139950-7f3d5800-4041-11ea-955e-3ac0b59a9d7f.png)

### Expected behaviour

Not red whenever I use an initializer list.

### To reproduce

Using the latest neovim 0.5, open any .cu file, and paste in:

```c++
int main()
{
   std::vector<double>({1.0, 2.0});
}
```

or the like. Then you get red error highlighting, even though nothing is wrong.

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim.

Syntax plugins (e.g. for ruby/java/YAML) are maintained by the maintainer listed at the top of the plugin file. Please report to that person, or to https://github.com/vim/vim. Thanks!
