### ISSUE TITLE
Neovim hangs on `:qall!` if tcp server is started

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#11820]
- `nvim --version`: NVIM v0.5.0-ead61e5a5
- Operating system/version: Linux 5.0.0-37-generic 40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 GNU/Linux

### Steps to reproduce using `nvim -u NORC`

Source the lua example available in `:help tcp-server` and then run `:qall!`.

### Actual behaviour

Neovim hangs.

### Expected behaviour

Neovim doesn't hang.

The issue can be made to disappear with this patch:
```patch
diff --git a/src/nvim/main.c b/src/nvim/main.c
index 56d9030a7..e2a60e0c2 100644
--- a/src/nvim/main.c
+++ b/src/nvim/main.c
@@ -181,7 +181,7 @@ bool event_teardown(void)
   signal_teardown();
   terminal_teardown();

-  return loop_close(&main_loop, true);
+  return loop_close(&main_loop, false);
 }

 /// Performs early initialization.
```

This might be related to #7376.

**Comment by justinmk** [comment]
Yeah, re-reading libuv docs, `UV_RUN_DEFAULT` seems wrong in `loop_close`. 

- Q: why it was ever like that (since the beginning, 991d3ec1e679)?
- A: Because: libuv maintainers recommend it: https://stackoverflow.com/q/25615340/152142
  - But we aren't doing `uv_walk .. uv_close` as recommended there, so it seems possible that `UV_RUN_DEFAULT` has nothing to do and hence blocks forever.

So quick fix is to always `UV_RUN_NOWAIT`. But maybe better fix is to `uv_walk .. uv_close`, and also, yes, #7376 has been tragically neglected and needs a review.
