### ISSUE TITLE
Can't ctrl-L ctrl-G etc. to complete from buffer in / and :s/

### ISSUE THREAD

**Issue by theonlygusti** [neovim/neovim#11844]
- `nvim --version`:0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently? yes
- Operating system/version: macOS Catalina 
- Terminal name/version: Terminal.app
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
ienter some text
into the file
which we will search for search search
search<ESC>:set incsearch
gg:%s/sea<C-l>
```

### Actual behaviour

Types a `^L` into the command line

### Expected behaviour

Like VIM, should autocomplete the `r` from the next `search`. See https://vi.stackexchange.com/a/22821/9024 or `:help /_CTRL-L`

Similarly, CTRL-G doesn't work, CTRL-H neither.

**Comment by justinmk** [comment]
That's a pretty recent Vim feature. 

If it's fixed then it still can't ever be fixed on older versions of Nvim. That's why we ask to try the current development version before reporting an issue.

CTRL-L definitely works in Nvim 0.5, though I don't remember if it was in Nvim 0.4.3.

No idea what ctrl-h/ctrl-g are supposed to do, you should link to the relevant Vim `:help` or commit.

Closing this since we don't track every Vim feature, we simply merge Vim features as soon as someone sends a PR. 
https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim
