### ISSUE TITLE
checkhealth/perl: check for "Neovim::Ext" is broken

### ISSUE THREAD

**Issue by bertilow** [neovim/neovim#11858]
- `nvim --version`: v0.5.0-370-g5d5b068d5
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Kubuntu 19.10
- Terminal name/version: Konsole
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

run "checkhealth"

### Actual behaviour

Reports:

## Perl provider (optional)
  - INFO: Perl: v5.28.1
  - INFO: Nvim perl host: /usr/local/bin/perl
  - WARNING: Module "Neovim::Ext" is out-of-date. Installed: 0.02, latest: 5.28.1
    - ADVICE:
      - Run in shell: cpanm Neovim::Ext

### Expected behaviour

Not complaining since the latest version of "Neovim::Ext" is in fact 0.02. The version number reported as latest is the Perl version number. The version numbers seem to get mixed up.

Running "cpanm Neovim::Ext" gives "Neovim::Ext is up to date. (0.02)"

**Comment by justinmk** [comment]
If you know how to fix it, send a PR or share a patch here. The current check was an initial attempt merged recently, and we need perl/cpan users to say a better way to get this info.

The logic is here: https://github.com/neovim/neovim/blob/58ec72f9fdfd186e5154ce82be1da7c65b9c8ea0/runtime/autoload/health/provider.vim#L682

it uses shell commands such as `cpan` to attempt to get version info.

**Comment by bertilow** [comment]
I'm not sure how to fix it, but I did find the cause.

The command "cpanm --info Neovim::Ext" is supposed to return "JACQUESG/Neovim-Ext-0.02.tar.gz" and then extract the version from that.

But what is actually returned is this:

!
! Can't write to /usr/local/share/perl/5.28.1 and /usr/local/bin: Installing modules to /home/bertilow/perl5
! To turn off this warning, you have to do one of the following:
!   - run me as a root or with --sudo option (to install to /usr/local/share/perl/5.28.1 and /usr/local/bin)
!   - Configure local::lib in your existing shell to set PERL_MM_OPT etc.
!   - Install local::lib by running the following commands
!
!         cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
!
JACQUESG/Neovim-Ext-0.02.tar.gz

And there the Perl version comes first and is caught by the command "let latest_cpan = matchstr(latest_cpan, '\(\.\?\d\)\+')".

To get the expected return you'd have to run "cpanm --info" with "sudo", but that is of cause not feasible.

But the "matchstr" part can probably be modifed, perhaps something like: "let latest_cpan = matchstr(latest_cpan, 'Neovim-Ext-\(\.\?\d\)\+')".
My vimscript skills are not very good, so I can't be sure have to actually write that last part.

**Comment by janlazo** [comment]
The hint is right there in the error message

```
!   - Configure local::lib in your existing shell to set PERL_MM_OPT etc.
!   - Install local::lib by running the following commands
!
!         cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
```

If `local::lib` is installed and setup correctly by running the `eval` command in the shell's startup (ie. `~/.bashrc`) to define perl environment variables, then `cpanm` will not need sudo to not error out. `sudo` here won't work on Windows so the recommendation should be to setup `local::lib` for the current user.

Alternative is to recommend perlbrew or plenv to install a different perl version  that does not need sudo to install packages.

The rest of code for dealing with version numbers should be fine but the warning from cpanm should be suppressed if possible in order to not complicate the version parsing and the error code/message should be checked before continuing on the next shell command.
