### ISSUE TITLE
Buffer opened as insert mode when splitting from a terminal with "WinEnter startinsert"

### ISSUE THREAD

**Issue by igrep** [neovim/neovim#11850]
- `nvim --version`:  
  ```
  NVIM v0.5.0-305-g29b1a4761
  Build type: RelWithDebInfo
  LuaJIT 2.1.0-beta3
  Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/yu/tmp/neovim/build/config -I/home/yu/tmp/neovim/src -I/home/yu/tmp/neovim/.deps/usr/include -I/usr/include -I/home/yu/tmp/neovim/build/src/nvim/auto -I/home/yu/tmp/neovim/build/include
  Compiled by yu@debian

  Features: +acl +iconv +tui
  See ":help feature-compile"

        システム vimrc: "$VIM/sysinit.vim"
         省略時の $VIM: "/usr/local/share/nvim"
  ```
- `vim -u DEFAULTS` (version: 8.1.1401) behaves differently?
    - Yes. `vim` doesn't reproduce.
- Operating system/version:
    - According to `uname -a`: `Linux debian 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux`
- Terminal name/version: `mintty 2.9.5 (x86_64-pc-msys)` (I run `nvim` via ssh from Windows 10).
- `$TERM`: `screen`

### Steps to reproduce using `nvim -u NORC`

1. Launch nvim
    ```
    nvim -u NORC
    ```
1. Start the insert mode when switching to some terminal window:
    ```vim
    :autocmd WinEnter term://*bash startinsert
    ```

1. Launch the command with the autocmd:
    ```vim
    :term bash
    ```
1. Create a new window:
    ```vim
    :split test
    ```

### Actual behaviour

(Update: I by mistake wrote the actual behavior as the expected one, and the expected behavior as the actual one.) 

The buffer `test` is open as the *insert* mode.

### Expected behaviour

The buffer `test` is open as the *normal* mode.

**Comment by lacygoill** [comment]
> Actual behaviour
>
> The buffer test is open as the normal mode.

In the `test` buffer, I end up in insert mode:

    nvim -u NORC +'autocmd WinEnter term://*bash startinsert' +'term bash' +'split test'

> Expected behaviour
>
> The buffer test is open as the insert mode.

Maybe I misunderstood something, but I think that:

   1. you want to be in normal mode in the `test` buffer, instead of insert mode
   2. the purpose of the original autocmd is to automatically enter terminal mode in a terminal buffer, which it currently fails to do

`2.` is due to the fact that `WinEnter` is not fired when you execute `term bash`.
But `TermOpen` is:

    nvim -u NORC +'autocmd TermOpen,WinEnter term://*bash startinsert' +'term bash'
                           ^^^^^^^^

`1.` is due to the fact that when `WinEnter` is fired after `:split` has been executed, the current buffer is still the terminal buffer, so the buffer name still matches the pattern `term://*bash`.  To prevent this, you could delay the autocmd until the next `BufEnter`:

    nvim -u NORC +'autocmd WinEnter term://*bash au BufEnter * ++once if &buftype is# "terminal" | startinsert | endif' +'autocmd TermOpen term://*bash startinsert' +'term bash'

With the last command, when `:term bash` is executed, you immediately enter insert mode; and when you later execute `:split test`, you stay in normal mode.

**Comment by igrep** [comment]
> you want to be in normal mode in the test buffer, instead of insert mode

Aaah, sorry! I mistakenly wrote the expected result as the actual result, and the actual result as the expected result!

> the purpose of the original autocmd is to automatically enter terminal mode in a terminal buffer, which it currently fails to do

Yes. My vimrc is actually written as `autocmd BufWinEnter,WinEnter,TermOpen ...`. I omitted them just to minimize the vimrc to reproduce.

> To prevent this, you could delay the autocmd until the next `BufEnter`

Okay, I'll try that. Thank you!

**Comment by justinmk** [comment]
see also https://github.com/neovim/neovim/issues/4977

thanks @lacygoill
