### ISSUE TITLE
remove -Z ("restricted" mode)

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#11972]
Followup to https://github.com/neovim/neovim/pull/11929#discussion_r386078979 :

`-Z` is a fake-secure mode that behaves slightly differently than "sandbox" mode. It sprinkles more whack-a-mole "secure" code in various places.

Does anyone actually use `-Z`? Where/why is it useful?  

It's fragile to expect applications like N/Vim to plug all potential vectors for eval/shell/etc. For secure scenarios, OS permissions should be used instead.

**Comment by dstein64** [comment]
> "Does anyone actually use -Z? Where/why is it useful?"

One use case is for [vimgolf](https://github.com/igrigorik/vimgolf), where `-Z` is passed to the `vim` command. As is, removing `-Z` breaks vimgolf for users using `GOLFVIM=nvim`. I guess that most vimgolf users, including those who use Neovim as their editor, do not change `GOLFVIM`—from its default `vim`—to `nvim`, since there would not be much (or any as far as I know) difference for playing vimgolf.

**Comment by bfredl** [comment]
@dstein64 does vimgolf rely anything allowed in restricted mode but disabled in the sandbox? because otherwise it could use the sandbox (I don't like sandbox either, but we won't do anything about it except doc updates possibly for 0.5)

**Comment by dstein64** [comment]
The documentation for `sandbox` says that "changing the buffer text" is not allowed in the sandbox, which would be a problem if the sandbox is used generally, and not just for normal mode commands.

`vimgolf` runs locally on users' computers, launching Vim with the `-W` option to record keystrokes. A few additional options, like `-Z` and `--noplugin` are passed so that solutions can only use pure Vim, as opposed to relying on external functionality or plugins. The keystrokes are then sent to the Vimgolf server for submission to the leaderboard.

In case the sandbox would be feasible, is there some way to run Neovim such that all commands are run through the sandbox?
