### ISSUE TITLE
hang on exit when systemd automount cannot mount network drive 

### ISSUE THREAD

**Issue by cristobaltapia** [neovim/neovim#12075]
- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

- `vim -u DEFAULTS` (version: 8.2) behaves differently? Yes
- Operating system/version: Archlinux
- Terminal name/version: Termite v15
- `$TERM`: termite

### Steps to reproduce using `nvim -u NORC`

1. Setup a network share that will mount on access (this is defined in `/etc/fstab`), e.g.:
```
//server/share /mnt/mount user=user,password=pass,gid=1000,uid=1000,noauto,x-systemd.automount,x-systemd.mount-timeout=5s,_netdev 0 0
``` 

2. Define the corresponding automount systemd unit
```gitconfig
# /etc/systemd/system/mnt-mount.automount
[Unit]
Description=Automount remote shared folder

[Automount]
Where=/mnt/mount

[Install]
WantedBy=multi-user.target
```

3. Start the unit with
```
$ sudo systemctl daemon-reload
$ sudo systemctl start mnt-mount.automount
```

4. Open neovim and then try to close it with `:q`

### Actual behaviour

If the shared folder is reachable, only a small delay is experienced.
If the shared folder is not reachable, neovim will hang. (Neovim is opened in the home directory, so it should not be influenced by the shared folder being not reachable). This behavior is not seen with vim.

### Expected behaviour

Neovim should close as fast as vim does.

**Comment by rumpelsepp** [comment]
can confirm this. It is enough to mount via nautilus and e.g. terminate the VPN so the folder is unreachable.

**Comment by j-n-f** [comment]
This issue seems resolved for me now. The problem must have been in a dependency.

**Comment by justinmk** [comment]
sounds like https://github.com/neovim/neovim/issues/12808 . Please comment there if you have insight.

I wonder what changed, that we have two similar reports like this? Never heard of this since 2014...

**Comment by justinmk** [comment]
can you get a backtrace of the hang?

**Comment by cristobaltapia** [comment]
@justinmk I can't reproduce this anymore. Now neovim is closing instantly as expected.

**Comment by cristobaltapia** [comment]
@justinmk I am experiencing this issue again. How can I get the backtrace? Do I need to compile neovim manually?

**Comment by cristobaltapia** [comment]
BTW, this started today after editing a file in the network share. It had been a while since I did that. I suppose that neovim must be looking for the last files or so. Maybe there is internally a list with the last opened files?

**Comment by sycx2** [comment]
I got the same issue. I checked the verbose log and found out it seems to be related to the shada files (at least for me of course). Deleting the files with "rm /home/$USER/.local/share/nvim/shada/*" solves the symptoms for me temporarily.

In the logs it says
chdir(/mnt/foo)

where foo is currently not available, just mounted on access.
Guess the attempt to access it takes too long.

**Comment by sencer** [comment]
This happens when shada refers to a file in a network drive which is not accessible at that moment

**Comment by bobrippling** [comment]
As the reddit mentions, [the fix] is `set shada+=r/mnt/exdisk` - instant exit for me now.

[the fix]: https://old.reddit.com/r/neovim/comments/duqg7v/shada_and_external_drives/f79zplg/

**Comment by cristobaltapia** [comment]
Thanks @bobrippling ! That fixed the problem.

**Comment by ingo-h** [comment]
I have a NFS automount link `/mnt/vserver/ingo` in my `/etc/fstab` that is also always triggered for nothing to waste performance only when start and exit nvim with `:q`. The suggested fix at https://github.com/neovim/neovim/issues/12075#issuecomment-867956505 is to add `set shada+=r/mnt/vserver/ingo` to the `~/.config/nvim/init.vim` (Debian "trixie").

This does not help me. I have to insert the line `set shada=` to fix the issue.

**Comment by ingo-h** [comment]
After some days using nvim with `set shada=` in its config file `init.vim` I realized that this disables the cached command history completely. With every new start of nvim the history called with `q:` is empty. It isn't stored anymore. That is not acceptable for me.

So here is the whole story.

I use Debian 13/"trixie" to understand the examples. I have several automount shares to my server, e.g. `/mnt/vserver/home/ingo` or `/mnt/vserver/home/mary`. When I used neovim just for a quick edit of a local file, e.g. `~/.bashrc`, to modify a single entry neovim accesses the share `/mnt/vserver/home/ingo` for nothing so that it automounts. This is annoying because of wasting resources (mounting an encrypted network resource with *kerberos* is expensive) and it slow down use of neovim. Within nvim you find with `:h shada`:

> When Vim is started and the 'shada' option is non-empty, the contents of the ShaDa file are read and the info can be used in the appropriate places. The v:oldfiles variable is filled. The marks are not read in at startup (but file marks are). When Vim exits and 'shada' is non-empty, the info is stored in the ShaDa file (it's actually merged with the existing one).

Long story short: if you have used a file on the share and it contains file marks for some reasons, e.g. you have set one with `mX`, the share will be automounted, even if you just start and exit nvim without editing anything. To avoid this you can use prefix  **r**  with `set shada+=r/mnt/vserver/home/ingo` in `~/.config/nvim/init.vim`. Then the file marks are not stored in `~/.local/share/nvim/shada/main.shada`. This means you loose these file marks on exit of nvim. If you have file marks stored from older sessions and then `set shada+=r/...` in `init.vim` it does not have an effect. Automount still take place until you completely delete all old information about file marks. I did it with deleting `main.shada` one time after setting the option.

On the other side `set shada+=r/mnt` respects all nested mount points so the automounts to ingos and marys server home will not take place on starting neovim. So my solution of the issue are these entries in `init.vim`:

    " avoid accessing unneeded nfs shares and slow down writing docs
    set shada+=r/mnt
    set shada+=r/media
 
This ensures that I do not have always to modify the neovim configuration on all my workstations when modifying the mount points.
