### ISSUE TITLE
Alternative donation methods

### ISSUE THREAD

**Issue by tricktux** [neovim/neovim#12083]
[bountysource](https://salt.bountysource.com/teams/neovim) has been having a lot of issues lately. Maybe setup alternative methods for donation.
I believe the project is loosing donations because of this.

**Comment by XVilka** [comment]
It's possible to use [OpenCollective](https://opencollective.com), we use it for Radare2. It also integrates with GitHub sponsors and working on accepting cryptocurrencies.

**Comment by tricktux** [comment]
I'll be more than happy to set something up if maintainers reach a consensus.

**Comment by teto** [comment]
I have the feeling that all these systems to gather money kinda `suck`, sometimes for valid reasons.
Considering the administrative cost, it would be nice to elaborate on the `bountysource has been having a lot of issues lately`.

**Comment by tricktux** [comment]
@teto I've been trying to sign up for a few days now and I am unable.

>all these systems to gather money kinda suck

Agree. Is the bitcoin link reliable?

**Comment by XVilka** [comment]
It is. I donated with Bitcoin to the wallet on the NeoVim site successfully
before.

**Comment by tricktux** [comment]
[Here](https://pi-hole.net/donate/) is, what I believe, a good example of a nice donate page.

**Comment by wsdjeg** [comment]
do not use OpenCollective.

**Comment by teto** [comment]
@wsdjeg without more justification, it's not exactly helpful :p

**Comment by gdude2002** [comment]
Please note that BountySource [has updated their terms of service](https://github.com/bountysource/core/pull/1480/files#diff-22543f4d1095933c60885e9c799d7bbeR42), with the following text:

> 2.13 Bounty Time-Out.
> 
> If no Solution is accepted within two years after a Bounty is posted, then the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource. For Bounties posted before June 30, 2018, the Backer may redeploy their Bounty to a new Issue by contacting support@bountysource.com before July 1, 2020. If the Backer does not redeploy their Bounty by the deadline, the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource.

This change was made [about a month ago](https://www.reddit.com/r/opensource/comments/gn7rkq/bountysource_just_made_a_retroactive_tos_change/), but they seem to have deliberately delayed announcing it - I just got an email about it this morning, in fact.

There doesn't seem to be too much discussion about this at the moment, although I found [a thread on the Nextcloud forums](https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943).

---

I personally do not feel that this change has been made in good faith. It's especially egregious given that they announced it _exactly_ two weeks before the deadline mentioned in the clause - the same amount of time as the claim deadline for completed issues.

This seems like the perfect time for Neovim to move to something else.

**Comment by glacambre** [comment]
I've had an uneasy feeling with Bountysource ever since they were bought by a cryptocurrency company and I'm not surprised they started stealing money from open source projects. I stopped donating to neovim a few months ago when my credit card expired and I'd like to start donating again - but through another, trust-worthy company/service.

Github sponsors is probably the best alternative as it has zero fees. However it's complicated to setup as the organization must have a bank account and you need to fill tax forms (https://help.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-organization).

Another alternative could be [liberapay](https://liberapay.com/) - it also has the concept of organization and although the site isn't great to look at it works nicely. I'm not sure how the money is handled when donated to an org though.

If you want to go with the self-hosted route, you could try [fosspay](https://github.com/ddevault/fosspay).

I've received donations through both Liberapay and Github sponsors and am satisfied with them. I would be willing to help setup Neovim with another service but I don't feel I've contributed enough to the project to be trusted with something as critical as donations.

**Comment by tricktux** [comment]
Here is a link to the hacker news discussion:


[BountySource have turned evil – alternatives? -](https://news.ycombinator.com/item?id=23551098)

**Comment by teto** [comment]
The bountysource move is a bit worrying and their website is unreliable. I think we are going to setup additionnal methods. May take some time though so this message is just to inform you this is being discussed.

**Comment by anelson** [comment]
I've also been a regular supporter of neovim, and would like to continue to do so, but not via Bountysource.  I'll be eagerly awaiting a new method of supporting the project.

**Comment by WhyNotHugo** [comment]
I've been wanting to donate to the project for months now, but the Bountysource always has some internal error, CORS issues, etc, and I've never been able to set it up due to their fault.

Now they're taking money from open source projects and keeping it for themselves -- I'm very reluctant to have money go through them at this point. They're neither ethical nor competent.

**Comment by jemag** [comment]
Considering the reluctance of many to use bountysource and the fact that this is how Neovim developers get paid, I think it would be important to prioritize this. Is neovim working through the process of Github Sponsors?

**Comment by teto** [comment]
Yes we agreed to setup bountysource. I tried to set it up last week but couldn't due to technicalities. It is a bit involving and so it takes time sry for that.

**Comment by chmln** [comment]
+1 for github sponsors. Neovim is one of the best projects in the text editor space, in my opinion. It would be great if maintainers could get paid for their efforts and eventually work on it full-time.

**Comment by jamessan** [comment]
[OpenCollective](https://opencollective.com/neovim) is setup and we're in the process of finishing the GitHub Sponsors setup.

**Comment by tricktux** [comment]
Is great OpenCollective is setup. But it's still not mentioned anywhere outside of this issue (that I could find)

**Comment by bfredl** [comment]
The big Public Reveal will happen quite soon.

**Comment by jamessan** [comment]
[GitHub Sponsors](https://github.com/sponsors/neovim/) is live now.

**Comment by arusahni** [comment]
After reading about how questionable BountySource has been of late, I moved my sponsorship over to GitHub. However, it seems as if there's no equivalent tier to my recurring amount. Is it possible to add a $5/mo tier? Thanks! 🎉

**Comment by chaficnajjar** [comment]
@arusahni There's now a tier where you choose a custom amount, like $5/month.
