### ISSUE TITLE
neovim health...

### ISSUE THREAD

**Issue by bijang** [neovim/neovim#12143]
...in the coronovirus time...
I love this project but I couldn't help but notice the commit activity has been on the decline over a few months, the only obvious unifying factor being the situation we are in,.. and I would  have thought social distancing allowed for more coding... so I hope everyone is okay in these times and thank you for your contributions.... 
please delete this horrible non-issue as you see fit :) 
[also I'm really impatient for release 0.5  ;p]

**Comment by teto** [comment]
Thanks for your concern. The project is usually very active but it's not because it's less active it isn't active :) We even sent a newsletter today ?!
A lot of sweat has gone into preparing 0.5 but there is still a long way to go to polish the whole release.
I am going to close this but anyone wanting to share some love feel free to reply (with your mask on).

NB: Note that social distancing does not necessarily lead to more coding for various reasons (kids being one of them).
