### ISSUE TITLE
[Discussion] LSP support for $/progress

### ISSUE THREAD

**Issue by wbthomason** [neovim/neovim#12392]
I've recently built https://github.com/wbthomason/lsp-status.nvim, which implements support for [`$/progress`](https://microsoft.github.io/language-server-protocol/specification#progress) (as well as some other niceties around LSP diagnostics/protocol extensions for status messages) using the built-in LSP library.

In https://github.com/wbthomason/lsp-status.nvim/issues/3, @teto mentioned that part of this functionality might be good to upstream - specifically, the callback for `$/progress`: https://github.com/wbthomason/lsp-status.nvim/blob/7a9a2a73171a5ea6457753a849baa2a0929ca297/lua/lsp-status/messaging.lua#L8

I wanted to open a broader discussion about upstreaming this (or other parts of the plugin). Doing so would require including at least most of `messaging.lua` (i.e. to setup the message inboxes, handle retrieving messages, etc.), and there's probably some code cleanup and definitely some documentation work to be done.

I wrote this as a separate plugin because I wasn't sure the core would want to add this feature (it seems like the built-in client is intentionally being kept fairly minimal). However, if I'm wrong about that and people would like this functionality in core, I'd be happy to make a PR. What do others think?

(Also, thanks to @h-michael and @norcalli and others for the core LSP library; it's been a pleasure to build on top of!)

**Comment by teto** [comment]
Not to forget the original LSP PR from our beloved @tjdevries . I haven't looked at the code in detail yet but it's part of the standard so we should support it. Less of an argument but is also very helpful.
As a first step the pyls/clangd non-standard (?) extensions should live in your plugin IMO (out of curiosity what are their benefits ? do you think they can converge towards the standard ?). @tjdevries may have a plan to support extensions

**Comment by wbthomason** [comment]
Of course, sorry to forget to tag @tjdevries!

Re: the `pyls_ms`/`clangd` extensions: I agree that these should remain in my plugin. They were added because those two language servers don't yet use `$/progress` to send status messages (at least, not that I could find), but do define their own message types to signal indexing/other status updates (since before version 3.15 of the LSP spec, which introduced `$/progress`). I hope they will converge toward the standard; once they do, those extension modules can go away. For now, though, they're necessary to get status messages from those servers.

**Comment by teto** [comment]
@clason interested :D ?

**Comment by clason** [comment]
> @clason interested :D ?

Kind of a random summon, but I'll bite :)

Given that progress messages are now [part of the LSP spec](https://microsoft.github.io/language-server-protocol/specification#progress), I'd say that makes sense (although I personally don't use a server that makes use of them).

I'd also be interested in more feedback (in particular, server status -- attached, starting up, terminated) capabilities -- I believe there was a discussion a while back that the naive approach using the tools available now could be too costly?

**Comment by teto** [comment]
Only half-random as you "+1ed" my post on upstreaming this. but if you don't use any server that relies on this, that can't be helped :'(

Regardless of the spec, we do need to have some neovim command to better diagnose lsp issues, like `:NeomakeInfo` or `:CocInfo` IIRC. The current checkhealth nvim_lsp is underwhelming, we would need a buffer version of it but that's another issue.

**Comment by clason** [comment]
> Only half-random as you "+1ed" my post on upstreaming this. but if you don't use any server that relies on this, that can't be helped :'(

That's true :) I didn't think my opinion would be worth more than that, though.

I just checked, the server does support it, but for a function I don't really use -- but it means I could (and would) test it.

And I agree, some dynamic info on _running_ (or not) servers in addition to the static health check of the configuration (which is ok for what it does) is needed. A simple indicator in the status line whether a server was attached would already be valuable; an `:LspInfo` that dumps the current configuration or capabilities -- both client and server, in particular the workspace -- to `messages` would help a lot for bug reports. (But the latter is probably outside the scope of this particular issue and requires some thinking since one can't poll the server on such info; the best I can find is the `InitializeResult` that would have to be stored.)

**Comment by wbthomason** [comment]
I’d add that it would be useful to include log messages/maybe progress messages if they’re not already captured in the logs in any `LspInfo`/similar output.

**Comment by norcalli** [comment]
The messaging code looks straightforward enough to add in. I could see a few places for some small refactoring that might make it a little smaller too. I think it's a good candidate for upstreaming. It also looks very similar to the code I use to initialize buffers. In general, defaultdict style patterns are common enough that it may be worth including a utility for it (by implementing __index).

@wbthomason if I want to propose some changes, does it make sense to keep doing it on lsp-status and then you can make a PR against core? Also if it's mainlined, then removing duplication from lsp-status would introduce some difficulty of having it be tied to a version of neovim then, so if users update your plugin and don't update master, there will be some breakage.

@clason I agree with the extra information. I've had quite a few user reported issues that could've been pre-emptively solved by including whether or not nvim-lsp was actually targetting the file due to the root_patterns, for instance, which is for non-running servers. I think in order to make the built in LSP actually useful for people to feel comfortable trying, improving diagnostic/debuggin/status info is a high priority.

**Comment by wbthomason** [comment]
@norcalli Sure, proposing changes on the original repo with the intent of me eventually making a PR against core sounds good.

re: removing duplication risking breakage: I think this can be dealt with reasonably by making lsp-status fall back to the messaging feature in core if it detects that the user's Neovim has it, and adding a message to the README encouraging users to update their Neovim version. Once a stable core is released with the feature, that part of lsp-status can be removed.

re: refactoring and cleanup: Please do make any/all suggestions you have for this, common Lua patterns, improving performance, etc. This (and the other Neovim plugins I've written recently) is the first "significant" Lua I've ever written, so there's a lot I need to learn in terms of writing idiomatic, performant Lua. If you have any recommended resources for learning that, I'd appreciate those too.

**Comment by weilbith** [comment]
What is the latest status of this issue? 🙃

**Comment by teto** [comment]
I've just pushed https://github.com/neovim/neovim/pull/13294 . I dont trust my lua so feel free to comment over there.

**Comment by teto** [comment]
@wbthomason progress report was merged in case you want to mention it in lsp-status. The doc is lacking though.

**Comment by tjdevries** [comment]
@teto we should change the name of the function in `handlers.lua` to be `handler`, not `callback`

```
progress_callback
```

;)

**Comment by teto** [comment]
ack !

**Comment by teto** [comment]
will put some doc while at it
