### ISSUE TITLE
add option to disable delay on W10 error

### ISSUE THREAD

**Issue by alexmo1997** [neovim/neovim#12486]
- `nvim --version`: v0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: Arch Linux; Kernel: 5.7.2.arch1-1
- Terminal name/version: urxvt
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC somereadonlyfile
```
or
```
nvim -u NORC "+set ro" somefile
```

### Actual behaviour
~1 second delay after pressing `i` or any other key that goes to insert mode

### Expected behaviour
being able to disable that, at best also setting it dependent on if it has a immutable flag or if it is not writable by permission

**Comment by mhinz** [comment]
It doesn't need any setting, it just needs to get fixed as I see no technical reason why there should be any delay, but it happens in Vim as well.

Maybe you want to report it to vim/vim instead, because we merge their patches anyway.

**Comment by alexmo1997** [comment]
Doesn't seem like a bug: https://github.com/vim/vim/blob/master/src/change.c#L61

**Comment by mhinz** [comment]
Unfortunately it's highly unlikely that it will ever change in Vim then. And we try to diverge from Vim's code base only if necessary.

I consider this only a minor annoyance at best, because 1) it's a very rare use case (the warning is shown for a reason) and 2) it only happens when switching to insert mode for the first time.

Nvim has so many options already, adding another one just to work around a rare 1s delay is not worth the effort of adding code and documenting it.

Thanks for asking anyway.

**Comment by alexmo1997** [comment]
Thinking about this, you said that it is not worth the effort of adding code and documentation. Would you accept a PR with a feature removing the delay optionally then?

**Comment by justinmk** [comment]
We can likely implemented delayed notifications without blocking user input. That solves the problem without a new option.
