### ISSUE TITLE
Add api to get neovim startup time 

### ISSUE THREAD

**Issue by glepnir** [neovim/neovim#12490]
- `nvim --version`: neovim nightly
- `vim -u DEFAULTS` (version: ) behaves differently? same
- Operating system/version: mac os 10.15.4
- Terminal name/version: item2
- `$TERM`: xterm-256

### Actual behaviour

no api to get  the neovim startup time string.`--startuptime` is a cli command to check the neovim startuptime. but  i expect to get startup time by a function return value. it's very useful
when write some plugins. read the `--startuptime` output file is a way to get it .
But he is not suitable for some startup screen plugins. For example, [dashboard-nvim](https://github.com/hardcoreplayers/dashboard-nvim), reading the output file will affect the startup speed of the plugin. I think.

### Expected behaviour
I can  get the neovim startup time string by a function in vimscript. I think it's useful when write some plugins.

**Comment by glacambre** [comment]
I'm curious, why do you need this? Is it to show the startup time every 
time neovim starts or do you have other use cases?

**Comment by glepnir** [comment]
I hope this feature will appear in my plugin. It is also very important for vimer reminders. vimer can clearly notice that it takes time to start vim.

**Comment by mhinz** [comment]
Implicitly collecting startup stats takes time and memory and shouldn't be done by default, since most people will never use it.

`--startuptime` is a debugging tool and should be treated like that. I see no merit in doing this at every startup.

You could try to convince [vim/vim](https://github.com/vim/vim) of this and we'll merge their patch, but I'm pretty certain that won't ever happen. Sorry. :)
