### ISSUE TITLE
Type schema of api-info should use String instead of Binary

### ISSUE THREAD

**Issue by myitcv** [neovim/neovim#1250]
I think we need to start being explicit about the MSGPACK types used in the `--api-info` output. Some languages (read Go, at least) will want to code generate the MSGPACK handling code. To do so, we need to be explicit about the types used. 

All type references below are to those found in the [MSGPACK spec](https://github.com/msgpack/msgpack/blob/master/spec.md). I use the Go-esque notation `k, v = map[String]Integer` to refer to a map, in this example a map from `String -> Integer`. `k` and `v` are used here as the values of the map so I can refer to them later. `string(k)` is a conversion from a Binary byte array to a UTF8 string.

At present the schema of the output is as follows:

* `k, v = map[Binary]'thing'`
* 'thing' is determined by the value of the key
* `string(k) == "types" || string(k) == "error_types"`, `'thing'` has type `map[Binary]{map[Binary]int}` (strictly speaking this is a mixed type value map but for now we only have `id` which is of type `int`)
* `string(k) == "features"`, `'thing'` has type `map[Binary]{array[Binary]}`
* `string(k) == "functions"`, `'thing'` has as type as follows:

```
array [
  kk, vv = map[Binary] {
    bool                   if string(kk) == 'can_fail'
    array[Binary, 2]       if string(kk) == 'parameters'
    Binary                 if string(kk) == 'name'
    Binary                 if string(kk) == 'return_type'
  }
]
```

The one change I would like to propose is that for `--api-info` we use the String type instead of Binary. Because we are generating the output of `--api-info`, we know the contents of any 'string' will only be UTF8. Hence we should encode it as such. For typed languages this is significant because encoding them as Binary means that the decoded type is essentially `[]byte` with conversions required everywhere to get to a `string`. For buffer contents this is a reasonable expectation because we don't want to assume the contents of the buffer are UTF8. But here we are defining the types used in `--api-info` so we can specify that the strings are UTF8.

Otherwise this schema looks ok. I will create a separate issue to discuss the types of the API itself where I have a couple of changes to propose.

**Comment by justinmk** [comment]
@tarruda What if we simply declared that `'encoding'` is always utf8? Would it allow us to avoid this chicken-egg complication for msgpack clients, and allow us to send strings instead of binary? 

Adding this to 0.1 if only to answer that question, then either close this issue or act on it.

**Comment by tarruda** [comment]
> @tarruda What if we simply declared that 'encoding' is always utf8? Would it allow us to avoid this chicken-egg complication for msgpack clients, and allow us to send strings instead of binary? 

We can't force this encoding for all API functions because it is still possible to have raw data sent, what we can do is add a flag to the `String` type that can be used to serialize it into msgpack strings instead of binary. Since `vim_get_api_info` is guaranteed to return only utf-8 strings, we can safely modify msgpack-gen so that the metadata will make use of the utf8 flag:

```diff
diff --git a/scripts/msgpack-gen.lua b/scripts/msgpack-gen.lua
index 581641a..4c7c35e 100644
--- a/scripts/msgpack-gen.lua
+++ b/scripts/msgpack-gen.lua
@@ -113,6 +113,10 @@ output:write([[
 static const uint8_t msgpack_metadata[] = {

 ]])
+-- force msgpack to serialize lua strings into MSGPACK_OBJECT_STR instead of
+-- MSGPACK_OBJECT_BIN:
+-- http://fperrad.github.io/lua-MessagePack/msgpack.html#reference
+msgpack.set_string('string')
 -- serialize the API metadata using msgpack and embed into the resulting
 -- binary for easy querying by clients
 packed = msgpack.pack(functions)
diff --git a/src/nvim/api/private/defs.h b/src/nvim/api/private/defs.h
index 6c8e324..7c31209 100644
--- a/src/nvim/api/private/defs.h
+++ b/src/nvim/api/private/defs.h
@@ -6,7 +6,7 @@
 #include <string.h>

 #define ARRAY_DICT_INIT {.size = 0, .capacity = 0, .items = NULL}
-#define STRING_INIT {.data = NULL, .size = 0}
+#define STRING_INIT {.data = NULL, .size = 0, .utf8 = false}
 #define OBJECT_INIT { .type = kObjectTypeNil }
 #define ERROR_INIT { .set = false }
 #define REMOTE_TYPE(type) typedef uint64_t type
@@ -44,6 +44,7 @@ typedef double Float;
 typedef struct {
   char *data;
   size_t size;
+  bool utf8;
 } String;

 REMOTE_TYPE(Buffer);
diff --git a/src/nvim/msgpack_rpc/helpers.c b/src/nvim/msgpack_rpc/helpers.c
index 473958c..bb6bcad 100644
--- a/src/nvim/msgpack_rpc/helpers.c
+++ b/src/nvim/msgpack_rpc/helpers.c
@@ -99,6 +99,7 @@ bool msgpack_rpc_to_string(msgpack_object *obj, String *arg)
     }
     arg->data = xmemdupz(obj->via.bin.ptr, obj->via.bin.size);
     arg->size = obj->via.bin.size;
+    arg->utf8 = obj->type == MSGPACK_OBJECT_STR;
     return true;
   }
   return false;
@@ -225,8 +226,13 @@ void msgpack_rpc_from_float(Float result, msgpack_packer *res)
 void msgpack_rpc_from_string(String result, msgpack_packer *res)
   FUNC_ATTR_NONNULL_ARG(2)
 {
-  msgpack_pack_bin(res, result.size);
-  msgpack_pack_bin_body(res, result.data, result.size);
+  if (result.utf8) {
+    msgpack_pack_str(res, result.size);
+    msgpack_pack_str_body(res, result.data, result.size);
+  } else {
+    msgpack_pack_bin(res, result.size);
+    msgpack_pack_bin_body(res, result.data, result.size);
+  }
 }

 void msgpack_rpc_from_object(Object result, msgpack_packer *res)
```

@equalsraf / @myitcv  what do you think of this patch?

**Comment by fdinoff** [comment]
@tarruda Is this only going to effect `vim_get_api_info`? Or is it going to affect all functions that can possibly return strings? 

I feel like having two different string types makes it harder to write a type safe api as you don't know which one you're going to get until the object shows up.

**Comment by justinmk** [comment]
@fdinoff  what are your thoughts about the request in this issue ? Is it needed at all?

**Comment by tarruda** [comment]
> @tarruda Is this only going to effect vim_get_api_info? Or is it going to affect all functions that can possibly return strings? 

The above adds a utf8 field to the `String` type which(for the moment) is only used by `vim_get_api_info`

> I feel like having two different string types makes it harder to write a type safe api as you don't know which one you're going to get until the object shows up.

There are not two different string types, the utf8 field is just a hint to use `MSGPACK_OBJECT_STR` instead of `MSGPACK_OBJECT_BIN` when serializing to msgpack. But `MSGPACK_OBJECT_STR` itself is not a different type, it is the same as `MSGPACK_OBJECT_BIN` except it uses a different type code(It is perfectly fine to deserialize `MSGPACK_OBJECT_BIN` as if it was `MSGPACK_OBJECT_STR` for example)

`MSGPACK_OBJECT_STR` only exists to simplify decoding utf-8 by languages that have a specialized type for unicode strings. It is nothing but a hint message saying: "hey, I guarantee that the following byte array contains a utf-8 string, so feel free to decode it". But nvim can't  use it always because most API functions provide no guarantee that they will return utf-8 strings(`vim_get_api_info` is an exception). It's perfectly fine for a buffer to contain binary data which is returned unmodified by `vim_get_current_line` for example.

> @fdinoff what are your thoughts about the request in this issue ? Is it needed at all?

The patch I posted is not needed, it just provides a small simplification for plugin hosts during the api discovery phase.

**Comment by fdinoff** [comment]
@justinmk I personally think it would be nice if the api info used the string data type for the keys in the map.  (So the overall issue I think is relevant, however I don't know if the patch proposed is a good solution)

In Java, the binary type (byte[]) is actually kind of annoying to use. For instance, [msgpack-java](https://github.com/msgpack/msgpack-java) uses [jackson-databind](https://github.com/FasterXML/jackson-databind/) underneath to do automatic sterilization and deserialization. A couple of annotations and some generics/reflection magic and I can have a completely deserialized object. Currently it has problems dealing with binary objects since the library doesn't know how to decode the binary into a String object. If the library encounters binary strings, and its trying to do its automatic deserialization it guesses utf-8. If any other encoding is used, everything will break.

(Originally I didn't even read the api-info since the library didn't support reading the binary as utf-8. It just threw an exception since the keys of the map were not strings, and I didn't want to walk the msgpack object manually)

> There are not two different string types

@tarruda You don't have two different string types. You have a binary blob type, and a string type. Neovim's definition of a String is very broad. You might be able to treat both types as "String" in c, since both can be represented as character arrays, but in Java I can't treat `byte[]` and `String` as the same type. The compiler will yell at me. Almost no library function even knows how to deal with byte[] arrays, so I would have to roll my own everything. 

I can't really create a type safe api if I don't know the type that I'm expecting to get. I would like to get to the point where I would never have to return Object to the user since then the user has to do `instanceof` chains to figure out what they got. Asking for a byte[] array when the library returns a string will give a runtime error.

(Some of these things are probably artifacts of how the msgpack library was implemented in java, however there does not appear to be a consensus of how each library should work since every language has its own design philosophy)

**Comment by justinmk** [comment]
@tarruda I meant the original request, not your patch.

**Comment by tarruda** [comment]
> @tarruda You don't have two different string types. You have a binary blob type, and a string type. Neovim's definition of a String is very broad. You might be able to treat both types as "String" in c, since both can be represented as character arrays, but in Java I can't treat byte[] and String as the same type. The compiler will yell at me. Almost no library function even knows how to deal with byte[] arrays, so I would have to roll my own everything. 

That's because in java `String` instances are arrays of 16-bit integers and our `String` instances are arrays of 8-bit integers, so there's no need for a separate "binary blob" type. As I said,  `MSGPACK_OBJECT_STR` is only a decode hint for languages that have builtin unicode strings.

When you say that almost no library can deal with `byte[]` it just means that they are expecting Unicode strings and not byte arrays. Can't you convert `byte[]` to `String` instances by recursively traversing objects returned by the msgpack library? If you are only expecting to deal with valid utf8 strings then it is not a problem, but you need to take some action in case the utf8 decoding fails, perhaps throw a specialized exception containing the original `byte[]`?

> I can't really create a type safe api if I don't know the type that I'm expecting to get. I would like to get to the point where I would never have to return Object to the user since then the user has to do instanceof chains to figure out what they got. Asking for a byte[] array when the library returns a string will give a runtime error.

You can create a type safe API by automatically generating the functions that wrap msgpack-rpc calls.  Some examples:

- Node client generates [this file](https://github.com/neovim/node-client/blob/master/api.d.ts) to allow type-safe interaction with the API for typescript programs
- [nvim-hs](https://github.com/neovimhaskell/nvim-hs) also seems to generate API wrappers using a template.

You just need to find a tool that allows you to generate java code and hook it into your build system(before compilation, of course)

**Comment by myitcv** [comment]
@tarruda as a solution for `--api-info` I think this works. Just a quick clarifying question. Are you proposing that if I run `nvim --api-info`, `&encoding` is _guaranteed_ to be `utf-8` (in addition to the MSGPACK encoding being `str`), irrespective of any `.nvimrc` settings etc?

As a further point, and I think this is related to @fdinoff's comments, we need a solution for the value of `&encoding` at runtime. 

How is this value communicated to a plugin?
What if the value changes?

Whatever the language of the plugin host it needs to know the value of `&encoding` in order to correctly decode the `byte[]` to the string encoding the language uses, in order that the `String` API type can be exposed as the language's closest equivalent. 

Out of interest, what does the Python host do for different encodings?

**Comment by bfredl** [comment]
It is already generally assumed that `encoding` doesn't change after startup. (The python host, for instance)  #2929 will enforce this properly.

**Comment by myitcv** [comment]
Thanks @bfredl that's a useful reference. 

What about the initial value?

**Comment by bfredl** [comment]
By convention, all &encoding names are guarranteed to be ASCII, so for instance the python client does `vim_get_option('encoding')` and then `.decode('ascii')` in case of python3

> Are you proposing that if I run nvim --api-info, &encoding is guaranteed to be utf-8 (in addition to the MSGPACK encoding being str), irrespective of any .nvimrc settings etc?

similary, I would guess api info metadata to always be pure ASCII, so knowing &encoding is not needed. (but msgpack type `str` would indicate `utf-8` regardless of `&enc` anyway, right?)

**Comment by fdinoff** [comment]
@tarruda 

>  recursively traversing objects returned by the msgpack library

I would prefer if this wasn't necessary. Its more work for everyone using the library. Although the more I look into this the more it looks like using the msgpack-jackson library isn't going to work. 

> perhaps throw a specialized exception containing the original `byte[]`

Its one solutions, and I would say a frowned upon practice in java. 

> You just need to find a tool that allows you to generate java code and hook it into your build system(before compilation, of course)

I feel like this should be a last resort. If I were to use the lower level interface to traverse the msgpack data object I might consider writing something to do that. 

Maybe one day the existing msgpack library in java will be useful for neovim, but it appears that neovim usage does not align with usage the usage they designed the library for.

---

@myitcv You can get the initial value with `vim_get_option("encoding")` and assuming the encoding variable is returned as ascii... (Or at least thats how the [python client](https://github.com/neovim/python-client/blob/be6e96ee59f6101b20764eafe53bada6b8facb3e/neovim/plugin/host.py#L41) does it currently.)

**Comment by myitcv** [comment]
@fdinoff @bfredl surely the value returned by `vim_get_option("encoding")` is an API `String` (encoded as `byte[]`) that itself needs decoding?

**Comment by bfredl** [comment]
yes, but you could just assume it to ascii. (Seems to work for python3 host at least.)

**Comment by bfredl** [comment]
( another option is to just assume `encoding=utf8`, as it should be. I  do that in my Julia client. But there still is the issue of potentially invalid utf-8... )

**Comment by ZyX-I** [comment]
My small bit: ShaDa in #2506 uses STR type for all mapping keys and BIN type for almost everything else. So does `msgpackdump()` function, except that it is less legitimate: it does not check that &encoding is UTF-8, convert dictionary keys to UTF-8 if it is not or check that keys are valid UTF-8 when &encoding is UTF-8: it was written to make writing future ShaDa plugin easier and ShaDa uses STR for keys because I know that keys in question are ASCII.

**Comment by fdinoff** [comment]
I think using utf8 for all keys in maps is a good idea. I assume that they all keys have to be valid in &encoding?

**Comment by justinmk** [comment]
Perhaps for API simplification we should disallow changing `'encoding'` completely.

**Comment by tarruda** [comment]
> I would prefer if this wasn't necessary. Its more work for everyone using the library. Although the more I look into this the more it looks like using the msgpack-jackson library isn't going to work.

If I understood correctly, handling this in the java plugin host would free plugin developers from doing it themselves.

> Its one solutions, and I would say a frowned upon practice in java.

FWIW, I did something similar in the node client and it seems to works well: https://github.com/neovim/node-client/blob/master/index.js#L18-L20

> I think using utf8 for all keys in maps is a good idea. I assume that they all keys have to be valid in &encoding?

I'm not sure that's always going to be the case since maps can be converted from arbitrary vimscript dictionaries. If I understood correctly, @ZyX-I only used STR because the keys are known to be utf-8:

>  it was written to make writing future ShaDa plugin easier and ShaDa uses STR for keys because I know that keys in question are ASCII.

AFAIK vimscript can have arbitrary binary strings in keys

> Another option is: advise users that non-utf8 'encoding' is simply not supported if you use remote plugins. Then advise all API clients to assume utf8 'encoding'.

:+1: As shown in the link above, this is what I did in the node client(it will try to decode all binary strings into unicode, keeping the original array on failure.

**Comment by justinmk** [comment]
Then we don't need the hint in https://github.com/neovim/neovim/issues/1250#issuecomment-132573288 ? Can we close this?

**Comment by tarruda** [comment]
> Then we don't need the hint in #1250 (comment) ? Can we close this?

IMO we don't, I only provided this patch to simplify decoding API metadata when a plugin host doesn't want to assume every BIN is utf-8.

**Comment by myitcv** [comment]
> IMO we don't, I only provided this patch to simplify decoding API metadata when a plugin host doesn't want to assume every BIN is utf-8.

But as you've said before, unless I've misunderstood, we can't assume that every `BIN` is `utf-8` because we can't make any guarantees about the value of `&encoding`

To my mind the only outstanding questions here are:

* guaranteeing the encoding of `--api-info` to be `utf-8` 
* some sort of plugin handshake in which the value of `&encoding` is communicated to the plugin so that non-`utf-8` values can be supported

Unless you're suggesting that remote plugins are supported when encoding is `utf-8`?

**Comment by tarruda** [comment]
> But as you've said before, unless I've misunderstood, we can't assume that every BIN is utf-8 because we can't make any guarantees about the value of &encoding

I expressed myself badly: It is safe to assume everything is utf-8 as long as you are ready to deal with the exceptions. In the node client, I try to decode everything into utf-8, but when it fails the original byte array is kept intact.

> guaranteeing the encoding of --api-info to be utf-8

This is guaranteed even if the returned object has BIN fields.

> some sort of plugin handshake in which the value of &encoding is communicated to the plugin so that non-utf-8 values can be supported

While that's an option, I think it is simpler follow @justinmk suggestion:

> Another option is: advise users that non-utf8 'encoding' is simply not supported if you use remote plugins. Then advise all API clients to assume utf8 'encoding'.

Just to clarify, this doesn't imply that we will start returning `STR` in every msgpack call. It is just a documentation update stating that plugin hosts should not care about other encodings other than utf-8, like I did in the node client(try to decode utf-8, if it fails just return a byte array)

**Comment by myitcv** [comment]
> While that's an option, I think it is simpler follow @justinmk suggestion:

>> Another option is: advise users that non-utf8 'encoding' is simply not supported if you use remote plugins. Then advise all API clients to assume utf8 'encoding'.

Seems like a reasonable compromise for now, but until we have a means of handshaking the value of `&encoding` it will not be possible to write plugins in anything other than `utf-8`, unless of course there exists a reliable algorithm for determining `&encoding` from any given string (I don't know much about encodings but I consider this highly unlikely/impossible)

> try to decode utf-8, if it fails just return a byte array

Related to my previous point, isn't there an inherent problem here in that decoding `utf-8` may not fail when the encoding is something other than `utf-8`? i.e. that encodings are not mutually exclusive in their validity?

**Comment by tarruda** [comment]
> Related to my previous point, isn't there an inherent problem here in that decoding utf-8 may not fail when the encoding is something other than utf-8? i.e. that encodings are not mutually exclusive in their validity?

Another point to @justinmk suggestion that utf-8 should be the only explicitly supported option for remote plugins. Even if a buffer contains arbitrary binary data that happens to be valid utf-8, the programmer should deal with it accordingly if he/she only wants raw binary data.

I think the most correct approach is the one taken by the python client, where encoding can be specified on a per-plugin basis via decorators, but to simplify the implementation of clients in other languages it should be fine to take the "assume everything is utf-8" approach.

**Comment by bfredl** [comment]
For `0.1` I think we should document (for users and plugin developers) that `enc != utf-8` is considered deprecated, and for `0.2` we should seriously consider only allowing `encoding=utf-8` ( #2905 ). That would enable internal simplifications and remove much of the remaining confusion. ( For instance `set encoding=utf-16` just doesn't, it really means `enc=utf-8` + `setg fenc=utf-16`, but it would break any rplugin host that just does `data.decode(vim_get_option("encoding"))` )

**Comment by tarruda** [comment]
> For 0.1 I think we should document (for users and plugin developers) that enc != utf-8 is considered deprecated, and for 0.2 we should seriously consider only allowing encoding=utf-8 ( #2905 ). That would enable internal simplifications and remove much of the remaining confusion. ( For instance set encoding=utf-16 just doesn't, it really means enc=utf-8 + setg fenc=utf-16, but it would break any rplugin host that just does data.decode(vim_get_option("encoding")) )

:+1:

**Comment by myitcv** [comment]
>  Even if a buffer contains arbitrary binary data that happens to be valid utf-8, the programmer should deal with it accordingly if he/she only wants raw binary data.

True, but knowing the value of `&encoding` is an important factor in being able to "deal with it". Plugins hosts may well define what values of `&encoding` they support (or don't support for that matter) but they need to be told what the current mode is if they're to do anything other than assume `utf-8`.

Related to previous discussion on how to expose the API in different language hosts, this is where my current thinking has got to for the Go host, the API function `buffer_get_line(Buffer, Integer) -> String` is currently exposed as:

```go
func (b *Buffer) GetLine(index int) (string, error)
```

This currently works because I'm assuming `utf-8` for any `String` value (when unmarshaling and marshaling MSGPACK values), but it can easily be extended to support different encodings if the value of `&encoding` can be communicated via a [handshake](https://github.com/neovim/neovim/issues/1250#issuecomment-134063529) and there exists an algorithm to translate between encoding `X` and `utf-8`.

I've exposed the `String` API type as a Go `string` because 99.9% of the time that's what the plugin developer will want. But in case the underlying `[]byte` is required I'm also considering exposing a raw version:

```go
func (b *Buffer) GetLine(index int) ([]byte, error)
```

But this is very much `vN`

**Comment by myitcv** [comment]
@bfredl :+1: only saw your response after posting the above.

**Comment by myitcv** [comment]
Quick question, if #2905 becomes a reality (I won't even begin to claim I understand the implications one way or the other, but it sounds good) surely this means we should define the API type `String` to  map to MSGPACK `str`?

**Comment by justinmk** [comment]
> but until we have a means of handshaking the value of &encoding it will not be possible to write plugins in anything other than utf-8

@myitcv Just a reminder, `&encoding` is the _internal_ encoding of Vim, it is not the _file_ encoding. There should be zero reason for remote plugins to want support anything other than `encoding=utf8`. (I'm assuming here that a file with `fenc=foobar` will be converted to utf8 before being sent over API to remote plugins--is this correct?)

**Comment by myitcv** [comment]
> @myitcv Just a reminder, &encoding is the internal encoding of Vim, it is not the file encoding. 

Yup agreed. 

> There should be zero reason for remote plugins to want support anything other than encoding=utf8. 

...except when the value of `&encoding` is something other than `utf-8`. Which is where I believe #2905 makes sense, because it not only simplifies the internals of Neovim, but also means you can define the remote plugin API in terms of a single encoding.

> (I'm assuming here that a file with fenc=foobar will be converted to utf8 before being sent over API to remote plugins--is this correct?)

So am I.

**Comment by myitcv** [comment]
@justinmk apologies, replied before you updated your comment:

> [1] Or rather sent as Nvim's already-converted internal utf8 representation.

This would in effect mean that the API is defined with an encoding of `utf-8` - again, I would have no problem with this because it obviates the need for a handshake of the actual encoding being used and moves one step towards #2905.

But again, I don't understand the implications of making such a decision vis as vis the original decision in Vim to support different values for `&encoding`

**Comment by justinmk** [comment]
> ...except when the value of &encoding is something other than utf-8

The point is that remote plugins should not worry about that. It is not supported. We may eventually enforce it explicitly.

> vis as vis the original decision in Vim to support different values for &encoding

Vim's reasons for doing so are not relevant, that's why we moved forward with #2905. I researched the topic thoroughly, see https://github.com/neovim/neovim/pull/2905#issuecomment-115822032 for full details.

**Comment by myitcv** [comment]
> The point is that remote plugins should not worry about that.

Couldn't agree more!

In which case do we not effectively define the API to map `String` to MSGPACK `str`, i.e. encoded using `utf-8`, because any other encoding is not supported?

> Vim's reasons for doing so are not relevant, that's why we moved forward with #2905. I researched the topic thoroughly, see #2905 (comment) for full details.

Great, thanks

**Comment by justinmk** [comment]
> define the API to map String to MSGPACK str

The question is what do you expect from the API if the buffer contents are binary? If a Dict key is not utf8-encodable, how should the API behave? Should we have a "utf8" family of functions that returns `nil` (or something like that) for binary content? 

Note that I believe @tarruda mentioned that, at least, api-info metadata is guaranteed to be utf8.

**Comment by myitcv** [comment]
> The question is what do you expect from the API if the buffer contents are binary?

As @tarruda it's up to me the plugin developer to work that out, but at least we know that `String` values of Neovim settings, e.g. `&fenc` etc will be `utf-8` encoded so we have one fixed point.

> If a Dict key is not utf8-encodable, how should the API behave?

That's presumably a problem for Neovim internally as well... let alone the API?

> Should we have a "utf8" family of functions that returns nil (or something like that) for binary content?

I don't think so. If a `byte[]` is invalid UTF-8 that's all it is. As mentioned above you're probably not expecting it to be valid so you deal with it accordingly.

**Comment by justinmk** [comment]
Ok at this point I'm not clear where to go. What actionable steps are remaining for this ticket?

**Comment by ZyX-I** [comment]
> I'm not sure that's always going to be the case since maps can be converted from arbitrary vimscript dictionaries. If I understood correctly, @ZyX-I only used STR because the keys are known to be utf-8:
> 
> > it was written to make writing future ShaDa plugin easier and ShaDa uses STR for keys because I know that keys in question are ASCII.
> 
> AFAIK vimscript can have arbitrary binary strings in keys

Because *most* of the keys are known to be *ASCII*. There is one (*exactly* one) exception though: `g:VARIABLE_SAVED_IN_SHADA_FILE` may be a dictionary with non-UTF-8 keys which will still be dumped as MAP with STR keys inside: languages I was going to use to read ShaDa files do not care about encoding actually used in STR strings, shada variables are rare and non-&encoding (note: keys and any string values are converted to UTF-8 from &encoding before dumping anything) keys are even more rare.

Though before #3034 and corresponding update whet it was merged it was using `Object` type as an intermediate point, meaning BIN keys.

**Comment by myitcv** [comment]
@justinmk - @bfredl's [comment](https://github.com/neovim/neovim/issues/1250#issuecomment-134080931) suggests a way forward. If it is generally agreed this is the way to go then I think the only outstanding point to consider is whether the API `String` type should be mapped to MSGPACK `str` (on the understanding that the contents of these `str` values may not be valid `utf-8` if the buffer contents are themselves not valid `utf-8`)

**Comment by tarruda** [comment]
>  I think the only outstanding point to consider is whether the API String type should be mapped to MSGPACK str (on the understanding that the contents of these str values may not be valid utf-8 if the buffer contents are themselves not valid utf-8)

If we did that, we would be breaking compatibility with msgpack libraries written in languages that have distinct binary and character strings. Think about it: The msgpack parser receives a STR type and tries to decode using a language-specific utf-8 library which would probably result in a exception

**Comment by bfredl** [comment]
Quoting the msgpack spec:

>String objects may contain invalid byte sequence and the behavior of a deserializer depends on the actual implementation when it received invalid byte sequence
>
>    Deserializers should provide functionality to get the original byte array so that applications can decide how to handle the object

However I would guess many implementations don't do the latter, and just throws an exception as @tarruda said...

**Comment by tarruda** [comment]
> However I would guess many implementations don't do the latter, and just throws an exception as @tarruda said...

 I had missed this part of the spec, but found the two paragraphs to be a bit contradictory: Is the behavior implementation-specific or should the deserializer provide the original byte array? Because if the specification says the original byte array should be returned then we might very well map String to MSGPACK_OBJECT_STR and let plugins handle it

**Comment by myitcv** [comment]
@bfredl thanks, I too had missed that reference in the spec.

> Because if the specification says the original byte array should be returned then we might very well map String to MSGPACK_OBJECT_STR and let plugins handle it

@tarruda :+1: to this. 

Assuming [@bfredl's comment from earlier](https://github.com/neovim/neovim/issues/1250#issuecomment-134080931), `vim_get_option("encoding")` will then by definition be a valid `utf-8` string (because the valid values this option can assume contain only valid `utf-8` runes (to use the Go parlance)).

The only documentation point needed at that stage will be to highlight where in the API it's possible for there to be invalid byte sequences in these `String` values that plugin writers will have to handle. The contents of a buffer is an obvious one (e.g. `buffer_get_line`), there will be others. It will be down to plugins as you suggest to either test `&fenc` and/or the validity of the string (in Go this would be via [`utf8.ValidString`](http://godoc.org/unicode/utf8#ValidString))

**Comment by myitcv** [comment]
> `vim_get_option("encoding")` will then....

I use this simply as an example of an option that has a predefined set of values. I realise now it was a poor choice of example given the conversation regarding `&encoding` above.

**Comment by justinmk** [comment]
:+1:  It's settled then:

> map String to MSGPACK_OBJECT_STR and let plugins handle it

**Comment by ZyX-I** [comment]
@myitcv How is `&fenc` related? By the time plugin gets buffer contents via RPC &fenc must *already* be used by NeoVim to convert from it to &encoding.

**Comment by myitcv** [comment]
@ZyX-I - complete agree. It is only relevant if the plugin needs to know the file's original format. I used `&fenc` (and indeed `&encoding`) earlier as an example of a option that can take a list of predefined values... poor choice of option given the topic under discussion in this thread.

**Comment by myitcv** [comment]
@justinmk - is there any reason this is now `0.2` as opposed to `0.1`? I ask because until `String` is mapped to `MSGPACK_OBJECT_STR` there's lots of coding required in typed plugin hosts like Go to map from `BIN` to their native string types, e.g. when handling dictionary keys. This is painful, particularly if (like me) you are using code generation for the MSGPACK layer.

This change is also a breaking change for any existing plugin hosts.

Therefore I would argue this needs to be a `0.1` issue.

Surely the change is not that significant?

**Comment by justinmk** [comment]
@myitcv If someone sends a PR I would be fine with that but otherwise this cannot block 0.1

We reserve the right to make all kinds of breaking changes for Neovim-specific features until 1.0.

**Comment by bfredl** [comment]
@justinmk I'm looking into it
