### ISSUE TITLE
Sticky Buffers

### ISSUE THREAD

**Issue by amitlevy21** [neovim/neovim#12517]
### Environment
- `nvim --version`:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?: no
- Operating system/version: Arch linux
- Terminal name/version: alacritty 0.4.3
- `$TERM`: alacritty

### Actual behaviour

This is a suggestion to solve a general problem plugin developers encounter.

Consider the following scenario:

You have a file manager plugin installed (like NERDTree) and you wish to keep it's buffer through your nvim session.
The main problem is that if you try to open another file (For example with :FZF) you need to check if your focus is not on the file manager buffer or else this would happen:

![](https://cloud.githubusercontent.com/assets/675604/11937133/891f0592-a7f9-11e5-8dd3-24aaa7da93e0.gif)
(Taken from https://github.com/junegunn/fzf/issues/453)

The workaround is to use hacky vimscript to try detect the buffer name and then shift the focus:
```vim
nnoremap <silent> <expr> <Leader><Leader> (expand('%') =~ 'NERD_tree' ? "\<c-w>\<c-w>" : '').":FZF\<cr>"
```
But you'll have to use the prefix `(expand('%') =~ 'NERD_tree' ? "\<c-w>\<c-w>" : '')."` for each possible command you would like, which is tedious.
What if you would like to switch from NERDTree to other file manager? You would have to change everything to match the new buffer name.
This use case is also relevant when using a terminal buffer in normal mode, I don't want to accidently overwrite it with something else.

Plugin developers cannot make their plugin to act nicely with other plugins as fzf developer describes the problem perfectly in https://github.com/junegunn/fzf.vim/issues/326#issuecomment-282936932
### Reproduce with nvim -u NORC
```
nvim -u NORC
install fzf.vim and NERDTree
:NERDTREE (opens nerdtree)
Focus nerdtree buffer
:FZF and choose any file
nerdtree is gone

```
### Expected behaviour

Opening a file when the focus is on a buffer that I would like to keep, the file will be open in a different buffer or a vertical split if there are no more buffers.
Maybe marking buffers with sticky mode which can only be close only with :quit ?

```

1. nvim -u NORC
2. install fzf.vim and NERDTree
3. :NERDTREE (opens nerdtree)
4. Focus nerdtree buffer
5. Mark buffer as sticky
6. :FZF and choose any file
7. The file is opened in a split 
8. Focus nerdtree buffer
9. :FZF and choose any file
10. The file is opened in the same split as in step 7


```

Is there a better solution for this problem other than detecting buffer names?

I'm aware there are mapping to open files in vertical or horizontal split. But the main issue is that I constantly need to know where my focus is and be careful not to overwrite a buffer that I want to keep.

Thank you for your time.

**Comment by Shatur95** [comment]
It would be very useful. Without this I need to create a function and wrap all commands that changes current buffer.
There is also `switchbuf` option, but it  honored only for quickfix window.

**Comment by Shatur95** [comment]
Could you resend the issue to the [vim](https://github.com/vim/vim) repo first? Maybe it will be better to just backport it.

**Comment by amitlevy21** [comment]
Sure, done: https://github.com/vim/vim/issues/6445

**Comment by stevearc** [comment]
I would love to see this get a proper implementation in vim core, but in the meantime I made a plugin that mimics the functionality as best I could with some hacks: https://github.com/stevearc/stickybuf.nvim

**Comment by justinmk** [comment]
That's a lot of words. IIUC, the one-sentence feature request is:

> lock a buffer to a window

**Comment by ColinKennedy** [comment]
I gave this work a shot and have something about ... 70% working. Not every command is 'stickybuf' aware yet but most of the important ones are in already.

https://github.com/ColinKennedy/neovim/tree/add_stickybuf

It'll eventually become a Vim PR, I just started in neovim since that's my daily driver. Once the holiday season is over I'll be able to focus on completing the missing commands + polish

**Comment by will** [comment]
Congrats on getting it upstreamed to vim @amitlevy21!

**Comment by amitlevy21** [comment]
Don't thank me, thank @ColinKennedy for his awesome work! He's the one who worked on the design and PR

Thank you, @ColinKennedy ! 👏

**Comment by ColinKennedy** [comment]
Looks like it merged while I was asleep, what a great way to wake up! haha

Now to get this into Neovim.

There's a patch merge here https://github.com/vim/vim/commit/215703563757a4464907ead6fb9edaeb7f430bea

and then it looks like a small commit afterwards was made https://github.com/vim/vim/commit/58f1e5c0893aed47d762f5698a1ebebc05ec9819

FYI it might just be easier to take from my Neovim branch that I was working off, https://github.com/ColinKennedy/vim/tree/add_stickybuf, rather than starting from scratch. There were two WIP things left in that branch, I left a `PR.md` and `TODO.md` with personal notes that we'd want to remove + rebase/squash away and and a compile warning that I hadn't solved yet.

```
 ../src/nvim/window.c:139:6: warning: function declaration isn’t a prototype [-Wstrict-prototypes]                            
  bool check_can_set_curbuf_disabled()
```

Other than that, my other Neovim-based branch should be in a good state. I'd do the Neovim patch myself but I've never patched to Neovim before and it'd take some time to figure out how to do it properly. If anyone in the know wants to volunteer, I'd appreciate it!
