### ISSUE TITLE
Allow `autocmd TextYankPost * silent! lua require'vim.highlight'.on_yank()` to be disabled in macros

### ISSUE THREAD

**Issue by kdheepak** [neovim/neovim#12540]
- `nvim --version`:

```                                                                                                 ─╯
NVIM v0.5.0-574-g352831229
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/usr/local/opt/gettext/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Actual behaviour

Currently, when this `autocmd` is set, when a user yanks text it highlights the yanked region. If a user yanks text as part of a macro, it will highlight the corresponding region during each invocation of the playback of the macro.

### Expected behaviour

Don't highlight region during playback of macro.

### Reasoning

It's a little slow to play macros when this is enabled. I've also experienced a neovim crash once when playing back the same macro over 1000 times (using `1000@@`).

Pinging @clason @tjdevries

**Comment by clason** [comment]
Hmm, that is a reasonable suggestion, but I'm not sure it's possible -- I don't see any way for `TextYankPost` (or any autocommand) to know whether it is executed within a macro (@tjdevries?)

The best thing I can offer is the suggestion to clear the autocommand at the start of the macro and reset it at the end (make a simple `ToggleHighlight()` function for this).

**Comment by clason** [comment]
But the crash shouldn't happen either way. A hard crash points towards the `vim.defer_fn` function, which uses timers from the exposed libuv loop. Can you try to reproduce it (e.g., by using longer timeouts to ensure that the timers overlap more)? What happens if you move the highlights to a common namespace (`hl_yank` instead of anonymous `{}`)?

**Comment by kdheepak** [comment]
I tried to replicate it with a simpler example. 

I set the following in my vimrc:

```vim
augroup LuaHighlight
  autocmd!
  autocmd TextYankPost * silent! lua require'vim.highlight'.on_yank("IncSearch", 1500)
augroup END
```

1) Open a 1000 line long file
2) `gg0`
3) `qq0y$P0q`
4) `1000@q`

Things that I noticed:

1) Even after running a few times, neovim did not crash. My earlier experience was more complicated: yanking text, pasting it elsewhere in the line, then making edits.
2) CPU usage goes up to 30% during this process.

> What happens if you move the highlights to a common namespace (hl_yank instead of anonymous {})?

I'm not sure what you meant by this?

**Comment by tjdevries** [comment]
maybe we should add another param @clason for `options` or something and we can disable `visual` and `macro` by default -- I think we can tell if we're replaying a macro in nvim (although we might have to add the info to v:event again). What do you think of that? We can make those the default as well, since it seems much better UX than the current experience.

**Comment by clason** [comment]
@tjdevries If we can add the macro replaying to `v:event`, that solves the issue -- but that might require more messing with the C code than I'm comfortable with -- in the same way as the `visual` check. I wouldn't make disabling visual on yank the default, though (I do like the feedback that it actually yanked, even for visual selection...) 

How would you specify the option? A passlist of event properties that need be set, or a blocklist of properties that shouldn't be set, or...?

**Comment by tjdevries** [comment]
I was just thinking a dictionary of "enabled/disabled" modes.

```lua
require'vim.highlight'.on_yank("IncSearch", 1500, {visual = false, macro=true})
```

Something like that.

**Comment by tjdevries** [comment]
I think there's probably some global for "in a macro", similar to the visual one, so we could probably figure that out if we wanted.

**Comment by clason** [comment]
> Something like that.

But that's a bit brittle, isn't it, since it relies on a hardcoded list of (manually implemented) "modes" (which isn't really a vim concept)? I thing it might be more reliable to directly refer to the `v:event` fields so the function doesn't have to be adapted every time a new field is added (or changed). On the other hand, that makes it a bit more complex to use... There's a trade-off here; not sure what the best choice is.

> I think there's probably some global for "in a macro", similar to the visual one, so we could probably figure that out if we wanted.

If by "we", you mean "I", sure ;) I definitely have no idea where to even start :)

**Comment by kdheepak** [comment]
> I think there's probably some global for "in a macro",

Is it this?

https://github.com/neovim/neovim/blob/225f0bcd98dd8ff8cab964f13816dfdf327038ae/src/nvim/globals.h#L628

**Comment by clason** [comment]
But isn't that already exposed to lua (@tjdevries)?

**Comment by tjdevries** [comment]
Ah, you can just `vim.fn.reg_executing() ~= ''`

**Comment by clason** [comment]
I think that's the cleanest way -- maybe add this to the example in the doc?

**Comment by kdheepak** [comment]
So you are saying users should use something like this?

```vim
augroup LuaHighlight
  autocmd!
  autocmd TextYankPost * silent! lua if vim.fn.reg_executing() == '' then require'vim.highlight'.on_yank() end
augroup END
```

**Comment by tjdevries** [comment]
Yeah, adding that to the docs should probably "fix" it. 

Although I do feel like it should be disabled in reg executing by default, but it's fine.

**Comment by clason** [comment]
> Although I do feel like it should be disabled in reg executing by default, but it's fine.

OK, I accept that :) I just thought that the visual feedback might be useful in macros as well.

So you'd add an option to enable in macros (default false)? I'm not fully convinced to add the `visual` in there -- it does make sense, once you add optional overrides, but it feels a bit arbitrary to have `macro` and `visual` and nothing else... (Because you have to hard-code how the options map to "modes", so it's not very extendable -- and then you'd have to validate the dict...)

**Comment by tjdevries** [comment]
well I'm just suggesting the last parameter is an option dict, with a few keys that we describe in the docs for `on_yank`. For now it would just have:

```
enabled_for (table): table containing keys for controlling behavior of highlights. Keys are:
  `visual`: If the highlight came from visual mode
  `macro`: If the highlight came while executing a macro
```

And the code would just be like:
```lua
function on_yank(...)
  opts = opts or {}
  if opts.visual == false and event.visual == true then return end
  if opts.macro == false and vim.fn.reg_executing() ~= '' then return end
  ...
end
```

Similar to that idea (not sure if the logic or defaults are correct, but that's the idea anyway)

**Comment by clason** [comment]
OK, makes sense. I'll make a PR.

Out of interest, is there a performance issue with `if x then do_something end; if y then do_something end;` vs. `if x or y then do_something end`?

**Comment by tjdevries** [comment]
there is I think 0 difference, particularly for luajit. I wouldn't worry about it in terms of perf (and people would do these checks anyway, so it's all the same).

**Comment by tjdevries** [comment]
(agreed on defaults)
