### ISSUE TITLE
Package neovim for winget

### ISSUE THREAD

**Issue by Mikaela** [neovim/neovim#12571]
- Operating system/version: Windows 10 (2004 / 19041.329)

I would like to install Neovim on Windows directly from [Winget, the new package manager](https://github.com/microsoft/winget-cli/) instead of having to install Chocolatey or extract the files by myself. I think it can also be beneficial for Neovim as it will likely be shipping with Windows in the future. Vim is also available through it as `vim.vim`

* https://github.com/microsoft/winget-pkgs/

**Comment by teto** [comment]
winget is the way forward for windows apparently so yeah that would be nice, but it doesn't necessarily involve this repo, more like the winget repos ?

**Comment by erw7** [comment]
winget only supports `exe`, `msi`, `msix`, `inno`, `wix`, `nullsoft` and `appx`. I think we need to provide one of these. The build with the tag in AppVeyor seems to create an NSIS package (`nullsoft`), but it seems to have been thrown away without being published anywhere at the moment.

I tried it locally and If I don't create a shortcut to the Start menu during installation, the uninstaller seems to try to remove `C:\ProgramData\Microsoft\Windows\Start Menu\Programs`. So it may be dangerous to publish this as is.

**Comment by Jarmos-san** [comment]
Just for a heads up, `winget` support for `.zip` files is [expected to be shipped by March 2021](https://github.com/microsoft/winget-cli/blob/master/doc/windows-package-manager-v1-roadmap.md#windows-package-manager-roadmap--timeline) with `winget v0.16`. The milestone is listed [here](https://github.com/microsoft/winget-cli/milestone/18) & there's a [pretty active discussion](https://github.com/microsoft/winget-cli/issues/140) on the topic going on as well.

**Comment by itsme-alan** [comment]
heads up: winget is now v1.0 and will soon be shipped in stable versions of Windows

**Comment by itsme-alan** [comment]
I would recommend that neovim use [MSIX](https://github.com/microsoft/msix-packaging) if possible

**Comment by Jarmos-san** [comment]
> I would recommend that neovim use [MSIX](https://github.com/microsoft/msix-packaging) if possible

Sounds like a good plan, but is there any automated way to do so? AFAIK, there's a feature request [(see issue #396)](https://github.com/microsoft/msix-packaging/issues/396) on the msix-packaging repository for a GitHub Action. So, if there's any progress on that end, I believe it should be fairly easy to build & distribute Neovim through `winget`.

**Comment by itsme-alan** [comment]
> Sounds like a good plan, but is there any automated way to do so? AFAIK, there's a feature request (see issue #396) on the msix-packaging repository for a GitHub Action. So, if there's any progress on that end, I believe it should be fairly easy to build & distribute Neovim through winget.

I found this repo which shows how to set up a CI/CD pipeline for building MSIX apps for WPF apps. It should work the same for neovim: https://github.com/microsoft/github-actions-for-desktop-apps

> Personally, I've stuck with scoop for installing a couple other similar software I need. And I suggest doing so as well until winget matures a bit more.

`winget` is made by Microsoft so more people are likely to use it.

**Comment by swssr** [comment]
Here to plus one this. I instinctively assumed it'd there.

**Comment by clason** [comment]
PSA: a drive-by "plus one" will not move this forward. Somebody familiar with building and distributing apps on Windows (as well as our CMake build system and GH Actions) needs to make a PR.

**Comment by adityamwagh** [comment]
Any update on when this is going to be done?

**Comment by RenFraser** [comment]
I have experience packaging apps for windows using CMake/CPack. I can't make any promises because I'm very busy at the moment but I'll see how I get on and make a PR if it works out.

**Comment by RenFraser** [comment]
Hi all, I've added a [draft PR](https://github.com/neovim/neovim/pull/17390) for the installers. While I'm figuring out the CI steps, If you'd like to try them out in a debug build, please clone [my fork's feature/packaging branch](https://github.com/RenFraser/neovim/tree/feature/packaging) and run the following commands:

Make a build directory and cd into it:
```shell
mkdir build
cd build
```

Run CMake configure step
```shell
cmake ..
```

Build Neovim
```shell
cmake --build .
```

Run CPack to generate the installers (and zip)
```shell
cpack
```

Once done, you should see an msi, exe and zip file for neovim. I'd recommend using the exe (NSIS) so that you can add neovim to your path during installation, since it's a little easier ;).

**Comment by RenFraser** [comment]
The [PR to address this](https://github.com/neovim/neovim/pull/17390) has been merged. Looks like we can close this issue @Mikaela :)

**Comment by mjlbach** [comment]
Someone will need to make the PR to winget-pkgs, but the barrier from the neovim side is gone thanks to @RenFraser

**Comment by adityamwagh** [comment]
I can do it. Any idea how I can get started?

**Comment by just1a-person** [comment]
i recommend creating a automated Github action to publish it to winget-pkgs


https://github.com/microsoft/winget-create#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline

**Comment by RenFraser** [comment]
You can pretty easily do it through their command line script. You could also reference/diff it against the [existing vim manifests](https://github.com/microsoft/winget-pkgs/tree/master/manifests/v/vim/vim) to make sure everything looks good. 

When I had a look after the merge of the PR, it seems we'll have to wait for the 0.7 release of neovim due to winget-pkg not having support for pre-release packages. If I'm wrong and we can do it, please correct me though as I'm also keen to get going with winget and neovim.

**Comment by tajetaje** [comment]
Just gonna leave this as a note here https://github.com/microsoft/winget-pkgs/pull/55112#issue-1174673154

**Comment by mjlbach** [comment]
Yup, I took a crack and it and basically gave up, as currently there is not a good way to push a nightly release, so I'll only package the stable version (0.7) when it is released, as that will be the first release via which we will distribute MSI installers.

**Comment by itsmeboy0** [comment]
> Once done, you should see an **msi**, **exe** and **zip** file for neovim in this same `build` directory. I'd recommend using the exe (NSIS) so that you can add neovim to your path during installation, since it's a little easier ;).

@RenFraser is it possible to have the MSI installation add Neovim to path? An NSIS installer seems redundant to me.

**Comment by mjlbach** [comment]
@itsmeboy0 the neovim team takes no responsibility for packaging neovim, we don't maintain any official packages for any repositories (other than the flatpak/snap/appimage/GH releases.

**Comment by RenFraser** [comment]
>@RenFraser is it possible to have the MSI installation add Neovim to path? An NSIS installer seems redundant to me.

Yes, it is, it's just harder to do. You need to create wix patch files to tell wix to do certain things, like install to a specific location. I don't know how to do it but surely there'd be some sort of command available in their documentation. 

One thing that's bothered me since the merge of this PR is that Neovim will install to two different locations, depending on which installer is used, when really the zip, msi and exe should align on a common installation directory. Now that I'm thinking about it again, I'll just make the issue.

**Comment by itsmeboy0** [comment]
Right now, the MSI and EXE installers install in the same location, wouldn't that conflict with each other? (Possible scenario: I install Neovim for the first time using MSI and someone updates it with the NSIS installer) Might be another reason to just have one installer.

Second, the installer icon isn't transparent. Can you fix this?
![image](https://user-images.githubusercontent.com/75471378/162557333-858776e4-39f4-4aa3-9c0e-bacfb8d64b94.png)

**Comment by RenFraser** [comment]
Yes, they may conflict with each other. As you've seen, they'll install alongside each other. Not sure what the fix is right now. As a last resort, we could remove one of them, though I'd rather show a warning check to the user. Something along the lines of "Are you sure you want to overwrite an existing installation of Neovim?".

Sure, here's the PR: #18051.

**Comment by sitiom** [comment]
Looks like 0.7.0 has reached stable. I have created a PR of Neovim to Winget: https://github.com/microsoft/winget-pkgs/pull/57882
