### ISSUE TITLE
<S-Esc> mapping doesn't work

### ISSUE THREAD

**Issue by nkgm** [neovim/neovim#12584]
- `nvim --version`: NVIM v0.4.3 Release (homebrew)
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: macOS 10.15.5
- Terminal name/version: iTerm 3.3.11 (CSI u option enabled)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
inoremap <S-Esc> hello
```
Enter insert mode and hit Shift+Esc.

### Actual behaviour
Goes back to normal mode (received as plain `<Esc>`)

### Expected behaviour
Should insert "hello".

I ensured iTerm sends the correct escape sequence `^[[27;2u`, and similar maps (`<S-Enter>`, `<S-Tab>`) work as expected.

`:call nvim_input("<S-Esc>")` works as expected, after @jamessan's suggestion.

**Comment by jamessan** [comment]
There are two issues here.

1. https://github.com/neovim/neovim/blob/f137307dcee02ee287f77b986281232b42d36a86/src/nvim/tui/input.c#L201 unconditionally sends `<Esc>` into the input buffer, regardless of whether there are modifiers.
1. If we add a `key->modifiers == 0` check there, then the `termkey_strfkey()` call incorrectly formats the key as `<S-Escape>`. (@leonerd)

I'm _guessing_ that's why there's a special clause just for the escape key, so we should probably just improve that to directly handle the modifiers.  I'll double check some of the other examples that were brought up on gitter.

**Comment by jamessan** [comment]
I think some of the other issues are also likely incompatibilities between how termkey formats the combo and what nvim expects.

**Comment by jamessan** [comment]
The other example discussed was `<C-S-L>` but termkey sends unicode as the character instead of including `S-` in the modifier list.  That is, `<C-L>` and `<C-l>` are how things get formatted instead of `<C-S-L>` and `<C-L>`.

Key notation in Vim is always with the capital letter, so we need to specifically coerce termkey's format for ascii characters into the `<C-S-` form on input.  That should at least handle getting the right data _into_ nvim.

The other issue is then ensuring the map commands keep `<C-S-L>` and `<C-L>` distinct.

**Comment by jamessan** [comment]
Hmm, according to `:help key-notation`, we do handle `<M-a>` and `<M-A>` distinctly.  That's even true for Vim.  It looks like this issue is specific to when ctrl is present.

I'm not sure why that's the case other than the historical baggage of Vim (and terminals in general).  It will probably be least disruptive to require the `<C-S-...>` form.

**Comment by glacambre** [comment]
Related issue: https://github.com/neovim/neovim/issues/12037
