### ISSUE TITLE
Neovim needs a REPL!

### ISSUE THREAD

**Issue by a-elhag** [neovim/neovim#12629]
I'm a python programmer myself and I know the community has brought forth lovely plugins that try to extend the use of Neovim to allow it to REPL. But unfortunately, they are unoptimized, taking up a lot of spaces. Moreover, there are numerous bugs with them and they don't play nice with virtual environments. 

I would like to see an improvement to Neovim where I can select code in Screen 1 and send it to Screen 2 with a couple of options:

**1) Can send this code to another buffer, whether it is opened in another tab or if it is closed.** 

The implementation is pretty simple, as soon as the shortcut key or command is used letters pop up on all open screens to ask where you want to send it.

<Key> (a, b, c...)

If you want to send it to another tab, then you can just send
<Key> t (a, b, c ...)

If you want to send it to any generic buffer
<Key> b (buffer name/number)

And if you want to set it up with an external terminal/kernel
<Key> x ( )

**2) Only send subcode like Matlab.** 

In Matlab, you can segment your code using %% signs. In Python, I have seen this implemented via ##. 

**3) Code is formatted correctly when sent**

Again, I will use python as an example. But if I'm editing in a .py file, I would like my tabs/spaces to remain exactly as they are because it is syntactically important. 

As a conclusion, I understand that Vim is not meant to be an IDE but over the years that hasn't stopped IDE like features from being added to the benefit of us all. Terminals and asynch job support are incredible innovations. Adding a REPL would take Vim to the next level.

**Comment by glacambre** [comment]
>I know the community has brought forth lovely plugins that try to extend the use of Neovim to allow it to REPL. But unfortunately, they are unoptimized, taking up a lot of spaces. Moreover, there are numerous bugs with them and they don't play nice with virtual environments.

What is the advantage of doing this in Neovim? Does having access to Neovim's lower-level C APIs make building REPLs easier?

I guess since Neovim embeds an LSP client it'd make sense to also have an [nrepl](https://github.com/nrepl/nrepl) client, but since it is a generic protocol for multiple languages I'm not sure it'd solve your problem with python's virtual environments.

>1) Can send this code to another buffer, whether it is opened in another tab or if it is closed.

I think this would be useful to have even outside the scope of repls. For example, you can't currently interact in a sane way with terminal buffers. `nvim_buf_set_lines` tries to overwrite the content of the buffer and `nvim_input`/`nvim_feedkeys` require you to move the cursor to the buffer you need, which makes scripting interactions impossible. It would be nice to have a function like `nvim_buf_input` which would forward the input to the right buffer without moving the cursor.

>The implementation is pretty simple, as soon as the shortcut key or command is used letters pop up on all open screens to ask where you want to send it.

I think this kind of user interface should be left to plugins. If neovim only provides lower-level access to a protocol, different plugins can provide different ways of accessing it (e.g. with your idea or with fuzzy-matching on the name of buffers or with something entirely different that we haven't thought about yet).

**Comment by tjdevries** [comment]
I think if you have the job id for the terminal, you can send things directly to the terminal with `chansend`.

**Comment by hardenedapple** [comment]
Curious whether the approach I took in https://github.com/hardenedapple/vsh would be useful for you.
(I expect you could modify that plugin to suit your own needs)

It does what tjdevries suggested above -- each `vsh` buffer has its associated job id.
The keybindings are different to what you suggested:  In one python buffer I set the default "send" buffer and then you have an operator mapping (and command that can take ranges) which send to that the default buffer you've set up.

It automatically handles python virtual environments etc since it only starts a shell -- you just then type `source .../activate` and `python` to start the python REPL

HOWEVER:  For python especially, the REPL accepts different code than would be accepted in a module/script.
e.g. a newline in the middle of a function will end the function.
For my purposes I just have a different mapping for sending python code that avoids newlines and adds one at the end of whatever I'm sending.

**Comment by CKolkey** [comment]
This may be what you are looking for: https://github.com/jpalardy/vim-slime

**Comment by ggandor** [comment]
@tjdevries Is there an API equivalent of `chansend` or something else, i.e., can this be done from Lua without `vim.cmd`? I haven't found anything yet.

**Comment by bfredl** [comment]
>  Is there an API equivalent of chansend or something else, i.e., can this be done from Lua without vim.cmd?

I plan to add this quite soon #13567

**Comment by teto** [comment]
MR merged and there are already plugins doing this.
