### ISSUE TITLE
cursor stays in the command line after input() if the buffer doesn't change

### ISSUE THREAD

**Issue by x-yuri** [neovim/neovim#12707]
- `nvim --version`:

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Arch Linux
- Terminal name/version: `urxvt-9.22`
- `$TERM`: `rxvt-unicode-256color`

### Steps to reproduce using `nvim -u NORC`

`1.vim`:

```vim
function! F1()
    call input('> ')
    " redraw
    " echo ''
    return ''
endfunction
inoremap <expr> a F1()
```

```
$ nvim -u NORC -S 1.vim
```

Then press `aa<Enter>`.

### Actual behaviour

The cursor stays in the command line:

![](https://i.imgur.com/27yz9Xa.png)

### Expected behaviour

The cursor returns to the buffer:

![](https://i.imgur.com/QJJVXtz.png)

Combined with `redraw` and `echo ''` it produces even more weird effects:

![](https://i.imgur.com/ACnhGuB.png)

Or under `tmux`:

![](https://i.imgur.com/gSvsLZ5.png)

It works as expected in `vim-8.2`:

![](https://i.imgur.com/bWMidu8.png)

**Comment by JaySandhu** [comment]
Very high quality bug report, made it easy to reproduce. I tried to address the issue (https://github.com/neovim/neovim/pull/12837).

**Comment by x-yuri** [comment]
> Very high quality bug report

Sorry for a nonessential comment. It's just that I don't often get praised for bug reports :) But well, they're probably not always good.

**Comment by JaySandhu** [comment]
A few more bugs related to expression mappings. These could maybe go in a separate issue, but I'll document them here for now.

`nvim --version`
```
NVIM v0.5.0-653-g948e625e1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/usr/local/opt/gettext/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

Features: +acl +iconv +tui
See ":help feature-compile"
```

## 1. Misplaced character after `cmap <expr>` results in error

#### Repro

`:cnoremap <expr> x execute('throw 42')`
Type: `:testxing`

#### Actual behavior:
![Screenshot 1](https://i.postimg.cc/nh4m7tZ7/Screen-Shot-2020-09-05-at-17-37-49.png)

#### Expected behavior:
![Screenshot 2](https://i.postimg.cc/8zQWjC8N/Screen-Shot-2020-09-05-at-17-38-37.png)

## 2. Command line not restored after `cmap <expr>`

#### Repro

`:cnoremap <expr> x input("> ")`
Type: `:testx<CR>`

#### Actual behavior:
![Screenshot 3](https://i.postimg.cc/9FqZm7nL/Screen-Shot-2020-09-05-at-17-36-58.png)

#### Expected behavior:
![Screenshot 4](https://i.postimg.cc/NGnRv4py/Screen-Shot-2020-09-05-at-17-36-27.png)

Vim has the same bug in both cases. In the first case, the Vim version is worse.
