### ISSUE TITLE
Support for :normal inccommand

### ISSUE THREAD

**Issue by pianocomposer321** [neovim/neovim#12709]
Currently, the only commands that support neovim's inccommand option are `:s` and its relatives. One feature I would _love_ to see is the `:normal` command with live changes. This would mostly eliminate the need for plugins like https://github.com/mg979/vim-visual-multi, which IMO do things differently than "the vim way", with inconvenient keybindings such as Alt+up/down.

**Comment by jcorbin** [comment]
- https://github.com/neovim/neovim/issues/7370
- https://github.com/neovim/neovim/issues/7257

**Comment by teto** [comment]
yeah many would like it but it's non trivial. I had tried https://github.com/neovim/neovim/pull/11958 but seems like @bfredl had a more generic approach in mind. Closing as duplicate.

**Comment by pianocomposer321** [comment]
@teto @jcorbin unless I'm mistaken, #7370 is about _plugin_ support for the `:normal` inccommand and #11958 is about the `:global` inccommand. #7257 is about multiple cursors, which, while related, is an entirely separate issue, so I don't really think this is a duplicate.

**Comment by famiu** [comment]
Related to https://github.com/neovim/neovim/discussions/41723. Although this script can't properly add preview for `:normal` by itself, since it would also require filtering out `:normal` commands that do more than just basic editing. That would require some way of parsing a string of Normal mode commands into atoms, similar to `nvim_parse_cmd()` but for Normal mode commands.

Nevertheless, some sort of preview autogenerator script would likely be a stepping stone to adding preview support to a wider range of commands.
