### ISSUE TITLE
netrw bug: by default moving files via mm or selecting via `:MF` doesn't work on files inside subfolder

### ISSUE THREAD

**Issue by thisguychris** [neovim/neovim#12724]
- `nvim --version`: NVIM v0.5.0-619-g1153ac903
- `vim -u DEFAULTS` (version: ) behaves differently? behaves the same
- Operating system/version: Ubuntu 20.04 LTS (via wsl2)
- Terminal name/version: (Microsoft Terminal)
- `$TERM`: xterm-256color
- netrw version (currently using v170g) same bug tested on (v165)

### Steps to reproduce using `nvim -u NORC`

File tree looks like this:
.
├── foo
│   └── bar.txt
└── foo.c

1 directory, 2 files

Steps:
1. `$ nvim`
2. `:Ex`
3. higlight foo, press <kbd>Enter</kbd> to go inside folder foo
4. `:MF *.txt`

### Actual behaviour
Doesn't mark the file.

### Expected behaviour
Should mark the file.

### Screenshot
![image](https://user-images.githubusercontent.com/532797/89498819-911e6580-d7f1-11ea-9cf6-d4ef20e9dbd5.png)

### Additonal bug:

Manually marking a file works, half of the time (only on copy, move doesn't work)

1. `mt` on the target folder
2. `mf` on a file (that's inside a subfolder, not on project root/working directory - where you invoked vim)
3. `mc` works, `mm` doesn't

Also posted this on [vim](https://github.com/vim/vim/issues/6637)

### Additional Context
From Dr Chip's personal page, it seems he has `let g:netrw_keepdir = 0` set [as seen here](http://www.drchip.org/astronaut/vim/index.html#NETRW) . This may be the reason why this bug hasn't been caught for a long time.

As for users, maybe most users use the terminal on moving multiple files instead of `netrw`, surprisingly, `mc` works, which is another tangent where people usually copy files instead of moving.

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim.

Syntax plugins (e.g. for ruby/java/YAML) are maintained by the maintainer listed at the top of the plugin file. Please report to that person, or to https://github.com/vim/vim. Thanks!
