### ISSUE TITLE
[feature request] check nvim version and commit number in vimscript

### ISSUE THREAD

**Issue by antoinemadec** [neovim/neovim#12773]
- `nvim --version`: all
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: Debian testing
- Terminal name/version: N/A
- `$TERM`: N/A

### Actual Behavior
`nvim --version` prints: [nvim_version]-[commit_number_in_that_version]-[commit_hash].
For instance: 
```
> nvim --version
NVIM v0.5.0-631-g37aa9c9c9
```

However:
 - `:echo v:version` prints the vim version (`800`)
 - `:has('nvim-0.5.0')` returns 1
 - `:has('nvim-0.5.0-999-cafedeca')` also returns 1

**Making it impossible for a plugin to know if an nvim commit is present or not.**

### Expected behaviour

I read https://github.com/neovim/neovim/issues/9635 and understand it.
However, I would like neovim to provide a way to check on [nvim_version] and [commit_number_in_that_version] internally, either with a:
  1. `v:nvim_version` variable returning [nvim_version] and [commit_number_in_that_version]
  2.  `has()` function that would properly check the [commit_number_in_that_version] when it is provided

**Is it possible to add 1. or 2. in order to check neovim version and commit number in vimscript?**

Thanks,
Antoine

**Comment by justinmk** [comment]
not sure why you say "version and commit number". It's already possible to check version, `has('nvim-0.5.0')` works as you mentioned.

 So only "commit" is missing. I guess there's no reason _not_ to do this, except that it encourages bad practices. And if someone builds from a tarball instead of a git repo, then a plugin expecting a particular commit will incorrectly complain.

For a prerelease it is expected that users are staying up-to-date. That's life with prereleases. So `has('nvim-0.5.0')` is all that plugins should check.

**Comment by antoinemadec** [comment]
> For a prerelease it is expected that users are staying up-to-date. That's life with prereleases. So has('nvim-0.5.0') is all that plugins should check.

Got it, I guess I was just trying to find a system analog to vim patches for neovim.
Having up-to-date pre-releases works for me: I'll check `has('nvim-0.5.0')`.
Thanks :smiley:
