### ISSUE TITLE
怎么判断nvim的channel的状态

### ISSUE THREAD

**Issue by xklalala** [neovim/neovim#12780]
vim里面可以使用ch_status(channel)来判断，请问nvim里面有类似的方法吗

**Comment by justinmk** [comment]
No. https://github.com/neovim/neovim/pull/5485 is somewhat related. But mostly in Vim the need for ch_status() is because Vim requires plugins to care more about the status. In Nvim, you just call jobstop(). And in Nvim, the job status is refelected in the `on_stdout` handler. `:help channel-callback`
