### ISSUE TITLE
~neovim-ppa/+archive/ubuntu/stable dropped support for Ubuntu 16.04 ?

### ISSUE THREAD

**Issue by vizcay** [neovim/neovim#12946]
After following the instructions on https://github.com/neovim/neovim/wiki/Installing-Neovim the neovim packages is not found in Ubuntu 16.04 (Xenial).

Isn't listed also on https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable:

```
neovim | 0.4.4-1~ubuntu20.04.1~ppa1 | James McCoy (2020-08-24)
neovim | 0.4.4-1~ubuntu18.04.1~ppa1 | James McCoy (2020-08-24)
neovim | 0.4.3-3~ubuntu19.10.1~ppa1 | James McCoy (2020-05-02)
```

I can only add and install via ~neovim-ppa/+archive/ubuntu/stable but I have a couple of plugins failling because of course v5.0 quite new, so that doesn't seem like a viable option for me.

**Comment by jamessan** [comment]
The PPA (like all distribution-specific stuff) isn't maintained by the neovim team, so I'm closing this bug.

That being said, the reason I dropped the 16.04 and 14.04 builds is because the amount of things that needed to be backported became more effort than the time I had to invest in it.  There have been multiple LTS releases since 16.04, so my recommendation would be to upgrade.

**Comment by vizcay** [comment]
@jamessan fair enough, thanks for your fast response.

I've updated the Wiki at https://github.com/neovim/neovim/wiki/Installing-Neovim to reflect those changes.
