### ISSUE TITLE
Old Neovim builds

### ISSUE THREAD

**Issue by medwatt** [neovim/neovim#12961]
- `nvim --version`: 0.5
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: Windows 10
- Terminal name/version:
- `$TERM`:

### Actual behaviour and Expected behaviour
I am using FZF plugin with Neovim on Windows. In the stable build (0.4.4), after searching for a file (using FZF within vim) and you open the file, the file opens instantaneously. In the latest builds, there's a delay of a few seconds for the file to open. Since it might be hard to pinpoint which commit caused this regression, I was wondering if there was a way I could download older builds and narrow down the time when this issue started so I can figure out which commit caused this issue. Is there a repository where older builds are stored ?

**Comment by ktfleming** [comment]
I don't think there's a way to directly download any particular build after 0.4.4 since it all falls under the "nightly" umbrella, but if you're willing to [build Neovim from source](https://github.com/neovim/neovim#install-from-source) on your own machine, you can use `git bisect` on the master branch to find which commit changed the behavior.

**Comment by teto** [comment]
You may want to search `git bisect` if you want to pinpoint the commit that introduced your problem. That is if the problem comes from neovim and not a change in your environment. And apparently we only keep the latests nightly (but neovim is fast and easy to compile).
