### ISSUE TITLE
documentation: nvim_win_get_cursor()

### ISSUE THREAD

**Issue by strait** [neovim/neovim#12973]
- `nvim --version`:  NVIM v0.5.0-635-g8c49e3d50
- Operating system/version: Linux

### Actual behaviour
nvim_win_get_cursor() returns the byte index from the beginning of line in the buffer.

### Expected behaviour
The 'cursor position in the window' should be the actual position in the window grid, not the byte index from the buffer. This will obviously deviate when multi-byte characters are encountered.

**Comment by bfredl** [comment]
The behavior should not be changed but the documentation could be better. While the cursor is a _buffer_ position, but it can be different for different windows into the same buffer, hence it is on the window object.

**Comment by strait** [comment]
Must change any mention of 'columns' to 'byte-offset', because the offset that is get/set is no longer columns in any meaningful way. Where is the API call for the actual column in the window that shows on the screen, for moving the cursor X number of columns left or right, for ensuring vertical alignment, etc.?

**Comment by vigoux** [comment]
#### Hacktoberfest

This needs a documentation change, to fix that you will need to

- edit the doxygen comment of the corresponding C function.
- regenerate the documentation using `./scripts/gen_vimdoc.py`

**Comment by androidpcguy** [comment]
First time contributing to opensource, mind if I take a crack at this?

**Comment by vigoux** [comment]
Not at all, feel free to ask any question here !

**Comment by devabhishekpal** [comment]
Which file has the function? @vigoux

**Comment by vigoux** [comment]
My technique to find a function definition (as I am not an nvim source expert) is to do a little grep :
```
rg "nvim_win_get_cursor"
```

This yeilds `src/nvim/api/window.c:84` as the file/line combination

**Comment by devabhishekpal** [comment]
I did the VSCode search but there were a lot of references to the command

**Comment by androidpcguy** [comment]
Sorry, got really busy with school this week and couldn't work on this. I've updated the comment to reflect the proper behavior. Will submit a PR soon

**Comment by isovector** [comment]
It would be really fantastic to have a function like `nvim_win_get_cursor` that does the right thing for multibyte characters.

**Comment by gerazov** [comment]
It would be nice if this was more of an API change than a documentation change :+1: 

There was an issue with [hop.nvim](https://github.com/phaazon/hop.nvim), which is a `lua` implementation of easymotion-like navigation, that made it misidentify the cursor position for Unicode text https://github.com/phaazon/hop.nvim/issues/245

The call to `vim.api.nvim_win_get_cursor(w)` gives the column, which is around x2 in Unicode of the `virtcol`. I've [fixed](https://github.com/phaazon/hop.nvim/pull/248/files#diff-442dca31e2e341363cee123dca383ccce83bd9b498c4230e7beed9f86e80b3e4) this by using `vim.fn.getcurpos()[5]` which gives the `virtcol` of the cursor, which is the one we see when editing Unicode. 

The issue is that `getcurpos` doesn't accept a window handle, and there are other calls used in multi-window mode that cannot be substituted (lines 79 and 83).

It would be great if `nvim_win_get_cursor` returned the `virtcol` in addition to the line and col, or if it accepted an option to return the `virtcol` instead of the col, or to have a new `nvim_win_get_virtcursor` function :smiley:

**Comment by zeertzjq** [comment]
`getcurpos()` accepts a window handle as of v0.7.0.

**Comment by gerazov** [comment]
But that's the vim api right? I guess `nvim_win_get_cursor` should be faster?

**Comment by justinmk** [comment]
Documentation was updated in https://github.com/neovim/neovim/commit/09dffb9db7d16496e55e86f78ab60241533d86f6 

Also will mention `getcurpos()`.

An enhanced API could make sense as a new issue, but needs to explain the use-case: if you're writing a plugin then `getcurpos()` is perfectly fine; if you're writing a UI then UI events give this info.
