### ISSUE TITLE
Neovim struggles with detecting light vs dark terminal background color within tmux

### ISSUE THREAD

**Issue by khu-md** [neovim/neovim#13000]
Before posting this, I skimmed #9509, #5027, #11534, #12220.

- `nvim --version`: NVIM v0.5.0-cea2417
- `vim -u DEFAULTS` (version: 8.2.1700) behaves differently? **yes**
- Operating system/version: macOS 10.14.6
- Terminal name/version: iTerm2 3.3.12
- `$TERM`: xterm-256color
- tmux version: 3.1b
- shell is bash 3.2 (`which bash` -> `/bin/bash`)

### Steps to reproduce using `nvim -u NORC`

1. Open iTerm2 (using Profile with Color Preset choice 'Light Background')
2. Start tmux session with `$ tmux`
3. `nvim -u NORC` OR `env -i TERM=ansi-256color "$(which nvim)"`
4. `:set bg?`

### Actual behaviour

`background=dark`

### Expected behaviour

`background=light`

**Comment by erw7** [comment]
This is not a bug. It is limited by the terminal(tmux). tmux is not responding to OSC 11.

Ref tmux/tmux#1919.

**Comment by khu-md** [comment]
@erw7 Ahhh... Noted. I really appreciate you taking the time to shed light on this!

**Comment by thesofakillers** [comment]
Is there a workaround for this? I.e. a workaround for detecting color in neovim when using tmux?

**Comment by afirth** [comment]
since tmux 3.2 it _will_ respond, but only if you set the terminal bg inside tmux (who does that)
https://github.com/tmux/tmux/pull/2343 (it's in)

I've finally cracked this in a way i'm happy with - system theme is inherited by gnome-terminal and then tmux. inside .vimrc
```
let s:bg = system('gsettings get org.gnome.desktop.interface gtk-theme | grep -i dark && echo dark')
if s:bg == "dark"
  set background=dark
else
  set background=light
endif
``` 
```
gsettings get org.gnome.desktop.interface gtk-theme
'NumixSolarizedLightGreen'
```
obviously you can tweak this for your theme names.

If you're not doing it there, setting COLORFGBG is an option, but hard to get into _all_ your tmux panes, so I think writing a config file e.g. `echo dark > ~/.vim/bg` and then using `readfile("~/.vimrc/bg","",1)` would work ok
