### ISSUE TITLE
[LSP] Initialize request sets empty 'codeAction', therefore no Flutter+Dart action by default

### ISSUE THREAD

**Issue by bluz71** [neovim/neovim#13057]
Hello Neovim LSP team,

The default initialize request for Neovim sets the following code actions (an empty set):

```json
        "codeAction": {
          "codeActionLiteralSupport": { "codeActionKind": { "valueSet": [] } },
          "dynamicRegistration": false
        },
```

With that setting, the Dart language server provides no code actions upon a `textDocument/codeAction` request.

If I manually fiddle the initialize request to the following I do get Flutter+Dart code actions:

```json
        "codeAction": {
          "codeActionLiteralSupport": {
            "codeActionKind": {
              "valueSet": ["quickfix", "refactor", "refactor.rewrite", "source"]
            }
          }
        },
```

The [vim-lsp](https://github.com/prabirshrestha/vim-lsp) plugin does not specify an empty `codeAction` section, by default it sets the following in [lsp.vim](https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp.vim#L468):

```viml
    \       'codeAction': {
    \         'dynamicRegistration': v:false,
    \         'codeActionLiteralSupport': {
    \           'codeActionKind': {
    \             'valueSet': ['', 'quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite', 'source', 'source.organizeImports'],
    \           }
    \         }
    \       },
```

The [LSC](https://github.com/natebosch/vim-lsc) plugin also specifies a non-empty `codeAction` in the initialize request as noted in [server.vim](https://github.com/natebosch/vim-lsc/blob/master/autoload/lsc/server.vim#L189):

```viml
    \   'codeAction': {
    \     'codeActionLiteralSupport': {
    \       'codeActionKind': {'valueSet': ['quickfix', 'refactor', 'source']}
    \     }
    \   },
```

In both cases the setting of a non-empty `codeAction` value results in Flutter code actions working out of the both. It is extremely confusing to the average LSP user that Neovim LSP code actions do not work for Flutter but they do for vim-lsp and LSC.

Currently Neovim users need to do something like:

```lua
local client_capabilities = vim.lsp.protocol.make_client_capabilities()
client_capabilities.textDocument.codeAction = {
  codeActionLiteralSupport = {
    codeActionKind = {
      valueSet = {
        "quickfix", "refactor", "refactor.rewrite", "source"
      }
    }
  }
}

nvim_lsp.dartls.setup {
  on_attach = lsp_on_attach,
  capabilities = client_capabilities
}
```

This is not obvious at all.

Strong defaults, easily overridable.

I recommend doing what vim-lsp does and set the default `codeActions` to `['', 'quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite', 'source', 'source.organizeImports']`. That is the full set as noted in the [LSP specification](https://microsoft.github.io/language-server-protocol/specification).

Best regards.

**Comment by Jesse-Bakker** [comment]
I am actually not sure what the best default is in this case. From the spec:

"the ability to group code actions using a kind. Clients are allowed to ignore that information. However it allows them to better group code action for example into corresponding menus (e.g. all refactor code actions into a refactor menu)."

and

```
/**
			 * The code action kind values the client supports. When this
			 * property exists the client also guarantees that it will
			 * handle values outside its set gracefully and falls back
			 * to a default value when unknown.
			 */
			valueSet: CodeActionKind[];
```

As we do not support grouping code actions by kind, we'll always "fall back to a default value", which would mean the array should be empty. However, we do support all kinds of code actions (as we support code actions in general), meaning all kinds should be in the array. That is however redundant information, as this value being set already signals `codeActionLiteral`s being supported.

This is another part of the spec that is a bit confusing, as can also be seen from the behaviour of different language servers. rust-analyzer does return code actions with neovim's default value for example, but dartls does not. I lean towards leaving the current default as that feels more technically correct, but I am also not against using your suggestion. This could also be something for `nvim-lspconfig` as it involves a server-specific workaround.

**Comment by bluz71** [comment]
Note, Neovim LSP sends the following `completion` information as part of the `initialize` request:

```json
        "completion": {
          "completionItem": {
            "snippetSupport": true,
            "commitCharactersSupport": false,
            "preselectSupport": false,
            "deprecatedSupport": false,
            "documentationFormat": ["markdown", "plaintext"]
          },
          "contextSupport": false,
          "dynamicRegistration": false,
          "completionItemKind": {
            "valueSet": [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
              17, 18, 19, 20, 21, 22, 23, 24, 25
            ]
          }
        },
```

Notice that `completionItemKind` is fully populated by Neovim LSP. Value 1 translates to `Text`, 2 to `Method`, and so on.

Yet for code actions Neovim LSP sends an empty set for `codeActionKind`:

```json
   "codeAction": {
          "codeActionLiteralSupport": { "codeActionKind": { "valueSet": [] } },
          "dynamicRegistration": false
        },
```

To my eyes there is an inconsistency here.

The following section, as noted above, is interesting:

```
/**
			 * The code action kind values the client supports. When this
			 * property exists the client also guarantees that it will
			 * handle values outside its set gracefully and falls back
			 * to a default value when unknown.
			 */
			valueSet: CodeActionKind[];
```

`The code action kind values the client supports`.

Surely an empty set indicates to the language server that the client does not support any code actions.
And in this case the Dart Language Server is actually not providing code actions.

I strongly believe that Neovim LSP should replicate what it is doing for `completionItemKind` to `codeActionKind` and sending the full set of supported code action options. I don't envisage how that will be harmful.

Best regards.

**Comment by Jesse-Bakker** [comment]
I think there is some confusion about what the phrase "the client supports" means here. I want to make clear that I am not against specifying in the client capabilities that we support all `CodeActionKind`s, so this message is just to explain what I think this capability means and why I think that.

How I interpret "the client supports" here is it meaning the client supports special-casing for the stated kinds. We do that for completions in a way by showing the completion kind in the pop-up menu, but we don't do it for code actions. If we were to support requesting only a certain kind of code action (by supplying the `only?: CodeActionKind[]` parameter in the `CodeActionContext`) for example, or sorting them by kind on the client side, or even just showing the kind next to the action title, that would mean "supporting" these kinds.

The reason I believe these are the reasons for these capability values existing and what they mean is that the only difference between a completion item or code action of a certain "kind" is the "kind" they are tagged with. Resolving/applying the different kinds works in exactly the same way, so if you support applying one kind, you support applying every kind. The sentence "When this property exists the client also guarantees that it will handle values outside its set gracefully and falls backto a default value when unknown." is another reason I think this.

This reasoning is not explicitly stated in the specification, which is why I believe there is a difference in interpretation/implementation in both clients and servers and also why I'm not against filling the `codeActionCapabilites` with all kinds of code actions. I do hope you understand my reasoning about why I think it is technically more correct to leave this list empty (until we implement special-casing for `CodeActionKind`s of course). I think it might be good to file an issue about clarifying the intent of these capabilites in the specification's repo.

**Comment by bluz71** [comment]
> This reasoning is not explicitly stated in the specification, which is why I believe there is a difference in interpretation/implementation in both clients and servers and also why I'm not against filling the codeActionCapabilites with all kinds of code actions. 

Exactly.

The spec is **not clear**, hence language servers can interpret an empty `codeActionKind` a number of ways. We know definitively that Google with it's Dart Analysis Server is choosing to interpret an empty set as meaning the client does not support code actions, even if they are requested later.

Hence, Neovim LSP needs to be pragmatic and choose the option that will cause the least harm. The current behaviour is harmful with respect to Dart, and possibly other language servers (maybe).

This is what other notable (Neo)vim clients are doing:

- [vim-lsp is sending the full set in the initialise request](https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp.vim#L474):
```viml
    \       'codeAction': {
    \         'dynamicRegistration': v:false,
    \         'codeActionLiteralSupport': {
    \           'codeActionKind': {
    \             'valueSet': ['', 'quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite', 'source', 'source.organizeImports'],
    \           }
    \         }
    \       },
```

- [vim-lsc is sending a subset in the initialise request](https://github.com/natebosch/vim-lsc/blob/master/autoload/lsc/server.vim#L191):
```viml
    \   'codeAction': {
    \     'codeActionLiteralSupport': {
    \       'codeActionKind': {'valueSet': ['quickfix', 'refactor', 'source']}
    \     }
    \   },
```

- [I think coc.nvim is also sending a full set in the initialise request](https://github.com/neoclide/coc.nvim/blob/master/src/language-client/client.ts#L2329)
```typescript
      codeActionKind: {
        valueSet: [
          CodeActionKind.Empty,
          CodeActionKind.QuickFix,
          CodeActionKind.Refactor,
          CodeActionKind.RefactorExtract,
          CodeActionKind.RefactorInline,
          CodeActionKind.RefactorRewrite,
          CodeActionKind.Source,
          CodeActionKind.SourceOrganizeImports
        ]
      }
```

We live in an imperfect world where language server vendors can interpret phrases in certain ways. This is clearly the case here. Google with it's Dart Analysis Server is not wrong since the spec is ambiguous.

So I continue to recommend that Neovim LSP set the default `codeActions` in the initialise request to `['', 'quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite', 'source', 'source.organizeImports']`. I see real benefit in doing that and I don't see any harm coming of it.

Best regards.

**Comment by mfussenegger** [comment]
> I see real benefit in doing that and I don't see any harm coming of it.


I think based on the spec the worst case scenario is that the client displays code actions which the client doesn't support. Selecting such a code action would either result in an error or in "nothing happens".

Most code actions result in a workspace edit and that works generic, but there is also the possibility of sending other commands that clients need to know how to handle. See also [this issue 12326](https://github.com/neovim/neovim/issues/12326).


But I'm not sure if any language server uses the code action literals in practice as opt-in for special client command support.

(eclipse.jdt.ls requires additional settings in the `init_options` to enable code actions that require special client handling)

**Comment by Jesse-Bakker** [comment]
I believe these custom commands could also be sent using the non-codeActionLiteral way, and are not spec compliant (which is why eclipse.jdt.ls (and also rust-analyzer) changed their implementation to only send those when the client signals support), so I don't think we should worry about that for fixing this issue. I also ran into an issue today where the neovim client thinks the server does not support code actions if the server responds with a list of `CodeActionKind`s in its `codeActionProvider` server capability. We handle these kinds fine (by just applying them regardless of their kind) so I'll send a PR with a @bluz71's suggestion and correctly resolving server capabilities.

**Comment by bluz71** [comment]
Excellent. Looking forward to seeing this merged.
