### ISSUE TITLE
Quickfix Toc can't be triggered.

### ISSUE THREAD

**Issue by kevinhwang91** [neovim/neovim#13108]
- `nvim --version`: NVIM v0.5.0-757-gc8ce098e7
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version: ArchLinux
- Terminal name/version: alacritty
- `$TERM`: alacritty

### Steps to reproduce using `nvim -u mini.vim +':h h' +'normal gO'`
`cat mini.vim`
```vim
syntax on
```

### Actual behaviour
![image](https://user-images.githubusercontent.com/17562139/96360883-a0a41e00-1153-11eb-8523-a57a3d620a36.png)

### Expected behaviour
`nvim -u NORC +':h h' +'normal gO'`
![image](https://user-images.githubusercontent.com/17562139/96360894-bca7bf80-1153-11eb-94e3-dfa624be5493.png)

It works as expected by using `BufReadPost` event rather than `Syntax`.
https://github.com/neovim/neovim/blob/9817d991403ea3646b9a01234d12c7661ff8c62b/runtime/ftplugin/qf.vim#L40

**Comment by erw7** [comment]
The problem is caused by `autocmd`, in that order. Therefore, the behavior will change depending on the order of calling `syntax enable` and `filetype plugin on` as follows. Of course, it needs to work independently of the call order.

```
# OK
nvim -u NORC --cmd 'syntax enable | filetype plugin on' +':h h' +'normal gO'
# NG
nvim -u NORC --cmd 'filetype plugin on | syntax enable' +':h h' +'normal gO'
```

```vim
# init.vim OK
filetype plugin on
syntax enable
```

```vim
#init.vim NG
syntax enable
filetype plugin on
```

The following lines must be executed after `syntax` has been set. So it seems that we are calling `s:setup_toc()` in the `Syntax` event, but the problem arises because sometimes `ftplugin` is called after `syntax` is set, as shown above.

https://github.com/neovim/neovim/blob/78cd1b9f5a920ce6845cf275fa8c1fdfbf9400a3/runtime/ftplugin/qf.vim#L35

We can call `s:setup_toc()` in any event after syntax is set. How about creating an RP?

**Comment by justinmk** [comment]
This works for me on Nvim 0.10:

    nvim --clean --cmd 'filetype plugin on | syntax enable' +':h h' +'normal gO'
