### ISSUE TITLE
yaml syntax invalid on multiline strings

### ISSUE THREAD

**Issue by andykais** [neovim/neovim#13194]
- `nvim --version`: v0.4.4
- `vim -u DEFAULTS` (version: ) behaves differently? No
- Operating system/version: Arch Linux (rolling release)
- Terminal name/version: `rxvt-unicode (urxvt) v9.22`
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`

copy and paste the following yaml into a file (sample.yml)
```yaml
some_key: |
  not_a_key: abc
  [brackets]

this_is_a_key: def

```

```bash
nvim -u NORC sample.yml
```

### Actual behaviour
the multiline string is treated like regular yaml lines, the result is that we get keys and other yaml syntaxes highlighted inside a multiline string
![screenshot(254)](https://user-images.githubusercontent.com/6627147/97732388-d8448b80-1aac-11eb-8531-3c59b4444a8f.png)

this is better illustrated with a vibrant colorscheme, so here is the same file but using my regular vim config
![screenshot(253)](https://user-images.githubusercontent.com/6627147/97732397-daa6e580-1aac-11eb-923d-680c5ebb88b5.png)

### Expected behaviour
the content for the key `some_key` should all be highlighted as a string, which you can see in the way github highlights the yaml above ^

**Comment by glacambre** [comment]
Since this issue also happens in Vim, the problem probably comes from the syntax file rather than from Neovim. You should contact the [syntax files' authors](https://github.com/neovim/neovim/blob/4ae31c46f75aef7d7a80dd2a8d269c168806a1bd/runtime/syntax/yaml.vim#L3-L4) and ask them to fix this issue and send the result to Vim's maintainers as Neovim doesn't maintain its own runtime files - most of them are directly copied from Vim.

**Comment by andykais** [comment]
can we just @ then on this issue?

**Comment by glacambre** [comment]
>can we just @ then on this issue?

I don't see why not.

>I'm not really comfortable cold calling someones email about syntax bugs.

What if you send a fix along the email? ;D
IMO you shouldn't be too afraid to contact people by email, this is how software has been made for a long time. Plus, given the amount of automated junk we all receive every day, I'm sure they'll be happy to receive a hand-crafted email, even if it's about a bug.

>I'm unsure how to lookup their github usernames from their emails though

You could try creating fake commits with their emails in one of your repositories and seeing if Github resolves that to an account. If this doesn't work you could try sending an email to Vim's mailing list, perhaps the syntax file's authors are subscribed to that.

I'll close this issue because Neovim won't do anything about it until it's fixed in Vim, but feel free to keep using it for questions/guidance :).

**Comment by daviewales** [comment]
Related: https://github.com/vim/vim/issues/11517
