### ISSUE TITLE
Allow passing custom handler to vim.lsp.buf helper functions

### ISSUE THREAD

**Issue by entropitor** [neovim/neovim#13346]
To use a custom handler for one request, `vim.lsp.buf_request` must be used which means that the developer must figure out how to construct the params. It would be nice if the `vim.lsp.buf.*` utilities have a consistent interface to pass a handler as well

### Actual behaviour
We have to use the following, `vim.lsp.buf_request` doesn't accept a handler
```
:lua vim.lsp.buf_request(0, "textDocument/documentSymbol", require'vim.lsp.util'.make_text_document_params(), require'lsputil.symbols'.document_handler)
```

### Expected behaviour
Expected one of the following to work
```
:lua vim.lsp.buf.document_symbol({handler = require'lsputil.symbols'.document_handler})
:lua vim.lsp.buf.document_symbol(require'lsputil.symbols'.document_handler)
:lua vim.lsp.buf.document_symbol(nil, require'lsputil.symbols'.document_handler)
```

**Comment by entropitor** [comment]
Potentially an alternative could also be that there is a `make_..._params` that can be reused to easilly implement it with a different handler

**Comment by mfussenegger** [comment]
https://github.com/neovim/neovim/pull/19213 added a `on_list` handler to a couple of functions.

I don't think it's feasible to have a generic `handler` or `on_response` everywhere because many methods incur multiple steps. For example rename can consist of prepare rename and rename. Code actions involve getting candidates, selecting candidates, optionally resolving the code action. It's unclear where `handler` would get triggered. For the last request? For each client? For all clients once?

I think targeted handlers are the better option and most of the functions to create request parameters are already exposed in the `util` package.
