### ISSUE TITLE
workspaces' resolution with jdtls maven projects

### ISSUE THREAD

**Issue by ChrisAmelia** [neovim/neovim#13398]
- `nvim --version`: `v0.5.0-883-g6af64d384`
- language server name/version: `jdtls`
- Operating system/version: `Ubuntu 18.04 LTS` 

<details>
<summary>nvim -c ":checkhealth nvim lspconfig"</summary>

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: jdtls: configuration checked.

</details>

<details>
<summary>lsp.log</summary>

*before problem*
[lsp.log](https://github.com/neovim/neovim/files/5607565/lsp.log)

*after problem*
[lsp.log](https://github.com/neovim/neovim/files/5607571/lsp.log)

</details>

Given two Maven projects (having their own `pom.xml`) placed in the same directory: `Computer` and `Keyboard`.
Class `Keyboard` cannot be imported in `Computer` as following:

```java
import com.keyboard.Keyboard.Key; // The import Keyboard cannot be resolved

public class Computer {}
```

CoC solves this issue by updating the server's workspace by adding Keyboard's workspace when it's opened in a new buffer i.e. server's workspace has both Computer and Keyboard's workspace.

I tried to replicate the same procedure after #12638 has been merged:

1. Open `Computer.java` then add its workspace with `:lua vim.lsp.buf.add_workspace_folder()`: it's correctly added after checking with `:lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))`.

2. Open `Keyboard.java` (with `:e`) then add its workspace as above.
After having checked the list, it's now empty,
although returning on `Computer.java`, the list contains Computer's workspace but **not keyboard's**.
I assume the list for both buffers are different?

I also tried to manually input Keyboard's workspace in Computer's workspace: it now contains both as expected although the import still cannot be resolved.

**Comment by mjlbach** [comment]
#12638 Doesn't handle the case where you want to open a new buffer (in an added workspace) without launching a new server. Naively, all servers are launched upon opening a new buffer not under the same root directory (so you open a second server instance on workspace folder 2, 3, etc). If you're adding workspace folders without opening something in those workspaces, the server should be aware of them so workspace type code actions/analysis should be supported. the list_workspace_folders stores the workspace folders clientside per language server, so it only records what has been added to each language server. Since separate language servers are opening on buffers workspace folder 2 and 3. I hope that makes sense.

**Comment by ChrisAmelia** [comment]
If I understood it right, I should simply open **one**  buffer and in that one, adding the workspaces I need?

**Comment by mjlbach** [comment]
Yes, but if you open a file in a new buffer in any of the other workspaces you added, it won't use the language server opened from the first buffer. That needs to be implemented.

**Comment by mjlbach** [comment]
I opened this issue https://github.com/neovim/neovim/issues/13440 to track the feature that I believe addresses the problem

**Comment by mjlbach** [comment]
@ChrisAmelia You were using nvim-lspconfig right? Not manually handling this? I'm going to close in favor of 13440 if so, because it basically involves porting some of the root uri management from nvim-lspconfig to core.

**Comment by ChrisAmelia** [comment]
Yes to both.
