### ISSUE TITLE
Weird initial value of lines and columns when nvim-qt starts

### ISSUE THREAD

**Issue by Neur1n** [neovim/neovim#13532]
- `nvim --version`: 0.5.0-828-g0a95549d6
- `vim -u DEFAULTS` (version: ) behaves differently? Using minimal init.vim, see below.
- Operating system/version: Windows 10
- Terminal name/version: powershell core (used to launch nvim-qt with arguments)
- `$TERM`: n/a

### Steps to reproduce using `nvim -u minirc`

```
nvim-qt -- -u minirc
```
Inside file `minirc` is:
```vim
echomsg &columns.' '.&lines
```

### Actual behaviour
`echomsg &column.' '.&lines` from config file `minirc` always gives "211 52", while using this again in command mode gives "142 45" in my case (which I use `-qwindowgeometry 1280x720` to launch nvim-qt).

### Expected behaviour
Columns and lines should be consistent.

**Comment by glacambre** [comment]
This is a feature, not a bug :). Here's what's happening:

1) Neovim-qt starts.
2) Neovim-qt starts Neovim.
3) Neovim processes init.vim, echoes `&columns` and `&lines`.
4) Neovim-qt attaches to Neovim as a UI and sets columns+lines.
5) You then type your command mode `echo`, which gives you the new columns+lines.

There is no way for Neovim to know how tall and wide the UI is when it's processing your init.vim because there is no UI. There are two solutions though:

- Neovim-qt could add `--cmd 'set lines=X | columns=Y'` to the arguments passed to neovim when it starts. This is UI-specific, so not a great solution.
- You use the `UIEnter` autocommand (e.g. `autocmd UIEnter * echomsg &columns . ' ' . &lines`) - this will work across all UIs (so when you decide to replace Neovim-qt with something else you won't have to change your config).

Using UIEnter will work in both Neovim-Qt and the TUI. It's the right solution and the one you should use :)
