### ISSUE TITLE
Language issues on Windows

### ISSUE THREAD

**Issue by FedorLap2006** [neovim/neovim#13548]
- `nvim --version`:
```
NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5

Features: -acl +iconv +tui

```
P.S. I'm using nvim-qt.

- `vim -u DEFAULTS` (version: ) behaves differently? - Actually I don't know, It's just opening an empty file
- Operating system/version: Win 8.1
- Terminal name/version: Windows Command line (aka cmd)
- `$TERM`: None

### Steps to reproduce

- Use russian language as system language.
- Install `git` (that `git` which is with `git-bash` and `git-gui`)
- Install NeoVim using `chocolatey`
- Install `vim-plug`
- Try to install some plugins

### Actual behaviour

Unicode garbage.

### Expected behaviour

Normal installation message or deletion message.

### Current configuration (not helps at all):

```vim

let $LC_ALL="en_US.UTF-8"
language en_US.UTF-8
set enc=UTF-8


call plug#begin("$LOCALAPPDATA/nvim-data/autoload/plugged")

source $LOCALAPPDATA/nvim/pluginlist.vim

call plug#end()


set clipboard=unnamed

colorscheme gruvbox
```

P.S. Why not vim-plug issue? - Because of encodnig, and that's a problem of neovim.
Btw, I think that's a problem of git, but I can't even set locale for `git`, because nvim doesn't want to accept LC_ALL env-variable.

**Comment by bfredl** [comment]
"Unicode garbage" can be pretty much anything. a screenshot would be useful.

**Comment by FedorLap2006** [comment]
> "Unicode garbage" can be pretty much anything. a screenshot would be useful.
![image](https://user-images.githubusercontent.com/42876964/102656507-07aa7700-4185-11eb-928c-8c31bbc376f9.png)

**Comment by erw7** [comment]
The encoding of the output of Windows console applications is the system codepage. The internal encoding of neovim is always UTF-8, so their output will be garbled. In the case of vim, if `enconding` is the same as the system codepage, no garbling will occur, but if it is set to UTF-8, garbling will occur as in neovim. 

Currently, you can deal with this problem by using `iconv()` on the plugin side to change the character encoding. If the problem is to be solved on the neovim side, someone needs to create a patch to change the output of the commands in the system code page to UTF-8. For Windows 10, there is a setting called `"Beta: Use Unicode UTF-8 for worldwide language support"` which should solve this problem. I'm not actively trying to solve this problem as I expect the problem to be solved in that setting in the future.

You may be able to fix the garbled code by changing the code page of the git output to 437 (English) as follows. However, I feel that this setting itself may cause a lot of problems.

```vim
set shellcmdflag=/c\ chcp\ 437\ &\ cmd\ /s\ /c
```

**Comment by FedorLap2006** [comment]
> You may be able to fix the garbled code by changing the code page of the git output to 437 (English) as follows. However, I feel that this setting itself may cause a lot of problems.

Which problems

**Comment by FedorLap2006** [comment]
> The encoding of the output of Windows console applications is the system codepage. The internal encoding of neovim is always UTF-8, so their output will be garbled. In the case of vim, if `enconding` is the same as the system codepage, no garbling will occur, but if it is set to UTF-8, garbling will occur as in neovim.
> 
> Currently, you can deal with this problem by using `iconv()` on the plugin side to change the character encoding. If the problem is to be solved on the neovim side, someone needs to create a patch to change the output of the commands in the system code page to UTF-8. For Windows 10, there is a setting called `"Beta: Use Unicode UTF-8 for worldwide language support"` which should solve this problem. I'm not actively trying to solve this problem as I expect the problem to be solved in that setting in the future.
> 
> You may be able to fix the garbled code by changing the code page of the `git` output to 437 (English) as follows. However, I feel that this setting itself may cause a lot of problems.
> 
> ```viml
> set shellcmdflag=/c\ chcp\ 437\ &\ cmd\ /s\ /c
> ```

Well, everything is ok, but it shows me "Cannot find system path specified" or something like that after installing.

**Comment by FedorLap2006** [comment]
So... what can I do, if I'm not on win10?

**Comment by Sebastian-byte** [comment]
> So... what can I do, if I'm not on win10?

You may upgrade to Win10, it's easy.

**Comment by FedorLap2006** [comment]
> > So... what can I do, if I'm not on win10?
> 
> You may upgrade to Win10, it's easy.

And... that's another problem.

**Comment by 3N4N** [comment]
This is a really old issue.  I don't have Windows 8.1 (or 10, for that matter), so I can't test if it's fixed already.  Adding `needs:response` label seems like a sensible thing to do.

**Comment by dundargoc** [comment]
We don't support windows 8 anymore, so don't have to care about that.
