### ISSUE TITLE
Native Fennel support

### ISSUE THREAD

**Issue by ggandor** [neovim/neovim#13604]
First of all, an enormous thanks for the outstanding work of the core development team and every contributors.

I know about [Aniseed](https://github.com/Olical/aniseed) of course, but I am thinking about something along the lines of [fennel-nvim](https://github.com/jaawerth/fennel-nvim), making Fennel a true first-class citizen, like Lua itself. (Unfortunately that project seems pretty inactive lately.) @justinmk raised the possibility a good while ago in [#6580](https://github.com/neovim/neovim/issues/6580), that is the only mention I have found here among the issues, but his [recent comment](https://www.reddit.com/r/neovim/comments/iofl3s/vimconflive_conversational_software_development/g4eszlt?utm_source=share&utm_medium=web2x&context=3) gives me hope that the possibility might still be on the table. Is it being considered to support Fennel as an out-of-the-box, bundled scripting alternative sometime in the future? Any pros or cons? What do you think about it?

(I've skimmed through the old Moonscript vs Lua debate in [#207](https://github.com/neovim/neovim/issues/207). Developing the main codebase is one thing, but as a user-side feature, it seems a no-brainer for me to support some lightweight transpiled layer above Lua as a convenience, setting aside the question of time and resources for the moment.)

**Comment by bfredl** [comment]
I think we want fennel as the "native" macro system for tree-sitter queries at some point.

**Comment by addcninblue** [comment]
@ggandor: What would be the difference between having Fennel as a "lightweight transpiled layer" versus embedding it yourself through their [Embedding the Fennel compiler instructions](https://fennel-lang.org/setup#downloading-fennel)?

(Yesterday I rewrote my `init.vim` to `init.fnl`, and I use `fennel --compile`, and that seems to be fine as is.)

**Comment by teto** [comment]
lua can be enhanced via different options: moonscript, funnel, typed lua  https://github.com/teal-language/tl etc.
Lua support in neovim is recent so let the community play with it, favoring one over the others could kill community momentum. Especially since they are all easy to setup userside.

Closing this since I dont think we can act in the short term but this may be revisited for the 0.6 release for instance.

NB: I am really curious about funnel since the flawless vimconf presentation and want to play with it some more.

**Comment by alexaandru** [comment]
FWIW using Fennel became a lot simpler thanks to https://www.reddit.com/r/neovim/comments/otvt0q/hotpot_seamless_fennel_in_neovim_yafp/ :) 

Special mention to [antifennel](https://git.sr.ht/~technomancy/antifennel) which can greatly accelerate the Lua -> Fennel conversion :)

**Comment by teto** [comment]
would be nice to have a wiki page summarizing "alternatives" to lua like teal/fennel, feel free to create one.

**Comment by alexaandru** [comment]
Done: https://github.com/neovim/neovim/wiki/Configuration 

Please let me know what you think/if you want me to change anything. If it looks good, then I'd link to it in the Wiki index page. 

Also, I copied the 1st section from FAQ, so perhaps we could delete that 1st question from it now, after we link this new page to the index, of course. Otherwise, it'll be a little redundant, that's all.

FWIW, here is my own config, now 99.6% Fennel based :) https://github.com/alexaandru/nvim-config  Once I wrote the 1st few lines of Fennel, I couldn't stop... :) 

Cheers!

**Comment by alexaandru** [comment]
One other thing I could add, if you think is worth going into that much detail, is how to get parsing/compile errors for Fennel. I use EFM for that: https://github.com/alexaandru/nvim-config/blob/master/fnl/config/efm.fnl#L30-L34 and needless to say, it speeded up the development cycle greatly. And TreeSitter has support for it too (though just syntax, for now) so you can get quite a nifty Fennel editing setup :)

**Comment by thanhnguyen2187** [comment]
Hi guys. Do we have any update on this? I am really interested in having native Fennel support to ~~turn Neovim into Emacs~~ have a nicer configurating experience

**Comment by clason** [comment]
No plans currently. You can use one of the many transpilers available like https://github.com/rktjmp/hotpot.nvim.

**Comment by alexaandru** [comment]
Just to add my 2c to it, after using Fennel for almost a year now: yes, Hotpot works like a charm, I literally only have a single line of vimscript and the rest of my config is all Fennel :-)  -  https://github.com/alexaandru/nvim-config

I no longer miss native support for config purposes. However, I do miss it when writing plugins and/or colorschemes, esp. after you added that amazing support for Lua all over the place (colors, syntax, plugin, etc. folders). In my plugins, I'm forced to put lua "stubs" just to pull in Fennel code, because Fennel is only recognized under ./fnl/... folders, i.e.  https://github.com/alexaandru/froggy/blob/master/colors/froggy.lua so I need that bit of Lua, in order to "pull in" the Fennel code.

Now, I know Fennel native support is unrealistic, we did not even manage to get a Reddit user flair for ourselves ;) but what about some support for some sort of a "hooking" mechanism, that would allow us to run anything we want from all those nice places where lua is supported and just have some "pre-process" step (the "hook" part) before the code is actually run? So those who want to run Fennel would compile it with Fennel, before actually letting the Lua interpreter see it, those that prefer Teal (or whatever else), could do the same, etc. So, some sort of language agnostic "hook" that needs to have as an end result Lua code, by whatever means necessary (this could include a caching layer, etc. but this is up to the end users, that implement the plugins that use these hooks, neovim only needs to provide the hook mechanism).

**Comment by gpanders** [comment]
@alexaandru What you are asking can already be done, see https://github.com/gpanders/nvim-moonwalk as an example. This enables you to use Fennel for colorschemes, plugin files, ftplugin files, etc.

Essentially you just need to use Fennel's AoC feature to compile Fennel sources into Lua and either (1) add the directory containing the compiled Lua to your runtimepath (which is what nvim-moonwalk does) or (2) place the Lua files into a directory that is *already* on your runtime path (which is what I personally do in my own configuration).

If you are creating a 3rd party plugin, the solution is to simply compile your Fennel sources into Lua with a Makefile and "ship" the Lua code.

Adding "native" support for Fennel buys us very little, and just opens the door to other people asking to embed their own favorite language as well.

**Comment by justinmk** [comment]
> lua can be enhanced via different options: moonscript, funnel, typed lua https://github.com/teal-language/tl etc.

Another gradually-typed Lua dialect: https://github.com/Roblox/luau
