### ISSUE TITLE
Failing to Build Neovim on Windows

### ISSUE THREAD

**Issue by kirawi** [neovim/neovim#13618]
- Operating system/version: Windows 10 Version 2004

I cannot compile the deps, no matter if I use MSVC, GCC, or Clang, and following the build directions. I'm sure it's me doing something wrong that's causing it, but I'm completely unfamiliar with this.

[Console Output](https://pastebin.com/hkmWxxai)

**Comment by fredizzimo** [comment]
I had the same problem but managed to fix it locally.

It seems like the default cmake configuration is wrong (`x64-debug`).  There's also no other available configuration to select in the dropdown in Visual Studio (2019). But if you chose manage configruations, and manually add `x86-Release`, then the dependencies are downloaded and installed correctly.

The configurations are stored in the `CMakeSettings.json` file, but that file is not included in the repository, maybe it should be. The 64-bit configurations could also probably be removed at least until they are fixed.

The documentation also seems a bit outdated, since you don't open a project, you open the folder in Visual Studio. I also didn't manage to build it from the developer console by running cmake manually according to the instructions, maybe because Visual Studio 2019 actually uses Ninja under the hood, so a Ninja project has to be generated instead. But I didn't test that too much, since building from Visual Studio worked.

**Comment by kirawi** [comment]
I got the binaries from someone else. I'm assuming it's something to do with my environment/steps, and not with the project itself, so I'll close the issue.

**Comment by kirawi** [comment]
https://github.com/Kethku/neovide/issues/456

I needed to uninstall/reinstall MSYS2.
