### ISSUE TITLE
new tab with terminal and expand(`%:p`) broken

### ISSUE THREAD

**Issue by matu3ba** [neovim/neovim#13656]
Found an issues with E499: #7295 (unsolved and non-trivial).

- `nvim --version`: NVIM v0.5.0-dev+990-g0efbab5f5
- `vim -u DEFAULTS` (version: ) The same error occurs or only `%:p:h` is accepted (wrong path).
- Operating system/version: Arch Linux
- Terminal name/version: bash/5.1.4(1)
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`
In command mode:
```sh
:tabnew | !echo expand('%:p') # BROKEN
:tabnew | !echo expand("%:p") # BROKEN
:tabnew | terminal echo expand('%:p') # BROKEN
:tabnew | terminal echo expand("%:p") # BROKEN
:tabnew | !echo expand('%:p:h') # BROKEN by shell interpretation (and wrong path)
:tabnew | !echo expand("%:p:h") # BROKEN by shell interpretation (and wrong path)
:tabnew | terminal echo expand('%:p:h') # BROKEN by shell interpretation (and wrong path)
:tabnew | terminal echo expand("%:p:h") # BROKEN by shell interpretation (and wrong path)
```

### Actual behaviour
`E499: Empty file name for '%' or '#', only works with ":p:h"`
or for the wrong path `%:p:h`:
```txt
:!echo expand("$HOME/Schreibtisch/old")
/bin/bash: -c: Line 1: Syntax error on unexpected symbol »(«
/bin/bash: -c: Line 1: `echo expand("$HOME/Schreibtisch/old")'

Shell ends 2
```

### Expected behaviour
Proper expansion of % like described [here](https://jdhao.github.io/2019/07/31/nvim_show_file_path/) and which also works in the command mode (`:echo expand('%:p')`) without a new tab.

My intention is to have a new tab with the terminal output and no terminal running that blocks me editing.

If you can give me a short mentoring, where and how terminal interaction is supposed to work (or documentation), I would attempt to fix this myself.
Meta: Is there a workaround in lua? I found only `nvim_buf_get_name()` [here](https://neovim.io/doc/user/api.html) or which is the appropriate documentation?

**Comment by jamessan** [comment]
I think you're misunderstanding how these commands are working.

`:tabnew | !echo expand('%:p')` creates a new tab, expands the literal `%` in the command (as per `:help filename-modifiers`) to the filename of the new buffer (which is empty because it's unnamed), and then runs the shell command `echo expand('<expanded filename>')`.

That is, `expand()` is being passed to the shell and not evaluated in nvim.  This is different from `:echo expand(...)` (note, no `!`) which is evaluating the `expand(...)` expression and echoing the results, completely internal to nvim.

This is behaving as expected.

**Comment by matu3ba** [comment]
One needs to create the command and run execute, ie:
```sh
let l:cmd = "terminal latexmk -pdflatex=lualatex -pdf -outdir=build " .. expand("%") | tabnew | execute cmd
```

**Comment by jamessan** [comment]
```vim
tabnew | exe 'terminal latexmk -pdflatex=lualatex -pdf -outdir=build ' .. shellescape(expand('#'), 1)
```
should also work.
