### ISSUE TITLE
Incorrect behavior of mapping to <C-Space>.

### ISSUE THREAD

**Issue by Qrzysiek** [neovim/neovim#13680]
- NVIM v0.5.0-dev+998-g48caf1df8
- Windows 10 version 20H2
- Windows Terminal 1.4.3243.0

### Actual behaviour
`nmap <C-Space> <Plug>VimwikiToggleListItem` doesn't map command to the Ctrl+Space.

### Expected behaviour
`nmap <C-Space> <Plug>VimwikiToggleListItem` maps command to the Ctrl+Space.

Binding such as `nmap <C-P> <Plug>VimwikiToggleListItem` seems to work. On the version 0.4.4 binding to `<C-Space>` worked normally.

**Comment by mhinz** [comment]
Is this still happening with current nightlies?

**Comment by erw7** [comment]
This is a duplicate of #8435.

**Comment by erw7** [comment]
> Is this still happening with current nightlies?

I tried to fix it with neovim/libuv#8, but the problem #11061 occurred, so I reverted it with neovim/libuv#11. Therefore, nightlies has not been fixed yet. I think someone needs to find a way to solve the problem caused by the keyboard layout. I think we need to change the key translation table in `get_vt100_fn_key()`  of  libuv according to the keyboard layout in a similar way to the keymap setting in Linux.
