### ISSUE TITLE
Neovim not detecting zsh file automatically

### ISSUE THREAD

**Issue by MrAdityaAlok** [neovim/neovim#13696]
- `nvim --version`: v0.4.4
- Operating system/version: Android 9
- Terminal name/version: Termux 
- `$TERM`:xterm-256color

### Steps to reproduce

- open any zsh file

### Actual behaviour
Comments not colored
- following is screenshot of how it behaves without using  `:set filtype=zsh` 
![Screenshot_2021-01-05-22-00-36-434](https://user-images.githubusercontent.com/73517616/103672107-d5c94b00-4fa1-11eb-8e78-f3bd26d769fe.jpeg)

### Expected behaviour
Comments should be colored
- following is screenshot of how it should be
-  Note : I had to explicitly use `set filetype=zsh` to get this result
![Screenshot_2021-01-05-22-01-03-329](https://user-images.githubusercontent.com/73517616/103672084-c9dd8900-4fa1-11eb-90a9-b5249ce1ad6c.jpeg)

**Comment by glacambre** [comment]
zsh detection has been available since [day 1](https://github.com/neovim/neovim/commit/a98a6996c291b3e300d27b791eded9eed333d677) and is still done today:

https://github.com/neovim/neovim/blob/2ea3127697692b0b2c480d585ef6529e90a72b0e/runtime/filetype.vim#L1548-L1550

You probably have a bug in your init.vim which prevents the filetype from loading. Try running `nvim -u NORC p10k-robbyrussel.zsh` to see if the filetype is correctly detected without your init.vim.

**Comment by MrAdityaAlok** [comment]
@glacambre yes, you were right , there is some problem in my init.vim file
But I am not able to get. 

# Can you help me ? Please!

**Comment by glacambre** [comment]
@MrAdityaAlok Here's what I do when there's a bug in my init.vim:
1) Delete half of my init.vim
2) If the bug is still there, go to 1.
3) If the bug isn't there anymore, restore the removed half and remove the other one.
4) Got to 1.
This should help you find the line responsible for your problem :)

**Comment by MrAdityaAlok** [comment]
Okay, thanks @glacambre 
Nice Algorithm !!
