### ISSUE TITLE
Terminal-mode is started unexpectedly when switching buffers in some cases

### ISSUE THREAD

**Issue by ojroques** [neovim/neovim#13769]
- `nvim --version`: `NVIM v0.5.0-dev+1024-g2390a0d3c`
- `vim -u DEFAULTS` (version: ) behaves differently? **yes**
- Operating system/version: **Ubuntu 20.04 (in WSL1)**
- Terminal name/version: **Windows Terminal 1.5.3242.0**
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`
1. Execute `:term`
2. Open a new split: `:vs test`
3. Run `cat` using the built-in terminal with an exit callback that closes the window: 
```vim
:call termopen('cat', {'on_exit': {-> execute('close')}})
```
4. Enter terminal mode then end `cat` with `<C-d>`. The process terminates and the window is closed.

### Actual behaviour
We are now in the buffer containing the terminal created at step 1 but **in terminal mode**.

### Expected behaviour
We stay in normal mode in the terminal buffer just as we left it.

This may sound like a very minor bug but it's still quite annoying: this is exactly the behavior of [FZF](https://github.com/junegunn/fzf). FZF runs in the built-in terminal and the window is closed when it terminates. That means when we use fzf.vim `:Buffers` command to switch to a terminal buffer, we enter it in Terminal mode. See [this issue](https://github.com/junegunn/fzf.vim/issues/1216).

The workaround I mention in the above issue makes me think that we are still in terminal mode when the window is closed and it is somehow passed to the next buffer.

**Comment by glacambre** [comment]
This is not a bug, the mode is global (as opposed to local to a window/buffer). You can replicate this behavior with insert mode and any other mode:
- `nvim -u NORC /tmp/a` (Open neovim
- `:sp /tmp/b` (Create a new split+buffer)
- `:inoremap <C-c> <Cmd>close<CR>` (Create a mapping that closes the current window while staying in the current mode)
- `i` (Enter insert mode)
- `<C-c>` (Run the command that closes the window)

You'll see that the cursor is back to `/tmp/a` and still in insert mode, because the mode is global.

You can use the `TermEnter` and `TermLeave` autocommands to keep track of what mode your terminal buffers are in and restore that mode on `BufEnter`.

**Comment by ojroques** [comment]
I see, thank you for your clear explanation it makes sense.

I thought this was not intended because Vim terminal behaves differently (it always exits terminal mode) and it seemed correct since I assumed that mode was local. But knowing now that mode is global, Neovim's behavior seems more consistent to me. Thanks again, I'm closing this issue.
