### ISSUE TITLE
Build for android

### ISSUE THREAD

**Issue by LoneLySTTR** [neovim/neovim#13795]
Does the assembly for android work at all? if it works how to assemble it?

**Comment by glacambre** [comment]
>Does the assembly for android work at all?

Looks like [alpine](https://pkgs.alpinelinux.org/packages?name=neovim), [debian](https://packages.debian.org/sid/neovim) and [gentoo](https://packages.gentoo.org/packages/app-editors/neovim) provide binary releases of Neovim for Arm, so there shouldn't be any issues building neovim for android.

> if it works how to assemble it?

There are build instructions [in the wiki](https://github.com/neovim/neovim/wiki/Building-Neovim#building). I would also look at the packages of the mentionned distributions in order to find out if there's anything specific you need to do in order to build on Arm.

**Comment by chalybeum** [comment]
Just yesterday I've compiled nightly under Termux-arch. Unfortunately I have no experience in packaging but will look into it. For now I can give the steps that worked for me.
1. Make sure you are logged in as normal user in Termux-arch.
2. Install ( sudo pacman -Syu <packagenames>) all dependencies mentioned here: https://aur.archlinux.org/packages/neovim-nightly-git/
Also make sure you have git on your system.
3. Now: git clone https://github.com/neovim/neovim
4. Follow the instructions on the github page. Make sure to read to the end first and pay special attention on how to build without bundled deps and install to custom location.

Let me know, if there is need for further explanation.
