### ISSUE TITLE
Replace two lines with nvim_buf_set_text leaves last line unchanged

### ISSUE THREAD

**Issue by trkoch** [neovim/neovim#13890]
- `nvim --version`: NVIM v0.5.0-dev+1055-g8950f4e94
- `vim -u DEFAULTS` (version: ) behaves differently? Yes (API does not exist)
- Operating system/version: macOS 11.2
- Terminal name/version: iTerm
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

```
$ nvim -u NORC --listen /tmp/vim
```

Buffer

```
AAA
BBB
```

neovim/node-client

```
$ NVIM_LISTEN_ADDRESS=/tmp/vim NVIM_NODE_LOG_FILE=nvim.log node --experimental-repl-await
> const nvim = await require('neovim/scripts/nvim')
> // (1)
> await nvim.request('nvim_buf_set_text', [0, 0, 0, 1, 3, ['XXX', 'YYY']])
> // (2)
> await nvim.request('nvim_buf_set_text', [0, 0, 0, 1, 3, ['XXX', 'YYY', '']])
```

### Actual behaviour

Buffer

(1)

```
XXX
YYY
BBB
```

(2)

```
XXX
BBB
```

### Expected behaviour

```
XXX
YYY
```

### Related issues/PRs
* https://github.com/asvetliakov/vscode-neovim/issues/543
* https://github.com/neovim/neovim/pull/13580

**Comment by chentau** [comment]
Doing the same thing with lua inside neovim works for me, so this is probably an issue with the node client/async?

**Comment by trkoch** [comment]
> Doing the same thing with lua inside neovim works for me, so this is probably an issue with the node client/async?

That's odd. What could possibly go wrong only partly? Maybe some issues with parameter parsing? By same do you mean option (1) or (2)?

**Comment by trkoch** [comment]
@chentau How did you verify? Executing a Lua command with `:lua vim.api.nvim_buf_set_text(0, 0, 0, 1, 3, {'XXX', 'YYY'})` results in the same result on my machine.

**Comment by chentau** [comment]
@trkoch  Ah, I think I see the issue.

`buf_set_text` applied the changes properly, its just that the changes are not being displayed. In other words, the buffer is actually

```
XXX
YYY
```

but in this case, only the first line was redrawn, meaning that what you see is

```
XXX
BBB
```

Normally, `win_update` will call `win_line` to redraw any lines that have changed - however the call to `changed_lines` inside set_text is off by one, meaning the last row of the changed text does not get redrawn. I didn't see this bug since I have relative numbers turned on.

**Comment by chentau** [comment]
@trkoch Can you try out the linked pr to see if it fixes your issue?
