### ISSUE TITLE
The mouse doesn't work properly on help windows with Konsole terminal

### ISSUE THREAD

**Issue by dstein64** [neovim/neovim#13948]
- `nvim --version`: NVIM v0.5.0-dev+1089-gdc3ca16a9
- `vim -u DEFAULTS` (version: ) behaves differently? Yes
- Operating system/version: Ubuntu 20.04.2
- Terminal name/version: Konsole 19.12.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set mouse=a
:help
```

Select text in the help window using the mouse, or try changing the size of the help window by dragging the status line with the mouse (while the help window is the current window).

### Actual behaviour

Text is only sometimes selected. When it is selected, the selection only partially corresponds to the corresponding mouse drag. More often, there is a jump of the cursor or an error message: `E149: Sorry, no help for option,`.

The window cannot be resized when trying to drag the status line.

### Expected behaviour

Text could be selected.

The window could be resized. Window resizing works after changing moving the cursor to some other window.

**Comment by glacambre** [comment]
I'm on master+kitty 0.18.3.

>Text is only sometimes selected.

I can't reproduce this.

>When it is selected, the selection only partially corresponds to the corresponding mouse drag. More often, there is a jump of the cursor 

I can see this happen when clicking on a tab character. The whole character is highlighted instead of just the portion the user clicks on. This behavior makes sense to me but it would indeed be less confusing if only the cells selected with the mouse were highlighted.

>or an error message: E149: Sorry, no help for option.

This only happens when double-clicking for me. This is because you can double-click words to jump to the corresponding help section, e.g. double clicking `move` is equivalent to `:help move`.

>The window cannot be resized when trying to drag the status line.

This works fine for me. Can you reproduce this behavior with another terminal/Neovim GUI?

**Comment by dstein64** [comment]
@glacambre, I cannot reproduce the issue when using` XTerm(353)` or `Neovim-Qt`.

I'll update the title to reflect that this issue occurs on Konsole.

Thanks!

**Comment by dstein64** [comment]
This is no longer an issue as of Konsole 21.04.0, released 2021-04-15.
