### ISSUE TITLE
health check tmux can never be correct?

### ISSUE THREAD

**Issue by GopherJ** [neovim/neovim#13950]
I use tmux, neovim and alacritty.

At this beginning I've set `TERM` environment variable to `xterm-256color`,  in `tmux.conf` I've put:

```
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
```

then neovim throws out an error that `TERM` differs..
![image](https://user-images.githubusercontent.com/33961674/108023234-174b1c80-705d-11eb-99f3-d6b765c26676.png)

Then I've tried to follow instructions and I've changed `TERM` to be `tmux-256color`, at the same time I changed `tmux.conf` to be:

```
set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",tmux-256color:RGB"
```

then it throws again another error:

![image](https://user-images.githubusercontent.com/33961674/108023446-7e68d100-705d-11eb-88d7-54f5ebf9962b.png)

I'm then confused what should I do to make this correct? I've read all issues related to this, I've done google search but nothing points me to the right way.

**Comment by GopherJ** [comment]
All my configs are:

1. [vimrc](https://github.com/GopherJ/cfg/blob/master/coc/.vimrc)
2. [tmux conf](https://github.com/GopherJ/cfg/blob/master/tmux/.tmux.conf)

**Comment by scheatkode** [comment]
Duplicate of #7353 ?

This may be a shot in the dark but try changing this line in your `tmux.conf` :

    set-option -sa terminal-overrides ",tmux-256color:RGB"

With this :

    set-option -sa terminal-overrides ",xterm*:Tc"

I have this same configuration and tried `:checkhealth` using Alacritty *SSHing from Windows*, works like a charm.
Also check if any if your dotfiles is setting `$TERM`, *which shouldn't happen* but let's be on the safe side and run this command from your home directory to make sure.

    rg --hidden '$TERM='

**Comment by GopherJ** [comment]
@scheatkode I've read that issue but it didn't help on my side. I've removed `TERM=` from `~/.zshrc`

now the only thing left is:

`.vimrc`
```
   28 if has("termguicolors")
   29     set termguicolors
   30 endif
```

`.tmux.conf`
```
set-option -g default-terminal "tmux-256color"
# set-option -sa terminal-overrides ",tmux-256color:Tc"
set-option -sa terminal-overrides ",xterm*:Tc"
```

![image](https://user-images.githubusercontent.com/33961674/108576134-69d75200-7357-11eb-9ccf-5d3d81a9a0c4.png)

**Comment by scheatkode** [comment]
> I've removed `TERM=` from `~/.zshrc`

Great ! `TERM` shouldn't be set manually, it defaults to `xterm-256color` on most recent terminals, which is your case as well.

> now the only thing left is:
> 
> `.vimrc`
> 
> ```viml
> if has("termguicolors")
>    set termguicolors
> endif
> ```

This enables 24-bit RGB color mode in neovim and isn't relevant to your current issue. It's safe to keep.

> `.tmux.conf`
> 
> ```shell
> set-option -g default-terminal "tmux-256color"
> # set-option -sa terminal-overrides ",tmux-256color:Tc"
> set-option -sa terminal-overrides ",xterm*:Tc"
> ```
> 
> but still I've got warnings, how difficult it is to be correct...

Since this is basic configuration is functional on my end, I suspect the issue originates from somewhere else.

Can you try again but with a minimal configuration ? No plugins or anything fancy. Only a `tmux.conf` with these two lines, preferably disabling your `zshrc` entirely as well or even trying with a different shell for the sake of proceeding by elimination.

If this still doesn't work, would it be possible to have more information about your environment, terminal capabilities, versions, and the such ?

**Comment by erw7** [comment]
@GopherJ Perhaps the `TERM` environment variable outside of `tmux` is set to `alacritty`. Please try the following settings.

`.tmux.conf`

```
set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",alacritty*:Tc"
# or
set-option -sa terminal-overrides ",alacritty*:RGB"

```

**Comment by GopherJ** [comment]
@erw7 @scheatkode thanks actually when I try again it looks all working.

1. `set-option -sa terminal-overrides ",xterm*:Tc"` => OK
2. `set-option -sa terminal-overrides ",tmux-256color:Tc"` => OK
3. `set-option -sa terminal-overrides ",alacritty*:Tc"` => OK

it looks better, thanks for your instant help!

Last question, which one shall I choose? Shall I go for: 

```
set-option -sa terminal-overrides ",xterm*:Tc"
```
and what is this configuration for? Sorry I didn't really understand it. I'll do some search today

**Comment by erw7** [comment]
> Last question, which one shall I choose?

You should configure it by the terminal name obtained by running echo `$TERM` on the host terminal before running tmux. If you are not sure, you can do the following.

```
set-option -sa terminal-overrides ",xterm*:Tc,alacritty*:Tc"
```

The reason why 1 and 2 in your example are OK is probably because you ran it with another tmux while the tmux was started with no problem by setting 3.

**Comment by GopherJ** [comment]
clear thanks!
