### ISSUE TITLE
Is any of developers neovim trans?

### ISSUE THREAD

**Issue by micwoj92** [neovim/neovim#13975]
Hello, I am trying to bring back more trans positivity into software I use. I did learn that vi development was led by trans woman after Bill Joy stopped maintaining it. I do not like vi that much because it limits my abilities and I already had good neovim setup but trans representation in software is important for me.

**Comment by qnirz** [comment]
Picking software based on the gender of the developer is inherently sexist. The same applies with any other personal trait of developers and users. Please stop immediately.

**Comment by micwoj92** [comment]
> Picking software based on the gender of the developer is inherently sexist. The same applies with any other personal trait of developers and users. Please stop immediately.

Do you know why ReiserFS is not widely used? Because mr. Hans decided to kill his wife. I will not use software developed bu murderer. Also you just created your account, bad troll attempt.

**Comment by qnirz** [comment]
ReiserFS is not widely used because there was no reason to use it, rather than there being a reason to avoid it. Today, ext4 pretty much stomps on ReiserFS, and is the default one, so naturally ReiserFS fell out of favour. Many of ReiserFS' ideas were still used in other filesystems.

Even if the developer being a murderer was a reason to avoid his (genderless pronoun, please lower your tridents) software, I believe using a piece of software solely for the reason that one of the developers is transgender is not a very convincing decision. Consider directly supporting transgender people instead.

**Comment by micwoj92** [comment]
>  I believe using a piece of software solely for the reason that one of the developers is transgender is not a very convincing decision.

Yes, I believe that too. But if there is alternative (vi) I definitely prefer alternative. :)

**Comment by adnan449** [comment]
I see quite a few contributors are using anime avatar, OP so you are in luck. Can you go back to 4chan and delete [the thread you created](https://rbt.asia/g/thread/80289915/#q80290038) now?

**Comment by qnirz** [comment]
I was confused as first, but yeah, turns out this entire issue is probably a troll one created by a 4chan user. Judging by the repulsive amount of toxicity on the thread adnan449 linked, the internet's teenager never changes, it seems.

**Comment by bfredl** [comment]
The issue tracker is for bugs and requests actionable within the repo itself. https://www.reddit.com/r/neovim/ is a better place for discussions like this.
