### ISSUE TITLE
let neovim nix flakes can be build at macOS

### ISSUE THREAD

**Issue by c4dr01d** [neovim/neovim#13996]
Hi, I'm follow the Neovim HEAD with nix, when I trying to using it at my macOS nix-darwin with flakes support, I got error about platform and nix features. I view the contrib/flake.nix, maybe can add macOS support?
ps.: I was report the error at nix-community's neovim overlay, but I didn't get any solutions for my problem, so I come to here to ask for help or finding some solutions and workaround.

**Comment by teto** [comment]
so I found your thread but it would be best to keep going at https://github.com/nix-community/neovim-nightly-overlay/issues/93 since the problem isn't clear yet. I've added a flake.nix to neovim because that's the best technology I knew to get reproduciable results on linux/darwin. Other contributors let me do it (thank you) but I would rather not have the tracker filled with nix issues otherwise they may change their mind :)
