### ISSUE TITLE
LSP: Support for rust-analyzer inlay hints:

### ISSUE THREAD

**Issue by ibraheemdev** [neovim/neovim#14005]
`rust-analyzer` provides a feature where you can display type hints inline in an editor:
![image](https://user-images.githubusercontent.com/34988408/109048683-5c96cc00-76a5-11eb-9600-bd35c6297ac5.png)
It would be nice if this functionality was available in the built-in LSP. [languageclient-neovim recently added support for this as well](https://github.com/autozimu/LanguageClient-neovim/pull/1108)

**Comment by clason** [comment]
You mean like https://github.com/nvim-lua/lsp_extensions.nvim#inlay-hints-rust-analyzer ?

**Comment by ibraheemdev** [comment]
> You mean like https://github.com/nvim-lua/lsp_extensions.nvim#inlay-hints-rust-analyzer ?

Yup, exactly. I didn't see that before, thanks! I assume that functionality will stay in `lsp_extensions` and not be added to this codebase? If so, this issue can be closed.

**Comment by clason** [comment]
I think so, since it's not part of the LSP spec and a custom extension of a single server. But it's only a single file: https://github.com/nvim-lua/lsp_extensions.nvim/blob/master/lua/lsp_extensions/inlay_hints.lua so you could just include it in your own config if you don't want to depend on another plugin.

One could discuss how to make that (or other server-specific features) more discoverable, though. Maybe adding it to https://github.com/neovim/nvim-lspconfig/wiki/Language-specific-plugins?

**Comment by clason** [comment]
OK, I'll close it then -- feel free to open an issue on  https://github.com/neovim/nvim-lspconfig about discoverability (if there isn't a similar one already).

**Comment by ibraheemdev** [comment]
All right, thanks!
