### ISSUE TITLE
Add regex101 support for vim's regular expression

### ISSUE THREAD

**Issue by reportaman** [neovim/neovim#14021]
Vim has its own regular expression syntax. I have dreaded regular expression syntax in past before using https://regex101.com. What makes regex101 easy to learn with is it's immediate feedback for user's test string & explanation of what each part of regex actually means/does. This will avoid ever-increasing total human time spent in debugging regex while developing code with vim's regex syntax. There is a ticket on regex 101's website since 2014 https://github.com/firasdib/Regex101/issues/157, though it might need driving from (neo)/vim team.

**Comment by teto** [comment]
why do you want neovim to drive everything ? we have limited ressources and barely manage to handle critical issues (see the 1k issues on tracker). I appreciate your enthusiasm but we develop APIs to empower people like you to make a difference and develop their own plugin.  I encourage you to take on this issue since you are the most appropriate for it and ask any question with the API at https://neovim.discourse.group/

**Comment by reportaman** [comment]
@teto Because I thought your team wants to make neovim a easy tool to work with, and this could help your goal.
