### ISSUE TITLE
Can neovim have a unified diagnostic API?

### ISSUE THREAD

**Issue by nawordar** [neovim/neovim#14373]
I am currently using neovim 0.4 with ALE and vim-lsp. The problem with these plugins is that, since Vim doesn't have a unified diagnostic API, they both display diagnostic in their own way. This results in separate shortcuts for switching between ALE and vim-lsp diagnostic and overall inconsistency.

I think that, as there is currently a built-in LSP client in a development, maybe it would be a good idea to introduce a unified diagnostic API, similar to what [VSCode does](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#provide-diagnostics). The LSP client could then use this API instead of its own.

I know, that the built-in LSP client introduces `vim.lsp.diagnostic` namespace, but the namespace already implies, that it is only for LSP, even if it might be used by third party plugins too. Wouldn't something like `vim.diagnostic` be better?

Diagnostic messages could have then an information about the source i.e. built-in LSP client or a plugin name, so it would be easier to find, where the message is coming from.

What do you think about that?

**Comment by bew** [comment]
So in a similar way as ALE, neomake and others does it, the builtin diagnostic api would have a list of sources for diagnostics, and LSP would be one of the (default) source.
And then similarly to the current `vim.lsp.diagnostic` it would be used by anyone for anything (for display, to fill quickfix/loclist, for statusline, ...).

I'm not in the core team, but I think it's a _very_ good idea!
And in general I think (and I know I'm not alone) that we need more unified APIs like this that plugins can be based on instead of re-inventing the wheel.

_(like completion, notification (which already exist :+1:), maybe signs could be defined like this instead of a 'flat' list, ...)_

**Comment by glacambre** [comment]
I think the quickfix window is meant to be the unified diagnostic API. It would be interesting to know why ALE and vim-lsp aren't using it and if the quickfix window could be improved to make using it attractive to more plugins.

**Comment by mfussenegger** [comment]
I'm abusing `vim.lsp.diagnostic` as a generic diagnostic API in [nvim-lint](https://github.com/mfussenegger/nvim-lint). There some aspect that are a bit hacky (e.g. it passes an arbitrary client-ip to the publish handler - this currently works because internally the client is not used, but it theoretically could break at some point) but it works surprisingly well.

Having a `vim.diagnostic` API designed for general use would have been nice.

**Comment by nawordar** [comment]
> I think the quickfix window is meant to be the unified diagnostic API. It would be interesting to know why ALE and vim-lsp aren't using it and if the quickfix window could be improved to make using it attractive to more plugins.

I completely forgot about quickfix. Yes, it does sound like a better idea to improve the quickfix window instead of making a completely new API

**Comment by mjlbach** [comment]
Closed by https://github.com/neovim/neovim/pull/15585/files
