### ISSUE TITLE
[security] Codecov security incident (malicious Bash uploader)

### ISSUE THREAD

**Issue by koernepr** [neovim/neovim#14396]
Codecov's Bash uploader was compromised; quoting the [advisory](https://about.codecov.io/security-update/):

> The altered version of the Bash Uploader script could potentially affect:
> 
> * Any credentials, tokens, or keys that our customers were passing through their CI runner that would be accessible when the Bash Uploader script was executed.
> * Any services, datastores, and application code that could be accessed with these credentials, tokens, or keys.
> * The git remote information (URL of the origin repository) of repositories using the Bash Uploaders to upload coverage to Codecov in CI.

It looks like Neovim might be affected: The README contains a Codecov badge and there is a reference to `https://codecov.io/bash` in [submit_coverage.sh](https://github.com/neovim/neovim/blob/master/ci/common/submit_coverage.sh) for example.

Related discussion: https://github.com/jupyterhub/team-compass/issues/398

**Comment by jamessan** [comment]
Thanks for the heads up.  We don't actually use any secrets/tokens aside from the temporary ones created for each action.

**Comment by minrk** [comment]
Happened to see this since it links to our discussion. One thing I think folks don't quite appreciate is that all actions have *write* access to your repo if they run from a branch on your repo, **even if you don't pass them a token.** This is because the GHA runner provides all actions a `${{ github.token }}` which unconditionally has write access.

In particular, the checkout action ([used here](https://github.com/neovim/neovim/blob/66f9dd3c6e2e2968e4534ac0eacb7695f97c11b1/.github/workflows/ci.yml#L36) and ~everywhere) puts a token with write access to your repo in a common and easily discoverable place readable by every later step in the job (in .git/config).

So while your secrets may not be directly compromised, the malicious code did have the ability to push additional commits to your repo, which may in turn have been able to access certain secrets in later runs. So if you have concerns, you need to audit all commits (author and committer is not enough, only the *actor* in the github events archive is identifiable). If you have enabled branch protection, there's less to worry about.

**Comment by koernepr** [comment]
@jamessan Please see the comment above (and the linked discussion).

**Comment by jamessan** [comment]
I did. We have branch protections enabled, and now that GitHub allows [limiting the permissions](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/) for the transient token, we'll switch over to read only permissions for most things.

**Comment by koernepr** [comment]
Great, thanks!
