### ISSUE TITLE
Too wide hard tabs by default

### ISSUE THREAD

**Issue by Logarithmus** [neovim/neovim#14518]
- `nvim --version`: `NVIM v0.4.4`
- Operating system/version: `Void Linux (rolling)`
- Terminal name/version: `kitty 0.20.1`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

Just open any file which uses hard tabs for indentation

### Actual behaviour

Hard tabs are 8 spaces wide, which wastes screen real estate. I've seen the argument "we use 8 tabs because printers use 8 tabs", but it seems not very applicable for `nvim`. AFAIK, most `nvim` users are computer-related people like programmers, system administrators, etc. Come on, it's 2021 out there, not 1960! Programmers don't print source code on paper anymore!

I propose `tabstop=4` as default. 2 is too narrow for some languages, 8 wastes screen real estate. 4 seems like a reasonable middle ground. Also many people put `tabstop=4` in their `init.vim` anyway.

### Expected behaviour

`tabstop=4` by default

**Comment by jamessan** [comment]
It's trivial to change if you want something different, and printing isn't the only scenario where that matters.

**Comment by Logarithmus** [comment]
> It's trivial to change if you want something different, and printing isn't the only scenario where that matters.

Could you be so kind and tell about those scenarios, because I can't really come up with any of such?

**Comment by jamessan** [comment]
> Could you be so kind and tell about those scenarios, because I can't really come up with any of such?

Only everything _other_ than a text editor with configurable tab width.

Not to mention that using different tab widths is a false nirvana anyway, since most people still tend to _align_ text after the indent with spaces.  That means that any tab width other than the one that was in use by the person doing the aligning is going to be wrong.

As you suggest, tab width is a subjective thing, so why should we impose anything other than the default value on our users?  People/projects can choose to use a non-default value as they please.

> many, if not majority of free software projects have weird defaults

There's nothing weird about a tab stop of 8.  There probably _are_ defaults that could be reasonably argued as weird, but tab stop being 8 is not one of them.

> Personally, I see it as an example of gatekeeping.

The fact that we let you configure tab stop but don't want to change the default value to your preferred value (which would only upset the next person) is gatekeeping?  Adding `set tabstop=4` to your init.vim is "extensive configuration"?

Anyway, real programmers don't use tabs for indenting.  That reduces the size of their files, and every byte counts!

**Comment by janlazo** [comment]
Changing tabstop value is possible in another release if you can do the hard work of updating `runtime/` files to not depend on the default values for indent,tab options and then send those updates to their respective maintainers. Neovim uses Vim's `runtime/` files for filetype,indent,syntax support so upstream this issue if you want Neovim to change the default values for indent,tab options.
