### ISSUE TITLE
JavaScript highlighting breaks if backtick is inside regex

### ISSUE THREAD

**Issue by Anthony-Gaudino** [neovim/neovim#14553]
- `nvim --version`: NVIM v0.4.4
- Operating system/version: Debian Sid
- Terminal name/version: xfce4-terminal 0.8.10
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Enter this on VIM and use JavaScript highlighting `:set filetype=javascript`.
```js
function test() {
 return myfunc(/`/g, 'param2');
}

function anotherFunc() {
}
```

### Actual behavior
The JavaScript syntax highlighting is incorrect due to the backtick (`) in the regex. From the backtick onward the highlighter thinks it's a string.

### Expected behavior
The rest of the file should not be highlighted as a string.

**Comment by clason** [comment]
Issues with runtime files (in particular syntax files) alway need to be addressed upstream first since neovim does not want to diverge from vim in this regard without a special reason.

The procedure is 
1. contact the maintainer of the syntax file (listed at the top of, here, `runtime/syntax/javascript.vim`), in this case Claudio Fleiner <claudio@fleiner.com>
2. once the maintainer has updated the file, open an issue for vanilla vim (via github or the mailing list)
3. once vim has updated the file, open an issue or a PR here to update neovim's version to upstream; you can see the exact format of these PRs in the list of closed PRs (e.g., https://github.com/neovim/neovim/pull/13718).

**Comment by clason** [comment]
There's also https://github.com/pangloss/vim-javascript, which may give better results in this case.

**Comment by mhinz** [comment]
The given example is already fixed on master.
