### ISSUE TITLE
diff-mode: Use patience algorithm

### ISSUE THREAD

**Issue by dbarnett** [neovim/neovim#1466]
When diffing buffers with vimdiff or `:diffthis`, vim uses a diff algorithm that sometimes chooses poor alignment. Would it be possible to implement [patience diff](http://bramcohen.livejournal.com/73318.html) support for diff mode in neovim?

If performance is a significant factor, it could be controlled by a setting.

**Comment by justinmk** [comment]
A new plugin implements this: https://github.com/chrisbra/vim-diff-enhanced

**Comment by liujoey** [comment]
will give it a try.

**Comment by LemonBoy** [comment]
Some thoughts on the issue, since I was thinking of adding support for the unified diff [1] format as opposed to the normal format [2], which is the one vim currently understands.
The first step was getting my feet wet in the deep sea of the vim codebase (the diff.c part wasn't hard to understand or 'dirty', imo it should use a bit more comments) and after a brief look it seems that it won't be too hard to plug in this useful feature (converting the diff format by hand isn't that good).

Another idea that sparked into my mind was to use libxdiff (the forked & improved version from git source code) [3] to have an in-house way of diffing the files.

There are a few advantages
* No shelling out (more portable ?)
* Fast(er than diff ?)
* Reliable (since it's being battle-tested by git)
* Provides the histogram/patience algorithms along with the good 'ol myers

As well as a few drawbacks
* No way to use a CVS-specific diff (not that it's possible anyway due to the incompatible diff format)
* One more library to take care of (but it should be pretty stable due to the fact is actually being used by git)

Sorry for the long post, I hope to have got everything right.

[1] https://www.gnu.org/software/diffutils/manual/html_node/Detailed-Unified.html#Detailed-Unified
[2] https://www.gnu.org/software/diffutils/manual/html_node/Detailed-Normal.html#Detailed-Normal
[3] https://github.com/git/git/tree/master/xdiff

**Comment by justinmk** [comment]
@LemonBoy Only advantage you listed compared to https://github.com/chrisbra/vim-diff-enhanced is no shelling out. I've yet to hear of anyone wanting to diff a 100 MB file. Has anyone had *performance* problems with Vim's diff?

**Comment by Pyrohh** [comment]
Perhaps we could have an implementation in Lua, which would presumably be much shorter, and might allow for efficient diff updating (`:diffupdate` automatically) in real time. This is just an idea, given we haven't done much in Lua combined with C so far.

**Comment by justinmk** [comment]
@Pyrohh That was alluded to in https://github.com/neovim/neovim/issues/1007

**Comment by Pyrohh** [comment]
Thanks, it seems I missed a lot of interesting discussions.

**Comment by justinmk** [comment]
I feel the same way after 3 *days* :)

**Comment by tagirb** [comment]
https://github.com/vim/vim/pull/2732
What about porting this to neovim?

**Comment by aktau** [comment]
So https://github.com/vim/vim/commit/e828b7621cf9065a3582be0c4dd1e0e846e335bf was merged into Vim, authored by the creator of vim-diff-enhanced (@chrisbra). He mention son github.com/chrisbra/vim-diff-enhanced/issues/11 that this makes the vim-diff-enhanced plugin obsolete. That issue also takes about a performance issue with a `diffexpr` approach. It is essentially @LemonBoy's proposal from up above: integrating libxdiff. Not saying it should be done, but it's a Vim incompatibility to look out for and we might not be able to point to vim-diff-enhanced so much anymore if people come asking.

**Comment by justinmk** [comment]
we'll merge it, just like we merge almost all Vim patches. Someone needs to send a PR.

**Comment by chrisbra** [comment]
FWIW, the vim-diff-enhanced plugin is still functioning. There is no logic in it currently, that checks for the internal diff library, although I do plan on making this change. However this will be included behind a `has` patch condition, so it should keep on working with Vim/Neovim that do not support this feature.
