### ISSUE TITLE
Add "Expected Failure" test status to testsuite

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#14738]
As mentioned yesterday in chat, I think having an "Expected Failure" and an "Unexpected Pass" test status would help a lot with managing Github issues. Tests could be filed as soon as issues are created and this would help ensure that the issue being reported is valid and that issues do not outlive their bugs, as an "Unexpected Pass" would be a good signal that an issue can be closed.

It seems that Busted doesn't support xfails for now, but it might not be too hard to either implement upstream or to come up with a scheme that simulates this test status.

**Comment by jamessan** [comment]
https://github.com/Olivine-Labs/busted/issues/665 for the busted side of things.

**Comment by glacambre** [comment]
https://github.com/lunarmodules/busted/pull/658 might be enough to implement `xfail`. I'll look into it.

**Comment by eskerda** [comment]
@glacambre let me know if you want any help on that. On the process of writing https://github.com/eskerda/busted-flaky I did mess a lot with the related internals

**Comment by justinmk** [comment]
> Tests could be filed as soon as issues are created and this would help ensure that the issue being reported is valid and that issues do not outlive their bugs

This isn't blocked on the existence of `assert.fail()` though. Can be done using `assert` or `eq` already.

**Comment by glacambre** [comment]
@justinmk The tests would fail, but they'd be logged as failing, instead of as "expected to be failing". Developer time would be wasted trying to figure out whether their change is making the test fail or if it was already failing.

**Comment by justinmk** [comment]
Maybe. It's not common, but my current practice is to just add a comment like:

    -- If this test fails that means the bug was fixed, yay

Actually, I'm not sure how "Expected Failure" or "Unexpected Pass" would avoid confusion here. Maybe a concrete example is needed.

**Comment by jamessan** [comment]
> This isn't blocked on the existence of `assert.fail()` though. Can be done using `assert` or `eq` already.

The difference is that you write the test as it _should_ behave, but then mark it as expected to fail.  Particularly if there may be various reasons why a certain test scenario fails, writing a test for the expected behavior and annotating it is easier (and clearer) than changing the various failure points to negative tests.

Subversion makes heavy use of xfail, and they describe it as [such](https://github.com/apache/subversion/blob/0f4de5d963ce3b43084f66efab0901be15d2eec2/subversion/tests/README#L75-L85):

> Instead of SVN_TEST_PASS, you can use SVN_TEST_XFAIL to declare that a
test is expected to fail. The status of such tests is then no longer
marked as PASS or FAIL, but rather as XFAIL (eXpected FAILure) or
XPASS (uneXpected PASS).
> 
> The purpose of XFAIL tests is to confirm that a known bug still
exists. When you see such a test uneXpectedly PASS, you've probably
fixed the bug it tests for, even if that wasn't your intention. :-)
XFAIL is not to be used as a way of testing a deliberately invalid
operation that is expected to fail when Subversion is working
correctly, nor as a place-holder for a test that is not yet written.

**Comment by justinmk** [comment]
> The difference is that you write the test as it _should_ behave, but then mark it as expected to fail.

Oh I get it now :)
