### ISSUE TITLE
lsp: rust-analyzer code lens actions do not work

### ISSUE THREAD

**Issue by hallmaxw** [neovim/neovim#14874]
- `nvim --version`: NVIM v0.5.0-dev
- Operating system/version: NA
- Terminal name/version: NA
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

You'll need the rust toolchain and rust-analyzer on your PATH to run the repro steps. 

My init.vim:

```
call plug#begin('~/.config/nvim/plugged')

" Collection of common configurations for the Nvim LSP client
Plug 'neovim/nvim-lspconfig'

call plug#end()

lua <<EOF

-- nvim_lsp object
local nvim_lsp = require'lspconfig'

-- Enable rust_analyzer
nvim_lsp.rust_analyzer.setup({})

EOF
```

Initialize a rust crate and open up the generated source:

```bash
mkdir rust_analyzer_repro
cd rust_analyzer_repro
cargo init --lib
nvim src/lib.rs
```

lib.rs should contain:
```
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
```

Try running the included test 

1. Refresh code lens `:lua vim.lsp.codelens.refresh()`
2. Move your cursor over `it_works`
3. Try executing the "Run Test" code lens `:lua vim.lsp.codelens.run()` (select the Run Test option)

### Actual behaviour

The following error is returned:
>RPC[Error] code_name = MethodNotFound, message = "unknown request"

### Expected behaviour

I expected the test to be executed.

The problem is neovim is trying to execute the command via the workspace/executeCommand LSP API, but this operation is unsupported by rust-analyzer. See this related rust-analyzer issue created by a maintainer of LanguageClient-neovim https://github.com/rust-analyzer/rust-analyzer/issues/1232.

**Comment by mjlbach** [comment]
My stance on this has always been if the server requires any custom extensions/handlers not in the spec, as it seems from that issue, it will have to go into a plugin

**Comment by hallmaxw** [comment]
I tried taking a stab at writing a plugin to handle this. I'd like to write a plugin that customizes how neovim executes lenses specifically for rust-analyzer LSP clients. However, I don't think it's possible given the current customization options.

A `workspace/executeCommand` handler doesn't work because the custom handler is executed after sending the request to rust-analyzer, which fails. I don't see any other ways to extend the logic in code lens execution.

@mfussenegger It does seem like expanding your PR could address this issue.

**Comment by mjlbach** [comment]
I'm going to close this issue, since we aren't planning to add (specific) support for rust-analyzer directly in core. We can continue the discussion on #14115 on how to make sure a plugin can easily register the correct client side command.

**Comment by matklad** [comment]
>My stance on this has always been if the server requires any custom extensions/handlers not in the spec, as it seems from that issue, it will have to go into a plugin

Agree that that's the best way to do it -- that way, the development is decentralized, and each language can get perfect support, rather than the lowest common denominator. Note that this is how the stuff architectured in VS Code as well -- the core of the editor doesn't know anything about the protocol, there's just an vscode-LSP library which is shared by language-specific plugins. 

One point of caution here though is that the dev process for the spec itself is closely tied to VS Code for many features. Roughly, a feature is implemented in VS Code, and then is exposed via LSP. Features which are not implemented in VS Code have a harder time getting into the spec, sadly. 

So, it might make sense to implement common extensions, even if they are not in the spec. One such example would be [utf8 offsets](https://github.com/microsoft/language-server-protocol/issues/376#issuecomment-767608565). Sadly, I don't think there's a process around designing common, but out-of-spec extensions.
