### ISSUE TITLE
Active Signature Highlight fails when the server is using labels rather than offsets, and there are multiple equal labels

### ISSUE THREAD

**Issue by urandom** [neovim/neovim#15022]
The active signature parameter highlight (74527a30edf4c71c6376343d5cd23fe0584def01) fails when the server is not using offsets, and there are multiple parameter labels with the same value

<img width="414" alt="Screenshot 2021-07-08 at 09 13 49" src="https://user-images.githubusercontent.com/7908/124879194-a4bfe680-dfd5-11eb-8ab4-82b89cb5977b.png">

**Comment by folke** [comment]
There is no easy (or non-hacky) way around this, apart maybe from using trigger characters in order to determine the active parameter in case parameter names are the same.

I don't think your example would happen often in real life use cases tbh.

I would also argue that the better fix would be to file an issue to the lsp server to make sure they support label offsets, which is the real solution.

From the Neovim side, we send the correct list of capabilities to deal with offsets:
![image](https://user-images.githubusercontent.com/292349/124997068-e31dcb80-dffe-11eb-96b4-803d01b70548.png)

**Comment by folke** [comment]
Actually it might be easier to do this than I initially thought.

We simply need to loop over all parameters and `find` them one by one with the `offset` to find being the previous `end`.

Until we arrived at the active parameter.

**Comment by folke** [comment]
I made a new PR locally, but need to be able to test this somehow. What language is that in your screenshot? :)

**Comment by mjlbach** [comment]
Guessing golang :)

**Comment by folke** [comment]
right :) Don't have that setup yet. I'll get some sleep here first and will test tomorrow

**Comment by urandom** [comment]
@folke 
Right, looping over all parameters and finding the position of the current one is how i fixed the problem in my active parameter pr. I think it's the way to go, and it's not difficult.

I can also test it if you want

**Comment by folke** [comment]
@urandom juts pushed a PR. Would be good if you could review/test. Thanks!
