### ISSUE TITLE
LSP shows "LspDiagnosticsSign" in the wrong line using Lua Sumneko Server

### ISSUE THREAD

**Issue by charbelnicolas** [neovim/neovim#15093]
- `nvim --version`: 0.5
- Operating system/version: Arch Linux 5.12.15-arch1-1
- Terminal name/version: Kitty 0.21.2
- `$TERM`: xterm-kitty

I'm not sure how to reproduce this without plugins enabled since lsp-config takes care of everything LSP related.

What I found is that while using the Lua Sumneko Server, if an Error, Warning, Information or Hint diagnostic comes up on the very first word of the line, the diagnostic sign will appear one line above where the actual diagnostic is supposed to be.

### Actual behaviour

Please watch the video below:

https://user-images.githubusercontent.com/14960414/125733653-97b2644b-a7cc-4026-a19a-dc9d7b79cc22.mp4

### Expected behaviour

The diagnostic sign should be shown on the actual line of the error, hint, warning or information.

**Comment by mjlbach** [comment]
I thought this was a duplicate, but I think the person who asked had asked on Matrix. I debugged this awhile ago, and sumneko returns the range that is displayed. If you take a look at lsp.log after setting the log level to "trace" you should also see this. If not feel free to reopen, but otherwise this should be reported to https://github.com/sumneko/lua-language-server
