### ISSUE TITLE
effective runtime path is repeated for pre-startup start/ packages after startup 

### ISSUE THREAD

**Issue by stasjok** [neovim/neovim#15101]
- `nvim --version`: 0.5.0
- Operating system/version: linux
- Terminal name/version: WT
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

Run command:

```
:2verbose runtime! indent/foo.vim
"or
:11verbose runtime! indent/foo.vim
```

### Actual behaviour

```
not found in 'runtimepath': "indent/foo.vim"
not found in 'packpath': "pack/*/start/*/indent/foo.vim"
not found in 'packpath': "start/*/indent/foo.vim"
```
It searches for sourced file in runtimepath and in packpath. Every 'start' package is automatically in runtimepath, so it sources them two times.

### Expected behaviour

```
not found in 'runtimepath': "indent/foo.vim"
```
File should be sourced only one time from runtimepath.

### Context

I was having trouble to override indent file from ansible plugin. I created file `after/indent/ansible.vim` with my modifications, but it didn't work. Turns out nvim first sources stock file (because it's in runtimepath), then my file, and then stock file once again ('start' directory in 'pack'). I managed to "fix" it by using file `start/my/indent/ansible.vim`, but that way nvim sources every ansible file (my and stock) two times.
There is autocommand in indent.vim:
```exe 'runtime! indent/' . name . '.vim'```
Based on `:h :runtime` when `[where]` is omitted only 'runtimepath' should be used. But instead it sources runtime plus "start" in 'packpath'.

My first attempt to override plugin indent (note that plugin's file sourced two times):
```
sourcing "/home/stas/.local/share/nvim/site/pack/packer/start/ansible-vim/indent/ansible.vim"
finished sourcing /home/stas/.local/share/nvim/site/pack/packer/start/ansible-vim/indent/ansible.vim
sourcing "/home/stas/.config/nvim/after/indent/ansible.vim"
finished sourcing /home/stas/.config/nvim/after/indent/ansible.vim
sourcing "/home/stas/.local/share/nvim/site/pack/packer/start/ansible-vim/indent/ansible.vim"
finished sourcing /home/stas/.local/share/nvim/site/pack/packer/start/ansible-vim/indent/ansible.vim
not found in 'packpath': "start/*/indent/ansible.vim"
```
I managed successful to override it by placing my file in 'start' directory:
```
sourcing "/home/stas/.config/nvim/start/my/indent/ansible.vim"
finished sourcing /home/stas/.config/nvim/start/my/indent/ansible.vim
sourcing "/home/stas/.local/share/nvim/site/pack/packer/start/ansible-vim/indent/ansible.vim"
finished sourcing /home/stas/.local/share/nvim/site/pack/packer/start/ansible-vim/indent/ansible.vim
sourcing "/home/stas/.local/share/nvim/site/pack/packer/start/ansible-vim/indent/ansible.vim"
finished sourcing /home/stas/.local/share/nvim/site/pack/packer/start/ansible-vim/indent/ansible.vim
sourcing "/home/stas/.config/nvim/start/my/indent/ansible.vim"                                                                                                                                                                                 finished sourcing /home/stas/.config/nvim/start/my/indent/ansible.vim
```

**Comment by bfredl** [comment]
The behavior was originally changed for two reasons:

- 'packpath' gets translated to 'rtp' _after_ startup, so all plugins that relied on 'rtp' during startup broke
- subsequent 'packpath' updates won't get reflected in 'rtp'

The ideal idea was that we could avoid adding 'start' packages to 'rtp' _at all_ (which also would side step the rtp length issue). Though there was some heisenbreakage when using `start/` in all places that used 'rtp', so we opted not to do this for 0.5, but perhaps we should try again for 0.6.

**Comment by therealdannzor** [comment]
I noticed this issue also when I looked through verbose logs. Without having done any benchmark at all, I wonder if this impacts the performance of the client notably? I get the impression that after upgrading to 0.5.0 things are a bit slower, especially the highlighter after fixing incorrect syntax and such may take several seconds now as opposed to almost-instantly.

**Comment by bfredl** [comment]
it shouldn't affect the highlighter at runtime, only when loading queries (once per filetime).

**Comment by stasjok** [comment]
Could you at least de-duplicate loading? I mean to remember somehow what files was already sourced during current `runtime!` command and not sourcing them again? I was using Plug earlier and it was working perfectly (because it doesn't use pack directory). And after switching to packer.nvim I imagine all these ftplugin/indent/syntax files are sourced twice. Sure most plugins use some guarding against double sourcing like
```
if exists("b:did_ftplugin")
    finish
endif
let b:did_ftplugin = 1
```
but it still can produce some slowdown (probably negligible) or even undesired behavior (as in my case when I was debugging why it doesn't work properly when it worked with my earlier setup). Plus vim sources file only once (but I see now that it was intended change in neovim).

**Comment by gpanders** [comment]
Related https://github.com/neovim/neovim/issues/15272

**Comment by bfredl** [comment]
WIP: #15632

**Comment by gwerbin** [comment]
Out of curiosity, why would `:runtime!` ever even look at what's in `'packpath'`, let alone run files there?

Based on my reading of the Vim help files, `'packpath'` is supposed to exist solely in order to tell Neovim _where to find packages_, which are added to `'runtimepath'` either on startup (if in `pack/*/start/`) or upon `:packadd[!]` (if in `pack/*/opt/`).

As a result, I was under the impression that `:runtime!` should not double-source anything, because `'runtimepath'` should usually contain unique values.

Moreover, I would have thought the simple way to fix this would be to just remove this line in `source_runtime()`:

[v0.5.1 nvim/runtime.c L238](https://github.com/neovim/neovim/blob/v0.5.1/src/nvim/runtime.c#L238)

```c
int source_runtime(char_u *name, int flags)
{
  flags |= (flags & DIP_NORTP) ? 0 : DIP_START;  // <-- This line. Why is this even here??
  return source_in_path(p_rtp, name, flags);
}

```

which specifically requests `do_in_path_and_pp()` to descend into `pack/*/start/*/%s` and `start/*/%s`. Ergo, setting `DIP_START` default does _not_ correspond to the documented behavior of `:runtime!` and it doesn't make much sense anyway.

Removing `pack/*/start/` from `'runtimepath'` seems like a really blunt instrument for fixing this problem, which causes downstream issues (described in https://github.com/neovim/neovim/pull/15632) and which I think is just semantically weird.

Clearly bfredl knows a whole lot more about this situation and the code than I do, but I am very curious as to why the core devs decided to go the way they went.

**Comment by gwerbin** [comment]
Out of curiosity, why would `:runtime!` ever even look at what's in `'packpath'`, let alone run files there?

I know it's in the documentation, but it seems like weird and unintuitive behavior. If putting something into `pack/*/start/` already adds it to `'runtimepath'`, and if `:packadd[!]`-ing something in `pack/*/opt/` already adds it to `'runtimepath'`, wouldn't it be easier to just change `:runtime!` to _only_ look in `'runtimepath'` and not also try to look in `'packpath'`?

Removing `pack/*/start/` from `'runtimepath'` seems like a really blunt instrument for fixing this problem, and I think it leads to really weird semantics about what exactly the "runtime path" is supposed to mean.

Was the objective here to preserve Vim-compatibility? Are there a lot of plugins and/or package-related Vim internals that rely on this behavior of `:runtime!`?

---

If you wanted to break compatibility, it looks like the simple way to fix this would be to just remove this line in `source_runtime()`:

[v0.5.1 nvim/runtime.c L238](https://github.com/neovim/neovim/blob/v0.5.1/src/nvim/runtime.c#L238)

```c
int source_runtime(char_u *name, int flags)
{
  flags |= (flags & DIP_NORTP) ? 0 : DIP_START;  // <-- This line. Why is this even here??
  return source_in_path(p_rtp, name, flags);
}
```

And then of course the docs would have to be updated accordingly.

**Comment by bfredl** [comment]
@gwerbin see https://github.com/neovim/neovim/pull/15867/. Seems we can add `XDG_DATA_DIR/nvim/site/pack/*/start/*` (et al) as an _unexpanded_  wildchar to `&rtp` which keeps it both short and explicit and still supporting `globpath(&rtp, ...)`.

**Comment by gwerbin** [comment]
@bfredl Wow, cool!

Is this an accurate-ish summary of the changes?

* Items in `pack/*/start` will be added to `runtimepath` when they are first loaded, like in v0.5.1.
* `:runtime!` de-duplicates files so that it doesn't somehow source a file twice.
* `'runtimepath'` now accepts glob patterns.

That's as far as I could gather with my limited C skills. If so, that's a really great set of changes!
