### ISSUE TITLE
Range of current visual selection is invalid

### ISSUE THREAD

**Issue by s1n7ax** [neovim/neovim#15144]
- `nvim --version`: NVIM v0.5.0
- Operating system/version: Arch Linux
- Terminal name/version: suckless st
- `$TERM`: st-256color

[ ] `vim -u DEFAULTS` (version: ) behaves differently

### Steps to reproduce

* Add following key bind+ to print the selection range
```
:lua vim.api.nvim_set_keymap('x', ',w', '<cmd>lua print(vim.inspect(vim.api.nvim_buf_get_mark(0, "<")), vim.inspect(vim.api.nvim_buf_get_mark(0, ">")))<cr>', {})
```
* Open a file with multiple lines
* Hit `V` to select the first line
* Hit `,w` to print the range
* Hit `V` in the second line
* Hit `,w` to print the range

### Actual behaviour

**First line output**

```
{ 0, 0 } { 0, 0 }
```

**Second line output**

```
{ 1, 0 } { 1, 2147483647 }
```

### Expected behaviour

**First line output**

```
{ 1, 0 } { 1, 2147483647 }
```

**Second line output**

```
{ 1, 0 } { 2, 2147483647 }
```

**Comment by dstanberry** [comment]
What's strange is that executing `lua print(vim.inspect(vim.api.nvim_buf_get_mark(0, "<")), vim.inspect(vim.api.nvim_buf_get_mark(0, ">")))` in command mode while the selection is active works as expected. 

It looks like it only works in this case because the selection is "unselected" before the evaluation happens. So, a temp. workaround could be to reset your selection before calling `nvim_buf_get_marks(...)`.

**Comment by zeertzjq** [comment]
`'<` and `'>` are the previous Visual selection, not the current Visual selection.
```
- In Visual mode you can use `line('v')` and `col('v')` to get one end of the
  Visual area, the cursor is at the other end.
```
