### ISSUE TITLE
Porting patches that use test_* functions

### ISSUE THREAD

**Issue by VVKot** [neovim/neovim#15187]
### Feature already in Vim?

Yes

### Feature description

I wanted to port https://github.com/vim/vim/commit/07ada5ff2fd8f22ed3233ae5c4ddf87c7b3f56fe but neovim does not have `testing.c` to put this in https://github.com/vim/vim/commit/07ada5ff2fd8f22ed3233ae5c4ddf87c7b3f56fe#diff-0237800c5fd886a66364f685a101cd2d77c583eb759ba84229e2b43df07f219c. Judging by the `vim_diff`, this is expected, and I should use some API function instead. What that function would be?

**Comment by VVKot** [comment]
I presume that's a @janlazo question.

**Comment by justinmk** [comment]
`test_` functions are almost never needed, they are hacks. Usually screen test adds the same (or often better) coverage. For `test_clear_search_pat` specifically, IIUC it isn't needed because each Nvim test starts a new `nvim` instance so there is no need to "clear the search pattern". The `clear()` function in our tests also takes optional arguments that allow more control over how `nvim` is started:

https://github.com/neovim/neovim/blob/5e0c435ca1b711e80f78429431b4d400d789c618/test/functional/helpers.lua#L399-L415

But clear() probably isn't needed (saves 30ms), because the test session is started with `-i NONE -u NONE`:

https://github.com/neovim/neovim/blob/5e0c435ca1b711e80f78429431b4d400d789c618/test/functional/helpers.lua#L41-L43

**Comment by VVKot** [comment]
@justinmk thanks! I guess it *is* need for cases where we want to specifically reset search pattern like here: https://github.com/neovim/neovim/pull/15188/files#diff-fad08c197a65cb28247af99fbb663f5ef4c65918d2846641c3131d270aebaabc.

However, I can easily do the same with ` let @/ = ''`

**Comment by janlazo** [comment]
https://github.com/vim/vim/commit/07ada5ff2fd8f22ed3233ae5c4ddf87c7b3f56fe is N/A because it's reverted in 8.2.0250. I didn't mark those 2 N/A (yet) because of v8.2.0243.
