### ISSUE TITLE
Support ignoring tree-sitter 'queries' for a specific language from specific plugins

### ISSUE THREAD

**Issue by MunifTanjim** [neovim/neovim#15244]
### Feature description

A way to disable loading tree-sitter queries from the `queries` directory for a specific language from specific plugins.

I'm aware of `vim.treesitter.set_query`, which sets explicit queries for a language. But then it doesn't load any queries for that language from any plugins at all. This feature request is different from that.

### Usecase

- I'm wrote a new tree-sitter parser for `language-x`.
- `nvim-treesitter`, `nvim-treesitter-textobjects` plugins already have queries for `language-x` written for a different parser.
- I want to completely disable queries for `language-x` from those plugins.
- I want to use queries for `language-x` from other plugins if they have them.

**Comment by vigoux** [comment]
As @clason suggested, I add the discussion flair to this issue, as we need to discuss how to proceed a bit.

I'd say that we could provide a new function named `ignore_queries(lang, query_type, list_of_plugins)` which does the following:
- When `list_of_plugins` is `"all"` just disable everything
- When `list_of_plugins` is a table, use this to search in the different query paths, if there's a match, then ignore this query file, otherwise use it

**Comment by MunifTanjim** [comment]
I've created a Draft PR to discuss further implementations https://github.com/neovim/neovim/pull/15260

**Comment by MunifTanjim** [comment]
I just found another PR related to this: https://github.com/neovim/neovim/pull/14932

@theHamsta any thoughts?

**Comment by theHamsta** [comment]
I think the PRs are complementary. The current `set_query` is not good and needs to be fixed. You could implement your PR in terms of mine by setting `set_query` to a function filtering the queries. This would be a more general solution.

**Comment by MunifTanjim** [comment]
Any update for this one? 😅 Any feedback is appreciated... even if it is "we won't allow it".
