### ISSUE TITLE
Support `codeAction/resolve` in LSP

### ISSUE THREAD

**Issue by David-Else** [neovim/neovim#15339]
### Feature description

Currently any language server than uses `codeAction/resolve` crashes when the code action is selected with:

```
Error executing vim.schedule lua callback: ...nt_nvimPgykEF/usr/share/nvim/runtime/lua/vim/lsp/buf.lua:458: command: ex
pected string, got nil
```

This is the case with the Deno LSP, and in this (partially related) thread a Deno maintainer explains what is happening and why `codeAction/resolve` is needed: https://github.com/denoland/deno/issues/11610#issuecomment-896277545

**Comment by justinmk** [comment]
can you try latest Nvim with https://github.com/neovim/neovim/pull/14115 , and  try configuring `vim.lsp.commands`

**Comment by mfussenegger** [comment]
> can you try latest Nvim with #14115 , and try configuring `vim.lsp.commands`

The linked PR won't fix the issue here. `codeAction/resolve` allows a language server to speed up showing the available actions because they don't have to pre-compute the `command` definition, instead it is lazily resolved once the user chooses an action.

What we need is something like this:

https://github.com/mfussenegger/nvim-jdtls/blob/afe619ec05866a3c2ff6f7af4c4b5b4f1d9fb7c6/lua/jdtls.lua#L694-L704

The main reason there isn't a PR yet for it is because I didn't want to create multiple ones affecting the same area.

I want to follow up on it once https://github.com/neovim/neovim/pull/15771 is resolved. (Though I guess I should have done the less controversial changes first :))
