### ISSUE TITLE
Termdebug: missing function: mapset 

### ISSUE THREAD

**Issue by igorlfs** [neovim/neovim#15458]
### Neovim Version

NVIM v0.5.0

### Operating system/version:

Void Linux

### Terminal name/version:

kitty 0.23.1

### TERM environment variable

xterm-kitty

### Installation

System package manager

### Steps to reproduce

Start bare neovim:
`$ nvim -u NONE`
Map K to something:
`:nnoremap K i`
Add Termdebug package and initialize a debugging session (tested with gdb):
`:packadd termdebug`
`:Termdebug`
Quit gdb:
`(gdb) quit`

### Vim

Yes, vim works just fine. Vim version: 8.2, included patches: 1-2874

### Expected behavior

Neovim should stop the debugging session without throwing an error. 

### Actual behavior

Neovim throws the following error:

     Error detected while processing function <SNR>_1EndTermDebug[3]..<SNR>1_EndDebugCommon[21]..<SNR>1_DeleteCommands:
     line 21:
     E117: Unknown function: mapset

Other than that, neovim quits the session normally.
Taking a look at the source code, I believe this behavior is due to neovim lacking such function.

**Comment by justinmk** [comment]
https://github.com/vim/vim/commit/4c9243f9fb708c9010867d3cc8e928f36b58509a

**Comment by gpanders** [comment]
> [vim/vim@4c9243f](https://github.com/vim/vim/commit/4c9243f9fb708c9010867d3cc8e928f36b58509a)

Porting this patch depends on https://github.com/neovim/neovim/pull/15293

**Comment by ii14** [comment]
Can't we use `nvim_get_keymap()` instead?

**Comment by clason** [comment]
No, that would just get a list of _all_ (global) mappings for a given mode. What we need and don't have yet is a method for _setting_ a keymap from a dict (similarly to `nvim_set_hl`).

The `mapset` can be replaced by `nvim_set_keymap`, it's just tedious since you need to manually extract all the options from the saved `maparg()`-dict and pass them individually.

**Comment by ii14** [comment]
Sorry, that's what I meant, getting the current mapping with `nvim_get_keymap` and then setting it back with `nvim_set_keymap`.

**Comment by clason** [comment]
Yes, but `nvim_get_keymap()` doesn't work like that (it's not paired with `set_keymap` like `get_hl`--`set_hl` are).

**Comment by ii14** [comment]
Sure, but you can pass the options individually, like you said. For the time being at least, until `mapset` is ported

**Comment by clason** [comment]
Again: it's not the `set` that's the problem, it's the `get` -- we currently don't have a function to get individual(!) mappings in a format that we can just pass to `nvim_set_keymap`. (We _do_ have `maparg`, though, so the `s:k_map_saved` is there.)

**Comment by ii14** [comment]
I tried it some time ago -- getting mappings with `nvim_get_keymap` and setting them back later with `nvim_set_keymap` -- and it seemed to work okay. Unlike maparg, `nvim_get_keymap` even returns `<SID>`s converted to `<SNR>XX_`, so that solves the problem of `nvim_set_keymap` not supporting `sid` option. Querying all mappings to get just one of them might be an overkill, but this could be fixed later.

**Comment by clason** [comment]
> Querying all mappings to get just one of them might be an overkill

That was exactly my point.

**Comment by ii14** [comment]
Okay, but can we do it anyway or do we just wait for `mapset`? I can do it over the weekend, maybe even later today.

**Comment by clason** [comment]
Oh, if you want to make a PR that replacs `mapset` with an explicit `nvim_set_keymap`, that would be very much appreciated!
