### ISSUE TITLE
RFE: Indent better when typing bullet lists

### ISSUE THREAD

**Issue by m1027** [neovim/neovim#15473]
neovim already detects a leading dash as bullet and can reformat a bullet list nicely (visual selection + gq).

But when typing a long line, starting with a bullet and when the line break kicks in, the second row is indented as if there was no bullet.

Desired behaviour: When the link break kicks in, the next line should (optionally) start a little more to the right, just like gq does on the marked paragraph.

**Comment by gpanders** [comment]
This is entirely up to the filetype plugin in question. You didn't mentioned which filetype you're using, but I'll assume Markdown (this comment is relevant in any case). Neovim ships with the runtime files from Vim, which itself uses the Markdown runtime files from Tim Pope's [vim-markdown](https://github.com/tpope/vim-markdown). That filetype plugin handles all of the indentation, including the issue you've mentioned.

You can see who the maintainer of your filetype plugin is by running the following in Nvim:

```vim
:e $VIMRUNTIME/ftplugin/{filetype}.vim
```

so for example with Markdown:

```vim
:e $VIMRUNTIME/ftplugin/markdown.vim
```

If the behavior is not as you'd like it to be then you need to report the issue to the upstream filetype plugin. If and when they fix or update the behavior, those changes need to be updated in Vim itself, at which point they will be copied into Neovim. It can be a long process, which is why in many cases it's easier to just use the filetype plugin directly as one of your own plugins.

(There is also https://github.com/plasticboy/vim-markdown if you don't like tpope's vim-markdown.)

In any case, this is not an issue with Nvim.

**Comment by m1027** [comment]
Thanks for the detailed information on filetypes.

I am talking about ordinary txt files, though. I believe, there is no filetype plugin involved in this case, correct? At least I do not load anything specific for txt files I am aware of.

Please let me know whether I should adress my RFE elsewhere but currently I assume it *is* something built-in into neovim and thus concerns neovim directly.

**Comment by clason** [comment]
There _is_ a filetype plugin, since the filetype of `.txt` files is recognized as `text` (so look for `text.vim` under `runtime`), which _is_ shipped by neovim.

However, as @gpanders explained well, it is _not_ maintained by neovim -- we just take it from upstream vim (which possibly takes it from a separate plugin or an individual maintainer). 

So all requests and changes _must_ go through https://github.com/vim/vim.

**Comment by gpanders** [comment]
By the way, you can configure this behavior yourself by creating the file `~/.config/nvim/after/ftplugin/text.vim` and adding settings for `'formatlistpat'` and `'formatoptions'`. Read the help docs for these two options, and also look at e.g. `$VIMRUNTIME/ftplugin/markdown.vim` for an example of how they do it.
