### ISSUE TITLE
Unable to locate FZF binary with fzf.vim

### ISSUE THREAD

**Issue by paniash** [neovim/neovim#15528]
### Neovim version (nvim -v)

v0.6.0-dev+200-gb35de6c52

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Artix linux

### Terminal name/version

suckless terminal

### $TERM environment variable

`st-256color`

### Installation

Build from repo

### How to reproduce the issue

1. `nvim -u NORC`
2.  Install `fzf.vim` with neovim's package management feature (personally using vim-plug) and fzf binary installed through system's package manager (in my case, pacman). i.e.

```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'junegunn/fzf.vim'
call plug#end()
```

3. Run `:Files`

### Expected behavior

Be able to launch fzf within neovim.

### Actual behavior

Does not launch fzf and end up with the following error:

```
Error detected while processing function fzf#vim#with_preview:
line   59:
E117: Unknown function: fzf#shellescape
line   62:
E121: Undefined variable: preview_cmd
Error detected while processing function fzf#vim#files[15]..<SNR>62_fzf[1]..<SNR>62_check_requirements:
line    6:
E605: Exception not caught: fzf#run function not found. You also need Vim plugin from the main fzf reposit
ory (i.e. junegunn/fzf *and* junegunn/fzf.vim)
```

This is only true when building from source. When using neovim v0.5 (installed with pacman), neovim is able to pick up fzf binary installed with pacman and `:Files` command works!

**Comment by clason** [comment]
There is a (common) misconception here: the `fzf.vim` plugin is actually part of the `junnegun/fzf` repository (i.e., the plugin is bundled with fzf) -- what `junnegun/fzf.vim` provides is _additional_ functions for accessing vim internals (registers, buffers etc.) through `fzf`. The "classical" functions like `Files`, `Grep` etc. are part of the former.

What happens if you install both `(neo)vim` **and fzf** through your package manager is that the latter "helpfully" puts the `fzf.vim` (the one bundled with `fzf`) in the _system_ runtime directory for `(neo)vim`.

So this is not a bug; you just have wrong expectations due to being tricked by a overly helpful distribution.

**Comment by paniash** [comment]
@clason Thank you. I just wanted to know if it is possible to link the package manager installed fzf binary into the system runtime directory with source installed neovim.

**Comment by clason** [comment]
It's not about the `fzf` binary, it's about the vim scripts from `junnegun/fzf`. Those needs to be in your runtime path. How they get there is up to you ;)

**Comment by paniash** [comment]
> It's not about the `fzf` binary, it's about the vim scripts from `junnegun/fzf`. Those need to be in your runtime path. How they get there is up to you ;)

That's the thing.... I don't know how :-(. I've tried `set rtp+=/usr/bin/fzf` but it doesn't seem to work.

**Comment by clason** [comment]
because that's not where the _vim_ scripts are.

Why not just `Plug 'junegunn/fzf'`(without the `.vim`!), like its README recommends?

**Comment by paniash** [comment]
Ah! I get it now. Thank you :-) (and sorry for the annoying questions).
