### ISSUE TITLE
Relative Lua Requires

### ISSUE THREAD

**Issue by LandonSchropp** [neovim/neovim#15574]
### Feature already in Vim?

No

### Feature description

I've recently started using LunarVim, and I ran into an issue with it that took me quite a while to figure out.

I like to split my configuration across multiple files. One of these files is `plugins.lua`, and I set up my `config.lua` like this (LunarVim) requires `config.lua` from their `init.lua` file:

``` lua
require("settings")
require("keys")
require("plugins")
```

Unfortunately, LunarVim has also defined a `plugins.lua` file, which caused a naming collision that broke the LunarVim configuration in an unexpected way.

This problem is easily fixable by renaming my module, but this got me thinking that naming collisions are going to become a bigger problem as more tools start using Lua. Ideally, this problem could be solved by using relative imports instead of `runtimepath` imports.

```
require('./lua/plugins')
```

Barring that, it'd be great to be able to disambiguate plugins in requires so lower-level tools like LunarVim didn't need to reserve file names.

Thanks for the great editor!

**Comment by clason** [comment]
`require` is a basic Lua functionality; I don't think we can or should mess with its semantics as that would break all manner of implicit and reasonable assumptions.

There are other functions (like `luafile` and `dofile`, not to mention `runtime` and `source`) that allow more targeted loading and executing of `.lua` runtime files. I would suggest familiarizing yourself with those.

**Comment by bfredl** [comment]
> Unfortunately, LunarVim has also defined a plugins.lua file, which caused a naming collision that broke the LunarVim configuration in an unexpected way.

@LandonSchropp  This is obviously a bug with LunarVim. it should not define a package called `plugins` and other random common terms without a prefix, it should be properly namespaced and called `lunarvim.plugins` or something like that. I'll suggest filing a bug at LunarVim (they are free to choose not to care, but that would be their problem, not any any issue with neovim packpath semantics).

**Comment by LandonSchropp** [comment]
@clason Thanks for the suggestions! I wasn't aware of `dofile`. To be honest, I'm having a bit of trouble finding documentation on them. I didn't see them mentioned anywhere in [NeoVim's Lua documentation](https://neovim.io/doc/user/lua.html) or in the [nvim-lua-guide](https://github.com/nanotee/nvim-lua-guide). Is there a specific reason `require` seems to be preferred over `dofile`? As far as luafile goes, are you referring to the `:luafile` command? If so, are you suggesting that I should call that from a Lua file?

In this particular case, it sounds like there's still an issue, because even having a file called `plugins.lua` in the runtime path causes the LunarVim code to break. Would you suggest they use `dofile` instead of `require` in their code?

@bfredl In this particular instance, I agree with you and I also opened an issue for this in LunarVim. However, my issue was more that I felt like there should be a way to load a file without worrying about collisions `runtimepath`. It sounds like that may be the case with `dofile`.

**Comment by gpanders** [comment]
> To be honest, I'm having a bit of trouble finding documentation on them. I didn't see them mentioned anywhere in [NeoVim's Lua documentation](https://neovim.io/doc/user/lua.html) or in the [nvim-lua-guide](https://github.com/nanotee/nvim-lua-guide). Is there a specific reason `require` seems to be preferred over `dofile`?

`dofile` is a Lua construct. `require` is preferred in the vast majority of cases because it 1) uses Lua's package loading mechanisms and 2) caches the result so that subsequent `require()`s are much faster. See [Chapter 8 of Programming in Lua](https://www.lua.org/pil/8.html) and the [relevant section in the Lua manual](https://www.lua.org/manual/5.1/manual.html#5.3). Generally speaking, you should always use `require()` unless you have a very good reason not to.

> It sounds like even with `dofile` there's still an issue, because even having a file called `plugins.lua` in my `lua` folder causes the LunarVim code to break. Would you suggest they use `dofile` instead of `require` in their code to avoid this issue? Or namespace their code like @bfredl suggested?

As long as LunarVim has a top-level (non-namespaced) `plugins.lua` file this will be a problem. The solution is not to use `dofile`, but to use a namespace, as bfredl said.

You can get around this on your end by namespacing your own modules. For example, move your own `plugins.lua` file to `lua/private/plugins.lua` and load it with `require("private.plugins")` (the directory can be called anything, of course. It doesn't need to be "private"). This is probably a good practice anyway so that your *own* Lua files won't collide with any plugins.

> However, my issue was more that I felt like there should be a way to load a file without worrying about collisions `runtimepath`. It sounds like that may be the case with `dofile`.

Collisions are avoided by plugins properly namespacing their modules. Not doing so is an anti-pattern and is not something Neovim is likely to support. Besides, the ability for a user to override what module gets loaded upon `require()` is a feature, not a bug.

**Comment by LandonSchropp** [comment]
Gotcha. Thanks for the clarifications!
