### ISSUE TITLE
vim.lsp.buf.definition doesn't work

### ISSUE THREAD

**Issue by AllenDang** [neovim/neovim#15588]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+1695-gdb695cc4c

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 11.15

### Terminal name/version

xterm-256color

### $TERM environment variable

xterm-256color

### Installation

homebrew

### How to reproduce the issue

open `nvim`, open *.go file with gopls setted.
move cursor to a method, run `:lua vim.lsp.buf.definition()`.

### Expected behavior

jump to the definition of method under cursor.

### Actual behavior

nothing happened

**Comment by justinmk** [comment]
`:help lsp-quickstart`

**Comment by AllenDang** [comment]
@justinmk why close this? I have all lsp configured well, auto-complete works. lsp client is attached to current buffer. only go-to definition doesn't work.

**Comment by clason** [comment]
Because if the server attaches correctly, then the builtin client is working correctly. So that leaves either

1. a configuration error on your part (e.g., you have mapped your binding to `textDocument/declaration` instead by mistake, or overwrite that mapping later in your config) or
2. a problem with gopls where it doesn't respond to a valid response (for some reason).

Either is off-topic here. In any case, without a minimal reproducing config (using the minimal `init.lua` from lspconfig and a minimal go file), we cannot do anything.
