### ISSUE TITLE
Proposal: Use `--clean` instead of `-u NORC` in vim-patch.sh

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#15629]
`-u NORC` still loads plugins, and there may be plugins that cause the script to hang or cause the behavior of the script to deviate from the expected behavior (not sure about this).

**Comment by justinmk** [comment]
I don't remember why I used NORC instead of NONE. But if `-u NONE` works that would be preferrable. `--clean` is also fine.

But also, there is not really a good reason that `-u NORC` loads "START" plugins. Vim "packages" should be considered as "initialization" ("RC"), hence "NORC" should preclude them.

Please send whatever change to vim-patch.sh works for you, don't need to keep this issue open.

**Comment by clason** [comment]
> But also, there is not really a good reason that -u NORC loads "START" plugins. Vim "packages" should be considered as "initialization" ("RC"), hence "NORC" should preclude them.

I think this is a larger discussion to be had (not here) that also depends on how and when we decide  `packpath` should be folded into `runtimepath` (see https://github.com/neovim/neovim/pull/15342).

More specifically, I agree that having `-u NORC`, `-u NONE`, `--noplugin`, and `--clean` that do overlapping (and partly the same!) things is confusing and unnecessary. We just need one "factory default" switch (which I propose using `--clean` for in https://github.com/neovim/neovim/issues/15605) (and possibly the current `-u NORC` for compatibility.

But note that currently `--clean` skips even builtin plugins (see above issue), so this may not work as intended. There's currently no way to skip only user plugins except by using an explicit minimal `init.vim` with
```vim
set runtimepath=$VIMRUNTIME
set packpath=$VIMRUNTIME/pack
```

**Comment by zeertzjq** [comment]
#16179 will be a solution to this.
