### ISSUE TITLE
`nvim_set_current_dir` does inform `:cd -`

### ISSUE THREAD

**Issue by ms-jpq** [neovim/neovim#15757]
### Neovim version (nvim -v)

NVIM v0.(5|6).0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

both MacOS 11.5 and Ubuntu 20.04

### Terminal name/version

Iterm2

### $TERM environment variable

xterm-256color

### Installation

homebrew / unstable repo

### How to reproduce the issue

`:lua vim.api.nvim_set_current_dir("/")`

### Expected behavior

`:cd -` should bring us back to previous work dir?

not sure if this is meant to be this way by design, please close this issue if this is.

### Actual behavior

Errors out with

`E186: No previous directory`

**Comment by justinmk** [comment]
hmm. It's an old API. And the original vision of the API was for low-level control, which shouldn't affect user editor state. 

Since then it became clear that it is often needed to have the full editor side-effects. So a "opt out" model is needed (or more likely, "opt in", because it seems more common that clients _want_ the side effects).

In the case of `nvim_set_current_dir` ... we could probably just change the behavior to the expectation here.
