### ISSUE TITLE
Can not set commentstring for c files using autocommand.

### ISSUE THREAD

**Issue by doubleloop** [neovim/neovim#15845]
### Neovim version (nvim -v)

0.6.0 commit 270cc1d70fa8e24299b6df13712b49216fe324ec

### Vim (not Nvim) behaves the same?

no, vim 8.2.3458

### Operating system/version

Debian bullseye

### Terminal name/version

alacritty 0.10.0-dev

### $TERM environment variable

screen-256color

### Installation

build from repo

### How to reproduce the issue

```sh
$ cat test.vim
filetype on
au FileType c setl cms=//%s
$ nvim -u test.vim test.c
```

### Expected behavior

`cms` should be set to `//%s`

### Actual behavior

`cms` is set to `/*%s*/`

### Notes

Bisected, 4819737853fc3676b976be93bd0332a3e44ab837 introduced the issue cc @janlazo

**Comment by gpanders** [comment]
FileType autocommands defined in init.vim are executed before built-in ftplugin files, so they get overridden. To override settings in default ftplugin files, use `~/.config/nvim/after/ftplugin/c.vim` (or whatever the appropriate filetype is). Tthis is the correct way to do it anyway since autocommands have no way to enforce ordering.
