### ISSUE TITLE
`has('path_extra')` returns true but `:help path_extra` shows nothing

### ISSUE THREAD

**Issue by Rubonnek** [neovim/neovim#15902]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+398-gc4d581dea

### Vim (not Nvim) behaves the same?

no, 8.2

### Operating system/version

Arch Linux

### Terminal name/version

XTerm(369)

### $TERM environment variable

xterm

### Installation

Arch User Repository - neovim-git package

### How to reproduce the issue

nvim -u NONE
:help path_extra

### Expected behavior

Show a description of the path_extra feature.

### Actual behavior

```
E149: Sorry, no help for path_extra
```

**Comment by clason** [comment]
In Vim, this tag leads to `various.txt`, which contains documentation of the output of `:version`, including the features Vim is compiled with. Since Neovim always compiles with all features, `:version` does not contain such a list and hence its documentation does not need to explain individual features.

**Comment by Rubonnek** [comment]
Does that mean that users are expected to browse Vim's documentation for features that do not seem referenced in NeoVim but that `has()` return true in both?

**Comment by clason** [comment]
Users are not expected to care about what feature _flags_ mean -- the features themselves are of course documented in Neovim's `:help` as well (just without the "enabled if built with `path_extra`).

**Comment by chrisbra** [comment]
Note: you want to do `:h +path_extra`
