### ISSUE TITLE
A better/more intuitive way of disabling diagnostics in insert mode

### ISSUE THREAD

**Issue by YorickPeterse** [neovim/neovim#16076]
### Feature already in Vim?

No, this is NeoVim specific

### Feature description

If a user doesn't want diagnostics to show up when typing, they can use the option `update_in_insert`.

This option has a flaw: it only applies to NeoVim itself, not other consumers of diagnostics data.

As an example, imagine you have `update_in_insert` set to `false`, and your statusline shows the number of diagnostics for the current buffer. When using a language server that produces diagnostics while typing (i.e. in insert mode), two things happen:

1. NeoVim won't show any signs or virtual text
2. Your statusline _will_ show the number of diagnostics as it changes while you are typing

Another example is using the location or quickfix list for displaying diagnostics, and refreshing them every time new diagnostics are produced. Similar to the above, the lists will update as you type, but signs/virtual text changes are deferred until exiting insert mode.

Finding this inconsistency annoying, and not being a fan of diagnostics as I type (99% of the time the diagnostics are not yet useful, as I haven't finished typing), I had to resort to the following hack:

I override the publishDiagnostics handler [like so](https://gitlab.com/yorickpeterse/dotfiles/-/blob/5575b95250951e4ff1f96c5be1e2e834600f3ce9/dotfiles/.config/nvim/lua/dotfiles/lsp.lua#L64-70). This override buffers the diagnostics in a cache when I'm in insert mode, otherwise it forwards them to NeoVim. The caching logic is implemented [here](https://gitlab.com/yorickpeterse/dotfiles/-/blob/5575b95250951e4ff1f96c5be1e2e834600f3ce9/dotfiles/.config/nvim/lua/dotfiles/diagnostics.lua#L17). When exiting insert mode, the diagnostics are flushed using [this hook](https://gitlab.com/yorickpeterse/dotfiles/-/blob/5575b95250951e4ff1f96c5be1e2e834600f3ce9/dotfiles/.config/nvim/lua/dotfiles/hooks.lua#L96), which calls [this function](https://gitlab.com/yorickpeterse/dotfiles/-/blob/5575b95250951e4ff1f96c5be1e2e834600f3ce9/dotfiles/.config/nvim/lua/dotfiles/diagnostics.lua#L26).

The result of this setup is that diagnostics are _not_ pushed to NeoVim until I leave insert mode. The beauty (if you can call it that) of this setup is that I don't have to check for the mode every time I want to display the diagnostics somewhere. I did do this previously, but it gets a bit messy and requires quite a bit of repetition.

The obvious downside is that if something depends on diagnostics coming in as you type, regardless of whether they are displayed or not, this may not work well; though I can't think of any such cases.

Ultimately the point is this: I think NeoVim needs something better; something that doesn't require users to repeat the pattern `if api.nvim_get_mode() == 'i' then ... end` whenever they want to show diagnostics data _unless_ they are in insert mode.

**Comment by gpanders** [comment]
If `vim.diagnostic.disable()` had a way to disable diagnostics _without_ removing existing diagnostics, would this work?

```vim
autocmd InsertEnter * lua vim.diagnostic.disable()
autocmd InsertLeave * lua vim.diagnostic.enable()
```

**Comment by YorickPeterse** [comment]
@gpanders 

> statusline display itself: cache the number of diagnostics in the buffer and only update that value when not in insert mode.

I did more or less that [here](https://gitlab.com/yorickpeterse/dotfiles/-/commit/5fa97291e94e26c1b34033e6eba61d611fc5b5a3#77396b44bbb67bdc6c808cc1e2cc1c035cfdea1c_26_29) and it gets hairy. Basically I had to cache the counts, then refresh them when exiting insert mode. Worse, you need to do something similar for everything that presents diagnostics but is meant to honor your "don't bother me in insert mode" setting. This applies to location lists, quickfix lists, plugins (e.g. Trouble), etc.

> Similarly, presuming you're using the DiagnosticsChanged autocommand to update the quickfix/location list, you can still just check that mode() !=# 'i'.

My personal setup is a bit more complex, as it also ensures location lists for new windows to the same buffer are populated. Either way, the point is as I mentioned above: users have to implement their own ad-hoc "don't bother me in insert mode" checks in a variety of places.

**Comment by YorickPeterse** [comment]
> That's a lot of additional complexity, and for what benefit?

The complexity isn't that big. What you need is a table that stores diagnostics per buffer/client ([like this](https://gitlab.com/yorickpeterse/dotfiles/-/blob/5575b95250951e4ff1f96c5be1e2e834600f3ce9/dotfiles/.config/nvim/lua/dotfiles/util.lua#L74)), a check in `on_publish_diagnostics` to decide where the diagnostics go, and an `InsertLeave` hook to flush data from this store to the main one.

Now I can totally see the point of doing this in a plugin. The reason for discussing it here is because I can see other users being annoyed/confused by NeoVim's behaviour when `update_in_insert` is set to `false` :smiley:

**Comment by gpanders** [comment]
> The complexity isn't that big

That's a lot of new code paths and edge cases and in general makes the whole concept harder to grok. It's no longer just "stuff a bunch of diagnostics into a table and then pull them back out", now there is state involved.

I'm not wholly opposed to the idea. If you want to submit a PR with a working implementation we can discuss it further there with the benefit of having concrete code to talk about rather than just abstract concepts. But this would need to be something that is 1) not easily implementable by a plugin and 2) would benefit a sizable portion of users.

**Comment by mfussenegger** [comment]
> . However, this is essentially similar to setting debounce_text_changes to some high value (e.g. 5000)

debounced changes get flushed out once another LSP request is triggered, so this is a bit different.

> From my understanding things like code actions, hovering, etc are all normal mode operations, so they would continue to work.

That's true. 
I'm not saying it is a deal-breaker. But it's still something worth to consider when evaluating if a feature should be added or a behavior should be changed. If LSP actions use diagnostics today, there is a chance future additions may do as well, and who knows if those will still be things you usually trigger in normal mode?

**Comment by YorickPeterse** [comment]
To add to the above: in case of rust-analyzer, and probably many other servers, the diagnostics come in _after_ `BufWritePost` is triggered for the buffer.

**Comment by YorickPeterse** [comment]
I ended up implementing https://gitlab.com/yorickpeterse/dotfiles/-/blob/ad79e1b69d09384a0ca8739ae16e0d8991c77b0d/dotfiles/.config/nvim/lua/dotfiles/defer_diagnostics.lua. This basically defers diagnostics such that:

- In insert mode new diagnostics are not displayed, but existing ones are left as-is
- In other modes we display diagnostics after a short period of time (1 second by default)
- When exiting insert mode, any diagnostics produced while we were in insert mode are scheduled for display (using the same timeout)

I ended up taking this path because deferring diagnostics until a file write required too much messy code.

Since the topic is quite subjective (e.g. some might actually want diagnostics in insert mode), I'll close this issue. Should at some point more people want this, I think we can revisit it then :smiley:

**Comment by mjlbach** [comment]
I think it would be fine/welcome to make a tracking issue for more granular diagnostic refreshes. I previously had a PR that attempted this.

The main usecases I've historically seen people ask for are:
* refresh diagnostics on save
* refresh diagnostics on a constant timer
* refresh diagnostics when leaving insert mode
* consistently refresh diagnostics 

The latter two are covered by `update_in_insert`, by the mechanism is a bit hacky. We could instead change it so that diagnostics are driven by a custom autocommand that can be triggered by sources (if a user desires, such as in on_publish_diagnostics), or by autocommands.

cc @gpanders

**Comment by NicholasAsimov** [comment]
@mjlbach apologies for the ping, I'm trying to migrate to using diagnostics instead of classic cmd based approach (e.g. neomake) and the only thing I'm missing to make this nice to use is "refreshing diagnostics on save". Is there a tracking issue/ongoing work for this already or it's on hold for now?

**Comment by mjlbach** [comment]
There's not a "defer diagnostics to save" feature, it does not make sense in the case of LSP support as diagnostics are push, not pull (we can't request or control when servers send diagnostics. In the neomake case, it would be the responsibility of the diagnostic provider (say, `nvim-lint`) to only update/populate the diagnostic namespace matching the provider on save. With nvim-lint, it's pretty trivial to get diagnostics on save but using the appropriate autocommand trigger, for LSP, we haven't added the feature because it would be the "illusion" of deferring diagnostics.
