### ISSUE TITLE
Treesitter highlighting sometimes gets stuck

### ISSUE THREAD

**Issue by Gelio** [neovim/neovim#16152]
### Neovim version (nvim -v)

v0.6.0-dev+493-g035d82e0d

### Vim (not Nvim) behaves the same?

it does not have Treesitter :D

### Operating system/version

Ubuntu 20.04 LTS

### Terminal name/version

kitty 0.23.1

### $TERM environment variable

xterm-kitty

### Installation

Unpack tar archive and use `stow` to install it in `/usr` (https://github.com/Gelio/ubuntu-dotfiles/blob/8a39aee019f0cb2f65083053b8962ee6b8b99a63/install/neovim/install.sh#L44)

### How to reproduce the issue

I have noticed that after editing a file for some time (definitely over 20 minutes, with at least ~100 lines changed over that time), Treesitter syntax highlighting turns off for parts of the file I just modify. `:e` helps to get that part to be highlighted again, but the highlighting stops again after a few more edits.

After Treesitter highlighting breaks once, it will keep breaking over and over as I edit the file and restart it with `:e`. Restarting neovim is the only way I found to "fix" the problem (for the next ~20 minutes or so).

I cannot pinpoint it to a specific list of steps to reproduce. I don't know how to debug it further. Any actions/commands I can do to try to debug it would be useful.

I have only been editing TypeScript files lately, so I can't say if the problem also occurs for other filetypes.

My nvim-treesitter config:
https://github.com/Gelio/ubuntu-dotfiles/blob/8a39aee019f0cb2f65083053b8962ee6b8b99a63/install/neovim/stowed/.config/nvim/lua/plugins.lua#L537-L598

I also have `indent-blankline.nvim` set up to use Treesitter, but I don't think that matters:
https://github.com/Gelio/ubuntu-dotfiles/blob/8a39aee019f0cb2f65083053b8962ee6b8b99a63/install/neovim/stowed/.config/nvim/lua/plugins.lua#L234-L271

### Expected behavior

Here is a screenshot from the time that the problem occurs:
![image](https://user-images.githubusercontent.com/889383/138856427-a24e266b-1239-4912-9099-e400cbb6907e.png)
I have highlighted the lines I have just modified. They's foreground color is white and remains as such until I either restart neovim, or do `:e`.

After doing `:e`, they are highlighted again:
![image](https://user-images.githubusercontent.com/889383/138856606-4c39f739-19a8-473a-858e-0010a20b18da.png)

However, after a few more edits, other lines are not highlighted (in that same file):
![image](https://user-images.githubusercontent.com/889383/138856760-41707c70-f674-411b-ae35-07912a315670.png)

and I have to do `:e` again do get them to highlight:
![image](https://user-images.githubusercontent.com/889383/138856959-2104e11b-16d2-4407-9390-48c082e8d133.png)

### Actual behavior

The code is consistently highlighted no matter how long I edit the files for.

**Comment by yioneko** [comment]
Perhaps i find the reason. The problem lies in the nvim core. 

https://github.com/neovim/neovim/blob/3ba800f1538e083f8172655c6bab096cd604a0b5/src/nvim/globals.h#L838-L839
The maximum of the tick is **only 65535** and when the saved tick of one buffer reached the maximum, the redraw function of the buf will never be called.  @Gelio That is why there is a 20mins delay of disappearance of highlight.

Note perhaps the issue not only affect treesitter highlight because it involves screen update.

### Current workaround (treesitter only)
Add this line to your vimrc:
```viml
au FileType * lua << EOF | local parser = vim.treesitter.get_parser(0) | if parser ~= nil then parser:register_cbs({ on_bytes = function() parser:parse() end }) end | EOF
```
btw, i think this is more reasonable than calling `parser:parse()` in `nvim_set_decoration_provider`.

**Comment by Gelio** [comment]
@yioneko Thanks for taking the time to debug and suggest a workaround. I stopped working on that one single file for the time being, so I doubt I will hit the problem again, though :/

**Comment by yioneko** [comment]
@Gelio Yes, you won't encounter this problem if you don't work on one buffer for a very long time (till the tick reaches the maximum). But I work on a single file from time to time, so I'm frustrated with the problem very often 😂. Thank you for raising the issue without which I can't recognize the issue is my specific problem :)

**Comment by 52617365** [comment]
Still having this problem.
