### ISSUE TITLE
VimL vs. Vim script terminology problems

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#16150]
In Neovim's documentation, error messages, C source code comments and Lua test comments, `VimL` appears many times. However, the correct terminology is `Vim script`, not `VimL`. (<https://github.com/vim/vim/commit/b544f3c81f1e6a50322855681ac266ffaa8e313c>, I can also recall Bram mentioned something related in mailing lists, but I cannot find where.) Should Neovim replace all mentions of `VimL` with `Vim script` as well? (This may make several error messages longer.)

**Comment by zeertzjq** [comment]
#24109 changes "VimL" to "Vimscript" in docs, though "VimL" still appears in error messages.

**Comment by justinmk** [comment]
I will followup #24109 with a final PR that replaces "VimL" with "Vimscript" everywhere.

Conflicts with vim's use of "Vim script" are very rare so that isn't a problem. Spelling it "Vimscript" avoids stupid things like `vim_script`, `vimScript`, `vim-script`, also avoids annoying false positives when grepping for `Vim` or `script`.
