### ISSUE TITLE
`termopen` leaks memory if `on_exit` runs `bdelete` (fzf)

### ISSUE THREAD

**Issue by tomtomjhj** [neovim/neovim#16257]
### Neovim version (nvim -v)

v0.6.0-dev+563-gb74916cfd

### Vim (not Nvim) behaves the same?

N/A? In Vim 8.2.3582, memory usage grows much slowly when spamming fzf.

### Operating system/version

Ubuntu 21.04

### Terminal name/version

GNOME Terminal 3.38.1 using VTE 0.62.3 +BIDI +GNUTLS +ICU +SYSTEMD

### $TERM environment variable

tmux-256color

### Installation

built from the repository

### How to reproduce the issue

Minimal reproducer extracted from this part of fzf vim integration:
https://github.com/junegunn/fzf/blob/e4c3ecc57e99f4037199f11b384a7f8758d1a0ff/plugin/fzf.vim#L845-L856
```vim
" leak.vim
" this leaks memory
nnoremap x :call termopen('echo 1', opts)<CR>
let opts = {}
function! opts.on_exit(...)
  bdelete
endfunction

" this does not leak memory
nnoremap o :call termopen('echo 1')<CR>i<CR>
```
Run `nvim --clean -u leak.vim` and hold down `x` key. Check the memory usage with tools like htop or run memory profilers like heaptrack. Roughly 200kb is leaked for each invocation.

Screenshot of heaptrack profile result:
![image](https://user-images.githubusercontent.com/19489738/140640422-d4976363-583d-4e7d-8838-cf5b9facf956.png)

### Expected behavior

Should not leak memory. Specifically, `terminal_destroy` should be called. 

### Actual behavior

`terminal_destroy` is not called if `on_exit` runs `bdelete`, resulting in memory leak.

**Comment by zeertzjq** [comment]
I think this is a problem with `:bdelete` unrelated to `on_exit`.

**Comment by zeertzjq** [comment]
Oh, maybe changing `terminal_close` is more reasonable.

**Comment by zeertzjq** [comment]
This is not as easy to fix as I think. I'm leaving a note here:
`close_buffer()` calls `terminal_close()` to close a terminal. However, if `channel_process_exit_cb()` has called `terminal_close()` on that terminal before, it has set `term->closed` to `true`, but has not freed the terminal because Nvim waits for a key to be pressed to free the terminal. When `term->closed` is `true`, further calls to `close_buffer()` are no-op, so `:bdelete` fails to free a terminal whose process has already exited. I tried to fix that, but cannot find an approach that is always safe.
