### ISSUE TITLE
GUI reference implementation

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1639]

**Comment by oakes** [comment]
I am now at the point where I can successfully send a `attach_ui` message over msgpack-rpc. The response I get is an array with four items: `1 1 Nil Nil`. I assume this means it was successfully received. However, when I continue using neovim, switching buffers and inserting text, I don't receive any subsequent messages. I was expecting to receive messages informing me when events like "switched buffer" or "entered insert mode" occur. Sorry to add to this long thread, but if anyone can point out what I am misunderstanding, I would appreciate it.

**Comment by justinmk** [comment]
@oakes The next step is to subscribe to the events you want. In `src/nvim/api/vim.c`:

    vim_subscribe(uint64_t channel_id, String event)

[python client test](https://github.com/neovim/python-client/blob/5e5856c9fe1861446e6c0710484b008cd377c101/test/test_events.py) shows that these events can be arbitrary (with the assumption that you or some other component will fire them later via `channel_send_event`[1]). If you want to know which UI events are currently fired by nvim, check out `src/nvim/msgpack_rpc/remote_ui.c`. By inspecting each `push_call()` I see that these events are fired[2]:

```
 push_call(ui, "resize", args);
 push_call(ui, "clear", args);
 push_call(ui, "eol_clear", args);
 push_call(ui, "cursor_goto", args);
 push_call(ui, "cursor_on", args);
 push_call(ui, "cursor_off", args);
 push_call(ui, "mouse_on", args);
 push_call(ui, "mouse_off", args);
 push_call(ui, "insert_mode", args);
 push_call(ui, "normal_mode", args);
 push_call(ui, "set_scroll_region", args);
 push_call(ui, "scroll", args);
 push_call(ui, "highlight_set", args);
 push_call(ui, "put", args);
 push_call(ui, "bell", args);
 push_call(ui, "visual_bell", args);
```

>  I was expecting to receive messages informing me when events like "switched buffer" or "entered insert mode"

For other types of events I believe it is currently required to send an `autocmd <foo>` command. [python client example](https://github.com/neovim/python-client/blob/5e5856c9fe1861446e6c0710484b008cd377c101/test/test_events.py#L7-L17):

    vim.command('call rpcnotify(%d, "test-event", 1, 2, 3)' % vim.channel_id)

I think it might be good to make a proper API call for Vim event subscription, but under the hood I think we will continue to use the Vim event/autocmd system (and improve them as needed).

[1] @tarruda `channel_send_event` doesn't seem to be exposed to clients. Am I missing something? 

[2] We should think about auto-generating documentation for this.

**Comment by justinmk** [comment]
BTW @tarruda what is the reason for the event pairs such as cursor_on/off, insert_mode/normal_mode, etc.? It be more flexible to send a "changed" event with the old and new value? For example:

- "mode_changed"
    - if entering insert mode, send values like old=normal, new=insert
- "cursor_changed"
    - if changed to "on", send old=off, new=on

Is the current design for performance?

**Comment by oakes** [comment]
@justinmk thanks very much. I tried using `vim_command` with autocmd syntax and it worked great for the events I wanted to get notifications for.

**Comment by tarruda** [comment]
> I am now at the point where I can successfully send an attach_ui message over msgpack-rpc. The response I get is an array with four items: 1 1 Nil Nil. I assume this means it was successfully received. However, when I continue using neovim, switching buffers and inserting text, I don't receive any subsequent messages. I was expecting to receive messages informing me when events like "switched buffer" or "entered insert mode" occur. Sorry to add to this long thread, but if anyone can point out what I am misunderstanding, I would appreciate it.

`attach_ui` is deprecated, it was renamed to `ui_attach` in #1657, so I recommend you to develop against that PR. Simply calling `ui_attach` should be enough to start receiving 'redraw' notifications.

> @oakes The next step is to subscribe to the events you want. In src/nvim/api/vim.c:
@tarruda channel_send_event doesn't seem to be exposed to clients. Would it be a good idea to create a new API method like vim_publish(uint64_t chan_id, char *name, Array args)?

I will eventually remove vim_subcribe/unsubscribe from the API and move event subscription/broadcasting to vimscript, so yes.

> BTW @tarruda what is the reason for the event pairs such as cursor_on/off, insert_mode/normal_mode, etc.? It be more flexible to send a "changed" event with the old and new value? For example:

>"mode_changed"
if entering insert mode, send values like old=normal, new=insert
"cursor_changed"
if changed to "on", send old=off, new=on
Is the current design for performance?

The current design is fully based on the way vim handles redrawing(based on termcap sequences), we need it to simplify transition, write tests, etc.  We should definitely improve the UI protocol once we have enough tests to ensure these changes wont cause bugs.

I was inactive lately due to holidays, but have been working on a python gtk3 GUI prototype on my spare time and it is almost ready. There's a good chance I will push it to github today.

I dropped the tk GUI because I was unable to get good performance with that toolkit, the gtk3 GUI is much faster even in python. I used python because I work faster with it, so it was a better choice for prototyping, but the gtk API is the same so it will be easy to port to C.

**Comment by tarruda** [comment]
I have pushed the gtk GUI, those interested in testing read [this comment](https://github.com/neovim/neovim/pull/1657#issuecomment-68533866)

**Comment by blueyed** [comment]
JFI: the ui-prototypes branch / PR has been merged.

I've tried `pynvim` and noticed that it does not work with Python 3 (via pyenv, with patches for nvim).
It looks similar to the colorscheme issue with Python 2.

**Comment by equalsraf** [comment]
FWIW I'm looking at a way to set the guifont with a bit of VimL and vim_subscribe notifications right now it looks like this equalsraf/neovim-qt#16
