### ISSUE TITLE
Upgrade Doxygen in CI to 1.9.0 or later

### ISSUE THREAD

**Issue by gpanders** [neovim/neovim#16498]
### Feature description

See e.g. https://github.com/neovim/neovim/pull/16483/files#diff-438cabcc877e34fbb948241c7e7e611579449d08085f5e38817a11450214a35bL1610-L1616

The API docgen workflow step keeps flip flopping on the `vim.validate` docs. This is a bug that was fixed in Doxygen 1.9.0 (I can confirm that using the last 1.8.X version shows the bug, but I cannot reproduce in 1.9.2).

**Comment by KillTheMule** [comment]
Just a small headsup: When I started using doxygen for lua documentation way back , there was some sort of problem with versions >= 1.8.2. I'm very sorry to say that I can't really remember what it was, and I might just have brushed over it without too much thought (since the default on CI did just work). Sorry to be so unhelpful, but you might just want to double check if things keep working properly after the update.
