### ISSUE TITLE
Request: reliable way to determine if a buffer is a :checkhealth output buffer

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#16639]
### Feature already in Vim?

No

### Feature description

There's currently no way to reliably determine if you are viewing a checkhealth buffer. I don't know if a full-on filetype is required, or if a flag set in the runtime file might do it, or if there is a convention that is followed in checkhealth buffers. I created a related thread on reddit here with my current workaround, but it's brittle: https://www.reddit.com/r/neovim/comments/r85x4u/is_there_a_reliable_way_to_determine_if_a_buffer/?utm_source=share&utm_medium=web2x&context=3

**Comment by matveyt** [comment]
Following the linked thread on reddit, it probably suffices just to set up "health" buffer with `setl buftype=nofile` (instead of `nomodified` which is always true for "nofile" buffers anyway) that makes perfect sense, IMO. At least I, personally, map "q" to "close" for all `!empty(&buftype)` buffers at once, not only "help" or "quickfix" specifically. Right now, it doesn't work for "checkhealth" though which is a bit annoying.

**Comment by teto** [comment]
makes sense. Patch welcome I would say for a filetype "checkhealth".

**Comment by stsewd** [comment]
There is also some discussion about this at https://github.com/neovim/neovim/issues/8148.

**Comment by matveyt** [comment]
@stsewd Yes, it's a highly subjective point if we need a whole new filetype or not. Personally, I'm agree that if we had some sophisticated plugins for "checkhealth" then it would be a good idea. But as of now, just having `buftype=nofile` should be enough for personal configs.

**Comment by muniter** [comment]
https://github.com/neovim/neovim/pull/16660
