### ISSUE TITLE
Bug: Prevent neovim from replacing symlinked .nviminfo with a real file.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#1674]
Steps to reproduce:

 1. `ln -s .viminfo .nviminfo`
 2. launch `nvim`
 3. Quit NeoVim with `:q`
 3. `ls -l .nviminfo`
 4. Notice .nviminfo is no longer a symbolic link.

**Comment by jrobeson** [comment]
so does the switch to shada files mitigate this problem in any way, or does it still exist?

**Comment by justinmk** [comment]
So far no use-case has been mentioned other than syncing history between vim and nvim, which is of course impossible now that shada was merged. Shada still writes to a temp file while doing a merge, so I doubt this issue would be resolved. Since Bram mentioned it is a security issue I feel we should close this issue until proven otherwise.
