### ISSUE TITLE
Default values for 'opts' in nvim_set_keymap ?

### ISSUE THREAD

**Issue by RaZ0rr-Two** [neovim/neovim#16919]
### Feature description

The docs for `:h nvim_set_keymap()` doesn't specify what the default value for opts is. Shouldn't it specify that all values are `false` by default or something ?

This might be pointless now that #16591 is being worked on.

**Comment by clason** [comment]
The documentation links to `:map-arguments`, which discusses what happens when each argument is added -- this strongly implies that unless you set `foo=true`, the command behaves like the argument is _not_ added. So it's "default false" (technically, "default `nil`", but `nil` is falsey in Lua).

Nevertheless, being explicit in documentation never hurts in my opinion.
