### ISSUE TITLE
[Discussion] Make learning to use vim easier for newcomers

### ISSUE THREAD

**Issue by fmoralesc** [neovim/neovim#1692]
![](http://mrozekma.com/editor-learning-curve.png)

One of neovim's goals is to provide a better experience to users by default, and that also means to improve the experience for those who are just beginning to use vim. Let's discuss what improvements can be made in this sense.

Some references:

* Yehuda Katz - [Everyone who tried to convince me to use Vim was Wrong](http://yehudakatz.com/2010/07/29/everyone-who-tried-to-convince-me-to-use-vim-was-wrong/)
* [Your problem with vim is that you don't grok vim](http://stackoverflow.com/questions/1218390/what-is-your-most-productive-shortcut-with-vim/1220118#1220118)
* [Learn Vim Progressively](http://yannesposito.com/Scratch/en/blog/Learn-Vim-Progressively/)
* [Learning Vim in 2014](http://benmccormick.org/learning-vim-in-2014/)

**Comment by fmoralesc** [comment]
I've worked a bit more today on vim-tutor-mode, and managed to have some interactivity implemented (it marks errors in lines to edit, and shows when the lines have changed correctly). There's a small demo [here](http://gfycat.com/ImperfectFantasticAtlanticridleyturtle). I converted the whole vim tutor into the new format and it seems to handle that fine. I'll be working on improving the syntax highlighting of normal commands now. Some feedback and ideas would be appreciated, as would improvements to the text or new tutorials.

**Comment by dahu** [comment]
I wrote https://github.com/dahu/vimgym for this purpose.

**Comment by fmoralesc** [comment]
@dahu Both vimgym and LearnVim are really good. I would like to convert LearnVim (or at least, parts of it) to vim-tutor-mode's format; that would be OK as long as attribution is stated, right?

**Comment by dahu** [comment]
Yep. No problem.

**Comment by fmoralesc** [comment]
As an update: I've transformed parts of @dahu's Learnvim to vim-tutor-mode, and created a tutorial on how to write vim-tutor-mode tutorials ;) Some feedback would be *really* appreciated; now that the infrastructure is more or less done (ja!), I'll try to come up with a writing plan. A series of topic-specific tutorials would be good to have.

**Comment by fwalch** [comment]
What about adding some startup messages for (n)vim beginners? This could for example replace the intro screen if no `nvimrc` has been found (as this could indicate that someone is new to nvim) or be added as additional text on the intro screen.

Something along the lines of:

```
Welcome to nvim!

First time using a vi-like editor? Type `:Vimtutor<Enter>` or
exit nvim by typing `:q<Enter>` and start `nvimtutor`.

If you already know your way around Vim, see `:help nvim-intro`
for an introduction to Neovim's features and differences from Vim.

There you will find prerequisites for Neovim's clipboard support and
instructions on how to set up Neovim for Vim plugins using Python,
for example.

If you're stuck and don't find what you are looking for in the help system,
see Neovim's website at neovim.org for support resources.
```

`nvim-intro` would then need to mention things like: vimrc can be reused as nvimrc, you need the python client for the builtin python commands (see `:help nvim-python`), etc (I guess this is planned anyway).

There have been multiple issues on Github about why some Vim plugin that uses Python doesn't work etc, so I think we need to point out that additional setup is required here as obviously as possible.

With "support resources" I mean things like the Github issue tracker, the mailing list, ... The wording can surely be improved, but I think having a few friendly sentences on startup could already make a difference for beginners.

**Comment by fmoralesc** [comment]
@fwalch I like this idea.

**Comment by techtonik** [comment]
Provide a fuzzy/sane help system, which can answer `:help open file` or `:how to open file` questions. Maybe even looking up online DB if required and updating it.

**Comment by fmoralesc** [comment]
@techtonik not a bad idea, but I think looking things up online would be needlessly complicated. For a start, we could try allow help tags to include spaces and add some common ones in places where it is not clear what is the required command.

**Comment by Pyrohh** [comment]
Yes, I must agree that an online help system would be too much. Having a good help system, like having good man pages, should be preferred to any situation requiring a browser (or any network connection IMO).

**Comment by Pyrohh** [comment]
It's also worth mentioning that dashes don't seem to be taken into account for `K` when `keywordprg=:help`. For example, go to `starting.txt`, and to the first instance of `cmdline-arguments`. Where `K` brings you depends on whether your cursor is in front of or behind the dash.

I'm guessing this could be "fixed" by setting option-backslash.

**Comment by techtonik** [comment]
I never could read man pages, maybe because I used to have help navigation based on <kbd>F1</kbd> and <kbd>TAB</kbd> like http://www.farmanager.com/img/screen/f1.png and man doesn't provide any means to get any help about its navigation. Vim could also use <kbd>TAB</kbd> to jump from |bars| to |bars|.

**Comment by Pyrohh** [comment]
@technotik I think a good man page is important, but it shouldn't be so long as to necessitate section movement hotkeys (although that's not to say such hotkeys wouldn't be useful). I love concise man pages, as opposed to monstrosities like `zshall`, which is why I'm currently porting the nvim man page to vim.

Regarding jumping from |bars| to |bars| in vim, it can already do that. Use `keywordprg=:help` as part of an ftplugin for when `ft=help` and the `K` key. I've had this for a while and think it might be a good idea to integrate it into nvim.

**Comment by techtonik** [comment]
I am not sure I am able to understand this `keywordprg=:help` stuff just yet. =)

**Comment by Pyrohh** [comment]
Oh it's very simple; `:h K` has a straightforward explanation.

**Comment by r0nk** [comment]
@fwalch I really really like this Idea. A intro screen will go a long way for beginners. Perhaps another feature would be having some sort of system that tells the user what the commands that their pressing do. Like, if I pressed j the status bar would come up with "'j', move down a line."

Also, If a beginner is panicking (as everyone does the first time they open anything vi-like), there probably going to mash the Esc key. There's no reason to mash the escape key if you know what your doing, so maybe there should be some output when that happens, like with Ctrl-c and its "Type :quit<Enter> to quit".

**Comment by TotalKrill** [comment]
Please, i am using vim, the best way to help beginners in my opinion would be to have good default settings, and then have a lot of common settings that are commented with what they do. It is so annoying trying to google every little tweak that you want and then skimp through a lot of .vimrc files. I have to do this to often since i do not have my precious standard vimrc with me everywhere. 

Also, have a cheatsheet shortkey, much like unity does it with their shotcut commands. This should ofcourse be optional.

**Comment by Pyrohh** [comment]
> Please, i am using vim, the best way to help beginners in my opinion would be to have good default settings, and then have a lot of common settings that are commented with what they do. It is so annoying trying to google every little tweak that you want and then skimp through a lot of .vimrc files. I have to do this to often since i do not have my precious standard vimrc with me everywhere.

See `:h vimrc_example`, although it could probably be expanded and moved to `/usr/share/doc`.

> Also, have a cheatsheet shortkey, much like unity does it with their shotcut commands. This should of course be optional.

The `F1` key and `:h` show somewhat of a cheat sheet, but it's primarily concerned with navigating the built-in documentation. A cheat sheet might be better, perhaps it could even be bound to `F1` by default.

**Comment by dahu** [comment]
You should almost never use Google to search for internal Vim stuff. Google
is better suited for finding plugins. Use Vim's :help for internal stuff.
Look at `:help help-context` to learn what prefixes to use for different
modes and options. Speaking of options, your search for what to tweak is
also covered by a Vim builtin. Try the :options command.

The Vimple plugin provides a :MyMaps command that shows you all of _your
current_ maps and tries to group related commands together.

**Comment by Pyrohh** [comment]
> Try the :options command.

Oh wow, this is fantastic. Thanks.

**Comment by TotalKrill** [comment]
Yes, well beginners tend to start googling when they are lost. Most well used editors have easy to find keybindings, nano for example is often recommended. Mostly because you can use it right away. Vim has a steep learning curve and default settings that are horrible for almost any user. 

Never underestimate the power of defaults. Imagine if the most used commands in vim was visible always somewhere by default, (nano style) or had a cheat sheet toggleable by really easy means. 

I know hardcore users of vim will disagree, but defaults should probably be a few to many newbie friendly things, things that later can be turned off. Most power users have their own vimrc anyways. Reading manuals and such is helpful, but not newbie friendly.

**Comment by kopischke** [comment]
> I know hardcore users of vim will disagree, but defaults should probably be a few to many newbie friendly things, things that later can be turned off. Most power users have their own vimrc anyways. Reading manuals and such is helpful, but not newbie friendly.

An emphatic :+1: from a hardcore user.

**Comment by noahfrederick** [comment]
@TotalKrill

> I know hardcore users of vim will disagree, but defaults should probably be a few to many newbie friendly things, things that later can be turned off.

While I agree that the defaults are important and can be improved, introducing things that most people will want to turn off later sounds like the opposite of good defaults.

I'm not convinced the difficulty of learning Vim has much to do with the defaults. For example, having syntax turned off by default is a little silly, but didn't inhibit me from learning or using the editor at all. It has much more to do with the following:

- Modal editing is weird—and one of Vim's big strengths, of course.
- Many settings, commands, and features have terrible names (`'list'`?! `'directory'`?!), but there's nothing much to be done about that at this point. Also, Vim uses potentially unfamiliar terminology such as "buffer", "register", "yank".
- There is just a huge volume of stuff to learn because Vim has so many features.

Fortunately, the existing documentation is great. I can see wanting a better way to find a help topic when you don't know exactly what you're looking for, although `:helpgrep` can serve that role.

**Comment by TotalKrill** [comment]
@noahfrederick 

I disagree, having features that can be turned of actually adds value since it shows the option from the start. This in conjunction with a populated vimrc file that contains a lot of commented settings that can easily be uncommented/commented would be a better step than an entirely empty vimrc. 

I am not talking about custom keybindings enabled by default. But maybe a commented custom keybinding, with explanations in the vimrc. 

Usually when people learn something new, they look at what others have done. Since vim comes pretty empty in that regard. Maybe some suggestions on where to start right away would be nice. 

To clear it up, i do not want to change the way vim works fundamentally, i just want to present it differently. Standard vim will always exist in the form that it does. Neovim is supposed to be a polished as i understand it, not just rewritten for the sake of it.

The popularity of these kind of threads that covers default settings, and ease of learning are there for a reason. I can use vim nicely. and know the settings i mostly use. But still i would rather uncomment some settings if find them annoying than add some setting i want. Less keystrokes, and less hassle.

**Comment by Pyrohh** [comment]
@TotalKrill I too think that having a more in depth example nvimrc (with many comments) would be great to have, but I must disagree with this:

> I can use vim nicely. and know the settings i mostly use. But still i would rather uncomment some settings if i find them annoying than add some setting i want. Less keystrokes, and less hassle.

I'm all for more sane defaults (i.e., backspace behavior), but the defaults we do change should have obvious reasons behind them. I'm not sure if you're suggesting this, but not everyone wants things like `hlsearch`, `number`, `cursorline`, etc. I know you said if people find it annoying, then they can comment things out, which brings me to an example:

I like a lot of things about emacs, but it just has so damn many visual distractions enabled by default, which, for me at least, took a while to track down all the options and add them to my config. I'm a much bigger fan of things that have a minimal base, which can then be built upon when needed (e.g., Gentoo), as it follows the principal of least surprise.

**Comment by TotalKrill** [comment]
I was suggesting to have things like hlsearch, number , cursorline and more
enabled by default, but if the community finds that to be bad defaults, at
least have them commented and explained in the nvimrc. I we want to help
the adoption of vim forward, we need more accessible information about how
to configure it and how to use it.

But now we are straggling into the field of defaults to much. The question
at hand is not which settings should be enabled by default, but more how to
present vim to a new user. The defaults i think was decided to be
vim.sensible or at least leaning that way. In whatever defaults are set, i
would like to have comments there. Oneliners explaining an option and a
header text explaining vimrc in a few short lines.
-------------------Example-----------------

" This is the default settings file, to comment lines use a double quote at
the beginning of the file.
" To enable a setting found here, remove the double quote, to disable,
insert a double quote.
" This is also where you enable plugins.
" If you want custom settings for a specific project. Place a new file
.vimrc in the directory you want
" the settings to apply.

" Some common settings are:
:source vim.sensible " - Using the settings from the file vim.sensible
[default]

":set number " - this will place linen numbers to the left of the editor.
":syntax enable " - this will enable syntax highlighting for known formats

"...

" To change the colorscheme use the below setting, where <name> can be:
list most common 4.
":colorscheme <name>

**Comment by Pyrohh** [comment]
I see, thanks for clarifying. A well commented vimrc would go a long way.

**Comment by ZyX-I** [comment]
> It's also worth mentioning that dashes don't seem to be taken into account for K when keywordprg=:help. For example, go to starting.txt, and to the first instance of cmdline-arguments. Where K brings you depends on whether your cursor is in front of or behind the dash.
> 
> I'm guessing this could be "fixed" by setting option-backslash differently.

Option-backslash and `&keywordprg` value are completely irrelevant, what you see is the expected behaviour and can be fixed (by breaking other motions). Check out the very third sentence in `:h K`.

**Comment by waldyrious** [comment]
FWIW, the single most efficient and pleasant system I have ever experienced to teach new users how to use an unfamiliar program can be described as a learn-as-you-go system. No "tips" popups on startup, no tutorials / tours, no cheatsheet modal dialog, no help menu, etc. The program simply let me use it normally as I would expect, and when I did an action which had a better way to do it, a tooltip appeared (in-place, not in a generic "tooltip area") telling me how to do it better. When I did something that could be misinterpreted as meaning something else (say, saving instead of exporting), I got a similar notification telling me what I did *and* how to do the other thing I might have intended instead.

Granted, it was a GUI program, but the concept is easily adaptable to other interfaces. For vim, an example would be to start out in insert mode and the regular keyboard shortcuts (Ctrl+S, Ctrl+C/X/V, etc) and only when the user does something, the interface presents a friendly, unobtrusive tip, saying something like "you can also do X by pressing (...) and then (...)".

That would be my suggestion for a newbie-friendly learning experience -- one which helps contextually and unobtrusively, neither interrupting nor paternalistically deciding for the user what they should learn and in what order.

**Comment by HiPhish** [comment]
I'm going to chime in as someone who learned Vim only a few months ago (after being fed up with Xamarin Studio).

The first thing any new user has to realise when starting out with Vim is that Vim is a fundamentally different editor than what they are used to. Expecting Vim to be like Notepad is like expecting a car to be like a bicycle. Sure, both are contraptions with wheels to drive around, but they are operated in fundamentally different ways. If someone expects to just jump into Vim without re-learning things they might as well just go back where they came from.

I'm not saying this to be elitist, but people need to come in with the right mindset. You will never be able to please everyone, and Vim is not an editor for grandma to write letter to her grandchildren in. Vim like every other tool has a particular purpose and trying to bend it to do something it was not meant to do will just break it.

What I found most useful for starting out was the Vimtutor. It's a nice tutorial that lets you experiment with text and when you are through with it you are competent enough to do basic text editing. That's not to say that Vimtutor is perfect, far from it. Vim is like a language with its own grammar, so a tutorial should also draw attention to that fact and explain why certain chords are what they are.

In fact, instead of having only one tutorial we should have several. The original is good to get the user to not run around in circles screaming, but after that you are kind of on your own with a manual that could fill a library. A second tutorial could for example be about efficiency, further emphasising the modal nature and how a few short chords can perform large tasks. The third tutorial would be about customising Vim and a very light introduction to Vimscript (only the bare minimum, no functions or loops). And a fourth tutorial would be an introduction to Vimscript.

This is just a basic idea, we could argue whether to have more or less tutorials or which topics to include, but my idea is to help users help themselves. Vim's built-in documentation is good if you know what you are looking for, but if you have no idea it is as useful as looking at the circuitry of your TV when you want to know how to swap two channels. We need to ease users into Vim, and as they go along they will become more and more comfortable with the way Vim works. I have Drew Neil's *Practical Vim* here and it does a very good job of this, whereas another book I had borrowed from the library was just an abridged version of the built-in documentation, pretty awful.

I like the idea of @fwalch to display a beginner's message if there is no `.nvimrc` file, beginners will like it and every halfway experienced user will have a `.nvimrc` anyway.

I disagree with having visual clutter turned on by default. Even though personally I like visual clutter, it is distracting when you have no idea where it is coming from or what it means. Anything but the bare minimum should be something users explicitly turn on by their own will. We can draw attention to the most useful and popular ones like syntax highlighting and line numbers in the customisation tutorial though.

**Comment by fmoralesc** [comment]
> In fact, instead of having only one tutorial we should have several. The original is good to get the user to not run around in circles screaming, but after that you are kind of on your own with a manual that could fill a library. A second tutorial could for example be about efficiency, further emphasising the modal nature and how a few short chords can perform large tasks. The third tutorial would be about customising Vim and a very light introduction to Vimscript (only the bare minimum, no functions or loops). And a fourth tutorial would be an introduction to Vimscript.

@HiPhish Good ideas! If we assume we'll go ahead and include my vim-tutor-mode plugin to replace the old vimtutor in nvim, as per #2351 (I'll make a PR bundling it once I'm done with #2041), perhaps someone could help writing those tutorials in the new format? ;) (vim-tutor-mode also allows plugin writers to provide interactive tutorials, btw).

**Comment by HiPhish** [comment]
I could write the first two tutorials, but I'm still too unexperienced to write about more advanced topics. Interactive tutorials sound like a good idea. If others agree we can start properly planning the tutorials series.

**Comment by Pyrohh** [comment]
Small reminder that it might be a good idea to build off of @dahu's LearnVim as a starting point, or at least as a point of reference (he mentioned above that attribution should be given). Apologies if I'm missing something, I just don't someone to waste their time unnecessarily writing a tutorial from scratch.

**Comment by fmoralesc** [comment]
I already started porting learn in to vim-tutor-mode, as mentioned above
and elsewhere. It would be nice if someone helped me finishing porting it.
Just saying...  ;)

**Comment by Pyrohh** [comment]
I'd love to help out, just message me on gitter.

**Comment by fmoralesc** [comment]
Will do.

**Comment by HiPhish** [comment]
Me too. I have experience with teaching, so I'd be glad if I can help out.

**Comment by fmoralesc** [comment]
Added you both to a channel for vim-tutor-mode in gitter, so we can discuss things further.

**Comment by fmoralesc** [comment]
For anyone else interested in joining that, it' at https://gitter.im/fmoralesc/vim-tutor-mode

**Comment by justinmk** [comment]
Resolved to a reasonable degree by https://github.com/neovim/neovim/pull/2700 . New issues can discuss other approaches.

**Comment by techtonik** [comment]
It would be nice to see an article summarizing the stuff that happened in this thread. Might be valuable experience for somebody who is studying design on interfaces.

**Comment by Pyrohh** [comment]
@techtonik Indeed, but I think that's very low priority right now. If someone wants to contribute an article I'm sure that'd be welcome.
