### ISSUE TITLE
filetype.lua does not use scripts.vim

### ISSUE THREAD

**Issue by SanchayanMaity** [neovim/neovim#16940]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+835-gf65b0d423

### Vim (not Nvim) behaves the same?

I assume it does

### Operating system/version

EndeavourOS/Arch Linux

### Terminal name/version

kitty 0.24.0

### $TERM environment variable

xterm-kitty

### Installation

Build from source

### How to reproduce the issue

Use neovim as pager in git config.

```
[core]
	editor = nvim
	pager = nvim -R
```
Have this in `init.lua`

```
vim.g.do_filetype_lua    = 1
vim.g.did_load_filetypes = 0
```
Run `git diff`. Things will not be highlighted and `echo &ft` returns no result.

Note that opening a `diff` file works properly.  Also, `git difftool` works fine where the relevant config is below.

```
[diff]
	tool = nvimdiff
[difftool]
	prompt = false
	trustExitCode = true
[difftool "nvimdiff"]
	cmd = nvim -R -d $LOCAL $REMOTE
```

### Expected behavior

File type should be set to diff and highlighted as per diff.

### Actual behavior

File type not set to diff and not highlighted as per diff.

**Comment by clason** [comment]
Can you check whether the corresponding file type detection from file type.vim has been ported? At this stage, lack of parity is NOT a bug (yet).

In general, if you find a missing check, please make a PR instead of opening an issue about it; it's very easy, and otherwise these issues will end up cluttering the tracker.

**Comment by SanchayanMaity** [comment]
> Can you check whether the corresponding file type detection from file type.vim has been ported? At this stage, lack of parity is NOT a bug (yet).

Sure, understandable. Will remove that label. To clarify, a `diff` file when opened does work properly. 

> 
> In general, if you find a missing check, please make a PR instead of opening an issue about it; it's very easy, and otherwise these issues will end up cluttering the tracker.

I did check and IIUC it is done [here](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/filetype.lua#L151). Do not know how it differs when using `git diff` where neovim is pager.

**Comment by gpanders** [comment]
As @naruaway correctly pointed out, `scripts.vim` (which detects filetype based on file contents) is at this time *not* part of filetype.lua, which only does filetype detection based on the file name.

If you set `let g:did_load_filetypes = 0` to disable `filetype.vim` then `scripts.vim` is also unused. This is something I'm aware of, but am not sure yet how best to solve. The tricky part is that we want the ordering to work like this:

1. Run filetype.lua
2. If no filetype found, run filetype.vim
3. If no filetype found, run scripts.vim

>for example, filetype.nvim is using "setf" to prevent it from overriding already-detected case but filetype.lua is always forcefully setting filetype.

setf is useful for filetype.vim-style autocommands, where you may have multiple autocommands fire for the same buffer and you want to enforce a kind of "priority". However, filetype.lua only ever runs once per buffer, and it runs before any of the other filetype detection autocommands, so it doesn't make sense to use setf in this case.

**Comment by naruaway** [comment]
Thanks @gpanders for quick and thorough response!
>  it runs before any of the other filetype detection autocommands

I just want to clarify about this part, I think it still makes sense to at least consider user-defined custom file type detection intercept like putting something like `autocmd BufNewFile,BufRead imactuallytypescript.txt setf typescript` (weird example but assuming in reality we could have more complicated logic to conditionally call `setf`) inside `init.lua`. This way is sometimes better than overriding filetype "later" (e.g. ftdetect) since it can avoid possible side effects due to multiple `FileType` autocmd triggers.

However when using filetype.lua, it always overrides filetype even if it's already set in an autocmd defined in init.lua...
Should I open an issue for this? Also related, I feel like if we can turn `vim.filetype.match()` into a pure function (input is `path` and `getline` function for contents inspection, output is resolved filetype or `nil`) directly usable by anyone, we can make the whole filetype detection mechanism more composable and flexible (e.g. users can write their own file type detection logic inside `init.lua` by leveraging `vim.filetype.match()`)

**Comment by gpanders** [comment]
> I just want to clarify about this part, I think it still makes sense to at least consider user-defined custom file type detection intercept like putting something like autocmd BufNewFile,BufRead imactuallytypescript.txt setf typescript (weird example but assuming in reality we could have more complicated logic to conditionally call setf) inside init.lua. This way is sometimes better than overriding filetype "later" (e.g. ftdetect) since it can avoid possible side effects due to multiple FileType autocmd triggers.

Good point, this is a use case I hadn't considered. setf does make more sense in light of this.

>Also related, I feel like if we can turn vim.filetype.match() into a pure function (input is path and getline function for contents inspection, output is resolved filetype or nil) directly usable by anyone, we can make the whole filetype detection mechanism more composable and flexible (e.g. users can write their own file type detection logic inside init.lua by leveraging vim.filetype.match())

Sure, if you want to whip something up in a PR we can discuss the details there.

**Comment by clason** [comment]
> Also related, I feel like if we can turn vim.filetype.match() into a pure function (input is path and getline function for contents inspection, output is resolved filetype or nil) directly usable by anyone, we can make the whole filetype detection mechanism more composable and flexible (e.g. users can write their own file type detection logic inside init.lua by leveraging vim.filetype.match())

That may also be useful for plenary's fast filetype detection magic @tjdevries

**Comment by tjdevries** [comment]
Yeah, maybe `vim.filetype.match(filepath: string, get_contents: fn() -> []string)` where filepath is the file and get_contents returns the file contents (so that you don't have to always get all the file contents) would be good, IMO. Or perhaps:

```lua
-- This matches bufnr 5
vim.filetype.match(5) 

-- This calculates based on these two inputs
vim.filetype.match { path = "/path/to/file", contents = function() return { "#!/usr/bin/env python3", "print('hello world')" } end }
```

could be interesting

**Comment by tjdevries** [comment]
Also, feel free to tag me in PR as well so we can chat more about it

**Comment by oncomouse** [comment]
> That may also be useful for plenary's fast filetype detection magic

I just wrote a quick plugin, based on @clason's suggestion, that uses `plenary.filetype` to do content-based detection when `filetype.lua` doesn't guess `filetype`, if anyone is interested: https://github.com/oncomouse/plenary-script.nvim

**Comment by SanchayanMaity** [comment]
@naruaway @gpanders Thank you for the detailed explanation.
