### ISSUE TITLE
filetype.lua sets wrong filetype for yaml

### ISSUE THREAD

**Issue by seblj** [neovim/neovim#16977]
### Neovim version (nvim -v)

NVIM v0.7.0-dev+848-gb4fbb9dcf

### Vim (not Nvim) behaves the same?

Not relevant because of `filetype.lua`

### Operating system/version

Ubuntu 20.04

### Terminal name/version

xterm 3.1

### $TERM environment variable

xterm

### Installation

Build from master

### How to reproduce the issue

Have the following in `init.lua`:
```lua
vim.g.do_filetype_lua = 1
vim.g.did_load_filetypes = 0
```

Open a file named `zsh.yml`.

### Expected behavior

I would expect that the filetype is set to `yaml` like it seems to do on other filenames. For example if opening a file `test.yml` it sets the correct filetype.

I also couldn't override it myself using:
```lua
vim.filetype.add({
    extension = {
        yml = 'yaml',
    },
})
```

### Actual behavior

It sets the filetype to `zsh`.

**Comment by seblj** [comment]
Workaround until this is fixed is:
```lua
vim.filetype.add({
    filename = {
        ['zsh.yml'] = 'yaml',
    },
})
```

**Comment by gpanders** [comment]
This is a flaw in `filetype.lua`. Because patterns are checked before extensions, patterns like this: 

https://github.com/neovim/neovim/blob/72c3c1a0141406033c10443be0a38f50cb1fdbe2/runtime/lua/vim/filetype.lua#L1339

Will match before any extension does.

We need to rearchitect `filetype.lua` to make patterns with negative priority run after extension matching.
