### ISSUE TITLE
Config option for hybrid line number alignment

### ISSUE THREAD

**Issue by lilibyte** [neovim/neovim#17124]
### Feature description

Current functionality:

```
  2
  1
72
  1
  2
```

Ideal functionality provided the option is set:

```
  2
  1
 72
  1
  2
```

[Relevant answer](https://vi.stackexchange.com/a/3517)

**Comment by clason** [comment]
Your "ideal functionality" is exactly how it looks with `set number relativenumber`. Are you sure you're using the latest version of Neovim?

**Comment by lilibyte** [comment]
I'm on the latest Arch Linux package at least. Here's another example for a file with 1000 lines:

```
   2
   1
3  
   1
   2

   2
   1
10  
   1
   2

   2
   1
100 
   1
   2

   2
   1
1000
   1
   2
```

**Comment by clason** [comment]
Yep, that is how it's supposed to look -- to have the current line number stand out.

I think this request should first be opened upstream (https://github.com/vim/vim); if they implement it, we will port the patch. This avoids needless duplication of effort and divergence.

**Comment by lilibyte** [comment]
The goal of neovim is confusing to me if effort and divergence from vim is avoided in principal, but I'll close this anyway. Thanks.

**Comment by clason** [comment]
Well, we try not to change things that would also make sense for Vim (unless they explicitly refuse to do so, in which case feel free to reopen); we focus our efforts on specific _additions_.

But I agree that knowing what is best done upstream and what is better done here is not easy -- I wasn't telling you that opening this issue here was _wrong_; just how to best proceed with your feature request.
