### ISSUE TITLE
Neovim starts with some command typed on already [GitBash]

### ISSUE THREAD

**Issue by CarlosMiraGarcia** [neovim/neovim#17141]
### Neovim version (nvim -v)

0.5.0

### Vim (not Nvim) behaves the same?

No. Vim works correctly. Version 8.2

### Operating system/version

Windows 10

### Terminal name/version

mintty 3.5.2 (Git Bash)

### $TERM environment variable

xtern-256color

### Installation

system package manager

### How to reproduce the issue

nvim --clean

### Expected behavior

The problem is somehow related to the background color of the terminal.
Here in the videos you can see how nvim starts with some command already typed in, which changes when the background color of the terminal changes.

![mintty_AdJAOzlEOg](https://user-images.githubusercontent.com/72560934/150149355-af04e6e9-b886-4ebf-8c35-a75a8a6591fd.gif)

### Actual behavior

In this video, you can see how it works correctly when using Windows Terminal, even though is using mintty too.

![WindowsTerminal_WIoWzxkPbh](https://user-images.githubusercontent.com/72560934/150149398-6ff0c63e-2afe-4fd3-bf2a-8468efc60602.gif)

**Comment by clason** [comment]
Please upgrade to the latest version (0.6.1) and try again. (`--clean` doesn't work as you expect in 0.5.0).

**Comment by CarlosMiraGarcia** [comment]
> 
Tried that. Same issue

![mintty_AV6vu57z9P](https://user-images.githubusercontent.com/72560934/150159068-1af9e8c7-c85a-4c05-9bfe-3f3b4dabee82.png)

**Comment by kdheepak** [comment]
I’ve also experienced this on my Mac only with Neovim (not with vim/emacsclient/nano etc). But I assumed at the time that I was doing something incorrectly. I knew at the time it was because of the background color of the terminal. I believe neovim is requesting for the background color and the terminal is responding late (?), and then once neovim loads the terminal stdin gets the terminal escape code for the background color. Since that escape code has `/` in it, it fills the command prompt as a search. Here is a related issue:

https://github.com/kdheepak/taskwarrior-tui/issues/46#issuecomment-778871257

**Comment by CarlosMiraGarcia** [comment]
Thank you kdheepak for explaining the issue better than I did!

**Comment by CarlosMiraGarcia** [comment]
Any updates on this?

**Comment by erw7** [comment]
This is caused by the missing `<ESC>` in the sequence being sent (I have checked with debugger). Closed because it is not a neovim issue.
