### ISSUE TITLE
Is VisualNOS deprecated?

### ISSUE THREAD

**Issue by adrian5** [neovim/neovim#17400]
### Feature already in Vim?

Nvim 0.7.0

### Feature description

I was looking at the (`:h highlight-groups`) docs and was wondering what the story regarding [VisualNOS](https://github.com/neovim/neovim/blob/master/runtime/doc/syntax.txt#L5225-L5226) is.

Did it get supplanted by [VisualNC](https://github.com/neovim/neovim/blob/master/src/nvim/highlight_defs.h#L140), or do the two have different roles? The only relevant issue I found was [this comment](https://github.com/neovim/neovim/pull/6737#issuecomment-301377619) from 2017.

**Comment by dundargoc** [comment]
I played detective for 30 minutes, this is how I interpret what happened to visualNOS:

* VisualNOS was removed in [this PR](https://github.com/neovim/neovim/pull/2914) and [this commit](https://github.com/neovim/neovim/pull/2914/commits/f48c8d652ce93091a0ba0cb38c353ebb991e0700) with the following commit message:

> Nvim hasn't ever had X11 integration, so this has was never needed.

Then I interpret from [this comment](https://github.com/neovim/neovim/pull/6737#issuecomment-301377619) that VisualNOS should be kept since we plan on re-implementing autoselect (not sure how relevant it is currently since it's been a while since that comment).

I think that VisualNOS isn't used/needed at this point but may be relevant later, which is why I think it's in a bit of a no man's land currently (as in not completely removed but not completely included either).

I think that's the gist of it really. Someone please correct me if I misunderstood anything.

**Comment by dundargoc** [comment]
I'll use the time I spent researching this as a justification to close down this issue if you don't mind :). Let me know if I missed to mention something.

**Comment by adrian5** [comment]
Cool, thanks for looking into it!
