### ISSUE TITLE
Expose LSP-specific functionality (e.g. code actions, hover) to plugins

### ISSUE THREAD

**Issue by jose-elias-alvarez** [neovim/neovim#17511]
### Feature already in Vim?

No

### Feature description

Currently, there is no way for users and plugins to reliably hook into a majority of Neovim's LSP functionality, as described in `:help lsp-api`. In some cases, users can [override the built-in handlers](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/handlers.lua) to inject additional results from non-LSP sources, but this relies on and can cause conflicts with actual LSP clients. There's some discussion about how to define additional handlers in #14258, but these also depend on "hijacking" a client. Plugins like [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) can get around these limitations but must override the mechanism used to spawn clients, an approach which is far from ideal.

To my knowledge, the stance so far has been that this functionality is inherently LSP-specific, and so exposing it to non-LSP sources doesn't make sense. However, I think that generalizing at least some of this functionality could have benefits.

To use code actions as an example: It's easy enough to write a plugin to generate custom, non-LSP code actions and combine them with authentic code actions. The issue is that each new code action provider then depends on that plugin, and each new consumer must also integrate with that plugin, which significantly raises the burden of writing and maintaining integrations across the board. This is similar in nature to [the issue that motivated the creation](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#why-language-server) of the language server protocol, albeit on a much smaller scale:

> From language toolings' perspective, they need to adapt to code editors with different APIs. From code editors' perspective, they cannot expect any uniform API from language toolings. This makes implementing language support for `M` languages in `N` code editors the work of `M * N`.

I think the `vim.diagnostic` API is a fantastic example of the benefits of generalizing previously LSP-specific functionality. Thanks to the API, users can display and interact with diagnostics in a unified way without knowing or caring about the exact nature of the source. New diagnostic sources and consumers then can expect full integration as long as they conform to the API.

While not definitive, I think it's also worth mentioning that VS Code (for which the language server protocol was originally developed) allows extensions to integrate with almost all of this functionality via [its API](https://code.visualstudio.com/api/references/vscode-api). As a result, it's trivial for extensions to register themselves as providers, as in [this simple example](https://gist.github.com/jose-elias-alvarez/c3e84cc26e275ce0183fef65cd5b670c). 

I am happy to contribute to this but am opening an issue first to gauge if there is any interest in this / if there's any chance of getting something like this merged in the first place. I think code actions may be a good place to start, since I've seen interest from users in various places.

**Comment by mjlbach** [comment]
> To my knowledge, the stance so far has been that this functionality is inherently LSP-specific, and so exposing it to non-LSP sources doesn't make sense. However, I think that generalizing at least some of this functionality could have benefits.

My general issue with this, is it assumes that vscode is something worth emulating which, personally, I strongly disagree with. I do not think we should not build out features that attempt to emulate vscode, unless we think those features have inherent value/are an unambiguous improvement to core neovim functionality that could not be implemented in a plugin, or strongly would benefit from inclusion in neovim core. I would argue while diagnostics and formatting are worthy of independent APIs, things like code actions and hover (while I see some case for code actions, I'm not sure I see any value in this one?) are not.

Diagnostics are a generic concept, we didn't break vim.diagnostic into a module because we wanted to emulate the vscode API, we did so because we wanted to consolidate thing like ALE, neomake, and LSP's presentation layer because we had already a presentation layer for LSP and the integration actually made the lsp diagnostic api more robust/*less* overfit to vscode compatibility.

With code actions, it's different. A code action is two round trips to a language server. The long and short of it is user's want to shove custom lua code into that menu because it's convenient for a specific workflow, they just want a generic, context specific menu. I think it's fine as a plugin, but I'm personally not interested in reviewing/merging some generic code action module in core.

**Comment by jose-elias-alvarez** [comment]
I understand your thinking and appreciate the guidance. I'll close this and think about other solutions.

**Comment by mjlbach** [comment]
I'm also not the only opinion who matters, so others can chime in. @mfussenegger had some thoughts. I personally don't use code actions that often (which IMO is what users care most about in the context of this).

**Comment by mfussenegger** [comment]
I can somehow see the appeal, but I agree with the points raised by @mjlbach and I think it would also go a bit against the core idea of LSP. It would encourage people to write extensions on the client side specifically for neovim instead of improving the language servers themselves so that users of other editors can also benefit. That's something that bugs me about the vscode model - some authors write things in their client extensions that would fit into the language server. Less functionality for us - unless we invent the same thing in custom neovim plugins. We don't need to turn this around so both sides suffer.

I see linters as an exception because they are useful outside of editors as part of CI and existed long before LSP came along. (My own nvim-lint plugin was initially actually intended as a stop-gap solution until LSPs have caught up, not as a permanent thing)

For formatters we already have `formatprg` and `formatexpr` and you typically only want to use one formatter, not multiple since they'd just override each other. I'd rather reduce the amount of ways to do formatting instead of extending that further.


For code actions my point regarding "move it into the language server" applies - especially given that for many useful code actions you probably need to parse the document and do some semantic analysis. A language server already does that. Because of that, language servers like hls and jdtls have a plugin model that allows to extend the language servers themselves.

I think part of the motivation to write this all with lua/for neovim is because that's what some people are comfortable with - even if it isn't the best solution. 


The only part where I think it could be useful to extend/improve the existing API is around the completion, but that requires some thought if we want to avoid building a new world separate from the existing functionality. (and it is already well covered by dozens of plugin - many of which support some kind of pluggable sources)

**Comment by jose-elias-alvarez** [comment]
> It would encourage people to write extensions on the client side specifically for neovim instead of improving the language servers themselves so that users of other editors can also benefit.

This is a really good point. I think the threshold for contributing to language servers is much higher than the convenience of whipping up something in Lua but the former helps everyone, not just Neovim users. The original motivation for a lot of this comes from the JavaScript / TypeScript ecosystem, where the LSP situation is a gigantic mess and VS Code extensions have to fill the gap, creating exactly the situation you describe. Thank you for the thoughtful feedback on this!
