### ISSUE TITLE
Make it easy to build libnvim separately for embedding in other projects

### ISSUE THREAD

**Issue by monkey-w1n5t0n** [neovim/neovim#17524]
### Feature already in Vim?

N/A

### Feature description

The [API documentation](https://neovim.io/doc/user/api.html) mentions that `libnvim` can be embedded and used directly as a C library, but there's no guidance on how to build and use it. 

Building the whole project doesn't seem to produce any usable library objects (presumably because it's used statically?), and my CMake knowledge isn't advanced enough to know what needs to be changed to successfully build it as an independent dynamic library without breaking anything, so that can be easily integrated with other projects.

Could someone shed some light on how to do this? Perhaps it could be added as an optional flag to the build process for others that may want to do the same?

**Comment by zeertzjq** [comment]
Related: #12898

**Comment by lm-w1n5t0n** [comment]
The linked issue seems to focus on the documentation aspect of using the library. 

My request has to do with adding a "build just `libnvim` as a static/shared library" option to the build scripts, so that one can actually build it first before including it. As far as I can tell, to do that now I'd have to mess with the CMakeLists files at a level that's impractical and nearing the limits of my understanding of CMake builds.

They are, however, similar enough that I would be happy to merge them if that means attracting more attention.

**Comment by clason** [comment]
You might want to look at how https://github.com/qvacua/vimr does it (which to my knowledge is the only current serious user of `libnvim`). The sources are modified, though: https://github.com/qvacua/neovim

**Comment by jamessan** [comment]
> My request has to do with adding a "build just `libnvim` as a static/shared library" option to the build scripts, so that one can actually build it first before including it.

When we're ready to provide a stable C library, we'll do that.  That's not a priority right now.

**Comment by justinmk** [comment]
closing in favor of https://github.com/neovim/neovim/issues/21693
