### ISSUE TITLE
`setlocal nomodifiable` in `ftplugin/man.vim` not working 

### ISSUE THREAD

**Issue by nobodyatandnothing** [neovim/neovim#17595]
### Neovim version (nvim -v)

NVIM v0.6.1

### Vim (not Nvim) behaves the same?

yes, VIM - Vi IMproved 8.2 

### Operating system/version

Clear Linux 35970

### Terminal name/version

foot version: 1.11.0-72-g7d647c08 -pgo +ime +graphemes -assertions

### $TERM environment variable

foot

### Installation

system package manager (swupd)

### How to reproduce the issue

$ bash
$ export MANPAGER='nvim +Man!'
$ echo setlocal nomodifiable>~/.config/nvim/ftplugin/man.vim
$ man ls
:set modifiable?

### Expected behavior

nomodifiable

### Actual behavior

modifiable

**Comment by zeertzjq** [comment]
Does putting it in `~/.config/nvim/after/ftplugin/man.vim`

**Comment by nobodyatandnothing** [comment]
> Does putting it in `~/.config/nvim/after/ftplugin/man.vim` work?
no

**Comment by nobodyatandnothing** [comment]
but i can :q without a ! after editing

**Comment by dundargoc** [comment]
Summoning @nhooyr as he is the maintainer of `man.vim`.

**Comment by nobodyatandnothing** [comment]
opening a man page from within neovim with `:Man` does not have this issue

**Comment by bartels** [comment]
A workaround is to set `nomodifiable` at startup directly in $MANPAGER

```bash
export MANPAGER='nvim +"setlocal nomodifiable" +Man!'
```

I believe the issue might be due to this line, which resets `modifiable` to its original value
https://github.com/neovim/neovim/blob/release-0.7/runtime/autoload/man.vim#L499

The `init_pager` function's comment says it only runs when invoked as $MANPAGER.  It looks like the idea is to temporarily set `modifiable` and then reset to its original value at the end of the function. However since `filetype=man` happens in the line right before that (the `set_options` function call), any  ftplugins that have set `nomodifiable` are undone.

**Comment by justinmk** [comment]
What is even the problem? No mention of a use case.

 If you want to send a small, low-risk PR, feel free. Not worth tracking this otherwise.

**Comment by bartels** [comment]
@justinmk Perhaps not such a big deal, the problem I ran into is when using nvim to read a man page (e.g. with `export MANPAGER='nvim +Man!'` as `help Man` suggests), the buffer is modifiable, so accidentally typing the wrong key can land you in insert mode and change the buffer. 

There's also some wonkiness around then using `u` to undo the changes, which will undo the document's formatting.

To reproduce:

1. Set `export MANPAGER='nvim +Man!'` (as nvim `help Man` docs suggest)
2. Open a new terminal and open any man page: `man man`
3. Press `u` key

The formatting will be undone, leaving what look like raw control characters in the buffer. `nomodifiable`  prevents that.

Simple workaround: `export MANPAGER='nvim +Man! +"set nomodifiable"'`

**Comment by dundargoc** [comment]
I'll send a PR to fix this, as well as a PR removing nhooyr as the maintainer.
