### ISSUE TITLE
Fix ambiguous terminal key strokes? [$35]

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#176]
For example, in modern Linux terminal emulator like mate-terminal or gnome-terminal there is no difference between pressing ``<c-i>`` and ``<tab>``, among others.

Neovim not only should renovate vim, but also the terminals that vim runs on because the functionality allowed by terminals is very much a part of what defines vim functionality when in a terminal environment.

I'd like to be able to use neovim in modern Linux terminal while being able do both

```
map <c-i> :echo "hello"
```

and

```
map <tab> :echo "awesome"
```

Try these two mappings in terminal vim then try both <c-i> and <tab> to see what happens...

Such issues as these should definitely be addressed in a modern renovation of vim.

Please see this long thread on the topic in the vim_dev group: https://groups.google.com/forum/m/#!topic/vim_dev/2bp9UdfZ63M

**Comment by justinmk** [comment]
@tarruda @leonerd Since https://github.com/neovim/neovim/pull/1820 was merged, isn't this issue as close to resolved as can be expected? Will nvim recognize CSI codes if configured as mentioned in 
https://github.com/neovim/neovim/issues/176#issuecomment-37070131 and
 https://github.com/neovim/neovim/issues/176#issuecomment-38017737 ?

**Comment by justinmk** [comment]
@cstrahan @leonerd Do you know of a document or  tutorial that explains how to configure CSI codes for, say, xterm or gnome-terminal or iterm2? [This link](http://www.quora.com/What-is-iTerm2s-modern-parser) seems to imply that it's just a single checkbox to enable CSI magic (I don't use iterm2 so I can't check).

**Comment by cstrahan** [comment]
@justinmk I don't know of any readily available configurations - perhaps @leonerd knows of some?

I use urxvt, so I might take a stab at writing a configuration for that.

**Comment by cstrahan** [comment]
To set the high bit (instead of sending an escape character) for meta, you can use the following (for URXVT) in `.Xresources`:

    URxvt.meta8: true

So, that's a start :).

**Comment by cstrahan** [comment]
I do wonder if there's an existing program that will echo (in English) the the key sequences entered, according to fixterms... Would be a really nice tool for quickly sanity checking terminal configurations.

**Comment by tarruda** [comment]
> To set the high bit (instead of sending an escape character) for meta, you can use the following (for URXVT) in .Xresources:

> URxvt.meta8: true

You can't do that for Neovim since libvtermkey requires the leading esc to parse alt/meta

**Comment by tarruda** [comment]
> @tarruda @leonerd Since #1820 was merged, isn't this issue as close to resolved as can be expected? Will nvim recognize CSI codes if configured as mentioned in #176 (comment) and #176 (comment) ?

Yes nvim is now capable of recognizing these through libtermkey.

> @justinmk I don't know of any readily available configurations - perhaps @leonerd knows of some?

> I use urxvt, so I might take a stab at writing a configuration for that.

@cstrahan Something you can do check what codes [pangoterm](http://www.leonerd.org.uk/code/pangoterm/) sends when a key combination is pressed(using xxd or cat) and configure urxvt to send the same codes. Pangoterm is also another project by @leonerd and consequently it uses the same encoding used by libtermkey. For example, to map ctrl+alt+j you need to add this to you .Xresources:

```
urxvt.keysym.C-M-j:       \033[106;7u
```

The above code is what pangoterm sends when ctrl+alt+j is pressed

**Comment by cstrahan** [comment]
> You can't do that for Neovim since libvtermkey requires the leading esc to parse alt/meta

From fixterms:

> Certain key presses have special behaviours with modifiers. Alt tends to prefix Escape or set the top bit. Ctrl ends to mask with 0x1f. When the simplest form of these keys are pressed, they should be encoded as previously.

I haven't looked at libtermkey's source, but if it follows fixterms - and assuming I interpreted that quote correctly - it should be okay to set the high bit for alt/meta for the "simplest form of these keys."

**Comment by cstrahan** [comment]
And Escape shouldn't be necessary for alt/meta, as you can use the 8bit CSI code `0x9b` instead of the 7bit multibyte `0x1b 0x4b` (`Escape [`). If you use `0x9b`, programs can be configured to no longer employee timeouts for determining if `Escape <blah>` means `Alt-<blah>` or `Escape` followed by `<blah>`.

**Comment by leonerd** [comment]
@cstrahan If a program sends S8C1T to the libvterm instance, then that's exactly what will happen. :)

**Comment by cstrahan** [comment]
@leonerd: I'm afraid I don't follow. Being unfamiliar with S8C1T, I tried looking it up, but I don't know how to interpret the documentation (http://vt100.net/docs/vt510-rm/S8C1T).

**Comment by boxofrox** [comment]
@cstrahan, I think @leonerd was saying if nvim prints(?) <Esc><Space>G, then libvterm will upgrade from 7-bit controls to 8-bit controls, and 8bit CSI codes will be used instead of 7bit multibyte.  The ANSI Control Functions Summary in the docs you linked was informative.  (http://vt100.net/docs/vt510-rm/chapter4#S4.1)

**Comment by cstrahan** [comment]
Oh, gotcha. So sending S8C1T requests that the terminal emulator send 8-bit controls. @leonerd is there a standard way to test (within a terminal application) that S7C1T/S8C1T is supported by the terminal emulator, and which mode is currently active? Is SMCUP/RMCUP supposed to persist/restore this setting? Trying to think of ways that 8-bit controls could be sent per application, while restoring back to default 7-bit on exit so other terminal apps don't break.

**Comment by leonerd** [comment]
@cstrahan Definitely. What you do is ask to enable S8C1T then immediately enquire the state of some terminal mode using `DECRQSS` or similar. The result will come back in either 7- or 8-bit form. If it comes back in 8bit form then all is fine. If it comes back in 7- rather than 8-bit form, then you know it wasn't recognised, and you can continue working as it does now.

I don't offhand know how DECAM ("DEC Alternate buffer Mode", the mode that `SMCUP`/`RMCUP` usually modify) interacts with this setting on most terminals; though I expect it's largely independent. Certainly on `libvterm` they are independent. It would be easy enough to do the `DECRQSS` dance first on startup, and remember if you need to reset back to `S7C1T` on exit.

**Comment by cstrahan** [comment]
@leonerd Very cool, thanks! I was initially under the impression that configuring one's terminal would have to be an all-or-nothing ordeal, potentially breaking mappings in other apps. It sounds like a reasonable migration path would be:

* Have terminal emulators follow `fixterms` when in `S8C1T`, and behave as usual in `S7C1T`.
* Have applications use `DECRQSS` to check for support for S8C1T. That doesn't necessarily mean that the terminal follows `fixterms`, but it could be a good enough heuristic: an app could provide an option along the lines of `set fixterms` that would first check for 8-bit controls, using fixterms mappings if so, otherwise falling back to the status quo.

As a user, that doesn't sound too inconvenient. I think the big thing that needs to happen is getting support into the terminals (either upstream, or providing a robust third-party solution via plugins or some such), and then we need to expand awareness about this "progressive-enhancement" approach. Neovim could potentially spearhead this technique, and if others will follow suit, we could one day live in a world where keybindings work somewhat intuitively :).

**Comment by mskar** [comment]
Does anyone know the terminal escape code for `<D-CR>`?
I found all the other `<CR>` combo escape codes:

| KeyCombo       | EscapeCode |
|----------------|------------|
| \<S-CR\>       | [13;2u     |
| \<M-CR\>       | [13;3u     |
| \<M-S-CR\>     | [13;4u     |
| \<C-CR\>       | [13;5u     |
| \<C-S-CR\>     | [13;6u     |
| \<M-C-CR\>     | [13;7u     |
| \<M-C-S-CR\>   | [13;8u     |

**Comment by leonerd** [comment]
@mskar Don't think of them as a flat list; there's thousands of combinations, you'll be there forever. Think of them as a bitmask. "Shift" adds 1 (1<<0), "Meta" or "Alt" adds 2 (1<<1), "Ctrl" adds 4 (1<<2). Add them together, add 1 more for silly legacy reasons, and that gives the "modifier" value in the "CSI u" sequence.

As to the "D-" part, I'm not sure what the "D-" modifier might be, but perhaps you just want to make that 8 (1<<3)?

**Comment by mskar** [comment]
Thanks @leonerd, the modifier for `D-CR` will depend on the OS:
- Mac: cmd
- Linux: super
- Windows: win
It may be that a new sequence will be required, e.g. `[13;9u`, but the terminal programs I am using (vim/neovim) will have to be able to process that code as `D-CR`. I know neovim supports `D-CR` (it also works by default in some vim GUIs like macvim and vimr) but I may have to submit a issue or pull request to have vim/neovim to expect `[13;9u`.
Thanks again for your help!
