### ISSUE TITLE
test setreg(), getreg() (convert testdir/test_eval.in)

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1780]
followup of https://github.com/neovim/neovim/pull/1182#discussion_r21437179

**Comment by bfredl** [comment]
I think this can be closed now, or anything you miss @justinmk ?

**Comment by justinmk** [comment]
Do we support `getreg()` with 3 arguments yet? I can't check any of this at the moment.

#2411 looks nice btw, great work.

**Comment by justinmk** [comment]
Couldn't help myself... Looking at `testdir/test_eval.in`, it seems to test:

   ...(getreg(a:reg, 0, 1)), getreg(a:reg, 1), string(getreg(a:reg, 1, 1)

which covers the first 2 variants in my linked comment. It also tests `setreg(..., 'c')` as well as `'l` and `'b'` variants. 

However, it does not test clipboard, per this comment at the top:

    Note: system clipboard support is not tested. I do not think anybody will thank
    me for messing with clipboard.

So, this task reamining to close this issue is:

- convert `testdir/test_eval.in` to a lua test, using the fake clipboard provider
- add `+` and `*` to the test table in the converted `testdir/test_eval.in`

**Comment by bfredl** [comment]
Sounds reasonable. BTW `test/functional/clipboard/clipboard_provider_spec.lua` suffers a bit from identity crisis: in order to test clipboard function, due to `clipboard=unnamed` it must actually test a lot of register functionality in general. A solution would be to refactor `basic_register_test` into a `describe` collection of tests of register functionality, and somehow rerun the entire `describe` block both without and with `clipboard=unnamed`

**Comment by bfredl** [comment]
> Note: system clipboard support is not tested. I do not think anybody will thank
me for messing with clipboard.

Actually, in #2077 I would like to test the clipboard  between instances, using "system" clipboard. Perhaps this could only be done by default on ci, and on local systems with `Xvfb` (and `xsel` ) available. (Restoring old clipboard contents/ownership on X11 _kind_ _of_ works, but I dont think it can be done reliably)
