### ISSUE TITLE
{visual}P to put without yank to unnamed register

### ISSUE THREAD

**Issue by jfelchner** [neovim/neovim#1790]
This is one of those things that has always bugged me about vim.  I understand the reason that it's there, but it seems to me as something that behaves the way it does simply due to the way things _used_ to be rather than the way things are now.

What I'm talking about is how 'put' replaces the contents of the default register whenever it's used with any visual block or text object prior to being used.
#### Explanation (for those that need it)

If my text file is:

```
hello
goodbye
```

And I move the cursor to the `goodbye` line and press `yy` to yank it and then move to the `hello` line, visually select and press `p`, if I went to another line to do another put, it wouldn't put `goodbye`, it would put `hello`.

So now if I want to put `goodbye` I have to use the yank register which is two extra keystrokes.  And that only works if I yanked it.  If I deleted it, I have to use a different register.  And now I have to remember if I yanked it or deleted it and use the proper register.
#### End Explanation

I have a mapping to do this, but it barely ever works and is something that IMO needs proper blessed support.

**Comment by justinmk** [comment]
For visual mode, AFAICT `P` does the same thing as `p`. We could change `{visual}P` to always preserve the unnamed register.

Another general enhancement that would be low-risk and high-value is adding autocmds for paste/yank events, to allow robust and efficient "yankring" plugins. Currently, yankring plugins must listen to `CursorMoved`.

**Comment by bfredl** [comment]
@justinmk +1 to paste/yank autocommands (I prototyped a `Unite.vim` based yankring-style plugin on the first clipboard provider iteration some time ago. autocommands should work nicely for this use case )

**Comment by jfelchner** [comment]
@justinmk thanks!

**Comment by ChrisPenner** [comment]
I'm all in favour of this, I rigged up a 'substitute' mapping to 's' that takes a motion (or the selection) and substitutes it with what's in the register WITHOUT replacing what's in the register.

I think it's a good idea to use P in visual mode for this.
Also, the easier we can make things like Yankring, the better.

**Comment by davidv171** [comment]
Could anyone take a look at my PR and tell me if I'm on the right path? Is this even still a bug to be fixed?

**Comment by wsdjeg** [comment]
Backward compatibility is a fundamental principle of project development. We should not change the behavior of `v_P` in neovim.

**Comment by davidv171** [comment]
So the issue should either be closed, or discussed(this is 5 years old). Personally I don't think current behaviour makes much sense and it frustrates me on a daily basis. The operation has no reason to override the default register, especially with d -> p achieving this as well.

**Comment by cparadis6191** [comment]
Personally, I have come to rely on this behavior and it is exceptionally useful for exchanging text. It's frequently used in some of my editing patterns.

Take this example:

`int foo = foobar(bar, buzz, zazz);`

If I need to switch buzz and zazz with each other I simply select and yank buzz, select zazz and put, select buzz and put. The unnamed register getting changed during v_p is a very useful feature.

> The operation has no reason to override the default register, especially with d -> p achieving this as well.

d -> p does not achieve the same thing with either the old or new behavior.

I think a subtle thing here is that the selected text that is being replaced *is* being deleted. Every normal mode command I can think of that deletes text also puts it into a register. d, D, c, C, s, S, R, x, and probably some more all put the deleted text into the unnamed register. I can't think of a single normal mode command that deletes text that *doesn't* put it in the unnamed register. Putting deleted text into the black home register is always an explicit action as far as I can tell and that's a good thing.

If this is a pain point for people something should probably be done but this solution would annoy myself and a lot of other people.

A new option with the default being the old behavior would probably be better. Or a way to specify the register to put the deleted text into for v_p.

Does a user mapping like `xnoremap p pgvy` not achieve what's being suggested here?

**Comment by Maltimore** [comment]
@cparadis6191 you raise good points, although I think you're missing is the proposal is to map v_P, not v_p, so I think this means that your points don't apply here (?)

**Comment by cparadis6191** [comment]
@Maltimore 

> @cparadis6191 you raise good points, although I think you're missing is the proposal is to map v_P, not v_p, so I think this means that your points don't apply here (?)

Whoops! Yeah, I definitely did. I was reading this a like 1 in the morning and I guess P and p look a little too similar. I think this is a better solution than originally proposed but I still agree with wsdjeg's latest comment about backward compatibility. 

> Backward compatibility is a fundamental principle of project development. We should not change the behavior of `v_P` in neovim.

I do think keeping compatibility with Vim is important. I think adding new or different behavior behind an option is the best way to handle this and changes like it. That would keep Vim purists happy and let Neovim be an almost drop-in replacement and would allow for new improvements to be made without breaking compatibility. Every breaking change like this makes it less likely for a certain crowd of people to adopt Neovim over Vim.

Something like `set noyankonvisualput` with `yankonvisualput` being the default?

**Comment by sullyj3** [comment]
I think programmers are a pretty pragmatic bunch, and most will recognize that an improvement is an improvement. I'd say hardcore vim purists who object to any change in behaviour, no matter how small or well justified, are probably a minority. I don't think it's necessary to hide what seems to be clearly a strict improvement behind an option.

**Comment by davidv171** [comment]
@cparadis6191 Honestly you've changed my mind, and I do think hiding this behind an option is definitely what should be done. I'm really glad we finally got a discussion going. 

> I think programmers are a pretty pragmatic bunch, and most will recognize that an improvement is an improvement. I'd say hardcore vim purists who object to any change in behaviour, no matter how small or well justified, are probably a minority. I don't think it's necessary to hide what seems to be clearly a strict improvement behind an option.

I definitely agree if we could unanimously agree on this, however the problem here is that we cannot seem to agree if this is an improvement or not. I've since gotten really busy with real life so the PR will be on hold for a bit anyway, and I'd appreciate any further discussion on this.

**Comment by cparadis6191** [comment]
@sullyj3 

> what seems to be clearly a strict improvement

The fact that a discussion is happening means that it isn't considered a strict improvement.

The problem with a GitHub issues is that the responses are inherently biased towards the negative. People who like or people who are simply used to the current behavior are not going to go searching for issues like this to comment on. It's the same reason I don't call the fire department every day to tell them that my house _isn't_ on fire. I have no reason to complain. Only the people who dislike this behavior are going to come looking or are going to make a GitHub issue. That means we're not going to have much meaningful discussion in a GitHub issue and we're not actually hearing what the general Vim/Neovim population cares about. I'm only here because I happened to stumble on this while looking for something completely unrelated.

No one goes out of their way to fight for the status quo. They only fight for it when the status quo is challenged. I would put money on the fact that if this change went in there would be a lot of angry comments on an issue like this.

In general, changes should cause as little friction as possible for users and breaking compatibility causes a lot of friction.

**Comment by jamessan** [comment]
> I do think hiding this behind an option is definitely what should be done

Options should be a last resort.  They magnify the test scenarios and code paths because now you have to handle both with and without the option set.

In current code, `p` and `P` do the exact same thing in visual mode.  Therefore, it's a reasonable request to put new behavior behind `P`.  Similarly, since the behavior is the same, it's less likely that people are using `P` instead of `p` in visual mode.

An alternative is to bind the behavior to an unused key in visual mode, but using `P` is attractive because it is already associated with performing a put.

I think either of those options (using `P` or a new binding) is fine.  I do not agree with adding an option.

**Comment by sullyj3** [comment]
> The fact that a discussion is happening means that it isn't considered a strict improvement.

I would agree with this, if it was the case that a single object level argument had actually been raised against the proposal as stated. As it stands, you've argued against changing the behavior of `p`, which I think there's pretty broad agreement with you that change would be a bad idea. Looking through the thread, the only arguments against changing `P` are based on appeals to the desires for the status quo of users who are so far, purely hypothetical. 

I appreciate that the dynamic that you mention about only people who are dissatisfied with the status quo showing up in github issues could possibly exist. However, I guess it doesn't seem plausible to me that a significant proportion of users will be upset by this change, because it's difficult to imagine a common mechanism through which that could occur. The scenario that I can come up with involves something like, the user has remapped `visual{p}` and regularly makes use of `visual{P}` to get the default behavior. This scenario on the face of it seems likely to be pretty unusual. In that particular case, the user is already familiar with mappings, and would have little difficulty remapping `visual{P}` back to what they were used to if its behavior were changed.

So, the cost would be inconveniencing this group who are likely pretty small, who in fact at this stage are purely hypothetical, and will be able to work around the inconvenience with a pretty straightforward mapping. The benefit would be to make a behavior available that fixes an actual concrete, existing annoyance that bothers myself, other people in this thread, and probably many others every time we use this editor. To me, those benefits outweigh the costs easily.

**Comment by justinmk** [comment]
> Backward compatibility is a fundamental principle of project development. We should not change the behavior of `v_P` in neovim.

Back compat is a high priority, but this change is unlikely to break any plugins. 

Locking the issue so that @jamessan 's comment is easy to see, don't need more discussion.
