### ISSUE TITLE
Disabling old filetype detection and enabling new filetype.lua does not work as expected

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#18131]
### Neovim version (nvim -v)

v0.7.0 stable

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

binary release

### How to reproduce the issue

Use the following `mini.vim`:

```
let g:do_filetype_lua = 1
let g:did_load_filetypes = 1
```

Open nvim: `nvim -u mini.vim mini.vim`

Check the filetype: `set ft`

### Expected behavior

filetype should be `vim`

### Actual behavior

filetype is not set.

Note that if we use `let g:did_load_filetypes = 0`, filetype detection will work.

However, in that case, I am not sure if the new filetype.lua mechanism actually works.

Is this a bug or just document typo?

**Comment by jdhao** [comment]
Okay, I checked the code [here](https://github.com/neovim/neovim/blob/master/runtime/filetype.lua#L1). `filetype.lua` checks if the variable `did_load_types` is equal to 0, if not, it will return.

But I think the common practice to disable a certain feature in vim is to set the variable `loaded_xxx` to 1?

**Comment by clason** [comment]
This is by design, in order to allow you to have either 
1. only `filetype.vim`;
2. `filetype.lua` _and_ `filetype.vim`;
3. only `filetype.lua`.

If you feel the documentation is unclear or could be improved, please make a PR.

(In any case, this is only temporary, as `filetype.lua` is intended to become the default at some point.)
