### ISSUE TITLE
Neovim 0.7.0 might break gopls autoimport?

### ISSUE THREAD

**Issue by lucassperez** [neovim/neovim#18239]
### Neovim version (nvim -v)

v0.7.0

### Language server name/version

gopls v0.8.3

### Operating system/version

Fedora 35

### Steps to reproduce using "nvim -u minimal_init.lua"

I made a minimal config with gopls autoimport here:

https://gist.githubusercontent.com/lucassperez/9288ab6f981e03b2d1e7d8fbcd3f7a78/raw/fbb28238f37c1e6b32e661c0aa0a06f847e71c60/minimal_init_golang_autoimport

This config file defines a function named `golangImports` that might be run inside neovim with `:lua golangImports(1000)`, for instance.

### Expected behavior

When I execute the autoimport function, it should import modules that have been used in the file but was not imported.

### Actual behavior

When a module was used but not imported, it throws an error.

![image](https://user-images.githubusercontent.com/60318892/164947780-f61a4259-4f3b-4360-b53b-4fd28c2771db.png)

If modules are not alphabetically ordered, I get the same error, apparently.

When an unused module gets wiped, or imports were correct, its all fine though.

If I go back to neovim 0.6.0 everything works again. I don't know if I'm setting something wrong, I got the `golangImports` function from some video I think, I'm not very knowledgeable on how any of this works :sweat_smile:

Thanks! (:

### Log file

https://gist.github.com/lucassperez/f827fdde8bbedf41f693dd067b8086af

**Comment by fsouza** [comment]
I'm surprise it works some times, it should never work, as you need to pass the offset_encoding to apply_workspace_edit. I guess sometimes gopls is returning a command instead of textedits idk

Also, gotta say, that function isn't quite right. The code below is misleading, it doesn't do what you think:

```lua
  local result = vim.lsp.buf_request_sync(0, 'textDocument/codeAction', params, timeout_ms)
  if not result or next(result) == nil then return end
  local actions = result[1].result
```

It gives the impression that result is a list-like table, but in reality vim.lsp.buf_request_sync returns a map of client_id to result, if you open neovim and load a go file first, gopls will be client id 1, but if you have multiple servers configured and load something else first, gopls will not be the client with id 1 and your function will not do what you want). A more robust  alternative would be something like this (it's still not perfect, it breaks if you run multiple language servers for Go files):

```lua
  local result = vim.lsp.buf_request_sync(0, 'textDocument/codeAction', params, timeout_ms)
  if not result then return end
  local client_id, result = next(result)
  if not client_id then return end
  local client = vim.lsp.get_client_by_id(client_id)
  if not client then return end
  local actions = result.result
```

Then in your call to `vim.lsp.util.apply_workspace_edit`, pass `client.offset_encoding` as the second parameter and you'll be all set:

```lua
      vim.lsp.buf.execute_command(action.command, client.offset_encoding)
```

Either way, this is more of a question than an issue with neovim x)

**Comment by justinmk** [comment]
Issue tracker is not a plugin support channel.

**Comment by lucassperez** [comment]
Thanks a bunch, this actually solves it! Like I said, I never really understood the snippet I got, and it had an issue with it, which often times is the case with copy paste stuff.

Sorry about posting here, but when the only thing one upgraded was neovim and suddenly it breaks and the neovim issues page itself has a template for LSP bugs that even ask what language server one is using, it seems like an easy mistake to make, but I definitely learned it now.
