### ISSUE TITLE
vim.o supports Lua tables

### ISSUE THREAD

**Issue by binyomen** [neovim/neovim#18246]
### Feature already in Vim?

No

### Feature description

There's currently a feature split between getting/setting options with `vim.opt`/`vim.opt_local`/`vim.opt_global` and `vim.o`/`vim.go`/`vim.bo`/`vim.wo`. The former support setting array, map, and set options using Lua tables but don't support setting options for specific buffers or windows. The latter support setting options for specific buffers or windows (by indexing with buffer/window number) but don't support using Lua tables.

My proposal is to add `vim.opt_buffer` and `vim.opt_window` APIs. These can be used similarly to `vim.bo` and `vim.wo` in that they can be indexed by buffer or window number. They will however allow getting/setting options using Lua tables. So, for example, you could set 'cinkeys' by doing `vim.opt_buffer[5].cinkeys = {'0{', '0}'}` or 'colorcolumn' by doing `vim.opt_window[3].colorcolumn = {80, 120}`. You'd also be able to use `:append` etc.

I opted (lol) for adding `vim.opt_buffer` and `vim.opt_window` rather than changing `vim.bo` and `vim.wo` to use Lua tables since changing `vim.bo` and `vim.wo` would be a breaking change.

If this is something people think should be added, I'd be happy to do the work.

**Comment by justinmk** [comment]
> My proposal is to add `vim.opt_buffer` and `vim.opt_window` APIs.

Please, no more. Let's fix what we have.

We need to step back and rethink all of the options wrappers. We currently have three or four different options wrappers that all don't work like users expect them to work.

Adding even more options wrappers sounds very unappealing.

1. We need to fix `vim.o`, `vim.bo`, `vim.wo` so that they work like the Vimscript equivalents. 
    - This implies, also, fixing `nvim_set_option` and related functions. It doesn't matter if it's "breaking change". We need to fix it. The current behavior sucks.
3. We need to deprecate and remove `vim.opt`, it should not have been added.

**Comment by gpanders** [comment]
>We need to fix vim.o, vim.bo, vim.wo so that they work like the Vimscript equivalents.
This implies, also, fixing nvim_set_option and related functions. It doesn't matter if it's "breaking change". We need to fix it. The current behavior sucks.

`nvim_set_option_value` was added for this purpose. It is functionally equivalent to `:set`, `:setglobal`, and `:setlocal` (depending on arguments).

**Comment by justinmk** [comment]
> This is what `vim.o` uses under the hood.

Nice, was that a change in the last year or so? Then it sounds like the only missing part is to add "Lua table support" to the `vim.o` family?

**Comment by gpanders** [comment]
> > This is what `vim.o` uses under the hood.
> 
> Nice, was that a change in the last year or so? 

[Yes](https://github.com/neovim/neovim/pull/15996).

**Comment by bfredl** [comment]
we could make `vim.o` just behave like `vim.opt` and deprecate the latter. people did not like that when I suggested it before 0.5 release, however.

**Comment by clason** [comment]
The (sole) point of `vim.opt` is as a convenience layer on top of `vim.o` to offer a replacement of the `let foo^=` etc. append/prepend functionality from Vimscript for list options.

**Comment by justinmk** [comment]
> The (sole) point of `vim.opt` is as a convenience layer on top of `vim.o` to
> offer a replacement of the `let foo^=` etc. append/prepend/remove(!)
> functionality from Vimscript for list options.

Five pages of documentation for working with options, on top of the existing
options documentation, is not convenient :)

The whole purpose of a "Lua table interface" is to work with tables. But
`vim.opt` doesn't work with regular Lua tables, it works with special objects
and requires special functions. Appending/prepending to tables shouldn't require
a special function. If we can't do that then what did we gain over `vim.cmd('set foo += ...')` ?

I literally don't understand what the use case for `vim.opt` is. A Lua table interface is useful _if it works with vanilla tables_. If the only thing we gained was that `vim.cmd('set foo+=...')` now looks like `vim.opt.foo:append(...)`, this serves no purpose. The point of a Lua table interface is to be composable with vanilla Lua table-manipulation.

It's also not great that `vim.opt.isfname` is separate from `vim.o.isfname`. There should be--conceptually--_one_ options collection, not several parallel collections.

Here's a potential interface that shows how plain Lua tables could be returned, modified, and assigned:

```lua
-- Get
local isfname = vim.o.get(vim.o.isfname)
-- Set
vim.o.set(vim.o.isfname, {'^,', 'a', 'b', 'c'})
-- Append. (Note: vim.add() is fictional, we may need new "functional" utilities.)
vim.o.set(vim.o.isfname, vim.add(isfname, 'e'))
-- Prepend. (Note: vim.prepend() is fictional, we may need new "functional" utilities.)
vim.o.set(vim.o.isfname, vim.prepend(isfname, 'e'))
-- Remove last item. Note: vim.pop() is fictional, we may need new "functional" utilities.
vim.o.set(vim.o.isfname, vim.pop(isfname))
```

**Comment by binyomen** [comment]
This all makes sense to me. I wasn't sure why the `vim.o` and `vim.opt` both existed anyway.

I'm just putting a table here to organize my thoughts on this. Basically a goal would be to have two methods of getting/setting options from Lua: the `vim.api.*` functions and the `vim.*o` objects which are just Lua wrappers around them. Does this seem right?

| API                                                | Lua      |
| ---                                                | ---      |
| `nvim_get_option_value(option, {})`                | `vim.o`  |
| `nvim_get_option_value(option, {scope = 'local'})  | ?????    |
| `nvim_get_option_value(option, {scope = 'global'}) | `vim.go` |
| `nvim_buf_get_option`                              | `vim.bo` |
| `nvim_win_get_option`                              | `vim.wo` |

I guess this also raises the question: would we want a Lua equivalent to `nvim_get_option_value` with local scope? Something like `vim.lo`? I'm not sure if that really makes sense with `vim.bo` or `vim.wo`, though, which is maybe way this wasn't implemented before. I guess it could be nice as a convenience similar to `:setlocal`, but I don't have any strong feelings either way.

**Comment by binyomen** [comment]
> The whole purpose of a "Lua table interface" is to work with tables. But `vim.opt` doesn't work with regular Lua tables, it works with special objects and requires special functions. Appending/prepending to tables shouldn't require a special function. If we can't do that then what did we gain over `vim.cmd('set foo += ...')` ?

I definitely agree with this. I've been thinking about this a bit, and so I'll add the API I was thinking of here as well:

```lua
-- Get
local isfname = vim.o.isfname
-- Set
vim.o.isfname = {'^,', 'a', 'b', 'c'}
-- Append
vim.o.isfname = vim.list_extend(vim.o.isfname, {'e'})
-- Prepend
vim.o.isfname = vim.list_prepend(vim.o.isfname, 'e')
-- Remove
vim.o.isfname = vim.list_remove(vim.o.isfname, 'a')
```

The `vim.list_*` APIs don't currently exist (except for `vim.list_extend`), but I put those there as standins for potential future APIs/existing APIs with some modification to my code above.

**Comment by justinmk** [comment]
> I definitely agree with this. I've been thinking about this a bit, and so I'll add the API I was thinking of here as well:

Sure, if we can use `=` for assignment instead of `vim.o.set()` that's even better. I've updated my previous comment and will hide yours to avoid cluttering the discussion.

**Comment by binyomen** [comment]
@justinmk  do we still need the `vim.o.get` in your example above? I think that could just be direct assignment `local isfname = vim.o.isfname`, right?

**Comment by justinmk** [comment]
> do we still need the `vim.o.get` in your example above? I think that could just be direct assignment `local isfname = vim.o.isfname`, right?

Hopefully not. The finer details of the API don't matter too much here, that will get worked out in the PR.

What we need here is general 👍  on the concept. Waiting to hear any technical issues or objections.

**Comment by clason** [comment]
> Note: vim.add() is fictional, we may need new "functional" utilities.)

Lua already has `table.insert(table, pos, value)` (or simply `table[#table+1]=value` for appending) and `table.remove(table, pos)`. 

What's missing is a convenience function for inserting multiple values at the same time.

**Comment by justinmk** [comment]
> Lua already has `table.insert(table, pos, value)` (or simply `table[#table+1]=value` for appending)

But those don't work as expressions, e.g. table.insert() returns nil.

> The technical issue (and what prompted the creation of `vim.opt` IIRC) is that unlike comma-separated strings, dict-like tables do not have a guaranteed ordering in Lua, so things like "append" or "prepend" are... iffy.

We can add `vim.o.append()` if that's really needed. But it doesn't require an entirely separate namespace (`vim.o` vs `vim.opt`). And I'm not actually seeing a strong reason why all of this plumbing was added just to avoid `vim.cmd('set foo+=...')`.

**Comment by tjdevries** [comment]
> The (sole) point of vim.opt is as a convenience layer on top of vim.o to offer a replacement of the let foo^= etc. append/prepend/remove(!) functionality from Vimscript for list options.

Well not exactly the sole point. It also adds the ability to use lua tables (as map-type and array-type) to interact with options since those are simpler, and to retrieve those from nvim in those same types as well. (so instead of getting a raw string repr, you get the effective table representation).

```lua
-- Get
local isfname = vim.o.isfname  -- Or vim.o.get(vim.o.isfname) if necesary
-- Set
vim.o.isfname = {'^,', 'a', 'b', 'c'}
-- ...
```

This will be a breaking change (and would have been a breaking change from before as well). We can add `vim.o.get()` but it feels weird to have that live on `vim.o`. The reason this would be breaking is because the expectation is that `vim.o` returns the string representation of vim options. Perhaps instead it would be better to have `vim.opt.NAME:raw()` instead or similar, to get the string value if it was required for something.

Beyond that, I think people will often make the mistake of doing:

```lua
lua isfname = vim.o.isfname
table.insert(isfname, 'e')
```

and then be confused why nothing is changing (because it looks and _is_ just a lua table. But the underlying representation is not that same lua table, so it will have no effect).

Additionally, to know _how_ to add values to different options, you often need to know associated metadata about which option it is (at least for some list-type and map-type tables), so you can't just call `add(...)` on at table, you also need to at least know the option name (which is why I used metatables, so I could track the information between subsequent lua calls).

----

Additionally, can you explain how we have only "half-implement"-ed `set`? I think (besides the one open issue) replicated the semantics of `set` in a way that people are used to and allows easy conversion from vimscript -> lua. G

**Comment by justinmk** [comment]
> It also adds the ability to use lua tables (as map-type and array-type) to interact with options since those are simpler

Simpler how? It's a new interface, and it doesn't avoid needing to know how Vim options work, so the cognitive burden is strictly additive.

> Perhaps instead it would be better to have `vim.opt.NAME:raw()` instead or similar, to get the string value if it was required for something.

More stuff on `vim.opt` is the opposite of where we need to go. The goal is to have fewer concepts and to remove a redundant interface.

> Beyond that, I think people will often make the mistake of doing:
> 
> ```lua
> lua isfname = vim.o.isfname
> table.insert(isfname, 'e')
> ```

In user configs, there's just no point in this kind of code. Tables would make if they're being programmatically manipulated, and work with vanilla Lua mechanisms.

> so you can't just call `add(...)` on at table, you also need to at least know the option name (which is why I used metatables

Yes, and that defeats the purpose of exposing Vim options as tables. These special objects are not composable with vanilla Lua mechanisms. It's another DSL, an uncanny valley with its own quirks vs `vim.cmd('set foo+=...')`.

**Comment by tjdevries** [comment]
It's not only for setting values, it's also for reading values.

`vim.opt` returns the value in a way that is easy to make sense of and use programmatically. If it's a set of items, it returns it as a map style table, so you can just check if something is included in the set of arguments. If it's a list, it will return it in an array style table, so that you can iterate over the items. This greatly reduces complexity when interacting with options because you don't have to figure out which way to parse the strings to interact with option.

I would rather see `vim.o` deprecated than `vim.opt` personally because I think `vim.opt` provides much better ergonomics for users and for plugin authors, and allows for writing and reading code that deals with options much more explicitly and without having to learn the vimscript DSL.

Just a random example from searching for mentions of `vim.opt_local`:

https://sourcegraph.com/github.com/Furkanzmc/zettelkasten.nvim/-/blob/ftplugin/markdown.lua

I think basically anyone can read this and understand what is happening top-to-bottom. I don't think reading `set` DSL and worrying about escaping spaces, special characters, illegal options and string encoding problems is "just as easy" or that this is strictly additive.

NOTE: I would prefer _not_ to add `vim.opt.NAME:raw()` because I think the raw string values are useless. I was jusst proposing it because it would allow `vim.o` to become useless and we could deprecate it.

You still didn't answer this:

> Additionally, can you explain how we have only "half-implement"-ed set? I think (besides the one open issue) replicated the semantics of set in a way that people are used to and allows easy conversion from vimscript -> lua.


As for real world examples, it might be worthwhile to take some time to scroll through the thousands of usages of vim.opt and see why people are preferring to use that over `vim.o` or `vim.cmd [[set ...]]`. 

https://sourcegraph.com/search?q=context:global+vim.opt+lang:lua+count:2000&patternType=literal

I don't think saying "just use set" is a good response to working with vim options.

(not saying vim.opt is the perfect way, or that we couldn't deprecate it in favor of improvements to vim.o, but I super disagree with your original statemenets about vim.cmd. I would like to see us have a simple and straightfoward way of working with options, but that must include interacting with them instead of using vim.cmd)

**Comment by tjdevries** [comment]
(for example, how would `vim.add` in your mind work with `listchars` for example)

**Comment by justinmk** [comment]
> vim.opt returns the value in a way that is easy to make sense of and use programmatically
> ... I don't think reading `set` DSL and worrying about escaping spaces, special characters,

Absolutely. Exposing _structure_ is a great way for Nvim to add value. But we can do that without adding special interfaces or opaque objects. Options can be modeled as plain Lua tables, and operations can be functions that act on the `vim.o` family.

> As for real world examples, it might be worthwhile to take some time to scroll through the thousands of usages of vim.opt and see why people are preferring to use that over `vim.o` or `vim.cmd [[set ...]]`.
> 
> https://sourcegraph.com/search?q=context:global+vim.opt+lang:lua+count:2000&patternType=literal

In those results there is a lot of this kind of thing, which is verbose enough that a non-OOP approach wouldn't look much different:

    vim.opt.rtp:remove(vim.call("stdpath", "config"))
    vim.opt.rtp:remove(join_paths(vim.call("stdpath", "config"), "after"))
    vim.opt.rtp:prepend(self.config_dir)
    vim.opt.rtp:append(join_paths(self.config_dir, "after"))

The results also have plenty of things like `errorformat = "%f:%l: %m"`, which drives the point home: vim's DSLs are part of using vim. 

> You still didn't answer this:
> 
> > Additionally, can you explain how we have only "half-implement"-ed set?

1. missing support for the complex options (where structure is most needed): guifont, guicursor, signcolumn statusline, tabline
2. doesn't work with plain Lua tables
3. doubled the number of Lua options interfaces.


> (for example, how would `vim.add` in your mind work with `listchars` for example)

'listchars' is modeled as a nested dict, so we need functions similar to `vim.tbl_get()` that make it very ergonomic to work with nested structures.

https://github.com/neovim/neovim/issues/18246#issuecomment-1107931182

**Comment by justinmk** [comment]
Continuing at https://github.com/neovim/neovim/issues/20107
