### ISSUE TITLE
Different font sizes for different buffers

### ISSUE THREAD

**Issue by amitkot** [neovim/neovim#18285]
### Feature already in Vim?

No

### Feature description

I use NeoVim for Flutter app development (using [flutter-tools.nvim](https://github.com/akinsho/flutter-tools.nvim))  and use a buffer for displaying the dev log.

The requirements from a log buffer are different than those of the code buffers, namely, I want to use a much smaller font.

This is an important feature for using NeoVim as an IDE.

**Comment by zeertzjq** [comment]
I guess this is already supported by ext_multigrid?

**Comment by bfredl** [comment]
yes, use `nvim_ui_try_resize_grid()` on a per-window grid.

**Comment by amitkot** [comment]
@bfredl could you please give an example of how I can call `nvim_ui_try_resize_grid()` to change the font size? 
Looking at the help page, I see how I can change the dimension of the grid but not how to change the font size.

**Comment by bfredl** [comment]
@amitkot well, indirectly. font has to be managed by UI itself by now. so you need to calculate `(grid size in pixels) / (font size in pixels)` on the UI side, and inform nvim how many cells you are able to render.

**Comment by supermacro** [comment]
Out of curiosity, is it possible to increase the font size (or even change the font entirely) on a single buffer?

e.g. imagine I'm writing markdown. Could the font size change depending on the number of pound (#) symbols I use in order to denote heading size (e.g. # -> h1 tag / large, ..., #### -> h4 tag / small).
