### ISSUE TITLE
use "git subtree" instead of downloading deps

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#1832]
For non-CI builds, instead of downloading deps from URLs, is there any reason not to use [git subtree](http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/)? 

Benefits:

- makes `git bisect` significantly more useful
- may avoid the need for separate repos like https://github.com/neovim/libtickit

**Comment by jszakmeister** [comment]
I don't think using `git subtree` is going to help us here.

The current problem with bisecting is because some things weren't/aren't nailed down.  Pegging those things would improve bisecting just the same.  Plus, there are some other bits, like the python client, that is still not likely to be nailed down, and changes between all these things can still make bisecting a headache.

Besides that, we bloat the repository with other folks code (and history, if you elect to do it that way).  But in the end, we aren't going to stay on the bleeding edge forever (or at least I hope we don't) and once stable versions of our dependencies are easily available, the need for having them is far less necessary.

Mental exercise: what would 10 years of constantly updating dependencies do to us? :-)

**Comment by rainerborene** [comment]
What is the problem of downloading deps from URLs?

**Comment by jszakmeister** [comment]
@rainerborene One problem is that they go offline sometimes.  Another is that we didn't have the pegged to specific versions and that made it hard to `git bisect` to find the change that caused some issue.

**Comment by justinmk** [comment]
Ok. It could be argued that the third-party commit hashes are enough, in a DVCS sense, and the subtree is redundant. I feel a bit bad about the bandwidth while bisecting, but other than that there seems to be no strong argument in favor of subtree.

**Comment by mikaelj** [comment]
Also, git subtree is a nightmare once you start merging back and forth and
don't remember to use --squash. At my company we've been using subtree but
are going to switch to submodules instead. (Which don't help you - more as
a warning.)

-- Micke
