### ISSUE TITLE
New LSP capability system broke renames without prepare support

### ISSUE THREAD

**Issue by entropitor** [neovim/neovim#18427]
### Neovim version (nvim -v)

v0.8.0-dev+1584-g3ec93ca92

### Vim (not Nvim) behaves the same?

/

### Operating system/version

/

### Terminal name/version

/

### $TERM environment variable

/

### Installation

brew

### How to reproduce the issue

Try to rename a symbol using e.g. typescript-language-server which supports rename but not `prepareRename`

### Expected behavior

The `prepareRename` is skipped and the `<c-word>` default is used instead (like it was before https://github.com/neovim/neovim/issues/14090#issuecomment-1113956767)

### Actual behavior

A failure when trying to rename because there is no client supporting `prepareRename` so the following request fails:

```lua
request('textDocument/prepareRename', util.make_position_params(), prepare_rename)
```

**Comment by jackfranklin** [comment]
I have no prior experience contributing to NeoVim but if the fix is a case of checking if the server supports `prepareRename`, and only running that block of code in that case, I'm happy to try to contribute a PR and take guidance from more experienced folks :)

**Comment by muniter** [comment]
> I have no prior experience contributing to NeoVim but if the fix is a case of checking if the server supports `prepareRename`, and only running that block of code in that case, I'm happy to try to contribute a PR and take guidance from more experienced folks :)

Give it a try! 👍

**Comment by mjlbach** [comment]
I just wanted to provide some light guidance for someone who tries to fix this. The previous behavior prior to the capabilities change was not the appropriate fix, and in fact had some issues.

The appropriate fix, is for each server, to check if it supports prepareRename (this can be done by examining server capabilities) and only firing off the request to do prepareRename for servers that do, otherwise defaulting to c-word. This is made slightly more complicated by the fact that prepareRename is itself a request, so the c-word will need to be cached for servers that do not support prepareRename and sent with the other rename requests.

Should be a relatively simple PR.

**Comment by mfussenegger** [comment]
Should get fixed with https://github.com/neovim/neovim/pull/18441
