### ISSUE TITLE
architectural repair of vim

### ISSUE THREAD

**Issue by Konfekt** [neovim/neovim#1859]
Hello,

In case this is not know to the Neovim community, there is a paper "Architectural Repair of Open Source Software" that suggests redistrubtion of the Vim source code on a file level (diagrammatically shown on page 6) so that the naming of files reflects its architecture better, see 

http://www.eecs.yorku.ca/course_archive/2003-04/F/6431/ResearchPapers/Tran.pdf

How outsiders grasp the architecture of (Neo)VIM best might is helpful to incite contributions to  NeoVim. I have not kept track of all internal restructurings of NeoVim starting from the Vim code base, so I am not sure how much of their advice still applies.

**Comment by justinmk** [comment]
>Next, we attempted to repair the Utility subsystem. Analyzing the unexpected dependencies entering Utility, we noticed that many of the dependencies ended at the modules named misc1.c and misc2.c.

Haha.

**Comment by justinmk** [comment]
I read the paper. @tarruda has intuitively reached an even better topology, by decoupling the presentation layer, introducing a provider layer, and routing everything through a message loop. 

Also funny that we broke out `memory.c` as suggested in the paper. I wonder if the authors would like to analyze neovim. 

`vim_stdlib.c` is a decent suggestion for the `misc.c` stragglers, we might use that.

**Comment by Konfekt** [comment]
I'd be curious about what they'd to say about NeoVim. 

Can you give a pointer where these architectural/topological questions are discussed here and give a hint what the provider layer and message loop achieve?

**Comment by justinmk** [comment]
>  where these architectural/topological questions are discussed here 

They weren't discussed at length. That's why I said "intuitively". The authors of the referenced paper are invited to analyze nvim as they did with vim. In particular, we will soon be totally rid of misc1.c and misc2.c as recommended by the paper.

> and give a hint what the provider layer and message loop achieve?

Providers allow implementation of features without coupling. Message loop allows queuing of asynchronous messages, and communication without coupling.

**Comment by tarruda** [comment]
> Providers allow implementation of features without coupling. Message loop allows queuing of asynchronous messages, and communication without coupling.

Any interactive program(including Vim), has a message loop that drives changes to the program state(In Vim/Neovim context, the message loop can span across multiple function calls). The difference between Neovim and Vim are what kinds of events result in messages being delivered to the loop.

Vim message loop is largely driven by keyboard/mouse input, and is one of the reasons Vim does not accept asynchronous communication from other programs.

Neovim uses libuv to implement its message loop to accept other sources of events:

- msgpack-rpc requests
- job output
- signals

Since libuv is at the core of Neovim message loop, we can easily add support to other libuv features such as communication from other threads or timers.

**Comment by tarruda** [comment]
As for the provider infrastructure, I think it still has a lot of room for improvement. For example, if functions/ex commands are refactored to use a dynamic hash table for storage, nothing stop us from implementing things such as job control, python support or msgpack-rpc as plugins(that can be linked at either build time or at run time as native dynamic libraries). This is something I plan to have a look after the first release.

**Comment by philix** [comment]
Reminds me of #209. I remember splitting `structs.h` although I think `structs.h` was generated during the fork. Disentangling the declarations without adding too many includes in all the files was very tricky.

I always thought about how one could perform this kind of analysis presented in the paper and make these nice dependency graphs to figure out how to reduce the coupling. Thanks @Konfekt.

It's encouraging to see that nvim is in a good path towards a better topology.
