### ISSUE TITLE
LSP: supports_method always return true

### ISSUE THREAD

**Issue by pedro757** [neovim/neovim#18686]
### Neovim version (nvim -v)

NVIM v0.8.0-dev+265-g12f45fd69

### Language server name/version

It happens with every LS but I use typescript-language-server@0.10.0

### Operating system/version

arch

### Steps to reproduce using "nvim -u minimal_init.lua"

```lua
local nvim_lsp = require"lspconfig"

local on_attach = function(client, bufnr)
  print(client.supports_method("blabla"))
end

nvim_lsp.tsserver.setup {
  on_attach = on_attach
}
```

### Expected behavior

It should verify, **blabla** is not even a **LSP-Method** at least it should return false

### Actual behavior

This function always returns true no matter the input `client.supports_method("blabla")`

**Comment by fsouza** [comment]
At least initially, this was intentional: the idea is that if you're using a method for which neovim doesn't know the required capability, it assumes that the method is supported. It's a fail open principle: since neovim doesn't know the method, it can't really tell whether the server supports it or not, and the function returns true to allow the call to go through in buf_request.

Definitely a limitation of using a boolean though.
