### ISSUE TITLE
Add default mappings from `C-_` to undo in macOS

### ISSUE THREAD

**Issue by andmis** [neovim/neovim#18746]
- macOS users use ⌘Z as their undo key almost everywhere. It would be nice if the same keyboard shortcut worked in terminal applications, including Neovim.
- `C-_` already acts as an undo key in Readline contexts (notably, every major shell). So it makes sense to standardize on `C-_` being "the undo key" in terminal contexts, the way ⌘Z is "the undo key" in macOS GUI contexts (by convention).
- Then terminal emulators can generate `C-_` when the user strikes ⌘Z.
- Then, if we add default mappings from `C-_` to undo in Neovim, then ⌘Z will work as an undo key by default in nearly all contexts in macOS, which is great for users.

---

A longer write-up is at https://github.com/linty-org/proposals/issues/1.

Obviously this would be a lot more compelling for Neovim if the terminal emulator maintainers agree to this proposal, and vice versa, so I'd like to just open the conversation.

**Comment by justinmk** [comment]
please copy the part that is relevant to Neovim, here. That helps with search, and also avoids N people needing to distill a very long discussion N times.

**Comment by andmis** [comment]
> please copy the part that is relevant to Neovim, here. That helps with search, and also avoids N people needing to distill a very long discussion N times.

I updated the issue with a summary, how is that?

**Comment by justinmk** [comment]
No objection, if this doesn't clobber other Nvim default mappings.

We intentionally avoid cornball ideas like "source `mswin.vim` by default on Windows", because it _changes_ Vi/Vim defaults, which is confusing for people who expect a consistent experience on all platforms--the target audience for Neovim...

> Then terminal emulators can generate `C-_` when the user strikes ⌘Z.

We should probably also set `<D-c>`, `<D-z>`, `<D-x>`, `<D-v>` now that we have https://github.com/neovim/neovim/pull/17771 https://github.com/neovim/neovim/issues/5916

**Comment by zeertzjq** [comment]
> We should probably also set `<D-c>`, `<D-z>`, `<D-x>`, `<D-v>` now that we have #17771 #5916

libtermkey does not support `<D-` modifier.
