### ISSUE TITLE
Copying using middle mouse click after toggleing set number and set nonumber causes 4 extra spaces

### ISSUE THREAD

**Issue by VelocityDv** [neovim/neovim#18844]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

don't know

### Operating system/version

ArchLinux

### Terminal name/version

xterm

### $TERM environment variable

xterm-256color

### Installation

Pacman

### How to reproduce the issue

1. open neovim using `nvim -u none`
2. type some text on multiple lines
3. turn on set number using `set number`
4. turn off set number using 'set nonumber'
5. select and copy using middle mouse button
6. lines will magically have 4 extra spaces at the end. 

### Expected behavior

No magical extra spaces at after turning `set nonumber` 

### Actual behavior

Copy texts with extra magical 4 spaces at the end.

**Comment by rktjmp** [comment]
I am assuming this:

> select and copy using middle mouse button

Is implicitly "select with left mouse button, enter insert mode, press middle mouse button to paste selected text", otherwise I think this would depend on specific wm configuration.

Can reproduce in xterm, not reproducible in Alacritty or Wezterm. "selection accuracy" does not impact the result, you can broadly select the entire last line and a


```
λ xterm -v
XTerm(372)
```

**Comment by justinmk** [comment]
duplicate https://github.com/neovim/neovim/issues/18564
