### ISSUE TITLE
Incorrect indentation for javascript inside html

### ISSUE THREAD

**Issue by RealSaltyFish** [neovim/neovim#18865]
### Neovim version (nvim -v)

0.7.0

### Vim (not Nvim) behaves the same?

yes, vim 8.2.5046

### Operating system/version

Arch Linux

### Terminal name/version

tmux 3.2a

### $TERM environment variable

screen-256color

### Installation

pacman

### How to reproduce the issue

put the following text in `test.html`
```html
<script>
	function foo() {
		bar()
	}
</script>
```
nvim --clean test.html
press =G to format the file

### Expected behavior

nothing is changed

### Actual behavior

indentation is changed to:
```html
<script>
	function foo() {
			bar()
		}
</script>

```

**Comment by zeertzjq** [comment]
https://github.com/vim/vim/issues/8997

**Comment by RealSaltyFish** [comment]
> [vim/vim#8997](https://github.com/vim/vim/issues/8997)

I was able to find a workaround and posted it there. It works fine for me, but I'm not sure if it could break things.

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We don't track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker. The issue will go away as soon as we merge the relevant runtime update from Vim.

Syntax plugins (e.g. for ruby/java/YAML) are maintained by the maintainer listed at the top of the plugin file. Please report to that person, or to https://github.com/vim/vim. Thanks!
