### ISSUE TITLE
Stable Ubuntu PPA repository doesn't contain 0.7.0 yet

### ISSUE THREAD

**Issue by JelteF** [neovim/neovim#18963]
### Feature already in Vim?

No

### Feature description

I get neovim through the official neovim stable ubuntu PPA, but it doesn't have the 0.7.0 release yet even though it's been out for ~2 months.

@jamessan, it seems you uploaded the previous packages there

**Comment by jamessan** [comment]
This isn't a bug tracker for the PPA.  That's an independent effort, so I'm going to close this bug.

That being said, I'm waiting on 0.7.1, since 0.7.0 had issues that made it fail when building the Debian packaging (as is usually the case when the PPA is outdated).

**Comment by lucc** [comment]
@jamessan sorry to hijack this conversation but it looks like the bug tracker in launchpad is not used an there are no links configured in the PPA for issue reporting apart from the "description" at https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable which points here for issues.

You mentioned waiting for 0.7.1, as 0.7.2 is now out, maybe it is possible to make a new release on the PPA.  Also might it be able to update the description or config on the PPA to announce some more meaningful location to report issues with the PPA specifically?

**Comment by jamessan** [comment]
> You mentioned waiting for 0.7.1, as 0.7.2 is now out, maybe it is possible to make a new release on the PPA.

As the first line in the description says, the stable PPA is backported from Debian.  Neovim 0.7.2 just today finally made it to Debian testing, so now it's in my queue to propagate to the PPA.

> Also might it be able to update the description or config on the PPA to announce some more meaningful location to report issues with the PPA specifically?

There aren't meaningful issues to report about the PPA.  If there's an issue in Neovim, then it should be reported here.  Otherwise, people just need patience.  The point of the stable PPA is to have qualified versions of the stable release.  That takes time.
