### ISSUE TITLE
Remove 'edcompatible'

### ISSUE THREAD

**Issue by Grimy** [neovim/neovim#1902]
When this option is on, the `g` and `c` substitute-flags are remembered globally, and toggled whenever they are given. For example:

    :set edcompatible
    :s/foo/bar/c     " ask confirmation
    :s/bar/baz/      " ask confirmation
    :s/baz/foo/c     " do not ask

This is as stupid as it sounds. The doc actually discourages setting this option. I think we should remove it entirely. We could make `set noedcompatible` a noop like we did for `set nocompatible`; since `edcompatible` is used much less than `compatible`, I’m not sure that’s necessary.

**Comment by Pyrohh** [comment]
The majority of removed options so far have been completely removed, as opposed to being made no-ops (cp & nocp being one exception). It should be fine to remove it completely (except a stub in the docs), because as you said, the docs discourage its usage. We might want to wait on some more opinions though, as I'm too keen on removing things.

**Comment by Pyrohh** [comment]
#1911
