### ISSUE TITLE
Registers for clipboard missing

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#1908]
If I do `:registers`, there's no trace of `+` or `*`.
Also, If I do `:put +`, I get `E850: Invalid register name`.

I don' think we meant this when we removed code for clipboard support. Did we...?

**Comment by aktau** [comment]
I believe the clipboard/registers system, especially as it pertains to interacting with external clipboards (via providers), could do with a makeover. Also to restore compatibility with the Vim way of handling things.

As an aside: sadly, I don't think we'll reach Vim-levels of efficiency there with the current approach. Especially on X11, Vim uses the selection ownership mechanisms. An alternative would be to write an `os_clipboard.c`, though I'm not sure if that's entirely necessary. The slowness of `]p` in nvim really bothers me (https://github.com/tpope/vim-unimpaired/issues/89), own issue: #1690.

Ping @fmoralesc @bfredl because I think you might be interested in clipboard business, from commit and comment history :).

**Comment by justinmk** [comment]
Definitely a bug

**Comment by justinmk** [comment]
> could do with a makeover ... `os_clipboard.c`

I don't know what you mean exactly, but I think we can achieve near-parity with Vim (and less confusion resulting from "do I have this feature or not") with the provider approach. There is work to be done for sure, but that's unavoidable in any case.

> Especially on X11, Vim uses the selection ownership mechanisms

We can modify https://github.com/kfish/xsel to support special targets (and bundle it if needed).

> The slowness of `]p` in nvim really bothers me

Since it's my job to ask dumb questions, why can't we prefetch the clipboard (using an async job) on focus/cursormoved? Then the shell cost won't be noticed by the user. Furthermore, can't we cache the clipboard value so repeated `]p` is fast?

**Comment by bfredl** [comment]
Related to the discussion in #1288. A first step would be that the vimscript provider implements a concept of ownership. At least on X11, it could run `xsel` (or @fmoralesc improved utility) as a job, and check if we still own the clipboard by checking if the job is still running, and then use a cached value in the provider (I tried to do this, but there is some improvements to job infrastructure needed)
 Another solution, closer to `vim`, would be to reintroduce ownership in the provider infrastructure itself. This would mean reintroduce separate STAR/PLUS registers (+ a flag for each if this instance "owns" it). Then, the provider, some time after a clipboard_set, should notify `nvim` that we _lost_ ownership of this clipboard. (could be done in a job exit Autocommand) This means the provider will  be involved much less when `clipboard=unnamed` and just using the unnamed register internally.

**Comment by aktau** [comment]
> I don't know what you mean exactly, but I think we can achieve near-parity with Vim (and less confusion resulting from "do I have this feature or not") with the provider approach. There is work to be done for sure, but that's unavoidable in any case.

You are right of course, the provider approach is far slower but also far more flexible. I don't advocate not using it anymore before we can see whether we can fix the issues that plague the nvim system clipboard integration now.

> Since it's my job to ask dumb questions, why can't we prefetch the clipboard (using an async job) on focus/cursormoved? Then the shell cost won't be noticed by the user. 

Well, it's difficult to predict what the windowing system of the system we're running on will do (or will allow). Let's take Linux/X11 as an example. There are applications that change the cut/select/... buffers entirely in the background (xcutsel, ...). They don't need to gain focus to start doing that. I suspect it would be madness to try to detect this. I've thought about it. I'd love to be proven wrong though.

The only way that stands out as "watertight" to me is to let the X11 server itself notify us when the selection has changed. Which is more or less what Vim is doing (except that it's only quickly asking the X11 whether it still owns the selection, and if so, reuses the cache, which is fast). 

> Furthermore, can't we cache the clipboard value so ]p]p]p is fast?

While it initially sounds nice to assume that the clipboard hasn't changed in the last X seconds. The approach doesn't feel good to me. It's good enough for human changers of the clipboard, but not for programs that may be interfering.

Another ref I forgot: #1822.
People are doing spiffy things with X11/xcb and clipboard selections: https://github.com/Cloudef/xcmenu

**Comment by justinmk** [comment]
> There are applications that change the cut/select/... buffers entirely in the background (xcutsel, ...).

Yeah, I figured someone would mention that. But I bet it would solve the problem for 90% of our users and buy us some time to work on other things. Without linking to Xorg.

**Comment by tarruda** [comment]
> Related to the discussion in #1822. A first step would be that the vimscript provider implements a concept of ownership. At least on X11, it could run xsel (or @fmoralesc improved utility) as a job, and check if we still own the clipboard by checking if the job is still running, and then use a cached value in the provider (I tried to do this, but there is some improvements to job infrastructure needed)

If we can make it work as a job, then all the better. What kind of trouble you had when trying to implement this?

**Comment by bfredl** [comment]
@tarruda see #1838 (I need to send EOF to `xsel` without killing it)

**Comment by elmart** [comment]
@bfredl What's the status of this? Do you plan working on it?

**Comment by bfredl** [comment]
@elmart Sorry, have been a bit busy bit work the last weeks (and mostly worked on highlighting stuff when I had time for neovim hacking), but I definitely plan to work on this. I actually have a half-complete solution for caching inside the vimscript provider, it basically just needs #1838 . If someone with more experience with libuv and job control were to look into #1838 it would help (especially the EOF part, I've already fixed the final newline issue for `systemlist` before), otherwise I'll try to do it as soon as I have time.

**Comment by elmart** [comment]
@bfredl Ok. I didn't want to put pressure on you. Just knowing plans and checking we weren't waiting in a deadlock. Thanks!

**Comment by bfredl** [comment]
Now #2077 tries to fix this issue (missing `:register` entries)

**Comment by bfredl** [comment]
@elmart Does master work as intended now? (the title issue, caching is not merged yet)

**Comment by elmart** [comment]
@bfredl Works perfectly. Thanks!
