### ISSUE TITLE
Shift-backspace no longer reporting "Shift"

### ISSUE THREAD

**Issue by ltratt** [neovim/neovim#19265]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

Unknown

### Operating system/version

OpenBSD-current and Debian 11

### Terminal name/version

xfce4-terminal-1.0.4

### $TERM environment variable

xterm-256color

### Installation

Both package (for 0.7.2 on OpenBSD) and from source (55e81b0fe8bb205b579c1da24b3ac042191a4bbf) on Debian

### How to reproduce the issue

```
$ cat /etc/conf.lua
vim.api.nvim_set_keymap('i', '<BS>', 'hello', {noremap=true})
vim.api.nvim_set_keymap('i', '<S-BS>', 'goodbye', {noremap=true})
$ nvim -u /etc/conf.lua
```

Pressing either "backspace" or "shift-backspace" in insert mode inserts the text "hello" but never the text "goodbye" (this happens in the terminal on OpenBSD and Linux and also in neovim-qt). These key bindings worked as expected on nvim-0.7.0.

### Expected behavior

Please see above.

### Actual behavior

Please see above.

**Comment by ltratt** [comment]
> I cannot reproduce this in neovim-qt

I'm currently testing neovim-qt-2.18.9999 and it doesn't work properly on that. But if I drop back to neovim-qt-0.2.16.1 it does work. [It still doesn't work in terminal nvim for me though.]

**Comment by zeertzjq** [comment]
I test Nvim v0.7.0 built from source with xfce4-terminal on Debian 11 and this didn't work either, so I do know how this worked correctly for you in v0.7.0.

**Comment by ltratt** [comment]
Honestly, I mostly used 0.7.0 with neovim-qt so I might just not have noticed (or assumed it was due to some sort of other problem of my own making!).

**Comment by ltratt** [comment]
Confirmed: neovim 0.7.2 does work with `xterm` so this is a neovim-qt bug. Mea culpa!

**Comment by jgehrig** [comment]
@zeertzjq  @ltratt 

I don't think this is a regression in `neovim-qt` per-se...

Here are the issue that necessitated the  `<S-BS>` behavior change:
https://github.com/equalsraf/neovim-qt/issues/728
https://github.com/equalsraf/neovim-qt/issues/259

I think an argument can be made that the issue here is how neovim handles `<S-` input for backspace and space in terminal mode. I don't think it is practical for the GUI to send different key events based on the current editor mode.

However, I am not opposed to sending different key events in `terminal` mode from  `neovim-qt` if there is a simple way to do so... Unfortunately, I'm not aware of a good way to check editor mode before sending key events.

The current APIs have some drawbacks:
 - The `mode_change` events do not distinguish `terminal` mode.
 - The `API2 `get_mode` call would require an RPC request for each input event. This would be a big performance hit.
 
I am inclined to "Won't Fix" the issue https://github.com/equalsraf/neovim-qt/issues/999:

I think `<S-BS>` should either be invalid, or tolerated by terminal mode...

**Comment by zeertzjq** [comment]
I think making https://github.com/equalsraf/neovim-qt/issues/259 and https://github.com/equalsraf/neovim-qt/issues/728 wontfix makes more sense.

**Comment by zeertzjq** [comment]
And I don't think it is possible to fix this in Nvim if libvterm doesn't expose an API to check if the program running inside terminal has requested CSI u.

**Comment by ltratt** [comment]
@jgehrig 

> I think <S-BS> should either be invalid, or tolerated by terminal mode...

I *guess* that the original complaint ("Shift-Backspace inserts funny characters") is probably because people were used to a terminal emulator which didn't forward Shift-Backspace on and assumed that it's an invalid combination: if they'd used, say, `xterm` they might not have thought it was invalid.

Another way of looking at things (bearing in mind my heavy bias!) is that if people don't want Shift-Backspace to insert funny characters, they have the ability to bind those keys to a no-op. But if neovim-qt stops forwarding the keypress on, users like me can't do anything other than hacking neovim-qt's source code.

[FWIW, I looked, and also couldn't work out a practical way of saying "don't send shift-backspace in terminal mode" -- I'm glad that I don't seem to have completely missed the mark!]

**Comment by jgehrig** [comment]
> always sending <S-BS> makes more sense.

The user experience here is pretty jarring here. I'm not sure it is reasonable to ask users to map a handful of keys such as `<S-Space>` and `<S-BS>` to a no-op. How do we expect users to know about this workaround?

I learn toward keeping the neovim-qt behavior as-is. We get far more feedback that: "Terminal mode doesn't work correctly".

Since most terminals don't pass `<S-` for these key sequences, `<S-BS>` isn't a mapable key sequence in many environments anyways.

> And I don't think it is possible to fix this in Nvim if libvterm doesn't expose an API to check if the program running inside terminal has requested CSI.

Perhaps we can make the GUI clients terminal-mode aware?

I'm not opposed skipping <S-BS> only in terminal mode if it is the only practical option... However, I am not aware of an API that provides a performant mechanism for this task. 

Can something like `mode_change` be made to report terminal mode?

**Comment by ltratt** [comment]
> The user experience here is pretty jarring here. I'm not sure it is reasonable to ask users to map a handful of keys such as <S-Space> and <S-BS> to a no-op. How do we expect users to know about this workaround?

neovim-qt could choose to bind these keys to no-ops itself, which would still allow users to rebind them to something else if they want to?

**Comment by jgehrig** [comment]
> I think making https://github.com/equalsraf/neovim-qt/issues/259 and https://github.com/equalsraf/neovim-qt/issues/728 wontfix, i.e. always sending <S-BS> makes more sense.

I don't think doing nothing here is an option. Users are filing bugs against neovim-qt because it appears to work in the TUI and not the GUI. Actually, the issue is masked by many terminals not forwarding this key sequence. 

I think it is common for users to hold shift while pressing space and backspace, and the experience is bad. We should do something and it would be nice to fix this Neovim-side, so all GUI-clients can benefit.

I think @ltratt suggestion is the best so far, although I would like to avoid adding silent mappings if I can...

---

@zeertzjq

Is there a way to detect terminal mode without making an RPC `nvim_get_mode` call for every keystroke?

Is there a reason `mode_change` does not report terminal mode? Is there an alternative API that can be used to detect terminal mode?

**Comment by justinmk** [comment]
> Is there a reason `mode_change` does not report terminal mode? Is there an alternative API that can be used to detect terminal mode?

Certainly could be added. @jgehrig would you mind creating a tracking issue in https://github.com/neovim/neovim ?

**Comment by jgehrig** [comment]
@justinmk 

I've created an issue to track the lack of `mode_change` events for Terminal Mode:
https://github.com/neovim/neovim/issues/20325

I'd like to see a solution that allows front-ends to seamlessly fix these issues:
https://github.com/equalsraf/neovim-qt/issues/999
https://github.com/equalsraf/neovim-qt/issues/259

Currently I don't see a good way to fix this 'out-of-the-box' and different users want opposite solutions for the same bug.

Always happy to help write or test any code -- neovim or neovim-qt :)

**Comment by bfredl** [comment]
This can be configured by the user in nvim itself without any involvement of the client:

    tnoremap <s-bs> <bs>
    tnoremap <c-i> <tab>

and so on.
