### ISSUE TITLE
make_client_capabilities() does not return the updated capabilities

### ISSUE THREAD

**Issue by qianwch** [neovim/neovim#19342]
### Neovim version (nvim -v)

0.8.0 3a4fa22

### Language server name/version

0.8.0 3a4fa22

### Operating system/version

mac os 12.4

### Steps to reproduce using "nvim -u minimal_init.lua"

1. modify the   capabilities:
```
  local capabilities = vim.lsp.protocol.make_client_capabilities()
  capabilities.textDocument.completion.completionItem.snippetSupport = true
  require("lspconfig").jdtls.setup{...
  capabilities = capabilities
  ...
 }
```
2. call lua vim.lsp.protocol.make_client_capabilities() to check

**Comment by zeertzjq** [comment]
This sounds like intended behavior?

**Comment by qianwch** [comment]
> This sounds like intended behavior?

If it is intended, is there anyway to find out current enabled capabilities?

**Comment by clason** [comment]
https://github.com/neovim/neovim/issues/14090#issuecomment-1113956767

**Comment by mfussenegger** [comment]
`:lua =vim.lsp.get_active_clients()` lists the clients with their capabilities (both config.capabilities for the client and server_capabilities)

That the capabilities returned by make_client_capabilities cannot be mutated is intentional, and changing that would cause all sorts of havoc if you use multiple clients with different capabilities
