### ISSUE TITLE
Help on some coverity issues

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#1938]
I'm currently resolving all coverity issues in the "High Impact Outstanding" category.
Most of them I can do myself, but for some of them, I'd need some help from people knowing better the corresponding piece of code. They seem real issues needing some meaningful change to the code. So, what I want is just some hint on the proper way to go, and I'll do the rest.

@ZyX-I: coverity/13746: It seems `cleanup_conditionals` can in fact return a negative number. But in the following conditional, `cstack->cs_pending[idx]` is accessed when `idx < 0`. Maybe the else branch shouldn't run either if `idx < 0`?

@tarruda: coverity/68484, coverity/68485: Channel gets indeed freed in case of error, producing incorrect accesses to freed pointer later on. Maybe error handling code should be added to avoid this?

**Comment by tarruda** [comment]
> @tarruda: coverity/68484, coverity/68485: Channel gets indeed freed in case of error, producing incorrect accesses to freed pointer later on. Maybe error handling code should be added to avoid this?

Right now it seems the simplest way to fix the issue is to remove the `free_channel` call out of `close_channel` and only invoke `free_channel` in places where its safe:

- When returning from `channel_send_call` if the call stack size is 0 and `channel->closed == true`
- When returning from `parse_msgpack` if the call stack size is 0 and `channel->closed == true`
- In `channel_close` if the call stack size is 0
- In `channel_teardown` which is called when exiting nvim.

The msgpack-rpc code has grown into an unmanageable monster and is in need of some serious refactor/redesign. I had plans to extract it into a library(which can be reused by clients) but ended up not doing it due to lack of time.

**Comment by elmart** [comment]
@ZyX-I Any comment on coverity/13746?

**Comment by elmart** [comment]
Ok, coverity/68484 & coverity/68485 are gone in the last coverity build. Thanks, @tarruda.

**Comment by elmart** [comment]
@ZyX-I I've fixed coverity/13746 at https://github.com/neovim/neovim/commit/b0c31ee8dbb825326d65ae73466c77c14fc498ea. Would be nice if you could have a look.

**Comment by elmart** [comment]
Closing. All mentioned issues already fixed.
