### ISSUE TITLE
multiple quickfix / location lists - a neovim feature or a plugin?

### ISSUE THREAD

**Issue by dlants** [neovim/neovim#19424]
### Feature already in Vim?

No

### Feature description

In my vim workflow I use the quickfix list for:
- project errors
- references (like the output of an lsp references call)
- grep results

Since there is only a single global list, I often run into issues where I am forced to lose the list during my workflow.

For example: grep for everything mentioning x. Find a helper function f that manipulates x -> look for references to f via lsp (wipes out the grep for x list) -> grep for x again, find the spot where I left off, etc...

I think this pain point is likely quite common - many plugins have functionality that interact with the quickfix list or the location list, and end up trampling over each other.

It seems the ecosystem would benefit from some more generic solution, that would allow plugins to create and update their own lists, without trampling over each other.

I'm curious if this would be something that would belong in neovim itself, or if it should be delegated to a "meta-plugin", like telescope or plenary, which other plugins would interact with.

**Comment by ii14** [comment]
`:chistory` and `:colder`/`:cnewer`?

**Comment by justinmk** [comment]
> I often run into issues where I am forced to lose the list during my workflow.

For `:colder` / `:cnewer` the `]f` / `[f` mappings from https://github.com/tpope/vim-unimpaired work well. I use this all the time.

> that would allow plugins to create and update their own lists, 

That creates an "inner platform". How is the user going to manage all of this, cognitively? If multiple plugins are trying to show results from difference sources, that is similar to what we've noticed in `vim.lsp`, where we want to "merge" results from multiple sources into a single quickfix list. Which is the central purpose lf the quickfix list--to provide a single interface that the user can iterate through. 

What's actually needed is for the sources of the items to serialize through a common function that funnels into one quickfix list. In `vim.lsp` we've done that. 

Coordinating multiple unrelated plugins would require a notion of a "collect" or "gather" phase where the plugins are asked for, or passively provide, their items. That could be interesting, but I would suggest raising this idea at https://github.com/vim/vim because quickfix is a core Vim topic.

**Comment by im-n1** [comment]
@ii14 u deserve a cake
