### ISSUE TITLE
iterm2 doesn't get tab title set with TERM=iterm2 but does with TERM=xterm-256color

### ISSUE THREAD

**Issue by lf-** [neovim/neovim#19463]
### Neovim version (nvim -v)

NVIM v0.7.0

### Vim (not Nvim) behaves the same?

not altogether, 8.2.4975

### Operating system/version

macOS 12.4 aarch64

### Terminal name/version

iTerm2 3.4.16

### $TERM environment variable

xterm-256color, also tried iterm2

### Installation

nixpkgs unstable

### How to reproduce the issue

Open neovim in an iterm2, then

```
TERM=iterm2 nvim --clean
:set titlestring=t title iconstring=i icon
```

For reference, the terminal should receive the following to get the respective results:

```
echo -e '\x1b]0;bothtitles\x07' 
echo -e '\x1b]1;tabtitle\x07' # this is "icon title" in xterm parlance
echo -e '\x1b]2;windowtitle\x07'
```

### Expected behavior

I would like the window *and* tab titles to be set when setting titlestring in a neovim started with TERM=iterm2

### Actual behavior

It seems that (debugged with `script`), with TERM=xterm-256color, neovim will send the OSC 0 ST sequence (great!) and with TERM=iterm2 such as would be necessary over ssh to get full colour and so on, it will send OSC 2 ST, which will only set the window title.

------

What does vim do?

With TERM=iterm2, the same thing: only sets the title irrespective of `'icon'`/`'iconstring'`.

With TERM=xterm-256color, it will set either one separately with iconstring as the tab title and titlestring as the window title.

**Comment by lf-** [comment]
Is this a Unibilium bug? No idea, but quite possibly.

**Comment by gpanders** [comment]
The `iterm2` terminfo entry has a `ts` (set title) capability, but `xterm-256color` does not:

```
$ infocmp -x -C -1 iterm2 | grep -w ts
	:ts=\E]2;:\
$ infocmp -x -C -1 xterm-256color | -w grep ts
$
```

Since a `ts` entry exists for `iterm2`, Unibilium uses that to set the title. But since it's missing from `xterm-256color`, Nvim patches it in:

https://github.com/neovim/neovim/blob/746a153bc1a1bc1433a1246fcf454eeb058b9de1/src/nvim/tui/tui.c#L1775

The solution is to update the `iterm2` terminfo to use `\e]0` (either by making your own copy or sending a patch upstream).
