### ISSUE TITLE
RFE: make ZZ always save the file (i.e. behave like :w instead of :x )

### ISSUE THREAD

**Issue by dumblob** [neovim/neovim#1956]
~~~~sh
echo abc > xyz
nvim xyz
~~~~
in another shell
~~~~sh
rm xyz
~~~~
then press `ZZ` to save and quit nvim and see what happened:
~~~~sh
ls: cannot access xyz: No such file or directory
~~~~
Btw, after removing `xyz` and running `:w` in nvim, the whole file is correctly saved and exists.

**Comment by ZyX-I** [comment]
File was not changed (I mean, internally), so NeoVim does not need to save it. `:w`  saves file regardless of whether it was modified or not. To make `ZZ` work as you expect you need to do some modifications prior to quitting.

I do not really think this is a bug.

**Comment by dumblob** [comment]
>it is explicitly referenced that `ZZ` writes the current file only if it was modified.

My mistake, you're right. Still, I think the semantics is unfortunate as it's quite rare to use `:x` instead of `:w` and thus making `ZZ` behave like `:x` and having no such convenient and standardized shortcut for `:w` is a pity.

What about changing `ZZ` to `:w`?

**Comment by elmart** [comment]
> it's quite rare to use :x instead of :w

Sorry, I disagree. I do think that, in fact, what people wants when thinking "save" is "save what has changed", this is, `:x`. Thus `ZZ` corresponding to that instead of `:w` is just nice. The only reason people use `:w` is because of its more mnemonic resemblance to "write". But they usually don't want to write everything, even if unchanged.

**Comment by dumblob** [comment]
> I do think that, in fact, what people wants when thinking "save" is "save what has changed", this is, `:x`.

I have to make a short survey among other hard-core developers, but all the people who use Vim and I know them in person think "what I see is getting saved". That's also the reason why they don't use `:x`. For me it's difficult to remember what were the changes I made in one of my 6+ vim buffers and windows (each with different files), so I always trust what I see. Usually though, I'm saving the file incrementally after each small change using `:w`, so the situation where I accidentally lose something is nearly non-existent, but it happened today :(

Anybody else here with yet different experience?

**Comment by ZyX-I** [comment]
@dumblob I just keep pressing `<F2>` each time I have free time to move my fingers that far (it is mapped to `:update`). Also this argument is pointless: `:w` *just saves*, `:x` *saves and closes*, thus `:w` cannot be possibly the replacement for `ZZ`.

I would though find that `:wqall` is better suitable for `ZZ`, but it is not good to break working things for old users. And this is not going to change anything anyway because `:wqall` will only write changed files. Vim has no command for “write all files regardless of their &modified state and exit”. More, `:wq` (which will write the current buffer regardless of &modified state) is not going to write *all* buffers which are going to be closed because you’ve run it in the last remaining window, it will write only the current buffer. You may map `ZZ` to it if you wish as this solves your particular case.

I would also suggest to use `autowrite` and `autowriteall` options (they are not going to save you in this particular case). With this and my `<F2>` habit I just quit vim with `:qa` or `:cq` (latter is faster to type then `:qa!`) without losing any changes I do not want to lose.

---

My opinion is that `ZZ` meaning must not be changed. Reasoning:

1. Users are already used to it.
2. Writing non-modified files can be harmful:

    1. Closing help window with `wq` is not possible if help file is not writeable (i.e. is located in `/usr/share/vim/…` and user is not root and does not have necessary capabilities).
    2. Closing readonly window with `wq` fails and `wq!` is not a wise idea since &readonly is most likely there for a reason.
    3. Implementing new command (say `:wqr`) that works like `if &readonly | exit | else | wq | endif` is harmful as well: if you view modifiable log files within NeoVim without an intention to modify them, but as well without setting `&readonly` (e.g. by viewing them with `:view`) it may appear that after `wq` log files are no longer updated. Reasoning is simple: depending on the options when saving Vim may  act in two ways: create new file, unlink old one, move or trim and write. In the first variant a number of loggers will stop working because they have opened the old file once and are not going to reopen it. System is completely fine with writing to “deleted” file: it will just wait until file is closed to delete it from cache and delete the inode, until then “deleted” file exists as an inode that is not linked in any directory and in some kernel structures. So new items in log are going to the old file and new file saved by NeoVim remains untouched.
    4. Writing to the file if it was not changed may make some backup systems unnecessaraly backup the file once again (or at least trigger wasting resources on checking whether file has changed since the last backup).

**Comment by dumblob** [comment]
@ZyX-I thank you for the description how you do it (and you're right, I was all the time talking about `:wq` instead of `:w`). Initially I didn't want to remap `ZZ`, because I often have to work in environments only with default program configurations and it would behave differently from my own setup. It doesn't make sense to think up a new binding for `:wq`, because I also use `ZQ` and `ZZ` is just too simple to press accidentaly. Remap seems to be the best option.

Regarding your reasoning, I was aware of all of them except for *2.iv.*, which is not a problem - it would become one if there were thousands and more of such files. Actually I was quite surprised few years ago, when I discovered, that `:w` actually doesn't care about the original inode. All the other reasons are "obvious" and I'm quite used to use `ZZ` and if it fails (vim issues a nice human-readable description why it failed) and it's appropriate (which is in 95% of cases), I continue with `ZQ`.

I'm closing this issue as invalid and going to remap `ZZ` to `:wq`. Thanks.
