### ISSUE TITLE
Can't use nushell inside neovim on windows.

### ISSUE THREAD

**Issue by B4mbus** [neovim/neovim#19648]
### Neovim version (nvim -v)

NVIM v0.7.2 

### Vim (not Nvim) behaves the same?

Vim 9.0, it works completely differently, it tries to do `nu /c ...`.

### Operating system/version

Windows 10 PRO N

### Terminal name/version

I'm using neovide.

### $TERM environment variable

In neovide it displays nothing. In nushell it can't find that variable.

### Installation

MSI Installer IIRC.

### How to reproduce the issue

Install nvim and nushell on windows, set `nu` as the shell `vim.opt.sh = 'nu'` and try to invoke any command like so: `:!command` or use it inside toggleterm.

### Expected behavior

Things.. working.

### Actual behavior

Nushell works when in `:term` 
![image](https://user-images.githubusercontent.com/75364377/183073579-281aee44-ab95-43ae-8b87-96ec2b0b68dd.png)
but it doesn't when I'm trying to use any filter command (`:!asd`).
![image](https://user-images.githubusercontent.com/75364377/183073595-aa99ee0c-cde5-473c-8f14-413e23588ae5.png)
Or toggleterm (it's the same error in toggleterm).
It doesn't matter if I put a full path in the config or just `nu`.

**Comment by 3N4N** [comment]
Could you share the output of `:4verbose!help` please? Also, try running a direct executable (.exe or .com) file, e.g., `:4verbose!C:\Windows\System32\tree.com`.

**Comment by B4mbus** [comment]
![image](https://user-images.githubusercontent.com/75364377/184193105-6b51ce13-1a91-4f27-9cb9-a0609ae87bcb.png)
For the second one - I tried:
 - `4verbose!C:\Program Files\nu\bin\nu.exe`
 - `4verbose!"C:\Program Files\nu\bin\nu.exe"`
 - `4verbose!C:\\Program Files\\nu\\bin\\nu.exe`
 - `4verbose!"C:\\Program Files\\nu\\bin\\nu.exe"`
 - `4verbose!C:/Program Files/nu/bin/nu.exe`
 - `4verbose!"C:/Program Files/nu/bin/nu.exe"`
Every try results in the same error as above. Trying to run any other executable that doesn't have spaces in it results in the same error too.

On the other hand, if I set my shell to `cmd` which is the default windows shell and the path doesnt contain spaces executing everything works fine.

**Comment by 3N4N** [comment]
> On the other hand, if I set my shell to cmd which is the default windows shell and the path doesnt contain spaces executing everything works fine.

Yeah, the problem is neither in your machine/system nor in neovim. You just need to set some options properly. I've just installed nushell to dig around, but you could take a look at `:h shell-powershell` and try taking+chaging some options from there. Neovim underneath has to invoke a proper nu command, like `cmd -c 'echo hello'` but for nushell instead of cmd. The `-c` stuff comes from `:h shellcmdflag`. Just try messing around with it. And I'll report back if I find the proper flag. (I just heard about nushell, so I'll need time.)

**Comment by 3N4N** [comment]
@B4mbus well, found the settings. Try these:

```
let &shell = 'nu'
let &shellcmdflag = '-c'
let &shellquote = ""
let &shellxquote = ""
```

---
@zeertzjq think it should be documented? (I did `:helpgrep nushell`. Nothing.)

**Comment by B4mbus** [comment]
@3N4N This works. Thanks.

**Comment by justinmk** [comment]
Setting 'shell' requires that you understand what you're doing, i.e. you must set all of the shell-related options appropriate for the shell you want to use. This is a fact of Vim.

**Comment by zeertzjq** [comment]
Vim's `set_init_3()` does do this kind of thing:
```
/*
 * Set 'shellpipe' and 'shellredir', depending on the 'shell' option.
 * This is done after other initializations, where 'shell' might have been
 * set, but only if they have not been set before.
 */
```

Although apparently it is no possible to cover all shells.

**Comment by omaru-ok** [comment]
![image](https://user-images.githubusercontent.com/108952834/233487512-108a7b77-a4ed-413e-a130-a183feb1e028.png)

okay there is somethign wrong!

**Comment by JonasLeonhard** [comment]
@NormTurtle 
I had trouble using nushell withing neovim too. 

if you use `:r !ls` with nvim running inside of neovim i get the same error as you above: "cant read file ...". 

I think this might happen because of the "set shellredir" option. 
By default this is set to "shellredir=>". ">" in this nushell context is not a valid file redirector. 
It should be something like "| save %s". 

There is one more step to get "r !ls" working in nushell after setting "set shellredir=| save %s". 
You will still get the same error as above. When you run `:5verbose r!ls` you will see which command nvim tries to execute:

Log:
Executing command: "(ls) | save /var/folders/d7/6dndt7v55hnfdw_lb6vqfz0dmwspnq/T/nvim.jonas.leonhard/bXLj5v/0"

And if you run this command in nushell you will get:
```
Error: nu::shell::cant_convert

  × Can't convert to string.
   ╭─[entry #2:1:1]
 1 │ (ls) | save /var/folders/d7/6dndt7v55hnfdw_lb6vqfz0dmwspnq/T/nvim.jonas.leonhard/Lvs8Cz/2
   ·  ─┬
   ·   ╰── can't convert record<name: string, type: string, size: filesize, modified: date> to string
   ╰────
```

This is because ls returns a table instead of a string, which cannot be saved into a file. To fix this you could run something like:
":r !ls | to text" or ":r !ls | get name"

Hopefully this helps.
