### ISSUE TITLE
Window-local display of extmarks

### ISSUE THREAD

**Issue by johnwilmes** [neovim/neovim#19654]
### Feature already in Vim?

n/a

### Feature description

I would like to be able to highlight a particular region in a particular buffer, but only in one window. It seems that this is maybe possible using :ownsyntax, and then defining a new syntax for that window, but this seems incredibly complicated compared the wonderful neovim extmarks, which let me just specify the bounds of the region and the highlight group.

Unfortunately, there does not seem to be any way of scoping visual aspects of an extmark (highlight, virtual text) to a particular window - everything about an extmark displays in all windows.

It would not be quite enough for my use case, but even :winhighlight seems to not work with extmarks. E.g.,

`:lua vim.api.nvim_buf_set_extmark(0, vim.api.nvim_create_namespace('test'), 0, 1, {hl_group="Visual", end_row=0, end_col=2})`

`:set winhighlight=Visual:IncSearch`

This correctly makes actual visual mode look different in the current window, but does not affect the appearance of the extmark with visual group highlighting.

**Comment by lewis6991** [comment]
I guess for this we would need to add `nvim_win_set_extmark` for window local marks.

This might be useful for implementing folding on extmarks (#19226).

**Comment by echasnovski** [comment]
I think it is reasonable to be reopened since there is no exported way of doing so. `nvim__ns_get()` and `nvim__ns_set()` are experimental (#28432). @bfredl, does that sound reasonable?

**Comment by justinmk** [comment]
There is a plan for maturing `ns_get`, we just need to execute it

**Comment by echasnovski** [comment]
> There is a plan for maturing `ns_get`, we just need to execute it

And until then I'd argue that this issue is not resolved. It was closed with assumption that the solution was already non-private and stable.

Also, would you mind pointing me at that plan? I can't seem to find it in the issues or PRs. There is #28728, but no actual steps to make those function stable and public.

**Comment by bfredl** [comment]
>  It was closed with assumption that the solution was already non-private and stable. 

It was closed because the feature was, in fact, implemented. There are tests for the feature, and those tests pass.

If there is undocumented assumptions which cause practical problems for some usecases, it is better to open a new issue which clearly **spells out** these assumptions in a new OP, not to repurpose a solved issue into a unsolved one after the fact.

**Comment by echasnovski** [comment]
> It was closed because the feature was, in fact, implemented. There are tests for the feature, and those tests pass.

It was implemented, yes. And then reverted into "EXPERIMENTAL" API which is subject to no API contract. Hence the question about whether it is reasonable to also revert the status of this issue.

It is, probably, mostly driven by me not thinking that "there is a private method that can be changed at any time" is a valid reaction to a completed feature request.

> If there is undocumented assumptions which cause practical problems for some usecases, it is better to open a new issue which clearly **spells out** these assumptions in a new OP, not to repurpose a solved issue into a unsolved one after the fact.

It is a bit of a chicken-and-egg problem. I don't think there will be any battle-tested usage until there is an exported method. And there doesn't seem to be a movement towards exporting the method until it "matures".

I personally have at least three different plugins that would benefit from this, but investing that much effort into the very much unstable API is not inviting.

Nvim itself uses this in only one place (`vim.hl.on_yank`) for one and a half years. So it also doesn't look like it will be much tested with this.

**Comment by bfredl** [comment]
> Hence the question about whether it is reasonable to also revert the status of this issue.

Sure that it a matter of style I guess. but the issue was closed because the original feature request was fulfilled (and that code _still_ works, it was not reverted). the new criteria for stabilization are apparently different, so it becomes much clearer if those requirements are spelled out somewhere new (or if it is obvious enough, just a PR right away).

It is not very clear to have an open issue with requirements which are all already satisfied, because of some unrelated issue which really is somewhere else. At least that is how I see it.

**Comment by justinmk** [comment]
I wouldn't say it's chicken-and-egg. All that's needed is to make sure we have an interface that will generalize to other namespace purposes. They don't all need to be implemented, as long as an extensible "shape" is in place. 

I will try to write something up.
