### ISSUE TITLE
Refresh neovim instance command

### ISSUE THREAD

**Issue by asteroidalaz** [neovim/neovim#19681]
### Feature already in Vim?

NO

### Feature description

It would be nice if the neovim will have some sort of `reinit` / `reload` / `refresh` functionality, which could do the cleanup and then start the startup process, without actually exiting the neovim instance.
The `:source` command sources the file on top of the previous settings, due to that `:source` sometimes misbehaves.
### Pros:
- Adding/removing/testing plugins will be nice.
- Less confusion why anything is not working.
- Faster than the `kill nvim -> exec nvim` process
- The x11 window will not have to be closed, just the content update and done.
### Cons:
- I don't know, you tell me.

**Comment by matveyt** [comment]
Cons

1. Non-trivial implementation
2. Incompatibility with (old) frontends

It looks more natural to me as a feature of a frontend application. Say, nvim-qt can re-exec nvim on app crash; so it could do that by user request too, perhaps.

**Comment by gravndal** [comment]
You can achieve something like this fairly easily with a simple shell script/function that re-executes neovim in a loop given a specific exit code and `:h :cq`.

**Comment by asteroidalaz** [comment]
> You can achieve something like this fairly easily with a simple shell script/function that re-executes neovim in a loop given a specific exit code and `:h :cq`.

For that to work, it will need a wrapper around the nvim executable, or doing some tweaks in the bashrc. Or something different if using Windows.

> What would be the actual use case? Nothing short of `:q` followed by `nvim` can _ensure_ a clean slate. If you _don't_ want a clean slate (which it turns out people who request this feature -- and there have been many -- usually don't), you have to be very specific about what is and is not preserved.

Use case?
I think **automation** is the thing that everyone wants, that is the reason computer were made, programs were made, and this is one of that. Rather doing it manually, why can't we have an automatic one, like vs code at least.
Neovim is now going to have mouse support for nvim _beginners/noobs_, and I think this restart feature used by some awesome plugin could have _asthetic_ and _functional_ potential

_Example_:
When installed plugins which require restart, then plugin manager could do a prompt for restart, and restart. (And may create and load session in background)

This will be helpful for the plugin devs.

**Comment by clason** [comment]
> Neovim is now going to have mouse support for nvim beginners/noobs, and I think this restart feature used by some awesome plugin could have asthetic and functional potential

Sorry, but that's an exceptionally weak argument.

The key point here is, as always for new features, a cost-benefit analysis -- how much does it cost to implement and maintain _in core_ versus how much does it offer to users (e.g., new functionality over mere convenience)? In particular, why can't it be a plugin?

(And VS Code comparisons are fraught since the code architecture is _very_ different and so the cost-benefit analysis will come to different conclusions as well. Neovim is -- at least right now -- monolithic, in contrast to VS Code, which therefore has a much easier job restarting a "backend". A better target would be Neovim GUIs, which could similarly stop, restart, and reattach a Neovim instance.)

**Comment by asteroidalaz** [comment]
I think, a plugin will be best then, so I am closing this issue.
