### ISSUE TITLE
(UNKNOWN PLUGIN): Error executing lua: attempt to call a nil value

### ISSUE THREAD

**Issue by kevinhwang91** [neovim/neovim#19831]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-877-g35653e6bc

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ArchLinux

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

build from repo

### How to reproduce the issue

Since https://github.com/neovim/neovim/commit/35653e6bcda6923b5213fb9356c35067d6d0288f
`cat mini.lua`
```lua
local api = vim.api

local ns = api.nvim_create_namespace('test')
api.nvim_set_decoration_provider(ns, {
    on_start = function(...)
    end
})

_G.test = function()
    local bufnr = api.nvim_create_buf(false, true)
    local winid = api.nvim_open_win(bufnr, false, {
        col = -1,
        height = 5,
        relative = 'cursor',
        row = -1,
        width = 50
    })
    vim.wo[winid].winhl = 'Normal:Menu'
    api.nvim_buf_set_lines(bufnr, 0, -1, true, {'foo', 'bar'})
end

vim.defer_fn(function()
    _G.test()
end, 1000)
```
nvim --clean -u mini.lua mini.lua

### Expected behavior

No error. 

### Actual behavior

![image](https://user-images.githubusercontent.com/17562139/185414190-f64a0cec-40a3-43ed-a5a2-b7991a95f00c.png)

**Comment by lmburns** [comment]
I'm not sure if my issue is related to this one, but it started happening after the same commit.

When using [`coc.nvim`](https://github.com/neoclide/coc.nvim)'s functions `CocAction` and `CocActionAsync` with the following commands, I get a segmentation fault:

```
[1]    1746810 segmentation fault (core dumped)
```

The commands are:
```
":call CocActionAsync('jumpDeclaration', 'drop')<CR>"
":call CocActionAsync('jumpTypeDefinition', 'drop')<CR>"
":call CocActionAsync('jumpImplementation', 'drop')<CR>"
":call CocActionAsync('jumpUsed', 'drop')<CR>"
":call CocActionAsync('jumpReferences', 'drop')<CR>"
```

It may have something to do with the with the quickfix, because each of these commands will fill the quickfix window. However, when using something like this, I do not get a segmentation fault:

```
":call CocActionAsync('diagnosticRefresh', 'drop')<CR>"
```

I'm still trying to debug the command to try and figure out more about this issue.

**Comment by gordun209-hub** [comment]
I'm having this issue too when trying to find files with telescope, with archlinux and nightly neovim.
