### ISSUE TITLE
Matching Brace Only Highlights when On-Screen

### ISSUE THREAD

**Issue by ezzieyguywuf** [neovim/neovim#19851]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

yes, vim 9.0

### Operating system/version

debian something

### Terminal name/version

alacritty something

### $TERM environment variable

xterm-256color

### Installation

apt install

### How to reproduce the issue

1. open nvim
2. creating a brace-pair
3. scroll so that one-half of the pair is off-screan
4. highlight the visible brace
5. scroll so that both are now on-screen

### Expected behavior

When the second brace comes on-screen, I expect it to be highlighted

### Actual behavior

It's not.

Here's a screencast that shows the behaviour.

[![asciicast](https://asciinema.org/a/fWeMBBZdcIwCPRybOJXFDytCr.svg)](https://asciinema.org/a/fWeMBBZdcIwCPRybOJXFDytCr)

**Comment by ezzieyguywuf** [comment]
See https://github.com/vim/vim/issues/10942

**Comment by ezzieyguywuf** [comment]
From the linked vim issue, it looks like (?) there is a fix in something called a "runtime file"

I have a few questions:

1. I see this bug is tagged as `bug-vim` which has a description of `wrong behaviour inherited from vim`. This is slightly confusing to me - while I understand that the intent of neovim is to be a drop-in replacement for vim, I don't understand why this means carrying over bugs like this as-is. Is neovim based on the original vim code? (I guess for some reason I thought it was rewritten from scratch)
2. Now that a fix has been found (?) upstream (I guess - they closed the bug), when is it reasonable to expect this same fix to propagate to neovim?

**Comment by zeertzjq** [comment]
> when is it reasonable to expect this same fix to propagate to neovim?

Usually when the next "Update runtime files" commit arrives in Vim.

**Comment by clason** [comment]
Re your first question: `bug-vim` is additional information (for us), indicating that the fix should be coordinated with Vim -- Neovim is indeed a fork of Vim and still shares a lot of code, including most of the runtime files (which, as the name implies, are loaded at runtime and not compiled into the binary). By reporting a bug upstream, both projects profit.

And Vim has a bit of an untypical development model (dating back to email lists before Github was a thing); your issue is handled the way things usually are there. (Runtime files are updated in batch without a fixed schedule; usually roughly once per week. Once they land, we try to port them quickly; this could be a bit more tricky in this case since Vim likes to take such opportunities to rewrite files in their new language vim9script, which is not compatible.)

**Comment by clason** [comment]
Will be closed by https://github.com/neovim/neovim/pull/19929
