### ISSUE TITLE
New terminal UI broke bracketed paste mode

### ISSUE THREAD

**Issue by renstrom** [neovim/neovim#2000]
With https://github.com/neovim/neovim/pull/1820, [bracketed paste](http://cirw.in/blog/bracketed-paste) no longer works, [ConradIrwin/vim-bracketed-paste](https://github.com/ConradIrwin/vim-bracketed-paste) has stopped working.

Neovim (`66a03a7`)

![screen shot 2015-02-17 at 9 10 56](https://cloud.githubusercontent.com/assets/177685/6225010/1cf9859c-b685-11e4-9fb2-b17892caa2e6.png)

Vim `7.4.488`

![screen shot 2015-02-17 at 9 12 02](https://cloud.githubusercontent.com/assets/177685/6225014/2d62231c-b685-11e4-85ab-656ed39ff900.png)

**Comment by renstrom** [comment]
I'm using iTerm2 by the way.

**Comment by justinmk** [comment]
see also https://github.com/neovim/neovim/issues/937

**Comment by renstrom** [comment]
Also, I'm not sure if it was clear, but this worked before https://github.com/neovim/neovim/pull/1820.

**Comment by fmoralesc** [comment]
I think this might be related to [this](https://github.com/neovim/neovim/pull/1820#issuecomment-74496769), the `<Esc>` keys vim-bracketed paste uses are probably not being sent.

**Comment by tarruda** [comment]
I've seen the code for the vim-bracketed-paste plugin and can say that it wont work now that the UI layer has a different architecture because it relies on setting terminal key codes(eg: `set <f28>=...` no longer works).

I can however, add direct support for the bracketed paste sequences in the tui module, this should remove the need for a plugin that automatically set the `paste` option.
