### ISSUE TITLE
Non-empty 'winhighlight' interferes with hl-StatusLine

### ISSUE THREAD

**Issue by lbrayner** [neovim/neovim#20069]
### Neovim version (nvim -v)

0.8.0 1ffd527c837fb2465c9659273bbe5447a1352db2

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Ubuntu 20.04

### Terminal name/version

st 0.8.5

### $TERM environment variable

st-256color

### Installation

Neovim PPA unstable

### How to reproduce the issue

nvim --clean
:set termguicolors
:hi StatusLine gui=NONE guibg=#121212 guifg=#5f87ff
:hi NormalNC guibg=#303030
:split
:split
:set winhighlight=NormalNC:NONE
:hi StatusLine gui=reverse guibg=#121212 guifg=#5f87ff
:wincmd w

### Expected behavior

Statusline colors are inverted after `hi StatusLine gui=reverse guibg=#121212 guifg=#5f87ff` on all three windows.

### Actual behavior

Statusline colors are not inverted on window where `winhighlight=NormalNC:NONE`. It works for the other windows

**Comment by zeertzjq** [comment]
This seems to work if `'winhighlight'` is set (again) after changing the `StatusLine` highlight, so probably a missing highlight update.

**Comment by melkster** [comment]
I'm having a similar issue where if `winhighlight` is set, nothing happens if I change the highlight of `CursorLineNr`, `CursorLine`, `LineNr`, `EndOfBuffer` (and probably more highlight groups) until I open a new window.

**To reproduce:**

1. `> nvim -u NONE -c "set winhighlight=SpecialKey:Text number cursorline"`
2. `:hi CursorLineNr ctermfg=red | hi CursorLine ctermfg=red | hi LineNr ctermfg=red | hi EndOfBuffer ctermfg=red `
3. _No difference_
4. Open a new window with `:sp` and the highlights appear

If you remove the `set winhighlight` command it works:

1. `> nvim -u NONE -c "set number cursorline"`
2. `:hi CursorLineNr ctermfg=red | hi CursorLine ctermfg=red | hi LineNr ctermfg=red | hi EndOfBuffer ctermfg=red `
3. _Highlights change to red as expected_

I'm on version v0.8.0-dev-1194-ga80ab395a

**Comment by lbrayner** [comment]
This is fixed as of `neovim-0.9.0~ubuntu1+git202212280018-d215dae0e-333b5866f`, i.e. https://github.com/neovim/neovim/commit/bf459641a85ff1b4f24196ba6345de7bb8159884.
