### ISSUE TITLE
Cannot run nightly using nix flake

### ISSUE THREAD

**Issue by florentc** [neovim/neovim#20072]
### Neovim version (nvim -v)

commit 927d4d2a15b8474cd6c605df65ef53873cf73131

### Vim (not Nvim) behaves the same?

no

### Operating system/version

NixOS unstable

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

Nix flake

### How to reproduce the issue

Follow instruction from the [wiki](https://github.com/neovim/neovim/wiki/Building-Neovim#nixos--nix) to run Neovim nightly using the provided nix flake.

### Expected behavior

Neovim nightly runs

### Actual behavior

Nix error: `error: attribute 'defaultApp.x86_64-linux' should have type 'derivation'`

**Comment by teto** [comment]
what returns `nix --version` ? indeed `nix run github:neovim/neovim?dir=contrib` fails I think due to a change in flakes. 
Funnily enough I was tweaking the flake 2 days ago. I will fix it this week and update the wiki as well.
You can work around the issue via `nix run 'github:neovim/neovim?dir=contrib#neovim'`.

**Comment by florentc** [comment]
Nix version is 2.11.0
Thank you very much for your quick reply and the workaround

**Comment by teto** [comment]
could you checkout https://github.com/neovim/neovim/pull/20091 and check that `nix run` works for you ?
