### ISSUE TITLE
generated source is not reproducible

### ISSUE THREAD

**Issue by gzm55** [neovim/neovim#20124]
### Feature already in Vim?

NO

### Feature description

when try to do a reproducible build, we found that the generated sources (.c/.h/.gperf) files are not reproducible, mostly due to the iterator in lua is not ordered. can we make them reproducible?

**Comment by matu3ba** [comment]
Yes.
See https://stackoverflow.com/questions/70701890/why-pairs-working-randomly-in-lua-how-to-fix-it as design decision.
See also for context http://lua-users.org/wiki/HashDos.

From source code of LuaJIT in `src/lj_prng.c`:

```
/* If you really don't care about security, then define
** LUAJIT_SECURITY_PRNG=0. This yields a predictable seed
** and provides NO SECURITY against various attacks on the VM.
```

Another, but potentially costly solution depending on coverage we are testing documented in `faq.html:134:0`:
```
<dt>Q: Table iteration with <tt>pairs()</tt> does not result in the same order?</dt>
<dd>The order of table iteration is explicitly <b>undefined</b> by
the Lua language standard.<br>
Different Lua implementations or versions may use different orders for
otherwise identical tables. Different ways of constructing a table may
result in different orders, too.<br>
Due to improved VM security, LuaJIT 2.1 may even use a different order
on separate VM invocations or when string keys are newly interned.<br><br>
If your program relies on a deterministic order, it has a bug. Rewrite it,
so it doesn't rely on the key order. Or sort the table keys, if you must.</dd>
</dl>
```

1. Can you provide more context, why sorting is not option?
2. Can we make execution order of commands deterministic (the runtime itself being determinstic instead of asynchronous)?
3. As how bad do you expect the effect from `LUAJIT_SECURITY_PRNG=0` and providing the initial seed from as special build mode? I dont understand what guarantees the neovim luajit runtime wants to provide.
4. If 3 is no option: Do we really want to maintain luajit with separate states for table iteration for this?

**Comment by bfredl** [comment]
Rather than disabling LUAJIT_SECURITY_PRNG globbally, it would be better to determine what step in generation depends on hash orderning and try to eliminate that specifically. Then generated sources will not depend on lua 5.1/luajit version either.

**Comment by gzm55** [comment]
under `https://github.com/neovim/neovim/blob/master/src/nvim/generators/`, many .lua generators invoke `.pairs()` function, such as (gen_eval.lua)[https://github.com/neovim/neovim/blob/master/src/nvim/generators/gen_eval.lua]

**Comment by bfredl** [comment]
Ever using `pairs()` internally is not a problem. The one in `gen_eval.lua` is not serializing anything. we need to know where nondeterminism ends up in the _output_.

**Comment by gzm55** [comment]
we can use `diffoscope` to compare two output objects files (*.o) from the same commit. Here are the different ones

```bash
build/src/nvim/CMakeFiles/nvim.dir/api/private/helpers.c.o
build/src/nvim/CMakeFiles/nvim.dir/lua/executor.c.o
build/src/nvim/CMakeFiles/nvim.dir/msgpack_rpc/helpers.c.o
build/src/nvim/CMakeFiles/nvim.dir/autocmd.c.o
```

**Comment by bfredl** [comment]
you also need to include `build/src/nvim/auto` generated _source_ files, so we have something we can reason about.

**Comment by gzm55** [comment]
the nondeterminism auto generaed sources:

```bash
build/src/nvim/auto/api/private/funcs_metadata.generated.h
build/src/nvim/auto/api/private/ui_events_metadata.generated.h
build/src/nvim/auto/lua/vim_module.generated.h
build/src/nvim/auto/auevents_name_map.generated.h
build/src/nvim/auto/keysets.generated.h
build/src/nvim/auto/keysets_defs.generated.h
build/src/nvim/auto/options.generated.h
build/include/keysets.h.generated.h
```
