### ISSUE TITLE
UI: Load UI from a shared library

### ISSUE THREAD

**Issue by tarruda** [neovim/neovim#2034]
Nvim core is now clearly separated from UI implementations and the new terminal UI is self-contained in the "tui" directory. In fact, the only core reference to the tui module is [here](https://github.com/neovim/neovim/blob/6293b5513c54557bbf56077374df83cb52344fa3/src/nvim/ui.c#L72).

An implication of this separation is that we can easily make any UI implementation a shared library that is discovered and loaded by nvim on startup and implements the UI structure(ui.h). The tui directory could built into a shared library and installed into `$VIMRUNTIME/uis/tui.so`, for example.

Another implication is that we can more easily perform in-process embedding on nvim, as suggested by @oakes in #1918(instead of calling `tui_start`, call a function pointer set by the embedder)

This scheme will make it possible to use projects like [vimr](https://github.com/qvacua/vimr) or [macvim](https://code.google.com/p/macvim/) by simply installing shared libraries in runtime directories(in case multiple UIs are found the choice can be made through command line flags, nvimrc or via environment variables)

To achieve this, some refactoring may be necessary, especially on the build system(The automatic header generation probably needs to be exported to a self contained script that we can invoke on arbitrary directories)

I cant work on this right now, but if someone else is interested I can assign the issue.

**Comment by kopischke** [comment]
:+1: from a MacVim GUI addict.

**Comment by rainerborene** [comment]
ping @qvacua and @b4winckler to the discussion.

**Comment by Pyrohh** [comment]
I'd like to read what @oakes said, but It looks like you linked the wrong issue. Also just a small nitpick, but we probably shouldn't be putting libraries in `$VIMRUNTIME` (which I assume to be `/usr/share` or `/usr/local/share`, unless you meant `/usr/lib`).

**Comment by oakes** [comment]
It was PR #1918, @Pyrohh. I did that work primarily for my Rust library, [neovim-rs](https://github.com/oakes/neovim-rs). The example project in it has a working example of using Neovim as a static library with [a fairly small amount](https://github.com/oakes/neovim-rs/blob/master/example/src/main.rs) of Rust code. Specifically, it runs Neovim on the main thread, and launches a separate thread that communicates with it over msgpack-rpc and logs the path of every buffer you enter into.

My approach was just to break up the main function into two parts, `nvim_main_setup` and `nvim_main_loop`, so I could create a new channel just before the main loop. It looks like a function pointer may be a nicer approach, but I will probably keep maintaining my fork for now. Since doing this in Rust adds the additional complication of FFI, I had to do some extra work to make that practical.

**Comment by tarruda** [comment]
> I'd like to read what @oakes said, but It looks like you linked the wrong issue. Also just a small nitpick, but we probably shouldn't be putting libraries in $VIMRUNTIME (which I assume to be /usr/share or /usr/local/share, unless you meant /usr/lib).

:+1: Fixed the link

**Comment by qvacua** [comment]
Hey, guys. I started to look into neovim only yesterday, so please bear with me if I'm saying something stupid.

So, if I understand it correctly, there are two ways of implementing UIs:

- Implement `ui.h` and let nvim control you.
- Embed neovim, either as a separate process or instantiate neovim in-process, and communicate via msgpack-rpc. This way the GUI would control neovim.

I guess for GUI versions of neovim, let's say something like MacVim with neovim, the embedding is probably more appropriate or am I mistaken?

**Comment by tarruda** [comment]
> I guess for GUI versions of neovim, let's say something like MacVim with neovim, the embedding is probably more appropriate or am I mistaken?

If you want to implement in C, it would probably be simpler to implement ui.h directly. If you want to use a high level language such as python or ruby, I think msgpack is the best way approach. ([python gui example](https://github.com/neovim/python-client/blob/master/neovim/ui/gtk_ui.py))

**Comment by tarruda** [comment]
Here is another example in coffeescript(atom shell): https://github.com/coolwanglu/neovim.as/blob/master/src/nvim/ui.coffee

**Comment by equalsraf** [comment]
Honestly, don't see the point of implementing the UIs as multiple shared libs - understandably it would be easier to implement - but in the end we would have two ways to do the same thing and more surface to cover. With the downside that a UI implemented like this cannot connect to a remote Neovim process.

I would let this be until nvim can be fully used as a static lib. At which point this would no longer be an issue - i.e. could just be a compile flag instead of dynamically searching for shared libs.

> we probably shouldn't be putting libraries in $VIMRUNTIME

yeah, something like /usr/lib/nvim, like in firefox/nss

**Comment by tarruda** [comment]
> With the downside that a UI implemented like this cannot connect to a remote Neovim process.

It will be possible to use with remote nvim instances, all we need is to abstract the functions used to communicate with nvim into pointers passed to the initialize function( instead of using input_enqueue directly, use a pointer and let nvim handle communication within the process or to a remote one)

> we probably shouldn't be putting libraries in $VIMRUNTIME

These are just nvim-specific loadable modules, and not reusable libraries in the common sense.

**Comment by philix** [comment]
Why not make Neovim "core" a shared library which UI executable can use?

Neovim as a binary that calls UI functions inside shared library seems too unusual to me. What's the advantage other than ease of implementation on our side compared to the Neovim as a library approach?

**Comment by qvacua** [comment]
I also think that Neovim-shared-(or static)-library is more usual and also easier for GUI-projects to integrate, especially when you are using some cousins of C.

**Comment by aktau** [comment]
> Neovim as a binary that calls UI functions inside shared library seems too unusual to me. What's the advantage other than ease of implementation on our side compared to the Neovim as a library approach?

Not here to debate the (de)merits of the general approach, but your comment made me think of another software project where it was used: [Quake II](http://fabiensanglard.net/quake2/).

**Comment by Gaelan** [comment]
Why don't we just separate tui into a separate process that embeds nvim?

**Comment by ZyX-I** [comment]
I think that with current codebase turning NeoVim core into a usable library will be hard: loads of exported functions and globals without neovim-specific prefix, the only official API are functions used for RPC, `#include` problems with every inherited header and some new ones. Though this meets project goals, as a first stage having UI’s be shared libraries is enough. Once NeoVim core is a library (if this will happen) it is easy to create a wrapper program which *both* loads the UI and links to the core library.

And, as usual, I do not trust the performance of UIs that communicate with NeoVim via usual RPC. Though I have not actually tested them.

**Comment by osor-io** [comment]
Hey all! 😊

What is the update on how to do this currently? I have some C code already running graphics on a window and I'd like to embed neovim, if possible avoiding all RPC shenanigans. Having a library (static or dynamic) would be ideal but I don't know if there has been any movement besides what has been discussed here a few years back already.

If there is a current go-to approach for this could someone share it? I believe it would be useful for other people coming to this thread looking for something like this in the future.

Thanks for your time!

Cheers! 😄

Ruben.

**Comment by oakes** [comment]
@osor-io you may be interested in https://github.com/onivim/libvim

It uses the esy build tool which may complicate things, but the end result is a static library and it includes an API for sending input and executing commands.

**Comment by osor-io** [comment]
@oakes Thanks a lot! 😊 It looks interesting indeed, might have to go to that if I can't figure out a solution with neovim. Looks like the author of that would also like to be able to use neovim if he could.

Implementing ui.h like @tarruda suggested could prove slightly difficult as it's more like integrating current code into the neovim code instead of the opposite.

If there is a path to be able to get neovim to do this I'd gladly try to collaborate. Anywhere I can check possible plans on this? Maybe @justinmk knows more?

Apologies in advance for the inconvenience.

**Comment by justinmk** [comment]
we definitely are interested in maturing "libnvim" , but it's not planned soon. 

What _is_ planned and close to being realized is Nvim-as-a-RPC-client. So "RPC shenanigans" are done by Nvim, saving lots of hassle.

**Comment by marcthe12** [comment]
The ui.h style is good for simple gui frontends who do not need much stuff over gui like neovim-qt or neovim-gtk. They can use native controls/clipboard providers but do not need anything more and any extra stuff are done via plugins.

**Comment by justinmk** [comment]
# Status

Closing this because most of the discussion is outdated. 

Tracking issue for `libnvim`: https://github.com/neovim/neovim/issues/21693

> What _is_ planned and close to being realized is Nvim-as-a-RPC-client.

- Nvim as a reusable msgpack-rpc library is still TODO.
- However, Nvim 0.9 has enabled the Nvim TUI to work as a RPC UI client: https://github.com/neovim/neovim/pull/18375 . 
    - This means that `nvim --remote-ui ...` can connect to any Nvim server (via RPC)

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open an issue if you have new information/topics to discuss._
