### ISSUE TITLE
neovim is not respecting vim.cmd('noautocmd ...') in some circumstances

### ISSUE THREAD

**Issue by alanoliveira** [neovim/neovim#20450]
### Neovim version (nvim -v)

NVIM v0.8.0-1210-gd367ed9b2

### Vim (not Nvim) behaves the same?

I don't think it can be reproduced on vim

### Operating system/version

debian 5.10.0-18-amd64

### Terminal name/version

XTerm(366)

### $TERM environment variable

tmux-256color

### Installation

appimage

### How to reproduce the issue

Start nvim with `nvim --clean -u init.vim -c "e aaa | vs bbb"`, then press space to run the function.

```vim
" init.nvim
au BufEnter * echom "BufEnter " .. @%

lua << EOF
vim.keymap.set("n", "<space>", function()
	local curwin = vim.api.nvim_get_current_win()
	vim.cmd('noautocmd wincmd l')
	vim.api.nvim_set_current_win(curwin)
end)
EOF
```

### Expected behavior

Is expected the autocommand be suppressed by **noautocmd**, so the message `BufEnter bbb` should not be displayed. 

### Actual behavior

Autocommand is running regardless **noautocmd**.

### additional details

It interest to notice it works fine if the `vim.cmd` be executed after `nvim_set_current_win`
```
lua << EOF
vim.keymap.set("n", "<space>", function()
	local curwin = vim.api.nvim_get_current_win()
	vim.api.nvim_set_current_win(curwin)
	vim.cmd('noautocmd wincmd l')
end)
EOF
```

**Comment by seandewar** [comment]
isnt this due to the nvim_set_current_win() call returning to the original window?

**Comment by seandewar** [comment]
Had a look locally and this behaviour seems correct.
The autocmd is being triggered by the `nvim_set_current_win()` call switching from the window viewing into buffer `aaa` to the window viewing into buffer `bbb`.
If you remove `noautocmd` from `wincmd l`, you'll see that `BufEnter aaa` also fires before, and if you add `noautocmd` to `nvim_set_current_win()`, no BufEnters are fired.

> It interest to notice it works fine if the vim.cmd be executed after nvim_set_current_win
The reason it doesn't trigger in this case is because you're trying to switch to the same window, so no switch actually occurs.
