### ISSUE TITLE
Please show slow plugins

### ISSUE THREAD

**Issue by andreicristianpetcu** [neovim/neovim#2050]
Hello, 
Firefox Nightly just landed a way to show what plugins make it slow. I have ~20 FF plungins and I removed the offending 4 and now FF is blazing fast! I want something similar for Neovim :D
I have >100 plugins for Neovim/Vim I bet some of them make my text editor seriously slow (when working with large files this becomes really painful). Both Neovim and Vim are fast with large files if there are no plugins used. Is there a way to troubleshoot this type of issue? If not, can it be made into a feature?
Thank you for building this project!

**Comment by justinmk** [comment]
But firefox took 15 years to add that feature because it is not easy. It's a good idea, but we don't need more ideas, we need detailed requirements, specifications, and design.

**Comment by MarcWeber** [comment]
The way to go is liek VAM does it: Make it easy to activate code lazily
as needed or to deactivate plugins (eg bisecting) - so that you can find
the problem fast. What you ask for is not so easy because plugins could
be slow in very cumbersome conditions (eg long lines in .php files and
syn on) - so I'd even say its impossible.

Marc Weber

**Comment by tarruda** [comment]
Perhaps [this](http://vimcasts.org/episodes/profiling-vimscript-performance/) will help?

**Comment by andreicristianpetcu** [comment]
Ok, I understand. Thank you again for building Neovim! And thank you for the profiling vimscript link.
