### ISSUE TITLE
[Bug] expand('<sfile>') does not report a path in the current shell format when using git-bash on Windows

### ISSUE THREAD

**Issue by Adnn** [neovim/neovim#20603]
### Neovim version (nvim -v)

v0.8.0-1210-gd367ed9b2

### Vim (not Nvim) behaves the same?

no, vim v8.2.2859

### Operating system/version

Windows 10

### Terminal name/version

Windows Terminal 

### $TERM environment variable

xterm-256color

### Installation

scoop

### How to reproduce the issue

add `let myexpand` = expand('<sfile>') to your `init.vim`

Launch neovim, and issue command:

    :echo g:myexpand

### Expected behavior

I would expect a path that is understood by my current shell (bash):

    /c/Users/adn/.config/nvim/init.vim

### Actual behavior

Instead, I get a "Windows cmd" path:

    C:\Users\adn\.config\nvim\init.vim

Since VIM output the expected path (`/c/Users/adn/.config/nvim/init.vim`), I suppose this is not the intended behaviour.

**Comment by matveyt** [comment]
There's no such thing as "current shell format".

If Vim reports `/c/xxx` path then it must be msys/vim build. While Neovim is only built as native Windows application (in principle, it could be possible to build version for msys and/or cygwin but there's no support for this).

**Comment by Adnn** [comment]
Thank you for your response

> There's no such thing as "current shell format".

What I meant is there is a current value for `shell` within vim. And a shell expects paths to adhere to a certain format (something akin to `/c/foldertop/folderbelow` in the case of `git-bash`).

**Comment by matveyt** [comment]
First, msys apps, such as msys/bash, should handle _both_ path formats equally well (there could be some corner cases and bugs but that's a different story). So it is unlikely ever needed.

Second, _native_ windows apps, such as nvim, cannot handle posix-style paths themselves. Hence, you can't `:edit /c/foo/bar/baz`, it just won't work. And so it could _only_ make some sense to translate a path _before passing it as argument_ to such shell.

So if you really believe you need this for your config then implement it in VimScript. C source code doesn't help much in this case as a native application is not allowed to call msys dynamic libraries directly. And so you'll probably end up invoking something like cygpath tool anyway.

**Comment by erw7** [comment]
As matveyt explains, this behavior depends on whether the binary is a Windows-native binary or a binary that uses the POSIX emulation layer of MSYS2 (Cygwin). In other words, the behavior is determined at compile time and does not depend on the `shell` value. If you use the windows native vim that can be downloaded from this [page](https://www.vim.org/download.php#pc), you should find that vim (Windows-native) returns Windows paths instead of POSIX paths as well as neovim.

Although not recommended, if you really need neovim to be able to use POSIX paths, you will need to compile neovim yourself using `gcc` (in `/usr/bin`), which is included in the "Git for Windows SDK".

**Comment by justinmk** [comment]
> this behavior depends on whether the binary is a Windows-native binary or a binary that uses the POSIX emulation layer of MSYS2 (Cygwin). In other words, the behavior is determined at compile time and does not depend on the `shell` value.

Yes. OTOH, in https://github.com/neovim/neovim/issues/16957 we are considering whether it makes sense to have some dynamic decisions. Because if a single Windows binary works in both "Windows console" style terminals and unix-style, if there are only a few small changes needed, then it makes sense to do those changes rather than have separate binaries for separate shells/terminals.

**Comment by Adnn** [comment]
Thank you for the responses, this was enlightening!
