### ISSUE TITLE
 ":highlight Cursor" can't work.

### ISSUE THREAD

**Issue by buddhiko1** [neovim/neovim#20628]
### Neovim version (nvim -v)

0.8.0

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Archlinux x86_64

### Terminal name/version

alacritty (0.10.1)

### $TERM environment variable

xterm-256color

### Installation

build from repo

### How to reproduce the issue

":highlight Cursor guibg=red" can't work when you are in a night color scheme.

This command is available in version 0.7.2 but not in version 0.8.0.

### Expected behavior

![expect](https://user-images.githubusercontent.com/8435488/195473292-0bd24c90-176e-4433-948e-65b975c6297c.png)

### Actual behavior

![bug](https://user-images.githubusercontent.com/8435488/195473315-12390707-b311-4b8c-9912-fba0721cce41.png)

**Comment by zeertzjq** [comment]
What's you `'guicursor'` option?

**Comment by buddhiko1** [comment]
> 

Hi~
This is my guicursor option: `guicursor=n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20-Cursor`
 
In addition，the background color of cursor is changed in noice command wind, but not in text buffer.
![test](https://user-images.githubusercontent.com/8435488/195481565-cd5f300f-3ccf-424a-9e4f-53723116e459.png)

**Comment by buddhiko1** [comment]
> What's you `'guicursor'` option?

Hi~
This is my guicursor option: `guicursor=n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20-Cursor`
 
In addition，the background color of cursor is changed in noice command wind, but not in text buffer.
![test](https://user-images.githubusercontent.com/8435488/195481848-09a3f8fa-1ea8-42a8-9231-6c052acfdb52.png)

**Comment by erw7** [comment]
Bisected to 34d41baf8a8e4ab8c006b7f29a8106e60e311aa2.

`Cs` for `xterm-256color` is `\E]12;%p1%s\007`. Therefore, it should be necessary to set a string like `rgb:\x\{1,4}/\x\{1,4}/\x\{1,4}` (vim regular expression) with `unibi_var_from_str()`.

Ref. https://www.x.org/releases/X11R7.5/doc/man/man3/XParseColor.3.html#sect4

The current implementation should send `\E]12;\007` to the terminal. So, I do not believe that https://github.com/neovim/neovim/commit/34d41baf8a8e4ab8c006b7f29a8106e60e311aa2 will solve the foot problem.

Cc: @kraftwerk28.

**Comment by mg979** [comment]
https://github.com/neovim/neovim/issues/19607#issuecomment-1268458959

**Comment by buddhiko1** [comment]
This command work as expected when change from 'xterm-256color' to 'rxvt-256color'.

**Comment by mg979** [comment]
@buddhiko1 yes but you shouldn't be required to change the default TERM value for you terminal.

Currently cursor in xfce4-terminal-emulator (and probably others) is broken. Strangely it works fine in Iterm2 (also using `xterm-256color`. Anyway it worked fine in 0.7, not sure why it was changed.

**Comment by tomcur** [comment]
@erw7 is right. The relevant code for handling of `%p1%s` is here https://github.com/mauke/unibilium/blob/e3b16d6219ca1cb92d98b1d9cc416b49a3ac468e/unibilium.c#L1228-L1242.

Neovim sets numeric params and so `%p1` pushes a numeric param. The `%s` pops a string param. Both unibilium and ncurses default to an empty string in the case a numeric param was popped. xterm and Alacritty define `Cs` using `%p1%s`. Neovim currently defaults to `%p1%06x` if `Cs` is missing in terminfo for these terminals, which correctly formats the numeric param it sets: these terminals expect "legacy" hex color input like `#0099ff` or input like `rgb:00/99/ff`.

That's why setting `TERM=rxvt-256color` works: rxvt's terminfo doesn't specify `Cs`.

Perhaps the better behavior would be for Neovim to set a hex color string param, but I'm not sure if there's some broader convention for parameters to `Cs` (or any "user-defined" terminfo capability for that matter).
