### ISSUE TITLE
Idea: Let us make lowercase commands if they don't already exist in neovim?

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2095]
Having to type uppercase letters to start a command is :-1:.

### Bad:

```
:MyCommand
```

### Good:

```
:my-command
```

or

```
:my_command
```

or

```
:mycommand
```

The idea would be to allow us to override builtin commands (just like we can basically anywhere else and no one complains), or throw an error.

**Comment by justinmk** [comment]
This would be a huge breaking change to vimscript. It also has performance implications which @ZyX-I has alluded to.

**Comment by trusktr** [comment]
How would it break vimscript?

Performance only depends on the implementation chosen.

**Comment by Pyrohh** [comment]
Just a guess, but if you have two lookup tables, one for internally defined commands, one for external, you could determine which table to use depending on the case of the first character for the supplied command string, presumably resulting in lower latency lookups. Again, this is just a guess, so you'd have to ask @ZyX-I.

**Comment by ZyX-I** [comment]
@trusktr 

> The idea would be to allow us to override builtin commands (just like we can basically anywhere else and no one complains), or throw an error.

Overriding builtin commands is a breaking change. *Not* overriding builtin commands mean that update may break plugins which create new lowercase letter commands because plugin’s lowercase command was replaced with NeoVim one.

Also I would not say “nobody complains”.

1. For typed commands you may use `noremap` and `normal!`. This is one of the “best practices” mentioned by any sane book talking about plugin development. I do not like remappable behaviour being the default, but you can **not** override built-in commands.
2. Commands can be overridden and nobody complains only because plugin commands almost always look like `{Prefix}{Command}` or are at least just `{Prefix}` (where Prefix has something to do with a plugin name) and thus names do not collide.
3. There are script-local functions and API or cross-file functions again use `{prefix}{name}` (though now prefix may have something to do with autoload functions). Yet you can see my frawor which hides *everything* it can: as long as some function is intended to be used only from plugins (even if it is API function) you can make it anonymous which means that you may not do or may do, but with ugly hacks, many things with it witohut receiving function reference pointing to it.

    And functions cannot override built-in functions.

I cannot possibly vote for your suggestion without adding proper scopes to NeoVim. Now all functions (including anonymous ones), commands, mappings, … are global and things like extended-funcref branch or VimL->Lua translator can only do something with anonymous functions and function references, still leaving the main problem intact. I do not like the idea of seeing *everything* break because some dunderhead has redefined `:function` in his plugin and made a mistake in new definition that allows it to work only in his plugin. Currently the amount of damage that can be dealt is very limited, and amount of damage that can be dealt unintentionally is even lower.

Also note that straightforward implementation makes it possible to create an unrecoverable breakage: e.g. redefine `command` and `delcommand` to no-op and watch how you can’t define commands any longer up until restarting NeoVim. Non-straightforward requires non-redefineable addition of `:builtin` command which will run its argument, disabling all `:command` definitions.

And the last note: `:command` defines a way its argument is parsed. I am already not much fond of the hacks I am going to need to handle user commands in the translator (specifically deferring handling of the user commands to runtime in place of doing this in the parser). Adding an ability to redefine builtin commands will make VimL *completely unparseable **in advance***.

**Comment by ZyX-I** [comment]
@Pyrohh Built-in commands will be parsed at the parsing stage, and will later be compiled to something fast (i.e. bytecode of some VM, if VimL->Lua survives the practice then it will be VimL->Lua->LuaJIT bytecode), can be cached to FS (like Python does with its \*.pyo/\*.pyc files (former is generated at request, latter is generated automatically always unless disabled)). User commands parsing will be deferred until the time code is actually run and I cannot do anything with this as I do not know how to parse user command until it is defined (== at runtime).

Current situation is that you indeed have two tables selected depending on the first character. But I can easily imagine it being one table (one even with `:builtin`: this command needs to switch pointer to the table to the builtin one while used table may be a mix of builtin and user commands).

**Comment by ZyX-I** [comment]
Another note just came up to my mind: allowing to override lowercase built-in commands requires clear definition of what will happen with abbreviations then: e.g. what `ed` will do if `:edi` command was defined (currently `:edi` stands for `:edit`).

**Comment by Pyrohh** [comment]
> I cannot even do anything with this after they are defined: user commands may be redefined. There is some possibility of optimization (== compile at the definition and add a hook which will trigger recompiling on redefinition), but that would be hard to do right given the existence of abbreviations (== ability of the user to type only the first unambiguous part of the command).

Thank you for explaining, but I'm curious about what you said regarding how abbreviations and shorthand command names complicate things. Keep in mind this is from my idealistic point of view, as I don't actually know how this is implemented in nvim (or your luaviml branch).

I would think that abbreviating a command would be completely separate from any actual command parsing, i.e. `:cabbrev yeye buffers` wouldn't have any relation to the `buffers` command besides having its name; as far as the nvim command line is concerned, `yeye` just an arbitrary string which should be changed to `buffers` when recognized. As I said, this is conjecture, so might be wrong.

**Comment by ZyX-I** [comment]
@Pyrohh I did *not* mean `*abbrev` commands. See `:h 20.2`: section “Command line abbreviations”.

**Comment by Pyrohh** [comment]
I see, my mistake.

**Comment by ZyX-I** [comment]
By the way, I did not say they complicate the parser. I said that it requires clear definition. I do not expect abbreviations complicate parser, but this depends on the definition.

They clearly will significantly complicate the “user” parser (i.e. increase cognitive load when reading code).
