### ISSUE TITLE
backwards compatibility with vim, error handling.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2103]
My saved session from MacVim contains

```
set fullscreen
```

~~Vim ignores this and continues without error, but~~ NeoVim throws an error complaining that the command doesn't exist (makes sense since we can have TUIs or GUIs connected to it so there won't be a sense of "fullscreen" for neovim itself, only for each UI).

I think generically better handling would be to just ignore it ~~the same way Vim does~~, instead of ~~removing it and~~ throwing errors. Perhaps sessions can be generated using `silent!` in front of unknown commands?

**Comment by trusktr** [comment]
Same thing with this error:

```js
E319: Sorry, the command is not available in this version: winpos 0 23
```

I feel these things should be handled differently, so that vim users can transition to neovim without problems.

**Comment by Pyrohh** [comment]
What version of Vim are you using? Vim `7.4.617-1` and nvim from master throw the same errors for me, for both of your examples. Is the `fullscreen` option exclusive to MacVim?

If so then I'm not sure we should provide a no-op for it as that would mean we should provide no-ops for all other MacVim options, unless there are only a few MacVim exclusive options to cover.

**Comment by trusktr** [comment]
@Pyrohh You're right, Vim is complaining. I hadn't noticed this before. In the general case it makes sense if the user is trying a non-existing command in the vim/neovim command line that an error should be displayed. Since sessions are automatically generated, maybe the fix is to simply preceded all commands with `silent!` since the user doesn't really care what's in the session fil?.

**Comment by Pyrohh** [comment]
> Since sessions are automatically generated, maybe the fix is to simply preceded all commands with silent! since the user doesn't really care what's in the session file?

I'm honestly not sure, as I have no experience with vim's session feature :stuck_out_tongue_closed_eyes:

**Comment by ZyX-I** [comment]
@trusktr I do not think this is good idea. Silencing some things like `:e` (sessions use something different AFAIR, but that is not the point) is bad because if file cannot be read user should know.

But since sessions are automatically generated it is fine to create many `:try`/`:catch` blocks (for options: better wrap with `if exists('+option')`) and protect from *certain* errors. Only you should go with this suggestion to MacVim community first, *not* to NeoVim because it is MacVim who creates these session files.

**Comment by trusktr** [comment]
NeoVim is the future of Vim in my eyes so I don't want to waste time posting issues for MacVim. I agree, certain errors do need to be displayed. Overall, session management would be better not failing due to non-existent commands between version of vim. It's some generic type of solution. I don't have the time to do it, unfortunately, but hopefully someone does!

**Comment by ZyX-I** [comment]
@trusktr You *can’t* solve this kind of errors by patching NeoVim in any fashion. You can make NeoVim session files in a fashion so that they don’t emit errors, but that’s useless because problem is NeoVim opening MacVim session files, not the opposite. You can as well silence all or some errors from foreign session files, but this is wrong as well: *you* know that `set fullscreen` is insignificant, *NeoVim* can’t know this. And errors from session files do no more harm then bugging you unless session sourcing is put into `try…catch` which is not with `-S`.

So I am closing it:

1. `set fullscreen` without a fullscreen option is an error and only user knows how significant it is, so NeoVim must not silence it by default.
2. This error does not prevent session file from being useful, so it is not even worth bothering.
3. The error is from session files that do not belong to NeoVim, so initial suggestion (put `silent!` in front of commands) is wrong.

**Comment by trusktr** [comment]
> `set fullscreen` without a fullscreen option is an error and only user knows how significant it is, so NeoVim must not silence it by default.

Understandably, you'd want vimscripts written by users to throw errors, but session files aren't written by users.

Also, sessions don't always get loaded properly after these errors.
