### ISSUE TITLE
`print` should only send one `msg_show` event with `ext_messages`

### ISSUE THREAD

**Issue by folke** [neovim/neovim#21044]
### Feature description

Right now if you do something like the below, a separate `msg_show` event will be created for every line in the `print` output.

It would be better to get all the content in one `msg_show` event. This is already the case for most commands like `:ls`.

```lua
print(vim.inspect({a=1, b=2}))
```

**Comment by AzerAfram** [comment]
Hello, should I help out here? If so, what file should I look into?

**Comment by zeertzjq** [comment]
In `src/nvim/lua/executor.c`, there is:
```c
        // TODO(bfredl): use proper multiline msg? Probably should implement
        // print() in lua in terms of nvim_message(), when it is available.
```

**Comment by AzerAfram** [comment]
First of all, thank you for your response, but I have a question. 


This is the output I currently get for the above command  (`lua print(vim.inspect({a=1, b=2}))`):

![Screen Shot 2022-11-14 at 7 23 27 PM](https://user-images.githubusercontent.com/97570339/201818960-713ba0e4-1859-4bff-85e5-2e240dc2f006.png)



If I we were to put all content ('a' and 'b' in this case) into one `msg_show` would the output of the above command change in any way?

**Comment by folke** [comment]
Now we get multiple msg show events each with a newline. Ideally it should be one msg show event including the newlines, so should look the same as in your example

**Comment by bfredl** [comment]
I think the function could be changed to use `msg_attr_keep` with multiline=true. it still needs to handle embedded NUL:s somehow.

**Comment by AzerAfram** [comment]
Okay, one last question (hopefully). 

What exactly is getting passed in as the argument vector in the class `nlua_print_event` in `src/nvim/lua/executor.c` on line 874:

    `static void nlua_print_event(void **argv)`


I am confused on this because of the following 2 lines:

    `char *str = argv[0];
     const size_t len = (size_t)(intptr_t)argv[1] - 1;  // exclude final NUL`

We don't seem to be using all indexes in the argument vector. Or does the vector always have a length of 2?

**Comment by zeertzjq** [comment]
> Or does the vector always have a length of 2?

Yes.

**Comment by AzerAfram** [comment]
In that case I don't think the issue has anything to do with the `lua print` function. How so? Well the `lua print` function simply displays what was evaluated by (output of) `vim.inspect()`. So assuming that `:lua print`, similarly to `:ls`, displays all outputs as efficiently as possible, than the issue is rooted in the input of `lua print()`. If so, then the solution should come with an appropriate change to: `/runtime/lua/vim/inspect.lua`. 

Feel free to acknowledge any doubts.

**Comment by bfredl** [comment]
> So assuming that :lua print, similarly to :ls, displays all outputs as efficiently as possible,

It has been made efficient for internal message printing (i e in the TUI), but not yet with ext_messages.

**Comment by AzerAfram** [comment]
Alright, I have two questions then:

  Do the commands `lua print(2)` and/or `lua print(2*3)` print an internal message?

  Do all external messages in a `print()` take the form of: `lua print(vim.inspect(...))`?

**Comment by zeertzjq** [comment]
Whether message is internal or external has nothing to do with what is printed.

**Comment by AzerAfram** [comment]
How do I enable `ext_messages`?

**Comment by folke** [comment]
@azerafram see example code at https://github.com/neovim/neovim/issues/21068
