### ISSUE TITLE
incorrect kill+paste behavior with clipboard=unnamed

### ISSUE THREAD

**Issue by zachariahreed** [neovim/neovim#2105]
Killing a line and then pasting with `p` pastes text I killed two times ago instead of the most recent instance. Pasting with `]p`, however, works correctly and also causes a subsequent `p` to past the correct text.  With `clipboard=`, I am not seeing this behavior.

(version a4c3ac2799281b56c1c38d0fdc584e22ac1b3d2f).

**Comment by bfredl** [comment]
@zachariahreed What OS do you run `neovim`? (Asking since #2077 might be related, but it is only implemented for X11 and not OSX so far)

**Comment by zachariahreed** [comment]
This is using X11. I just tried applying the changes in #2077, but I still the same behavior.

**Comment by bfredl** [comment]
Do you use any clipboard-related plugins? if you use `"*y`/`"*p` or `"+y`/`"+p` directly is it the same problem?

**Comment by abasak** [comment]
I was also facing the exact same problem and came here to report it. I had [vim-yankstack](https://github.com/maxbrunsfeld/vim-yankstack) plugin installed, which I disabled after seeing the last comment and the behavior is back to normal again.

I am using OX and installed neovim using homebrew (version [2d65ccf](https://github.com/neovim/neovim/commit/2d65ccf))

**Comment by zachariahreed** [comment]
Yes, this does seem to be an interaction with a clipboard plugin (in this case YankRing). Using the commands `"*dd"*p`, `dd"*p`, and `dd[p` all work as expected with the plugin enabled, as do as all yank variants. It is only `ddp` (and similar delete motions) that seems to be problematic. For the time being there's no issue in disabling this plugin, but what's the plan for dealing the combination of clipboard providers and clipboard plugins in the future?

**Comment by bfredl** [comment]
It is definitely a bug, any clipboard plugin in `vim` should also work in `nvim`. I can't reproduce with `yankstack` + `clipboard=unnamed` right now but I will investigate more later (I override some keybindings in `yankstack` right now)

**Comment by pignatenko** [comment]
Just FYI with the new clipboard provider and clipboard=unnamed some registers will fail to work properly, for example non-drop "0p won't work correctly. Not sure if this has been reported but there's just so many bugs in the new copy/paste system

**Comment by bfredl** [comment]
@pignatenko could you post instructions to reproduce ?

**Comment by pignatenko** [comment]
There used to be 2 things I think one was already patched out as I upgraded nvim recently the one that was patched was:

1. Make sure clipboard has unnamedplus in it.
2. Find a line to yank
3. Drop a line.
4. "0p from no-drop buffer
5. Get dropped line instead of yanked.

2nd problem which still exists is that the clipboard integration copies the system clipboard to the no-drop buffer after pasting in vim.

Ex:

1. Copy in vim.
2. Drop in vim.
3. "0p in vim should yeild  step 1.
4. Copy in system.
5. "0p should yeild step 1.
6. p should yeild step 4.
7. "0p should yeild step 4.

**Comment by pignatenko** [comment]
There used to be 2 things I think one was already patched out as I upgraded nvim just yesterday the one that was patched was:

1. Make sure clipboard has unnamedplus in it.
2. Find a line to yank
3. Drop a line.
4. "0p from no-drop buffer
5. Get dropped line instead of yanked.

2nd "problem" which still exists is that the clipboard integration copies the system clipboard to the no-drop buffer after pasting in vim.

Ex:

1. Copy in vim.
2. Drop in vim.
3. "0p in vim should yeild  step 1.
4. Copy in system.
5. "0p should yeild step 1.
6. p should yeild step 4.
7. "0p should yeild step 4.

Not sure what expected behavior should be for that one, it's sort-of jarring though.

**Comment by bfredl** [comment]
Can confirm, and I will look into fixing it.

**Comment by bfredl** [comment]
@pignatenko Does #2244 fix this for you?

**Comment by pignatenko** [comment]
Works so far.

**Comment by bfredl** [comment]
@zachariahreed Would you mind testing this on latest master again? ( I have not explicitly tested this, but it could be related to some of the fixes already done to master)

**Comment by elmart** [comment]
Works for me. Thanks!

**Comment by zachariahreed** [comment]
I still see the behavior originally reported using the current head ( 5f3eeadd037e111e8ba5b04d39ff69806899ed6c)

**Comment by elmart** [comment]
Must be X11 related. I can confirm it works for me on OS X 10.10.2.

**Comment by bfredl** [comment]
I think I have fix for the `ddp` issue (will push PR later), but `YankRing` + `clipboard=unnamed` doesn't work with unnamed paste (from external copy) with nvim for me...

**Comment by bfredl** [comment]
@zachariahreed could you try #2381 ? It fixes some issues with `YankRing` in my testing.

**Comment by zachariahreed** [comment]
@bfredl I didn't run through all possible commands but #2381 looks like it does correct the reported behavior

**Comment by bfredl** [comment]
#2381 is now on master. Please reopen if there still is some issue.
