### ISSUE TITLE
Cursor is not visible in `:terminal`

### ISSUE THREAD

**Issue by orhun** [neovim/neovim#21074]
### Neovim version (nvim -v)

0.8.1

### Vim (not Nvim) behaves the same?

no, vim 9.0.0814

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.11.0 (8dbaa0bb)

### $TERM environment variable

xterm-color

### Installation

Arch Linux community repository

### How to reproduce the issue

nvim --clean
`:terminal`
\<see that the cursor is either not visible or wonky\>

### Expected behavior

`vim`:

![rec_20221116T004108](https://user-images.githubusercontent.com/24392180/202032148-b22323d4-6c22-4507-a577-12e70d027473.gif)

### Actual behavior

`nvim --clean`:

![rec_20221116T004028](https://user-images.githubusercontent.com/24392180/202032033-4eb84cc7-1117-448d-8f25-03688e9f1846.gif)

**Comment by clason** [comment]
That is intentional (if I understand this issue correctly; it's a bit hard to tell -- videos show less than people seem to think...): like any buffer, the terminal buffer starts in normal mode and you need to press `i` to enter insert (or, rather, terminal) mode. This is one of the few major intentional differences between Vim and Neovim.

If you want to have terminal mode by default when you open one, you can easily use an autocommand like
```lua
vim.api.nvim_create_autocmd('TermOpen', { command = 'startinsert' })
```

**Comment by clason** [comment]
Hmm, that doesn't happen here. Probably related to the terminal (alacritty). Can you try with a different one?

**Comment by orhun** [comment]
I tried with different terminal emulators (and shells) but no luck :/
I tried deleting the `~/.cache`, hoping it might affect, but that didn't work also.

**Comment by clason** [comment]
That's strange. Which terminal emulators did you try? Are you using wayland/GPU acceleration/etc.? Does Nvim 0.8.0 (or 0.7.0) work?

**Comment by orhun** [comment]
> Which terminal emulators did you try?

I tried:
- [xterm](https://en.wikipedia.org/wiki/Xterm)
- [wezterm](https://github.com/wez/wezterm)
- [rxvt-unicode](https://wiki.archlinux.org/title/Rxvt-unicode)
- [kermit](https://github.com/orhun/kermit)

> Are you using wayland/GPU acceleration/etc.?

No.

> Does Nvim 0.8.0 (or 0.7.0) work?

I'm having the same issue with both versions.

**Comment by clason** [comment]
That's very strange then. With such a standard setup and such old versions, someone else surely would have reported this before. Maybe somebody else has a better guess what's going on.

**Comment by clason** [comment]
Also, try the appimage from the releases page. Distro builds can be... weird.

**Comment by zeertzjq** [comment]
Maybe this is a problem with your alacritty configuration? Does it work with `alacritty --config-file /dev/null`?

**Comment by orhun** [comment]
> Also, try the appimage from the releases page or [build from source yourself](https://github.com/neovim/neovim/wiki/Building-Neovim). Distro builds can be... weird.

I will try building it from source and post results.

> Maybe this is a problem with your alacritty configuration? Does it work with `alacritty --config-file /dev/null`?

Nope, it didn't work :/

**Comment by orhun** [comment]
Built from source, still having the same cursor issue on the terminal. Investigating...

**Comment by zeertzjq** [comment]
Is the cursor still invisible if you run some other program inside `:terminal`, e.g. `:terminal cat`?

**Comment by zeertzjq** [comment]
`xterm-color` doesn't look right. Should it be `xterm-256color`?

**Comment by orhun** [comment]
> `xterm-color` doesn't look right. Shouldn't it be `xterm-256color`?

That was it! Thank you so much ❤️

**Comment by alma3lol** [comment]
Hi,
I'm having the same issue. I changed nothing in my config and thought maybe my computer needs an update.
After reading thought issue and comments above, I tried:

> Faster way to reproduce is `SHELL=/usr/bin/sh nvim --clean +terminal`

It showed me that the problem is not:

> `xterm-color` doesn't look right. Shouldn't it be `xterm-256color`?

but, the shell it self. **At least for my case.**
I'm using `zsh`. When I use `bash`, the issue is gone.

I'm going to investigate `zsh` as the number 1 reason for the cursor disappearing is using it. Again, **at least for my case.**

If there's something that could be done other that switching to a different shell, that would be great.

**Comment by alma3lol** [comment]
44 minutes into investigation and I found what the issue is.
The highlight groups `TermCursor` and `TermCursorNC` are  the ones that cause the disappearing if you set them to `NONE` on both `guifg` and `guibg`.
Setting both of them to either `guifg=#ffffff` or `guibg=#ffffff` will resolve the problem. But.... any theme can set them which appeared to me that a theme I'm using actually either set them or reset them (idk what the default value is).
