### ISSUE TITLE
setting install prefix

### ISSUE THREAD

**Issue by danielb2** [neovim/neovim#2111]
I went into change the build/Makefile and added `cmake -DCMAKE_INSTALL_PREFIX=/...` to get the install location I wanted.

Is there an easier way to do this?

**Comment by jszakmeister** [comment]
`CMAKE_EXTRA_FLAGS` is used by the Makefile to pass extra arguments to the CMake invocation.  So you can do `make CMAKE_EXTRA_FLAGS=-DCMAKE_INSTALL_PREFIX=/path/to/install/location`.  I put this in my local.mk to make sure it's set:

```make
CMAKE_EXTRA_FLAGS := -DCMAKE_INSTALL_PREFIX=/usr/local/neovim-latest
```

So I don't have to set it up myself all the time.

**Comment by danielb2** [comment]
thanks.  Would be nice if I could do just gmake -DPREFIX=...

**Comment by Pyrohh** [comment]
@jszakmeister would you object to me submitting a PR with an example `local.mk` and some documentation for using it? Its currently undocumented.

**Comment by danielb2** [comment]
I should note that I ended up having to install it in the default prefix, because when meddling with it the way I was doing it, the syntax files weren't found

**Comment by jszakmeister** [comment]
It's not much documentation, but is [mentioned on the wiki](https://github.com/neovim/neovim/wiki/Building-Neovim#custom-makefile).

> @jszakmeister would you object to me submitting a PR with an example local.mk and some documentation for using it? Its currently undocumented.

What would you call the file?  I'd definitely object to calling it `local.mk`, since that would mean we'd be editing a file under version control and stuffing our personal customizations into it.  I think it should probably be in the wiki rather than checked into the tree, but I'm on the fence.

Note: I don't consider the Makefile the "official" way to build Neovim.  I consider using CMake the official way to do it.  The Makefile is really there to help you get going.

**Comment by jszakmeister** [comment]
@danielb2 

> should note that I ended up having to install it in the default prefix, because when meddling with it the way I was doing it, the syntax files weren't found

CMake builds in two steps: a configuration step and a build step.  It may be that you had already configured the build, so your new setting wasn't picked up.  If you clean (`make distclean`) and try again, it probably would have worked fine.

**Comment by Pyrohh** [comment]
@jszakmeister how about `local.mk.example`? There could be a comment added above `-include local.mk` in `Makefile` mentioning it.

**Comment by jszakmeister** [comment]
@Pyrohh Sure, lets see what you put together.

**Comment by jszakmeister** [comment]
> Would be nice if I could do just gmake -DPREFIX=...

It would be `gmake PREFIX=...`, and you would still have the same issue as above (having your build configured and then attempting the change it).

Also, I purposefully avoided common things like this to avoid conflicts when building dependencies.  Variables have a way of leaking down into other contexts and ruining what you're trying to do.  In this case, Luarocks and friends will install into your prefix rather than the deps area it was supposed to, breaking the build, and littering the install area with pieces that should not be there.
