### ISSUE TITLE
Highlight bug on long lines in xml file

### ISSUE THREAD

**Issue by lahwran** [neovim/neovim#2123]
I found this while viewing an svg file exported from illustrator. If you have long lines in an xml file, and you have a string that wraps between lines, but the start of the string is off the right edge of your screen, you will get incorrect highlight.

![Highlight error](http://i.imgur.com/p2Q9wPf.png)

``` xml
<a                                                                  x="                                
                            "/>
<dfsa x="fds dfs sadf fdsaasdf  fdsasdf fdsasdf fdsaasdf fdsaasdf fdsasdf fdsaasdf fdsaadsf fdsadsf fdsa"/>
```

**Comment by justinmk** [comment]
Vim has identical behavior.

**Comment by lahwran** [comment]
from what I've learned about vim's syntax highlighting, this is probably just vim's syntax highlighting approach being awful. I imagine this will end up being fixed with some eventual rewrite of nvim's syntax highlighting.

**Comment by dundargoc** [comment]
Syntax highlighting is done through runtime files, which Neovim doesn't maintain. This issue thus belongs to Vim's repository (but you shouldn't open issues about runtime files in Vim - see this [document](https://github.com/vim/vim/blob/master/CONTRIBUTING.md#syntax-indent-and-other-runtime-files) to learn what to do).

I'm also pretty sure this has already been resolved since I couldn't recreate the problem in neovim nor vim.
