### ISSUE TITLE
nvim_get_chan_id, or return channel id from nvim_set_client_info

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#21291]
### Feature already in Vim?

N/A

### Feature description

Right now you can call `nvim_get_api_info` to get the channel ID and the API metadata, but often you want these pieces of information at different times - the channel is relevant when you're running the plugin, while the API metadata is mostly relevant for generating API bindings. The API metadata still may be relevant at runtime for validation purposes, but libraries that choose not to do this validation (instead letting invalid calls result in error responses from Neovim) only need the channel ID.

**Comment by bfredl** [comment]
Not a priority but a complete PR with docs and tests will be accepted.

**Comment by KenCox94** [comment]
I have some code ready for this just wanted to ask a question before I updated docs -- no much in the way of that btw.

I see:
```
assert( channel_id <= INT64_MAX );
ADD_C(rv, INTEGER_OBJ((int64_t)channel_id));
```
in nvim_get_api_info

Since mine is just returning to caller, can I add a `UInteger` type in defs.c or would it be preferable for me to make that assertion and then cast and return?

**Comment by justinmk** [comment]
> can I add a `UInteger` type in defs.c or would it be preferable for me to make that assertion and then cast and return?

assertion is preferred. API types are mostly 1-to-1 with msgpack and we don't want to add more requirements for clients.

**Comment by justinmk** [comment]
> maybe the channel ID should just be returned by `nvim_set_client_info`,

I forgot that `nvim_set_client_info` returns `void` (instead of a Dict). Because of `:help api-contract` we can't change that. 

Instead, we could make `nvim_get_chan_info(0)` (that is, "zero" means "current channel") work.

**Comment by andrewwillette** [comment]
Hey all, I'm working on this issue and had a question I'm hoping you might be able to help me with.

I'm attempting to get the "current channel" in order to return when `nvim_get_chan_info` is called with `0`.

[Here's my code](https://github.com/andrewwillette/neovim-willette/blob/issue_21291/src/nvim/api/vim.c#L1627). My best bet right now, but it appears to be wrong, is to access the [current_channel_id](https://github.com/andrewwillette/neovim-willette/blob/issue_21291/src/nvim/globals.h#L338) variable. I'm seeing that value as `0` in the logs though, regardless of how I call the function (lua API or RPC calls from python code).

I'm guessing I'm going about getting the "current channel id" incorrectly. Could you point me in the right direction?

Thank you, I really appreciate your time / help.
