### ISSUE TITLE
Question: Configuration files in /etc

### ISSUE THREAD

**Issue by toupeira** [neovim/neovim#2134]
I'd like to use my Vim configuration in `/etc/vim` and tried symlinking it to `/usr/share/nvim/vimfiles` (as with `/usr/share/vim/vimfiles` on Debian), but this resulted in weird errors from some plugins ("E31: No such mapping"). Symlinks in `/etc/nvim` or `/etc/nvimrc` don't seem to get picked up either. The only way I got it working was with links in `~/.nvim` and `~/.nvimrc`. (tried both with current master and the PPA package, same behaviour)

Is there a way to have configuration files in `/etc`?

**Comment by rainerborene** [comment]
Neovim code base has the [`SYS_VIMRC_FILE`](https://github.com/neovim/neovim/blob/master/src/nvim/os_unix_defs.h#L102) constant value set to `$VIM/nvimrc` path. But on Vim repository the [`SYS_VIMRC_FILE`](https://github.com/b4winckler/vim/blob/7babc8007dc9c15dd7d11bbcfdf7d9aa870a480c/src/feature.h#L934) constant is commented with the right value `/etc/vimrc`. what do you think @tarruda?

**Comment by tarruda** [comment]
I'm not sure why it was changed to `$VIM/nvimrc`, cc @justinmk.

Since we are touching this subject, it might be a good idea to have a `$NVIMPREFIX` variable that is set to:

- the parent directory of the executable directory(bin/..) when the platform supports getting the executable path(`uv_exepath` can be used for that)
- the installation prefix if the exepath cant be detected

Then `$SYS_VIMRC_FILE` can be set to `$NVIMPREFIX/etc/nvimrc` and `$VIMRUNTIME` to `$NVIMPREFIX/share/nvim/runtime`

This is compatible with the current behavior and and makes nvim installation portable

**Comment by justinmk** [comment]
> `$NVIMPREFIX` ... the parent directory of the executable directory(bin/..) when the platform supports getting the executable path

Unless I'm mistaken, that's what `$VIM` is for. See https://github.com/neovim/neovim/pull/2011#discussion_r25407902 and `:help $VIM`.

As for `SYS_VIMRC_FILE`, it's been like that since Neovim's start.

> makes nvim installation portable

Item 3 in `:help $VIM` alludes to that use case. I guess we should change it to `$NVIM` in our case though.

> But on Vim repository the SYS_VIMRC_FILE line is commented with the right value /etc/vimrc

I don't know what the significance of a commented-out line is, but, like with many of these things, we need someone to compare the various Vim os_win32/unix/mac strategies and think of how it fits with Neovim's goals.

**Comment by justinmk** [comment]
Reworked by XDG adoption. https://github.com/neovim/neovim/pull/3120
