### ISSUE TITLE
ctermbg, ctermfg vs. guibg, guifg

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2140]
Seeing as how nvim will no longer distinguish between terminal and graphical UIs, what will be the expected way to set colorschemes accordingly? Is there a plan for colorschemes in general?

**Comment by doppioandante** [comment]
There was an open issue, but ti was closed because it became too long: https://github.com/neovim/neovim/issues/793

**Comment by mtglsk** [comment]
Most colorschemes bundled with vim are just awful in terminal, unless you install CSApprox...

**Comment by justinmk** [comment]
I believe `cterm/bg/fg` can be ignored (@tarruda correct me if I'm wrong). We could add an option to force the use of `cterm`; but if ignoring `cterm` allows us to remove a lot of redundant code, we should do that instead.

**Comment by tarruda** [comment]
> I believe cterm/bg/fg can be ignored (@tarruda correct me if I'm wrong). We could add an option to force the use of cterm; but if ignoring cterm allows us to remove a lot of redundant code, we should do that instead.

This is how it works: When a UI is attached, it passes a "rgb" boolean parameter that tells nvim which kind of color/attributes should be sent.  gui* attributes will be sent if rgb is true, cterm* attributes will be used otherwise.

Color schemes can be written in the same way as for vim, the difference is that cterm* and gui* are not mutually exclusive. So the color scheme should not check for `&term` or `has('gui_running')` because nvim will select the right attributes for each connected UI.

**Comment by mtglsk** [comment]
What about `gui=undercurl` for example? There is no such thing in terminals...

**Comment by tarruda** [comment]
Undercurl results in underline being set: https://github.com/neovim/neovim/blob/master/src/nvim/tui/tui.c#L242-L244

**Comment by frankier** [comment]
@tarruda: Would the following scheme make things backwards compatible with colourschemes that check gui_running? (Assuming this is considered useful - at least for the time being.)

1. Change the colourscheme command to just set an internal variable.
2. Actually execute the colourscheme every time a UI is attached.

**Comment by tarruda** [comment]
@frankier that seems like a reasonable alternative, could you create an issue with that suggestion so it's easier for me to track it?

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/2781
