### ISSUE TITLE
uv_tty_set_mode failed: invalid argument

### ISSUE THREAD

**Issue by lobanov4real** [neovim/neovim#21445]
### Neovim version (nvim -v)

NVIM v0.9.0-dev-514+g72a19b2ff

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 11 21H2

### Terminal name/version

Windows Terminal 1.15.3466.0

### $TERM environment variable

PowerShell 7.3.1

### Installation

scoop install neovim-nightly

### How to reproduce the issue

1. Open C:\Users\Ivan\AppData\Local\nvim-data\Log
2. Always got this (every run):  ERR 2022-12-16T22:21:23.505 nvim.2232.0 terminfo_start:361: uv_tty_set_mode failed: invalid argument

### Expected behavior

No errors in Log file.

### Actual behavior

Every run nvim write error in Log:
ERR 2022-12-16T22:21:23.505 nvim.2232.0 terminfo_start:361: uv_tty_set_mode failed: invalid argument
ERR 2022-12-16T22:22:37.671 nvim.14164.0 terminfo_start:361: uv_tty_set_mode failed: invalid argument
ERR 2022-12-16T22:22:52.713 nvim.11460.0 terminfo_start:361: uv_tty_set_mode failed: invalid argument
ERR 2022-12-16T22:26:41.887 nvim.12108.0 terminfo_start:361: uv_tty_set_mode failed: invalid argument
ERR 2022-12-16T22:27:04.220 nvim.13368.0 terminfo_start:361: uv_tty_set_mode failed: invalid argument
ERR 2022-12-16T22:30:14.650 nvim.8680.0 terminfo_start:361: uv_tty_set_mode failed: invalid argument
ERR 2022-12-16T22:30:48.285 nvim.10268.0 terminfo_start:361: uv_tty_set_mode failed: invalid argument
ERR 2022-12-16T22:32:05.827 nvim.8648.0 terminfo_start:361: uv_tty_set_mode failed: invalid argument
ERR 2022-12-16T22:32:33.527 nvim.1536.0 terminfo_start:361: uv_tty_set_mode failed: invalid argument

**Comment by lobanov4real** [comment]
It's same on Neovim stable

**Comment by lobanov4real** [comment]
I have installed plugins:
packer.startup(function(use)
  use 'wbthomason/packer.nvim'
  use {
    'svrana/neosolarized.nvim',
    requires = { 'tjdevries/colorbuddy.nvim' }
  }
  use 'nvim-lualine/lualine.nvim' -- Statusline
  use 'nvim-lua/plenary.nvim' -- Common utilities
  use 'kyazdani42/nvim-web-devicons' -- File icons
  use 'nvim-telescope/telescope.nvim'
  use 'nvim-telescope/telescope-file-browser.nvim'
  use 'windwp/nvim-autopairs'
  use 'windwp/nvim-ts-autotag'
  use 'Yggdroot/indentLine'
  use 'mtdl9/vim-log-highlighting'
  use 'numToStr/Comment.nvim'
  use { 'akinsho/nvim-bufferline.lua', tag = "v3.*", requires = 'nvim-tree/nvim-web-devicons' }
  use {
        'nvim-treesitter/nvim-treesitter',
        run = function()
            local ts_update = require('nvim-treesitter.install').update({ with_sync = true })
            ts_update()
        end,
    }
  use 'norcalli/nvim-colorizer.lua'
end)

**Comment by 3N4N** [comment]
> I have installed plugins:

The default approach to bug report is to check if the bug is reproducible without personal config/plugins.  Check `:h --clean` for details.

**Comment by justinmk** [comment]
> ERR 2022-12-16T22:21:23.505 nvim.2232.0 terminfo_start:361: uv_tty_set_mode failed: invalid argument
> ERR 2022-12-16T22:22:37.671 nvim.14164.0 terminfo_start:361: uv_tty_set_mode failed: invalid argument

This is a known issue and is visible in the logs of any (failed) Windows CI job. Relevant code: https://github.com/neovim/neovim/blob/a0a112515923206b640f0056a8282386b5514978/src/nvim/tui/tui.c#L361-L364

**Comment by 3N4N** [comment]
> Is tui->output_handle.tty invalid somehow?

No, it's valid.  I'm currently building the dependencies with Debug flag, so I can track down the source of the issue (building deps with Debug flag will let gdb step into `uv_tty_set_mode`, right?).

**Comment by 3N4N** [comment]
In Windows, `uv_tty_init` is called twice and `uv_tty_set_mode` is called five times.  The value of `flags` set in `uv_tty_init` is `0x1006088` (first call) and `0xa088` (second call).  The first value is after being OR'd with `UV_HANDLE_TTY_READABLE`, while the second one doesn't do that.  This makes sense to me because there are two nvim processes, one with TUI and one without; one takes input from TTY and one doesn't.

Anyway, my takeaway from this investigation is, when [`readable` here][1] is TRUE, `uv_tty_set_mode failed: invalid argument` is being output to log.  But this seems like expected behavior to me.

[1]: https://github.com/libuv/libuv/blob/ee206367d4e8ebb70455665de78b8309220fd7d0/src/win/tty.c#L216

**Comment by 3N4N** [comment]
cc @dundargoc

**Comment by justinmk** [comment]
> seems like expected behavior to me, because one of the two nvim processes doesn't have input TTY.

makes sense. what condition can we use to skip the `uv_tty_set_mode` ?

**Comment by 3N4N** [comment]
You'll have to forgive me.  Everything I said in my last comment is wrong xD (or maybe new commits have been made in the meantime that changed the behavior since I last dealt with this).  The culprit line is executed only once, not twice.  So my theory, that this line was being executed once for each of the two nvim processes, is wrong.

https://github.com/neovim/neovim/blob/2af31fc50ac20493e0e931fc0750e3d15da436ef/src/nvim/tui/tui.c#L361-L364

What I want to report now is that the following call to `uv_tty_init` (L356) has the value of `readable` (local variable of `uv_tty_init`) always false, and so the consequent call to `uv_tty_set_mode` (L361) always returns non-zero.

https://github.com/neovim/neovim/blob/2af31fc50ac20493e0e931fc0750e3d15da436ef/src/nvim/tui/tui.c#L356-L361

Now, to give any opinion or proceed further, I need to --
- understand why we want L361 to be executed
- understand if we expect `readable` (local variable of `uv_tty_init`) to be false

**Comment by 3N4N** [comment]
https://github.com/neovim/neovim/blob/374955bcc571dff05f068ec18d0f578d1f334c5f/src/nvim/tui/tui.c#L363

^This function call doesn't make sense.  We're calling it on a handle of stdout.  See the third parameter to `uv_tty_init` call.

https://github.com/neovim/neovim/blob/374955bcc571dff05f068ec18d0f578d1f334c5f/src/nvim/tui/tui.c#L358

Of course `uv_tty_set_mode` is not going to work.  The first thing that function does is [check if the file handle is readable][1].

```
  if (!(tty->flags & UV_HANDLE_TTY_READABLE)) {
    return UV_EINVAL;
  }
```

Now, the interesting thing is that the unix version of the function `uv_tty_set_mode` (this function is differently implemented for Win and Unix) doesn't have this check.

I guess now one question remains:
- why we want [L363][2] to be executed

I think we don't need it, at least not in Windows.  It's exiting with error code anyway, and nvim runs perfectly.

This is the end of my investigation.  Awaiting feedback, @justinmk.

[1]: https://github.com/libuv/libuv/blob/62c2374a8c005ce9e42088965f8f8af2532c177b/src/win/tty.c#L352-L354
[2]: https://github.com/neovim/neovim/blob/374955bcc571dff05f068ec18d0f578d1f334c5f/src/nvim/tui/tui.c#L363

**Comment by 3N4N** [comment]
Got confirmation that `uv_tty_set_mode` on stdout handle isn't supposed to work<sup>[[1]]</sup>:

> Windows cannot set the properties of the output of a tty, unix can.

Which means, we should remove this:

https://github.com/neovim/neovim/blob/374955bcc571dff05f068ec18d0f578d1f334c5f/src/nvim/tui/tui.c#L362-L367
