### ISSUE TITLE
restore FEAT_BROWSE

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#2160]
I don't know of any reason why we would want to remove FEAT_BROWSE. We should restore it.

**Comment by mhinz** [comment]
After taking a look around, I wonder if we should really restore everything.

`:h :browse` shows  that it can be used for plenty of commands. Try it with gvim or MacVim or any Vim that has the `+browse` feature compiled in. E.g. `:browse e`. It usually opens a GUI-specific file selection dialog. I think restoring code from `src/gui_{athena,gtk_x11,mac,photon,...}` is not something we want.

There are 2 notable cases where this command acts differently:

1) `:browse set` which is the same  as `:options`. In Neovim `:browse set` is a no-op, but `:options` still works as intended. Nothing to do here.

2) `:browse oldfiles`, which starts a simple TUI file selection. Actually this is the only case I see `:browse` being used for from time to time.

What do you think of only restoring `:browse oldfiles`? And since this would be the only use case for `:browse`, we could drop that command and make `:oldfiles` do the prompting automatically.

Your opinions?

**Comment by justinmk** [comment]
> we could drop that command altogether and simply make :oldfiles always do the prompting automatically.

Seems fine, as long as  it still works with `:redir`.

**Comment by mhinz** [comment]
Then I'll just skip the prompting if `:redir` is in affect.

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/3611
