### ISSUE TITLE
NVIM_APPNAME: isolated configuration profiles

### ISSUE THREAD

**Issue by NoNaim95** [neovim/neovim#21691]
### Problem

Switching configs is a chore. If I want to switch my config and check out another config, I would have to backup my Config, copy the other config into `~/.config/nvim/`, clear/backup `~/.local/share/nvim/site` and do this all over again if I want to switch back. This is super tedious. Especially for neovim beginners like me. Making configs more packageable, would make learning neovim easier since beginners could use an already working config and simultaneously build up a personal config to learn.
There is https://github.com/NTBBloodbath/cheovim which somehow emulates this behavior with symlink hacks (which does not even work anymore), but this solution is flawed with bugs, because the configs are not self-contained and instead switch around symlinks. 

### Expected behavior

You would have something like a `profiles` directory where the different configs live. all configs would have their own datadir (where site/ and so on lives). The configs are self contained this way and do not interfere with other configs.
This way you could do something like
`nvim --profile own_config`
`nvim --profile astronvim`
and so on

**Comment by justinmk** [comment]
> If I want to switch my config and check out another config, I would have to backup my Config, copy the other config into `~/.config/nvim/`, clear/backup `~/.local/share/nvim/site` and do this all over again if I want to switch back. This is super tedious. 

I'm open to making this less tedious by including a script somewhere, or documenting a shell one-liner in :help. 

But adding another concept for this is just not worth the extra surface area.

> Especially for neovim beginners like me.

Why are beginners switching between different config "profiles"? I've never needed this functionality.

> Making configs more packageable, would make learning neovim easier since beginners could use an already working config and simultaneously build up a personal config to learn.

This can be achieved by using a `if` block in your init.vim or init.lua.

**Comment by bew** [comment]
Funny thing, I'm currently making my way to have a fully self-contained config for my experimental config and use the usual directories for my work config. (same as OP, but I'm not really a beginner ^^)

(rather long comment incoming!)

One way to load a custom config instead of the default one is to do `nvim -u /path/to/my/custom/init.lua`, however trying to modularize this config will not really work, as the default `vim.o.runtimepath` still points to `~/.config/nvim`.
:point_right: This means that if my custom init.lua does `require"foo.bar"` nvim will try to load `~/.config/nvim/lua/foo/bar.lua` instead of `/path/to/my/custom/lua/foo/bar.lua`, because `~/.config/nvim` is the standard config path, and it is automatically added to `vim.o.runtimepath` (the option listing all the places to look for things).

One way I considered at the begining was to just remove the default config path from `vim.o.runtimepath` and replace it with mine at the beginning of the config, but that doesn't work when plugins are getting the config dir using `vim.fn.stdpath` (like `lazy.nvim`), or just try to get the data/run/state dir using that same function.


### XDG spec

The `vim.fn.stdpath(what)` function returns the standard paths following the XDG spec as to where to find various directories.
See `:h standard-path`
Following this I could have put my config 'profile' in `/foo/new-config/nvim` and set `XDG_CONFIG_HOME=/foo/new-config` before starting nvim, and that would be a self contained config (note: would need more XDG_.. env vars to also change data/run/state/.. dirs).

The issue with that, is that if my nvim config is using tools (e.g: git) that also have their config in the usual `XDG_CONFIG_HOME` (`~/.config`), using a custom config home for nvim would make these tools use their default config, not my own.


### Changing nvim's standard paths?

To keep my `XDG_CONFIG_HOME` untouched, while still have a self-contained nvim config, I figured we would need to change what the standard paths point to, so that requiring things work seemlessly.

I was thinking maybe there was already env vars to change these paths, something like:
- `NVIM_STDPATH_CONFIG` to change the standard `config` path
- `NVIM_STDPATH_DATA` to change the standard `data` path
- `NVIM_STDPATH_STATE` to change the standard `state` path
- ...

(a profile would be a bunch of these, set to a profile-specific path)

But there's nothing like that in the documentation.
I could try to change neovim's source to add them, but I figured I could experiment something simpler first.


### (Experiment) Changing nvim's standard paths in my Lua config

Let's instead do something simpler, change what is returned by `vim.fn.stdpath(what)`.
I don't know if it's possible to replace a vimscript function, but changing a Lua function is easy! So I experimented.

In Lua that works:
```lua
-- In file: /path/to/my/custom/init.lua

local real_stdpath = vim.fn.stdpath
vim.fn.stdpath = function(what)
  -- see `:h stdpath` for what `waht` can be
  if what == "config" then
    return "/path/to/my/custom"
  else
    return real_stdpath(what)
  end
end

-- We also need to change the runtimepath, to ensure requires
-- work as expected, and do not search in the default paths.

-- This is enough to start:
vim.opt.runtimepath = {
  vim.fn.stdpath"config",
  vim.env.VIMRUNTIME,
  vim.fn.stdpath"config" .. "/after",
}

-- now I can do
require "foo.bar"
-- and it'll find it in /path/to/my/custom/lua/foo/bar.lua
```
And that mostly work (missing a few specialized data/state/.. dirs for that profile)

To further my experiment, I made a small module to override in a configurable way the `vim.fn.stdpath` function and make it return what I want.

Here it is for now:
https://github.com/bew/dotfiles/commit/1f49c8ccb1bc42a13808064ae6b402e0979643e8
You can see the (ugly) `TEST` function at the bottom, to see what I expect based on how the nvim is called.

You can see in my dotfiles, I have `nvim` (the one linked to `~/.config/nvim`) which is my old vimscript-based config, and `nvim-wip` which is a full Lua-based config I'm slowly working on, and what this experiment is for: being able to load a fully alternative config from non-standard paths.

NOTE: I had to require that custom module manually (`dofile("path/to/file")` instead of `require`), since the `runtimepath` is still pointing to standard paths when requiring it! (I could change runtimepath just before.. but oh well, that'll do for now)
See: https://github.com/bew/dotfiles/blob/887e4c9051c18cf94e7fe876316782ff4ba9b27d/nvim-wip/init.lua#L12-L26


## What now:

It's still not perfect because I have fiddle with Lua's `stdpath`, I don't know how to override the vimscript one, and I need to force change the runtimepath..
But for my usage it's enough.

:point_right: I'd be interesting if some part of this could be useful to neovim?

For example, I'm thinking the `NVIM_STDPATH_*` env vars could be useful to be able to change reliably some standard paths for a given nvim instance?
Then it's easier to have specialized (profiles) nvim configs with a wrapper script that sets these env vars and load a specific init with `-u`.

WDYT?

**Comment by justinmk** [comment]
> interesting if some part of this could be useful to neovim?
> 
> For example, I'm thinking the `NVIM_STDPATH_*` env vars could be useful to be able to change reliably some standard paths for a given nvim instance?

We intentionally want to avoid introducing more environment variables or options. Because:

1. this use-case is unusual
2. the xdg spec needs to decide how to serve this use-case
3. you can achieve the same thing simply by renaming directories. e.g.:
   ```
    mv ~/.config/nvim ~/.config/nvim.a
    mv ~/.config/nvim.b ~/.config/nvim
    mv ~/.local/share/nvim/ ~/.local/share/nvim//nvim.a
    mv ~/.local/share/nvim/.b ~/.local/share/nvim/nvim
    ...
   ```

**Comment by bew** [comment]
> 1) this use-case is unusual

I really like that neovim is extensible as it is, and I'm thinking to use it as a kind of framework that I instanciate with different kinds of configs (self-contained, I don't want one to depend on another / be stored at the same place, more like independant apps).

For me this is a compelling use case for the extensibility of neovim, and one way it could be used as a framework (not just as a lib / as part of another software).
Do you want to prevent this kind of use-case ?

> 2) the xdg spec needs to decide how to serve this use-case

That would only be in a long time unfortunately :/

> 3) you can achieve the same thing simply by renaming directories. e.g.:

That doesn't work for me as I want to be able to use both configs _at the same time_

---
> Note: some have suggested something like a `XDG_APPNAME` var that would set the "nvim" part of the various xdg paths.

Curious, do you have a reference link for this? Googling `XDG_APPNAME` doesn't give any useful result

**Comment by justinmk** [comment]
`XDG_APPNAME` or `NVIM_APPNAME` would be something we add, since xdg doesn't have it yet (or maybe ever).

**Comment by lewis6991** [comment]
I think this is something worth having. All external sources `nvim` reads should have some knobs to control them (somewhere).

One application I've had in mind for this is for encapsulated testing without a fully fledged container. `-u` can get you the most of the way there, but obviously it isn't quite enough.

**Comment by mfussenegger** [comment]
> One application I've had in mind for this is for encapsulated testing without a fully fledged container. -u can get you the most of the way there, but obviously it isn't quite enough.

At least on linux one could get something like that with cgroups/user namespaces. For example with systemd you can run something like this:

    systemd-run --user -qt -p PrivateUsers=yes -p BindPaths=/home/user/profile_xy:/home/user/.config/nvim nvim

**Comment by justinmk** [comment]
# Status

- A single `NVIM_APPNAME` env var should address the use-cases here. Avoid multiple `NVIM_STDPATH_*` env vars.
- Let's also document the cgroups one-liner mentioned by @mfussenegger . Maybe there's a similar idea for docker that we could mention.

**Comment by glacambre** [comment]
What would be the recommended behavior of UIs regarding NVIM_APPNAME? Should they set it or not?

**Comment by bew** [comment]
Thank you @justinmk & @glacambre for the recent work on this ❤️

**Comment by przepompownia** [comment]
It's a step ahead that makes isolation easier, but I still have no idea how to contain all stdpath directories under a separate path like `/tmp` withouth setting `XDG_*` variables. With `NVIM_APPNAME` I can only replace `nvim` with another custom path under `~/.config` etc.
