### ISSUE TITLE
using statusline’s format expr customize foldtext

### ISSUE THREAD

**Issue by NEX-S** [neovim/neovim#21733]
### Problem

it seems we can’t use statuslines format expression to customize foldtext. will neovim add this feature in some days?

### Expected behavior

if so, maybe we can add some special format to foldtext such as folded lines number etc…

it might be more user friendly than using function to customize it 
:up

**Comment by justinmk** [comment]
what's a concrete example of what you expect? e.g. sample config code. 

also why not do this via 'statuscolumn' ?

**Comment by luukvbaal** [comment]
I think here they are asking for a `'statusline'`-format option alternative for `'foldtext'`, i.e. the text in the buffer for a closed fold, rather than the fold column.

I won't speak to that, but indeed most of the other (closed) requests that I have seen popping up should be able to be covered via 'statuscolumn'. Although it will require some work in the form of a plugin in some cases.

There might still be merit in providing some of those options for the default columns regarding performance. I guess we first need to how it performs in the form of a 'statuscolumn' plugin. If it performs well enough, perhaps core can decide to ignore/close further default column feature requests...

**Comment by lewis6991** [comment]
You need to pass `{highlights=true}` and use the returned information to constructs the correct string.

**Comment by lewis6991** [comment]
I do plan to add support to `foldtext` in the future to support returning a structure similar to `virtual_text` for providing highlights.
