### ISSUE TITLE
macOS: Lua loads .so but not .dylib libraries

### ISSUE THREAD

**Issue by Avishayy** [neovim/neovim#21749]
### Describe the bug

I've been trying to use [`lazy.nvim`](https://github.com/folke/lazy.nvim) to load a library compiled to a `.dylib` (specifically [`lua-json5`](https://github.com/Joakker/lua-json5)) on macOS (13.1 Ventura)

Modifying `package.cpath` to include `;?.dylib` doesn't yield any results, adding the full path of the library to `cpath` "fixes it".

More info on the exact scenario at https://github.com/folke/lazy.nvim/issues/368

### Steps to reproduce

1. Add lua-json5 as a package through any package manager
2. Build it with `./install.sh`
3. Try to require it `lua require('json5')`
4. Neovim fails to resolve it
5. Manually add `dylib` to `cpath`
```lua
package.cpath = package.cpath .. ";?.dylib"
```
7. Still fails to resolve

### Expected behavior

Either loading a .dylib should work out-of-the-box (like it does for an .so), or adding the pattern `?.dylib` will help it resolve.

In my case, adding the full path to the lib fixed the resolve `;/Users/avishay/.config/nvim/.repro/plugins/lua-json5/lua/json5.dylib`

### Neovim version (nvim -v)

NVIM v0.8.1

### Vim (not Nvim) behaves the same?

Irrelevant, no lua libraries

### Operating system/version

mac OS 13.1

### Terminal name/version

iTerm 2 3.4.19

### $TERM environment variable

xterm-256color with tmux

### Installation

bob

--

Unrelated, but thank you for developing and maintaining such great software!

**Comment by clason** [comment]
@carlocab not homebrew-specific, but you may have experience with Lua libs on macOS.

**Comment by folke** [comment]
I looked into this and it seems that `dylib` isn't part of `package.cpath` in macos, so the code below won't pick it up

https://github.com/neovim/neovim/blob/ddecf5e27f987f4b3f376ae3e14976960cf60522/runtime/lua/vim/_init_packages.lua#L3

**Comment by folke** [comment]
@Avishayy what does `:lua= package.cpath` print?

**Comment by Avishayy** [comment]
> table.insert(vim._so_trails, "/?.dylib")

I can confirm using this works.

**Comment by clason** [comment]
I think we should discuss first what the intention and best implementation is.

**Comment by folke** [comment]
See also this LuaJit issue https://github.com/LuaJIT/LuaJIT/issues/76

Aparently PUC adds `dylib` to the default cpath on macos, but it list at the time of the issue LuaJit did not. And they probably still dont.

**Comment by clason** [comment]
Yeah, that's what I was thinking of and why I was hesitant to just do it.

**Comment by folke** [comment]
I believe on Windows, it already contains `dll`. Need to doublecheck though

**Comment by clason** [comment]
> .so should also be kept in the so path on macos I believe, so ideally cpath should be first dylib, then so and then the rest.

I worry about what happens in situations where you have a `.so` _and_  a `.dylib` -- because a package helpfully provides binary libs for Linux _and_ macOS...

**Comment by folke** [comment]
Agree, but that would be ok if we set `dylib` first and `so` after? On Macos?

**Comment by folke** [comment]
Relevant: https://github.com/LuaJIT/LuaJIT/blob/d0e88930ddde28ff662503f9f20facf34f7265aa/src/luaconf.h#L25

It seems that LuaJit doesn't add `dylib` to the cpath for Macos.

So not sure we should do anything different then tbh...

But making it work by adding something to `vim._so_trails` is also not ideal

**Comment by clason** [comment]
@Avishayy regardless of the discussion here, this is an actual issue with lua-json5 that needs to be fixed: that project claims to target LuaJIT, which (intentionally!) does _not_ have `dylib` in `package.cpath`. The simplest fix is therefore to just name the built library `json5.so` on macOS as well.

**Comment by Avishayy** [comment]
I don't know if it means anything, but [Tarantool's fork of luajit does support it](https://github.com/tarantool/luajit/commit/b4ea162891bc686aa65abeb15662946bd4c8259d), I really do wonder why main luajit doesn't

Why shouldn't we load `.dylib` in neovim's loader? What if `lua-json5` was actually `nvim-json5` and it would only target neovim (as a `rust -> lib` repo)? Are we deliberately going to not support loading `.dylib` libraries?

**Comment by clason** [comment]
> I don't know if it means anything, but [Tarantool's fork of luajit does support it](https://github.com/tarantool/luajit/commit/b4ea162891bc686aa65abeb15662946bd4c8259d),

It doesn't mean anything, since that's not what we are using.

>  I really do wonder why main luajit doesn't

Only Mike Pall can (but probably won't) answer that.

> Why shouldn't we load .dylib in neovim's loader?

One possible reason would be to avoid divergence, which always complicates maintenance (documentation, testing, etc.) This not a hard reason not to do it, of course, but it means that such changes are not free and should be deliberated at least a bit.

>  What if lua-json5 was actually nvim-json5 and it would only target neovim (as a rust -> lib repo)?

And this is the crux of the matter: it's _not_, so it's not a compelling reason. So let me turn this around: do you know of (or can find) a binary "nvim" library that only builds `dylib` and not `so` on macOS and needs to be supported in this way?

**Comment by Avishayy** [comment]
I see. As `.dylib` don't provide any real advantages over `.so`, I guess it doesn't really matter, it should be easy enough (I believe) for each such library to simply provide an `.so`.

Thank you for the explanation and the honest response.

**Comment by carlocab** [comment]
For context: on Darwin, `.dylib`s are typically compiled with `-shared` or `-dynamiclib` and have file type `MH_DYLIB`, while `.so`s are typically compiled with `-bundle` and have file type `MH_BUNDLE`.

The difference is that `MH_DYLIB`s can be linked at link-time (e.g. `-lfoo`), while `MH_BUNDLE`s cannot. Both can be loaded using `dlopen`.

Typically, libraries written for use inside Lua(JIT) are designed to be `dlopen`ed (because you call them with Lua code rather than directly through a C API and Lua(JIT) handles the `dlopen` for you), and not really meant to be linked with `ld`, so you usually want them to be `MH_BUNDLE`s.

In my experience every loadable Lua module ships a `.so` (which is usually an `MH_BUNDLE`, but they occasionally get compiled as `MH_DYLIB`s), so I imagine one doesn't want to deviate from upstream for the single exception of `lua-json5`.
