### ISSUE TITLE
`statuscolumn` only respects the last line of the click functions

### ISSUE THREAD

**Issue by erw7** [neovim/neovim#21767]
### Describe the bug

Even if different click functions are set for each row in `statuscolumn`, only the click function for the last row is set.

#### test.vim
```vim
function! StcClickAble() abort
  if v:lnum % 2
    return '%@ClickStcOdd@' . v:lnum . ' %X'
  else
    return '%@ClickStcEven@' . v:lnum . ' %X'
  endif
endfunction

function! ClickStcOdd(minwid, count, button, mod) abort
  call ClickStc(v:true)
endfunction

function! ClickStcEven(minwid, count, button, mod) abort
  call ClickStc(v:false)
endfunction

function! ClickStc(odd) abort
  echomsg 'click statuscolumn on ' . (a:odd ? 'odd' : 'even') . ' line'
endfunction

set stc=%{%StcClickAble()%}
```

```
nvim -u test.vim test.vim
" Click on the line number of each line.
" It is always echoed as "click statuscolumn on odd line".
Go<ESC>
" Click on the line number of each line.
" It is always echoed as "click statuscolumn on even line".
```

### Expected behavior

If the user clicks on an odd line, the message "click statuscolumn on odd line" is echoed; if the user clicks on an even line, the message "click statuscolumn on even line" is echoed.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-656+g93d99aefd

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

build from repo

**Comment by luukvbaal** [comment]
Yeah I realized this during development but I wasn't sure what to do with it. Storing the click definitions for each line in each window seems excessive. I also think it is unnecessary since each segment in a statuscolumn (whether printed or not) should have the same width(not guaranteed but I can't think of a situation where it would make sense not to be).

Can you think of an example why we would have to be able to define different click handlers for each line? In my eyes this can be handled in the callback instead.

**Comment by erw7** [comment]
> Can you think of an example why we would have to be able to define different click handlers for each line?

I do not have a use case for this (I will probably never use statuscolumn, which causes delays in drawing). I just created the issue because I was looking into a memory leak in `build_stl_str_hl` and noticed it.

But if it only makes sense to parse the last row, do we really need to parse `'statuscolumn'` by row? Is there any way to improve performance by parsing only one line, replacing it with a temporary character, and replacing the temporary character with a new one?

**Comment by luukvbaal** [comment]
Well it needs to be parsed by row since the text is expected to be different on each row. I don't think the click definitions need to be parsed/re-allocated each row. Should only be necessary once per redraw. (I guess only if the width of the statuscolumn changes in most cases but the statuscolumn width may stay the same while width of the statuscolumn segments, and their respective click handlers might change.)

**Comment by erw7** [comment]
> Well it needs to be parsed by row since the text is expected to be different on each row.

Hmmm, I've been thinking about it and it might be possible to change the parse to a two-pass. The first pass processes line-independent `%@`, `%#`, etc., while the next pass processes line-dependent `%l`, `%{`, etc., for each line. If the width of each row is equal, there should be no problem. However, it is unclear whether the cost of implementation is worth the performance improvement.

**Comment by luukvbaal** [comment]
> However, it is unclear whether the cost of implementation is worth the performance improvement.

Yeah, I imagine that will be even more difficult considering `%{%%}` and `%!`.

**Comment by justinmk** [comment]
> if different click functions are set for each row in `statuscolumn`

Yeah, it's a reasonable limitation to specify that 'statuscolumn' click handlers can't be "switched out". Users must specify a handler that works dynamically, instead of dynamically setting different handlers per-row.

So yes this is a documentation issue.
