### ISSUE TITLE
tui: tmux can no longer read the CWD (regression)

### ISSUE THREAD

**Issue by kylo252** [neovim/neovim#21771]
### Describe the bug

tmux can no longer read the CWD from neovim, and this was something which has "worked" until https://github.com/neovim/neovim/pull/18375 (found using git-bisect)

This was tested against with different `$TERM` values: `alacritty`, `xterm-256color`, `tmux-256color`.

### Steps to reproduce

- `nvim -u NONE`
- `:pwd`
- execute this tmux command `display -p '#{pane_current_path}'` and check that it matches the previous result
- `:cd build`
- re-run the tmux command and see a mismatch

### Expected behavior

tmux is able to read the CWD using `nvim-0.8.2`

### Neovim version (nvim -v)

2aabe9b85870912b9eb8fe2ced0c21544de66f58

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Linux

### Terminal name/version

Alacritty 0.11.0

### $TERM environment variable

`alacritty`, `xterm-256color` and `tmux-256color`

### Installation

build from repo

**Comment by kylo252** [comment]
probably related to https://github.com/neovim/neovim/issues/21636

**Comment by ii14** [comment]
clipboard is irrelevant. tmux probably does something like `pwdx` (checks `/proc/X/cwd`), but TUI is now a separate process and I doubt changing the directory is forwarded to the TUI process from the server.

**Comment by ii14** [comment]
Yes, when you change directory with `:cd`, the directory changes only on the server process. TUI process stays on the directory it was opened in, and I assume that is what tmux sees.

**Comment by justinmk** [comment]
Would emitting OSC 7 on `DirChanged` fix this? https://github.com/neovim/neovim/pull/16740 does this for `:terminal` but Nvim could also do this by default.

Meanwhile, user config can do `:au DirChanged * call chansend(v:stderr, ...)`

**Comment by bfredl** [comment]
if it is just `/proc/` shenanigans, the TUI could of course change its cwd as well. That would require an ui event for changed cwd, but that might be a reasonable pattern anyway.

**Comment by joshbode** [comment]
Thanks for the tip, @justinmk!

This worked for me:
```vim
autocmd DirChanged * call chansend(v:stderr, printf("\033]7;%s\033", v:event.cwd))
```
along with the following bindings for `tmux` which I use to create splits in the current directory:
```
bind-key | split-window -h -c '#{?#{!=:#{pane_path},},#{pane_path},#{pane_current_path}}'
bind-key - split-window -v -c '#{?#{!=:#{pane_path},},#{pane_path},#{pane_current_path}}'
```

Note: on `0.8.2` I didn't need the `autocmd` and I just had these bindings for `tmux`:
```
bind-key | split-window -h -c '#{pane_current_path}'
bind-key - split-window -v -c '#{pane_current_path}'
```
since `tmux` happily picked up the current path from `/proc/${PID}/cwd` for the single process.

**Comment by kylo252** [comment]
I think the same issue is affecting `kitty` as well.

Opening a new tab in the same cwd isn't picking up the latest change.

---

> (OSC7 sets `#{pane_path}`, not `#{pane_current_path}` which is set from `/proc/${PID}/cwd`)

@joshbode, thanks! That did the trick for tmux.

**Comment by ces42** [comment]
This is also affecting kitty. The workaround sending `OSC 7` does not work for kitty since it doesn't support `OSC 7` (https://github.com/kovidgoyal/kitty/issues/3024#issuecomment-930352975).

The author of kitty outlines how things should work (in his opinion) [here](https://github.com/kovidgoyal/kitty/discussions/4869).

**Comment by zeertzjq** [comment]
Hmm, I don't think that the same problem. This fixes the problem for kitty but not for tmux:
```diff
diff --git a/src/nvim/event/libuv_process.c b/src/nvim/event/libuv_process.c
index e528d21a7..5f310193b 100644
--- a/src/nvim/event/libuv_process.c
+++ b/src/nvim/event/libuv_process.c
@@ -37,8 +37,6 @@ int libuv_process_spawn(LibuvProcess *uvproc)
     uvproc->uvopts.flags |= UV_PROCESS_DETACHED;
   }
 #else
-  // Always setsid() on unix-likes. #8107
-  uvproc->uvopts.flags |= UV_PROCESS_DETACHED;
 #endif
   uvproc->uvopts.exit_cb = exit_cb;
   uvproc->uvopts.cwd = proc->cwd;
```

**Comment by ces42** [comment]
I don't really know how setsid works, but the author of kitty says that kitty looks at the child process with the highest pid associated to the terminal, which would be `nvim --embed` if it didn't call `setsid()` (I'm assuming the code you suggest removeing makes the `nvim --embed` process call `setsid()`?). tmux probably just used the first child process, so having the `nvim --embed` process attached/detached from the terminal does not make a difference.

In sum I guess both bugs are caused by the same thing (remote TUI) but might need a different fix.

**Comment by ces42** [comment]
It turns out kitty *did* add support for `OSC 7` in https://github.com/kovidgoyal/kitty/commit/afa6128155630e7506f4ad229eccb84bbd8731fb and https://github.com/kovidgoyal/kitty/commit/e33bf110123b8715a1399240c54e622456d9a374, if you use `launch` with `--cwd=last_reported`. So I managed to adapt @joshbode's workaround like this
```vim
autocmd DirChanged * call chansend(v:stderr, printf("\033]7;file://%s\033\\", v:event.cwd))
```
to work with kitty.

**Comment by dtcyganok** [comment]
Please, could anyone post a valid workaround for kitty?

**Comment by ddickstein** [comment]
@ces42 that looks like the same line @joshbode originally wrote - am I missing a difference that was needed to make it work with kitty (other than also using `--cwd=last_reported`)?

**Comment by ces42** [comment]
You're right. I thought that another change was needed but I checked my config and it just has @joshbode's line

**Comment by ddickstein** [comment]
For display purposes, it may be helpful to adjust the recommended tmux line to do a regex strip of the "file://" prefix:

```
#{?pane_path,#{pane_path},#{pane_current_path}}
```
becomes
```
"#{?pane_path,#{s@^file.//@@:pane_path},#{pane_current_path}}"
```
(this suggestion is taken from https://github.com/tmux/tmux/issues/2506)

**Comment by astephanh** [comment]
I've had to make a slight adjustment, as (at least) my pane_path includes the Hostname

so for me it becomes

```
bind c new-window -c "#{?pane_path,#{s@^file.//#H@@:pane_path},#{pane_current_path}}"

```

**Comment by gadanidis** [comment]
Unfortunately the workaround doesn't seem to work for terminals like alacritty that haven't implemented OSC 7 (https://github.com/alacritty/alacritty/pull/2937). Hopefully a long-term solution to this issue would be to change the TUI's cwd rather than only emitting OSC 7, though I understand why this isn't prioritized given the workaround seems to work for most people.

**Comment by gpanders** [comment]
Changing the TUI’s pwd is (imo) the better solution anyway. OSC 7 for this purpose strikes me as a bit of a hack
