### ISSUE TITLE
Neovim hangs with large parameters of ui_attach

### ISSUE THREAD

**Issue by coolwanglu** [neovim/neovim#2180]
As found in https://github.com/coolwanglu/neovim.as/issues/26

If `columns` and `lines` are not set in `~/.nvimrc`, calling ui_attach with row=999 and col=999 will make neovim hang. However by setting the values, even with small values (e.g. `set columns=10 rows=10`) in `~/.nvimrc`, it will just work normally.

I also tried with the python-client, neovim hung in both cases, but the black background shows only when the values are set in `~/.nvimrc`.

**Comment by justinmk** [comment]
@coolwanglu The problem here may have been not a hang, but just that with height=999 and width=999 some logic might have been very slow. In adding [test coverage](https://github.com/neovim/neovim/pull/5974/files#diff-f3f4e5db8516f833bea49c71b21fa35dR693) I noticed that it takes our Screen.lua UI implementation (which is just a fake screen for functional tests) 1.5 seconds to initialize at 999x999. And with 9999x9999 it ran out of memory.
