### ISSUE TITLE
abort() by 'resize -1' with 'cmdheight=0 redrawdebug=invalid'

### ISSUE THREAD

**Issue by Jun-T** [neovim/neovim#22154]
### Describe the bug

`resize -1` leads to abort() if options `cmdheight=0 redrawdebug=invalid` are set.

### Steps to reproduce

nvim --clean
set cmdheight=0 redrawdebug=invalid
resize -1

### Expected behavior

resize works

### Actual behavior

nvim is terminated by abort(3).

abort() is called at line 427 in ui_compositor.c.
https://github.com/neovim/neovim/blob/8fbe75b3dda7ab3b9e6df0d5406539bde4c80887/src/nvim/ui_compositor.c#L425-L428

### Neovim version (nvim -v)

NVIM v0.9.0-dev-877+g228684d2f-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu-22.04, macOS (Mojave etc.)

### Terminal name/version

gnometerminal, Apple's Termial.app

### $TERM environment variable

xterm-256color

### Installation

build from source

**Comment by Jun-T** [comment]
Here is the back trace from the core (macOS Mojave).
[bt.txt](https://github.com/neovim/neovim/files/10674142/bt.txt)

**Comment by nwounkn** [comment]
The problem is in `update_screen`, it invalidates all `msg_grid` rows that are used for displaying a message, when the screen is scrolled down back https://github.com/neovim/neovim/blob/22d397c233b12a94ba36052d9e626ed61e25d488/src/nvim/drawscreen.c#L458-L468  
But then, if redraw type is `UPD_NOT_VALID`, `msg_grid` rows from 0 to `p_ch` are used for compositing in https://github.com/neovim/neovim/blob/22d397c233b12a94ba36052d9e626ed61e25d488/src/nvim/drawscreen.c#L535-L538  
So, any command that shows a scrolled message, and causes a `UPD_NOT_VALID` redraw should trigger the same bug. For example, `:split | echo "\n"` command with `redrawdebug=invalid` set also triggers the bug.  
Here's the fix I came up with:  
```diff
diff --git a/src/nvim/drawscreen.c b/src/nvim/drawscreen.c
index 73dd584fb..608b7806d 100644
--- a/src/nvim/drawscreen.c
+++ b/src/nvim/drawscreen.c
@@ -463,7 +463,7 @@ int update_screen(void)
       // non-displayed part of msg_grid is considered invalid.
       for (int i = 0; i < MIN(msg_scrollsize(), msg_grid.rows); i++) {
         grid_clear_line(&msg_grid, msg_grid.line_offset[i],
-                        msg_grid.cols, false);
+                        msg_grid.cols, i < p_ch);
       }
     }
     msg_grid.throttled = false;

```

**Comment by Jun-T** [comment]
Thanks. The patch works for me.

**Comment by clason** [comment]
@nwounkn would you care to open a PR (this fix might not be the correct way, but it's at the very least something to base a discussion on).
