### ISSUE TITLE
True Color support makes gui_running true but not during startup...

### ISSUE THREAD

**Issue by jszakmeister** [neovim/neovim#2216]
I do some extra customizations when running in gui mode, some of which is delayed until after all plugins are loaded (using the VimEnter autocmd).  It appears that setting `NVIM_TUI_ENABLE_TRUE_COLOR=1` causes my vimfiles to be sourced with `has("gui_running")` false, but when VimEnter happens it's now true.  This causes also kinds of things to fail since half the setup did not occur. :-(  Is this intentional behavior?

**Comment by tarruda** [comment]
> Is this intentional behavior?

Yes, its the best way I've found to make the new UI architecture more or less compatible with old color schemes. `has('gui_running')` is true when there's at least one RGB UI attached, the builtin UI initialization only occurs after vimrc is sourced.

**Comment by jszakmeister** [comment]
:-(  Bummer.  Okay, I'll try and work around it then.

**Comment by jbaum98** [comment]
> its the best way I've found to make the new UI architecture more or less compatible with old color schemes.

This behavior makes www.github.com/altercation/vim-colors-solarized not work, because on startup it is checking for `has('gui_running')`. Only if you resource `.nvimrc` does it display correctly. So at least in this once case, this behavior is making it incompatible with a vim color scheme, and I'm confused as to why this is supposed to help compatibility.
