### ISSUE TITLE
`nvim_buf_set_text()` doesn't always adjust cursor to stay on same character

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#22526]
### Problem

When adding text with `vim.api.nvim_buf_set_text()` just to the left of cursor, it doesn't adjust cursor to stay relative to the same character. When adding text in any other place, this holds true.

### Steps to reproduce

1. `nvim --clean -u NONE`
2. Create text `abcd` and place cursor on `c`.
3. Execute one of the following:
    3.1 `:lua vim.api.nvim_buf_set_text(0, 0, 0, 0, 0, { 'xxx' })`. This results into `xxxabcd` and cursor still on `c`.
    3.2 `:lua vim.api.nvim_buf_set_text(0, 0, 1, 0, 1, { 'xxx' })`. This results into `axxxbcd` and cursor still on `c`.
    3.3 `:lua vim.api.nvim_buf_set_text(0, 0, 2, 0, 2, { 'xxx' })`. This results into `abxxxcd` **but cursor is on first `x`**.
    3.4 `:lua vim.api.nvim_buf_set_text(0, 0, 3, 0, 3, { 'xxx' })`. This results into `abcxxxd` and cursor still on `c`.

### Expected behavior

Cursor is always adjusted to stay on its relative initial position.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1100+g1dd2424b1

### Vim (not Nvim) behaves the same?

No (doesn't have this functionality)

### Operating system/version

EndeavourOS Linux x86_64 (6.1.12-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

appimage

**Comment by bfredl** [comment]
Unfortunately there is no gravity behavior which is universally correct. the current behavior preserves the position used by `i` (and already being in insert mode), but not of `a` or `x` (the latter of which the cursor being "on" a character interpretation makes sense). We can flip the behavior if we so want, but then the situation would be the reverse (`i` and insert mode would no longer be on the "same character" anymore).

**Comment by echasnovski** [comment]
> Unfortunately there is no gravity behavior which is universally correct. the current behavior preserves the position used by `i` (and already being in insert mode), but not of `a` or `x` (the latter of which the cursor being "on" a character interpretation makes sense). We can flip the behavior if we so want, but then the situation would be the reverse (`i` and insert mode would no longer be on the "same character" anymore).

Yes, I see the reasoning. And indeed, if done when in Insert mode, it does behave coherent.

I would argue that more frequent use case for `nvim_buf_set_test()` is not for when Insert mode is active, though. Might be wrong, but this is my experience.

Also I would argue that having cursor shifted even in Insert mode is least unexpected than not shifted in Normal mode. Like this is also acceptable when executing `vim.api.nvim_buf_set_text(0, 0, 2, 0, 2, {'xxx'})` and cursor is `c` in Insert mode:

```
  ⎸          ⎸ 
abcd -> abxxxcd
```

**Comment by bfredl** [comment]
that doesn't apply to deleting in insert mode tho.

**Comment by echasnovski** [comment]
> that doesn't apply to deleting in insert mode tho.

Not sure what you meant here, but did some additional tests for delete/replace in Insert mode. And there are also some inconsistencies there.

1. Create mapping `:inoremap <M-m> <Cmd>lua vim.api.nvim_buf_set_text(0, 0, 1, 0, 2, {'xxx'})<CR>`
2. Create `abcd` text, put cursor on `c`, and start Insert mode with `i`.
3. Press `<M-m>`. Text becomes `axxxcd` and cursor is before second `x`, i.e. not adjusted. While if on `d` originally, it is1 adjusted.

Now, I understand that this seems to be a result of a compromise choice. This is just to have this documented.

**Comment by faergeek** [comment]
> Unfortunately there is no gravity behavior which is universally correct. the current behavior preserves the position used by `i` (and already being in insert mode), but not of `a` or `x` (the latter of which the cursor being "on" a character interpretation makes sense). We can flip the behavior if we so want, but then the situation would be the reverse (`i` and insert mode would no longer be on the "same character" anymore).

I apologize in advance if this is a silly question, but would it make sense to adjust this behavior based on current mode? So that, for example, adding text exactly at cursor position would not move cursor forward only in INSERT mode in the current window, but in other modes and other windows it would.

Right now I'm trying to solve the following problem. The basic idea is being able to run the buffer contents through a formatter like `stylua`, to which an entire buffer content is passed through stdin and it gives new content back through stdout.

In that case just replacing the whole buffer causes all kinds of problems, like losing marks and extmarks together with cursor positions in all windows, messed up diagnostic signs, opening folds etc. But `vim.diff` can help in figuring out exactly which lines have changed. And with hunks that either only remove lines or only add lines `nvim_buf_set_lines` gets job done perfectly well, cursors in all windows shift as they should, extmarks for remaining lines are not lost, etc.

Then in case of a "replacement" hunk, especially if one line was turned into a few or vice versa, it seems like the only option is to go deeper on character level diffs to figure out minimal edits being made by the formatter and use `nvim_buf_set_text` to apply those edits. But given that it does not always adjust cursor position in a natural way, it becomes necessary to at least adjust cursor position manually for each window for that buffer, then probably also adjust extmarks positions, the list goes on. But even with cursors alone, if they are adjusted manually, a simple undo/redo cycle after formatting wipes out those adjustments.

In the end, I think it would be much easier to be able to just figure out necessary edits and apply them using `nvim_buf_set_text` and expect that marks, cursors and extmarks would be properly shifted. And I suppose it would then require no manual adjustments to the cursor position after applying text edits from LSP. At least my understanding is that they are necessary for the same reason https://github.com/neovim/neovim/blob/5d8ab32f3871b0232972cac1116ac7cba98389e5/runtime/lua/vim/lsp/util.lua#L564-L571

I guess this issue can be related to these adjustments as well https://github.com/neovim/neovim/issues/24297

If this sounds reasonable, I would be happy to try to implement those changes, but I know nothing about neovim codebase and I don't have a lot of experience writing C.
