### ISSUE TITLE
[builtin-terminal-emulation] “press any key to close” is a lie

### ISSUE THREAD

**Issue by Grimy** [neovim/neovim#2256]
Pressing a key to close a terminal window whose command has completed only works in terminal-mode, not in normal mode. The prompt “press any key to close” appears in all modes, which is error-inducing.

IMO the default behavior should be to auto-close the window when the command is complete. I can understand that in some cases, the user might want to interact with the output afterwards, but I don’t think that’s the common case.

**Comment by Pyrohh** [comment]
I'm a little skeptical, but I think that might be a good idea. It does seem counterintuitive that closing a :term session doesn't immediately terminate the buffer (unlike regular buffers).

**Comment by noahfrederick** [comment]
> IMO the default behavior should be to auto-close the window when the command is complete.

I agree. I almost suggested that `:terminal!` (with a bang) change the behavior, but it stretches the semantics of `!` and is probably not a good idea ultimately. Maybe firing an event when the process exits is sufficient, so that the buffer can be deleted with an autocommand. Then again, I'd rather it "just work" without extra configuration.

**Comment by noahfrederick** [comment]
See also [dispatch.vim](https://github.com/tpope/vim-dispatch/)'s `:Start` command, which fills much the same role as `:terminal`. When used with the tmux adapter, the tmux window closes when the spawned process exits. This feels natural.

**Comment by Grimy** [comment]
This issue is mostly a duplicate of #2171. I think it can be closed. Sorry for the inconvenience.
