### ISSUE TITLE
Cursor set to last line when leaving terminal mode

### ISSUE THREAD

**Issue by Grimy** [neovim/neovim#2257]
When in terminal mode and using `<C-\><C-N>` to return to normal mode, the cursor is positioned on the last line of the window, which is very inconvenient and doesn’t make much sense. vim’s cursor should placed wherever the terminal’s cursor was. At least for shells, that would be much more useful; for some terminal applications it won’t make much sense either.

Tested on a6e53a3 with `-u NONE`.

**Comment by tarruda** [comment]
> When in terminal mode and using to return to normal mode, the cursor is positioned on the last line of the window, which is very inconvenient and doesn’t make much sense. vim’s cursor should placed wherever the terminal’s cursor was

The problem is that most times the terminal cursor is at a invalid buffer position(after the end of a line), so we can't leave the normal mode cursor where the terminal cursor is.

**Comment by noahfrederick** [comment]
If matching the terminal cursor's position isn't feasible, I would expect the normal-mode cursor to start on the first line, like any other buffer, rather than the last line. Perhaps it would feel more natural, too, if the normal-mode cursor position was remembered when going from normal -> terminal -> normal. I suppose that would have to be restricted to remembering the line only, as the column may become invalid as the buffer's content changes.

**Comment by Grimy** [comment]
> The problem is that most times the terminal cursor is at a invalid buffer position(after the end of a line)
How is that a problem? The current behaviour is to place the cursor on the last line of the window, which is also an invalid buffer position when the buffer has fewer lines than the window.

At a minimum, I’d expect the normal mode cursor to be on the same line the terminal cursor was. It would be even better if it tried to match the column as well (which should be possible at least when `virtualedit` is set).

**Comment by tarruda** [comment]
> How is that a problem? The current behaviour is to place the cursor on the last line of the window, which is also an invalid buffer position when the buffer has fewer lines than the window.

The terminal buffer never has fewer lines, it always stretches to the terminal height if necessary.

> At a minimum, I’d expect the normal mode cursor to be on the same line the terminal cursor was. It would be even better if it tried to match the column as well (which should be possible at least when virtualedit is set).

:+1: I will try to implement tmux behavior which is to use the latest column and with the 'virtualedit' special case

**Comment by alcesleo** [comment]
Minor note: If you `:set number` in the terminal buffer the cursor actually ends up inside the numbering after you leave terminal mode. I guess this might be fixed automatically after this. 
![screen shot 2015-09-08 at 17 06 49](https://cloud.githubusercontent.com/assets/2709244/9738501/17f94de0-564c-11e5-8496-de472b262414.png)

**Comment by dnmario** [comment]
Dear Jimmy Börjesson,

The email sent to danielm@tinyhub.tk with subject
"Re: [neovim] Cursor position when leaving terminal mode (#2257)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to danielm@tinyhub.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by Grimy** [comment]
This is probably related to #2259. Both of these can still be reproduced as of e38cbb9.

**Comment by still-dreaming-1** [comment]
I would really like returning to normal mode to keep the cursor position as much as possible as well. I don't mean to be hostile, I know this is an open source project that many people volunteer their time to support. But it is just common sense to work this way. Saying that it doesn't work this way because the position is often invalid is like saying that we can't do the exact thing asked for down to the letter, therefore let's do something completely ridiculous that everyone will hate. I think I understand what is meant though when it is said that the cursor position is often invalid in the buffer. It sounds like the cursor position is often one character to the right beyond what is in the buffer on that line. Well, obviously that means it just needs to be adjusted one character to the left for that case, when going into normal mode. The main advantage of having a terminal emulated in a buffer is you can return to normal mode, so I think it is really important to get that right.

**Comment by still-dreaming-1** [comment]
I found a workaround that works well for me. I already use a custom mapping `kk` to return to normal mode. Once there, I mostly just needed to search for my username which is displayed in my prompt. For me this amounts to
`tnoremap kk <C-\><C-n>G$?jesse<enter>$bl`

**Comment by albertnetymk** [comment]
This reminds me of Acme; however, not keeping the cursor position on mode switching seems rather counter-intuitive.

**Comment by yanlobkarev** [comment]
Agree, very counter-intuitive :/

**Comment by justinmk** [comment]
I also agree, but there are other things that are more important. Help with this would be welcome.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/6185 addresses this
