### ISSUE TITLE
System wide init.lua?

### ISSUE THREAD

**Issue by grappas** [neovim/neovim#22595]
### Problem

There's no way of setting up system wide init.lua. I can set up sysinit.vim but there's no lua equivalent.

### Expected behavior

add sysinit.lua recognition. Also would be fun if there was way to set up system wide ginit.vim and ginit.lua.

**Comment by justinmk** [comment]
ginit.vim and ginit.lua are intentionally not supported, what is the purpose of all these special cases? Just use autocmds or call functions from your main init.lua.

sysinit.lua also is pretty questionable because you can just call a lua file from sysinit.vim. So it is not worth the extra complexity (though it's minor).

**Comment by clason** [comment]
Just put the Lua code in a `lua << EOF ...`  heredoc block. System config files are an antipattern that Neovim doesn't perpetuate further.

**Comment by grappas** [comment]
@justinmk 
> ginit.vim and ginit.lua are intentionally not supported, what is the purpose of all these special cases? Just use autocmds or call functions from your main init.lua.
Understandable.
> sysinit.lua also is pretty questionable because you can just call a lua file from sysinit.vim. So it is not worth the extra complexity (though it's minor).
Change in code base would be minor too though... :(

@clason 
> System config files are an antipattern that Neovim doesn't perpetuate further.
"Antipattern" - what entitles you decide what's good or bad xD? First time I'm hearing something like this.

**Comment by craigmjackson** [comment]
How exactly is it an antipattern to provide sensible defaults for my users that work best for projects most used by the team?  They can always create their own config to override it.

**Comment by dundargoc** [comment]
Because the neovim experience will differ wildly between different distributions and systems which is not desirable for users who expect a consistent behavior. Even if the user can override these, they'll still end up with changed defaults they might dislike and have to spend time to figure out which system file causes the change and what they need to fix in their config.

Also what's the point of relitigating this?  A reasonable workaround has been provided: call lua file from `sysinit.vim` or run lua code directly in `sysinit.vim`
