### ISSUE TITLE
Scrolling with splits and map <ScrollWheelUp/Down>

### ISSUE THREAD

**Issue by kwkelly** [neovim/neovim#2262]
When I `map <ScrollWheelUp> 3<C-Y>` and `map <ScrollWheelDown> 3<C-E>` and use the mouse to scroll in the split that is NOT active, the active one also scrolls. Happens in with both vertical and horizontal splits. Disabling these maps does not have the same issue. Scrolling within the active split works as expected though. 

Example with the maps set: https://gfycat.com/InsidiousCookedAtlanticbluetang

And with them disabled: https://gfycat.com/ScratchyHospitableHeifer

You can see the maps in lines 84 and 85

**Comment by Grimy** [comment]
Unlike scroll events, `<C-E>` and `<C-Y>` always take effect on the active split. With the mappings enabled, the correct behavior would be to scroll only the active split.

I can’t reproduce this issue. What terminal emulator are you using? Can you reproduce the issue on stock vim?

**Comment by kwkelly** [comment]
Terminal is iTerm Build 2.0.0.20141103. 

On stock vim, with the mappings set only the active split scrolls.

**Comment by Grimy** [comment]
I managed to reproduce the issue on XTerm. Here’s a minimal example:

Steps to reproduce
---
Run `nvim -u NONE +'map <ScrollWheelUp> <Nop>' +'set mouse=n nu' +'normal! 200o'`
Scroll the mousewheel up

Expected results
---
Nothing happens (<Nop>)

Actual results
---
The buffer scrolls up irregularly, as evidenced by the line numbers. Roughly one out of two wheel step causes the buffer to scroll up by three lines, with no apparent patterns.
For comparison, scrolling down works perfectly fluidly. Each wheel step causes the buffer to scroll down by three lines.

**Comment by splinterofchaos** [comment]
I took @Grimy's steps to reproduce to vanilla vim and found that it had the same behaviour. Tried to git bissect, but going back as far as 7.4.026, the nop is still ignored (scroll works).

Also, interestingly, if you enter insert mode, then try to scroll, scrolling down inserts `B` on the current and next few lines, then scrolling up inserts `A`.

**Comment by qstrahl** [comment]
Two quirks come together to produce the problem you're seeing:

1. The built-in mappings for scroll wheels are magic, and `<C-e>` and `<C-y>` are not; the former read the mouse position and scroll the window under it. The latter only ever scroll the active window - that is, the window in which the keyboard focus is.
2. When you scroll up multiple "clicks", you send '<ScrollWheelUp><2-ScrollWheelUp><3-ScrollWheelUp><4-ScrollWheelUp>` instead of repeating `<ScrollWheelUp>`. The pattern repeats after `4`. Because you've only bound `<ScrollWheelUp>', your mapping only triggers on the first key of this cycle. The other scroll events are not mapped to anything, and hit the default mouse scroll behaviour.

Neither vim nor neovim give you access to the mouse event magic in a way you can use to solve this problem. The best you can do is make a mapping which uses 'getchar()' to access `v:mouse_win` on the NEXT scroll event, maybe finding a way to cache the mouse event data or something... I've tried, it's a nightmare.

You CAN remap the numbered `ScrollWheel` "keys", but it's tedious and it won't scroll the split under your mouse. See https://github.com/neovim/neovim/issues/6211#issuecomment-473078631

The ideal solution would be something like #1288 but in a hilarious Catch-22, it's closed until issues like this are solved :D

Alternatively, we could maybe populate the 'v:mouse_' vars in mappings, similar to 'getchar()'. This would allow users to make use of mouse information to switch windows or whatever before scrolling. Ideally, I'd like to see both.

**Comment by justinmk** [comment]
This has sat around long enough that https://github.com/neovim/neovim/pull/1288 no longer seems unwarranted. It's an isolated change, and it has parallel with  'mousetime'.

**Comment by justinmk** [comment]
BTW is this issue (#2262) a bug in Nvim or does Vim have the same behavior?

**Comment by qstrahl** [comment]
I'm not sure it's a bug at all, and whether or not you receive the numbered `<ScrollWheel>` events might be terminal-dependent, though I'm only guessing. In any case, it's not as though those numbered events are bad. Strictly speaking, it's a feature.

**Comment by qstrahl** [comment]
You could maybe make a case that the bug is in `:help scroll-mouse-wheel` for giving people the impression that binding ScrollWheel "keys" to normal mode mappings would have a similar effect when it doesn't.

**Comment by justinmk** [comment]
But regarding this particular issue ("mapping mouse to CTRL-E"), I am not sure it's a bug. [Vim has the same behavior](https://github.com/neovim/neovim/issues/2262#issuecomment-88136687).

> temporarily set the active window to the one under the mouse for mouse maps? Seems precarious

Maybe, but I really think this actually wouldn't be welcome. Most GUI programs don't work like that, and most users don't expect "scroll" to change focus based on the mouse pointer.
