### ISSUE TITLE
[bug?] $SHELL inside terminal is that of host shell

### ISSUE THREAD

**Issue by Pyrohh** [neovim/neovim#2278]
- `echo $SHELL` shows `/bin/mksh`
- `nvim -u NONE`
- `:set shell` shows `mksh`
- `:set shell=bash`
- `:set shell` shows that the shell has indeed been changed to `bash`
- `:term`
- inside the slave terminal, `echo $SHELL` shows `/bin/mksh`, despite bash being the actual shell (prompts are different, and running `shopt` works, which isn't in mksh)

`:set shell=/bin/bash` has the same effect

I'd imagine that $SHELL shouldn't be inherited from the host environment into the slave terminal, because it might break `[[ $SHELL == /bin/shell ]] && ...` checks in certain cases.

**Comment by ZyX-I** [comment]
> I'd imagine that $SHELL shouldn't be inherited from the host environment into the slave terminal, because it might break [[ $SHELL == /bin/shell ]] && ... checks in certain cases.

According to http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html

> This variable shall represent a pathname of the user's preferred command language interpreter. If this interpreter does not conform to the Shell Command Language in the Shell and Utilities volume of IEEE Std 1003.1-2001, Chapter 2, Shell Command Language, utilities may behave differently from those described in IEEE Std 1003.1-2001.

“User’s preferred command language interpreter” ≠ “currently used shell”. Scripts using `test $SHELL = /bin/shell` are incorrect (scripts using `[[` are completely incorrect because in those shells which have `[[` there are variables `$ZSH_VERSION`, `$BASH_VERSION` and `$ZSH_VERSION`; usually either these or `$0` variables are used) and I have never actually seen such scripts.

**Comment by ZyX-I** [comment]
Note that if you run bash from zsh for some reason and have `SHELL=/bin/zsh` set in zsh, bash will still have `SHELL=/bin/zsh`. It means that scripts using `test $SHELL` are completely incorrect even in such simple cases (assuming such tests are being used to check what is the *current* shell and not what will be launched when script does `$SHELL -c "foo"`).

**Comment by ZyX-I** [comment]
And another interesting fact from `/bin/bash`: this variable is described as

> The full pathname to the shell is kept in this environment variable.  If it is not set when the shell starts, bash assigns to it the full pathname of the current user's login shell.

. You see: “assigns to it the full pathname of the current user’s *login shell*”, not “assigns to it the full pathname of the bash executable”. `env -i bash -c 'echo $SHELL'` echoes `/bin/zsh` on my system because this is what is my login shell. `env -i zsh -c 'echo $SHELL'` (also mksh, posh and dash) echoes nothing, `ksh` echoes `/bin/sh`: none of the shells bother setting it to path to their executable.
