### ISSUE TITLE
:py cannot deal with suprocesses outputting anything

### ISSUE THREAD

**Issue by SirVer** [neovim/neovim#2283]
Simple way to crash it:

```
$ pip install neovim
$ nvim 
:py import subprocess; subprocess.call(["echo", "hi"])
Error detected while processing function provider#python#Call:
line    1:
Channel 1 sent an invalid message, closed.
```

No `:py` command will not work anymore until Neovim is restarted.

I report this as a neovim bug, because I believe it is a general issue with external plugins. A possible solution is to not use stdin/stdout for communication with external plugins, but rather a socket.

**Comment by tarruda** [comment]
> A possible solution is to not use stdin/stdout for communication with external plugins, but rather a socket

This is possible, but whats the use case of spawning processes with inherited stdio from a python plugin? Even in Vim I fail to see how it is useful, seeing as how the output would be mixed with that of the editor.

If its really necessary then there's a simpler alternative that can be achieved from a change in the plugin host:

- dup stdin/stdout into other fds
- close the original stdin/stdout or redirect it to /dev/null(or to an anonymous pipe if its desired to redirect output to nvim as echoed messages)
- use the dupped fds for communication with Neovim

I say simpler because from neovim it is easier to synchronize with a process started by [`rpcstart()`](http://neovim.org/doc/user/eval.html#rpcstart()) if we know the msgpack payloads are being delivered from the standard streams(no need to wait for a socket connection and associate it with the started process, stdio is already there)

**Comment by SirVer** [comment]
I cannot comment on most of the answer since it seems to be a design choice depending on internals I know nothing about, but this one I can answer:

> Even in Vim I fail to see how it is useful, seeing as how the output would be mixed with that of the editor.

I use MacVim, a GUI which i launch from an xterm. So I have a valid terminal that can be inherited to the child process in Vim.

My use case: I have a lot of small functions that use `:py << EOF` in Vim that do semicomplex things: open a specific line in my current file in the browser with the URL of the line on github, dump something into my TODO file, fetch some data from the webs. They often output debug information or errors and having them interleaved on the console where I started my MacVim Gui is useful to me. If feasible, I think stdout/stderr of plugins should be bridged to the host program.

A line on stdout in a subprogram should not crash the connection though - that at least is a critical bug that must be fixed somehow.

**Comment by blueyed** [comment]
This was fixed in pynvim: https://github.com/neovim/pynvim/commit/14ab154
