### ISSUE TITLE
Spell checker Italian accepts French sentences

### ISSUE THREAD

**Issue by jfmoulin** [neovim/neovim#22934]
### Problem

When spell checking text mixing italian and french sentences with spelllang='it', french sentences are not marked as invalid

### Steps to reproduce

Type the following

    This is a test  
    ceci est un essai
    Questo e una prova
    Dies ist ein Versuch

    :lua vim.opt.spelllang = 'it'
    :lua vim.opt.spell = true

### Expected behavior

Only the third line should be unmarked.

### Neovim version (nvim -v)

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3 Compiled by runner@fv-az183-550

### Vim (not Nvim) behaves the same?

not tested

### Operating system/version

Linux Mint 20

### Terminal name/version

xterm 

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by bonderado** [comment]
This may not even be  bug at all, because the spell checker just verifies individual words and the example text for the reproduction of the bug is not a very good one  since, in Italian:
"ceci" means 'chickpeas',
"est" is the direction opposite to west,
"un" has the exact same meaning it has in French (the article "a"),
and "essai", while definitely a French word, is used in Italian in certain expressions (e.g.: cinema d'essai), thus appearing in Italian dictionaries as a well known foreignism.

If there is a different example that has French-only non-loanwords in it, then the dictionary could need to be amended.

**Comment by jfmoulin** [comment]
Yes... You are absolutely right.
Sorry for raising a meaningless red flag and thanks for the detailed criticism.
Closing.
