### ISSUE TITLE
":terminal cmd" should raise a TermEOF event rather than [Program exited, press any key to close]

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#2293]
[sorry if this was discussed already, I'm catching up on things]

Currently `:term ls` ends with `[Program exited, press any key to close]` and there doesn't appear to be a way to scroll up to see output. It seems like nvim is being a bit too "smart" here: the user should be able to use any Vim commands on the buffer to navigate around the output. Instead of showing `[Program exited, press any key to close]`, nvim can raise a `TermEOF` (or something) event--then users can create their own `[Program exited, press any key to close]` behavior if they want, or they can react to the "EOF" in some other way, or not at all. I already know how to close a window/buffer, I don't want *any key* to do it for me.

**Comment by tarruda** [comment]
I choose to hardcode this exit message because it seems to be a standard behavior in some terminal emulators(terminal.app for example). I agree that a `TermClose` event is better than the forcing the current behavior, but I still think we need to print a exit message because simply jumping to normal mode will make it harder for the user to know when the program exited.

My next PR will add the TermClose autocmd and change the message to `[Program exited]` while jumping into normal mode.

In any case, it should already be possible to press `<c-\><c-n>`(or scroll with the mouse wheel) to interact with a finished program output.

**Comment by justinmk** [comment]
:+1:

**Comment by mhinz** [comment]
So we agree that a `TermClose` event should be added, right?

**Comment by justinmk** [comment]
Yes, though I suggest the message should say `[Process returns <exit code>]` if possible.
