### ISSUE TITLE
Persist window id across sessions

### ISSUE THREAD

**Issue by chikko80** [neovim/neovim#23104]
### Problem

I don't know if its even possible to implement with the current architecture, but due to the lack of that feature, its impossible to create plugins which depend on these window ids and make it work with session managment.

I am currently coding a new window/pane management plugin - which enables moving buffers into new panes rather than moving the pane by itself, which totally works fine, but I obviously can't use it with sessions, since I build a tree data structure in the background which depends on the window ids of the current layout.

### Expected behavior

Saving and restoring window ids across sessions

**Comment by matu3ba** [comment]
Can you describe your problem more specific with some example code?

I use every day `:mks! ses` and `nvim -S ses` works fine and restores all tabs with their layout. If you look closely through windows, then you'll see that the window number is consistent: https://gist.github.com/matu3ba/39d3624de1779584b5cfb2cbe0853513 but might change due to swaps (`C-w [HJKL]`) and the session file then has a different order of split and vsplit.

Did you consider a hacky/ugly workaround of adjusting sessionoptions and remove the unnecessary vim parts?

**Comment by chikko80** [comment]
Yeah i discovered this literally like 10 minutes ago. I was always working with the windows is, which is persistent across the layout no matter where you move the pain, but its not persistent if you load a new session. But you are totally right, the window number instead is always persistent so this solves the issue!
Thanks
