### ISSUE TITLE
vim.fn.taglist is too slow on big tags

### ISSUE THREAD

**Issue by linrongbin16** [neovim/neovim#23330]
### Problem

vim.fn.taglist is too slow on big tags

### Steps to reproduce

open nvim on a super big repo with big tags.

### Expected behavior

is there any other function with faster speed, or has async, timeout, paged query(like sql limit offset) feature? or other replacement?

### Neovim version (nvim -v)

latest nightly

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

macOS 13.3

### Terminal name/version

zsh

### $TERM environment variable

xterm-256

### Installation

github release macos

**Comment by tomtomjhj** [comment]
It's slow because by default it linearly searches the tag file. So async, timeout, paged query, ... won't be useful. 

You can enable binary search by providing the "exact match" query. See `:h taglist()`:

> To get an exact tag match, the anchors '^' and '$' should be
> used in {expr}.  This also make the function work faster.
> Refer to |tag-regexp| for more information about the tag
> search regular expression pattern.

Example usage: https://github.com/tomtomjhj/init.vim/blob/83d8016b72c6f0df09437182f224e925d48b787e/lua/tomtomjhj/cmp_tags.lua#L23
This is fast enough for 1GB tags file for the entire linux codebase.

**Comment by linrongbin16** [comment]
thanks, that is exactly what I am looking for. I am using nvim-cmp-tags plugin, as one of nvim-cmp source.
But the completion is laggy.

**Comment by milanglacier** [comment]
I guess starting from nvim-0.9, `vim.lsp.tagfunc` will be registered as `&tagfunc` may also have influence on this problem.

I feel that using `cmp-nvim-tags` is a bit laggy after upgrading to `nvim-0.9`, and after setting `vim.bo.tagfunc = nil` at the `LspAttach` event, I feel the performance is the same as before 0.9.

I am using a tagfunc of 200M+, and the default is okay to me.

**Comment by linrongbin16** [comment]
I submit some PRs yesterday to cmp-nvim-tags, it is performant now.
