### ISSUE TITLE
Enabling true color from .nvimrc

### ISSUE THREAD

**Issue by wayneashleyberry** [neovim/neovim#2334]
Is it possible to enable true color support from my `~/.nvimrc`?

I can only get it to work using environment variables, `$ NVIM_TUI_ENABLE_TRUE_COLOR=1 nvim`

**Comment by Pyrohh** [comment]
Please see the following comment and below https://github.com/neovim/neovim/pull/2198#issuecomment-83793582

**Comment by tarruda** [comment]
just like you would set any environment variable from vimrc: `let $NVIM_TUI_ENABLE_TRUE_COLOR=1`

**Comment by wayneashleyberry** [comment]
awesome, thanks @Pyrohh and @tarruda :)

**Comment by trusktr** [comment]
I have this line in my vimrc,

```
let $TERM="xterm-256color"
```

which works great on systems where I know I always have color.

**Comment by ZyX-I** [comment]
@trusktr This is totally incorrect, the only right way to set this environment variable is using terminal emulator’s own settings (like `set-option -g default-terminal …` in tmux or “environment variables” list in profile in konsole. Otherwise you will sooner or later run into situation where termcap returns sequences that have nothing to do with your terminal emulator. Not to mention the fact that Neovim is not the only application which needs to access termcap and thus receive correct `$TERM`.

**Comment by trusktr** [comment]
Seems to work fine so far. What can go wrong? Like trying toouse scroll actually input characters into the buffer instead, or similar?

**Comment by sztomi** [comment]
Since this is one of the top Google results: to set 24-bit colors in neovim, the `let $NVIM_TUI_ENABLE_TRUE_COLOR=1` setting no longer works. Now `set termguicolors` is needed.

**Comment by hpjansson** [comment]
Apologies for resurrecting this, but am I correct in assuming NeoVim's terminal will export `TERM=xterm-256color` irrespective of whether `termguicolors` has been set? Is there a reliable way for client applications to detect whether directcolor is supported?

**Comment by gpanders** [comment]
@hpjansson That's a different question than the one in this issue, which is about 24 bit color in Neovim. Presumably, you're asking about how Nvim sets `TERM` in its terminal emulator. Please open a new issue if you have a bug to report (with reproduction steps!), or use Matrix/IRC/StackOverflow/Reddit/Discourse, etc. for usage questions.
