### ISSUE TITLE
Bundle vim-tutor-mode

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#2351]
We have removed vimtutor from the runtime files, but an introduction to (neo)vim is invaluable for beginners. We could just refer them to online resources, but I think we should have a built-in tutorial.

I'm not sure what's the best way to go about this, but it would be great to ship @fmoralesc's [vim-tutor-mode](https://github.com/fmoralesc/vim-tutor-mode) with Neovim. There haven't been any updates to its repository lately, so I assume that it has reached a stable point.

What do you think? Any ideas how to integrate vim-tutor-mode?

Related: #1885

**Comment by fdinoff** [comment]
Is https://github.com/fmoralesc/vim-tutor-mode/issues/6 still relevant?

**Comment by fmoralesc** [comment]
> Is fmoralesc/vim-tutor-mode#6 still relevant?

No, thanks for reminding me to update the issue. ;)

@fwalch For a replacement of vimtutor, I think the current version is probably stable enough (it was fully converted). I would love it if vim-tutor-mode could be used in neovim this way ;) Just tell me what you need.

That said, I wish we had more tutorials to bundle alongside it. I could probably convert the rest of @dahu's [Learnvim](https://github.com/dahu/LearnVim) to vim-tutor-mode's format, since he gave me permission to do so. Any ideas (and help) about this point would be appreciated.

**Comment by Pyrohh** [comment]
> That said, I wish we had more tutorials to bundle alongside it. I could probably convert the rest of @dahu's Learnvim to vim-tutor-mode's format, since he gave me permission to do so. Any ideas (and help) about this point would be appreciated.

That sounds great, I'd gladly help out with that.

**Comment by fwalch** [comment]
@fmoralesc How do you think we could integrate vim-tutor-mode best? Just copy over the files into `runtime/`?

Should we keep the full functionality, or strip it down/modify for use as "built-in plugin" (e.g. remove help on how to write vim-tutor-mode tutorials, only single `:tutor` command)?

**Comment by fmoralesc** [comment]
@fwalch I think it's best not to strip it, because then it could be used by plugin developers for their own documentation (like I did for [vim-pad](https://github.com/fmoralesc/vim-pad/blob/devel/tutorials/vim-pad.tutor) as a proof of example).

As for how to integrate it, it should be enough to copy the relevant files over to runtime. vim-tutor-mode also provides a script to simulate the old `vimtutor` executable, I'm not sure what would be the best approach for that (at any rate, having vim-tutor-mode in the runtime path implies that script would have to be modified).
