### ISSUE TITLE
Missing "/" when DIR name contains parenthesis

### ISSUE THREAD

**Issue by Kirenai** [neovim/neovim#23530]
### Problem

When i try to open a file inside: app\\(login)\\_layout.tsx 
neovim open the file without the path separator: app(login)\\_layout.tsx, and the file is empty.

![image](https://user-images.githubusercontent.com/66179578/236712030-21283c5e-f47c-4c19-9f66-5229d3e747f2.png)

### Expected behavior

That the file path is opened with the separator.
Before: app(login\\_layout.tsx
After: app\\(login)\\_layout.tsx

**Comment by zeertzjq** [comment]
Double the number of backslashes or use `fnameescape()`

**Comment by lmgraf** [comment]
@zeertzjq using `fnameescape()` does **not** fix this issue on windows, because `(` and `)` are not part of `isfname`. There are a lot of plugins that still have issues with this to this day (just look at the mentions in #24542). If we can't include a fix for this in neovim, I think we should at least provide a recommended fix. Can you help with this?

I found that [nvim-tree/nvim-tree.lua](https://github.com/nvim-tree/nvim-tree.lua) fixed this on their own in https://github.com/nvim-tree/nvim-tree.lua/pull/2374 using a helper function in addition to `fnameescape()` (thanks @davisthedev):

```lua
-- Escapes special characters in string if windows else returns unmodified string.
-- @param path string
-- @return path
function M.escape_special_chars(path)
  if path == nil then
    return path
  end
  return M.is_windows and path:gsub("%(", "\\("):gsub("%)", "\\)") or path
end
```

**Comment by justinmk** [comment]
@lmgraf how are you opening the file?

This may be another case where `:nospecial` https://github.com/neovim/neovim/issues/37862 would be helpful.

We could try adding parens to 'isfname' (affects `gf`), but maybe not be necessary; `bufadd()` / `bufload()` seem to reliably avoid filename special chars and 'isfname':

    :call nvim_win_set_buf(0, bufadd('app/(login)/_layout.tsx'))
    :setlocal buflisted

I'll document that somewhere, unless someone knows better...

**Comment by lmgraf** [comment]
@justinmk I am not talking about opening a file manually, I always use plugins to open files (nvim-tree.lua, telescope.nvim). Both of these plugins have (or had in the past) issues with opening files with parentheses in paths e.g. "app/(login)/_layout.tsx".

I would need to dig into the code bases to figure out how they open files. Please lmk if this would help you. But here's a minimal repro:

1. Open nvim without a config
```
nvim --clean
```
2. Define a test filepath (I used backslashes because windows does. If the answer is "just don't use backslashes" or "just double the number of backslashes" then idk what to tell you. Isn't the whole idea of `fnameescape()` to escape these special chars?!):
```
:let g:test_path = 'app\(login)\_layout.tsx'
```
3. Notice how fnameescape does not escape the parentheses. Following command results in: `app\(login)\_layout.tsx`
```
:echo fnameescape(g:test_path)
```

4. Notice how nvim opens `app(login)\_layout.tsx` instead of `app\(login)\_layout.tsx`
```
:execute 'edit ' . fnameescape(g:test_path)
```

This can be fixed by adding `(` and `)` to `isfname` to the config like this:
```lua
vim.o.isfname = vim.o.isfname .. ',(,)'
```
But I think this workaround causes issues in other areas I have no idea about (see `:h 'isfname'`), which is why it probably isn't inside `isfname` by default.

---

Thanks for your ideas, I will see if they work. I have no idea how `:nospecial` is supposed to help though.

**Comment by justinmk** [comment]
@lmgraf I am asking how the plugins open the files. That's what matters. Your notes about `fnameescape` are covered by my previous comment: `bufadd()` is not affected by 'isfname', that's why I suggested it (i.e. nvim-tree.lua, telescope.nvim and should use that)

**Comment by lmgraf** [comment]
Sorry, I overread that (not exactly a neovim expert either). But thanks again, I will dig into the code bases and come back to you.

**Comment by lmgraf** [comment]
To be clear: I am not a maintainer of either of the plugins, just an invested user.

### How nvim-tree.lua opens files:
https://github.com/nvim-tree/nvim-tree.lua/blob/8e8be709c9a93e1ebefde7964884a8b564bfd3e0/lua/nvim-tree/actions/node/open-file.lua#L168-L184

But they fixed it by doing this:
https://github.com/nvim-tree/nvim-tree.lua/blob/8e8be709c9a93e1ebefde7964884a8b564bfd3e0/lua/nvim-tree/utils.lua#L50-L65

### How telescope.nvim opens files:
https://github.com/nvim-telescope/telescope.nvim/blob/9377230aa5305d9e9aca4ed8dadf1070fb4aa9fc/lua/telescope/actions/set.lua#L100

Telescope is still unable to open files with `(` in path, **only on WINDOWS**.

So what's the final recommendation here? using `bufadd()` / `bufload()`?

Edit: idk why github isn't displaying the code inline...

**Comment by justinmk** [comment]
> So what's the final recommendation here? using `bufadd()` / `bufload()`?

yup. AFAICT, they could avoid all that pain with the approach I mentioned:

```lua
local bnr = vim.fn.bufadd(vim.fs.normalize(...))
vim.cmd('buffer '..tostring(bnr))
```
