### ISSUE TITLE
Equivalent of Vim's `state()` function?

### ISSUE THREAD

**Issue by AlexSWall** [neovim/neovim#23576]
### Problem

Currently, [Vim has the built-in `state` command](https://vim-jp.org/vimdoc-en/builtin.html#state()).
I believe this does not currently exist in Neovim.

If it doesn't, I think there's a case to be made to add it. If Neovim has similar functionality, do point me in the right direction.

(I actually only want to check for `o` and `m`, in case that affects the availability in Neovim. I note that we do have `mode` via `vim.api.nvim_get_mode()`.)

### Expected behavior

`state` functionality exists as a command as in Vim.

**Comment by clason** [comment]
Obligatory link: https://github.com/vim/vim/issues/12115#issuecomment-1460041935

Now add to that the additional Lua and libUV loop states relevant to Neovim, and you'll see why this is not really feasible. You'll get better answers if you shared the concrete and complete use case you have.

**Comment by AlexSWall** [comment]
Ah I see, thanks for the link!

Well, for what it's worth, the concrete thing I'm looking to do is relating to the `showcmdloc` with `%S` in e.g. the status line.

I'd like to check whether there's a current pending operator state, and if so only then include a section of my status line with e.g. a background (which I don't want to show otherwise). Alternatively if there's a way to check what `%S` would expand to that would work but I couldn't find anything. The results I found online pointed to using `status()` in Vim.

(Precisely, I'm using Lualine to add this section, and for the function condition of when to show, I want to return as above. Without that, it expands to an empty space or such I believe, and I'm then getting an empty area with the background colour.)

**Comment by clason** [comment]
Well, the simplest thing would be to check for `''` and return `nil` in that case, then.

**Comment by axvr** [comment]
Hi, sorry for resurrecting this thread, but this is something I'd need for the Clojure indentation script to provide a way to detect if the `=` operator is what triggered the indentation.

The desired indentation behaviour is as such (to mimic the Clojure indentation in other editors such as Emacs and VS Code):

1. In insert mode, in a multline string, pressing enter should move down a line and indent to string indentation level.
2. In normal mode in a multiline string, pressing `o` should create a new line indented to string indentation level.
3. In normal mode, indenting a multiline string with `=` should **not** modify indentation within that string.
   - Otherwise reformatting the whole file, or part of a file, could break whitespace significant/intentionally formatted multi-line strings.

The following [code](https://github.com/clojure-vim/clojure.vim/pull/31/files#diff-d0fbef311a440654e941cf93c497aa88f1d0a079d39aac2a45562fffd82c9829R135-R144) works in Vim, but not in Neovim since it lacks the `state()` function.

```vim
return v:operator ==# '=' && state('o') ==# 'o'
```

Unfortunately checking only the `v:operator` variable alone doesn't work as the value sticks around after running it.  The sytax function could reset the `v:operator` variable, but that would break multi-line indentation with `=` (e.g. `gg=G`).

(Now of course if there's a better way of preventing indentation within multi-line strings with `=` I'd definitely want to learn about that too.)
