### ISSUE TITLE
line buffering triggers "rbuffer_consumed: Assertion 'count && count <= buf->size' failed"

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#23781]
### Problem

Neovim crashes.

### Steps to reproduce

```
printf '' | nvim --embed
```

### Expected behavior

No crash. Note that while this reproducer may seem contrived, it actually comes from an actual use case (piping messagepack commands to an embedded neovim from the shell).

This crash may or may not be related to https://github.com/neovim/neovim/issues/21604 .

### Neovim version (nvim -v)

8e6971695383047ee5ba2921c91d98acb18c6d7a

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

linux

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

Built from source

**Comment by ddickstein** [comment]
Hit this problem on 0.9.1 doing the same thing (communicating with Neovim remotely from the shell). Are there any known work-arounds?

**Comment by equalsraf** [comment]
So I came across the exact same issue, but my payload was valid msgpack (but slightly invalid rpc because I made a mistake).

Here is a trace:

```gdb
Program received signal SIGABRT, Aborted.
0x00007f6d37f94fec in __pthread_kill_implementation () from /gnu/store/gsjczqir1wbz8p770zndrpw4rnppmxi3-glibc-2.35/lib/libc.so.6

(ins)(gdb) bt
#0  0x00007f6d37f94fec in __pthread_kill_implementation () from /gnu/store/gsjczqir1wbz8p770zndrpw4rnppmxi3-glibc-2.35/lib/libc.so.6
#1  0x00007f6d37f4b202 in raise () from /gnu/store/gsjczqir1wbz8p770zndrpw4rnppmxi3-glibc-2.35/lib/libc.so.6
#2  0x00007f6d37f3645b in abort () from /gnu/store/gsjczqir1wbz8p770zndrpw4rnppmxi3-glibc-2.35/lib/libc.so.6
#3  0x00007f6d37f36395 in __assert_fail_base.cold () from /gnu/store/gsjczqir1wbz8p770zndrpw4rnppmxi3-glibc-2.35/lib/libc.so.6
#4  0x00007f6d37f444d2 in __assert_fail () from /gnu/store/gsjczqir1wbz8p770zndrpw4rnppmxi3-glibc-2.35/lib/libc.so.6
#5  0x00000000005f9771 in rbuffer_consumed (buf=buf@entry=0xe4b880, count=<optimized out>) at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/rbuffer.c:144
#6  0x00000000005f9792 in rbuffer_consumed_compact (buf=0xe4b880, count=<optimized out>) at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/rbuffer.c:166
#7  0x00000000005b3325 in receive_msgpack (stream=<optimized out>, rbuf=0xe4b880, c=<optimized out>, data=0xe4b0a0, eof=<optimized out>)
    at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/msgpack_rpc/channel.c:305
#8  0x0000000000518040 in read_event (argv=argv@entry=0x7ffd06e966d0) at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/event/rstream.c:192
#9  0x000000000051812c in invoke_read_cb (stream=stream@entry=0xe4b0c0, count=count@entry=14, eof=eof@entry=false)
    at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/event/rstream.c:205
#10 0x000000000051967c in read_cb (uvstream=<optimized out>, cnt=14, buf=<optimized out>) at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/event/rstream.c:134
#11 0x00007f6d3813e7b7 in ?? () from /gnu/store/f8xqz1n89vdm6cf609l6fmqrhi979xbp-libuv-1.43.0/lib/libuv.so.1
#12 0x00007f6d3813f058 in ?? () from /gnu/store/f8xqz1n89vdm6cf609l6fmqrhi979xbp-libuv-1.43.0/lib/libuv.so.1
#13 0x00007f6d38146ad5 in ?? () from /gnu/store/f8xqz1n89vdm6cf609l6fmqrhi979xbp-libuv-1.43.0/lib/libuv.so.1
#14 0x00007f6d38134474 in uv_run () from /gnu/store/f8xqz1n89vdm6cf609l6fmqrhi979xbp-libuv-1.43.0/lib/libuv.so.1
#15 0x00000000005145df in loop_uv_run (loop=loop@entry=0x7dbba0 <main_loop>, ms=-1, once=once@entry=true)
    at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/event/loop.c:65
#16 0x00000000005151b8 in loop_poll_events (loop=0x7dbba0 <main_loop>, ms=<optimized out>) at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/event/loop.c:87
#17 0x00000000005e4196 in inbuf_poll (ms=ms@entry=-1, events=events@entry=0xe014e0) at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/os/input.c:459
#18 0x00000000005e4697 in os_inchar (buf=0x0, maxlen=0, ms=<optimized out>, tb_change_cnt=1, events=0xe014e0)
    at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/os/input.c:143
#19 0x0000000000654ef4 in state_enter (s=0x7ffd06e99bd0) at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/state.c:78
#20 0x00000000005b8fc6 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/normal.c:497
#21 0x00000000004581f4 in main (argc=<optimized out>, argv=<optimized out>) at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/main.c:641
```

The assertion being hit in line 144 is 

```
assert(count && count <= buf->size);
```

gdb also shows us a bit more about the buffer

```
(ins)(gdb) p buf->size 
$4 = 14
(ins)(gdb) p buf->data
$14 = (void *) 0xe4b0c0
(ins)(gdb) x/14xb buf->data
0xe4b0c0:       0x01    0x00    0x00    0x00    0x00    0x00    0x00    0x00
0xe4b0c8:       0xc0    0xb0    0xe4    0x00    0x00    0x00
```

That data does not look like my msgpack payload, the size is correct in that my raw msgpack is 14 bytes long (hex 9400a57265716964a46e616d6590).

Going up the stack trace, the count value has been optimized out and I lacked the source files when I started gdb, but hopefully I loaded them properly. The original caller is receive_msgpack in line 305, and consumed is just size - p->read_size.

```gdb
(ins)(gdb) up
#7  0x00000000005b3325 in receive_msgpack (stream=<optimized out>, rbuf=0xe4b880, c=<optimized out>, data=0xe4b0a0, eof=<optimized out>)
    at /tmp/guix-build-neovim-0.9.1.drv-0/source/src/nvim/msgpack_rpc/channel.c:305
305       rbuffer_consumed_compact(rbuf, consumed);
(ins)(gdb) list
300       size_t size = 0;
301       p->read_ptr = rbuffer_read_ptr(rbuf, &size);
302       p->read_size = size;
303       parse_msgpack(channel);
304       size_t consumed = size - p->read_size;
305       rbuffer_consumed_compact(rbuf, consumed);
306
307     end:
308       channel_decref(channel);
309     }
```

However it looks like consumed will end up begin 0, which would explain the failed assert

```gdb
(ins)(gdb) p size
$19 = 14
(ins)(gdb) p p->read_size 
$20 = 14
```

Still need to dig inside rbuffer_read_ptr to see what is happening.

**Comment by nwounkn** [comment]
`unpacker_parse_header` doesn't update Unpacker's `read_ptr` and `read_size` in case of an error, any invalid header should crash nvim 
This patch seems to fix the issue:
```diff
diff --git a/src/nvim/msgpack_rpc/unpacker.c b/src/nvim/msgpack_rpc/unpacker.c
index c3b1022db..d14d06f95 100644
--- a/src/nvim/msgpack_rpc/unpacker.c
+++ b/src/nvim/msgpack_rpc/unpacker.c
@@ -202,13 +202,10 @@ bool unpacker_parse_header(Unpacker *p)
   mpack_token_t tok;
   int result;
 
-  const char *data = p->read_ptr;
-  size_t size = p->read_size;
-
   assert(!ERROR_SET(&p->unpack_error));
 
 #define NEXT(tok) \
-  result = mpack_read(&p->reader, &data, &size, &tok); \
+  result = mpack_read(&p->reader, &p->read_ptr, &p->read_size, &tok); \
   if (result) { goto error; }
 
   NEXT(tok);
@@ -257,8 +254,6 @@ bool unpacker_parse_header(Unpacker *p)
                                              tok.length, &p->unpack_error);
   }
 
-  p->read_ptr = data;
-  p->read_size = size;
   return true;
 #undef NEXT
 
```

**Comment by strottos** [comment]
I'm pretty sure I've hit exactly this with a plugin I wrote in Rust and it seems to be down to how Rust chooses to flush it's buffers. I've tracked it down to that Rust sometimes will send just this bytes snippet:
```[94, 00, 0A]```
rather than the following more complete which works fine:
```['94', '00', '0A', 'A9', '6E', '76', '69', '6D', '5F', '65', '78', '65', '63', '92', 'D9', '38', '73', '69', '67', '6E', '20', '70', '6C', '61', '63', '65', '20', '31', '31', '35', '37', '38', '33', '31', '20', '6C', '69', '6E', '65', '3D', '35', '30', '20', '6E', '61', '6D', '65', '3D', '56', '61', '64', '72', '65', '42', '72', '65', '61', '6B', '70', '6F', '69', '6E', '74', '20', '62', '75', '66', '66', '65', '72', '3D', '31', 'C2']```
I'd say whatever is connecting should be able to flush buffers however it chooses and Neovim should support this, but I hit the above error: `Assertion `count && count <= buf->size'`
If I remove this assertion everything works fine, and I think it's even only the `count` assertion so I can use the plugin with this line removed, but ideally I'd rather not long term ofc.

Indeed I can trigger it with the following as per the above:
```
$ echo -e -n '\x94\x00\x0a' | ./build/bin/nvim --embed
nvim: /home/strotter/code/nvim/neovim/src/nvim/rbuffer.c:144: rbuffer_consumed: Assertion `count && count <= buf->size' failed.
Aborted (core dumped)
```
but if I remove the count assertion fine:
```
$ echo -e -n '\x94\x00\x0a' | ./build/bin/nvim --embed
$
```
There may be a better fix though, but it seems to work.

**Comment by nikeedev** [comment]
Happens to me too when running packer.nvim commands

**Comment by zeertzjq** [comment]
Also occasionally happens on CI: https://github.com/neovim/neovim/actions/runs/6820700694/job/18550025712

**Comment by eulegang** [comment]
I'm hitting this issue as well.  Within a rust rpc plugin as well.

I believe this is because 0x0A is the newline code point and would get general println flushing treatment.  Low positive numbers get a 0 on the first bit, which means as soon I hit 10 messages sent the message id would trigger this issue.

Hopefully this is a useful/interesting observation.

**Comment by eulegang** [comment]
I was able to remedy by using an io type that does not flush after newlines are found.

`unsafe { tokio::fs::File::from_raw_fd(1) }` opposed to `tokio::io::stdout()`

**Comment by KillTheMule** [comment]
I've started investigating this, and it's definitely entered Heisenterritory for me...

For reproduction, see https://github.com/KillTheMule/reqbug. Check out the neovim submodule, build with the [included script](https://github.com/KillTheMule/reqbug/blob/main/build_nvim) (just so we have a debug build), and then run [runit.sh](https://github.com/KillTheMule/reqbug/blob/main/runit.sh). This needs a working rust installation.

Notes for reproduction:

- Doesn't always reproduce, but so far I could always trigger it by manually repeating the runit script. 
- Harder to trigger when nvim does not find a valid runtime at the default location, but still possible
- I've had some very light logging added https://github.com/neovim/neovim/blob/master/src/nvim/msgpack_rpc/channel.c#L285, which made triggering the problem less likely, but still possible

I've also added a neovim log from a [crash](https://github.com/KillTheMule/reqbug/blob/main/nvimlog_crash.txt) as well as a [non-crash](https://github.com/KillTheMule/reqbug/blob/main/nvimlog_nocrash.txt) (note that the latter also contains me typing `:qa!<Enter>` manually).

Some notes and questions;
- Channel 3 is used both for my job as well as communication with the TUI (at least that's what it seems like). Is that expected, are there no interactions? As far as I can tell, different streams (even when associated with the same channel) have their own ring buffers, so the shouldn't interfere, but I wanted to make sure. Seems strange to me anyways, since how does neovim determine what to use for e.g. `chansend`?
- When sending our Request, nvim sometimes reads 27 bytes, and sometimes 26. I've no idea where that is coming from.
- When neovim crashes, it always read 3 bytes directly before. That's always on message 10, so the last byte is 10, aka a newline.
- Rust's `stdout` is line-buffered indeed, but that should be strictly deterministic. Whatever makes neovim sometimes read those 3 bytes, and sometimes not? Also, when sending other messages containing newlines, that just doesn't seem to happen, and I've not yet figured out why.
- When sending huge messages, other buffers come into play (e.g. the one from the OS, or from out own wrapping of `stdout`), but neovim has no problems whatsover reading multpart-messages in these cases, at least not that I could discern.

Guess the next step is trying out the linked PR, but if anyone has more insights or comments, that would certainly be welcome.

**Comment by KillTheMule** [comment]
I'm kind of a loss for words :D I've applied https://github.com/neovim/neovim/pull/25494 to neovim, and the following happens:

- I can still trigger the crash
- When *not* crashing, the log says neovim read 29 bytes from our message. Note we're still sending 26.
- When crashing, the log says neovim read 28 bytes from our message. We're still sending 26. The reading of message 10 again files with 3 bytes read.
I've noted though that the comment for [`rbuffer_read_ptr`](https://github.com/neovim/neovim/blob/master/src/nvim/msgpack_rpc/channel.c#L304C17-L304C33) says it needs to be called twice, possibly using a macro. I'm not seeing how to apply that here (my C is pretty rusty), but might that be a problem?

**Comment by KillTheMule** [comment]
Ok, I've worked through it. See [the repository](https://github.com/KillTheMule/reqbug) if you want to try any of it yourself.

I've been able to log the stdout of my plugin, and I could very well see the linebuffering happening. The indeterminism probably comes from our flushing of the buffer, which could well happen before neovim reads the flushed message from the pipe, and then the pipe does contain the full message. So it's pretty timing dependent, agreeing with what I saw before.

It's not just in the msgpack metadata, but of course also happens when the payload contains a newline, as in `feedkeys("ia\n<Esc>")`. Nvim doesn't crash in that case though, but just does not read on from the pipe and therefore does not act upon the message (which includes responding here, I don't know what happens if I send another message after that).

@zeertzjq @bfredl @justinmk So it seems neovim can't handle partial messages from flushing a buffer early. If the flushing happens after the message ID, neovim crashes (as in this issue), if it happens in the payload, neovim seems to just be stuck in the communication of that channel. I'd suggest treating this as a bug, although I'm not aware of any spec saying anything about this (and I don't know how hard it is to change this).

I'll fix this in my lib by disabling line buffering.

**Comment by bfredl** [comment]
>  Nvim doesn't crash in that case though, but just does not read on from the pipe and therefore does not act upon the message (which includes responding here, I don't know what happens if I send another message after that).

Not sure I follow. if the external library does "line buffering" it is quite expected nvim will do nothing when `\n` is received, nvim will act once a complete message has been received. Nvim itself has no idea about line buffering in an RPC channel. it is just a sequence of bytes. 

I mean the real issue in nvim seems to be about handling of messages of large enough byte sizes (so multiple separate `read()` events are expected to stitch together a full message), not about lines per se.

**Comment by KillTheMule** [comment]
> nvim will act once a complete message has been received

That does not seem to be the case here. I hope my c&p and manual counting works out, but it seems the following:

Take the message ` [148, 0, 10,177, 110, 118, 105, 109, 95, 98, 117, 102, 95, 115, 101, 116, 95, 110, 97, 109, 101, 146, 212, 0, 1, 162, 97, 57]`, which is `nvim_buf_set_name(1, "a10")` in msgpack. If the buffer is flushed to the pipe after the third byte, the pipe contains `[148, 0, 10]`. If neovim reads that, it crashes, and does not wait for the rest of the message (this is what this issue seems to be about).

Take the message `[148, 0, 1, 173, 110, 118, 105, 109, 95, 102, 101, 101, 100, 107, 101, 121, 115, 147, 176, 105, 97, 10, 60, 69, 115, 99, 62, 105, 97, 10, 60, 69, 115, 99, 62, 160, 195]`, which is `nvim_feedkeys("ia\n<Esc>ia\n<Esc>","", true)` in messagepack. If the buffer is flushed to the pipe after the last 10, but before the 60, neovim reads the 30 bytes of the first part of the message, but never seems to read the rest which would complete the message an enable neovim to answer the request.

> not about lines per se.

Sure, lines come only into play here because I did use a linebuffered stdout in my library, so they "merely" serve as examples here.

**Comment by justinmk** [comment]
> the pipe contains `[148, 0, 10]`. If neovim reads that, it crashes,

If you can't you reproduce that with a Lua test, can you try hardcoding it in Nvim C code and confirm that it causes the crash, then share the patch here?

**Comment by bfredl** [comment]
FWIW, the mpack `Unpacker` would be a good candidate for systematic fuzz testing. Could be done somewhat regularly by taking some large dictionary of valid message strings (like the functional test suite) and split them into (at least) two pieces at any breaking point.

**Comment by KillTheMule** [comment]
> > the pipe contains `[148, 0, 10]`. If neovim reads that, it crashes,
> 
> If you can't you reproduce that with a Lua test, can you try hardcoding it in Nvim C code and confirm that it causes the crash, then share the patch here?

I've no idea how to go about this with a lua test... I'll have a look around, otherwise I'm gonna try the C route.

**Comment by KillTheMule** [comment]
See https://github.com/neovim/neovim/pull/27164 for what I've managed to come up with. At least something reproduceable, isn't it?

**Comment by KillTheMule** [comment]
Ok, I've been fiddling enough that the crash reproduces on CI now \,,/ I've noted though that I should be able to write to the pipe via luv, so that will be my next task :)

**Comment by KillTheMule** [comment]
I've managed to do this [in lua](https://github.com/KillTheMule/neovim/commit/13731b75ed98d64fc299eab1385b3d4874d760ba) as well. I was unsuccessfull killing the nvim instance we're running by directly writing to our own socket, though, which makes debugging probably slightly worse... maybe I can improve on that :)

**Comment by jinzhongjia** [comment]
When I just request `nvim_get_current_buf` I find it doesn't crash, which is weird

**Comment by jinzhongjia** [comment]
After investigation, neovim is sending a response to the client when the error occurred. Maybe I need to conduct further investigation.

**Comment by jinzhongjia** [comment]
I re-tested on wsl (archlinux) and found that as long as I requested `nvim_get_api_info`, neovim would crash. I conducted simple debugging and found that neovim's crash occured in the response phase.

**Comment by jinzhongjia** [comment]
I send this u8 array [148, 0, 60, 177, 110, 118, 105, 109, 95, 103, 101, 116, 95, 97, 112, 105, 95, 105, 110, 102, 111, 144] to neovim, neovim will crash (no reading neovim), and this is :
```json
[
    0,
    60,
    "nvim_get_api_info",
    []
]
```

**Comment by jinzhongjia** [comment]
I found that the problem is that if I send two requests, even if they are sent synchronously, nvim will crash (it is not a problem with nvim_get_api_info)
why?

**Comment by jinzhongjia** [comment]
I choose to buffer each request and then flush it, now it works well

**Comment by saidelike** [comment]
I hit what I believe is the same problem. My environment is Windows 10, I use nvim-qt.exe which spawns nvim.exe. I use neovim@4.11.0 imported into a nodejs project (using node-client (npm "neovim" package). Accessing whatever from the neovimClient triggers a crash.

This is enough to crash:

```typescript
  const client = (await plugin.nvim) as NeovimClient;
  const ret = await client.window;
  console.log("window ", ret);
  const lines = (await client.buffer).lines;
  console.log("lines ", lines);
```

An example of crash of `nvim.exe` below:

```
0:000> k
 # Child-SP          RetAddr               Call Site
00 0000008c`4e8fed40 00007ffb`28ac426e     ucrtbase!abort+0x4e
01 0000008c`4e8fed70 00007ffb`28ac4165     ucrtbase!common_assert_to_stderr_direct+0xb2
02 0000008c`4e8ff260 00007ffb`28ac44f1     ucrtbase!common_assert_to_stderr<wchar_t>+0x1d
03 0000008c`4e8ff2a0 00007ff6`c2bb15bb     ucrtbase!wassert+0x71
04 0000008c`4e8ff2d0 00007ff6`c2bb165f     nvim!rbuffer_consumed+0x4b [D:\a\neovim\neovim\src\nvim\rbuffer.c @ 144] 
05 0000008c`4e8ff300 00007ff6`c2b6629b     nvim!rbuffer_consumed_compact+0x3f [D:\a\neovim\neovim\src\nvim\rbuffer.c @ 167] 
06 0000008c`4e8ff330 00007ff6`c2acf16c     nvim!receive_msgpack+0xcb [D:\a\neovim\neovim\src\nvim\msgpack_rpc\channel.c @ 311] 
07 0000008c`4e8ff490 00007ff6`c2acf25f     nvim!read_event+0x3c [D:\a\neovim\neovim\src\nvim\event\rstream.c @ 194] 
08 0000008c`4e8ff4d0 00007ff6`c2acefcf     nvim!invoke_read_cb+0xbf [D:\a\neovim\neovim\src\nvim\event\rstream.c @ 211] 
09 0000008c`4e8ff5f0 00007ff6`c2ccdb72     nvim!read_cb+0x6f [D:\a\neovim\neovim\src\nvim\event\rstream.c @ 135] 
0a 0000008c`4e8ff620 00007ff6`c2ccea42     nvim!uv__pipe_read_data+0xb2 [D:\a\neovim\neovim\.deps\build\src\libuv\src\win\pipe.c @ 1954] 
0b 0000008c`4e8ff680 00007ff6`c2ccb78d     nvim!uv__process_pipe_read_req+0x122 [D:\a\neovim\neovim\.deps\build\src\libuv\src\win\pipe.c @ 2084] 
0c (Inline Function) --------`--------     nvim!uv__process_reqs+0x90 [D:\a\neovim\neovim\.deps\build\src\libuv\src\win\req-inl.h @ 159] 
0d 0000008c`4e8ff6d0 00007ff6`c2accc6a     nvim!uv_run+0x19d [D:\a\neovim\neovim\.deps\build\src\libuv\src\win\core.c @ 658] 
0e 0000008c`4e8ff710 00007ff6`c2acccc5     nvim!loop_uv_run+0x8a [D:\a\neovim\neovim\src\nvim\event\loop.c @ 66] 
0f 0000008c`4e8ff750 00007ff6`c2b97d58     nvim!loop_poll_events+0x15 [D:\a\neovim\neovim\src\nvim\event\loop.c @ 88] 
10 0000008c`4e8ff780 00007ff6`c2b975bc     nvim!inbuf_poll+0xb8 [D:\a\neovim\neovim\src\nvim\os\input.c @ 459] 
11 0000008c`4e8ff7b0 00007ff6`c2c069bb     nvim!os_inchar+0xec [D:\a\neovim\neovim\src\nvim\os\input.c @ 133] 
12 0000008c`4e8ff7f0 00007ff6`c2b6c53e     nvim!state_enter+0xbb [D:\a\neovim\neovim\src\nvim\state.c @ 80] 
13 0000008c`4e8ff830 00007ff6`c2a11ebf     nvim!normal_enter+0x7e [D:\a\neovim\neovim\src\nvim\normal.c @ 501] 
14 0000008c`4e8ff940 00007ff6`c2cea890     nvim!wmain+0x9af [D:\a\neovim\neovim\src\nvim\main.c @ 645] 
15 (Inline Function) --------`--------     nvim!invoke_main+0x22 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 90] 
16 0000008c`4e8ffbc0 00007ffb`29997344     nvim!__scrt_common_main_seh+0x10c [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
17 0000008c`4e8ffc00 00007ffb`2ab626b1     KERNEL32!BaseThreadInitThunk+0x14
18 0000008c`4e8ffc30 00000000`00000000     ntdll!RtlUserThreadStart+0x21
```

Other attempts which crashed too:

```typescript
  const buf = await client.buffer;
  const ret = client.isApiReady;
  console.log("isApiReady ", ret);   // true
```

```
  const type = await client.request("nvim_buf_get_option", [
    buf.id,
    "filetype",
  ]);
  console.log("request success", type); // "python" if test.py is open
```

Note that usually I get a reply to the client request (that I can check in the debugger) and the reply seems valid so it seems the nvim.exe crash happens afterward in some code path triggered by my request. If I don't do the request, nvim.exe does not crash

**Comment by saidelike** [comment]
Updating neovim to the latest nightly

```
C:\Windows\System32>"C:\Program Files\Neovim\bin\nvim.exe" -V1 -v
NVIM v0.10.0-dev-2480+g0eaae1bc0
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /DWIN32 /D_WINDOWS /MD /Zi /O2 /Ob1 /GL -W3 -wd4311 -wd4146 -wd4003 -wd4715  -DUNIT_TESTING -DHAVE_UNIBILIUM -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```
And it is node.exe (20.10.0.0, build time: Wed Nov 22 08:30:22 2023) crashing now.

![image](https://github.com/neovim/neovim/assets/387346/6b990715-0c8d-4a47-8d5f-30c7cc88ed78)

I know it is not a neovim problem in this case, though. Due to the randomness of that problem I can't say what the state is in neovim.

**Comment by justinmk** [comment]
> Updating neovim to the latest nightly

Not clear from your last comment. Are you still hitting `rbuffer_consumed` crash in latest Nvim?

**Comment by saidelike** [comment]
One question I have is: does it impact mostly Windows or also other OS? I know the original issue was on Linux but it was 9 months ago.

**Comment by saidelike** [comment]
One question I have is: does it impact mostly Windows or also other OS? I know the original issue was on Linux but it was 9 months ago.

**Comment by saidelike** [comment]
To answer my own question...

My understanding is that the line buffering behaviour (https://github.com/KillTheMule/nvim-rs/issues/47) is Windows-only in nvim-rs as their patch (https://github.com/KillTheMule/nvim-rs/commit/c5cfcc9140ea9bf2dc82605319eaed8aeb3d468e) does not change Linux behaviour (they just changed it for Windows).

However the underlying problem in neovim (this current issue: "count && count <= buf->size") is for any OS. It just happens to trigger all the time on Windows when using nvim-rs or node-client due to line buffering.

So to be clear, it seems the problem on neovim side is that it is not able to handle an incomplete message. Would it be possible to add support for it? It might not be enough to just check the header etc. It needs to assume the remaining data is going to come later potentially?

Fwiw it might be a workaround solution for me if we can figure out a similar way to avoid line buffering in node-client to avoid the neovim crash but it means the underlying issue in neovim will still be present.

**Comment by jinzhongjia** [comment]
Yes, the current problem is that neovim cannot handle incomplete messages correctly, which causes the client to send a complete message rpc message every time.
It is recommended not to use line buffering and flush the buffer manually
I do that on zig

**Comment by saidelike** [comment]
Can you point me to the zig code to see how you do it?

Also, do you use https://github.com/neoclide/neovim ? Just curious if it will have the line buffering behaviour too on Windows.

**Comment by KillTheMule** [comment]
> My understanding is that the line buffering behaviour ([KillTheMule/nvim-rs#47](https://github.com/KillTheMule/nvim-rs/issues/47)) is Windows-only in nvim-rs as their patch ([KillTheMule/nvim-rs@c5cfcc9](https://github.com/KillTheMule/nvim-rs/commit/c5cfcc9140ea9bf2dc82605319eaed8aeb3d468e)) does not change Linux behaviour (they just changed it for Windows).

That's not true, the behavior happens in non-windows as well. The relevant PR is https://github.com/KillTheMule/nvim-rs/pull/48.

> However the underlying problem in neovim (this current issue: "count && count <= buf->size") is for any OS. It just happens to trigger all the time on Windows when using nvim-rs or node-client due to line buffering.

"All the time" is a bit of a misnomer. In the case of `nvim-rs`, the behavior is racy... sometimes, we seem to manage to write the second part of the message to the pipe before neovim reads the first part, and then things are fine (at least that's what I think, as with all things racy, it would need a lot of investigation to be really sure here).

> So to be clear, it seems the problem on neovim side is that it is not able to handle an incomplete message. 

From my testing, neovim can handle incomplete messages, but not incomplete headers. Requests are of the form `[type, msgid, method, params]`, and in `nvim-rs`s case, we flushed the buffer after the `msgid`, which made neovim crash. I've had tests with other forms of buffering where the buffer was flashed inside of `params` (or a single param string, as far as I recall), and that did not pose a problem (although that might still be somewhat untrue due to the suspected racyness).

> Fwiw it might be a workaround solution for me if we can figure out a similar way to avoid line buffering in node-client to avoid the neovim crash but it means the underlying issue in neovim will still be present.

The best way seemt to be to just flush your output buffer after each message directly, but not inbetween. Most messages aren't so large that they need to be split due to buffer size, and as I said, it seems unproblematic to flush in the payload part.

**Comment by jinzhongjia** [comment]
> Can you point me to the zig code to see how you do it?
> 
> Also, do you use [neoclide/neovim](https://github.com/neoclide/neovim) ? Just curious if it will have the line buffering behaviour too on Windows.

I don't use neoclide/neovim, but coc.nvim works fine, my zig code is here, https://github.com/jinzhongjia/znvim/blob/2103ac12f2ea97abc56a8ea10115c82f801d2a4e/src/rpc.zig#L367
Just wrap a buffer and flush it manually

**Comment by strottos** [comment]
I don't think there's any question that Rust library that caused me the issue was slightly (and I mean slightly) suboptimal here in doing line vs bytes buffering. The latter is clearly what we want and, since it was changed to that, has basically solved the problem.

Nevertheless, I strongly think Neovim shouldn't crash if it gets incomplete data that was buffered awkwardly, technically awkward buffering like this could happen at any point, crashing is not desired output. Or you know, someone else implementing this kind of thing makes a similar bug.

**Comment by justinmk** [comment]
> From my testing, neovim can handle incomplete messages, but not incomplete headers

👀 

From the above discussion and https://github.com/neovim/node-client/issues/329 , it sounds like we could get a useful test-case if we can control the buffering. @KillTheMule were you able to get minimal test-case in Lua? Was there a followup to  https://github.com/neovim/neovim/pull/27164 ?

**Comment by glacambre** [comment]
I believe this patch is a good reproducer:
```
diff --git a/test/functional/api/server_requests_spec.lua b/test/functional/api/server_requests_spec.lua
index 298dbac21..6929ccb9c 100644
--- a/test/functional/api/server_requests_spec.lua
+++ b/test/functional/api/server_requests_spec.lua
@@ -319,6 +319,24 @@ describe('server -> client', function()
       connect_test(server, 'pipe', address)
     end)
 
+    it('via stdio, with variable flushing', function()
+      source([[
+      let chan = jobstart([v:progpath, '--embed', '--headless', '-n', '-u', 'NONE', '-i', 'NONE'], { 'rpc':v:false })
+      call chansend(chan, 0Z94)
+      sleep
+      call chansend(chan, 0Z00)
+      call chansend(chan, 0Z01)
+      call chansend(chan, 0ZAC)
+      call chansend(chan, 0Z6E76696D5F636F6D6D616E64)
+      call chansend(chan, 0Z91)
+      call chansend(chan, 0ZA5)
+      call chansend(chan, 0Z71616C6C21)
+      let g:statuses = jobwait([chan])
+      ]])
+      eq(eval("g:statuses"), { 0 })
+      assert_alive()
+    end)
+
     it('via ipv4 address', function()
       local server = spawn(nvim_argv)
       set_session(server)
```

**Comment by KillTheMule** [comment]
> > From my testing, neovim can handle incomplete messages, but not incomplete headers
> 
> 👀
> 
> From the above discussion and [neovim/node-client#329](https://github.com/neovim/node-client/issues/329) , it sounds like we could get a minimal test-case by setting the buffering mode. @KillTheMule were you able to get minimal test-case in Lua? Was there a followup to #27164 ?

Yeah I've made something in https://github.com/KillTheMule/neovim/commit/13731b75ed98d64fc299eab1385b3d4874d760ba, it's quite raw, but basically realizes this in a lua test (I've abused the structure quite a bit, one needs to run the TESTFILTER="via named pipe"). But @glacambre seems to have produced something that kills one's own nvim process, which seems much better for debugging :)

**Comment by bfredl** [comment]
ok, I think this might just be an overzealous assert. There's nothing wrong with not consuming anything after receiving some input:
```
diff --git a/src/nvim/rbuffer.c b/src/nvim/rbuffer.c
index ef286b3e22..493c079d4c 100644
--- a/src/nvim/rbuffer.c
+++ b/src/nvim/rbuffer.c
@@ -123,7 +123,10 @@ char *rbuffer_read_ptr(RBuffer *buf, size_t *read_count) FUNC_ATTR_NONNULL_ALL
 void rbuffer_consumed(RBuffer *buf, size_t count)
   FUNC_ATTR_NONNULL_ALL
 {
-  assert(count && count <= buf->size);
+  if (count == 0) {
+    return;
+  }
+  assert(count <= buf->size);
```
