### ISSUE TITLE
:set nowrap in  a :terminal does not work 

### ISSUE THREAD

**Issue by Bilalh** [neovim/neovim#2380]
Setting nowrap in a  terminal does not work.

On the left pane below  (a python file)  using `:set nowrap` worked as expected. In the right pane with the terminal in it the lines are still wrapped even when `:set nowrap` has been used.

![screen shot 2015-04-08 at 19 24 55](https://cloud.githubusercontent.com/assets/171602/7052230/3419116c-de25-11e4-9caf-ea7b5865aa4a.jpg)

**Comment by ZyX-I** [comment]
This is correct. Buffer on the left is *not* using usual wrapping mechanizm. Lines are wrapped by the library that manages terminal screen and it has a perfect reason to work the way it does work: software like zsh calculates where terminal will wrap and issues cursor positioning commands accordingly. You *cannot* make a terminal emulator which does not wrap and works correctly in different applications.

It may make sense to provide an option to *force* certain terminal width or length, no matter which buffer terminal is displayed within. This will break some applications (I mean, those that manage the whole terminal screen like Vim or tmux), but this may be desired in some cases like now.

**Comment by Bilalh** [comment]
That make sense,  but  there is a  terminal emulator that does no line wrapping   https://code.google.com/p/jessies/wiki/Terminator

I tested it with vim, tmux and REPLs (ghci) and it works. 

![screen shot 2015-04-08 at 20 21 23](https://cloud.githubusercontent.com/assets/171602/7053414/e0dcfa7e-de2c-11e4-99c7-76f9000c9891.png)

**Comment by ZyX-I** [comment]
@Bilalh Wondering how shells behave there (especially those with both prompt and right prompt): with DEC “no wraparound” mode supported by libvterm and xterm zsh behaves badly, clearing first line with user input and positioning cursor on the line *above* the prompt.

(I leave a possibility though that terminal can be queried about whether it performs line wrapping.)

Though in any case this is question to @leonerd because I am not sure his library allows this or can be extended to allow. It has “no wraparound” mode (`echo $'\e[?7l'`), but (at least in NeoVim that uses libvterm and xterm which does not, but usually considered to be a “reference implementation”) this cuts the line, not allows it to be extended. And zsh behaves badly with long lines of user input when this mode is activated.

**Comment by ZyX-I** [comment]
@Bilalh Note: you need to use REPL with complex cursor management like bash, zsh or fish have (in order of rising complexity): in “no wraparound mode” they all clearly show that when it is time to wrap they are telling terminal to do something. Simple readline (or something with similar capabilities)-based REPLs do not do anything like this, at maximum you will have undesired behaviour on `<C-u>` (when clearing the whole line).

**Comment by Bilalh** [comment]
@ZyX-I  Could you give more example of complex cursor management?  I added a right prompt  and tried C-u on a wrapped line. Both  worked for me.   How do I use test `DEC “no wraparound” mode`?

![screen shot 2015-04-08 at 21 37 14](https://cloud.githubusercontent.com/assets/171602/7054863/82bb075a-de37-11e4-9401-17c51d125704.png)

**Comment by Pyrohh** [comment]
This seems similar enough to #2360 and #2514, so I'll close this. Please reopen if that's incorrect.

**Comment by justinmk** [comment]
Actually @Pyrohh this issue seems more useful than #2360
