### ISSUE TITLE
Neovim destroying certain symlinks on windows

### ISSUE THREAD

**Issue by thirstyice** [neovim/neovim#23808]
### Problem

When I edit a file through a symlink (eg `:e ~/.vimrc` where .vimrc is a symlink to another location) nvim replaces the symlink with a copy of the linked file (`backupcopy=auto` behaves like `no` for symlinks?)

Edit: Specifically happens to symlinks created with `ln -s` in git bash (and maybe other cygwin-like shells?)

### Steps to reproduce

`nvim --clean`
`:e foo` (where foo is a symlink)
observe that `foo` is no longer a symlink

### Expected behavior

Edit the linked file without destroying the symlink
(behave as if `backupcopy=yes` for symlinks?)

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

Unknown, but see https://superuser.com/questions/193872/vim-destroys-symbolic-links-under-windows

### Operating system/version

Windows 11 22H2

### Terminal name/version

Nvy 0.3.5, cmd.exe

### $TERM environment variable

N/A?

### Installation

Windows msi

**Comment by 3N4N** [comment]
Doesn't happen for me, even though OP and I are using the same version of Windows.  Interesting.

@thirstyice how did you create the symlink?  I used this:

```
New-Item -Type SymbolicLink -Path .\link.txt -Value .\main.txt
```

**Comment by thirstyice** [comment]
Did some further investigating:
If I make the link with the method described by @3N4N, then it doesn't get overridden.
If I make the link using `mklink`, then it doesn't get overridden
But, if I make the link using `ln -s` from mintty, it gets overridden

So it looks like something about the links created by `ln -s` is causing them to not be recognized as links by nvim.
And it's definitely still a "nvim overriding the link" problem because the hidden attribute also gets unset, in addition to the link being broken

**Comment by 3N4N** [comment]
Interesting.  By mintty (which is a terminal emulator for cygwin or cygwin-like shells), I assume you mean cygwin or cygwin-like shell (e.g., git-bash, msys, etc).  I use msys, but I don't use its symlink feature.  I don't think enabled by default anyway.  In any case, yes, it is a "neovim overriding the link" problem.  Perhaps neovim isn't realizing it's a symlink.  Which begs the question, __what are the different kinds of links available in Windows and which of these is created by `ln -s`?__

I have no insight into this and no interest to acquire any.  I personally prefer the native solution (e.g., `mklink` instead of `ln -s`) as far as possible, so I don't have the incentive to investigate this.  Leaving the previous paragraph of this comment for any tentative contributor.

P.S.  @thirstyice consider updating the original issue description with the name of your cygwin-like shell.

**Comment by thirstyice** [comment]
You're right, I was using git-bash.

I also don't really have any insight into this either since I'm not very familiar with how windows files work re:links. I'm usually more of a unix person (hence why I originally went for `ln -s`).

I'd be down to do some poking if anyone wants is jazzed to get to the bottom of this, but it's not super high on my priority list since it's so easy to just avoid the problem altogether (using `mklink`)

**Comment by ykhan21** [comment]
To allow `ln -s` to work in git bash, you will need to enable symlinks in the Git Bash installer, or enable Windows Developer Mode in Settings and set `export MSYS=winsymlinks:nativestrict` in your .bashrc or run git bash as Administrator and set `export MSYS=winsymlinks:nativestrict` in your .bashrc.

See this answer and its comments: https://stackoverflow.com/a/40914277/8917573.

**Comment by thirstyice** [comment]
That's good information, though I think as it relates to this issue it's even better explained by point 2 in [this answer](https://stackoverflow.com/a/63325536)

Basically, when trying to create a link with `ln -s` without having taken the above steps `ln` will create a copy of the link target in place of the link you expect, which works great until either the link or the target are modified, at which point it becomes obvious that they are not actually linked.
(The actual cause of this "broken" link is much less obvious, hence this issue lol.)

In any case, this is not a problem with Neovim.
