### ISSUE TITLE
Semantic Token highlight randomized for equal priority

### ISSUE THREAD

**Issue by williamhCode** [neovim/neovim#23825]
### Problem

I get inconsistent highlighting for the same type of variables.  
For example here, the `BlendFactor` enum is getting different highlighting even though they're the same type.  
When I quit neovim and come back, the highlighting is changed.
First time:
<img width="833" alt="image" src="https://github.com/neovim/neovim/assets/83525937/df0999fb-1356-4377-b187-1651e76e2d1f">
Quit then reopen file:
<img width="833" alt="image" src="https://github.com/neovim/neovim/assets/83525937/f45520ab-944f-4eaa-85a0-17e7d4f979d1">

I've tried this with many different colorschemes and they all have the same problem.

### Steps to reproduce

I tried to create a minimal config but couldn't get it working, but it doesn't seem like this bug can be caused by other plugins or configuration.

1. Install any colorscheme that supports semantic tokens  
2. Setup lsp that supports semantic tokens
3. Edit a file with semantic token highlighting, and check the highlights

### Expected behavior

The highlight that isn't `None` on the most bottom when doing `:Inspect` should be the highlight color. In my case, all my the enums should be highlighted to orange instead of yellow.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-415+g55f6a1cab-Homebrew Build type: Release LuaJIT 2.1.0-beta3

### Vim (not Nvim) behaves the same?

no, vim has no semantic tokens

### Operating system/version

macos 12.6.5

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

homebrew

**Comment by swarn** [comment]
Hi @williamhCode. This is operating as expected: `priority` is the only mechanism for determining which highlight "wins" if they set conflicting attributes. In your example, conflicting colors are being set at the same priority, so it is **not specified** which color will be shown. This is an issue with your colorscheme. There are three ways forward:

- The colorscheme can choose non-conflicting highlights. For example, if `@lsp.typemod.variable.defaultLibrary` is italic and `@lsp.typemod.variable.readonly` is orange, then variables which are both read-only _and_ in the the default library will be underlined and orange.
- The colorscheme can pick only mutually-exclusive `typemod` highlights. You can safely link `@lsp.typemod.variable.classScope` and `@lsp.typemod.variable.localScope` to different colors, because one variable can't have two scopes.
- The colorscheme can use the `LspTokenUpdate` autocommand to deconflict the highlighting, either using different priorities, or by using logical expressions (e.g. something like "if readonly then if deafaultLibrary then orange else yellow"). See [my guide](https://gist.github.com/swarn/fb37d9eefe1bc616c2a7e476c0bc0316).

The order you are seeing in `:Inspect` is simply the display ordering generated _for the Inspect command_: sort by priority, then string sort. But that ordering is not otherwise meaningful.

**Comment by williamhCode** [comment]
I understand, I'll forward this to the colorscheme I'm using. On a closer look thou, I think this might also be the lsp's problem, since the enum isn't even part of the default library.
