### ISSUE TITLE
Windows: ~ symbol not treated as home when starting from CLI/terminal

### ISSUE THREAD

**Issue by devindang** [neovim/neovim#23901]
### Problem

any path including "~" cannot be operated correctly.
```sh
nvim ~/.vimrc
```
This doesn't work, and it will create a new file.
```sh
cd ~
nvim .vimrc
```
This get worked.

### Steps to reproduce

just install neovim
and execute `nvim ~/.vimrc`

### Expected behavior

It should edit the `.vimrc` file instead of creating a new one.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

no, vim 9.0

### Operating system/version

Windows 11

### Terminal name/version

windows terminal 1.16.10262

### $TERM environment variable

powershell

### Installation

scoop

**Comment by lewis6991** [comment]
Your shell should be expanding `~`, I don't think neovim should expand internally.

**Comment by devindang** [comment]
> Your shell should be expanding `~`, I don't think neovim should expand internally.

Is that expanded by the shell? But vim could process with it.

**Comment by lewis6991** [comment]
I'm pretty sure neovim should process the argument names verbatim on the command line.

**Comment by devindang** [comment]
> I'm pretty sure neovim should process the argument names verbatim on the command line.

Yes, it didn't happen on WSL.

**Comment by justinmk** [comment]
vim special-cases this on Windows. That was removed in Nvim. You can force the special-casing by using the `:next` command: 

    nvim +"n ~/.vimrc"

**Comment by devindang** [comment]
> vim special-cases this on Windows. That was removed in Nvim. You can force the special-casing by using the `:next` command:
> 
> ```
> nvim +"n ~/.vimrc"
> ```

Yes, it does get worked, but if nvim could treat this special case in windows, it will be better :)

**Comment by justinmk** [comment]
Does any other tool work like that on Windows?

**Comment by pjschinske** [comment]
> Does any other tool work like that on Windows?

Powershell supports tilde expansion for built-in commands, and for native applications if you enable an experimental feature. But third party applications presumably have to implement it on their own.
See https://github.com/orgs/PowerShell/discussions/15263

**Comment by devindang** [comment]
> Does any other tool work like that on Windows?

I didn't find yet. A similar situation occurs with wildcard symbol * in powershell :)

**Comment by daviewales** [comment]
In PowerShell <= 7.3, the problem of tilde expansion is somewhat mitigated by tab expansion which automatically replaces the tilde with the absolute path to your home directory when you press Tab.

```
nvim ~/Des<TAB> -->
nvim C:\Users\example\Desktop\
```

In PowerShell Core (7.4 in my case), Tab expansion autocompletes directories, but retains the tilde, and passes it unchanged in arguments.

```
nvim ~/Des<TAB> -->
nvim ~\Desktop\
```

See related PowerShell issue: https://github.com/PowerShell/PowerShell/issues/20750.

There is an [experimental feature](https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.4#psnativewindowstildeexpansion) in the pre-release version of PowerShell 7.5 which performs ~ expansion at the shell level if enabled, but it's not enabled by default, and 7.5 is not yet released.

It would be nice for Neovim to special-case ~ expansion on Windows at least until ~ expansion lands as a default feature in PowerShell.

**Comment by justinmk** [comment]
Thanks for that info. If powershell is gaining this feature then we definitely don't need to special case it.

**Comment by jadczak** [comment]
> Does any other tool work like that on Windows?

For what it's worth (and apologies for being late to the party)

sublime handles the tilde expansion.
So I can type the following to open my init.lua in powershell 7.4.2
`subl ~/AppData/Local/nvim/init.lua`

However python does not handle the tilde expansion, so trying to run the following:
`python ~/foo.py` 
will result in `No such file or directory` as python will interpret this as a relative path.

And the direction of the slash (`\` vs `/`) doesn't impact the results.  I guess powershell already manages that.

**Comment by justinmk** [comment]
> And the direction of the slash (`\` vs `/`) doesn't impact the results.

It matters almost nowhere, except in a few specific, old console (cmd.exe) commands.

**Comment by rkitover** [comment]
I started working on a [PR](https://github.com/neovim/neovim/pull/28515) for this.

I will put my notes from it here as well.

PowerShell on Windows recently removed the feature where arguments such as `~/.ssh/config` or `~/.vimrc` are expanded to `${env:USERPROFILE}/.ssh/config` etc..

What this means is, in PowerShell, when you run a command such as:

```powershell
nvim ~/.ssh/config
```
, what happens is that nvim tries to open `${PWD}/~/.ssh/config` because that looks like a relative path to a literal `~` directory to it.

In these cases the user is very unlikely to want to open a file in literal `~` relative directory. It's a huge annoyance for me in PowerShell because I run these commands frequently and now I have to run a command such as:

```powershell
nvim (gi ~/.ssh/config)
```
, instead to get the file I want.

There used to be an experimental feature for this in `get-experimentalfeature` that you could enable, I don't remember which exactly, but it has been removed.

In the unreleased development version of PowerShell, which may not be released for quite a while yet, there is an experimental feature for this, `PSNativeWindowsTildeExpansion`, see [here](https://github.com/PowerShell/PowerShell/blob/master/experimental-feature-windows.json).

I believe it would be better if we address this in neovim, because this PowerShell experimental feature will not be available for a while yet, and when it is it would require enabling it, and if this is done in neovim it would also work in WinPS (`powershell.exe`) and `cmd.exe`.

I should also mention that the PowerShell completion behavior for tilde paths has also recently changed. Before, when you would type:

```powershell
nvim ~/.ssh/config<TAB>
```
, it would expand to the absolute path, but PowerShell no longer expands tilde paths to absolute paths, it expands them to canonical tilde paths, leading to the behavior in neovim that I described.

I tried to do this in `os_open()` in `os/fs.c` first, but it is too late to do it there because `fix_fname()` has already converted the path to an absolute path to a relative `~` directory, this is why I put it there.

**Comment by T-727** [comment]
Note that as of 2 days ago `~` is expanded to native commands and is considered for backport to the current release  https://github.com/PowerShell/PowerShell/pull/21529
