### ISSUE TITLE
v:argv doesn't use the actual argv nvim was started with

### ISSUE THREAD

**Issue by ii14** [neovim/neovim#23953]
### Problem

Since TUI was moved to another process, the TUI process is spawned with `["/usr/bin/nvim", "--embed", ...]`.
`v:argv` and `v:progname` now always report that, instead of how nvim was actually started.

### Steps to reproduce

Create a symlink to change `argv[0]`:
```
ln -s `which nvim` foo
./foo
```
`:echo v:progname` says `nvim`

### Expected behavior

`:echo v:progname` should say `foo`

### Neovim version (nvim -v)

0.10.0 commit f959753e5

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ubuntu

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

ppa

**Comment by ii14** [comment]
Sorry, yes, `v:progpath` should always point to the actual executable.

**Comment by t0muxx** [comment]
I will try to fix that

**Comment by t0muxx** [comment]
I found that the commit 24488169564c39a506c235bf6a33b8e23a8cb528 changed the behavior of `v:argv`.
Before that commit when running neovim from a symlink `./foo` : 
- `echo v:argv` would print `./foo`.

After that commit, the value of `v:argv` would contains the symlink target path (eg  : `['/tmp/neovim/build/bin/nvim', '--embed']`)

It is due to the fact that the function `ui_client_start_server` sets `argv[0]` to the value of `VV_PROGPATH`.
`VV_PROGPATH` contains the value of the target of the symlink (eg : instead of `./foo`, it will contains `/tmp/neovim/build/bin/nvim`).

```C
uint64_t ui_client_start_server(int argc, char **argv)
{
...
  args[args_idx++] = xstrdup((const char *)get_vim_var_str(VV_PROGPATH)); // Contains symlink target path
  args[args_idx++] = xstrdup("--embed");
  for (int i = 1; i < argc; i++) {
    args[args_idx++] = xstrdup(argv[i]);
  }

  Channel *channel = channel_job_start(args, CALLBACK_READER_INIT,
                                       CALLBACK_READER_INIT, CALLBACK_NONE,
                                       false, true, true, false, kChannelStdinPipe,
                                       NULL, 0, 0, NULL, &exit_status);

```

I'm not sure what should be the behavior here ?  It should be easy to change `ui_client_start_server(int argc, char **argv)` that way to give correct argv[0] to ui process : 
```C

uint64_t ui_client_start_server(int argc, char **argv)
{
...
  args[args_idx++] = xstrdup((const char *)argv[0])); // Contains `./foo`
...
```

But for the `progpath` value, it seems that this variable has never worked the way expected in the issue.
I tried to compile `release-0.5` (older release did not compile on my laptop)  and `progpath` contained the target symlink path : 
- `echo v:progpath` -> `/tmp/neovim/build/bin/nvim`

This is because `VV_PROPATH` is set using `os_exepath` which is using `uv_exepath` from `libuv` that seems to follow the symlink. This should not be really hard to fix but I don't know if this the wanted behavior ?

I would appreciate some helps here.

Thanks

**Comment by zeertzjq** [comment]
There is no issue with `v:progpath`

**Comment by ii14** [comment]
Using progpath to spawn the server process is fine. argv from the UI process have to be somehow sent to the server

**Comment by t0muxx** [comment]
ok, what would be the best way to send `argv` from the UI to the server ? is it with `rpc_send_event` ?

**Comment by ii14** [comment]
@t0muxx I think the best solution is to add a command line option that changes `argv[0]` and removes itself from `argv` when spawning the server. For example if you start with `nvim --embed-argv0 ./foo arg1 arg2`, `v:argv` should report `./foo arg1 arg2` + do what `--embed` does.

**Comment by justinmk** [comment]
> I think the best solution is to add a command line option that changes `argv[0]` and removes itself from `argv` when spawning the server. For example if you start with `nvim --embed-argv0 ./foo `

Why do we need a new command line option? Can't the parent process call the child with the same arg0? Then the child only needs to remove `--embed` etc.

**Comment by ii14** [comment]
@justinmk Sure, that should work too. I assume then `--embed` would have to be unconditionally always removed from `v:argv`?

**Comment by justinmk** [comment]
> I assume then `--embed` would have to be unconditionally always removed from `v:argv`?

The UI child knows it's a UI child, right? So let's start with that and see if it's good enough.
