### ISSUE TITLE
#23801 breaks slimv

### ISSUE THREAD

**Issue by remexre** [neovim/neovim#24003]
### Problem

It appears that the semantics of plugin loading changed with #23801 -- it looks like before, it'd go thru each directory in rtp, and load each file matching any of the globs. After #23801, it goes one by one thru the globs, then thru each directory, and loads them.

Neovim ships `ftplugin/lisp.vim`, which does the standard

```viml
if exists("b:did_ftplugin")
  finish
endif
let b:did_ftplugin = 1
```

dance. [slimv](https://github.com/kovisoft/slimv/) ships its files as `ftplugin/lisp/*.vim`, and also does the same thing.

Previously, since slimv would be earlier in the rtp search order, it would "win the race" and be loaded. Now, the anemic lisp.vim does instead.

Reverting #23801 fixes this symptom.

### Steps to reproduce

Install slimv, open a Lisp file, type `,c`, note how nothing happens.

### Expected behavior

slimv should be loaded before Neovim's lisp.vim, and should work

### Neovim version (nvim -v)

v0.10.0-dev commit a7e5d4238a00d5bfa5809b2860047eca2d565e62

### Vim (not Nvim) behaves the same?

no

### Operating system/version

NixOS 23.05

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

tmux-256color

### Installation

Git or nixpkgs, tried both

**Comment by clason** [comment]
> After https://github.com/neovim/neovim/pull/23801, it goes one by one thru the globs, then thru each directory, and loads them.

That is the intended and documented order, yes. This issue is a very specific case, where the plugin uses a different location `ftplugin/lisp/slimv-lisp.vim` as the bundled `ftplugin/lisp.vim`. I'm not sure we can satisfy this at the same as the also intended and documented order "vim before lua, in each directory". (Note that the change in this PR fixed the latter behavior.)

I'm afraid this will have to wait until the blocker for https://github.com/neovim/neovim/pull/23202 is addressed.

**Comment by clason** [comment]
@remexre can you test #24147?
