### ISSUE TITLE
vim.iter: consistent callback signature for list-like and dict-like inputs

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#24141]
## Problem

For callbacks of functions like `Iter:fold()`, the callback signature has a different arity for array-like vs dict-like inputs: https://github.com/neovim/neovim/blob/3688735c2b63337ab8d8b12ac08b4e6e064e98a2/test/functional/lua/iter_spec.lua#L349-L370

array-like:

    vim.iter(t):fold({}, function(acc, v) ...

dict-like:

    vim.iter(t):fold({}, function(acc, k, v) ...

## Expected behavior

For all `vim.iter` callbacks, use the same signature for list-like and dict-like inputs.  In the array-like case, pass the index as the "key" arg.

E.g. for `fold()`:

    vim.iter(t):fold({}, function(acc, k, v) ...

## Benefits:

- increases composability (same callbacks can be used for both list-like and dict-like inputs)
- reduces verbosity in the documentation, avoids redundant examples for list-like and dict-like inputs.
- aligns with analogous libraries such as [lodash](https://lodash.com/)

cc @gpanders

**Comment by gpanders** [comment]
> For callbacks of functions like Iter:fold(), the callback signature has a different arity for array-like vs dict-like inputs

This was an intentional design choice as the input to each pipeline stage contains all of the outputs from the previous stage. This is true of all of the `Iter` methods. For list like tables, the “outputs” are just the values, so “downstream” stages get only the value, not the index. Consider how often one writes `for _, v in ipairs(t)`. Iterating over just the values is common. 

To include the index we have `enumerate()`, which is general purpose as it also includes an index even for non-list tables (e.g. function iterators or “dict-like” tables).

We can revisit the decision to not include the index for list like tables, though I have a preference for the status quo. If I’m iterating over a “list”, I don’t want to have to add the dummy/throwaway argument for the index every time. If I *do* want the index I can make that explicit with `enumerate()`.

Happy to hear other opinions. I won’t die on this hill.

**Comment by justinmk** [comment]
> If I’m iterating over a “list”, I don’t want to have to add the dummy/throwaway argument for the index every time

Makes sense. The tradeoff is 

-  the docs for each of these must explain the different callback signatures,
- users must also be vigilant about this difference
- if I change the input of a "pipeline" that I'm playing with, I have to change all the signatures.

Avoiding all of that seems like a very big win, no? But "dummy index" doesn't bother me at all, so I'm biased.

**Comment by gpanders** [comment]
>users must be ever-vigilant about this difference. could be a common source of mistakes/confusion

Personally I suspect the current approach is _less_ confusing. If you express the concept of "iterate through a list of things" in most functional languages, you end up with a lambda with a single argument representing the "thing" being iterated on. `vim.iter({1, 2, 3}):map(function(x) ... end)` matches that expectation. If we include the index by default then that code doesn't work, because now `x` is not the "thing" being iterated, but the index. Likely an easy bug to identify and correct, but I suspect people would trip over that. (Counterpoint is that people familiar with Lua may already be used to the `i, v` pattern from `ipairs()`, so maybe this isn't an issue).

Another point: sequential tables in Lua are created without explicitly specifying the key, e.g. `{"a", "b", "c"}`. Using only the value in iterator pipelines mirrors that ("I only care about the value, the index is an implementation detail").

I do agree that not having to handle different input types specially would be nice, although we already handle list-like tables specially anyway for performance reasons. And it is true that in Lua "arrays" are just tables, so it does make some sense to treat them the same. However, I think that "leaks" the Lua implementation details through to the iterator interface a bit (maybe not a big deal).

Maybe we can look into what such a code change would look like. If it simplifies other things or eliminates edge cases, then great, it's probably worth it! If it's a wash complexity-wise then it comes down to preference and I'd be in favor of leaving it as-is.

**Comment by justinmk** [comment]
> And it is true that in Lua "arrays" are just tables, so it does make some sense to treat them the same. However, I think that "leaks" the Lua implementation details

True. Though if this "leak" is idiomatic in Lua then hiding it may be confusing in its own way.

Does the current approach defeat some "composability"? Lua's list/dict table "fungibility" seems analogous to sequences in lisp, so one can stream tables to various handlers and pipelines. Requiring different signatures makes that harder.

**Comment by justinmk** [comment]
> > And it is true that in Lua "arrays" are just tables, so it does make some sense to treat them the same. However, I think that "leaks" the Lua implementation details
> 
> True. Though if this "leak" is idiomatic in Lua then hiding it may be confusing in its own way.

It's not a leak, it's an intentional interface design choice, per [The Implementation of Lua 5.0](https://www.lua.org/doc/jucs05.pdf).
