### ISSUE TITLE
default mappings for LSP, diagnostics, etc

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#24252]
# Problem

LSP and diagnostics don't have core mappings. In the case of LSP some of its natural mappings "conflict" with ftplugins or the builtin normal commands.

Related:

- https://github.com/neovim/neovim/pull/24331
- https://github.com/neovim/neovim/pull/16230
- https://github.com/neovim/neovim/pull/28500
- https://github.com/neovim/neovim/pull/26745
- https://github.com/neovim/neovim/issues/24054
    - https://github.com/neovim/neovim/pull/18506

# Expected behavior

We could introduce a way to _opt-in_ to more aggressive, more risky defaults (essentially the antithesis of https://github.com/neovim/neovim/issues/6293 , which proposed a way to enable "nineties mode" for slow devices/networks). But that kind of sucks, it's not really a long-term solution, it creates an "inner platform" that then gets its own inertia and baggage.

Instead:

- ✅ revisit [#16230](https://github.com/neovim/neovim/pull/16230) (was there objection to `]g` and friends? potentially better alternatives, borrowing from vim-unimpaired, vim-scriptease, something else?)
    - ✅ we can probably claim `]d` and friends, the default behavior is rarely useful.
- ✅ resolve https://github.com/neovim/neovim/issues/24252#issuecomment-1620459930
- finish [#18506](https://github.com/neovim/neovim/pull/18506) to deliver the full `vim.lsp.config` interface
- ~~add `vim.lsp.buf.set_defaults({buf})`, which sets recommended default mappings and other settings.~~

## LSP defaults

The defaults should answer these questions:

> - What about all the lsp functions that one can call?
> - What do I need to do to trigger auto-formatting?
> - ✅ Does gd call the LSP by default when one is attached?
>   - ✅ What about K?
> - ✅ How do I run code actions?
> - ✅ What if I want to see the documentation of the completion entry while I browse them?
> - ✅ What if I need the entries to show more than just plain white text without context?
> - ✅ Inlay hints are cool but do I really need a custom on_attach function to enable them globally?

**Comment by YodaEmbedding** [comment]
I'll start things off with a small selection from my [personal LSP mappings](https://github.com/YodaEmbedding/dotfiles/blob/master/nvim/.config/nvim/lua/mappings/_nvim_lsp.lua):

```lua
nnoremap("gd", vim.lsp.buf.definition)
nnoremap("gr", vim.lsp.buf.references)
nnoremap("K",  nvim.lsp.buf.hover)
```

**Comment by mfussenegger** [comment]
Note that `vim.diagnostic` is separate from `vim.lsp` and `vim.lsp` is just _one_ of many possible diagnostic providers. Anything part of `vim.lsp` should imho _not_ set up default mappings for `vim.diagnostic`.


---

> nnoremap("gd", vim.lsp.buf.definition)


We already set `tagfunc` by default, which has default keymaps and is more powerful (e.g. it works properly for multiple clients as it can merge results). I'm not even sure why we have a `vim.lsp.buf.definition` in addition

---

I think `K` for hover and `gr` for references are the least controversial.
For `K` we could also use a similar approach like we do with formatexpr, tagfunc or omnifunc and check if `keywordprg` is already set to a non-default value, and if not, override it. One reason we didn't do that yet was because it doesn't support lua function refs and we were deferring this, to see if it will be supported with the ongoing options refactoring. (Otherwise we'd have to add some kind of `:lsp hover` command)


For others like `code_action` there seem to be a lot of different choices.

**Comment by VonHeikemen** [comment]
What about the `F` keys? They could be useful.

* `<F2>` -> vim.lsp.buf.rename()
* `<F3>` -> vim.lsp.buf.format({async = true})
* `<F4>` -> vim.lsp.buf.code_action()

Other functions that don't have a default behavior could be behind a prefix. Something like `gl` or maybe `<LocalLeader>`.

* `gld` -> vim.lsp.buf.declaration()
* `gls` -> vim.lsp.buf.signature_help()
* `gli` -> vim.lsp.buf.implementation()
* `glt` -> vim.lsp.buf.type_definition()

**Comment by justinmk** [comment]
`<Fx>` keys are absolutely out of the question. 

This issue is not an invitation for drive-by half-baked suggestions.

**Comment by gpanders** [comment]
I actually am not in favor of automatically mapping `K` to hover. I rely on `'keywordprg'` in C and C++ quite a bit, so I prefer to keep `K` for man pages use a separate mapping for hover. `'keywordprg'` and LSP's hover are not interchangeable in many (maybe most?) cases, so I don't think automatically remapping `K` is an obvious choice.

>I think K for hover and gr for references are the least controversial.

I don't personally use the default `gr` behavior, but I think we should avoid overriding any builtin keys. That is also why I prefer using `g` as the diagnostics key (e.g. `]g, `[g`, etc.) instead of `]d` and `[d`. The builtin `[d` and `]d` may not be very popular or useful for many people, but if we are talking about default mappings then I think we should have a very high bar for what behavior we are overriding. And if even a small subset of people use `[d` and friends, we should not clobber it.

(The exception is if the new default mapping "improves" on the builtin behavior, e.g. the default mappings for `Y`, `<C-L>`, etc. make sense to me).

For references, I personally use `[R`, which mirrors the builtin `[I` and `[D` and I think has a similar principle (`[I` finds references to the keyword in include files, `[D` finds references from `#defines`, `[R` finds references from LSP).

**Comment by justinmk** [comment]
> There are a few popular choices like `<leader>ca` for code actions,

`cr` is a great prefix for code actions/fixes/refactors. E.g. `crn` for "rename".

> but if we are talking about default mappings then I think we should have a very high bar for what behavior we are overriding.

The escape hatch is that we make it opt-in or opt-out (via some sort of `...set_defaults()` thing). That allows us to avoid getting bogged down. Builtin `gr` is useless, it should be an LSP default mapping. I also think `]d` is available, it doesn't matter that some people use it for its current over-specific purpose.

> For references, I personally use `[R`,

I have found in practice that uppercase mappings are hard to use and hard to remember.

**Comment by gpanders** [comment]
>cr is a great prefix for code actions/fixes/refactors. E.g. crn for "rename".

Agreed, though we should be careful not to clobber anything from [vim-abolish](https://github.com/tpope/vim-abolish#coercion).

**Comment by mfussenegger** [comment]
> I rely on 'keywordprg' in C and C++ quite a bit, so I prefer to keep K for man pages use a separate mapping for hover. 'keywordprg' and LSP's hover are not interchangeable in many (maybe most?) cases, so I don't think automatically remapping K is an obvious choice.

If `keywordprg` is customized or `K` is already mapped, it won't add the mapping to hover. 
I think for most languages, having `K` open a man page is not useful and C/C++ are the exception. So the assumption is that having `K` map to `hover()` is the more sensible thing (at least looking at languages where it is useful vs. not, and not at the % of people writing those languages with neovim)

But maybe we move the discussion specific to K/keywordprg to the PR. I don't really have a strong opinion on it, so I don't mind either way.

> The escape hatch is that we make it opt-in or opt-out (via some sort of ...set_defaults() thing)

Would this affect the tagfunc/formatexpr/omnifunc behavior or would we have two kinds of defaults?

**Comment by justinmk** [comment]
> > The escape hatch is that we make it opt-in or opt-out (via some sort of ...set_defaults() thing)
> 
> Would this affect the tagfunc/formatexpr/omnifunc behavior or would we have two kinds of defaults?

All-or-nothing is easier to explain and maintain. Don't see a need for two kinds of defaults.

**Comment by rasulomaroff** [comment]
Hi everyone! I just tested nightly to check how new default mappings work and would like to ask some questions about them:

We now have `crn` and `crr` mappings that collide with the vim's default `c` operator and now when I press `c`, I'm not instantly in the operator-pending mode. Just my opinion: I believe when you press a key that's related to any of default operators, mode switch should be instant.

If I want to avoid this behaviour, do I have to remove `crn` and `crr` mappings in the `LspAttach` event? Has this colliding been considered? Maybe it's just not that important in terms of default api, I just wanna know :)

**Comment by justinmk** [comment]
> We now have `crn` and `crr` mappings that collide with the vim's default `c` operator and now when I press `c`, I'm not instantly in the operator-pending mode

"Instantly in operator pending mode" is a new one, haven't heard that before. By that logic, the `ys` mapping from vim-surround also would interfere, despite having no overlap with any builtin key sequence.

Why does it matter if "c" enters operator-pending mode immediately? What is the use-case?

**Comment by rasulomaroff** [comment]
Yes, you're right, it interferes with the `y` operator and this is the reason I remapped it to be `<leader>sa` for adding, `<leader>sd` for deleting etc

The use-cases are plugins that track the operator-pending mode to do something. For example, my plugin `reactive.nvim` tracks mode changes to apply window or global highlights when mode changes occur. `modes.nvim` works the same way I guess.

Even if you don't use plugins for that, I think it's a very popular situation where you want to highlight a current line (or a statusline? like in `lualine`) depending on the mode you're in, right? A lot of people and plugin developers just use `ModeChanged` event to do that. Right now in nvim 0.9.5 it will work instantly, if you check `vim.v.operator` to be equal `c` in `ModeChanged` event, but in nightly you have to wait for `vim.opt.timeout` ms after pressing `c` to actually see any changes on the screen.

And I don't know how many beginners actually pay attention to the `modemsg` message that tells you which mode you're in, but I remember myself as a beginner in neovim and I used that thing as an indicator constantly. Seeing immediate feedback after pressing any of default operators was convenient.

Yes, it still works and highlights after the timeout, but it's kind of inconsistent with other default operators. I don't know how crucial this is, but I'm just raising it up so that you know :)

**Comment by justinmk** [comment]
> I really don't like it when mappings collide with operators.

Open a separate issue for this. It's mostly a limitation of the current mappings behavior, and isn't something that inherently makes use choose between having a default `cr` mapping or not. I have some ideas, but will save them for the separate issue.

**Comment by justinmk** [comment]
## Status/Resolution/Summary

Resolved by:
- https://github.com/neovim/neovim/pull/28500
- https://github.com/neovim/neovim/pull/16230

Remaining, potential work is tracked in:
- https://github.com/neovim/neovim/issues/28479
- https://github.com/neovim/neovim/issues/24054

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open an issue if you have new information/topics to discuss._
