### ISSUE TITLE
Inlay hints not working if a file does not have a newline at end of file

### ISSUE THREAD

**Issue by lostl1ght** [neovim/neovim#24339]
### Problem

If a file does not have a newline at end of file then inlay hints are not working and rust-analyzer sends an error
message: `rust-analyzer: -32603: Invalid offset`

### Steps to reproduce using "nvim -u minimal_init.lua"

<details>

<summary>Minimal configuration</summary>

```lua
local pattern = 'rust'
local cmd = {'rust-analyzer'}
local root_markers = {'.git', '.editorconfig', 'Cargo.toml'}
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'rust-analyzer',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})

vim.api.nvim_create_autocmd('LspAttach', {
    group = vim.api.nvim_create_augroup('InlayHintsAttach', {}),
    callback = function(args)
      local buf = args.buf
      vim.lsp.inlay_hint(buf, true)
    end,
})
```

</details>

1. Create an executable crate: `cargo new hints`
2. Write some code that should display inlay hints, e.g. `let x = 12;`
3. Delete the newline somehow, I did that using `vscode`
4. Open `main.rs`
5. Observe an error and no inlay hints

### Expected behavior

Working inlay hints and no error message.

### Neovim version (nvim -v)

v0.10.0-dev-664+g0ce391086

### Language server name/version

rust-analyzer 0.3.1583-standalone (2023-07-10)

### Operating system/version

Windows 11, WSL2

### Log file

No log messages produced

**Comment by TinusgragLin** [comment]
This problem seems to be specific to `rust-analyzer`, `clangd` and `gopls` are working just fine after deleting the `0x0A` at the end of a file.

**Comment by ifyuhj** [comment]
When I deleted the entire content of the rs file using `ggdG`, I encountered the same error, possibly due to the same reason.

**Comment by TinusgragLin** [comment]
I believe the problem is caused by:
1. `neovim` uses `(line_count, 0)` to indicate the end of a file when requesting inlay hints.
2. The `line-index` crate in `rust-analyzer` project, which is used to converting between `(line, col)` pairs and text sizes (from the start) for a file, counts lines by only searching for `\n`, resulting in not counting the last line if a file does not end with `\n`. This is actually fine if you assume that `(line, col)` pairs passed in is in the range `(0, 0) ~ (line_count - 1, last_line_length - 1)`.

`vscode` uses `(line_count - 1, last_line_length - 1)` to indicate the end of a file, and thus does not have this problem.

Some other lsp servers seems to handle `(line_count, 0)`  correctly. I checked `gopls` and it actually checks for this specific case when converting `(line, pos)`s to text sizes.

**Comment by glepnir** [comment]
@ifyuhj could you try this patch 

```diff
diff --git a/runtime/lua/vim/lsp/util.lua b/runtime/lua/vim/lsp/util.lua
index 738e23ff2..73bd33f74 100644
--- a/runtime/lua/vim/lsp/util.lua
+++ b/runtime/lua/vim/lsp/util.lua
@@ -2211,18 +2211,19 @@ function M._refresh(method, opts)
         textDocument = M.make_text_document_params(bufnr),
         range = {
           start = { line = first - 1, character = 0 },
-          ['end'] = { line = last, character = 0 },
+          ['end'] = { line = last - 1 <= 0 and 0 or last, character = 0 },
         },
       }
       vim.lsp.buf_request(bufnr, method, params)
     end
   end
   if not only_visible then
+    local count = api.nvim_buf_line_count(bufnr)
     local params = {
       textDocument = M.make_text_document_params(bufnr),
       range = {
         start = { line = 0, character = 0 },
-        ['end'] = { line = api.nvim_buf_line_count(bufnr), character = 0 },
+        ['end'] = { line = count - 1 <= 0 and 0 or count, character = 0 },
       },
     }
     vim.lsp.buf_request(bufnr, method, params)
```

**Comment by TGlide** [comment]
This still happens to me in svelte files
