### ISSUE TITLE
E518: Unknown option: term=$TERM

### ISSUE THREAD

**Issue by athaeryn** [neovim/neovim#2435]
I've got `set term=$TERM` in my `.nvimrc`. When starting neovim, it throws the error:
```
Error detected while processing /Users/mike/.nvimrc:
line   23:
E518: Unknown option: term=$TERM
```

. I'm a bit confused, as the `h 'term'` lists:
```
	For example: 
		:set term=$TERM
```

**Comment by splinterofchaos** [comment]
I believe we no longer support `term`. Please use `cterm` instead. However, I'm hesitant to close this issue because (1) the docs need updating, and (2) should we silently ignore `term` or suggest that users use `cterm` instead? Ignoring it might provoke people to make bug reports like "term not respected". 

Are there reasonable circumstances where someone will not have access to a color terminal?

**Comment by ZyX-I** [comment]
@athaeryn What’s the point in doing `set term=$TERM`? This is the default.

**Comment by splinterofchaos** [comment]
Ignore my comment, I got confused by `:help term` when I should have read `:help 'term'`.

**Comment by splinterofchaos** [comment]
Weird, `:echo &term` outputs `nvim` (so `$TERM` is not the default and the docs still need updating), but `:set term=anything` indeed produces this error.

**Comment by athaeryn** [comment]
@ZyX-I It's quite possibly something I thought I needed a while back, but I don't need it anymore (and possibly didn't ever). I can probably remove it.

**Comment by justinmk** [comment]
`&term` is still returned for backward compatibility, but setting it is an error because it serves no purpose in Neovim.

**Comment by Pyrohh** [comment]
@splinterofchaos coincidentally, I'm updating the docs right now. I think it also make sense to bring back the removed options as no-ops, as the state of things having no-ops is inconsistent.

**Comment by justinmk** [comment]
>  I think it also make sense to bring back the removed options as no-ops, as the state of things having no-ops is inconsistent.

Where is it inconsistent? We make it an error in cases where our behavior would not match the behavior expected by the act of setting the option. E.g., 

- `set cp` is an error because the no-op behavior would be totally broken.
- same with `set edcompatible`
- For `set term=xterm` it depends on what is actually looking at `&term`. `set term=$TERM` is *not* a valid argument in favor of making `set term` a no-op :P

**Comment by Pyrohh** [comment]
> Where is it inconsistent?

I was going to list them off, but I got lazy :grin:. Anyways, here's what I've noticed:
- ttyscroll
- weirdinvert
- cryptmethod
- key
- :shell
- ttymouse does nothing at all, regardless of what it's set to (not sure if we should warn about this).

> For set term=xterm it depends on what is actually looking at &term. set term=$TERM is not a valid argument in favor of making set term a no-op :P

Oops, I didn't mean to imply that, in fact I haven't really thought much if it should be a no-op.

**Comment by justinmk** [comment]
@Pyrohh ttymouse and ttyscroll could be debatable, but the others should be errors.

**Comment by Pyrohh** [comment]
@justinmk It seems I used the wrong word (no-op), which I now realize totally changed the intended meaning. What I mean is that I think that those mentioned options could have an e_unsupported trait, instead of just being unknown.

**Comment by eric-saintetienne** [comment]
> `term=$TERM`? This

The point is to override the TERM variable. So we could have some value for bash (say xterm-256color) and a different value for neovim (say screen-256 which can handles HOME and END keys)
