### ISSUE TITLE
Behavior of `*`

### ISSUE THREAD

**Issue by raichoo** [neovim/neovim#2436]
Hi,

I've been thinking about this for quite a while now and thought "what the heck, let's see what people think".
`*` always kind of bothered me because it essentially does 2 things at once, it highlights the word under the cursor and jumps to the next occurrence. I don't consider that to be really composable in fact I've seen a lot of people, including myself, mapping `*` to `*N` to just highlight the word under the cursor. With `*` just doing the highlighting one would have a single building block to build up the original operations for `*` and `#` just by mapping them to `*n` and `*N`.
I understand that this is highly controversial but since the `neovim` community seems to have a very vibrant and constructive discussion culture I was wondering if that was actually a sensible idea. I don't know, maybe I'm missing something quite obvious here ^^.

Kind regards,
raichoo

**Comment by weaksauce** [comment]
I don't think that ```*``` highlights anything unless I am mistaken about your definition of highlights. perhaps you have a mapping that highlights when you press ```*```? 

Anyway, the search feature of ```*``` and ```#``` are one of the most widely used search shortcuts imo. This would be a bad addition to something that aims to be vim "out of the box" so to speak because it would break a long standing convention and be less usable out of the box. 

perhaps you want to highlight the keyword under the cursor in which case you can map it ```*``` to ```viw``` or ```*N``` I suppose. 

perhaps I am misunderstanding what you are proposing.

**Comment by raichoo** [comment]
Ah yeah, let me clarify. I also use `hlsearch`. Thinking about that this would require `hlsearch` to be on by default which is not desirable…

**Comment by liujoey** [comment]
```
    NeoBundle 'junegunn/vim-oblique' "{{{
      let g:oblique#incsearch_highlight_all = 1
    "}}}
```
