### ISSUE TITLE
Unexpected behavior when using `k` and `j` with count

### ISSUE THREAD

**Issue by thinety** [neovim/neovim#24382]
### Problem

Moving the cursor up or down with `<count>k` and `<count>j` behaves differently than with just `k` and `j`. If `count` is big enough, the cursor jumps to the middle of the screen, instead of staying at the borders of the window (respecting `scrolloff`).

### Steps to reproduce

- `nvim --clean`
- Create a file with many lines
- Go to end of file and move cursor up with `50k` for example (50 is just a big number, greater than the window height)
- Cursor jumps to middle of screen instead of staying on top

The same happens with `j` when moving down.

### Expected behavior

Expected `50k` to behave exactly the same as pressing `k` 50 times, but it does not: the latter stays at the top of the window (while also respecting configuration like `scrolloff`), while the former jumps to the middle of the screen. Analogously for `j`.

The behavior for `k` is caused by these lines:
https://github.com/neovim/neovim/blob/80cf0f3d29fa337d43ec417759cb061bd2798ea8/src/nvim/move.c#L317-L325
I have built neovim running the else block unconditionally and can confirm that it solves the problem.

For `j` the logic is a bit more elaborate, I am only sure that it involves code around `scroll_cursor_halfway` in that same file.

Is this behavior expected?

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

Yes, vim 9.0.1676 ([issue](https://github.com/vim/vim/issues/12675))

### Operating system/version

Arch Linux

### Terminal name/version

Alacritty 0.12.2

### $TERM environment variable

alacritty

### Installation

Arch official repositories

**Comment by kwabrahamson** [comment]
I just tried this same scenario with vim --clean and got the same behavior when moving the cursor up or down using `<count>k` and `<count>j` where `<count>` is greater than or equal to half of the screen height.

When repeatedly pressing `k` and `j` to move the cursor the behavior in vim differed from nvim. In vim when repeatedly pressing `k` in the middle of a long file the cursor only moves to the 6th line from the top of the screen before the text starts to scroll. In nvim the cursor will move all the way to the top of the screen before the text starts to scroll. Similar behavior happens when pressing `j` to move the cursor down the file.

This leads me to this question - when fixing issues do we want consistency with vim?

**Comment by zeertzjq** [comment]
It should be `vim --clean --cmd 'set scrolloff=0'`

**Comment by kwabrahamson** [comment]
Thanks! I now see the behavior is consistent between nvim and vim.

This leads me back to the original issue. Do we proceed with this request if the request makes the behavior of nvim inconsistent with vim?

**Comment by zeertzjq** [comment]
Let's close this.
