### ISSUE TITLE
meta/alt chords, function keys, shift-tab broken in :terminal buffers

### ISSUE THREAD

**Issue by ajpaulson** [neovim/neovim#2440]
If I open a terminal buffer `:terminal` and attempt to use `Alt .` (to insert the last argument of the previous command) I get a unicode character instead (infact `Alt` with any key inserts a unicode character - thereby breaking many readline shortcuts that have become muscle memory)

`Ctrl` based readline chords work as expected.

OS: Debian Jessie
Nvim version: 0.0.0-alpha+201504141749 (compiled from `HEAD` on April 15th `a86193d` )
After checking - this has been the case since the introduction of `:terminal` buffers.

**Comment by justinmk** [comment]
Yeah, I miss `M-.` too.

**Comment by ajpaulson** [comment]
I've noticed that building the current head ( 98053f0 ) `M-.` now inserts the last argument of the previous command but does so *before* the last word you just typed:

e.g:

    $ ls -l
    <M-.>
    $ ls /var/www-l

Is this coming from libterm or is it the integration into neovim?

**Comment by ajpaulson** [comment]
*Update* the previous behaviour (inserting unicode chars) has returned

**Comment by ajpaulson** [comment]
Is there some configuration value similar to Xterm's "metaSendsEscape"?

**Comment by justinmk** [comment]
No. I'd rather not make it configurable, let's focus on fixing the problems.

**Comment by ZyX-I** [comment]
@justinmk Most of terminal emulators allow configuring the escape sequences send when pressing certain key combinations. I do not think that they have such configuration options because their authors had nothing to do, so making this configurable most likely *is* fixing the problems.

Also do not forget about variants of escape sequences: fixterms and a number of legacy dialects, mainly xterm-based. At least switching between them should be configurable if you *ever* want to make fixterms *and* NeoVim popular (for the first support is needed on terminal emulators side, including NeoVim, but for the second legacy support is needed for compatibility issues).

**Comment by tarruda** [comment]
Note that is already possible to send any escape sequence to the terminal using `jobsend()`, so in theory it would be possible to configure certain keys to send anything by combining `jobsend()` with `tmap`.

This would not be very polished because `jobsend()` is non-blocking, so it might be a good idea to implement a simple mechanism to achieve translations. Possibly a user-defined vimscript function that receives typed keys and optionally returns a replacement string with the desired sequence?

**Comment by ajpaulson** [comment]
Not sure if I should open another ticket for this, but it seems that it's not just the alt key that is handled in an unexpected way for the terminal buffers. it seems up and down also are, in a way that breaks zsh history substring searching.

 (ref: http://lists.alioth.debian.org/pipermail/pkg-zsh-devel/2012-September/000537.html )

**Comment by acornejo** [comment]
+1.

There seems to be something fundamentally wrong with the alt key and vim (and neovim). Browsing through the issues I see that this has been reported multiple times, but this is one of the only issues that was left open.

It should be possible to detect this key stroke, since tmux (another console program) properly detects alt, ctl, and escape modifiers without getting confused between. That being said, I understand that doing the same in vim/nvim might be very tricky, since it depends on whatever code/library handles the input.

**Comment by kstep** [comment]
This issue is a show-stopper for me, this is the only thing (for now) that stops me from switching from vim to neovim.

**Comment by pgdouyon** [comment]
Not sure if this will work on everyone's setup (or if it's been posted somewhere else), but this workaround for alt chords did the trick for me:

```vim
tnoremap <M-.> <Esc>.
```

I've only tried it on iTerm2/Terminal.app and I also use it inside of tmux.

**Comment by justinmk** [comment]
@pgdouyon Yes that should work universally. We should probably add do that hack internally (for all keys) until this issue is solved for real.

**Comment by kstep** [comment]
Sorry, doesn't work for me (st+tmux). And I'm not going to switch to some other terminal emulator and/or OS for neovim only, as all other terminal programs work with Alt-keys very well.

**Comment by kstep** [comment]
However `inoremap <M-.> <Esc>.` worked. I think I can live with it, though it's not very good solution.

**Comment by justinmk** [comment]
@kstep You are commenting on an issue regarding `:terminal`. If `inoremap` is changing behavior then you aren't testing in a `:terminal`.

**Comment by Perugolate** [comment]
FWIW I've been using:
```
  tnoremap <A-b> <Esc>b
  tnoremap <A-f> <Esc>f
  tnoremap <A-.> <Esc>.
```
as a workaround for `Alt .` for yank-last-arg, and `Alt f` / `Alt b` for word jumping

**Comment by kstep** [comment]
@justinmk I see, thank you. I wasn't aware of the feature, I found the issue by googling for "alt key neovim issue". Anyway, `inoremap` fix works for my issue and now I know about `:terminal` neovim feature. Thank you!

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/3982 may be a fix for this issue.
