### ISSUE TITLE
Same sign id from sign_place for first 2 signs placed in different buffers

### ISSUE THREAD

**Issue by LiadOz** [neovim/neovim#24467]
### Problem

When placing signs using sign_place with 0 as the first parameter, if the first 2 signs are placed in different buffers, the sign id that is returned will be 1 for both of them. The subsequent sign ids are 2,3,4 ... regardless of where they are placed.
This does not happen when the first 2 signs are place in the same buffer.

### Steps to reproduce

nvim --clean
open 2 different buffers
run `:lua vim.fn.sign_define('test', { text = 'A', texthl = "", linehl = "", numhl = "" })`
run `:lua print(vim.fn.sign_place(0, 'my', 'test', vim.api.nvim_get_current_buf(), {lnum = 1, priority = 11}))` in each buffer

### Expected behavior

The printed output should be 1, 2. Instead you get 1, 1

### Neovim version (nvim -v)

0.8.3 0.9.0 0.9.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ubuntu 22 wsl

### Terminal name/version

-

### $TERM environment variable

-

### Installation

appimage

**Comment by zeertzjq** [comment]
It's only implies once here that sign ID only needs to be unique per buffer:
```
		It's up to the user to make sure the {id} is used only once in
		each file (if it's used several times unplacing will also have
		to be done several times and making changes may not work as
		expected).
```
I think it should also be mentioned here:
```
							*sign-identifier*
Each placed sign is identified by a number called the sign identifier. This
identifier is used to jump to the sign or to remove the sign. The identifier
is assigned when placing the sign using the |:sign-place| command or the
|sign_place()| function. Each sign identifier should be a unique number. If
multiple placed signs use the same identifier, then jumping to or removing a
sign becomes unpredictable. To avoid overlapping identifiers, sign groups can
be used. The |sign_place()| function can be called with a zero sign identifier
to allocate the next available identifier.
```

**Comment by LiadOz** [comment]
I don't think it's a vim issue, sign_place is a function unique to neovim. The first argumet is a requested sign id, if the sign id is 0 neovim returns the next sign id for that namespace.
I have looked a bit into neovim code and it does look like there may be an issue with the second sign allocation.

**Comment by zeertzjq** [comment]
Are you using a very old Vim version? `sign_place()` is present as early as Vim 8.1.0614.

**Comment by LiadOz** [comment]
Ah I see, I thought this a vim function that neovim wrapped...

**Comment by luukvbaal** [comment]
I do think this is quite unexpected indeed, and it only happens for signs placed in a specific group, not the global group. To replicate this I had to distinguish the two cases in #25724:

```c
static uint32_t sign_group_get_next_signid(buf_T *buf, const char *group)
{
  uint32_t ns = group ? (uint32_t)nvim_create_namespace(cstr_as_string((char *)group)) : 0;

  if (group && marktree_lookup_ns(buf->b_marktree, ns, 1, false, NULL).pos.row < 0) {
    return 1;
  }

  uint32_t id = group ? map_get(uint32_t, uint32_t)(&namespace_sign_ids, ns) : next_sign_id++;
  // Search for the next usable sign identifier
  while (marktree_lookup_ns(buf->b_marktree, ns, id, false, NULL).pos.row >= 0) {
    id = group ? id + 1 : next_sign_id++;
  }

  return id;
}
```

The global sign id is always incremented, a group sign id is only incremented when it is already found in the buffer. As well as the next group sign id is reset to 1 when it is not found in the buffer, the global sign id is unconditionally incremented.

Should I fix these instead of keeping it bug-for-bug compatible (will need to adjust some oldtests)?

**Comment by luukvbaal** [comment]
I actually think we shouldn't try to replicate vim at all here and just rely on `extmark_set()` to return the proper id. So I got rid of `sign_group_get_next_signid()`. `extmark_set()` unconditionally increments but since it stores the ids per buffer you would still get [1, 1].
I think that is fine since legacy signs and now extmark signs are unique to a buffer anyways.

**Comment by zeertzjq** [comment]
After #25724 the docs still doesn't mention that signs IDs are only unique per buffer, but since the docs are already different from Vim this no longer needs a Vim patch.
