### ISSUE TITLE
bountysource

### ISSUE THREAD

**Issue by Konfekt** [neovim/neovim#2450]
I'd like to contribute to the NeoVim bountysource but have scruples backing a 7500$ monthly salary where the cost of comfortable living is below (and 200$ minium wage). Perhaps as an open source idealist, I think of it rather as a donation than a hire; just as the money Vim raises goes to Uganda.
 
Viewed pragmatically this is just fine, as the proposed salary is probably the programmer's current market value and the bountysource is still a good investment for all of us. But wishful thinkers may have hoped it would take less to devote more time to NeoVim.

**Comment by tarruda** [comment]
We have a mailing list and chat room where you can express your non-technical opinions about the project, the issue tracker is not the best place to do it.

But since this is not the first time I read about this, I will indulge your questioning of the campaign values and reference it to others who have similar concerns.

> I'd like to contribute to the NeoVim bountysource but have scruples backing a 7500$ monthly salary where the cost of comfortable living is below (and 200$ minium wage).

You can help with as little as $1/month, I don't see how the final amount is relevant to you. Forgive me if I didn't get your argument, but it seems to me that the only reason you wont support Neovim is because you think that $7500 is too much for someone living in Brazil.

> Perhaps as an open source idealist, I think of it rather as a donation than a hire; just as the money Vim raises goes to Uganda.

I'm will willing to stop everything I do and focus all my energy on Neovim, so yes, this is not a simply a donation to assist development, but the crowdfunding analogous of hiring.(See the description of the service in https://salt.bountysource.com/)

As for the value, yes, it is above the average programmer salary. But I have to take the following into account:

  - 10% from bountysource
  - health insurance
  - transaction fees(I pay about $100 to receive wire transfers in my bank)
  - taxes, which in Brazil are as high as in France(except we get nothing in
    return)
  - the fact that this is not a fixed salary, since supporters can stop paying
    anytime

If you still don't feel like helping with the campaign, then I'm sorry but this is all the justification I will give.
