### ISSUE TITLE
vim.system(xdg-open) fails (but jobstart succeeds)

### ISSUE THREAD

**Issue by milisims** [neovim/neovim#24567]
### Problem

On my system,
- `vim.fn.jobstart({ 'xdg-open', 'https://github.com/neovim/neovim' })` opens the url as expected in the browser
- `vim.system({ 'xdg-open', 'https://github.com/neovim/neovim' })` does not, neither does `:!xdg-open <url>`, or `vim.fn.system`, and calling it with a string instead of a table does the same thing.

The detach option does not change this result, they both correctly call `xdg-open` with the correct url, with nearly the same environment (`SHLVL=2` is set in one), and I start neovim with `nvim -u NONE`

The same function calls with `expand('~')` all work as expected.

I found this from `K` working in lazy.nvim ([here](https://github.com/folke/lazy.nvim/blob/dac844ed617dda4f9ec85eb88e9629ad2add5e05/lua/lazy/util.lua#L44C24-L44C24)), and `vim.ui.open` with the new `gx` failing to open URLs

### Steps to reproduce

1. nvim -u NONE
2. `:vim.fn.jobstart({ 'xdg-open', 'https://github.com/neovim/neovim' })`
3. `:vim.system({ 'xdg-open', 'https://github.com/neovim/neovim' })`

### Expected behavior

the url opens in both cases.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-753+g4a06de40e (nightly 08/04)

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Ubuntu 22.04.01

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

appimage (extracted)

**Comment by zeertzjq** [comment]
Duplicate of #9886

**Comment by lewis6991** [comment]
There's a lot of context to digest in the issue chain. Can someone provide an up to date summary of the issue here? I'm confused why `jobstart` works.

**Comment by milisims** [comment]
Using `firefox` in place of `xdg-open` works as expected, and regardless of system or jobstart call, the script executes and returns 0, fwiw

**Comment by lewis6991** [comment]
It's also worth noting `vim.system` is just an alias for `vim.uv.spawn`. Afaik `jobstart` uses uv_spawn internally which is why I'm confused there is a difference in behaviour.

**Comment by justinmk** [comment]
> faik `jobstart` uses uv_spawn internally which is why I'm confused there is a difference in behaviour.

The flags given to uv_spawn may be different. https://github.com/neovim/neovim/blob/76f30591b0f07e2eb1e07e866eea893cc4488c0a/src/nvim/event/libuv_process.c#L23

For example that opening GUI apps with `UV_PROCESS_DETACHED` works much better than without. Though that isn't the difference in this case.

**Comment by justinmk** [comment]
oh wait, lol https://github.com/neovim/neovim/blob/76f30591b0f07e2eb1e07e866eea893cc4488c0a/src/nvim/event/libuv_process.c#L40-L41

**Comment by justinmk** [comment]
The discussion in https://github.com/neovim/neovim/issues/9886 is related, but this isn't a duplicate.

I think `vim.system` should always set `detach` on unix-likes, for reasons explained in https://github.com/neovim/neovim/commit/8d90171f8be6b92d7186ca84c42a0e07c2c71908 

But this also implies that `vim.system` processes need to be registered as "jobs", just like `jobstart` jobs. Otherwise Nvim can't cleanup jobs on exit. (Not to mention, we want all "jobs" in one system. I didn't block the `vim.system` PR on this detail, but it is something we eventually need to think about.)

**Comment by justinmk** [comment]
> The detach option does not change this result,

@milisims did you try `detach` with `vim.system` ?

**Comment by milisims** [comment]
`vim.system({ 'xdg-open', 'https://github.com/neovim/neovim' }, { detach = true })`, as well as just using [vim.ui.open](https://github.com/neovim/neovim/blob/6fa17da39b270bf230764859a9537124b18d3ed5/runtime/lua/vim/ui.lua#L152) on any url.

**Comment by lewis6991** [comment]
> Maybe vim.system should always set detach on unix-likes, as jobstart

It's not clear to me what tangible benefit this would have (other than potentially fixing this issue). This just seems like more effort than it's worth. For most cases non-detached is what you want as it guarantees child processes won't be orphaned. Even if we try to cleanup detached processes ourselves, that cleanup won't happen in case of a crash.

`jobstart` does some extra flags with the pipes which I think is more likely the culprit here.

**Comment by justinmk** [comment]
> For most cases non-detached is what you want as it guarantees child processes won't be orphaned.

Does killing a process started with `uv.spawn`, kill its descendants? That's the motivation for `libuv_process.c` always setting `UV_PROCESS_DETACHED` on non-Windows. https://github.com/neovim/neovim/issues/6530

> `jobstart` does some extra flags with the pipes which I think is more likely the culprit here.

yeah I was wondering about that too. Worth a try...

**Comment by lewis6991** [comment]
> Does killing a process started with uv.spawn, kill its descendants? That's the motivation for libuv_process.c always setting UV_PROCESS_DETACHED on non-Windows. https://github.com/neovim/neovim/issues/6530

No I don't think so, which is why `detached` should probably be preferred if the process is expected to launch its own subprocesses: LSP, `make`, etc.

Each way has its cons. I think this table is roughly correct.

<table>
<tr>
 <td>
 <td>attached (`setpgid()`)
 <td>detached (`setsid()`)
<tr>
 <td>nvim crash
 <td>killed
 <td>orphaned
<tr>
 <td>kill subprocess
 <td>doesn't kill descendants
 <td>kills all non-detached descendants
</table>

Neither is ideal, but given that I think most subprocesses are usually simple, defaulting to attached seems like the safest route.

With that said we should make sure that we add any necessary plumbing to make detached processes work as well as they can which means adding any cleanup logic to `vim.system` via a `VimLeave` autocmd.

**Comment by milisims** [comment]
fixed as of at least  NVIM v0.10.0-dev-2968+g344906a08 , don't know exactly. Probably a long time ago

**Comment by milisims** [comment]
fixed as of at least NVIM v0.10.0-dev-2968+g344906a08 , don't know exactly. Probably a long time ago
