### ISSUE TITLE
Bram Moolenaar

### ISSUE THREAD

**Issue by pguerin3** [neovim/neovim#24579]
### Problem

It's been widely reported that Bram Moolenaar, the originator of Vim and inspiration for Neovim, has passed.
https://groups.google.com/g/vim_announce/c/tWahca9zkt4

Just wondering if this could be recognised in the Neovim website somewhere?

### Expected behavior

Maybe a modest tribute on the Neovim website.

**Comment by ss-raicangu** [comment]
😢 RIP. An upvote from me to tribute Bram for his legacy with Vim and his charity efforts for Uganda.

**Comment by binbjz** [comment]
R.I.P
Thank you Bram.

**Comment by kuator** [comment]
I think dedicating the next neovim release to Bram might be an another idea to remember the man

**Comment by colbyrussell** [comment]
@justinmk @clason please determine the appropriate disposition for this bug.

From [comment #0](https://github.com/neovim/neovim/issues/24579#issue-1838058088):
> ### Expected behavior
> Maybe a modest tribute on the Neovim website.

The page at <https://neovim.io/news/2023/08> now exists.

This issue, therefore, needs to either be marked as resolved or the report modified to specify some other expected behavior.
