### ISSUE TITLE
rpcstart()'s API is inconsistent with jobstart

### ISSUE THREAD

**Issue by splinterofchaos** [neovim/neovim#2463]
@bfredl noted in #2424 that `rpcstart()`'s interface is rather inconsistent, and kinda odd, too.
```vim
call rpcstart('prog', ['arg1', 'arg2'...])
```
In #2424, I could easily change this to have a unified interface with `jobstart`, `termopen`, and `systemlist` (strings get run through the shell, lists get run directly), but I wanted to check if anyone relies on the current interface, first, or if there's a specific reason it works this way.

**Comment by bfredl** [comment]
:+1: I would guess that most occurences of `rpcstart` are currently in this repo (to start legacy providers and hosts) and could easily be changed togheter with `rpcstart` itself.

**Comment by tarruda** [comment]
:+1:

**Comment by elmart** [comment]
Some time ago there was some discussion about changing rpc family function names to something a bit more sensible and coherent with job family functions. See [here](https://github.com/neovim/neovim/pull/1515#issuecomment-63983230).

As changing these interfaces breaks existing plugins using async facilities, this kind of change shouldn't be done very often. I mean, we can do it (we're still in alpha and interfaces can be changed looking for improvement), but we shouldn't make many successive changes on them.
So, maybe you can take the chance you're changing this to also include the renaming to remotestart, remotecall, remotesend and remotestop suggested in the link above, if others agree. @tarruda ? @justinmk ?

**Comment by bfredl** [comment]
:+1: though I wonder if it should be `remotenotify` to make it obvious that it is a (msgpack) notification. It don't really correspond directly to `jobsend` as both `remotecall` and `remotenotify` will send data.

**Comment by elmart** [comment]
The fact that we use msgpack as transport protocol / transfer-format is an implementation detail that shouldn't leak to the interface. We could very well change that in the future (though that's improbable).

Also, calling it `remotenotify` doesn't change anything (you still have two functions sending data).
And, in fact, that's what we want: two ways for sending data: one synchronous (i.e., send data and wait for response) and one asynchronous (i.e. send data and return without waiting).

The intended improvement in naming is to clarify this sync-async distinction: the `call` in `remotecall` suggests "synchronous" while the `send` in `remotesend` (coherent with `jobsend`) suggests "asynchronous".

**Comment by bfredl** [comment]
> The fact that we use msgpack as transport protocol / transfer-format is an implementation detail that shouldn't leak to the interface.

This is not true. All external plugin hosts / client libraries comminucate with nvim over a well defined (though not yet stabilzed) interface, which is based on msgpack-rpc. If we change this, all such hosts/clients (many of which are outside of neovim organization) need to change as well. 

> And, in fact, that's what we want: two ways for sending data: one synchronous (i.e., send data and wait for response) and one asynchronous (i.e. send data and return without waiting).

Of course, that was precisely my point. But yes you're right `send` conveys the asynchronous nature, so it is probably clear that it corresponds to msgpack-rpc notifications :+1:

**Comment by tarruda** [comment]
@elmart Personally I don't mind changing the names, but the rpc functions don't have a 1-1 correspondence with the job functions, not only because the request/notification distinction, but because these functions can be also used with channels created via socket connections([here](https://github.com/lahwran/dotfiles/blob/651ae83665f4cb35e6d00df993b281c56e518690/bin/nvim-inner) is one example which would not break by a change in `rpcstart` but would in changes to `rpcnotify`).

The remote plugin infrastructure builds on top of the rpc functions, but they can also be used outside the context of remote plugins, as the above example shows.

**Comment by splinterofchaos** [comment]
> > The fact that we use msgpack as transport protocol / transfer-format is an implementation detail that shouldn't leak to the interface.

> This is not true. All external plugin hosts / client libraries comminucate with nvim over a well defined (though not yet stabilzed) interface, which is based on msgpack-rpc. If we change this, all such hosts/clients (many of which are outside of neovim organization) need to change as well.

In `runtime/doc/remote_plugin.txt`, we do talk about msgpack, and I think that's the only point one needs to start learning about msgpack. One doesn't need to know or understand msgpack in order to use the `rpc*` interface. Also, RPC is descriptive enough in that one could wiki it and at least understand that the communication undergoes some serialization/deserialization. I  think our naming scheme is fine.

It's only the parameters I want to change:
```vim
call rpcstart(['prog', 'arg1', 'arg2'])
" or
call rpcstart('prog arg1 arg2')
```
would allow `rpcstart()` to use the same `typval_T` -> `argv` code as `jobstart()`, `system()`, and `termopen()` (via the mentioned PR), and be more consistent from an API standpoint.

**Comment by elmart** [comment]
Ok, then. I just wanted to let you know there was this thing about renaming which was started but not concluded before. But, if there's no consensus on new names, better to leave it as it is and just do your original purpose of changing parameters. Thx.

**Comment by bfredl** [comment]
I'm fine with any naming really, my point was more, if you use these `rpc*` functions, you probably are in control of the messaging implementation of the other end as well. (or even use a non-nvim-aware msgpack-rpc program) If you communicate with an existing host/rplugin, you probably would use the highlevel host/rplugin interface that automatically wraps these in vimscript functions/commands. The expection to this is of course if you communicate with an embedded nvim instance, but even then my understand was that we might want to wrap this in a vimscript library for most usecases.

**Comment by justinmk** [comment]
> So, maybe you can take the chance you're changing this to also include the renaming to remotestart, remotecall, remotesend and remotestop suggested in the link above

I thought we settled on `rstart`, `rcall`, `rstop`, etc. If so I'm in favor of it, it's been on my to-do list.

**Comment by elmart** [comment]
Well, we didn't do it because, in fact, we didn't settle on anything.

**Comment by bfredl** [comment]
another option is to use `jobstart(..., {'rpc': v:true})` and `jobstop()`. At least `rpcstop()` seems very redundant, we don't have `termstop()` just because we have `termstart()`.

**Comment by justinmk** [comment]
@bfredl Yes, rpcstart's own doc mentions `Spawns {prog} as a job`, so it is arguably a special case of jobstart(). But it returns a channel id.

> `jobstart(..., {'rpc': v:true})`

So that would still return a job id, but that's fine. Because stdin/stdout connection is itself a "special case" (only one such connection is possible for a given process). We could add a new function `chan()` which takes a `{job}` or a `{address}` (like VIm's `ch_open()`). 

- If the argument is a job and the job has an existing stdin/stdout channel, `chan()` returns the channel id.
- If the argument is an `{address}` it behaves like Vim's `ch_open()`. (We can leave this TODO)

Lots of other simplification and unifcation that could be done with `rpc*()`, taking or simplifying ideas from Vim's `ch_*()`.

**Comment by bfredl** [comment]
Almost. I would also identify the job id and the channel id in the case `jobstart` creates both a job and a channel. Otherwise I would look forward to answer why this doesn't work 3 times a week on irc/gitter:
```
let myid = jobstart(..., {'rpc': v:true})
call rpcnotify(myid, "start", ["the", "thing"])
```
Remember, it is an ad-hoc internal distinction that rpc jobs have "channels" while bytes based io hasn't. Consider if we add sockets later on, then we should both support byte based and rpc based io. Bram said that our jobs-first approach scale badly to adding sockets, but for me thats only a question of naming the functions. There is no reason `jobsend(sock, ["bytes", "more bytes"])` and `jobclose(sock)` shouldn't work for a bytes socket, we only need to give the functions more neutral names (and keep the old ones as deprecated aliases).

**Comment by justinmk** [comment]
> we only need to give the functions more neutral names (and keep the old ones as deprecated aliases).

Agreed. I like the direction this is going.

**Comment by bfredl** [comment]
implementing `jobstart(..., {'rpc': v:true})` in #4723

**Comment by bfredl** [comment]
Also, apart from `jobstart(..., {'rpc': v:true})` and `jobstop`, I would suggest just "settling on" the existing names  `rpcrequest` and `rpcnotify`. As I said here most users and plugin writers will not use these directly, and so changing them at this point seems not worth it, not when the existing names are perfectly clear (for the host/client implementer which will deal with the requests and notifications on the other end) : they make an rpc request and an rpc notification respectively.

The only one that not sits well is `rpcstop(id)` where id is a socket (one closes a socket, "stops" it not), maybe that should be `rpcclose(id)` or we should rename/alias `jobclose()` to `close()` (which would also make sense if/when we add bytes sockets)

**Comment by justinmk** [comment]
The titular issue here was resolved by https://github.com/neovim/neovim/pull/4723 as well as some of the other directions suggested here. The last comments from @bfredl are the direction we want to go, and #4723 made progress there as well.
