### ISSUE TITLE
Windows: expand('%:p') returns inconsistent slashes

### ISSUE THREAD

**Issue by carlosdcastillo** [neovim/neovim#2471]
On windows, with the latest binary on appveyor if you run :echo expand('%:p') it will say the current filename however all slashes will be back slashes except the last one which is a forward slash. Example:

C:\Users\carlos\atom\packages\vim-mode\lib/vim-state.coffee
(all back slashes except for the last one which is a forward slash)

If I ask normal vim it reports the name as:

C:\Users\carlos\atom\packages\vim-mode\lib\vim-state.coffee
(all of them backslashes)

**Comment by equalsraf** [comment]
I've been seeing similar issues, and :set shellslash doesnt seem to help

From :echo expand('%:p') if I try to edit a non existing file

    (...)\build-mingw/test\

Which is doubly weird because of that trailing slash.

The culprit seems to be append_slash. Here is a small fix

```diff
diff --git a/src/nvim/path.c b/src/nvim/path.c
index dbb653c..688a778 100644
--- a/src/nvim/path.c
+++ b/src/nvim/path.c
@@ -2056,7 +2056,11 @@ int append_path(char *path, const char *to_append, int max_len)
       return FAIL;
     }
 
+#ifdef BACKSLASH_IN_FILENAME
+    STRCAT(path, pseps);
+#else
     STRCAT(path, "/");
+#endif
   }
```

but I'm not clear on whether or not to change the slash in the if statement.

```C
  // Glue both paths with a slash.
  if (current_length > 0 && path[current_length-1] != '/') {
    current_length += 1;  // Count the trailing slash.
```

**Comment by justinmk** [comment]
@equalsraf That looks like the right fix. Note that `append_path()` was mostly a new function introduced in Neovim, so there is no analog in Vim.

> but I'm not clear on whether or not to change the slash in the if statement

Based on usages of append_path and the fact that we introduced it, yes, it should compare `psepc` *and* `psepcN`.

P.S. Why don't we define `pseps` for all platforms and use it, instead of hard-coding "/" in places?

**Comment by equalsraf** [comment]
> P.S. Why don't we define pseps for all platforms and use it, instead of hard-coding "/" in places?

ascii.h actually defines PATHSEPSTR as pseps and PATHSEP as psepc. I've pushed a commit into #810 to fix a couple of cases in path.c. Still missing the following two

- path_fix_case()
- path_get_absolute_path()

In some cases though checking pseps is not the right way, one needs to check against '\' and '/'.

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/5184
