### ISSUE TITLE
Navigating back from netrw results in "Mark has invalid line number"

### ISSUE THREAD

**Issue by RobertBrunhage** [neovim/neovim#24721]
### Problem

When I navigate to a file, open `Netrw` and click `ctrl+o` to go back to the file it prints "Mark has invalid line number". I am just getting started with Netrw instead of a normal filetree plugin and maybe this is expected but couldn't find anything about it.

### Steps to reproduce

1. nvim .
2. pick a random file
3. `:Ex`
4. `ctrl+o
5. "Mark has invalid line number"

### Expected behavior

1. nvim .
2. pick a random file
3. `:Ex`
4. `ctrl+o`
5. Comes back to the random file from before

### Neovim version (nvim -v)

NVIM v0.10.0-dev-839+g7aad4643f

### Vim (not Nvim) behaves the same?

using defaults:
no, 9.0.1544 (:Explore not an editor command)

using `vim` normally it's doing the same as in Neovim

### Operating system/version

macOS 13.5

### Terminal name/version

Iterm 3.4.19 (also tried the default MacOS terminal)

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by clason** [comment]
> Vim (not Nvim) behaves the same?

> no, 9.0.1544 (don't have netrw)

Oh, it very much does  (where do you think we got it from?)

**Comment by RobertBrunhage** [comment]
> > Vim (not Nvim) behaves the same?
> 
> > no, 9.0.1544 (don't have netrw)
> 
> Oh, it very much does (where do you think we got it from?)

Never used the default vim before but tried the command above `vim -u DEFAULTS` and wrote `:Explore` but it said "no editor command"

**Comment by RobertBrunhage** [comment]
It seems to make a difference when I do the following:

**Works:**
1. open the specific file right away `nvim testing.txt` 
2. `:Ex`
3. `ctrl+o` 
4. now I am in testing.txt again.

**Doesn't work:**
1. nvim .
2. open testing.txt
3. `Ex`
4. `ctrl+o`
5. Cursor is at the top of Netrw(?) and doing it again takes me further back in the history (another file I've opened before)

**Comment by lsvmello** [comment]
This behavior was intentionally removed because [clipboard=unnamed is slow](https://github.com/neovim/neovim/issues/11804).
More information about it can be found on https://github.com/neovim/neovim/pull/25501#pullrequestreview-1657529362.

**Comment by justinmk** [comment]
what does clipboard have to do with this?

**Comment by lsvmello** [comment]
Vim's solution for this was using `let @+ = ...`.

As you mentioned on my closed PR:

> These `let @+ = ...` calls were intentionally removed in https://github.com/neovim/neovim/commit/6c22c7ab97cca9f8dda6863ee7f1db1ce30a3451 for performance.
> 
> netrw is super noisy about writing to the clipboard, which is slow in Nvim. 
> 
> Nvim clipboard could be made faster with an approach like https://github.com/neovim/neovim/issues/11804#issuecomment-1113927971

**Comment by justinmk** [comment]
But why does setting the clipboard affect marks / jumplist?

**Comment by RobertBrunhage** [comment]
I don't have `clipboard` changes in my neovim setup, so not sure I follow. From my understanding it shouldn't be an issue(?)

**Comment by justinmk** [comment]
The proposed fix in https://github.com/neovim/neovim/pull/25501/files adds code which sets the clipboard. This issue is about ctrl-o "Mark has invalid line number". I'm asking how the code changes in #25501, which only appear to set the clipboard (`@+` and `@*`), have an affect on ctrl-o or the jumplist.

**Comment by lsvmello** [comment]
@justinmk my bad, It is a weird behavior of the jumplist, and I by mistake thought that the `clipboard` had something to do with it because it 'worked' when I did the changes.

@RobertBrunhage I looked at the `jumplist` and netrw was built to not affect it by default, but you can disable this, see `:help netrw_keepj` (when disabled it polutes the `jumplist`).
You can test this out better opening Neovim without the ShaDa file: `nvim -i NONE`.

The "Mark has invalid line number" happens when the jump becomes `-invalid-`, when this happens and you jump forward Vim removes the jump from the list, and Neovim incrementes the line number.

Steps to reproduce:
1. Open a file with `nvim -i NONE file.txt`
2. `:Ex` to open netrw's file explorer
3. `Ctrl+O` to go back to the file
4. `:jumps` to see that the jumplist is fine
5. `Ctrl+I` to go back to the netrw's file explorer
6. `:jumps` now the current jump show as `-invalid-`
7. `Ctrl+O` to go back to the file
8. `Ctrl+I` to go back to netrw's file explorer then errors `E19: Mark has invalid line number`
9. `:jumps` -> you can see that the line has changed

On Vim if you check `:jumps` after step 7 the `-invalid-` jump won't be on the list.

**Comment by RobertBrunhage** [comment]
@lsvmello oh, disable `netrw_keepj` did the trick for me!

**Comment by RobertBrunhage** [comment]
I am closing this as I don't have the issue with the above solution.
