### ISSUE TITLE
CMD + SHIFT mappings are inconsistent

### ISSUE THREAD

**Issue by fredizzimo** [neovim/neovim#25068]
### Problem

CMD + SHIFT mappings behave differently from other mappings like ALT + SHIFT and are not normalized to a standard format. The reason seems to be this line, which I have found no explanation for https://github.com/neovim/neovim/blob/6e26964e0effdb4998fb98bc7f87430ce50cc672/src/nvim/keycodes.c#L774

This also makes mappings between different Neovim GUIs inconsistent, since each of them reports the mappings slightly differently to Neovim. 

NOTE: I'm aware that the CTRL mappings behaves differently due to legacy reasons, and it's also clear why the CTRL condition is there. But not why the condition is there for CMD.

### Steps to reproduce

1. Create a file `mappings.vim` with the following contents
```vim
map <D-a> <cmd>:echomsg "D-a"<cr>
map <D-A> <cmd>:echomsg "D-A"<cr>
map <D-S-a> <cmd>:echomsg "D-S-a"<cr>
map <D-S-A> <cmd>:echomsg "D-S-A"<cr>

map <M-a> <cmd>:echomsg "M-a"<cr>
map <M-A> <cmd>:echomsg "M-A"<cr>
map <M-S-a> <cmd>:echomsg "M-S-a"<cr>
map <M-S-A> <cmd>:echomsg "M-S-A"<cr>

map <C-a> <cmd>:echomsg "C-a"<cr>
map <C-A> <cmd>:echomsg "C-A"<cr>
map <C-S-a> <cmd>:echomsg "C-S-a"<cr>
map <C-S-A> <cmd>:echomsg "C-S-A"<cr>

call feedkeys("\<D-a>")
call feedkeys("\<D-A>")
call feedkeys("\<D-S-a>")
call feedkeys("\<D-S-A>")

call feedkeys("\<M-a>")
call feedkeys("\<M-A>")
call feedkeys("\<M-S-a>")
call feedkeys("\<M-S-A>")

call feedkeys("\<C-a>")
call feedkeys("\<C-A>")
call feedkeys("\<C-S-a>")
call feedkeys("\<C-S-A>")
```
2. Run `nvim --clean -u mappings.vim`
3. Type `:messages`
4. Observe that the following output was generated
```
D-a
D-A
D-S-a
D-S-A
M-a
M-S-A
M-S-A
M-S-A
C-A
C-A
C-S-A
C-S-A
```

### Expected behavior

The output should be:
```
D-a
D-S-A
D-S-A
D-S-A
M-a
M-S-A
M-S-A
M-S-A
C-A
C-A
C-S-A
C-S-A
```

Making the `D` and `M` mappings consistent, and select the last shift combination that was mapped.

### Neovim version (nvim -v)

NVIM v0.9.2

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux (WSL)

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

pacman

**Comment by matu3ba** [comment]
Likely related https://github.com/mitchellh/ghostty/issues/417 (certain modifier + function key keybinds do not work in neovim).
Motivation: Mapping C-F11 in neovim (which does not work) from https://neovim.discourse.group/t/how-can-i-map-ctrl-shift-f5-ctrl-shift-b-ctrl-and-alt-enter/2133/2

minimal `init.lua`:
```lua
local map = vim.api.nvim_set_keymap

map('n', '<sc-f5>', [[<cmd>lua print('ctrl+shift+f5')<cr>]], {noremap = true})-- does not work
map('n', '<c-f5>', [[<cmd>lua print('ctrl+f5')<cr>]], {noremap = true})-- does not work
map('n', '<s-f5>', [[<cmd>lua print('shift+f5')<cr>]], {noremap = true})-- does not work
map('n', '<a-f5>', [[<cmd>lua print('alt+f5')<cr>]], {noremap = true})-- does not work
map('n', '<cs-B>', [[<cmd>lua print('ctrl+shift+b')<cr>]], {noremap = true})-- works
map('n', '<c-+>', [[<cmd>lua print('ctrl+shift+=')<cr>]], {noremap = true}) -- Ctrl+Shift+= -- does not work
map('n', '<c-=>', [[<cmd>lua print('ctrl+=')<cr>]], {noremap = true}) -- Ctrl+= -- internally used to set default font size
map('n', '<c-.>', [[<cmd>lua print('ctrl+.')<cr>]], {noremap = true}) -- Ctrl+. -- works
map('n', '<a-cr>', [[<cmd>lua print('alt+enter')<cr>]], {noremap = true}) -- Alt+Enter -- works
```

`kitty +kitty show_key -m kitty` with aforementioned config shows:
```
shift+f5: CSI 15 ; 2 ~
ctrl+f5: CSI 15 ; 5 ~
shift+ctrl+f5: CSI 15 ; 6 ~
alt+f5: CSI 15 ; 3 ~
ctrl+shift+=: CSI 61 ; 6 u
``` 
From [issue](https://github.com/mitchellh/ghostty/issues/417#issuecomment-1712541859): "Note that these are the correct sequences because Neovim is explicitly requesting this Kitty keyboard mode."

**Comment by mitchellh** [comment]
Above issue is from my terminal project 😄 Happy to be educated I'm doing it wrong, but if I am, it appears Kitty is doing the wrong thing, too.

Note that this isn't restricted to Kitty keyboard protocol, because Kitty uses the legacy xterm/fixterms encoding for functional keys (source: https://sw.kovidgoyal.net/kitty/keyboard-protocol/#legacy-functional-keys and https://www.leonerd.org.uk/hacks/fixterms/). In both, it is described that the above quoted encodings are correct.

**Comment by fredizzimo** [comment]
@matu3ba, @mitchellh. I think you should open a new issue about that, since this issue is specifically about how nvim deals with CMD + SHIFT mappings. 

Your issue is most likely a TUI one, since since all those combinations work in Neovide, so the Neovim core deals with them correctly.
