### ISSUE TITLE
MatchParen highlight is applied to floating windows

### ISSUE THREAD

**Issue by MariaSolOs** [neovim/neovim#25099]
### Problem

`MatchParen` highlights are applied in non-active floating windows, such as the one for LSP hover.

### Steps to reproduce

1. Use the tippy-top of nightly Neovim.
2. In a `lua` file write:
```lua
local foo = {
  bar = 0,
}
```
3. Hover over `bar`.
4. Notice how the parentheses around `field` are underlined (the `MatchParen` highlight is being applied) despite my cursor being in an entirely different window:
<img width="253" alt="image" src="https://github.com/neovim/neovim/assets/62502207/c9ec2fbc-eefa-4001-9efe-d5eb7107932d">

### Expected behavior

For the `MatchParen` highlight to only be applied in active windows and based on the cursor position.

### Neovim version (nvim -v)

v0.10.0-dev-1074+g4258f4d53

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Mac Ventura 13.5.2

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Installation

From source

**Comment by clason** [comment]
Matchparen rewrite in Lua when?

**Comment by MariaSolOs** [comment]
@clason lol why are you looking at me

**Comment by gpanders** [comment]
This happens because `nvim_open_win` copies options from the current window into the new floating window. MatchParen uses a `WinLeave` autocommand to clear highlights in the non-active window. When the float is created, it copies everything from the current window (including MatchParen highlights), but a `WinLeave` autocommand is never triggered, so the highlight is never cleared.

I see the same thing with `'cursorline'` (I have a `WinLeave` autocommand to clear `'cursorline'` in non-active windows).

We don't see this with e.g. `:new` or `:split` because when a split is created, the new window is entered, which triggers a `WinLeave` event on the original window.

I'm not sure what the best solution is. Firing a `WinLeave` event after creating a float doesn't seem semantically correct, since the float was never entered in the first place.

**Comment by MariaSolOs** [comment]
@gpanders that's very interesting. I still get confused with the order of events and how window/buffer properties may differ in different events.

FYI that I tried #25078 and it fixes this though.

**Comment by MariaSolOs** [comment]
Closing as completed by #25078

**Comment by seandewar** [comment]
As a consequence of fixing #27121 (`BufWinEnter` is now fired again when `enter = false`), this issue is relevant again:

```vim
call setline(1, '(hi)')
lua vim.lsp.util.open_floating_preview({'(hi)'})
```

...as matchparen.vim applies its highlights on `BufWinEnter`:

https://github.com/neovim/neovim/blob/a873f33993ef84e3f954127038e559e1ac1cac43/runtime/plugin/matchparen.vim#L25

My initial reaction is that matchparen may be better served by listening to `BufEnter` instead here. :thinking:

**Comment by MariaSolOs** [comment]
> As a consequence of fixing #27121 (`BufWinEnter` is now fired again when `enter = false`), this issue is relevant again:

:'(



> My initial reaction is that matchparen may be better served by listening to `BufEnter` instead here. 🤔

That wouldn't work if the same buffer is displayed in multiple windows right?

**Comment by seandewar** [comment]
> That wouldn't work if the same buffer is displayed in multiple windows right?

If switching the current window's buffer to that one, it should still fire.
If switching to a different window that has the same buffer, `WinEnter`/`WinLeave` takes care of that instead.

One thing I can think of which _may_ make a difference is that `BufWinEnter` usually fires later than `BufEnter`, but maybe there's other issues.

**Comment by zeertzjq** [comment]
This is not limited to `nvim_open_win`. `nvim_win_set_buf` also has this problem.
