### ISSUE TITLE
set clipboard+=unnamedplus makes causes holding down 'x' in normal mode to fail

### ISSUE THREAD

**Issue by evert** [neovim/neovim#25180]
### Problem

When I add:

```
set clipboard+=unnamedplus
```

and afterwards I open any file and try to delete characters using `x`, I expect this delete to repeat but it only deletes the first character. 

### Steps to reproduce

```
nvim --clean
: set clipboard=unnamedplus
[type some characters in insert mode, exit insert mode and go to the start of the lie]
hold down 'x'
```

### Expected behavior

All characters should delete as I'm holding down x but only 1 character gets deleted.

### Neovim version (nvim -v)

NVIM v0.9.2

### Vim (not Nvim) behaves the same?

no, vim 9.0.1872  

### Operating system/version

Fedora Linux

### Terminal name/version

Gnome terminal and allacritty. 

### $TERM environment variable

`alacritty` or `xterm-256color` are both confirmed

### Installation

Fedora package manager

**Comment by evert** [comment]
Note that I'm not seeing slowness unlike the linked issue. Holding x does not work at all. Only the first delete is registered

**Comment by slankes** [comment]
@justinmk could you reopen this and remove the duplicate? I am seeing the same behaviour as well and it's not what is described in the linked ticket. 

Hitting "x" only one letter is deleted until I `:set clipboard=` and then deleting things gets back to working normally.

I am on Fedora as well - maybe the issue is related to fedora/the nvim shipped there?

**Comment by maztaim** [comment]
I am also seeing the same behavior, and I don't believe it's a duplicate of #11804 (assuming that's what was the intended duplicate).  This is true for holding down for deleting lines.  d-d<hold> fails to register subsequent d's.  If I set clipboard=, everything works as expected.

**Comment by justinmk** [comment]
> I don't believe it's a duplicate of #11804 (assuming that's what was the intended duplicate).

It is definitely the same root cause, so it is a duplicate.

**Comment by A404M** [comment]
I have the same issue but with different system/version
Arch Linux rolling release
NVIM v0.10.0
And the problem goes away when I do `:set clipboard= `
This is important for me that I just stoped using `unnamedplus` completely ( because of ease of use )
And my guess is it has something to do with Wayland/Gnome maybe ( because I use Gnome/Wayland and Fedora does too )

**Comment by miekg** [comment]
this also happens with `nnoremap x "+x`.

Regarding:

 > Hammering x is an edge case.

Agreed, but I want to default to the systems clipboard, so I also have ` nnoremap p "+p` (which is really convenient for "normal" pasting). If I make 'x' do something else, then 'xp' doesnt work anymore, which trips me up completely :)

All in all, I don't care that it would be slower (this will prolly force me to use another command to delete), but the fact the holding down 'x' doesn't repeat at all is super weird.

(sorry for posting in a closed issue)

**Comment by miekg** [comment]
To reproduce: `nvim --clean`

type something, <ESC> then x, see repeat

Add this mapping:  `:nnoremap x "+x`

Try the same, no repeat

**Comment by internettrans** [comment]
i also am encountering this problem

**Comment by EdiDD** [comment]
Same problem. 'x' not repeating with  unnamedplus and wl-clipboard installed.
Nvim 0.10.4. 
Is there any solution ?
