### ISSUE TITLE
`TreesitterAttach` and `TreesitterDetach` autocmds

### ISSUE THREAD

**Issue by lsvmello** [neovim/neovim#25237]
### Problem

There is no clean way to add logic right after treesitter is attached to a buffer, instead we have to hook our logic into another autocmd and `vim.treesitter.start()`.

Example: https://github.com/lewis6991/dotfiles/blob/13faceced69a2811773071587d9d1af1c4a7526f/config/nvim/lua/lewis6991/treesitter.lua#L65

### Expected behavior

**TreesitterAttach** and **TreesitterDetach** autocmds.

**Comment by clason** [comment]
Can you give actual examples what such an autocommand would be used for? As is, I don't really see how it would be useful. The example you show is not compelling, since the three commands in the `FileType` autocommand are logically independent.

(Treesitter doesn't "attach" or "detach"; that's something nvim-treesitter invented for their module system. That system was a mistake and is dead now.)

**Comment by clason** [comment]
You cannot avoid it, though; there's nothing else that could trigger a treesitter autocommand. 

What you have linked is in fact the intended way (together with a ftplugin).

**Comment by lsvmello** [comment]
I see, then this actually makes no sense.
