### ISSUE TITLE
Swapped characters while editing text

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#25339]
### Problem

It -could- be a coincidence, but I don't think so...

meager chromebook debian user, had been running the appimage of 10dev and while opening a directory with text files (for the second or third time) after having edited some text, some characters were misrepresented (corrupt?) like the carrot character turned to some greek-looking character and a couple others were substituted. Freaked me out at first, because I was worried my storage might have become damaged.

Upon exiting my terminal app and re-entering, there were no more misrepresented characters. I have since downloaded and am using version 0.9.2 and no issues thus far.

### Steps to reproduce

N/A

### Expected behavior

I desire the same thing you all do :  a safe and reliable editor for my work. I like the goal of NVIM and where it is heading. I recently removed classic vim v9, in favor of Neo.

### Neovim version (nvim -v)

10

### Vim (not Nvim) behaves the same?

No

### Operating system/version

chrome / debian

### Terminal name/version

chrome terminal

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by clason** [comment]
> a safe and reliable editor for my work

Then you should indeed stick to actual releases (0.9.2).

We appreciate trying to test prereleases and reporting issues, but we do need (a lot) more details in order to actually do something about them.

**Comment by zeertzjq** [comment]
There is too little information in this issue to find out what's going on.

**Comment by sawdude** [comment]
Yes, I understand your reply comments regarding too little info.

I should have emphasized how this has only happened when I invoke NVIM 10 DEV from the command line to *** open a PATH -- rather than actual file ***.

Afterward, I used NVIM's navigation to select the text file and on to editing.

In addition, it was the carrot '^' and greater than '>' that were 'swapped' upon re-entering the directory, then file like the second or third time.

**Comment by zeertzjq** [comment]
Where do the '^' and the '>' come from?

**Comment by sawdude** [comment]
Well.... I had been entering some instructions for a friend, here is a snippet:

Now, plz note that the quote and '>' is a comment in my vim script:
highlight   SAW_Comment5            ctermfg=68              ctermbg=black           cterm=bold
let MyVarComment5=matchadd('SAW_Comment5', '^">.*$')

And I wonder if that may be some contributor?

Here's the document:

">  BASE64
    Shell out to openssl's base64 using option options -e (when encoding) with option -A to produce
    output in a continuous line. Next, pipe the output to the linux fold command, specifying the desired
    width with option -w[#].

    Encoding syntax example: 'ssl enc -e -a -A -pbkdf2 -alg_name < input_file | fold -w100 > output_file'
">                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
">                           THIS is the new preferred practice. Notice that the capital '-A' is also
">                           specified along with the lowercase spec '-a'. I consider this a bug, but
">                           the good news is: only the lowercase spec '-a' is required during decoding /
">                           decryption.

**Comment by justinmk** [comment]
The formatting and narration here is all over the place. 

1. Use markdown formatting, not random junk like "***".
2. Can you just give an example of text you EXPECTED and the ACTUAL text.
3. Were the actual file contents CHANGED, or is the text only being DISPLAYED wrong?
4. Does it happen with `nvim --clean` ?

**Comment by sawdude** [comment]
That random junk was a small piece of the actual text file -- only included to show what I loaded in NV10. 

The contents only appeared changed (perhaps 2.. 3 or so characters total) but where that line of carrots was, every carrot was swapped with a non-text characters.  When I exited and re-opened my local terminal, this issue was resolved. I am thankful no data was damaged, but could not help but consider the high possibility NeoVim was the cause.

**Comment by zeertzjq** [comment]
Please answer the questions.

**Comment by sawdude** [comment]
I will try to be more precise. Thank you for your patience, I will catch on.

System = chromebook / 4gb ram, 15gb debian linux installation, local terminal session.

Shortly after installing NV10, running with fuse as an appimage -- and upon providing a path instead of file -- I selected one of only 3 text files in that folder and proceeded to edit it. 

To my best recollection, upon saving and applying the same action nearly verbatim, when I re-opened the file, that line of carrots appeared as a line of -ALL_THE_SAME- non-text greek-like character. There were a couple other instances of character-swapping, but with different characters.

Upon re-starting my local terminal session, re-opening said file, everything looked correct.

I have not run NVIM with the clean option. I carried over a basic configuration file from my previous Vim9 installation (and modified it slightly).

**Comment by clason** [comment]
They're called "carets", by the way.

**Comment by sawdude** [comment]
> They're called "carets", by the way.

TY. I had the best intentions in submitting my experience. It's not my desire to waste the developers time, which I know is valuable.

I will spend more time observing before making further entries.

**Comment by justinmk** [comment]
> Upon re-starting my local terminal session, re-opening said file, everything looked correct.

So this might be a display issue, but doesn't sound like data corruption (implied by the title).

**Comment by bfredl** [comment]
as this likely is a rendering issue, could we have a screenshot?

**Comment by clason** [comment]
> A funny thing about online communication is you generally don't know who you're chatting with.

No, nor should anyone care, beyond the relation we stand in here (maintainers and issue reporters). We are trying the best to identify an issue with our software given the information presented, and if we need more information, we ask for it (possibly curtly, given the time constraints of everyone in this business). 

And the misused word here is relevant, since you also could have referred to the "carrot" emoji, which confused me for a while.
