### ISSUE TITLE
Wish: Detach shell commands started in background

### ISSUE THREAD

**Issue by phmarek** [neovim/neovim#2543]
I pretty often run `:!git gui &` and similar commands. (Yes, I know about alternatives, like Fugitive and Gitv, and I'm using them too.)

This shorthand has the drawback that pressing Ctrl-C gets relayed to the background jobs, too - and eg. causes `git gui` to report that the spelling correction has aborted.

So, how about running the command via `setsid` if the last (non-whitespace) character in the shell command is a `&`?
Yes, that wouldn't work for multiple commands like `:!git gui & sleep 4`, but as long as the terminal is blocked by one of them it's okay that both receive the Ctrl-C, I guess.

**Comment by ZyX-I** [comment]
> So, how about running the command via `setsid` if the last (non-whitespace) character in the shell command is a `&`?

`:!cat \&`? If you need to detach there are other alternatives like `screen`. Just create a script like `~/bin/s` (assuming `$HOME/bin` is in `$PATH`) with something like the following:

    #!/bin/bash
    screen -d -m -S "s-${1//[^A-Za-z0-9_-]/_}" "$@"

and run

    s git gui

in place of

    git gui &

. It may even be faster because `s` does not require shift and is on the home row both in dvorak and us layouts.

**Comment by phmarek** [comment]
I mostly use `&` for X11 programs that shouldn't stop my running editor.

Yes, of course there are several solutions for that -- but why does everybody need to invent his own, if one `if` is enough to switch the controlling tty?

Perhaps _detach_ was the wrong word - it's mostly about having it run in the background, with a different session ID. It's not about "keep its output around".

**Comment by splinterofchaos** [comment]
What about `:call jobstart(["git", "gui"])`? For commands using the shell: `:call jobstart([&shell, &shcf, "git gui"])`.

**Comment by ZyX-I** [comment]
> Yes, of course there are several solutions for that -- but why does everybody need to invent his own, if one if is enough to switch the controlling tty?

It is not. `cat \&` does not start anything in the background, so to do this correctly you must do parsing. And you must do parsing for different shells, different versions: you cannot be sure that in next zsh version there will be no `$&` variable, though now `cat $&` is `cat '$' &`.

Also in Vim (terminal variant, not the case for GUI Vim) `git gui &` has good potential for spoiling program screen due to `git gui` output if it happens to have any, `s git gui` does not have one.

And I do not like any kind of exceptional behaviour. When I want to run something I want a clear understanding of what the result will be, and passing the input through a set of rules like “if OS is Windows and command starts with `!start` then … else if command ends with `&` then … else …” adds unneeded cognitive load.

**Comment by ZyX-I** [comment]
@splinterofchaos If I am not mistaking after #2424 second variant will be just `jobstart('git gui')`.

**Comment by splinterofchaos** [comment]
@ZyX-I correct

**Comment by justinmk** [comment]
As mentioned, jobstart() is a reasonable solution here.
