### ISSUE TITLE
:term does not support truecolor

### ISSUE THREAD

**Issue by Soares** [neovim/neovim#2571]
Running nvim in pangoterm `NVIM_TUI_ENABLE_TRUE_COLOR=1`, true color colorschemes are working great (which is great! Nice work!). However, when I drop into a `:term` and do

    echo -e "\x1b[38;2;255;100;0mI want this text to be orange\x1b[0m

the echoed text is white. By contrast,

    echo -e "\x1b[31mRED\x1b[0m"

does echo a red "red", so there must be somewhere along the way that nvim's terminal emulator isn't handling true color correctly.

Strangely enough, using fish-shell with `fish_term24bit=1`,

    echo (set_color FF6400)orang plz

*does* display orange! Weird.

(I asked about this issue on gitter, and @splinterofchaos said that he thinks there's an issue tracking it somewhere, but I couldn't find one after poking around a bit. My apologies for the noise if this is in fact a dupe.)

**Comment by jwhitley** [comment]
I've also noticed some odd behavior in :term with nvim truecolor enabled. I'm not clear whether there's overlap with @Soares' issues above.  My repro steps:

 1.  Start `nvim` with `$NVIM_TUI_ENABLE_TRUE_COLOR=1`.  I'm running under iTerm2, fwiw.
 2.  `:term`  (Note: colors in my zsh prompt are displayed correctly in this step.)
 3.  In that term window, run another nvim instance.

The "child" nvim displays no colors anywhere: it just uses the default foreground and background colors established by nvim.  This behavior stays the same whether I unset `$NVIM_TUI_ENABLE_TRUE_COLOR` in the :term window, or set it to `0`.

It's quite possible that this is a separate issue; I'll break it out as more information arises.

**Comment by liujoey** [comment]
Some updates on this, since the issue was opened on May.

When I open my gnome-terminal with solarized color template, zsh prompt looks like this:
![screenshot from 2015-08-09 21 24 29](https://cloud.githubusercontent.com/assets/123727/9158044/12a3b78e-3ede-11e5-83e4-010dde11d8fb.png)

with `NVIM_TUI_ENABLE_TRUE_COLOR=1 nvim` I got a full color vim in my terminal.
When I ran XtermColorTable plugin I got this
![screenshot from 2015-08-09 21 26 04](https://cloud.githubusercontent.com/assets/123727/9158072/6a7970f2-3ede-11e5-8c42-3d00d1396dc5.png)

Now open a `:term` in nvim, the zsh prompt color looks like this:
![screenshot from 2015-08-09 21 27 00](https://cloud.githubusercontent.com/assets/123727/9158078/8de01258-3ede-11e5-885b-c33ccc0dba5f.png)

You can already notice the color of three arrows are different from the first screenshot. Now if I open XtermColorTable, it looks like this:
![screenshot from 2015-08-09 21 27 45](https://cloud.githubusercontent.com/assets/123727/9158086/cc1e26e0-3ede-11e5-8e99-5c8220ee7677.png)

Most color are not showing, it's like the term only support 16 colors.

My $TERM is xterm-256color

**Comment by ironhouzi** [comment]
If implementing true colour for `:term` is non trivial, it would be nice to at the very least not break expected behaviour by only allowing for 16 colours in terminal mode. I would not be bothered by this if terminal mode only allowed 256 colours.

**Comment by apriendeau** [comment]
This was working at before and now just broke when I updated this yesterday and I update weekly.

**Comment by DarkDefender** [comment]
I think this issue should be solved now in master because of the changes I made in #4274

**Comment by wsdjeg** [comment]
@DarkDefender Thanks for you works ,now the even if I run nvim in terminal buffer, it looks well ,and also support true color
![2016-02-26 19-01-48](https://cloud.githubusercontent.com/assets/13142418/13350538/94dc7526-dcbb-11e5-8045-4a131302fcdc.png)

**Comment by justinmk** [comment]
Thanks @DarkDefender !

**Comment by jwhitley** [comment]
Just gave this a spin on `master`; looks great.  :beers: to @DarkDefender !
