### ISSUE TITLE
api/private/defs.h:REMOTE_TYPE

### ISSUE THREAD

**Issue by Yamakaky** [neovim/neovim#2582]
What's its meaning ? I'm working on improving struct names in buffer_defs.h. I defined Window and Buffer, but they are already defined in defs.h. It's a typedef to uint64_t, so maybe they could be renamed to WindowId and BufferId ?

**Comment by Pyrohh** [comment]
Window/BufferId sounds fine to me, but I don't see the need for a separate issue given #2588 exists.

**Comment by justinmk** [comment]
> maybe they could be renamed to WindowId and BufferId ?

Since this is Neovim-specific code, we can rename these if it makes sense. But here it implies these types are used to represent API objects:

https://github.com/neovim/neovim/blob/master/src/nvim/api/private/defs.h#L80

So, semantically, they are not ids, despite the underlying primitive. They may be extended in the future.

@tarruda should correct me if I'm wrong :)

**Comment by Yamakaky** [comment]
Name clashes, I love you ^^
