### ISSUE TITLE
on_bytes args of nvim_buf_attach are different when using `o` and `A<Enter>` 

### ISSUE THREAD

**Issue by lucario387** [neovim/neovim#25966]
### Problem

This is possibly the same as #25822 

Using `o`, the args passed to `on_bytes` of `nvim_buf_attach` is different from when using `A<Enter>`

### Steps to reproduce

- Have a test.lua file as such
```lua
vim.api.nvim_create_autocmd("BufEnter", {
  callback = function(args)
    vim.api.nvim_buf_attach(args.buf, true, {
      on_bytes = function(_, _, _, start_row, _, _, old_end_row, _, _, new_end_row, _, _)
        print(start_row, old_end_row, new_end_row)
      end
    })
  end
})
```
- `nvim --clean -u test.lua test.foo` and do `o`. We get `1 0 1`
- `nvim --clean -u test.lua test.foo` and do `A<Enter>`. We get `0 0 1`

### Expected behavior

They should both be `0 0 1`, or be more consistent.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-43b0e2752

### Vim (not Nvim) behaves the same?

unsure

### Operating system/version

Linux 6.6.1

### Terminal name/version

kitty 0.31.0

### $TERM environment variable

xterm-kitty

### Installation

Build from source

**Comment by lucario387** [comment]
This is also why #25822 was incorrect, I'd assume.

As `on_bytes` of foldexpr was relying on `on_bytes` to return the correct start row, old row and new row, but pressing `O` means the start row is the same as the new index, meaning the row range is one-off from the correct one. This can also be confirmed by instead doing `A<Enter>`, and the foldcolumn is correctly updated

**Comment by Groszczu** [comment]
I'm still encountering this issue in the latest Neovim build:

```
NVIM v0.11.0-dev-1936+g5ee62906a3
Build type: RelWithDebInfo
LuaJIT 2.1.1736781742
```

I followed the reproduction steps provided by @lucario387 and observed the same behavior. Specifically, when I press `o` on the first line (index 0), the `on_bytes` callback receives a `start_row` value of 1, whereas using `A<Enter>` results in a `start_row` value of 0.

This discrepancy is causing issues in my workflow. I call `vim.api.nvim_buf_get_text` in the `on_bytes` callback using parameters like this:

```lua
vim.api.nvim_buf_get_text(
  buf,
  start_row, -- 0 for `A<Enter>`, 1 for `o`
  start_col,
  start_row + new_end_row, -- 0 + 1 for `A<Enter>`, 1 + 1 for `o`
  (new_end_row == 0) and (start_col + new_end_col) or new_end_col,
  {}
)
```

However, pressing `o` on the last line of a buffer results in an `Index out of bounds` error due to the off-by-one error in `start_row`.

Is this discrepancy intentional or is it a bug?
