### ISSUE TITLE
New Lua background color detection doesn't work in `st` terminal emulator

### ISSUE THREAD

**Issue by echasnovski** [neovim/neovim#26038]
### Problem

When starting Neovim which includes ab102f188e86bdbfce1d4de2ef633092a906e8fe, there is an active Command line containing string like `0000/0000/0000^G` where `000000` is terminal's background color. It waits for user to press the key and then works as usual.

### Steps to reproduce

1. Download [`st`](https://st.suckless.org/) (here is a [direct link](https://dl.suckless.org/st/st-0.9.tar.gz) for download).
2. Extract archive and build it with `make` inside extracted directory.
3. Run `./st` inside extracted directory to run the terminal emulator.
4. Start `nvim --clean`. It shows `:0000/0000/0000^G` in Command line and waits for user to press a key. There is also a line `erresc: unknown csi ESC[>4;2m` printed in the terminal emulator instance which started `./st` (not sure if it is related).

This started to happen at ab102f188e86bdbfce1d4de2ef633092a906e8fe commit.

### Expected behavior

Terminal emulator starts as usual.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1561+g582d7f479

### Vim (not Nvim) behaves the same?

No

### Operating system/version

EndeavourOS Linux x86_64 (6.6.1-arch1-1)

### Terminal name/version

st-0.9

### $TERM environment variable

st-256color

### Installation

Both appimage and from source

**Comment by gpanders** [comment]
My theory is that st is sending the OSC 11 response terminated with `BEL` (`0x07`) instead of `ST` (`0x1b 0x5c`) as it should be. We learned recently that libtermkey [does not accept BEL as an OSC terminator](https://github.com/neovim/libtermkey/pull/4), so if my theory is correct what is likely happening is that st is sending us the OSC 11 response and it is not being interpreted correctly by termkey as an OSC sequence. Thus, it never gets sent in the `TermResponse` autocommand and is instead treated like regular terminal input, where it then appears in Nvim.

@echasnovski If you're comfortable doing this, here's what you can try to validate this theory:

1. Clone my [libtermkey fork](https://github.com/gpanders/libtermkey) and checkout the `orc-bel` branch
2. Clone the `neovim` repo if you haven't already. In `cmake.deps/deps.txt`, change the `LIBTERMKEY_URL` to the path where you checked out the libtermkey fork in step 1
3. Run `make distclean` just to be sure we're building everything from scratch. Then run `make deps` and `make` to rebuild Neovim
4. Run `VIMRUNTIME=runtime ./build/bin/nvim` and see if the problem persists

**Comment by echasnovski** [comment]
> @echasnovski If you're comfortable doing this, here's what you can try to validate this theory:
> 
>     1. Clone my [libtermkey fork](https://github.com/gpanders/libtermkey) and checkout the `osc-bel` branch
> 
>     2. Clone the `neovim` repo if you haven't already. In `cmake.deps/deps.txt`, change the value of the `LIBTERMKEY_URL` variable to the path where you checked out the libtermkey fork in step 1
> 
>     3. Run `make distclean` just to be sure we're building everything from scratch. Then run `make deps` and `make` to rebuild Neovim
> 
>     4. Run `VIMRUNTIME=runtime ./build/bin/nvim` and see if the problem persists

Yes, doing this seems to fix an issue. As you already know, your theory is also confirmed by [looking at source](https://git.suckless.org/st/file/st.c.html#l1859).

------

As patching `st` to fix issues locally is generally acceptable, I received an advice on how to do it from a *very* knowledgeable person. Here is the diff of the change (computed for the current latest 0.9 tag): 

```patch
diff --git a/st.c b/st.c
index 62def59..51e57f7 100644
--- a/st.c
+++ b/st.c
@@ -1849,7 +1849,7 @@ osc_color_response(int num, int index, int is_osc4)
                return;
        }

-       n = snprintf(buf, sizeof buf, "\033]%s%d;rgb:%02x%02x/%02x%02x/%02x%02x\007",
+       n = snprintf(buf, sizeof buf, "\033]%s%d;rgb:%02x%02x/%02x%02x/%02x%02x\033\\",
                     is_osc4 ? "4;" : "", num, r, r, g, g, b, b);
        if (n < 0 || n >= sizeof(buf)) {
                fprintf(stderr, "error: %s while printing %s response\n",
```

After adding this patch to my local configuration, everything seems to work just fine.

**Comment by gpanders** [comment]
Thanks @echasnovski.

This issue will be resolved when https://github.com/neovim/libtermkey/pull/4 is applied to libtermkey (either in our own fork, or upstream).

**Comment by gpanders** [comment]
This also happens in Apple's Terminal.app
