### ISSUE TITLE
How to get the result from `:term`? Or get a callback?

### ISSUE THREAD

**Issue by bramblex** [neovim/neovim#2618]
I  use [ranger](https://github.com/hut/ranger) instead of netrw for my exlpore. But it doesn't work well in NewVim. I know that i can use `:term` instead of `:!`, but I cannot get the result form `:term`. How can I solve this problem? And can I get a callback with `:term`? Thanks. :smile: 

[Source Here](https://github.com/bramblex/BlxVimrc/blob/master/utils/file.vimrc)

``` VimL
"https://github.com/bramblex/BlxVimrc/blob/master/utils/file.vimrc

function! s:ChooseFile(dir_path)
    let tmp_file = tempname()
    let path = s:AbsolutePath(a:dir_path)

    silent exec join(['!ranger', path, '--choosefile=' . tmp_file], ' ')
    " => In VIM, it will be blocked here.
    " => If Using `:term` in NeoVim, it would not.
    redraw!

    let result = 0
    if filereadable(tmp_file)
        silent let result = system('cat '. tmp_file)
    endif
    silent call system('rm -rf ' . tmp_file)
    return result
endfunction

```

**Comment by justinmk** [comment]
Callbacks are already implicitly available, because you can use another `nvim` instance to hook into the parent `nvim` instance, since @splinterofchaos's nice PR https://github.com/neovim/neovim/pull/1446

Here's a script to get some ideas: https://gist.github.com/splinterofchaos/1c6c8882e28185a98017#file-nasync-vim-L5

The key is `rpcnotify()`.

**Comment by justinmk** [comment]
`termopen()` takes a `on_stdout` callback (in fact `termopen()` has the same interface as `jobstart()`).

For adding callbacks after a `:terminal` already started, see https://github.com/neovim/neovim/issues/5023
