### ISSUE TITLE
The new default colorscheme causes the background to change during startup

### ISSUE THREAD

**Issue by lewis6991** [neovim/neovim#26372]
### Problem

When Nvim starts up, it is possible for the default colorscheme to be visible before any user colorscheme is loaded. This can result in a very annoying glitch in the colorscheme each time I open Nvim. This wasn't a problem before since the old default colorscheme did not set a background.

https://github.com/neovim/neovim/assets/7904185/6919505e-c09d-49db-b811-452685f556e1

Since I don't plan to use the default colorscheme I consider this a fairly large regression.

### Steps to reproduce

`nvim --clean -u NORC --cmd 'call system(["sleep", "1"])' --cmd 'color vim'`

### Expected behavior

The background should not change as nvim is starting up.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1744+g0d885247

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 14

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

Source

---

One solution is to revert the background color in the new colorscheme so it is not set for `notermguicolors`.

@echasnovski

**Comment by echasnovski** [comment]
I am honestly not sure how this can be solved to have both of these be true:
- Make default color scheme have dedicated background color (even with `notermguicolors`, as it was the requirement).
- Make it not show if redraw is triggered.

Maybe it is better to fix the problem of why it becomes visible before loading custom color scheme (either in core or in setup itself)? I don't think I can register this being the case in my setup.

@justinmk?

**Comment by lewis6991** [comment]
> Make default color scheme have dedicated background color (even with notermguicolors, as it was the requirement).

Why was this a requirement? IMO the opposite should have been a requirement. It is pretty uncommon for any terminal application to set a background color by default.

> Maybe it is better to fix the problem of why it becomes visible before loading custom color scheme (either in core or in setup itself)? I don't think I can register this being the case in my setup.

I don't think the repro can be any simpler. If any part of the config setup runs a system command synchronously then this can happen. I wouldn't be surprised if there were other cases that could cause it as well.

**Comment by echasnovski** [comment]
> Why was this a requirement?

Because otherwise there is no way to actually design a set of colors that can work together with background, i.e. have enough contrast.

**Comment by lewis6991** [comment]
Then maybe (IMO) the colorscheme with `notermguicolors` should have been restricted to colors 0-16. If there is not enough contrast then it is because of the users terminal theme.

If they then want the opinionated set of colours they can enable `termguicolors`.

**Comment by justinmk** [comment]
> Because that will be coherent with the users terminal palette. Only using the 17-255 colors results in a much more jarring experience since it completely deviates away from whatever the user may have configured.

Isn't that separate from the "background flicker" problem?

**Comment by lewis6991** [comment]
Ah yes, sorry, I misinterpreted what you said. So you're advocating to unset the background as per my suggestion?

On a related note, I do think the benefits outweigh the negatives on restricting the noguitermcolors version to only use colors 0-16, but I'll leave that as feedback on the other issue and maybe raise another issue about it.

**Comment by lewis6991** [comment]
That seems more like a rough workaround than a compromise.

**Comment by scy** [comment]
I’d like to add one more facet to this discussion that I didn’t see mentioned yet: For several terminals, having an application use a background color for its whole UI (instead of leaving most of it at the “default” color) breaks terminal _transparency_.

So, as you might know, some terminals allow some degree of transparency, i.e. have whatever window is behind the terminal, or the desktop wallpaper, shine through the terminal window. It’s obviously eyecandy, but quite a few people use it. But: On some (or maybe even most?) of the terminals supporting this, only the “default background color” (i.e. `\e[49m`) gets the special transparency treatment.

For example, here is Neovim running in tmux in WezTerm on Windows. You can see the desktop background image through the terminal, but NeoVim’s status bar, the separate items in the tmux status bar, and even the `'colorcolumn'` are not transparent at all.

![image](https://github.com/neovim/neovim/assets/28629/584ad714-28fb-486c-91d8-0b3e3973b04f)

I’d argue that this is a good thing, because it’s what makes the visual difference between “parts of the terminal are opaque, parts are see-through” vs. “I’ve just uniformly dialed down the opacity of the whole terminal, yolo”.

That being said, I understand both sides here: The one saying “I already _have_ a terminal background color, Vim shouldn’t bring its own”, but also the one saying “we can’t design a good colorscheme without defining the background color on which it is displayed”.

**Comment by echasnovski** [comment]
Thanks, Björn!

**Comment by echasnovski** [comment]
@bfredl, as there is still an issue for the (now default) `termguicolors`, maybe it is a good idea to reopen this with 0.10 milestone so that it is not forgotten?

**Comment by EvanCarroll** [comment]
This is really tacky. My terminal uses a color scheme for everything. It's actually blue. This is what I like. It sucks to have to have the same shade of blue in a vim color scheme. That sounds like the only workaround. It sucks quite a bit too to have these blue bars around neovims tui. If I refuse to find a theme for neovim. This is the only utility that does this and it stands out.

I prefer the old default of not doing this myself. Or perhaps there is a way to get all of the benefits of `termguicolors` while keeping the background transparent?

![Screenshot_2024-06-27_18-13-51](https://github.com/neovim/neovim/assets/19922/e82a0f09-f1f1-43b8-b17d-5c0f8aad7df2)

**Comment by justinmk** [comment]
> I prefer the old default of not doing this myself.

The old default was 256 colors. Just `set notermguicolors` in your config.
