### ISSUE TITLE
The default colorscheme should only pull from the 0-16 terminals colors with `notermguicolors`

### ISSUE THREAD

**Issue by lewis6991** [neovim/neovim#26385]
## Problem

With `notermguicolors` the default colorscheme pulls all its colors from the 17-255. This is a bold change from the old default colorscheme which only uses the [0-15 ansi colors](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors). The benefit this had was that it used whatever color palette was defined in the terminal, and thus whatever the user configures themselves. Now the new default colorscheme is quite jaring and completely deviates from the colors used in the terminal.

Note I think it's good to distinguish the two components of a colorscheme which often get conflated:
1. The palette. The actual values for each color, e.g. What is red, blue, etc.
2. How the palette is used.

This issue only wishes to change how palette is determined with `notermguicolors`, not how it is used.

Also note, I believe the old default colorscheme only had issues with 2 which #26334 addresses very well.

## Proposal

The current color palette almost falls into the 16 color space, however it contains 20 colors as it uses 8 colors for gray.

```
Dark:
blue    = "#005078"
cyan    = "#007676"
green   = "#015825"
grey1   = "#0a0b10"
grey2   = "#1c1d23"
grey3   = "#2c2e33"
grey4   = "#4f5258"
magenta = "#4c0049"
red     = "#5e0009"
yellow  = "#6e5600"

Light:
blue    = "#9fd8ff"
cyan    = "#83efef"
green   = "#aaedb7"
grey1   = "#ebeef5"
grey2   = "#d7dae1"
grey3   = "#c4c6cd"
grey4   = "#9b9ea4"
magenta = "#ffc3fa"
red     = "#ffbcb5"
yellow  = "#f4d88c"
```

Therefore we should be able to rework the colorscheme to only use the `cterm0-15` colors and provide a terminal configuration for users who wish use the new Nvim palette. Since the palette requires 4 additional colors either:
- pull these from the 17-255 space.
- merge these shades of grey into white, black, "dark white" and "bright black".

## Other points:
- The current `notermguicolors` differs quite a bit to the `termguicolors` version. If instead we use
the 0-15 space and provide a terminal configuration, then it is possible for the `notermguicolors` version
to much more closely match the `termguicolors` version. If the user wishes.
  - This will be useful for anyone who SSH's into machines that have Neovim but not their default config and/or without the correct terminfo to enable truecolor.
- The 256 color set is not usually configurable in terminals.
   - Wezterm **does allow** defining the full 256 range via OSC escape sequences: https://wezfurlong.org/wezterm/escape-sequences.html#operating-system-command-sequences
- Defining a background will change/disrupt any setups who use transparent terminals.

**Comment by echasnovski** [comment]
> Therefore we should be able to rework the colorscheme to only use the `cterm0-15` colors and provide a terminal configuration for users who wish use the new Nvim palette. Since the palette requires 4 additional colors either:
> 
>     * pull these from the 17-255 space.
> 
>     * merge these shades of grey into white, black, "dark white" and "bright black".

Unfortunately, non of these approaches are fully possible. For text foreground (red, green, yellow, blue, magenta, cyan) - yes, it is a matter of straightforward replacement, as those correspond to terminal colors (with intent of compatibility, as it is).

When it comes to text background it is a bit less straightforward, as it needs to be different from what is used in the foreground (or it will lead to no text at all). So such highlight groups should only have non-colored foreground. I think it is already the case in default, but not entirely sure.

The most problematic is indeed 4 additional grey colors. They define how UI looks. Pulling these from 16-255 space will not lead to entirely usable palette, as those can equal to some of user's 0-15.

Merging shades into 0, 7, 8, 15 will also result into not really usable palette as there needs to be shade distinctions in the following levels: NormalFloat - Normal (bg) - CursorLine and Pmenu - Visual - Comment - StatusLineNC - Normal (fg). Those are not really possible to merge into 4 shades and still have a usable UI (I tried). The only route I could find is to go Vim's one: underlined `CursorLine`, reverse `Visual`, magenta `Pmenu` and `NormalFloat`. I would advise against that.

------

I know the next question might sound a bit snarky, but I assure you it is not. Why the 16 colors? Why not 8 colors, as I am sure there are only 8 colors terminals out there.

**Comment by justinmk** [comment]
Sensing a no-win situation. The way we deal with this kind of "terminal-tradition hell" is to declare bankruptcy and focus on the common case.

- If there are some small low-risk tweaks we can make to improve the 16-color situation, fine. 
- But we don't need to fully support 16-color, as long as it "readable". 
- People who care about that can use `:colors vim` since their palettes probably already map to that.

> This will be useful for anyone who SSH's into machines that have Neovim but not their default config and/or without the correct terminfo to enable truecolor.

'termguicolors' forces RGB, terminfo is ignored: https://github.com/neovim/neovim/blob/66f1563c7a48d76f99c89e32de030e57af2abfb4/src/nvim/tui/tui.c#L673

**Comment by echasnovski** [comment]
> Sensing a no-win situation. The way we deal with this kind of "terminal-tradition hell" is to declare bankruptcy and focus on the common case.
> 
>     * If there are some small low-risk tweaks we can make to improve the 16-color situation, fine.
> 
>     * But we don't need to fully support 16-color, as long as it "readable".
> 
>     * People who care about full 16-color fidelity can use `:colors vim`.

The best approach I can think of is to replace red, green, and cyan in `ctermfg` with 1, 2, and 6. But having this small of a change doesn't look as being worth it.

------

> The background usually always matches or is close to color 0, or, is distinct from all other colors in the 0-15 space. I don't think this was really an issue with the default scheme?

I meant colored background, like `Diff*`, `Search`, etc.

------

> We could go 8, however I think 16 covers 99.9% of use cases and is much easier to achieve a compromised solution. Though if we can make 8 work then that would be ok with me.

And with 256 colors it is about 95%? Not sure where to find the actual numbers. [Here](https://fedoraproject.org/wiki/Features/256_Color_Terminals#Terminal_256_color_support_list) is one list, but it is far from being full in "Supports 256 colors" and a bit outdated or misleading in "Doesn't support 256 colors"

**Comment by tomtomjhj** [comment]
> If we could detect these situations

`t_Co`?
https://github.com/neovim/neovim/blob/66f1563c7a48d76f99c89e32de030e57af2abfb4/src/nvim/tui/tui.c#L358-L359

Old default colorscheme uses colors outside 0-15 if t_Co is bigger.

https://github.com/neovim/neovim/blob/66f1563c7a48d76f99c89e32de030e57af2abfb4/src/nvim/highlight_group.c#L821-L855

**Comment by craigmac** [comment]
From a branding perspective, using 16-255 colour indexes gives us much closer fidelity to the official colorscheme. Relying on the user-set 0-15 indexes is risky, and I think it will result in more bug reports. Neovim already assumes 256 colors, so let's assume 16-255 indexes are usable as well.

**Comment by clason** [comment]
No, this has been discussed and decided on. Truecolor is the official colorscheme (and now the default out-of-the-box experience, if possible). Non-termguicolors is a fallback to _terminal_ colors, which means the lowest (reasonable) common denominator.

**Comment by craigmac** [comment]
> No, this has been discussed and decided on. Truecolor is the official colorscheme (and now the default out-of-the-box experience, if possible). Non-termguicolors is a fallback to terminal colors, which means the lowest (reasonable) common denominator.

Maybe I'm reading your response wrong, but I'm not sure what you're saying 'no' to? Termguicolors is the official, yes I agree. What I'm arguing is the fallback (notermguicolors) should preferably be chosen from 16-255 colors, because neovim assumes t_Co = 256 by default so we should make use of that range instead of strictly 0-15 colour indexes

**Comment by gpanders** [comment]
@craigmac Using 16-255 gets us closer to the "true" colorscheme, but offers a worse user experience, as described in this issue and elsewhere (see https://github.com/neovim/neovim/pull/26389).

**Comment by tomtomjhj** [comment]
If `t_Co=256`, vim's default colorscheme uses colors from 16-255 as I mentioned above. In vim, you can make vim strictly adhere to the terminal's 16 colors by `set t_Co=16`. Try it. The problem with nvim is that it doesn't allow setting t_Co (https://github.com/neovim/neovim/issues/11974). 

So I propose three points
* allow setting t_Co
* make 256 colors variant of the default colorscheme mimic the gui version
* have a 16 colors fallback variant of the default colorscheme (e.g., using `lookup_color`) for the cases when the terminal doesn't support 256 colors or when the user just wants it

**Comment by craigmac** [comment]
@gpanders:
> but offers a worse user experience

My experience has been the opposite, if it's designed using the 17-255 indexes, it will be more consistent across any terminal emulator without termguicolors, without having to tweak your 0-15 palette, as @echasnovski also mentions in the linked issue.

@tomtomjhj:
> allow setting t_Co

Let's not go there again, I think removing the ability to manipulate this option was a good move by the project.

**Comment by clason** [comment]
> What I'm arguing is the fallback (notermguicolors) should preferably be chosen from 16-255 color

That's what I'm saying "no" to. If you want colors, use (the default) `termguicolors`. If you `set notermguicolors`, you opt in to terminal colors. This is the best compromise between the conflicting demands that have been raised, and easiest to reason about.

I'm sorry if that is not your preference, but the default colorscheme is one instance where executive decisions have to be made.

**Comment by echasnovski** [comment]
> My experience has been the opposite, if it's designed using the 17-255 indexes, it will be more consistent across any terminal emulator without termguicolors, without having to tweak your 0-15 palette, as @echasnovski also mentions in the linked issue.

As I've been mentioned here, here are my general thoughts.

Having a unified colors is important (for me) in two cases:
- With enabled `termguicolors`, as it is what most users end up using.
- With `nvim --clean`, as it is what most of **new** users see.

Initial new color scheme PR had that those two cases are both `termguicolors` and `notermguicolors`, hence the push for 16-255 to be used with `notgc`.

Several days after merging the PR, `termguicolors` became a default (if terminal emulator supports it) and virtually two of those cases squished into single `tgc` case. Which colors should be used for `notgc` is more a matter of preference and executive decision.

I personally probably still prefer using 16-255. But as a default color scheme to be used by broader audience, having `notgc` viewed as somewhat intentional choice to not use `tgc` results into colors 0-15 being more organic. So they are proposed in the new iteration of color scheme (#26540).

**Comment by tomtomjhj** [comment]
> Let's not go there again, I think removing the ability to manipulate this option was a good move by the project.

But why was it removed? It survived the initial removal of t_xx options (https://github.com/neovim/neovim/commit/3baba1e7bc6698e6bc9f1d37fce88b30d6274bc9), and then later removed because it "has never worked" and "should not have worked" (https://github.com/neovim/neovim/commit/944e3c06193f6d10baa9ba3021e01626337dd884) despite the fact that it was possible to set/get t_Co value and `lookup_colors` does use this value to make default colorscheme utilize 256 colors when available and fallback to 16 when it's not. I don't know how it actually behaved at that time, so please let me know. cc @justinmk. 

If t_Co is revived (and assuming that it works), it's a win-win.
* Users who want uniform terminal colorscheme experience can set t_Co=16, which is a marginal addition to set notgc already necessitated due to tgc now being default when available.
* Users who use terminals without tgc support can have better colorscheme by default.
* Users who use terminals without 256 colors support also gets good-ish 16 color colorscheme by default.

If t_Co is technically possible, what needs to be decided is whether achieving this win-win situation outweighs the complexity of maintaining t_Co option and implementing the fallback for the default colorscheme.
