### ISSUE TITLE
Error E1509 when I write a file that is a symbolic link

### ISSUE THREAD

**Issue by gmr458** [neovim/neovim#26473]
### Problem

![20231208_11h29m37s_grim](https://github.com/neovim/neovim/assets/53343401/456cfb4a-3ddb-4cf9-808f-8b7af6e93b2c)

### Steps to reproduce

This happens without plugins and without a configuration file.

Create a example file:
`touch example.txt`

Create a symbolic link of the example file:
`ln -s example.txt example_link.txt`

Open the symbolic link:
`nvim example_link.txt`

Execute `:w`

### Expected behavior

Since there are no problems saving the changes to the file, the expected behavior is that there is no error message.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2289ca2 Build type: Release LuaJIT 2.1.1700008891

### Vim (not Nvim) behaves the same?

no, vim 9.0.2120

### Operating system/version

Fedora 38

### Terminal name/version

alacritty 0.12.3

### $TERM environment variable

alacritty

### Installation

build from source

**Comment by zeertzjq** [comment]
What file system does these two files reside on?

**Comment by gmr458** [comment]
btrfs

**Comment by gmr458** [comment]
I did the steps to reproduce in Ubuntu WSL and I didn't get any errors.

**Comment by gmr458** [comment]
@pabloariasal The stable version should not have this problem, when I used the stable version I did not have any problem.

**Comment by martini97** [comment]
I'm running on btrfs on fedora 39 and I get the same error when saving symbolic links
```
NVIM v0.10.0-dev-1816+g2d33a766a
Build type: Release
LuaJIT 2.1.1702233742
```

**Comment by markmartirosian** [comment]
Seeing the same issue on Fedora Linux 39, saving any file.

```
NVIM v0.10.0-dev-1cf51a07a
Build type: Release
LuaJIT 2.1.1702233742
```

**Comment by jorden789** [comment]
Throwing a comment here to say I am also facing this issue.

File in question I attempt to write:
`nvim ~/.zshrc`

This is a symlink:
```
jallcock@fedora ansible $ ls -lrtha ~/.zshrc
lrwxrwxrwx. 1 jallcock jallcock 62 Jan  5 15:26 /home/jallcock/.zshrc -> /home/jallcock/Documents/development/git-repos/dotfiles/.zshrc
```

Running on Fedora 39 - Kernel Version 6.6.9-200.fc39.x86_64.

It is worth noting that when I edit the file itself and don't use the symlink reference, I don't get the issue.

**Comment by jpmorris** [comment]
Getting this error with 10.0 but, strangely, only with Unraid nfs mounts.  It was working for me before (does work with nvim 9.2 (or vim/nano) and local or other nfs mounts).  This may be an edge case not resolved? Not sure how to debug this further.  Are there commands I can run to test/isolate that this is actually nvim (I assume so unless unraid really did something wrong).

**Comment by Maerzig** [comment]
> Getting this error with 10.0 but, strangely, only with Unraid nfs mounts. It was working for me before (does work with nvim 9.2 (or vim/nano) and local or other nfs mounts). This may be an edge case not resolved? Not sure how to debug this further. Are there commands I can run to test/isolate that this is actually nvim (I assume so unless unraid really did something wrong).
> 
> Confirmed also works with 9.5

I'm having this exact problem as well on 10.1. No problem with vim or locally on the server. Seems to be a problem specifically with nvim and NFS shares combined. Have you found out anything new on this? @jpmorris

**Comment by jpmorris** [comment]
@Maerzig  which I had something more substantive to tell you but mine seemed to have resolved itself (not even exactly sure how).  What I would suggest is to do divide-and-conquer debugging:  Start turning things off until it works.  Try:

- rename your `~/config/nvim` (or equivalent) to make sure your'e starting completely clean
- turn off any sync tools if you have them running (I had `syncthing` writing to this nfs directory too)
- try a different nvim version?
- `chmod/chown` your different directories/files and see if the permission bits make a different
- try NFS from another machine? 
- try to do a manual NFS mount with different options at a different mountpoint

This issue may have been affecting my vscode-neovim plugin so that also added to the confusion of what I did to fix it. Sorry I can't be of more help.

**Comment by Maerzig** [comment]
Thank you for the quick answer!
I've already more or less tried all of those and the only one that seems to get rid of the error is just downgrading to 9.5. I suppose that's what I'll stick with for a while and hope that a future version will fix this for me since I'm a bit out of my depth on finding the actual problem myself. Not that it seemed to cause all that many problems beyond just having the annoying error message on writing to a file.
