### ISSUE TITLE
`insertTextMode` is not nullable

### ISSUE THREAD

**Issue by michaelpj** [neovim/neovim#26636]
### Problem

Neovim is sending `null` for `insertTextMode`, but this is not legal. Per the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem), `insertTextMode` is optional but not nullable.

Discovered [here](https://github.com/haskell/haskell-language-server/issues/3842). The Haskell Language Server is quite strict about spec compliance, so it fails here.

### Steps to reproduce using "nvim -u minimal_init.lua"

I don't know, I don't use neovim.

### Neovim version (nvim -v)

I don't know, the reporter didn't specify

### Language server name/version

I don't know, the reporter didn't specify

### Operating system/version

Arch Linux

**Comment by mfussenegger** [comment]
Assuming you're talking of the `CompletionClientCapabilities `, the property is marked as optional:

```
	/**
	 * The client's default when the completion item doesn't provide a
	 * `insertTextMode` property.
	 *
	 * @since 3.17.0
	 */
	insertTextMode?: InsertTextMode;
```


If you're talking of the `CompletionItem`, then I don't understand because that's send from the server to the client?

Neovim also doesn't announce that it supports it (`insertTextModeSupport` is not set)

This seems like a haskell-language-server issue to me?


https://github.com/haskell/haskell-language-server/issues/3842 also mentions `completionItem/resolve` - that's currently not implemented in neovim core, but must be coming from a plugin.

**Comment by michaelpj** [comment]
It's optional (you can omit it from the object) but you can't send it as null. 

I think this may have occurred during a completion resolve workflow, so possibly the issue is in processing the `CompletionItem` that HLS sends before sending it back to be resolved.

I'm fairly sure it's not HLS since we don't have this issue with any other client. I'll double check our encoding, though.

**Comment by clason** [comment]
Just to be clear (since you are not familiar with Neovim): `nvim_coq` is an external plugin and not bound by our implementation of the protocol (which we, like HLS, are very strict about).

You (or rather the user) should report this issue at https://github.com/ms-jpq/coq_nvim.

**Comment by michaelpj** [comment]
Oh I see. Your comment about resolve should have tipped me off. Thanks for the pointer, sorry about the noise!

**Comment by clason** [comment]
No worries, the ecosystem can be hard to keep track of!
