### ISSUE TITLE
Adding tmux-like session management

### ISSUE THREAD

**Issue by addisonamiri** [neovim/neovim#2706]
This is clearly an enhancement for some future release but at least two people think it would be nice to incorporate a few of tmux's session management features into neovim now that it supports a terminal. Things like attaching and detaching terminals were discussed in [this](https://www.reddit.com/r/neovim/comments/36gq5o/neovim_terminal_supports_w3mimgdisplay/crdw81l) comment thread on reddit. If there was more support for this it'd be nice to see in a post-stable release.

**Comment by Pyrohh** [comment]
Assuming you mean to integrate such functionality into the nvim core, I think it would be a waste of time. `dtach`, `abduco`, and of course `tmux` already work very well for this, so I think the "correct" route would be to better integrate those programs. For example, we could have a small `abduco` provider which nvim calls out to, similar to what's done with the clipboard provider.

**Comment by Pyrohh** [comment]
"waste of time" is maybe too general, so sorry if I came off as brash. I just don't like the idea of introducing what would most likely be a decent amount of complexity (and bugs), especially since other programs already do it.

**Comment by addisonamiri** [comment]
No problem. I definitely understand what you're saying. If there's a provider interface would it be possible to have a plugin that implements these? I don't think most of tmux's features would be used so most of it seems unnecessary. If simple plugin could implement this I think it'd be preferred.

**Comment by Pyrohh** [comment]
> If there's a provider interface would it be possible to have a plugin that implements these?

Maybe provider was the wrong word... I suppose I meant a bundled plugin -- but yes, I don't see much reason why we couldn't just wrap the aforementioned programs.

**Comment by tarruda** [comment]
> This is clearly an enhancement for some future release but at least two people think it would be nice to incorporate a few of tmux's session management features into neovim now that it supports a terminal. 

This is not so far in the future as you think, I already have been planning to implement something like this in the near future, once more urgent problems are fixed(#2371).

Most infrastructure to support this feature is already implemented, in fact you can already detach/reattach to headless nvim instances using pynvim, we just need to bring this functionality to the core.

Here's an idea of what I had in mind:

- a new "remote mode" where all keys except one combo(to detach) are sent to a remote nvim instance, and the client screen will mirror the remote nvim..
- a `rpcconnect()` vimscript function that takes the address of another nvim instance. This function returns a channel id representing the msgpack-rpc connection to the remote nvim.
- a `rpcattach()` vimscript function that takes a channel id, calls `ui_attach` and switches to remote mode. This function only returns when detaching, which can be triggered by some key combination(remappable in a separate namespace since this another mode)

Upon these base functions, very complex session managers could be built using pure vimscript.
Also, implementing this as vimscript functions would allow this feature to be reused by any third party UI.

> "waste of time" is maybe too general, so sorry if I came off as brash. I just don't like the idea of introducing what would most likely be a decent amount of complexity (and bugs), especially since other programs already do it.

As I said, the infrastructure for this(msgpack-rpc, remote UIs) is already implemented, we simply need to expose it in a flexible way that will allow connecting and controlling remote nvim instances interactively.

Besides, the programs you suggested only work in the terminal. While there are alternatives such as xpra for detaching from graphical progams, they don't work well in windows(can't detach from a nvim instance running on a windows machine), so it would be good to have a nvim-native solution to the problem.

**Comment by splinterofchaos** [comment]
> a new "remote mode" where all keys except one combo(to detach) are sent to a remote nvim instance, and the client screen will mirror the remote nvim..

Would we have an instance running with `--embed` as a daemon such that multiple instances could attach to it? I had a thought like this a bit ago, but I wasn't sure how the state of the non-remote instance (running in "remote mode"?) would manage its state. But if it's just a graphical front end, then maybe we could set up an entirely different code path for it, skip initializing modules like `eval.c` or re-sourcing the vimrc, and improve startup time.

If I understand correctly, I think this would be a good thing even though I have no interest in session management.

We'd also need a way to destroy the remote instance. Maybe the daemon could exit when all channels have closed. The idea of having an instance running, but not attached to a UI and having no open channels, leaving it in a zombie state, is what worries me most about ideas like this.

Also, if we have two clients connect to a remote instance, and one sourced some vimscript implementing an infinite loop, wouldn't the other freeze, too? How do we protect against one instance hogging all the resources, or do we just not worry about it since either could send `Ctrl+C`?

> a rpcconnect() vimscript function that takes the address of another nvim instance. This function returns a channel id representing the msgpack-rpc connection to the remote nvim.

Abstract of this issue, we do have a need for such a function, but more generically, to attach to existing sockets/pipes for clients that start before nvim and don't launch it themselves, perhaps because they run as daemons. 

Also, a similar function for reading from pipes not encoded with msgpack. (Imagine a small program that called `mkfifo()` and printed to it once every ten seconds.)

**Comment by tarruda** [comment]
> Would we have an instance running with --embed as a daemon such that multiple instances could attach to it? 

Not necessarily, note that I have said nothing about how the sessions are created, just how to connect with them. One could first call rpcstart with --embed and then connect to it, another option is to invoke the ssh command to start nvim in a server and connect the remote socket to a local port.

> I had a thought like this a bit ago, but I wasn't sure how the state of the non-remote instance (running in "remote mode"?) would manage its state. But if it's just a graphical front end, then maybe we could set up an entirely different code path for it, skip initializing modules like eval.c or re-sourcing the vimrc, and improve startup time.

When in remote mode it is just a graphical front end, but one can detach and continue working locally, or select another session. Local plugins can still be running while connected(though I don't see any use cases for this right now, it could be useful to have this flexibility)

> We'd also need a way to destroy the remote instance. Maybe the daemon could exit when all channels have closed. The idea of having an instance running, but not attached to a UI and having no open channels, leaving it in a zombie state, is what worries me most about ideas like this.

This highly depends on how the session was started. In any case, this is better to delegate to the vimscript land, where we can have most flexibility.

> Also, if we have two clients connect to a remote instance, and one sourced some vimscript implementing an infinite loop, wouldn't the other freeze, too? How do we protect against one instance hogging all the resources, or do we just not worry about it since either could send Ctrl+C?

It would only freeze updates to the remote UI, keys still pass through the local instance and are forwarded to the remote. The only exception should be a single key combo that can be used to detach and exit remote mode, so it's not a problem if the remote end freezes, detaching would simply restore the local UI.

> Abstract of this issue, we do have a need for such a function, but more generically, to attach to existing sockets/pipes for clients that start before nvim and don't launch it themselves, perhaps because they run as daemons.

Agreed, though this is more useful in the case of attaching to remote UI(at least for now, it doesn't make sense to me the idea of attaching to a long running plugin when one can simply spawn it with `rpcstart`)

> Also, a similar function for reading from pipes not encoded with msgpack. (Imagine a small program that called mkfifo() and printed to it once every ten seconds.)

We already have `jobstart(['cat', '/path/to/fifo'])` for that :smile:

**Comment by addisonamiri** [comment]
Just to clarify, when you say vimscript do you mean vimscript or lua? I was under the assumption that when the lua interpreter (and vimscript translator) was completed it would be the preferred way of writing plugins as the conversion wouldn't take place speeding up the process. Either way this is pretty exciting.

**Comment by splinterofchaos** [comment]
> Just to clarify, when you say vimscript do you mean vimscript or lua?

vimscript isn't going away, and lua won't be the only choice. With the remote API, one can write a plugin in any language.

**Comment by cablehead** [comment]
I've been experimenting with replacing my use of tmux with neovim. Just checking on where the state of this suggestion is at the moment?

**Comment by markmontymark** [comment]
I'm 2 weeks off of tmux, using a nvim process as a terminal manager (aka, buffer list is just a bunch of :terminal buffers), and in each terminal buffer, I run nvim.  I create a sense of "outer nvim", the terminal manager vs "inner nvim", 

This is highly tied to my own personal workflow or dev style and very much not suitable for general use.

https://github.com/markmontymark/dotfiles/tree/master/nvim

Relevant files in a modules/ directory:

Sets up an $IN_NVIM env var , if $IN_NVIM had not been set, then this is outer nvim, else, we are in an outer nvim terminal buffer that is running nvim.
https://github.com/markmontymark/dotfiles/blob/master/nvim/modules/05-pre-plugin-load.vim

then this bit creates a vsplit terminal buffer to run 'npm run m', which is a npm run-script I set up in all my projects to 'make'
https://github.com/markmontymark/dotfiles/blob/master/nvim/modules/30-mappings.vim#L101-L134
It's mapped to ```<leader>m```

**Comment by cablehead** [comment]
@markmontymark thanks for the description. using neovim this way is super interesting. are you able to detach and re-attach to your setup?

**Comment by markmontymark** [comment]
@cablehead 
No, sorry, I read "tmux", got excited about how I don't use it for local dev now(was using each tmux window as a project of panes) and skipped over this is about "session mgmt".  For now I would still use tmux for keeping my remote sessions going when I stop coding for the day.

**Comment by Shougo** [comment]
Similar neovim plugin is here.
https://github.com/brettanomyces/nvim-terminus

**Comment by justinmk** [comment]
Merging this with https://github.com/neovim/neovim/issues/5035.
