### ISSUE TITLE
Function names highlight support.

### ISSUE THREAD

**Issue by TotalKrill** [neovim/neovim#2713]
Neovim should support highlighting function names for easier usage in graphical interfaces and colorschemes. Meaning that the default syntax handlers should include this. This has been a problem for c languages in vim.

**Comment by splinterofchaos** [comment]
Identifying "function names" means semantic parsing, and that's a little outside the scope of vim's (and transitively nvim's) strategy for dealing with syntax. I think it would be best to write an external client that tells nvim how to highlight a file rather than adding this behaviour by default. Especially considering that some languages should be parsed/interpreted differently.

On a side note, https://github.com/justinmk/vim-syntax-extra does parse for `function(...)` and will highlight `function` differently, but then if you pass a function pointer, the pointer doesn't get highlighted. That's what I mean by semantic parsing, because otherwise we could just adopt more comprehensive syntax files.

**Comment by splinterofchaos** [comment]
See also: #719

**Comment by justinmk** [comment]
This is covered by #719. Scintillua remains the most intriguing option.
