### ISSUE TITLE
Add `vim.format` to replace `vim.fn.printf`

### ISSUE THREAD

**Issue by alexmozaidze** [neovim/neovim#27174]
### Problem

As I've noted [here](https://github.com/neovim/neovim/issues/18393#issuecomment-1907827221), `string.format` does not support positional arguments, whereas `vim.fn.printf` does. This is an issue when an argument `N` must be re-used many times in a format string; `string.format` just doesn't cut it.

### Expected behavior

Add `vim.format` that would support everything `vim.fn.printf` is capable of.

**Comment by clason** [comment]
I don't think that's a compelling argument for adding yet another API. `vim.fn.*` _is_ part of the Lua API, so that would just be filling empty checkboxes for no perceivable practical gain. Native Lua APIs are added when there is a significant demonstrable benefit in performance (avoiding marshaling non-native types) or flexibility (composability of other Lua APIs such as LSP or treesitter). None of those apply here, as far as I can tell.

**Comment by lewis6991** [comment]
Agree, I don't think this is worth adding at all. `string.format` is good enough for 99.9% of use cases and we don't need to implement another function to cover the 0.1% when there are answers on the internet to implement this in Lua.

**Comment by alexmozaidze** [comment]
Fair enough. `printf` is just such a misleading name, even an alias like `format` would be nice.

**Comment by LunarLambda** [comment]
> Fair enough. `printf` is just such a misleading name, even an alias like `format` would be nice.

FWIW You *can* just write `vim.fn.format = vim.fn.printf` in your `init.lua` or some such.
