### ISSUE TITLE
[RFC] How to handle auxiliary files when migrating legacy tests.

### ISSUE THREAD

**Issue by lucc** [neovim/neovim#2722]
I have started to migrate several legacy test and some of them are accompained by auxiliary files besides the obvious `src/nvim/testdir/testXX.{in,ok}`.

Here is a list of things that I have found and solutions/steps I have taken to make the tests run. Please feel free to comment on these or suggest more approaches.  Or there might be cases I have not seen yet or forgotten.

* Some tests need an `autoload` directory. I have created it at `test/functional/legacy/sautest/autoload` and then `set rtp+=test/functional/legacy/sautest` inside the test. An example is test 60, see #2721 or test 55 (will create the PR soon).
* Some tests need data, tags or spell files. They need to be in encodings other than utf8 in some cases. One idea is to create the files at runtime with lua's file io. This involves some quoting of strange bytes. I have tried this with test 83, see #2710.
* Some tests might need a viminfo file. As far as I could learn in #2585 when migrating test 74 this is not easily possible. I was told that I need to start a custom session (without the `-i NONE` command line flag) but was not yet able to achieve this.
* Test 60 also sources a script `test60.vim` which I have moved to `test/functional/legacy` directly.

After some discussion about the `execute()` and `source()` functions in the `helpers.lua` file I understand that in the last point the extra file might be dispensable (it is used to test the `exists()` function with script-local variables) and can be replaced by a call to `source()`.

Two oposing ideas insipire me to vote for the use of auxiliary files stored in the git repository or the writing of files at runtime and storing data in the main test file, respectively:

1. cleanlyness and readablity:  Long sequences of `execute()` commands in the test file are adding a lot of overhead (also for the human reader).  They are also harder to indent nicely.  `source()` calls with big strings mess up the syntax highlighting at some point (and they are highlighted as lua string in the best case, never as vim code).  Also string escaping and encoding issus have to be taken care of if files are written from lua strings.  So it might be desireable to wirte some code/data out into seperated files that can be sourced/used.
2. standalone files: If on the other hand all needed auxiliary files can be created at runtime one test case can be fully contained in the lua test file. So it might be desireable to remove some aux files and write them at runtime from within the lua test file.

**Comment by fwalch** [comment]
Thanks for writing this up.

Frankly, the readability is horrendous for most of the legacy tests anyway, so we don't need to be concerned with that too much. The most important point with the legacy tests is probably that they can be easily updated when they are changed in upstream Vim.

I'm more in favor of keeping everything in one Lua test file, but I can see how having files with strange encodings stored in the repo instead of writing them at runtime can be an advantage.. so, I'm a bit torn.

**Comment by justinmk** [comment]
> Some tests need an autoload directory. I have created it at test/functional/legacy/sautest/autoload

Any "prop" object AFAIK is usually called a "test fixture". There is a `test/functional/fixtures/autload/` directory that exists, for a similar purpose. It's better if we keep these props in one place so that it is clear which paths contain tests and which don't.

> I was told that I need to start a custom session (without the -i NONE command line flag) but was not yet able to achieve this.

See my comment on #2585.

> Test 60 also sources a script test60.vim which I have moved to test/functional/legacy directly.

Unless test60.vim is large, it's preferable to ensconce it in the test and write it out at runtime. See [helpers.lua:source()](https://github.com/neovim/neovim/blob/master/test/functional/helpers.lua#L209-L217) implementation for a way to do this.

> it might be desireable to remove some aux files and write them at runtime from within the lua test file.

:+1:

**Comment by justinmk** [comment]
> source() calls with big strings mess up the syntax highlighting at some point

@lucc You can fix this by calling  `:syntax sync fromstart`. Not sure if there is a way to set that to "always on" for a given buffer (other than an autocmd).

**Comment by lucc** [comment]
>>it might be desireable to remove some aux files and write them at runtime from within the lua test file.

>:+1: 

Should I open a PR to add [this function](https://github.com/lucc/neovim/blob/test83/test/functional/legacy/083_tag_search_with_file_encoding_spec.lua#L7-L12) to helpers.lua?

**Comment by justinmk** [comment]
@lucc sure
