### ISSUE TITLE
`Ctrl-^` (`alternate-file` buffer) behaves unintuitively when deleting buffers

### ISSUE THREAD

**Issue by Maltimore** [neovim/neovim#27286]
### Problem

This issue is similar to https://github.com/neovim/neovim/issues/25365, but for the `alternate-file`. I previously opened this as a "feature request" issue but was told it fits more the "bug report" issue.

It often happens that when deleting a buffer (with `:bd`), say `file1`, that buffer is just unlisted and "invisibly" stays the `alternate-file` for another buffer `file2`. When `file2` is active, pressing `Ctrl-^` will make neovim attempt to re-open `file1`.

Problems:
- some buffers can't be reloaded
- typically, a buffer was deleted for a reason, so it's unlikely that someone would use the `Ctrl-^` command with the intention to reload that buffer (although in certain scenarios this could be a valid use case)

If instead one doesn't just delete the buffer, but wipes it with `:bw`, then doing `Ctrl-^` as above, one gets the error "E23: No alternate file".

### Steps to reproduce

`nvim --clean file1`
`:e file2`
`:e file3`
Now, `file3` is active, and `file2` is the `alternate-file`.
`:bd2` to close `file2`, and the active buffer is still `file3`.
press `Ctrl-^`
Now, `file2` is loaded again even though it was just deleted.

### Expected behavior

I believe that for most use-cases, it would be practical that when deleting/wiping a buffer, another buffer predictably becomes the alternate buffer. The most obvious candidate would be closest other listed buffer in the `jumplist`.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2250+g6bba4bece

### Vim (not Nvim) behaves the same?

no, vim 8.2

### Operating system/version

Ubuntu 22.04

### Terminal name/version

konsole 23.08.4

### $TERM environment variable

tmux-256color

### Installation

appimage (nightly)

**Comment by zeertzjq** [comment]
> I believe that for most use-cases, it would be practical that when deleting/wiping a buffer, another buffer predictably becomes the alternate buffer. The most obvious candidate would be closest other listed buffer in the `jumplist`.

I don't think this makes sense. Alternate file is not jumplist and there is no such thing as "another buffer predictably becomes the alternate buffer".

**Comment by craigmac** [comment]
This is how it's supposed to work, and does work like that on Vim 9.1.

**Comment by Maltimore** [comment]
It is true that vim works the same way, but I didn't see this behavior of reloading deleted buffers documented, neither at the docs for `Ctrl-^` nor `alternate-file`.
So AFAICT, this is undocumented behavior that also doesn't make much sense (especially trying to load non-loadable ephemeral buffers!). Even if my proposed solution is not liked, I think the issue itself persists.

**Comment by gpanders** [comment]
@Maltimore You might be able to script something that does what you want by combining a `BufDelete` autocommand and setting the `@#` register. But I don't think the default behavior here is going to change. Some people like and want this behavior and may depend on it (seeing as it's been around since the beginning).

**Comment by Maltimore** [comment]
Thanks @gpanders! I'll see if I can come up with something and post it here if so, so others who find this issue can use it as well.

**Comment by alfariiizi** [comment]
I use alternate file a lot. In order to open recent active buffer, I do this:

## Code

```lua
-- Initialize the buffer history table
local buffer_history = {}

-- Function to update buffer history
local function update_buffer_history()
  local current_buf = vim.api.nvim_get_current_buf()
  -- Remove current buffer if it's already in the history to prevent duplicates
  for i, buf in ipairs(buffer_history) do
    if buf == current_buf then
      table.remove(buffer_history, i)
      break
    end
  end
  -- Insert current buffer at the start of the list
  table.insert(buffer_history, 1, current_buf)
end

-- Attach the update function to the BufEnter event
vim.api.nvim_create_autocmd('BufEnter', {
  callback = update_buffer_history,
})

-- Function to switch to the last available buffer
local function switch_to_last_available_buffer()
  local current_buf = vim.api.nvim_get_current_buf()
  for i = 2, #buffer_history do
    local buf = buffer_history[i]
    if vim.api.nvim_buf_is_loaded(buf) and buf ~= current_buf then
      vim.api.nvim_set_current_buf(buf)
      return
    end
  end
  print 'No suitable alternate buffer found'
end

-- Map Ctrl-^ to the new function using Lua
vim.keymap.set('n', '<C-^>', '', { noremap = true, callback = switch_to_last_available_buffer })
```

## Explanation:

- Global Buffer History: When Neovim starts, it initializes a global list `g:buffer_history` to track buffers based on your usage.
- Update Logic: Every time you enter a buffer, it's added to the front of this list, ensuring the most recently used buffer is always at the front, after the current one.
- Switching Function: `SwitchToLastAvailableBuffer` checks this list to find the first buffer that is still open (and not the current buffer) to switch to.
- Mapping: It remaps `Ctrl-^` to use this new function, overriding the default behavior that can lead to attempting to switch to a closed buffer.

---

Maybe this approach is not that beautiful, but for me it get the job done.
