### ISSUE TITLE
Lua types for vim.fn.bufnr and vim.fn.bufname shouldn't be integer

### ISSUE THREAD

**Issue by srcrip** [neovim/neovim#27444]
### Problem

These actually take strings and integers

### Expected behavior

and so I think it should reflect that

**Comment by wookayin** [comment]
Types for what? Parameter? Return value? Please be more specific. Problem/Expected behavior was written too short and not informative enough.

The lua annotation of `vim.fn.bufnr()` takes `any?` type and returns `integer` and I don't see any problem with it. What you said doesn't align with the current Lua types.

Same for `vim.fn.bufname()`. It returns `string` and takes `any?` type, so it's also not wrong although it could be more specific; narrow down it to `string|integer`.
