### ISSUE TITLE
A process outputting in a :term closes a "press ENTER" prompt.

### ISSUE THREAD

**Issue by Soares** [neovim/neovim#2748]
Repro steps: have something compiling in a `:term`, open a new buffer, type `:ls` to list open buffers.

Behavior: next time the output in the term gets to a newline, the `:ls` window will close (as if you had pressed ENTER to continue).

This makes it a bit hard to read the output of `:ls` :-p

**Comment by splinterofchaos** [comment]
Confirmed. Interestingly, the cursor remains at the bottom of the screen because, despite the output being clobbered, we're stuck in "press enter mode" and never get past [this line](https://github.com/neovim/neovim/blob/62bcd98ae3ad74265ded36e3e6e57209148a1ece/src/nvim/message.c#L852). I've been looking into this, but unfortunately have little familiarity with input processing, the message system, and screen drawing/updating. 

My best guess is that vim doesn't expect to have many events being processed in the background while at a "Hit RETURN" message, so the second redraw (the first having printed this message) thinks that nothing's there.

**Comment by justinmk** [comment]
This is fixed. Added a test as well.
