### ISSUE TITLE
undefined reference to ts_set_allocator

### ISSUE THREAD

**Issue by xiota** [neovim/neovim#27640]
### Problem

After tree-sitter commit https://github.com/tree-sitter/tree-sitter/commit/f1eecf9786a0c18fd659eb8b392f172f12e3b586, attempting to build `neovim` results in following error.

```
/usr/bin/ld: /tmp/ccBmSmO3.ltrans28.ltrans.o: in function `tslua_init':
/home/main-builder/pkgwork/src/neovim/src/nvim/lua/treesitter.c:171:(.text+0x37c9): undefined reference to `ts_set_allocator'
collect2: error: ld returned 1 exit status
make[2]: *** [src/nvim/CMakeFiles/nvim_bin.dir/build.make:5150: bin/nvim] Error 1
make[2]: Leaving directory '/home/main-builder/pkgwork/src/neovim/build'
make[1]: *** [CMakeFiles/Makefile2:624: src/nvim/CMakeFiles/nvim_bin.dir/all] Error 2
make[1]: Leaving directory '/home/main-builder/pkgwork/src/neovim/build'
make: *** [Makefile:156: all] Error 2
```

Checking out the commit immediate before (https://github.com/tree-sitter/tree-sitter/commit/52d69790f36b96ecc1541f6106782ab12786f7cb) results in successful build.

### Steps to reproduce

1. clone, build, and install tree-sitter from https://github.com/tree-sitter/tree-sitter
2. clone and attempt to build neovim

### Expected behavior

Successful build.

### Neovim version (nvim -v)

a4b4442524

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

Arch Linux

### Terminal name/version

Not applicable

### $TERM environment variable

Not applicable

### Installation

Not applicable / AUR

**Comment by clason** [comment]
> Not applicable / AUR

Very much applicable. You cannot pull in random (pre-release) versions of dependencies and expect them to build. (This is why distro nightly builds are not supported. Go and complain to the AUR.)

**Comment by roland-5** [comment]
Hi @clason. Please don't take this personally. Neovim nightly wouldn't start due to a treesitter error and I wasn't sure if it was I doing something wrong, or a problem with building the AUR package, or maybe a bug in Neovim that no one had noticed yet. Not fully understanding how to build packages at all, I asked the team responsible for the Archlinux chaotic-aur repository for help, and @xiota offered to help, hence this issue. I know that nightly versions have no support. I thought it might be something important for the project.

**Comment by clason** [comment]
I'm not taking it personally, but I want to be very clear that this kind of issue is not appropriate here -- so that there won't be any confusion about where to open issues in the future.

In brief, a build failure is only a valid issue if
1. it contains explicit, complete, step-by-step descriptions on how the build was done and
2. these steps use `git clone neovim`, `make distclean`, and `make`.

If the build is mediated by distro scripts, any failure is a distro issue and has to be reported there (only, or first if it turns out that a **supported** option to build with **valid** external dependencies fails using **our** build scripts as well. (Such a report would indeed be welcome.)

**Comment by roland-5** [comment]
I will remember this. Thank you for explanation.

**Comment by zeertzjq** [comment]
This seems to be bug in tree-sitter. It doesn't set correct visibility for `ts_set_allocator`.

**Comment by zeertzjq** [comment]
Reported at https://github.com/tree-sitter/tree-sitter/issues/3091
