### ISSUE TITLE
When using a custom statuscolumn, an increase in the number width doesn't redraw lines properly

### ISSUE THREAD

**Issue by yorickpeterse** [neovim/neovim#27709]
### Problem

When `numberwidth` is set to `3`, and a buffer is changed such that the width needs to be increased to `4`, _and_ a custom `statuscolumn` is set, the width change doesn't properly redraw all lines. The result is that the number/status column overlays one column of the buffer, until you somehow force a redraw or move the cursor around:

[Screencast from 2024-03-02 22-22-50.webm](https://github.com/neovim/neovim/assets/86065/21321001-8512-4f07-affe-71b6fb23ec05)

### Steps to reproduce

Create `repro.lua` with these contents:

```lua
vim.opt.numberwidth = 3
vim.opt.statuscolumn = '%s%=%{&relativenumber ? (v:virtnum == 0 ? (v:relnum > 0 ? v:relnum : v:lnum) : " ") : ""} '
vim.opt.relativenumber = true
vim.opt.number = true

local lines = {}

for i = 1, 99 do
	table.insert(lines, "line " .. i)
end

vim.api.nvim_buf_set_lines(0, 0, #lines - 1, false, lines)
```

Now run `nvim --clean -u repro.lua`, then:

1. Press `G` to go to the bottom of the buffer
2. Press `o` to create a new empty line
3. Observe how in the lines above the text changes from "line NN" to "ine NN"

When doing so, the following happens:

[![asciicast](https://asciinema.org/a/nfBRPU3ZajtcNx5iMLuWBU10w.svg)](https://asciinema.org/a/nfBRPU3ZajtcNx5iMLuWBU10w)

`:redraw` doesn't help, but pressing `Control+L` does (which is what triggers the redraw at the end of the recording).

### Expected behavior

Lines are redrawn properly such that all buffer text remains visible.

### Neovim version (nvim -v)

b12d193b4a

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

Ghostty

### $TERM environment variable

xterm-ghostty

### Installation

AUR

**Comment by Johnkb101313** [comment]
Hello, I have encountered the similar problem, but this time cause by 'cursorline' option.

### Steps to reproduce

Create repro.lua with these contents:

```lua
vim.opt.numberwidth = 4
vim.opt.cursorline = true
vim.opt.relativenumber = true
vim.opt.number = true
vim.opt.statuscolumn = '%s%=%{&relativenumber ? (v:virtnum == 0 ? (v:relnum > 0 ? v:relnum : v:lnum) : " ") : ""} '

local lines = {}

for i = 1, 999 do
	table.insert(lines, "line " .. i)
end

vim.api.nvim_buf_set_lines(0, 0, #lines - 1, false, lines)

```

Now run nvim --clean -u repro.lua, then:

1. Press `gg` to go to the top of the buffer
2. Press o to create a new empty line
3. Observe how in the lines below the text changes from "line NN" to "ine NN"

When doing so, the following happens:

https://github.com/user-attachments/assets/0a9f9709-1020-40b7-9b66-2057a07e4f2a

### Expected behavior

Lines are redrawn properly such that all buffer text remains visible.

### Neovim version (nvim -v)

```
NVIM v0.12.3
Build type: RelWithDebInfo
LuaJIT 2.1.1780076327
Run "nvim -V1 -v" for more info
```

### Operating system/version
Arch Linux

### Terminal name/version
Alacritty

### $TERM environment variable
xterm-256color

### Installation
`pacman -S neovim`
