### ISSUE TITLE
Command to read and show keyboard shortcut

### ISSUE THREAD

**Issue by houshuang** [neovim/neovim#2775]
In Emacs, C-h k let's you input a keyboard combination exactly as you would in the normal program, and then displays not only how it interprets that keyboard command, but also what commands are bound to it. This is very useful when figuring out how to describe special keys in remap commands, but also to debug binding problems (for example to see what the Apple key is bound to in terminal, etc). In Vim/NV, you can use `:nmap` etc to see what a key is bound to, but you need to specify it using Vim's syntax (<C-a> etc). 

If there was a set of new commands that let you directly enter the keyboard combination, that would probably make it much easier for newcomers.

**Comment by ZyX-I** [comment]
> In Vim/NV, you can use :nmap etc to see what a key is bound to, but you need to specify it using Vim's syntax ( etc).

You don’t. Just use `*map <C-v>{key}`.

**Comment by houshuang** [comment]
One peculiarity is that when I try with Alt+h in terminal, I get `:nmap è`,
however in my vimrc file, the mapping <A-h> works perfectly. (And indeed,
the result of `:nmap è` is the right command, however A-h is a lot more
legible for my .vimrc file, but C-v would not have told me that).

Thanks though, great trick.

Stian

On Sunday, May 31, 2015, Nikolai Aleksandrovich Pavlov <
notifications@github.com> wrote:

> In Vim/NV, you can use :nmap etc to see what a key is bound to, but you
> need to specify it using Vim's syntax ( etc).
>
> You don’t. Just use *map <C-v>{key}.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neovim/neovim/issues/2775#issuecomment-107161998>.
>


-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by glacambre** [comment]
@houshuang The reason neovim prints `è` when pressing `<C-v><A-h>` is that your terminal is sending `è` to neovim instead of sending `<A-h>`. A new API wouldn't fix this - it would instead behave in the same way as `<C-v>`. There is thus nothing to do here.

(By the way this is only tangentially related but there's a very neat function available on the lua side that will let you listen to all key events: `vim.on_key`. Check out `:h vim.onkey` to learn more!)
