### ISSUE TITLE
`expand('%')` returns absolute path in file having LSP diagnostics

### ISSUE THREAD

**Issue by hexium310** [neovim/neovim#27818]
### Problem

Executing `:echo expand('%')` without `:p` in the file having LSP diagnostics shows the absolute path. This issue occurs in the file opened after LSP is launched and does not occur in the file opened first. I notice it occurs with lua-language-server or rust-analyzer, but it may occur with other LSPs.

### Steps to reproduce using "nvim -u minimal_init.lua"

1. `touch empty.lua .editorconfig`
2. `echo 'global_var = 1' > diagnostic.lua`
3. `nvim -u minimal.lua`
4. `:e empty.lua` and wait for LSP to launch completely
5. `:e diagnostic.lua`
6. `:echo expand('%')`

`minimal.lua`
```lua
local pattern = 'lua'
local cmd = { 'lua-language-server' }
local root_markers = { '.git', '.editorconfig' }
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'bugged-ls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })

  end
})
```

### Expected behavior

It should return the relative path.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2563+g1da0f3494

### Language server name/version

lua-language-server 3.7.4, rust-analyzer 2024-03-04

### Operating system/version

Arch Linux on WSL

**Comment by zeertzjq** [comment]
Cannot reproduce

**Comment by hexium310** [comment]
I tried it on Mac and reproduced it. Did you wait a few seconds for the LSP to launch after opening empty.lua?

on WSL
![wsl_expand](https://github.com/neovim/neovim/assets/10758173/5a795a5f-3ed4-4fb4-93d4-1ba7b9088a66)

on Mac
![mac_expand](https://github.com/neovim/neovim/assets/10758173/1daa388e-3eeb-42d3-8d02-b62db17fa3bd)

**Comment by zeertzjq** [comment]
Oops, I misspelled `.editorconfig`. It's strange that this bug only happens when there is a `.editorconfig` file present.

**Comment by hexium310** [comment]
Actually, it does not occur when there is a `.editorconfig` file, but when I am under the directory existing root marker files (or directories) for LSP.  It occurs when there is a `.git` directory or editing `root_marker` such as `local root_markers = { 'minimal.lua' }` in `minimal.lua`.

**Comment by mfussenegger** [comment]
I think this is kinda expected.  The behavior of `expand('%')` depends on how the buffer was added.
When neovim receives diagnostics from the language server it calls `bufadd` for the file uris/filenames

 E.g. compare:

- Open nvim without file
- `:call bufadd("/absolute/path/to/file")`
- `:e to/file`
- `:echo expand("%")

With

- Open nvim without file
- `:call bufadd("relative/path")`
- `:e relative/path`
- `:echo expand("%")


Regarding `.git`/`.editorconfig`:  `.git` is a folder and `.editorconfig` is a file so you get a different root_dir. Compare `vim.fn.fnamemodify(".git/", ":p:h")` with `vim.fn.fnamemodify(".editorconfig", ":p:h")` in a folder where both exists. I use something like this because of that difference:


```lua
function M.find_root(markers, path)
  path = path or api.nvim_buf_get_name(0)
  local match = vim.fs.find(markers, { path = path, upward = true })[1]
  if match then
    local stat = vim.loop.fs_stat(match)
    if stat and stat.type == "directory" then
      return vim.fn.fnamemodify(match, ':p:h:h')
    end
    return vim.fn.fnamemodify(match, ':p:h')
  end
  return nil
end
```
