### ISSUE TITLE
$NVIM_TUI_ENABLE_TRUE_COLOR breaks YouCompleteMe's default mapping

### ISSUE THREAD

**Issue by frankier** [neovim/neovim#2782]
Many terminals send `<C-Space>` as `<Nul>`, including gnome-terminal which I'm using.

YouCompleteMe checks for a terminal and special cases it here: https://github.com/Valloric/YouCompleteMe/blob/65f0fac61c9b2f4fa08a843de701ce5b957ece24/autoload/youcompleteme.vim#L181

When I set `$NVIM_TUI_ENABLE_TRUE_COLOR`, `gui_running` is true and the special case is not run meaning the key is not correctly bound.

The question is should neovim/libtermkey translate `<Nul>` sent by gnome-terminal to <C-Space> (this would break current YouCompleteMe when `!gui_running`) or should YouCompleteMe special case some kind of `tui_running` as well as `!gui_running`?

**Comment by ZyX-I** [comment]
I am wondering how you can input `<Nul>` in GUI? I think it makes sense to define both mappings in YCM because I do not know such a way (though maybe custom XKB keyboard description might help here, but who will bother).

For YCM it may also make sense to do `imap <C-Space> <Nul>` (note: `imap` without nore, this is not a typo: this is the first class exception “allow using remappable mapping when you know that the whole rhs is mapped”) and unconditionally map `<Nul>`: should be rather harmless.

**Comment by frankier** [comment]
Okay, so the second question here is do common terminal emulators insert anything other than <C-Space> as <Nul>? If not should either neovim or libtermkey interpret <Nul> as <C-Space>?

**Comment by ZyX-I** [comment]
@frankier `<C-@>` is sent as `<C-@>` as well as `<C-Space>` (`<Nul>` is officially an alias to `<C-@>`).

**Comment by justinmk** [comment]
If we don't set gui_running for true color, then we have to convince colorscheme authors to not check for that. If we do set it (as we currently do), then we have to convince YCM to change the condition. Opting for the later.
