### ISSUE TITLE
:g and :v are quite slow compared to vanilla vim

### ISSUE THREAD

**Issue by zachariahreed** [neovim/neovim#2793]
For instance the command `:g/def/d` on around 250 lines in vim is instantanous, while an identical operation in nvim takes 2-3 seconds

**Comment by zachariahreed** [comment]
D'oh, I'm realizing this is probably a duplicate of #2584. It seems like almost every problem I've encountered with nvim is related to clipboard settings. What are the current recommendations in this area?

**Comment by kopischke** [comment]
It will probably attract @tarruda’s and @justinmk’s ire, but I am starting to think removing native clipboard integration was an error; (Neo)Vim’s internal text clipping system may simply be [too complex to be a good fit for existing external tools](https://github.com/neovim/neovim/issues?utf8=%E2%9C%93&q=xsel), and developing what is essentially a Neovim-only use case `xsel` clone is probably no less an effort than refactoring the festering mess of the old clipboard code to something sane would have been.

**Comment by bfredl** [comment]
I had some ideas how to improve the existing solution, but not much time to
work on it. It would all been much simpler if nvim just supported
_in-process_ plugins
Den 6 jun 2015 2:12 em skrev "Martin Kopischke" <notifications@github.com>:

**Comment by splinterofchaos** [comment]
Just a sanity check: Is this when compiling in release mode?

**Comment by tarruda** [comment]
@kopischke / @zachariahreed this particular problem is related with how nvim(and vim before[7.4.396](https://code.google.com/p/vim/source/detail?r=v7-4-396)) implements the global command, and not with how nvim implements clipboard. In this case, `g:` is unnecessarily copying data to the register for every invocation of the passed command, when it only needs to copy the last invocation(since the previous ones are overwritten anyway)

For normal registers this isn't noticeable because everything happens in memory, but when interfacing with an external system such as the clipboard, the performance is tied to how long it takes to communicate with said system. As stated by @chrisbra in #2155, on UNIX this was fast, but mainly because Xlib is very fast when sending clipboard data(I wouldn't expect it to be fast when running it over ssh with x11 forwarding for example). The right fix for the problem lies in patch 7.4.396.

@zachariahreed while the patch isn't ported, a temporary solution is to append a `_` to the end of the global command, instead of `:g/def/d` execute `:g/def/d _` which will send deleted lines to the black hole register.

**Comment by zachariahreed** [comment]
@splinterofchaos: it took me a second to verify since I'm not super familiar with the build system, but I see the problem in RelWithDebInfo as well as Debug. Debug is definitely worse though.

@tarruda:  thanks for the explanation. Once I realized that this was clipboard related, I was just unsetting clipboard=unnamed temporarily

**Comment by kopischke** [comment]
@tarruda thanks for the detailed explanation. Even if my remarks apply only tangentially to the current case, I still can’t shake the feeling we have created more problems than we solved by offloading something as specialised as interfacing Vim’s rather peculiar text clipping model with OS clipboards to external tools with no knowledge of the peculiarities they deal with.

**Comment by justinmk** [comment]
@kopischke The good thing about forcing the clipboard into the provider system is that it forces us to work out issues in the provider system/design. We can always retreat to in-process approach later if it turns out to be a mistake for clipboard.

**Comment by tarruda** [comment]
> @kopischke The good thing about forcing the clipboard into the provider system is that it forces us to work out issues in the provider system/design. We can always retreat to in-process approach later if it turns out to be a mistake for clipboard.

:+1:

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/2809
