### ISSUE TITLE
How to set-up spell checker in nvim

### ISSUE THREAD

**Issue by Robinlovelace** [neovim/neovim#2804]
This is a newbie question for sure and not necessarily related to the development of neovim. But it's bugging me and preventing me from using nvim as my main command-line text editor. So I'm asking the community.

How do I find my spellfile and how do I tell nvim where it is after getting this message:

"Warning: Cannot find word list "en.utf-8.spl" or "en.ascii.spl""

Here's my .nvimrc:

```
" Note: Skip initialization for vim-tiny or vim-small.
 " BundleUpdate
 " BundleUpdate
 if !1 | finish | endif

 if has('vim_starting')
   if &compatible
     set nocompatible               " Be iMproved
   endif

   " Required:
   set runtimepath+=~/.vim/bundle/neobundle.vim/
 endif

 " Required:
 call neobundle#begin(expand('~/.vim/bundle/'))

 " Let NeoBundle manage NeoBundle
 " Required:
 NeoBundleFetch 'Shougo/neobundle.vim'

 " My Bundles here:
 
 " Refer to |:NeoBundle-examples|.
 NeoBundle 'tpope/vim-markdown'
 NeoBundle 'ctrlpvim/ctrlp.vim'
 NeoBundle 'tomasr/molokai'
 NeoBundle 'scrooloose/nerdcommenter'
 NeoBundle 'vim-pandoc/vim-pandoc'
 NeoBundle 'vim-pandoc/vim-pandoc-syntax'
 NeoBundle 'vim-pandoc/vim-rmarkdown'

 
 " Note: You don't set neobundle setting in .gvimrc!

 call neobundle#end()

 " Required:
 filetype plugin indent on
 set mouse=a
 syntax enable
```

Sorry if this is really dumb; hope it's of use to others

**Comment by henrik-farre** [comment]
This looks like a duplicate of #1551 

My workaround is to download the spell files from ftp://ftp.vim.org/pub/vim/runtime/spell/ and put them in ~/.nvim/spell/

**Comment by Robinlovelace** [comment]
That fixed it. Thanks.

**Comment by fwalch** [comment]
FWIW, as also mentioned in the other thread, if you execute `:set spell`, (Neo)vim will ask you if it should download the spell files for you (no need for manual download from FTP).

**Comment by victoriastuart** [comment]
Ahhh ... guess I could have, eh?  Still, seems presumptuous (of me) editing another's GH repo page ...  ;-)

**Comment by victoriastuart** [comment]
I realize that this Issue is closed, but my experiences in migrating from vim to veovim (nvim) and spell-checking are apropos, here.

---

**Background**

    Arch Linux x86_64
    vim v.8.0; nvim v.0.1.7
    Locale: LANG=en_US.UTF-8

I migrated my Vim settings to nvim as follows:

    " Symlinks:
    ln -s  ~/.vim  ~/.config/nvim
    ln -s ~/.vimrc  ~/.config/nvim/init.vim

[Once you make those symlinks you can work on files at either location: edits made in one auto-populate the other.]

In vim I have a custom spell file,

    ~/.vim/spell/en.utf-8.add

to which I added my

    ~/.config/enchant/en_US.dic

spellings. To use that file in vim, you need to open it,

    ~/.vim/spell/en.utf-8.add

in vim and in Command mode execute

    :mkspell! %

[ ! overwrites an existing file; % is the current file, in the vim buffer.]

That command generates

    ~/.vim/spell/en.utf-8.add.spl

, a binary (?) file that is used by vim for spell-checking (spelling actions: add, delete, ... in vim are automatically added/removed from that file).

If you manually edit "en.utf-8.add" (in any editor of your choice: gedit, Geany, vim, ...) you must open it in vim and repeat the ":mkspell! %" command.

---

**Issue**

Upon switching to nvim, my spell-checking was "wonky:" words in my dictionary were highlighted (in pink) as misspelled; words not in my dictionary were unhighlighted.


---

**Spell-Check in Neovim**

As I determined (Google searches), Neovim (nvim) handles spell-checking "differently" than vim.

Here is the Spell section from my ~/.vimrc (now symlinked to ~/.config/nvim/init.vim):

    set spell spelllang=en_us
    set spellfile=~/.config/nvim/spell/en.utf-8.add

    " After adding a word to 'spellfile' with the above commands its associated
    " '.spl' file will automatically be updated and reloaded. If you change
    " 'spellfile' manually you need to use the |:mkspell| command. This sequence of
    " commands mostly works well:
    "
    "     :edit <spellfile; e.g. en.utf-8.add>
    "     (make changes to the spell file)
    "     :mkspell! %

Note the "set spell spelllang=en_us" and "set spellfile=~/.config/nvim/spell/en.utf-8.add" lines.

First, for use in nvim, change


    set spell spelllang=en_us

to


    set spell

Then, In nvim, temporarily comment-out ( " ) those lines,

    "set spell
    "set spellfile=~/.config/nvim/spell/en.utf-8.add

Quit; restart nvim.

Manually execute

    :set spell

and you will be presented with (based on your system Locale)

    No spell file for "en" in utf-8
    Download it? >> y (yes)

    ~/.config/nvim/spell/en.utf-8.spl written
    Downloading en.utf-8.sug

    ~/.config/nvim/spell/en.utf-8.sug written

Now you will have

    ~/.vim/spell/en.utf-8.add
    ~/.vim/spell/en.utf-8.add.spl
    ~/.vim/spell/en.utf-8.spl
    ~/.vim/spell/en.utf-8.sug

mirrored in

    ~/.config/nvim/spell/

Uncomment

    "set spell
    "set spellfile=~/.config/nvim/spell/en.utf-8.add

in your ~/.vimrc and you should have spell-checking in nvim!  :-D

**Comment by justinmk** [comment]
@victoriastuart Thanks for the thorough report, if there's a bug or a specific suggestion please open a new issue.

> As I determined (Google searches), Neovim (nvim) handles spell-checking "differently" than vim.

The only difference is that we don't ship with the spell files, they are auto-downloaded when you call `:set spell` (Vim has this feature as well, we just improved it a bit).

> Then, In nvim, temporarily comment-out ( " ) those lines,
> "set spell

The main problem IIRC is that with `:set spell` in your init.vim you might not get the auto-download prompt. That is a known issue (though I'm not sure if there's a ticket for it).

**Comment by dagolinuxoid** [comment]
@fwalch — it's all fine and good, but downloaded version is kinda sucks since it highlights even such common words as «what» :)

**Comment by samusz** [comment]
As per the documentation I did 
        `:setlocal spell spelllang=en_us`
with my locale and it did do a download of it... 

I don't know if there is a difference with `:set spell`.

HIH

**Comment by pierreay** [comment]
I also had troubles to have Neovim download interactively the new dictionary files.
The issue was that `netrw` was disabled in my configuration file. I had to comment out the two following lines:

```lua
-- vim.g.loaded_netrwPlugin = 1
-- vim.g.loaded_netrw = 1
```

With `netrw` enabled, Neovim was able to prompt me to download new dictionary. According to [this stackexchange](https://vi.stackexchange.com/questions/5651/how-can-i-make-vim-download-spell-files) post, `netrw` is used under the hood to download the files.
