### ISSUE TITLE
Add 32-bit binaries to the nightly release

### ISSUE THREAD

**Issue by Grimy** [neovim/neovim#2805]
Since neovim is built for both 64 and 32 bits, why should the nightly release only have 64 bit binaries?

**Comment by fwalch** [comment]
Just to make sure that we are on the same page: as stated in the release description of the nightlies, they are *not* for end users, just for plugin developers running tests on Travis.

To answer your question, there are no 32-bit nightlies because no-one needed them. For example, `python-client` [runs the tests only with the 64-bit version](https://github.com/neovim/python-client/blob/b1621173786815ff3145c01682ae3aa60326f3dd/.travis.yml#L28).
