### ISSUE TITLE
varnumber_T should be long?

### ISSUE THREAD

**Issue by phmarek** [neovim/neovim#2812]
After reading http://bugs.debian.org/788055 I looked at the neovim sources and found `src/nvim/eval_defs.h`:

```
typedef int varnumber_T;
```

so I guess that it will have the same problem (cutting off `getfsize()`), right?

Can this be changed to a long?

**Comment by justinmk** [comment]
Seems reasonable, we could wrap it in a `#ifdef`. An exploratory PR could get the ball rolling...

**Comment by splinterofchaos** [comment]
According to GNU (http://www.gnu.org/software/libc/manual/html_node/File-Positioning.html), `long` would be the correct going by the C standard, but keep in mind that both Linux and Windows use 32-bit `long`s, so the problem will remain. libuv stores file sizes as a `uint64_t`, so we could switch `varnumber_T` to `int64_t` (because it must be signed), and I think POSIX's `off_t` (used for file positions) is signed so that should be sufficient, but wasteful and slow on 32-bit machines.

Are there many other situations that exhibit this problem? I'm not convinced we should do this.

**Comment by phmarek** [comment]
@splinterofchaos: my 64bit machine gives `8` as `sizeof(long)`. Where do you see 32bit?
I think that `long` (as a per-architecture word) would be the best choice.

And no, having 32bit file size handling limitations is not okay - since about 10 years or so. Not even for display only.

**Comment by splinterofchaos** [comment]
>  my 64bit machine gives 8 as sizeof(long). Where do you see 32bit?

Mine, too. Maybe I'm wrong about linux, I'm going off of google and stack overflow. See also: https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models, which shows that Windows still uses 32 bits for `long`. Even if it didn't, using 64-bit numbers throughout the code base, even on 32-bit machines, could have a negative performance impact.

> And no, having 32bit file size handling limitations is not okay - since about 10 years or so. Not even for display only.

The problem is that `varnumber_T` is not tuned for file sizes but general programming and we store their values in `int`s all the time. This could lead to having to use `int64_t` by default in the code base.

Also, ten years ago, they thought that all integers might be 64 bits, but then they saw how much it increased their memory consumption and execution time. Not saying that'll definitely happen here, but we generally only need line and column numbers in vimL, not precise file sizes.

**Comment by justinmk** [comment]
Addressed by https://github.com/neovim/neovim/pull/5621
