### ISSUE TITLE
initialization startup documentation mentions vimrc but should be nvimrc

### ISSUE THREAD

**Issue by languitar** [neovim/neovim#2827]
The documentation for `exrc` mentions files called `vimrc`, but only files called `nvimrc` are processed.

e.g.
```
	Places for your personal initializations:
		Unix		$HOME/.vimrc or $HOME/.vim/vimrc
		MS-Windows	$HOME/_vimrc, $HOME/vimfiles/vimrc
				or $VIM/_vimrc
```

**Comment by Pyrohh** [comment]
There are many such instances, so if this is changed it should all be done in one go, IMO.

**Comment by jalvesaq** [comment]
All occurrences of vimrc could be replaced with a single `sed` command:

```shell
cd runtime/doc
sed -i -e 's/\<vimrc\>/nvimrc/g' *.txt
```

But, latter, a revision should be made by people who know well both Neovim code and plans for Neovim future because there are also references to `gvimrc` and to the path where the `vimrc` can be found (`vimfiles` on Windows, for example). What will be the Neovim directories on Windows? Some vim scripts in the runtime directory also make references to `vimrc` in commented lines. Should they be replaced by `nvim` too?

**Comment by justinmk** [comment]
> so if this is changed it should all be done in one go, IMO.

Fixing the most prominent cases which cause user confusion is probably enough in this case. We're going to move to XDG anyways.

> What will be the Neovim directories on Windows?

Most likely XDG convention. https://github.com/neovim/neovim/issues/78

**Comment by justinmk** [comment]
Rolling this into XDG milestone.
