### ISSUE TITLE
<C-\><C-n> versus <C-leader><C-n>?

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#2830]
Is it always `<C-\><C-n>`? Or could it be `<C-leader><C-n>` to work well with the user being able to choose any leader key?

**Comment by Pyrohh** [comment]
That sounds reasonable to me, but let's wait for more comments.

**Comment by justinmk** [comment]
The reason for `c-\ c-n` is that it matches the existing purpose of `c-\ c-n`. This isn't going to change. By default there will be a `nnoremap` to `<esc><esc>` or maybe just `<esc>` in terminal buffers.

see https://github.com/neovim/neovim/issues/2676#issuecomment-107998093 and https://github.com/neovim/neovim/pull/2760

**Comment by trusktr** [comment]
@justinmk 

I strongly oppose a default `nnoremap` to `<esc><esc>`. I use escape too often in certain ways that it will certainly get in the way.

But anyway, the default leader key is `/`, no? So `c-\ c-n` is simply just `<c-leader><c-n>` in disguise. `<c-leader><c-n>` could be the new default for everywhere else it's used too, and this would be nice because now this is customizeable without having to rewrite mapping, the user simply chooses any leader key they want, with `/` as the default.

**Comment by ZyX-I** [comment]
@trusktr No, it is not `<C-Leader><C-n>` and never was. `<C-\><C-n>` is *not a mapping*. It is a *built-in command* and such a thing was *never* customizeable and *cannot be* customizeable because it is needed to work when used in `nore` mappings, abbreviations and menus. It also cannot be customizeable because there is no facility for customizing shortcuts hardcoded in C code. And specifically `leader` cannot be placed there because user cannot type `<C-,>` in some terminal emulators at all and in *all* terminal emulators I know by default and comma is one of the most common `mapleader` keys.

**Comment by trusktr** [comment]
> No, it is not <C-Leader><C-n> and never was. <C-\><C-n> is not a mapping. It is a built-in command and such a thing was never customizeable and cannot be customizeable because it is needed to work when used in nore mappings, abbreviations and menus.

@ZyX-I This is software that is being written, and it can do anything we want it to. Everything you mentioned in that quote is doable. `<C-Leader><C-n>` can work if you want it to. It's just code! `nore` can work if you want it to, it's just code. 

For example, why not just have `<C-Leader><C-n>` send internally the so called `<C-\><C-n>` command? Etc. There's probably many ways to solve this, and saying that it can't be done is not true. :]

**Comment by ZyX-I** [comment]
@trusktr 

1. “Leader” is queried when mapping is defined. If you use `<C-Leader><C-n>` for “escape to normal mode” and then user changes leader then your `nore` mappings are no longer working. Behaviour is intentional, changing this is breaking compatibility (e.g. one may define `mapleader` in SourcePre to set leader only for specific plugin).
2. Leader is not guaranteed to have one character only, so what is `<C-Leader>`?
3. Leader is not guaranteed not to be `<C-something>` already.
4. There is `<C-\>`, but there is no `<C-,>` in terminals and it situation is not going to change any time soon.
5. `<C-\><C-n>` is already being used in code.

3\. is enough to state that having `<C-Leader>` is *impossible*. Also nobody is going to have a bunch of problems out of nothing.
