### ISSUE TITLE
Jobhandling - stderr not working

### ISSUE THREAD

**Issue by kassio** [neovim/neovim#2836]
I'm trying something like this:
```viml
" ~/jobcontrol.vim
function! s:JobHandler(job_id, data, event)
  echom a:event.': '.string(a:data)
endfunction
let s:callbacks = {
      \ 'on_stdout': function('s:JobHandler'),
      \ 'on_stderr': function('s:JobHandler')
      \ }

new | call termopen([&sh, &shcf, 'echo "STDOUT"'], s:callbacks)
new | call termopen([&sh, &shcf, 'BOOM'], s:callbacks)
```

```console
$ nvim -u NONE -S ~/jobcontrol.vim
```
I expected that the second call, the one with `BOOM`, would use `on_stderr`, but both calls used `stdout`:

```
stdout: ['STDOUT^M', '']
stdout: ['zsh:1: command not found: BOOM^M', '']
```

**Comment by tarruda** [comment]
When a program is spawned under `termopen`, both stdout and stderr send data to the same pty device and Neovim has no way to distinguish if the program sent the data via file descriptor 1 or 2.

This is not a bug, it's just how it works. Think about it: when you see a program message in your terminal, can you tell if it was sent via stdout or stderr? No, because all data received by the terminal comes from the pty master.

The only way to split stderr is to use redirection, but unfortunately Neovim doesn't support this natively at the moment(I may add this after implementing `:terminal` on windows). One temporary workaround is to use shell redirection and spawn a separate job to read the data, something like this:

```vim
function! s:Stdout(job_id, data)
  echom 'stdout: '.string(a:data)
endfunction
function! s:Stderr(job_id, data)
  echom 'stderr: '.string(a:data)
endfunction
function! s:RemoveFifo()
  call system('rm stderr.fifo')
endfunction

let s:stdout = {'on_stdout': 's:Stdout'}
let s:stderr = {'on_stdout': 's:Stderr', 'on_exit': 's:RemoveFifo'}

call system('mkfifo stderr.fifo; echo STDOUT > right-file')
new | call termopen([&sh, &shcf, 'cat right-file wrong-file 2> stderr.fifo'], s:stdout)
call jobstart(['cat', 'stderr.fifo'], s:stderr)
```

**Comment by kassio** [comment]
@tarruda Thank you for the explanation!

**Comment by tarruda** [comment]
BTW here's a fixed example that allows you to see the messages(`string(a:data)` doesnt work because newlines are converted to NULs):

```vim
let g:data = []
function! s:Stdout(job_id, data)
  echom 'stdout: '.a:data[0]
endfunction
function! s:Stderr(job_id, data)
  echom 'stderr: '.a:data[0]
endfunction
function! s:RemoveFifo()
  call system('rm stderr.fifo')
endfunction

let s:stdout = {'on_stdout': 's:Stdout', 'on_stderr': 's:Stdout'}
let s:stderr = {'on_stdout': 's:Stderr', 'on_exit': 's:RemoveFifo'}

call system('mkfifo stderr.fifo; echo STDOUT > right-file')
new | call termopen([&sh, &shcf, 'cat right-file wrong-file 2> stderr.fifo'], s:stdout)
call jobstart(['cat', 'stderr.fifo'], s:stderr)
```

With this you can see the captured stdout and stderr with `:messages`

**Comment by kassio** [comment]
I liked a lot the examples. I know this is not the best place, but just one more question about this: There's any way to get the last command's exit code?

**Comment by justinmk** [comment]
> There's any way to get the last command's exit code?

You mean `jobstart()` or `termopen()`?  `jobstart()` returns the exit code to `on_exit` handler:

```vim
function! OnExit(job_id, data)
  echom 'exit: 'string(a:data)
endfunction

call jobstart(['ls', '-l'], {'on_exit': 'OnExit'})
```

**Comment by kassio** [comment]
@justinmk this is useful. Buf I'd like to get the exit code without exit the term. Something like:
```viml
function! GetStatus(job_id, data)
  echom 'last command exited with: ' . a:data[0]
endfunction
call termopen([&sh, &shcf, 'BOOM'], { 'on_xpto': 'GetStatus' })
```

With that we could have a function to put on `statusline` the last command status. :smile:

**Comment by tarruda** [comment]
@kassio you could do something similar to what I suggested to capture stderr: create a named pipe and have the shell write the status of each command to it while a `cat` job is reading and updating the status line.

Clearly this requires some support from the shell, but here's an idea of how you might be able to do it with bash:

```
if [[ ! -p ~/.status.fifo ]]; then
	mkfifo ~/.status.fifo
fi
exec 3<> ~/.status.fifo
PROMPT_COMMAND='echo $? >&3'
```

The above needs to be sourced by each interactive invocation of bash(append it to the end of ~/.bashrc). Here's what it does:

- If a fifo named `status.fifo` doesn't exist, create it when a interactive shell is spawned. 
- Open the fifo and assign file descriptor 3 to it
- Bash will run the contents of the `PROMPT_COMMAND` env var before drawing the prompt, so use it as a hook to write the status of the last command to file descriptor 3.

You can test this by opening another terminal and invoking `cat ~/.status.fifo` to see the status of each command in the first terminal printed in the second. Note that unlike the first example, the fifo is opened and assigned a file descriptor, this is required because if  `>>` or `>` are used, the fifo would be closed after each command(which makes the `cat` program exit)

If you are going to write a neovim plugin then you probably don't want to ask users to modify their bashrc, so you simply need to make sure the above script is executed on every invocation of `termopen`, you also would need to use temporary file names(one for each shell) in order to match status codes with terminal buffers.

**Comment by justinmk** [comment]
When we add the ability to use nvim as a client, the named pipe stuff won't be necessary.

**Comment by tarruda** [comment]
> When we add the ability to use nvim as a client, the named pipe stuff won't be necessary.

:+1:  using msgpack-rpc to send data to the parent instance is also more portable

**Comment by kassio** [comment]
@justinmk and @tarruda thank you a lot for all the explanations! I learned a lot with all the great examples! :blush: 

For now, I'll parse the `on_stdout` and use it on my statusline. 
Here is what I'm doing kassio/neoterm#25.

One more time, thank you!
