### ISSUE TITLE
HAVE_WORKING_LIBINTL failing on OS X

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#2837]
At some point `HAVE_WORKING_LIBINTL` starting failing for me. I noticed this recently because a plugin call to `:lang` was reporting that the command was not available.

I worked around the problem by installing GNU gettext via homebrew (see  https://github.com/neovim/neovim/pull/76). I hadn't previously installed this.

I'm not really sure there's a reason we should allow build _without_ HAVE_WORKING_LIBINTL--it may just cause confusion.

Here's something weird: this appears to be the cause of https://github.com/neovim/neovim/issues/1962 (which is more an argument for requiring HAVE_WORKING_LIBINTL instead of making it optional...) That means this `gettext` detection issue has existed since at least February.

**Comment by jszakmeister** [comment]
FWIW, The only reason it's optional is because it was in Vim.  When ported much of the build system over, we kept parity.  If it doesn't make sense to do that any longer, we can certainly make it required.  However, I do remember that HAVE_WORKING_LIBINTL was *never* set on my Snow Leopard machine (I did not have Homebrew installed on it).  I did, however, have a locally built copy of gettext 0.18.1 but did not have libintl support.  I don't use that machine much any more, but I do have it around if it helps.

OTOH, I'm not sure how libintl is affecting #1962.  That smells like a different bug.

**Comment by equalsraf** [comment]
FYI I don't have libintl working for windows yet. Could this be mandatory only for UNIX?

**Comment by justinmk** [comment]
@equalsraf we can wait until we get it working on Windows. Is it feasible  for MSVC?

**Comment by equalsraf** [comment]
Looking at the gettext [docs](https://www.gnu.org/software/gettext/FAQ.html#windows_howto) we will need to build gettext and iconv ourselves, we cant link against their binaries (unless we start linking against the dynamic runtime /MD).

It seems gettext does not officially support being built with MSVC,  there a few unofficial builds around github. So we either:

1. Start linking against /MD and can use the gettext builds, but then we would need to find a way to gather dependency dlls for the install target
2. Cook up a build recipe for iconv+gettext - assuming it is possible
3. I suspect someone might have the build recipes figured out ([gtk](https://wiki.gnome.org/Projects/GTK%2B/Win32/MSVCCompilationOfGTKStack#gettext-runtime) has some notes about it that point to KDE)

**Comment by justinmk** [comment]
Can't reproduce this issue now.
