### ISSUE TITLE
&pastetoggle is set to <F37> after initial parsing of the nvimrc

### ISSUE THREAD

**Issue by ppwwyyxx** [neovim/neovim#2843]
I have `set pastetoggle=<F12>` in my vimrc.
With neovim, when I press `F12` in insert mode, I got `<F12>`  written to the buffer.
With vim, I can successfully switch to paste mode.

It might be a similar issue to #2048 ? 
My $TERM is screen-256color, and `infocmp $TERM` gives `kf12=\E[24~`.
When I press `C-V` + `F12` in shell, I see `^[[24~ `

Thanks a lot.

**Comment by Grimy** [comment]
Try to reproduce the issue without a nvimrc:
* Run `nvim -u NONE +'set showmode pastetoggle=<F12>'`
* Hit `i`, then `<F12>`

Expected result:
The text `-- INSERT (paste) --` is displayed at the bottom of the screen.

If it works, the issue was in your config. If it still inserts `<F12> ` it’s probably a terminfo-related problem.

**Comment by ppwwyyxx** [comment]
Thanks for your note. Your suggested method works for me, I can see it entering paste mode. But the following doesn't work for me:
```
echo 'set showmode pastetoggle=<F12>' > /tmp/vimrc
nvim -u /tmp/vimrc --noplugin
```
I still saw `<F12>` entered. However, if then I set the pastetoggle manually in vim with:
`:set pastetoggle=<F12>`, I can then use `F12` to toggle the mode.

The same things happens for all other keys, even a single letter. (set pastetoggle=k)
So it looks like neovim doesn't read my pastetoggle setting in config file. Sorry for submitting a issue with a wrong name without further tests.

**Comment by Grimy** [comment]
I can reproduce the issue on multiple terminals (uxterm, urxvt, roxterm). It could be renamed to « &pastetoggle is set to <F37> after initial parsing of the nvimrc ».

Steps to reproduce
------------------------

    nvim -u NONE +'set pastetoggle'

Expected result
--------------------

    pastetoggle=
(the document default for &pastetoggle is the empty string)

Actual result
----------------

    pastetoggle=<F37>

Since this happens after initial parsing of the vimrc, it overrides any setting done in the vimrc. Note that `set pastetoggle&` still works correctly (resets &pastetoggle to the empty string).

**Comment by Grimy** [comment]
I cannot reproduce the bug in gdb. Running `gdb nvim` followed by `r -u NONE +'set pastetoggle'` correctly yields `pastetoggle=`.

**Comment by Grimy** [comment]
This bug was introduced by 59fb8f8 (tui: Add support bracketed paste) Cc @tarruda

**Comment by justinmk** [comment]
Our bracketed paste approach is definitely a temporary hack (we shouldn't be occupying F37 or any other F...). PR would be welcome if you want to work on it.

**Comment by Grimy** [comment]
The problem here isn’t so much the fact that we occupy F37. The problem is that this is done after parsing the vimrc, overriding user configuration. 

One solution would be to remove the call to `vim_set_option` in src/nvim/tui/term_input.inl, and instead set the default value of pastetoggle in src/option.c to "<F37>" (and document that change).

**Comment by unphased** [comment]
I was using an autocommand to override `pastetoggle`. 

I don't use it anymore, actually, because `<F37>` automatically gets injected when you use paste in iTerm2, so to have it be anything other than `<F37>` is a frustrating experience.

**Comment by justinmk** [comment]
Has anyone seen this issue on latest master?

**Comment by tarruda** [comment]
> Has anyone seen this issue on latest master?

It should still be present, I haven't changed anything yet. Might do it on #3309

**Comment by cztchoice** [comment]
@justinmk I have this issue on the latest master.
I use `brew reinstall --HEAD neovim` get the lastest.

**Comment by dnmario** [comment]
Dear Zhitao Chen,

The email sent to danielm@tinyhub.tk with subject
"Re: [neovim] &pastetoggle is set to <F37> after initial parsing of"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to danielm@tinyhub.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by firedev** [comment]
Sorry the issue is still there when pasting into `:term` now the paste is being surrounded by some broken UTF-8 chars.

**Comment by justinmk** [comment]
@firedev Are you saying the value of `'pastetoggle'` changes? (That's the topic of this issue)

It is a known issue that `:term` does not handle some input correctly: https://github.com/neovim/neovim/issues/2440

**Comment by tarruda** [comment]
FWIW the latest version of libvterm supports bracketed paste, so this is something we can forward to the terminal

**Comment by firedev** [comment]
Sorry, never mind then. I was referring to pasted text being surrounded by `<F37>` and now I see it's being surrounded by broken Unicode chars in `:term`. Had a feeling these two are related.

**Comment by firedev** [comment]
Just now I had the word `setpaste` inserted. Didn't catch what I was doing prior.
