### ISSUE TITLE
vim.lsp.rpc.connect doesn't works on windows

### ISSUE THREAD

**Issue by pogyomo** [neovim/neovim#28485]
### Problem

When I try to start to write gdscript code which is used in Godot Engine,  I found the engine provide a default language server and can communicate it on port `6005`, so I wrote config for it using `vim.lsp.start` and `vim.lsp.rpc.connect` as follow.
```lua
vim.api.nvim_create_autocmd("FileType", {
    pattern = { "gd", "gdscript", "gdscript3" },
    group = vim.api.nvim_create_augroup("gdscript-lsp-start", {}),
    callback = function()
        vim.lsp.start {
            name = "gdscript",
            cmd = vim.lsp.rpc.connect("127.0.0.1", 6005),
            capabilities = capabilities,
            root_dir = vim.fs.dirname(vim.fs.find({ "project.godot", ".git" }, { upward = true })[1]),
        }
    end,
})
```
But the neovim doesn't attach client and so that `vim.lsp.get_clients` returns empty list. Afterthat, I found `cmd` accept a command and so that rewrite config using `ncat` command.
```lua
vim.api.nvim_create_autocmd("FileType", {
    pattern = { "gd", "gdscript", "gdscript3" },
    group = vim.api.nvim_create_augroup("gdscript-lsp-start", {}),
    callback = function()
        vim.lsp.start {
            name = "gdscript",
            cmd = { "ncat", "127.0.0.1", "6005" },
            capabilities = capabilities,
            root_dir = vim.fs.dirname(vim.fs.find({ "project.godot", ".git" }, { upward = true })[1]),
        }
    end,
})
```
Unlike when using `vim.lsp.rpc.connect`, this works well and `vim.lsp.get_clients` returns the client infomation.

### Steps to reproduce

I don't know any other lsp which can communicate with tcp, so I just introduce the procedure using Godot Engine.
1. create a `init.lua` with following content
```lua
vim.api.nvim_create_autocmd("FileType", {
    pattern = { "gd", "gdscript", "gdscript3" },
    group = vim.api.nvim_create_augroup("gdscript-lsp-start", {}),
    callback = function()
        vim.lsp.start {
            name = "gdscript",
            cmd = vim.lsp.rpc.connect("127.0.0.1", 6005),
            capabilities = capabilities,
            root_dir = vim.fs.dirname(vim.fs.find({ "project.godot", ".git" }, { upward = true })[1]),
        }
    end,
})
```
2. download latest Godot Engine from [here](https://godotengine.org/) and extract it.
3. open Godot Engine, then create a project by clicking `New` button.
4. goto `Editor` -> `Editor Settings...` -> `Text Editor` -> `External`, then click `Use External Editor` and set `Exec Path` to any neovim gui frontend  (I check with Neovide).
5. right-click file viewer on lower left and select `New Script...` to create a new gdscript code.
6. double click the created file to open neovim.
7. run `:lua vim.print(vim.get_clients())` and got a empty list.

### Expected behavior

Got a client infomation

### Neovim version (nvim -v)

0.10.0-dev-2987+g3305bb9e4

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Windows 11 Home 23H2

### Terminal name/version

Neovide

### $TERM environment variable

N/A

### Installation

Downloads nvim-win64.msi and execute it.

**Comment by TheLeoP** [comment]
This may be related to [this regression](https://github.com/neovim/neovim/pull/28398#issuecomment-2078152491). Maybe the problem isn't only with named pipes, but with windows being slower in general to connect to named pipes and TCP.

The problem is that Neovim sends the initialization request here

https://github.com/neovim/neovim/blob/af8500af64571f787579b60bf0064cd05655fd51/runtime/lua/vim/lsp.lua#L426-L441

which may happen before the TCP/named pipe connection has been stablished here

https://github.com/neovim/neovim/blob/af8500af64571f787579b60bf0064cd05655fd51/runtime/lua/vim/lsp/rpc.lua#L683-L687

**Comment by TheLeoP** [comment]
Using a command works because it handles the body since the command is launched

https://github.com/neovim/neovim/blob/af8500af64571f787579b60bf0064cd05655fd51/runtime/lua/vim/lsp/rpc.lua#L746-L748

https://github.com/neovim/neovim/blob/af8500af64571f787579b60bf0064cd05655fd51/runtime/lua/vim/lsp/rpc.lua#L761-L770

while connecting via TCP/named pipe starts handling the body once the connection has been established:

https://github.com/neovim/neovim/blob/af8500af64571f787579b60bf0064cd05655fd51/runtime/lua/vim/lsp/rpc.lua#L679-L681

**Comment by TheLeoP** [comment]
Would there be a prefered aproach for a PR addressing this? I can think of:

- Using `vim.schedule_wrap` to ensure the initialization request is made after the TCP/named pipe connection has been stablished (it's a workaround and may cause more problems in the future)
- Refactor the code to send the initialization request inside a callback provided by `client`. `vim.lsp.rpc.start` would use this callback inmedeatly after calling `vim.system` if everithing is ok and `vim.lsp.rpc.connect` would do the same inside the `on_connect` callback, after initializing the read loop

**Comment by mfussenegger** [comment]
@pogyomo can you try with https://github.com/neovim/neovim/pull/28507 ?

**Comment by pogyomo** [comment]
@mfussenegger I just try it with #28507 and found `vim.lsp.rpc.connect` works correctly so that `vim.lsp.get_clients` returns client infomation.
