### ISSUE TITLE
bracketed paste not stored in macro recording

### ISSUE THREAD

**Issue by schweikert** [neovim/neovim#28561]
### Problem

When I use Neovim in a terminal and copy paste some text in insert mode, I expect the effect to be more or less as if I wrote that text with the keyboard instead of pasting it. When recording a macro, that's not the case: if I record a macro and paste some text (for example to add a line of text) during the recording, then that text is not added when executing the macro.

### Steps to reproduce

- Copy some text to the clipboard
- Start a terminal that supports bracketed paste mode (I tested with gnome-terminal and wezterm)
- Start Neovim (nvim --clean)
- Start a macro: [q][q]
- Start insert mode: [i]
- Paste the text in the terminal with [Ctrl-Shift-V]
- Exit insert mode and stop the macro: [Esc], [q]
- Replay the macro: [@][q]

Result: the text is not added again.

### Expected behavior

The macro should add the text that was copy-pasted during the recording.

### Neovim version (nvim -v)

v0.9.6-dev-18+g0ef27180e

### Vim (not Nvim) behaves the same?

No (Vim 9.1)

### Operating system/version

Debian testing

### Terminal name/version

gnome-terminal 3.50.1

### $TERM environment variable

xterm-256color

### Installation

Build from repo (0.9 branch)

**Comment by EliphazBouye** [comment]
I'm going to work on this issue to fix the bug

**Comment by clason** [comment]
No licking the cookie, just send a PR!

**Comment by jroopam** [comment]
Hi Guys,
As far as I understand the issue is that the characters(from bracketed paste) do not reach the typebuffer. And the characters from typebuffer is used to put characters into the recording register.

Can anyone please give me some input/advice where should I start looking to find a solution to this issue?
 
 P.S. Please let me know if this is not the right place to discuss this and I will remove my comment.

**Comment by justinmk** [comment]
One idea for fixing this would be to manually check `reg_recording()` in `vim.paste`, and append the text to the currently-recording macro register: https://github.com/neovim/neovim/blob/648d6426c863c75643d714d45f4b67e19ac6944a/runtime/lua/vim/_editor.lua#L237

**Comment by jroopam** [comment]
@justinmk I tried the approach you shared, but when I checked the contents of the recorded register it didn't have the pasted content. When I checked the contents of the register that I was recording in, in `vim.paste` it still had the content from the previous recording. 
I also tried using `nvim_feedkeys` instead of `nvim_put` to simulate the contents being typed thinking it would solve this but it didn't work either.
Do you (or anyone else) have any suggestions on how to resolve this?

**Comment by justinmk** [comment]
> in `vim.paste` it still had the content from the previous recording.

Oh, right. Could handle the `RecordingLeave` event, but it happens *before* the register is updated. And the handler would need to insert the pasted text in exactly the right place. Though it should be possible to set some state during `vim.paste()` which would give a `RecordingLeave` handler enough info to fixup the macro register (on `CursorMoved` or whatever).

> I also tried using `nvim_feedkeys`

what parameters exactly? The "i" and/or "x" flags of feedkeys() might be relevant. Or maybe "t". We already use feedkeys for cmdline mode: https://github.com/neovim/neovim/blob/5792546777332361a9ac49107e46149c703de90e/runtime/lua/vim/_editor.lua#L259-L261

**Comment by jroopam** [comment]
> what parameters exactly? The "i" and/or "x" flags of feedkeys() might be relevant.
I tried it with the "i" flag. Will try it with the other flags and also the other things you mentioned.

**Comment by zeertzjq** [comment]
Maybe it's necessary to introduce `<PasteStart>` and `<PasteEnd>` to indicate the start and end of the pasted text in the register (and possibly redo buffer as well)? Similar to what was introduced in [Vim 8.0.0210](https://github.com/vim/vim/commit/ec2da36ca48b40c0654b32a8d2c9f52e796daa5e), but using `nvim_paste` instead of entering Insert mode.

**Comment by justinmk** [comment]
> introduce `<PasteStart>` and `<PasteEnd>`

Removing those fixed some very irritating bugs at the time...

**Comment by zeertzjq** [comment]
> > introduce `<PasteStart>` and `<PasteEnd>`
> 
> Removing those fixed some very irritating bugs at the time...

Yes, but those bugs won't be present if they use `nvim_paste` instead of Insert mode typing.

**Comment by zeertzjq** [comment]
Or maybe there can be a more general solution that stores an API call and its arguments in the typeahead buffer?

**Comment by justinmk** [comment]
Let's try to avoid reintroducing `<PasteStart>`. It adds even more complication. And depending on how we would use it, it's either (1) redundant with the existing paste "phases", or (2) would result in multiple `<PasteStart>` inputs for a single paste "stream", which would raise new questions/problems.

**Comment by zeertzjq** [comment]
I don't think those problems are relevant here, as when repeating a paste, all pasted text should have been added to the redo/record buffer, so there are no "phases".

**Comment by justinmk** [comment]
There are phases during bracketed-paste (unless it was changed to always buffer the entire thing until the end, and call `vim.paste` only once?). 

Another question: if we reintroduced `<PasteStart>`, and UIs send that, then `vim.paste` wouldn't be invoked, which would be a regression.

**Comment by zeertzjq** [comment]
I was not suggesting using these two keys for UI. I was suggesting using these two keys for internal paste repeating, so that repeating a paste also calls `vim.paste()`.
