### ISSUE TITLE
secure modeline

### ISSUE THREAD

**Issue by skyhighwings** [neovim/neovim#2865]
With a setting of `securemodeline`, only options in `g:securemodeline_settings` would be able to be set using a modeline. This, combined with a safe default, would mean that modelines could be secure by default and therefore enabled by default

 As they're a very useful feature for collaboration, I'd love to see this happen.

This is inspired by http://www.vim.org/scripts/script.php?script_id=1876

**Comment by Shougo** [comment]
I think this feature is very important.

https://github.com/vim/vim/commit/d0b5138ba4bccff8a744c99836041ef6322ed39a

I have tried to implement the feature, but it is not so easy and I have not much time...

So I will describe the implementation hint here.

* It should be ported in Vim
* This function should be implemented in `do_set()` OPT_MODELINE check in option.c.
* The modeline tests are needed
* The default should be strict.  But it breaks the backward compatibility...
* To check option value is not so easy.  I think `find_option_value()` like function is needed for it.  Cannot use `strstr()` or `vim_strchr()` like other options.

**Comment by cmcaine** [comment]
Are modelines still insecure?

I'm willing to investigate and fix if it's not known one way or another.

Obvious problems like `grepprg=bash` are forbidden and `:h modeline` only mentions inconveniences (setting `tw=5`) as security issues.

**Comment by cmcaine** [comment]
For reference: [VIM CVE list][https://www.cvedetails.com/vulnerability-list/vendor_id-8218/opec-1/VIM.html]

There's been one recent vulnerability report in 2016 that was fixed in 2017 and before that stuff reported before 2011 and fixed by 2012.

The list is missing all of these issues.

* [CVE-2002-1377](https://access.redhat.com/security/cve/CVE-2002-1377) allowed an attacker to execute an arbitrary command
* [CVE-2005-2368](http://www.securityfocus.com/bid/14374/discuss): arbitrary command execution using glob and expand functions
* [2007 (couldn't find a CVE number)](https://lists.alioth.debian.org/pipermail/pkg-vim-maintainers/2007-June/004020.html): DoS through the spell checker (might not be fixed, haven't tested yet)
* [CVE-2007-2438](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2007-2438): shell command execution through writefile, feedkeys and system

(Thanks [stackoverflow](https://security.stackexchange.com/questions/36001/vim-modeline-vulnerabilities))

**Comment by justinmk** [comment]
@cmcaine Thanks for that list. [CVE-2016-1248](https://www.cve.mitre.org/cgi-bin/cvename.cgi?name=2016-1248) was found by a Neovim contributor.

Regarding http://www.vim.org/scripts/script.php?script_id=1876, it takes a whitelist approach. Vim's 'modeline' option operates in the "sandbox" (`:help sandbox`), but again that's a blacklist instead of a whitelist.

I would be in favor of changing 'modeline' to use a whitelist approach (still also operating in the sandbox). That would be a breaking change, but I think it would be worthwhile.

Vim's flag to blacklist an option is `P_NO_ML` (in Nvim source, this is mapped to `deny_in_modelines` in our `options.lua` file). I see only one option marked as such: 'encoding'. Otherwise `P_SECURE` is the gateway. 

So the first phase would be to remove `P_NO_ML` and introduce a new `P_ML` flag. Mark only a few options, and see who complains.

**Comment by ZyX-I** [comment]
I would like to have a way for a user to exclude certain options from the allowed list, securemodeline has a point here. One of the reasons I do not like CtrlP sources is that it sets a number of variables which in my opinion must not be settable by a modeline: foldlevel, foldcolumn; also not sure where, but I saw setting number and/or relativenumber: valid options for modeline in my opinion are related to coding style, and placing options which control what editor shows or how it behaves is invalid there. Obviously, whoever placed these settings there has another opinion.

BTW, securemodelines does not list foldlevel, foldcolumn, number, and, of course (it is not being developed), relativenumber. Do not know why, but `foldmarker` must be in the list of allowed options, it *is* part of the code style, yet securemodelines does not list it.

**Comment by cmcaine** [comment]
options.txt documents a whole load of other options as being disallowed in modelines and sandboxes, so options.lua probably needs an update anyway :)

### Proposal

UX:

 - modelines only accept a whitelist of options
 - Whitelist is exposed as a setting for the user

Development:

 - Someone edits whatever interprets options.lua to understand the whitelist
 - We come up with a whitelist by either
    1. those supported by securemodelines + developer and reviewers pick the most obvious ones
    2. if someone can nominate a sensible corpus, someone can search for real-world use of modelines
    3. we come up with a more restrictive definition for modeline than "whatever vim supports" and the developer selects systematically from the ~100 buffer and window options available (assuming that there's no sensible use case for setting global options)
 - Someone needs to confirm that whatever bit of nvim reads in numbers and booleans from modelines is safe vs untrusted input (but if they're not, I'd expect someone to have published a CVE about it by now)
 - Settings like these will have to be examined carefully by developer and reviewers before inclusion:
    1. accepts a string
    2. can cause nvim to cd
    3. can cause nvim to read a file
    4. can be expensive

I'm happy to contribute to any of the above.

Depending on the size and composition of the whitelist, I was thinking of introducing fuzzing tests (if they're not there already) on the sandbox and on all of the options that modelines supports.

**Comment by cmcaine** [comment]
options.txt documents a whole load of other options as being disallowed in modelines and sandboxes, so options.lua probably needs an update anyway :)

### Proposal

UX:

 - modelines only accept a whitelist of options
 - Whitelist is exposed as a setting for the user

Development:

 - Someone edits whatever interprets options.lua to understand the whitelist
 - We come up with a whitelist by either
    1. those supported by securemodelines + developer and reviewers pick the most obvious ones
    2. if someone can nominate a sensible corpus, someone can search for real-world use of modelines
    3. we come up with a more restrictive definition for modeline than "whatever vim supports" and the developer selects systematically from the ~100 buffer and window options available (assuming that there's no sensible use case for setting global options)
 - Someone needs to confirm that whatever bit of nvim reads in numbers and booleans from modelines is safe vs untrusted input (but if they're not, I'd expect someone to have published a CVE about it by now)
 - Settings like these will have to be examined carefully by developer and reviewers before inclusion:
    1. accepts a string
    2. can cause nvim to cd
    3. can cause nvim to read a file
    4. can be expensive

I'm happy to contribute to any of the above.

Depending on the size and composition of the whitelist, I was thinking of introducing fuzzing tests (if they're not there already) on the sandbox and on all of the options that modelines supports.

**Comment by justinmk** [comment]
> options.txt documents a whole load of other options as being disallowed in modelines and sandboxes, so options.lua probably needs an update anyway

Not sure what you mean. We're at parity with Vim there. `P_SECURE` is different than `P_NO_ML`.

**Comment by cmcaine** [comment]
My bad.

Does the rest sound OK?

**Comment by justinmk** [comment]
The steps I recommend are described in https://github.com/neovim/neovim/issues/2865#issuecomment-316180358 . 

Anything more complicated can go later.

**Comment by justinmk** [comment]
`modelineexpr` option exists in Nvim 0.4 / Vim 8.1 now, and it is disabled by default.
