### ISSUE TITLE
Cant build in my school 

### ISSUE THREAD

**Issue by dxrxbxk** [neovim/neovim#28749]
### Problem

when i try to build it gives this error:

```User
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Gettext (missing: GETTEXT_MSGMERGE_EXECUTABLE
  GETTEXT_MSGFMT_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindGettext.cmake:81 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/nvim/po/CMakeLists.txt:1 (find_package)
```
  
The solution is quite easy the comment this line in `src/nvim/po/CMakeLists.txt`
the line `find_package(Gettext REQUIRED)` which happens to be the first line needs to be commented 

### Steps to reproduce

make 

### Expected behavior

compiling

### Neovim version (nvim -v)

NVIM v0.10.0-dev-d2c9dc056

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu

### Terminal name/version

Terminal

### $TERM environment variable

xterm-256color

### Installation

Ubuntu 22.03

**Comment by clason** [comment]
But it is.

**Comment by dundargoc** [comment]
> Ubuntu 22.03

Is this even a real ubuntu version? Googling gives "did you mean ubuntu 22.04".

**Comment by zeertzjq** [comment]
Did you follow the instructions at <https://github.com/neovim/neovim/blob/master/BUILD.md#ubuntu--debian>?

**Comment by justinmk** [comment]
The only reason this issue is still open is because it originally asked:

> Why is the REQUIRED package not required to build the program ?

The answer (which is just a detail of our build system) is:
1. REQUIRED is the best way to get useful messages from cmake if we can't find a library that we want to use
2. For this particular case, gettext is needed to provide translations. That's not strictly necessary to build `nvim`, but it is a basic feature that we support so of course we need to mark it as required.

For your particular case, as @zeertzjq mentioned you need to install the gettext package on your system. As documented.

**Comment by dxrxbxk** [comment]
Well i forgot to say that gettext is already installed
