### ISSUE TITLE
Add background to StatusLineNC when termguicolors is disabled

### ISSUE THREAD

**Issue by stepanbujnak** [neovim/neovim#28796]
### Problem

<img width="922" alt="Screenshot 2024-05-17 at 02 19 46" src="https://github.com/neovim/neovim/assets/355614/23ff15ee-1d06-4bd6-9654-a6d9337905f9">

Above is a screenshot of neovim 0.10.0 running inside Terminal.app on macOS which doesn't support true colors with two windows (vertical split). Since there's no background color for the top window status bar, it makes it hard to distinguish where the top window ends and bottom window begins, especially when there's a lot of text.

### Expected behavior

Would it be possible to add a background color to the window status bar? Thank you.

**Comment by echasnovski** [comment]
The problem for default color scheme with 'notermguicolors' is that there is no good (robust and visually accessible) way to highlight non-active statusline to be distinguishable both from text and active statusline. The best compromise in my opinion is already present and it uses bold text in non-active statusline.

I'd suggest that the solution here is for users to adjust `StatusLineNC` to fit their taste. For example: `hi StatusLineNC cterm=bold,underline` (underline is used very sparingly due to not having good universal support) or `hi StatusLineNC ctermfg=12` (to highlight with different color).

**Comment by justinmk** [comment]
For non-truecolor, I think we should consider underline for the StatusLineNC. I can accept the arguments against it for truecolor, but not for 256 color case.

**Comment by echasnovski** [comment]
> For non-truecolor, I think we should consider underline for the StatusLineNC. I can accept the arguments against it for truecolor, but not for 256 color case.

Using `cterm=underline` is not a problem for me as far as aesthetic goes ('notermguicolors' case is more like "make as good as is reasonable" for me).

The main concern was that if terminal emulator does not support 'termguicolors' then it might as well not support underline.

So I guess the question is should it be `cterm=bold,underline` (more visible than necessary but safer for compatibility) or just `cterm=underline` (less noisy but less compatible)?

**Comment by justinmk** [comment]
> So I guess the question is should it be `cterm=bold,underline` (more visible than necessary but safer for compatibility) or just `cterm=underline` (less noisy but less compatible)?

Either is fine with me. Underline is a big help. IMO bold is not visually helpful so it makes no difference (though "bold" in ANSI colors can actually mean a different color).

**Comment by echasnovski** [comment]
> Either is fine with me. Underline is a big help. IMO bold is not visually helpful so it makes no difference (though "bold" in ANSI colors can actually mean a different color).

OK, `bold,underline` it is then.
