### ISSUE TITLE
Suggestion - Make :help windows open full window by default

### ISSUE THREAD

**Issue by marblenix** [neovim/neovim#2882]
When typing, for example: `:help vimwiki`, inside vim it always bothered me that the screen would be split, making me lose my place in my previous window while simultaneously not giving me enough room to view enough of the documentation for a plugin/feature/doc.

My suggestion is to possibly make a new tab for the help documentation, or even just replacing `:help thing` with `:help thing | only` (though that last one might be confusing).

**Comment by justinmk** [comment]
> making me lose my place in my previous window

It should not lose your place. `<c-w><c-w>` will return to the previous window, with the cursor where you left it.

> possibly make a new tab for the help documentation, 

You can put `:tab` in front of `:help` to open it in a new tab:

    :tab help thing


This is one of those things where, if your suggestion was implemented, I predict you might miss the old behavior in certain cases. There's no perfect solution, so that's why flexibility and familiarity with window management is really crucial. 

Where there is no unambiguous path to take, it's a good bet to stick with the current behavior.
