### ISSUE TITLE
Allow suppressing deprecation warnings with a flag

### ISSUE THREAD

**Issue by daedlock** [neovim/neovim#28845]
### Problem

When using the latest neovim version, I am getting many deprecation warnings for lua functions used by plugins I have installed. There is no way to fix/update the deprecated functions until the plugin maintainer updates their upstream. So, this leaves me having to keep dealing with deprecation warnings popups.

### Expected behavior

`nvim` should support a flag `--suppress-deprecation-warnings` to ignore the deprecation warnings

**Comment by wookayin** [comment]
I believe that's one of the purposes of nightly and devel versions. If you find it's annoying and interferes with your workflow, you should stick to a stable release (0.10) version instead of HEAD/nightly versions. Warnings are actually useful, although it may seem a bit inconvenient, to encourage plugin authors to fix the deprecated API as soon as possible while in the development cycle and before the full release.

As a last resort, you may even want to monkey-patch `vim.deprecate` in your config (or in the command line argument to `nvim`) to suppress all warnings.

**Comment by clason** [comment]
No, that would completely defeat the purpose of these warnings. We _are_ working to make them less intrusive, though.

**Comment by daedlock** [comment]
Seems like monkey patching `vim.deprecate' works in my case as @wookayin explained

**Comment by clason** [comment]
Let me be clear: that is **not** an official recommendation; in fact, we strongly recommend against it and instead fixing (or reporting) the deprecations.

**Comment by daedlock** [comment]
Understood, but it's good to have this option to temporarily get a normal experience until maintainers update their plugins.

**Comment by posixenjoyer** [comment]
Be all of this as it may, I'm getting warnings from lua scripts which are condition guarding deprecated code with version checks, and I'm being warned on the presence of deprecated code even when it can never be reached in the versions which have deprecated it.
