### ISSUE TITLE
New colorscheme breaks syntax highlighting of keywords

### ISSUE THREAD

**Issue by 00-kat** [neovim/neovim#28860]
### Problem

Things such as `for`, `if`, and other keywords have no color with the new Neovim theme.

C:
![image](https://github.com/neovim/neovim/assets/65649991/8009eccd-f9d6-4936-962b-72dc7e278956)
`#include` and `int` have no color.

Lua:
![image](https://github.com/neovim/neovim/assets/65649991/f68e6787-9fe1-4e96-8a7b-02a3b8f088ac)
`for`, `in`, `do`, `if`, `then`, `end`, `local`, etc. have no color.

Python:
![image](https://github.com/neovim/neovim/assets/65649991/215c66b0-b6c5-4d66-9106-2aeb325c3397)
`import`, `def`, `if`

I'm sure you get the idea by now.

### Steps to reproduce

```
nvim --clean
:set ft=yourfavouritelanguage
i
// type some code here
```

### Expected behavior

Perhaps a *little* more color?

Here's Neovim's old colorscheme (running v0.9.5 in these screenshots):
![image](https://github.com/neovim/neovim/assets/65649991/348c1391-c52d-4261-b828-2c2792c925a4)
![image](https://github.com/neovim/neovim/assets/65649991/efcf77f6-bbfe-4c95-ab78-ca5c48d54cc8)
![image](https://github.com/neovim/neovim/assets/65649991/3ed65552-4f9a-4c18-a2a4-0985b1463f35)

And here's the `vim.lua` colorscheme (I tried every other colorscheme that comes with Neovim, they all have color):
![image](https://github.com/neovim/neovim/assets/65649991/636bc2a0-82db-4f5b-851e-726d807f27b9)
![image](https://github.com/neovim/neovim/assets/65649991/4d841978-1cce-4e36-a3f6-ce2ea5d9c06b)
![image](https://github.com/neovim/neovim/assets/65649991/86273306-c3f5-4171-83e2-dbaa0e5cfc9c)

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux (rolling release)

### Terminal name/version

Kitty

### $TERM environment variable

xterm-kitty

### Installation

System package manager (pacman), AppImage

**Comment by rvolosatovs** [comment]
Just updated from dd00b6b442a6d3a8a4758b0ee10ac93d07e7db72 to 0.10.0 and also experiencing this issue.
I've been been using neovim pinnned to dd00b6b442a6d3a8a4758b0ee10ac93d07e7db72, since sometime after that commit, the issue appeared on nightly.

I believe the cause of this, last time I checked, was the fact that the colorschemes we are using do not support the treesitter (or was it LSP?) highlighting groups.

Interestingly, if I do something like:
```
:colorscheme vim
:colorsheme base16-tomorrow-night // that's the scheme I want to use
```

I do get *most* of the highlighting it seems

I also have the LSP -> treesitter hl group mapping set up as following:
https://github.com/rvolosatovs/nixelium/blob/720a2167c27152e564238075f0f1b7167f7ba049/overlays/neovim/config.lua#L318-L335

This mapping may be out-of-date at this point

**Comment by clason** [comment]
The minimality of the default colorscheme is deliberate and not up for debate; you are welcome to keep using other themes that are more to your taste.

**Comment by bew** [comment]
Having a new colorscheme is great, but if it is detrimental to the default user experience I'm not sure why it exists..
