### ISSUE TITLE
cmdline lua completion for `vim.fn.*` has missing items

### ISSUE THREAD

**Issue by camoz** [neovim/neovim#28910]
### Problem

Completion for `:lua vim.fn.*` does not work correctly, there are items missing.

### Steps to reproduce

- `nvim --clean`
- enter `:lua vim.fn.`
- press tab

Result: It completes to `:lua vim.fn.executable`. No other choices are shown, like when tryingn to complete `:lua vim.`.

### Expected behavior

Completion should show all possible options.

On my normal setup (personal config + some plugins, including nvim-cmp, but not cmp-cmdline), completing `:lua vim.fn.` shows some more options, but still not a complete list:

![screen_2024-05-22_074913](https://github.com/neovim/neovim/assets/6276613/fe85148f-baa5-4701-bef0-498d5005207b)

[This comment](https://github.com/neovim/neovim/issues/19623#issuecomment-1727751856) says that lua cmdline completion is implemented "a bit hacky". Maybe this is a symptom of this.

### Neovim version (nvim -v)

v0.10.0

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Archlinux

### Terminal name/version

foot version: 1.17.2

### $TERM environment variable

foot-extra

### Installation

official repos

**Comment by wookayin** [comment]
`:lua= vim._expand_pat('vim.fn.')` indeed returns `{ "exectuable" }` only in a fresh nvim 0.10, apparently the vimscript function `executable()` is used somewhere in the default startup script. On nvim 0.9.4, it will simply return `{}` (no completion).

This behavior is due to the specific implementation details of (hacky) Lua tab completion and `vim.fn`. In short, Lua completions for `vim.fn` will show **only the vimscript functions that has been invoked at least once via `vim.fn`**. This is because: (i) `vim.fn` works like a cache-like table that store all the function keys, and (ii) `vim._expand_pat` will suggest all the existing keys for a table instance (`vim.fn`).

To avoid the confusion, we can also change the implementation of meta-accessor `vim.fn` in a way that it does not cache the Lua bridge function to `vim.call`. However, a possible solution is to add an tab completion implementation for `vim.fn` specifically so that it can fully suggest the completion like `getcompletion(<query>, 'function')` would do.
