### ISSUE TITLE
nvim sends excessive amount of grid_cursor_goto when pmenu is open with ext_popupmenu

### ISSUE THREAD

**Issue by vhakulinen** [neovim/neovim#29086]
### Problem

With nvim 0.10, nvim sends excessive (endless) amount of `grid_cursor_goto` and `flush` messages when the popupmenu is open (with ext_popupmenu).

### Steps to reproduce

1. use a GUI that as externalized popupmenu implemented and enabled (requires ext_popupmenu)
2. get your nvim to a state that it shows the popupmenu
3. observe the endless cursor goto and flush events

I pushed a branch to gnvim to make testing easier: https://github.com/vhakulinen/gnvim/tree/debug/excessive-cursor-goto (https://github.com/vhakulinen/gnvim/tree/e8b72c3c543e0ed953579fbb8175cb59f2ea6039 for exact commit).

If you have all the requirements installed on your system (i.e. latest gtk4) you can just run `cargo run --bin gnvim -- --nvim-args "-u NONE"` to test with a plain nvim. You can also use flatpak (see the README instructions). The default `make run` uses flatpak, and that branch has the nvim args adjusted.

### Expected behavior

Not sending unnecessary cursor goto events.

### Neovim version (nvim -v)

NVIM v0.10.0

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Pop!_OS 22.04 LTS

### Terminal name/version

gnvim

### $TERM environment variable

-

### Installation

build from source

**Comment by vhakulinen** [comment]
Bisected to e778e0116198470ba037b9426f4ff7fa5cb7f880

**Comment by luukvbaal** [comment]
It seems that resetting [these](https://github.com/neovim/neovim/commit/e778e0116198470ba037b9426f4ff7fa5cb7f880#diff-53486731970573492a91272bd9c6b764402a36b087c2ad24fee49fd09fa1cbd3L1111-L1113) variables before flushing the ext UI to avoid recursiveness there, in turn results in recursive `showmode()`'s because they may be set to `true` again by the function itself. I guess we set them to false at the start **and** end of `showmode()`.

**Comment by vhakulinen** [comment]
Not sure if related, but with `fidget.nvim` I also tend to get a ton of cursor goto events when the fidget floating window is updating _and_ I'm in insert mode (not a problem when in normal mode).
