### ISSUE TITLE
Moving macros/matchit.vim to plugin/matchit.vim broke things

### ISSUE THREAD

**Issue by chris-morgan** [neovim/neovim#2918]
In #2723, runtime/macros/matchit.vim was moved to runtime/plugin/matchit.vim.

This is a bad thing for Vim compatibility, because any plugin that required matchit.vim will now be broken, because `source $VIMRUNTIME/macros/matchit.vim` no longer works.

I suggest that either `matchit.vim` should be moved back or a new blank stub `macros/matchit.vim` should be created.

cc rust-lang/rust.vim#38 (an example of this blowing up), #2676 (does this issue apply to more of the files?)

**Comment by Pyrohh** [comment]
I'd prefer a blank stub for the time being. cc @fwalch @fmoralesc.

**Comment by fwalch** [comment]
A blank stub seems to be the best equivalent of a "no-op". cc @justinmk

**Comment by fmoralesc** [comment]
This seems more like a bug in the plugins that source matchit than in the current behavior. matchit.vim has (obviosuly) side-effects, and it shouldn't be sourced by plugins directly. Instead, the plugin authors should point the user to enable the plugin (or do nothing in neovim's case), and put the matchit related behavior in a conditional depending on the plugin being enabled.

**Comment by fmoralesc** [comment]
Just opened a PR adding the stub file. 

@chris-morgan I still think this is an issue in the rust plugin, it shouldn't source that file in behalf of the user (specially if it's not documented). Instead it should document it supports matchit and suggest the user to enable it. Besides, it should suggest `:runtime macros/matchit.vim` instead of `:source $VIMRUNTIME/macros/matchit.vim`.
