### ISSUE TITLE
tsserver wrong autoimports with multiline imports

### ISSUE THREAD

**Issue by geril2207** [neovim/neovim#29286]
### Problem

Incorrect comma (,) position when using autoimports, if the imports already exist from the module(multiline formatting).
I made bisect and for me the problem was in https://github.com/neovim/neovim/commit/2ce4a4d91e4abee0aab8b98c47eea9fbd4849ba6

So the problem:

https://github.com/neovim/neovim/assets/62308020/2243dca7-1835-49ab-b7a5-f4038568865a

Could be duplicate of https://github.com/neovim/neovim/issues/29284

### Steps to reproduce

Sorry, I don't want to figure out, how can I provide it to you :). Maybe somebody from your team has already installed tsserver and has projects with typescript, and can reproduce it.

### Expected behavior

Works fine on https://github.com/neovim/neovim/commit/6e45cd7f0026ee33b8c397b810dcfe5b4678bbd8 (commit before)

https://github.com/neovim/neovim/assets/62308020/10bbab32-ee7d-4d9e-989f-b3b609111dad

### Neovim version (nvim -v)

above

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

fc 39

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by justinmk** [comment]
@alcolmenar

**Comment by alcolmenar** [comment]
Yea I was afraid that other LSPs might be providing the textEdits in a way just to make it work with Neovim. However, I wasn't able to reproduce this using `vtsls`. Which tsserver wrapper are you using?

It's possible that the LSP would need to be updated to account for the fix. The fix was made to match closer to VSCode's implementation here https://github.com/microsoft/vscode-languageserver-node/blob/main/textDocument/src/main.ts#L371

In regards to #29284 though, it appears unrelated since that seems like more of an issue with what autocomplete options are provided, but I may be totally wrong there. I'm new to the codebase

**Comment by iurimateus** [comment]
See https://github.com/pmizio/typescript-tools.nvim/blob/master/lua/typescript-tools/protocol/text_document/did_change.lua#L11

Also, vscode's typescript server doesn't comply with the spec (not sure what the state of tsserver/vtsls is).

**Comment by geril2207** [comment]
> I expect it to need the same patch as above).

Do you mean patch from `typescript-tools`? If so, `typescript-tools` have the same issue

**Comment by geril2207** [comment]
I think we can close it, because of the same idea as #29392.
