### ISSUE TITLE
TUI cursor shape does not reset correctly

### ISSUE THREAD

**Issue by smasher816** [neovim/neovim#2937]
I am currently using [termite](https://github.com/thestinger/termite/) (a vte based terminal) with the cursor set to an underscore. When setting `NVIM_TUI_ENABLE_CURSOR_SHAPE=1` neovim correctly turns the cursor into an ibeam as mentioned in the faq. However, when exiting insert mode the cursor changes to a block and remains that way even after closing neovim. As far as I know there is no way for me to get the underscore I have in my terminal configuration back without restarting the terminal emulator. It would be nice if neovim restored the original cursor shape instead of always making it a block.

I have made sure to update neovim, libvte, and termite to their latest versions.

**Comment by jszakmeister** [comment]
As far as I know, there's no way to query the cursor shape from the terminal.  As a result, Neovim can set it, but there's no way to restore a previous shape.  You'd have to introduce some other way of setting the shape on exit and then configure it.  Or, you could try creating a shell function to help launch nvim and set the cursor shape to underline after it returns using something like `printf "\033[4 q"`.

**Comment by smasher816** [comment]
Thanks @jszakmeister, that printf appears to work when back at the terminal prompt. Unfortunately using something like `autocmd InsertLeave * call system('printf "\033[4 q"')` does not appear to work.

**Comment by splinterofchaos** [comment]
Unfortunately, `system()` doesn't connect directly to the host terminal, but rather a pipe read by nvim and echoed on screen. I believe bang (`!`) commands might be the same any more.

**Comment by smasher816** [comment]
I also tried bang commands but they popped up the output in the "Press ENTER or type command to continue" box. I think the real solution is to have nvim respect t_SI and t_EI like vim does.

**Comment by justinmk** [comment]
> t_SI and t_EI to change the shape in vim

Currently we don't pay attention to any of those term code extensions defined by Vim.

**Comment by splinterofchaos** [comment]
Even `T_*` is insufficient for some terminals that do not support changing the cursor shape via escape codes. For example, gnome terminal, except the most recent, but perhaps we could ignore that for now.

@taruda had recommended defining environment variables for this to keep the TUI separate, which is why the options were removed. I think we could alternately restore them and also save them within TUI itself, just updating their values when the options are set, but I have not investigated this.
 
However, I am not sure how this would solve your problem since it would not make neovim reset the cursor shape on exit and we haven't implemented a way to arbitrarily that the shape.

See also: #2391 and #2583

**Comment by justinmk** [comment]
This is a libvte bug: https://github.com/neovim/neovim/pull/3110#issuecomment-131276376

**Comment by joelostblom** [comment]
@justinmk If I understand correctly, the linked bug in the vte-widget was fixed in vte version 0.42. However, I am still seeing this bug in gnome-terminal 3.22.1, which uses vte 0.46.1. I am using neovim 0.1.7 from the Arch User Repository.

@smasher816 Is this working for you after the fix in vte?

**Comment by justinmk** [comment]
@joelostblom https://github.com/neovim/neovim/issues/4867

**Comment by joelostblom** [comment]
Thanks!
