### ISSUE TITLE
In ssh session, neovim doesn't set osc52 provider even though all conditions are true

### ISSUE THREAD

**Issue by nighthawk469** [neovim/neovim#29504]
### Problem

From :h clipboard

```
Nvim will attempt to automatically determine if the host terminal emulator
supports the OSC 52 sequence and enable the OSC 52 clipboard provider if it
does as long as all of the following are true:

  • Nvim is running in the TUI
  • g:clipboard is unset
  • 'clipboard' is not set to "unnamed" or "unnamedplus"
  • $SSH_TTY is set

If any of the above conditions are not met then the OSC 52 clipboard provider
will not be used by default and Nvim will fall back to discovering a
clipboard-tool through the usual process.
```
All the conditions are true
- nvim is in the terminal UI interface
- echo g:clipboard: "Undefined variable: g:clipboard"
- set clipboard?: "clipboard="
- $SSH_TTY="/dev/pts/3"

I need to manually set the OSC52 provider for it to work. Then it works fine. I shouldn't need to maually set osc52 provider when connected via ssh.

### Steps to reproduce

Select text
Try to copy to system clipboard with "+y

See warning 
`clipboard: No provider. Try ":checkhealth" or ":h clipboard".`

### Expected behavior

It should copy to my system clipboard through the osc52 provider

### Neovim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS 14.5 ssh to Ubuntu 20.04

### Terminal name/version

iTerm2 3.5.3beta2

### $TERM environment variable

xterm-256color

### Installation

AppImage

**Comment by Ridhamz-nd** [comment]
I am facing the same issue with the same env except that $TERM=xterm-kitty.
I ran `printf $'\e]52;c;%s\a' "$(base64 <<<'hello world test clip')"` on the machine I'm ssh'ed into and then queried the clipboard on my local machine and I am able to get the hello world string.
Any directions to debug are much appreciated

**Comment by rzalawad** [comment]
So I found that text still wasn't copied when using the `nvim --clean -u clipconf.lua` option where clipconf.lua is
```lua
    vim.g.clipboard = {
      name = 'OSC 52',
      copy = {
        ['+'] = require('vim.ui.clipboard.osc52').copy('+'),
        ['*'] = require('vim.ui.clipboard.osc52').copy('*'),
      },
      paste = {
        ['+'] = require('vim.ui.clipboard.osc52').paste('+'),
        ['*'] = require('vim.ui.clipboard.osc52').paste('*'),
      },
    }
```
Apparently the `reg == '+'` check was failing in `vim/ui/clipboard/osc52.lua`. After launching with the above config, if I run `:set clipboard=unnamedplus`, then the default yank register becomes `+` and I am able to copy from the ssh'ed target to the local host.
So do we really need to make sure `clipboard` is not set to `unnamedplus` as mentioned in the docs?

**Comment by gpanders** [comment]
If all of those conditions are true then Nvim will send the XTGETTCAP query to determine if the terminal emulator even supports OSC 52. If your terminal emulator doesn't support XTGETTCAP then Nvim still will not enable OSC 52 (because it doesn't know if your terminal supports it).

For anyone having this issue, run the following in your shell:

```
printf '\x1bP+q4D73\x1b\\'
```

You should see something very similar to this be printed back:

```
P1+r4D73=5C455D35323B25703125733B25703225735C303037
```

Different shells might omit parts of this string, but you should at least get _something_.

iTerm2 shows `P0+r`, indicating that it does not support OSC 52 (this is wrong, it does support OSC 52 but iTerm is not communicating that information to applications. So this is an iTerm2 bug).

>So do we really need to make sure clipboard is not set to unnamedplus as mentioned in the docs?

The reason we don't set it automatically when `'clipboard'` is set to a non-default value is because copying via OSC 52 can be slow, and pasting can be even slower or (even worse) display an annoying prompt to the user every time they use `p`. If users want to use OSC 52 with `'unnamedplus'` anyway then they can configure OSC 52 manually, but we don't want to make that the default experience.

**Comment by nighthawk469** [comment]
Thanks, I raised an iTerm2 ticket here
https://gitlab.com/gnachman/iterm2/-/issues/11723

**Comment by nighthawk469** [comment]
Solved here https://gitlab.com/gnachman/iterm2/-/issues/11723
Thanks @gpanders
