### ISSUE TITLE
Change the character range of regex classes such as `\w` for Unicode support

### ISSUE THREAD

**Issue by alerque** [neovim/neovim#2965]
I originally posted this [as a question on Vi.SE](http://vi.stackexchange.com/q/3726/267), but it seems the only proper fix is going to be introducing new options to the way regular expressions work.

English language users probably don't have this trouble, but vim has always been pretty dumb when it comes to regular expressions. In my case most letters in the Turkish alphabet outside the EN alphabet don't seem to qualify as word characters.

Given a file that contains Turkish words such as:

> gerçekleşiyor

…the search expression

    /ger\wek

…will not match the start of the word. For whatever reason ç is not a word character.

This becomes maddening when plugins use `\w` as part of their regular expression repertoire. A case in point is `neocompcache`. Baring extra matching rule sets for some language syntax, autocomplete only happens in word sized chunks. When I'm writing large amounts of Turkish prose it would actually be handy to have functional autocomplete, but with most words being broken into smaller chunks with the Turkish characters left out it is beyond useless.

I propose that either the default values for the regular expression classes need to be expanded with a whole lot more Unicode smarts or the value needs to be user adjustable so that we can define what constitutes a word character.

**Comment by justinmk** [comment]
Doesn't `\k` already cover this>

**Comment by amerlyq** [comment]
I somewhat agree and somewhat not. Maybe `\k` is fine for some umlauts. But what to do if the text is a mess of at least three languages? Like some native, greek and english in math articles, moreover commented in fourth language of its reader/reviewer like japanese (but at least with spaces)?

I would rather explicitly add all multibyte punctuation to `[:punct:]` and multibyte spaces to `[:blank:]` and then redefine `\w` as `[^[:punct:][:blank:][:nonprint:]]`. There is no any smart fast solution possible at all, because even Perl despite better support for multibyte `\w` doesn't include all necessary multibytes in `[:punct:]`.

But we can't redefine any of char class in vim, so I also have to explicitly list all multibyte punct/blank in that long regex. It's ugly as hell, and I don't see how `\k` can help in this case. Manually supplying char ranges for each lang in use? I think my definition is more flexible and useful, despite being less accurate. But, again, ugly as hell.

**Comment by justinmk** [comment]
> But we can't redefine any of char class in vim, so I also have to explicitly list all multibyte punct/blank in that long regex. 

One can define aliases or mappings. Or script it.

> It's ugly as hell, and I don't see how `\k` can help in this case. 

`\k` is driven by `'iskeyword', you can set that option as needed.

In general there isn't going to be a nice solution to this because the problem itself is not nice. Redefining character classes isn't much different than scripting a custom command or mapping.

**Comment by amerlyq** [comment]
It's not about aliases/mapping for personal use but also mostly about plugins, which if not break itself then at least completely useless on such texts.
From `iskeyword` help:
```
	Multi-byte characters 256 and above are always included, only the
	characters up to 255 are specified with this option.
	For UTF-8 the characters 0xa0 to 0xff are included as well.
```
So, how can I exclude multibyte punct/blank by using `iskeyword`?

**Comment by justinmk** [comment]
> Multi-byte characters 256 and above are always included

That not mentioned directly in `:help 'iskeyword'`, unlike 'isprint' and 'isfname'. Did you try it?

Related: https://github.com/vim/vim/pull/1373

**Comment by amerlyq** [comment]
Yup, I messed with exert. It was really taken from `isfname` where pointed help of `iskeyword`.
Of course I tried that and most of `:punct:`(like various brakets) are correctly distinguished from multibyte word chars by `\k`, but not all. Some of them are questionable and unicode standard haven't decided on them.
What I asked by question "how to exclude multibyte" is related to `E474: Invalid argument:` for any of this:
```
set iskeyword=@,48-57,_,192-255,^￤
set iskeyword=@,48-57,_,192-255,^65508-65508
```
So, I cannot correct anything by `iskeyword` beside using separate explicit regex.

***

And, of course, `\k` won't help with various plugins, which use `\w` by default.
I suppose, you will address them as "broken", because they don't use `\k`.
But almost everywhere, when people think about word regex, they will think about `\w`, even for unicode.
Because `\k` contains lang-specific additional symbols for e.g. function identifiers, etc.
And then even in program code we need two different `\k` -- for unicode words in e.g. comments and for function identifiers in rest of code. I don't think you can freely merge those two categories.

And this returns us to original question: why we must keep `\w` as alias to explicit `[A-Za-z0-9_]`?
Neovim already moved to utf8-only anyways. So it's reasonable to have extended `\w` for unicode and use `:alnum:` if you need old restricted behavior explicitly. It's at least more reasonable than rewriting all plugins to use `\k` instead of `\w` and dealing with aforementioned issues of included additional symbols by `\k` in mixed code/text.

**Comment by justinmk** [comment]
> And, of course, `\k` won't help with various plugins, which use `\w` by default.
> I suppose, you will address them as "broken", because they don't use `\k`.

Not really, but many plugins intentionally use `\w` because `\k` is much slower.

> It's at least more reasonable than rewriting all plugins to use `\k` instead of `\w` and dealing with aforementioned issues of included additional symbols by `\k` in mixed code/text.

I'm not strongly against any of the ideas here, but I don't think your assertion should be taken for granted. Surreptitiously changing basic assumptions in plugins has already has been done _numerous_ times in Vim's history--and it makes life for plugin authors (and users, transitively) very unpleasant. 

The thing you're suggesting sounds convenient in a vacuum. It sounds fine for your scenario in this instant of time. And that's the reasoning that led to things like 'gdefault' and many other side-effects in Vim.

Anyways, it seems to me like a good first step would be to change `\k` to allow unicode ranges to be specified. That should be discussed at https://github.com/vim/vim first.

**Comment by amerlyq** [comment]
> many plugins intentionally use \w because \k is much slower.

I'm not against it. Those who care about performance tend to use the most performant way despite how it looks like. It's only about intuitive logic and usage convinience -- using the most comfortable and logical way as defaults and all other optimized ways through api with explicit restrictions. Maybe, the root of evil was inherited from vimscript, where interative usage in TUI/CLI wasn't strongly distinguished from scripting terms...
 
> The thing you're suggesting sounds convenient in a vacuum. It sounds fine for your scenario in this instant of time. And that's the reasoning that led to things like 'gdefault' and many other side-effects in Vim.

I know, sigh. And therefore won't advocate my opinion strongly either.

> Anyways, it seems to me like a good first step would be to change \k to allow unicode ranges to be specified. That should be discussed at https://github.com/vim/vim first.

Alright, lets halt this question and temporary become satisfied by extending iskeyword to unicode ranges...

**Comment by goerz** [comment]
Is there a ticket/plan for extending iskeyword to unicode?

**Comment by Arnie97** [comment]
Related ticket: https://github.com/vim/vim/issues/576
