### ISSUE TITLE
After update to 0.10.1 neovim doesn't recognize filetypes anymore

### ISSUE THREAD

**Issue by lukeflo** [neovim/neovim#29900]
### Problem

After updating neovim to 0.10.1 via my package manager, filetypes are not detected correctly anymore.

Instead, when I start neovim, it will show the following error message in the minibuffer:

```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: .../share/nvim/lazy/LazyVim/lua/lazyvim/config/autocmds.lua:130:
attempt to compare nil with number
stack traceback:
        .../share/nvim/lazy/LazyVim/lua/lazyvim/config/autocmds.lua:130: in function 'ft'
        vim/filetype.lua:2368: in function 'dispatch'
        vim/filetype.lua:2535: in function 'match'
        /usr/share/nvim/runtime/filetype.lua:14: in function </usr/share/nvim/runtime/filetype.
lua:10>
```

If I press `Enter`, the file will be opened but without any highlighting, plus the filetype in the info bar always says `unix`.

I checked the mentioned files at the named lines, but my knowledge of those nvim internal things is non-existing.

I did not make any changes to my neovim config since the update.

### Steps to reproduce

Unclear. Tried with the `minimal.lua` conf file, but nearly had to include my whole `init.lua` to reproduce the error.

### Expected behavior

Filetypes should be detected automatically as regular.

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: None LuaJIT 2.1.1720049189

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Void Linux

### Terminal name/version

foot version: 1.17.2 -pgo +ime +graphemes -assertions

### $TERM environment variable

foot

### Installation

xbps-install -Su neovim

**Comment by clason** [comment]
Obviously this is an issue with your config, since filetype detection is tested in our CI. The usual approach is required here: start with `nvim --clean`, and then add `nvim --clean -u test.lua`, adding settings and plugins from your config to `test.lua` _one by one_. The culprit is virtually guaranteed to be a plugin.

**Comment by clason** [comment]
And we do not support LazyVim; if you cannot reproduce this with a clean, minimal config, you need to report the issue there.

**Comment by echasnovski** [comment]
This seems to have nothing to do with core filetype detection. The traceback mentions it because it is when the error happens.

The true reason seems to be [this line](https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/config/autocmds.lua#L130) which indeed compares number (output of `vim.fn.getfsize()`) with something that is possibly `nil`.

**Comment by Brikkel** [comment]
@lukeflo Have you managed to fix it? I have the same issue and this is the only place where I can find someone who has the same error.

**Comment by mysterfr** [comment]
@Brikkel, I had the exact same issue, seems this workaround does the job.
In one of your nvim config files add

`vim.g.bigfile_size=1024*1024*1 -- 1M`

For context:
- ArchLinux
- nvim v0.10.1
- blank LazyVim configuration in "Structured setup" (conf files split in directories), following https://lazy.folke.io/installation
- enabled plugins : catppuccin (theme), LazyVim and Telescope

I added the above line in the .config/nvim/lua/config/lazy.lua

Hope this helps ! (it doesn't solve the root cause however)

**Comment by brymon68** [comment]
Thanks @mysterfr, that worked for me as well. FWIW, I was uninstalling and reinstalling lazyvim and ran into this error. Using the fix suggested by @mysterfr  though I do not understand why it breaks in the first place
