### ISSUE TITLE
Use :terminal for opening shell commands found in &keywordprg

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#2995]
Using `:!man date` (or `K` on a keyword) the whole man page gets shows, with the "Press ENTER or type command to continue" prompt at the bottom.

There's no way to scroll the previous/scrolled up output.

This is different from Vim, where the `less` pager is used in this case, and only after quitting it (`q`), the "Press ENTER or type command to continue" prompt appears.

The workaround seems to be using `:term man date`.
Maybe `:split | term` should be used instead of `:!` by default?! (and for `K` etc)

**Comment by ZyX-I** [comment]
This is intentional, `:!` no longer provides a terminal, so `less` used by `man` can no longer take over the screen. Note that `less` pager *is* used in both cases, just it works as `cat` if output is not to a tty.

For `K` it will use `:Man` command (#1878), but I also think it makes sense to use `terminal` for `K`. Not so sure about hardcoded `split`. For `:!` I do not think that `split | term` should be used because in many places shell commands are launched using `exe '!' …` or something like this, especially this is the case in user mappings; and those do not need a tty.

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/1496

**Comment by ZyX-I** [comment]
@justinmk I would not say that this should be closed: I think this issue needs to be reworded to “Use :terminal for opening shell commands found in &keywordprg”.

**Comment by borring** [comment]
@blueyed if you don't mind adding another Scratch buffer to your session, you
might be able to get away with using this workaround for K.

Some things to note, it selects the WHOLE word. It's neither an operator, nor
does it work in visual mode. This is just a barebones example of what kinds of
workarounds are already possible.

	function! MAN()
		let l:w = expand("<cWORD>")
		new
		let &buftype="nofile"
		execute "r!PAGER=cat man " . l:w
		set syntax=man
		normal gg
	endfunction

**Comment by justinmk** [comment]
Note to self: this also fixes https://github.com/neovim/neovim/issues/2761

**Comment by squdle** [comment]
@borring Thanks for posting that snippet. It's also possible to use &keywordprg so that this works for python or other filetypes - [gist of similar function](https://gist.github.com/squdle/f078f6cf2c0068770b1b0fdb5fcd5429#file-nvim_keyword_lookup-vim)
