### ISSUE TITLE
Support old macOS in the prebuilt binaries in GitHub Releases

### ISSUE THREAD

**Issue by hronro** [neovim/neovim#30102]
I can confirm simply change this line

https://github.com/neovim/neovim/blob/a8fbe1d409e08c68b05bc26b096486020ae3162b/.github/workflows/release.yml#L92

to
 
```
MACOSX_DEPLOYMENT_TARGET: 10.13
```

will make the neovim binary run-able in macOS 10.13, and all the main features (editing, tree-sitter) works perfectly.

I understand that old macOS [is not officially supported](https://neovim.io/doc/user/support.html). However, if a single line of code could make it compatible with older macOS versions, it would greatly benefit users like myself who still rely on older systems. While there may be bugs specific to older macOS versions, having it run is better than not having it at all.

**Comment by clason** [comment]
> While there may be bugs specific to older macOS versions, having it run is better than not having it at all.

That is simply not true. These builds are officially supported, so if they don't work fully, that _is_ a problem for us. We also rely on those for reproducing issues, and we don't want to deal with unsupported builds on top of that.

Dropping deployment target would also mean that we can't make use of newer APIs which users on supported platforms can profit from.

(Note that we didn't pick the number arbitrarily; we're limited by what our dependencies -- most notably libuv -- support. Just because _you_ don't happen to run into an issue doesn't mean there are none.)

So I'm afraid this is not a change we want to make. If you want to run Neovim on outdated platforms, you have to either
* run an outdated version that still supports these platforms or
* build it yourself (it's really easy!) and live with the consequences.

**Comment by dundargoc** [comment]
You could just fork neovim and make this change manually if you'd like, and use the releases from your own fork. That way you'd get releases that (potentially) works on older macos and we don't have to take on the extra maintenance burden.
