### ISSUE TITLE
Hitting Esc goes back the tag stack (does :pop)

### ISSUE THREAD

**Issue by shmerl** [neovim/neovim#3011]
I noticed that if I go down the stack of tags (using ctrl+]), hitting Esc takes you back in nvim (i.e. it does :pop) which is unexpected (I don't see such behavior in vim) and also very annoying because you can press Esc by mistake when you are already in normal mode (thinking you are going out of insert mode), and it messes up your stack position.

Is it a bug or an intended behavior? And if the later, how can it be disabled?

**Comment by justinmk** [comment]
Can't reproduce, please provide steps with `nvim -u NONE`.

**Comment by shmerl** [comment]
Hm, it indeed doesn't happen with -u NONE. So it's something messed up in my .nvimrc then?

Here is my [current configuration](https://gist.github.com/anonymous/7ab52770df756c1b9f15).

**Comment by justinmk** [comment]
Try removing these mappings:

https://gist.github.com/anonymous/7ab52770df756c1b9f15#file-gistfile1-txt-L74-L77

Also try using `nnoremap` instead of `nmap`. In general, don't use `*map`, use `*noremap` unless you know what you're doing.

Also try removing the F2, F3 mappings. Then we can figure out if this is a known bug or what.

**Comment by shmerl** [comment]
Ah, I found the culprit setting:

    map <C-[> :pop<CR>

Using noremap with it doesn't help. I think it's because Esc is equal to Ctrl + [... I guess that prevents neat mapping for stack movement. So it's not a bug really.

**Comment by justinmk** [comment]
Yep, I missed that :)

**Comment by shmerl** [comment]
Yep, that's a good enough alternative, I'll use that :)
