### ISSUE TITLE
How about improving f/t/F/T/;/, to be multiline movements by default?

### ISSUE THREAD

**Issue by 907th** [neovim/neovim#3015]
I think many of us use plugins (https://github.com/dahu/vim-fanfingtastic and others) for that. Multiline behaviour is very natural and usefull.

**Comment by justinmk** [comment]
Why does this need to be built-in?

**Comment by 907th** [comment]
@justinmk 

> Why does this need to be built-in?
 
Because it is very handy behaviour. Because plugins are buggy.

> Also, there's no chance that this would ever be the default.

Why not? Vim had introduced `nocompatible` mode, so why shouldn't NeoVim rethink Vim's defaults? E.g. Vim's registers are completely [broken](http://vimcasts.org/blog/2013/11/registers-the-good-the-bad-and-the-ugly-parts/).

**Comment by justinmk** [comment]
We want to concentrate on making it possible for plugins to be bug-free by addressing the key problems that cause that. It's a distracting time sink to add little features like this to the core. 

> Vim had introduced nocompatible mode, so why shouldn't NeoVim rethink Vim's defaults

Because the current default is valuable and there isn't overwhelming evidence that changing it would solve more problems than it causes. In such cases, we will simply break compatibility, rather than introduce a "no-vim-compat" mode, which will never happen.

**Comment by mhinz** [comment]
Using saner default values (that everyone sets in their vimrc anyway) for some options is one thing, but this would break lots of existing plugins and macros that rely on the current behaviour.

IMHO, plugins like mentioned above or sneak or easymotion do a superb job. Most of the time `/` and `#` are more than enough + they can be used as a motion, too.

**Comment by 907th** [comment]
@justinmk @mhinz Ok, I understand and accept your point. Thanks for the answers!
