### ISSUE TITLE
CTRL+C in unsaved file breaks clipboard

### ISSUE THREAD

**Issue by luxflux** [neovim/neovim#3023]
Pressing CTRL+C in a unsaved file breaks the clipboard functionality:

```
Error detected while processing /opt/boxen/homebrew/Cellar/neovim/HEAD/share/nvim/runtime/autoload/provider/clipboard.vim:
line    1:
Interrupted
Interrupt: Press ENTER or type command to continue
```

Afterwards, pasting and copying to system clipboard does not work anymore.

# Steps to reproduce:

* Create simplistic `.vimrc`
```vim
" .vimrc.test
set clipboard+=unnamedplus " http://neovim.io/doc/user/nvim_clipboard.html#nvim-clipboard
```

* Open new file
```bash
nvim -u .vimrc.test /tmp/new-file
```

* Press CTRL+C (switch to INSERT mode and press CTRL+C, doesn't matter)

If you save the file and press CTRL+C afterwards, it does not display an error.

# System

OS X 10.10.4, with neovim nightly build

```
$ nvim --version
NVIM 0.0.0-alpha+201507141425 (compiled Jul 15 2015 09:55:40)
Commit: 59784b91dbf97388281c1eb6989e2e770eb7ecac
Build type: RelWithDebInfo
Compilation: /opt/boxen/homebrew/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150715-1628-1w393a6/build/config -I/tmp/neovim20150715-1628-1w393a6/src -I/tmp/neovim20150715-1628-1w393a6/.deps/usr/include -I/tmp/neovim20150715-1628-1w393a6/.deps/usr/include -I/tmp/neovim20150715-1628-1w393a6/.deps/usr/include/luajit-2.0 -I/tmp/neovim20150715-1628-1w393a6/.deps/usr/include -I/tmp/neovim20150715-1628-1w393a6/.deps/usr/include -I/tmp/neovim20150715-1628-1w393a6/.deps/usr/include -I/tmp/neovim20150715-1628-1w393a6/.deps/usr/include -I/opt/boxen/homebrew/opt/gettext/include -I/usr/include -I/tmp/neovim20150715-1628-1w393a6/build/src/nvim/auto -I/tmp/neovim20150715-1628-1w393a6/build/include
Compiled by raf@nine.ch

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/opt/boxen/homebrew/Cellar/neovim/HEAD/share/nvim"
```

**Comment by bfredl** [comment]
can confirm, on arch linux and with `nvim -u NONE --cmd "set clipboard=unnamed"`. No need to name the file. The same error also in normal mode ctrl+c.

**Comment by mhinz** [comment]
The main problem is that `<c-c>` is a default mapping but also sets `got_int`.

Because of the former, `normal_cmd()` is kicked of which eventually leads to sourcing the clipboard provider. But due to the latter `do_source()` throws that error, because `got_int` is set.

You can press almost any key before `<c-c>` and you won't get that error, because by then the provider will be loaded already.

You can't remove that check from `do_source()`, because it can be called recursively.

Abusing `disable_breakcheck` is probably frowned upon.

I guess there will be a nice solution for it, when https://github.com/neovim/neovim/pull/2980 gets merged.

Until then I suggest loading the clipboard provider before starting `main_loop()`, since it will be loaded on the first keypresses anyway.

If you agree, I'll create a PR for it.

**Comment by bfredl** [comment]
I think I understand why: it must source the provider to determine the value of `v:register` when `clipboard=unnamed`. @mhinz sounds like a good fix :+1: Perhaps it should only force load it if `&clipboard` is set.

**Comment by mhinz** [comment]
Fixed.

**Comment by luxflux** [comment]
Thanks!
