### ISSUE TITLE
Problem with default colorscheme when using `termguicolors`

### ISSUE THREAD

**Issue by brianhuster** [neovim/neovim#31097]
#### This is the default colorscheme with `notermguicolors`
![Image](https://github.com/user-attachments/assets/d1613f90-90ee-4874-8146-742933754268)

#### This is the default colorscheme with `termguicolors`
![Image](https://github.com/user-attachments/assets/9e1ceb04-53c2-4ce6-8fd1-0d3412188b91)

As you can see, the color of the words "setup" and "import" looks very differently when `set notermguicolors`, but they become almost indistinguishable when `set termguicolors`. This problem happens in both Konsole and Kitty terminals

### Steps to reproduce

1. `nvim --clean`

2.`:e test.lua`
Enter these content to the file test.lua
```
require("lazy").setup({
	{ import = "plugins" },
})
```

3. Switch between `notermguicolors` and `termguicolors`, I think you'll see the difference

### Expected behavior

The color of the word `setup` and `import` in the picture I sent should be more distinguishable with `termguicolors`

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1092+g0da4d89558 Build type: RelWithDebInfo LuaJIT 2.1.1727870382

### Vim (not Nvim) behaves the same?

No, Vim doesn't have this colorscheme

### Operating system/version

Kubuntu 24.04.1

### Terminal name/version

konsole 23.08.5 and kitty 0.32.2

### $TERM environment variable

xterm-256color (konsole) and xterm-kitty (Kitty)

### Installation

snap

**Comment by echasnovski** [comment]
This is an intended behavior of default color scheme. You can take a look at #26334 and #26540 for more details. TL;DR:
- The 'notermguicolors' version of default color scheme uses colors from terminal emulator's palette, while 'termguicolors' uses specially designed palette.
- The application of 'termguicolors' palette is made so that the overall feel is "blue-green, like Neovim". The colors in question of this issue are light cyan and light blue from the palette. As they are designed to have the same (high) lightness, the current values are as different as they can be made (due to some elaborate color theory arguments).

**Comment by brianhuster** [comment]
Thanks for responding and letting me know more about the colorscheme. So my problem is that I can't tell apart NvimLightBlue and NvimLightCyan, is there a way I can change one of them to a different color? Thanks in advance

**Comment by echasnovski** [comment]
> So my problem is that I can't tell apart NvimLightBlue and NvimLightCyan, is there a way I can change one of them to a different color?

Not without modifying source code ([this portion](https://github.com/neovim/neovim/blob/5a86360400691e55fae66d60485b61360a1d3d6c/src/nvim/highlight_group.c#L2935-L2936)) and manually building it. Otherwise I'd suggest overriding all highlight groups which use `NvimLightBlue` (there are only [three](https://github.com/neovim/neovim/blob/5a86360400691e55fae66d60485b61360a1d3d6c/src/nvim/highlight_group.c#L482) [of](https://github.com/neovim/neovim/blob/5a86360400691e55fae66d60485b61360a1d3d6c/src/nvim/highlight_group.c#L493) [them](https://github.com/neovim/neovim/blob/5a86360400691e55fae66d60485b61360a1d3d6c/src/nvim/highlight_group.c#L498)).
