### ISSUE TITLE
Search init.vim in &runtimepath

### ISSUE THREAD

**Issue by Yamakaky** [neovim/neovim#3127]
Sub thread of #3120 

Currently, a list of system and user files set at compilation are sourced. I suggest to source all init.vim files in &runtimepath in reverse order. So with &runtimepath=/a,/b,/c, vim would source /c/init.vim then /b/init.vim then /a/init.vim. It would allow distros to provide an init file, whose values could be changed in the user's init.vim.

Problem:
 - &runtimepath can be modified by one of the init.vim

**Comment by ZyX-I** [comment]
It is useless to discuss this suggestion without showing how you are going to solve this problem because of the downsides of each of the possible solutions.

Also do not forget that it would not allow distros anything more then what is currently allowed. I do not know whether NeoVim did (not) destroy this, but Gentoo Vim sources /etc/vim/vimrc fine. Given that /etc/vim/nvimrc exists (and I did not add it myself) I think that so does NeoVim.

My opinion is that

1. If XDG_\*_DIRS are not included in &runtimepath then just do equivalent of `runtime init.vim` (i.e. source whatever init.vim found first), then source distro init.vim (hardcoded at compile time). (Neither applies to invocation with `-u`.) This is also fine for me if XDG_\*_DIRS *are* included.
2. If XDG_\*_DIRS are included then do according to the suggestion, but use *only* default value of `&runtimepath`. This should simplify the code, and is XDG-compliant: X base directory specification does not say anything about `&runtimepath`. In this case documentation should say that `init.vim` files are taken from XDG directories, not mentioning `&runtimepath` at all to avoid questions like “I have used `--cmd 'set runtimepath=…'`, but it was ignored”.
3. Like above, but use effective `&runtimepath` value. This allows overriding directories using `--cmd`, but that’s all.
4. Keep directories that were already used over in a hash. If `&runtimepath` changed then restart sourcing from scratch, but ignore directories that were be found in a hash. Biggest downside here is that the resulting init.vim sourcing order may be very different from the one specified in `&runtimepath` at the end.

**Comment by Yamakaky** [comment]
debian sources a file in /usr by patching vim.

**Comment by Grimy** [comment]
The current `&runtimepath` mechanism is entirely fine and offers as much flexibility as you can possibly need. By default, the last entry is `$HOME/.nvim/after`, which means that you can override options set from wherever else by creating a `$HOME/.nvim/after/plugin/init.vim` file.

Since your nvimrc is parsed first, you can also take the chance to set `&runtimepath` to a sensible value: mine is `$VIM,$VIM/bundle/*`, which completely bypasses the distro config.

Of course, if Debian actually patched Vim instead of using the built-in `&runtimepath` mechanism (which is completely retarded), this won’t work.

**Comment by justinmk** [comment]
Agree with @Grimy's comment.

>  I suggest to source all init.vim files in &runtimepath in reverse order.

Why?

>  It would allow distros to provide an init file

I don't *want* distros to provide init files. Distros should ship the Neovim defaults, period. If they want to fork Neovim then they can do so and call it IceWeasel or something. I strongly encourage package maintainers to avoid the fragmentation that has occurred with the various distro vimrcs doing whatever they feel like. `/etc/nvim/init.vim` (or some equivalent thereof) exists for system administrators, but package maintainers should leave it the hell alone.

@ZyX-I variant 1 sounds simplest (and therefore the best) to me, but I don't completely understand it. Why does it matter if `XDG_*_DIRS` are included in `&runtimepath`? I thought the point of `XDG_CONFIG_HOME` (for example) is that we must respect it if the users specifies it. What different does it make if `&rtp` has it?

**Comment by ZyX-I** [comment]
@justinmk XDG_CONFIG_HOME is *one* of the directories where configuration is searched. There are also others, listed in XDG_CONFIG_DIRS. My suggestion was to include in `&runtimepath` all of the configuration directories.

And plugin files are not a configuration, thus XDG_DATA_\*. It was included in the latest version of the suggestion.

Preferring this variant over second only in case XDG_\*_DIRS are not included is what I think should be consistent with the specification, *and* allows distro maintainers to have their configuration. I have no objections to it if distro maintainers are sensible enough (BTW: Gentoo ones are not) to include only distro-specific fixes and put this thing in `/etc` (which is good because package managers allow editing files there). Though I have rather strange second suggestion thus: it should only talk about XDG_CONFIG_HOME and XDG_CONFIG_DIRS, but not about &runtimepath or its default at all.

**Comment by justinmk** [comment]
> it should only talk about XDG_CONFIG_HOME and XDG_CONFIG_DIRS, but not about &runtimepath or its default at all.

@ZyX-I  Not sure if I understand, but I think it makes sense to read `init.vim` *only* from `XDG*` directories. This is analogous to `vimrc` which is *not* read from `&rtp`, it is only read from specific locations.

Perhaps we should rename `init.vim` to `nvimrc` so that this distinction remains clear.

**Comment by ZyX-I** [comment]
@justinmk Second variant suggested to read only from new default &runtimepath. Its contents is detailed in #78, last edit of the first message.

New variant of second suggestion should be read as following: “read init.vim from the following directories (in order): $XDG_CONFIG_HOME/after/init.vim, $xdg_config_dir/after/init.vim (for each … in reverse order), $xdg_config_dir/init.vim (for each …), $XDG_CONFIG_HOME/init.vim”. This is like &runtimepath, but a) reversed and b) without directories deriving from VIMRUNTIME and XDG_DATA\*.

**Comment by jck** [comment]
Instead of using defines, I think we should  do something like this: https://github.com/jck/neovim/tree/xdg2

**Comment by justinmk** [comment]
@jck I saw that. I'm normally in favor of avoiding macros, but what's the advantage in this case?

**Comment by justinmk** [comment]
Actually, I see that you took care of some logic that is missing from #3120 and also avoid adding magic to `vim_getenv()`. Looks nice to me.

**Comment by jck** [comment]
Additionally, we can define `std_paths_spec` for each platform separately. All the other logic can be reused.

**Comment by justinmk** [comment]
@Yamakaky what do you think about using https://github.com/jck/neovim/tree/xdg2 ?

**Comment by Yamakaky** [comment]
In fact, debian adds a SYS_VIMRC_FILE2. See [vim_7.4.712-3.debian.tar.xz] in https://packages.debian.org/sid/vim-runtime.
Looks nice to me, I made some comments on https://github.com/neovim/neovim/commit/8fc097657d9adf4a81cb2ee03c29de6fb8f5bf16.

So will we use XDG* on windows even if it's a linux only standard ?

**Comment by jck** [comment]
> So will we use XDG* on windows even if it's a linux only standard ?
Only if the user explicitly defines these env vars. Otherwise, they will fallback to standard windows paths (like this: http://doc.qt.io/qt-5/qstandardpaths.html)

**Comment by justinmk** [comment]
@jck Did you get a chance to open a PR for your changes?

**Comment by jck** [comment]
I've resumed work on this here: https://github.com/jck/neovim/tree/xdg

I will open a PR later this week.
