### ISSUE TITLE
After setting `'guicursor'`, the `'background'` cannot be changed anymore

### ISSUE THREAD

**Issue by ofseed** [neovim/neovim#31360]
### Problem

In dark mode systems, after setting `guicursor` to `n:block-Cursor/lCursor` in nvim, and then using `background` set to light color, the colors in nvim will briefly change to light color, but will immediately revert to dark color.

The terminal request was likely responded or handled to incorrectly, which may related to https://github.com/neovim/neovim/pull/31350.

### Steps to reproduce

1. Set system to dark mode.
2. `nvim --clean`
3. `:set guicursor=n:block-Cursor/lCursor`
4. `:set background=light`

### Expected behavior

background changed to `light`.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1242+gd460928263

### Vim (not Nvim) behaves the same?

no, vim 9.1.787

### Operating system/version

NixOS

### Terminal name/version

ghostty 0.1.0-12fc439-nix

### $TERM environment variable

xterm-ghostty

### Installation

build from repo

**Comment by justinmk** [comment]
Same root cause as these?

- https://github.com/neovim/neovim/issues/23122
- https://github.com/neovim/neovim/issues/21018
- https://github.com/neovim/neovim/issues/6591
- https://github.com/neovim/neovim/issues/6477
- https://github.com/neovim/neovim/issues/6425

**Comment by gpanders** [comment]
I know what the problem is here, but not sure how to solve it. What we need is a way to more accurately detect where/how an option was set. So that if `'background'` is set outside of `_defaults.lua` we delete the autocommands that auto-update `'background'`.

By the way, what is the use case for updating `'background'` like this? This option *should* be one that doesn’t need to be set manually in most cases.

**Comment by gpanders** [comment]
Short term workaround is to delete the TermResponse autocommand in the `nvim_tty` augroup.

**Comment by ofseed** [comment]
> By the way, what is the use case for updating `'background'` like this? This option _should_ be one that doesn’t need to be set manually in most cases.

I found that the issue is that my current configuration causes nvim to flash black for a moment before switching to the system/terminal's light color. During debugging with `print`, I discovered that every time I switch vim modes, it triggers `OptionSet background`, which ultimately led me to this problem.

**Comment by gpanders** [comment]
The color palette update notifications spec was updated to clarify that the DSRs should only be sent when the color palette changes via a configuration or system theme change, _not_ when any palette was updated via an escape sequence. See https://github.com/contour-terminal/contour/issues/1659 and https://github.com/contour-terminal/contour/pull/1683 for more context.

That means this issue is now squarely a terminal issue, as there's nothing else for Nvim to do. Ghostty has an open issue here https://github.com/ghostty-org/ghostty/issues/3965. For kitty this was never a problem because Kitty only sends the DSR when the background color changes (not for cursor color or other palette changes).
