### ISSUE TITLE
`set all&` sometimes incorrectly sets `&modified`

### ISSUE THREAD

**Issue by Grimy** [neovim/neovim#3143]
Even though the documented default value of `&modified` is false, `set all&` will sometimes change it from false to true.

How to reproduce
----------------------------

    echo >repro
    nvim -u NONE repro +w +'set modified? all& modified?'

Expected results
--------------------------

    nomodified
    nomodified

Actual results
--------------------

    nomodified
      modified

**Comment by ZyX-I** [comment]
I would not say this is a bug. `&modified` is a flag that indicates that file contents is modified. If file contents change because setting change this flag should also be set. Settinds that can change file contents:

- `binary+noendofline` switched to `nobinary` (default) or `binary` (not default) + `endofline` (default).
- `fileencoding` switched to any value, but the one it was when last writing.
- `fileformat` switched to any valu, but the one it was when last writing.
- `binary` switched to `nobinary` with `fileformat` not equal to `unix`.

If this is one of the cases, then `modified` setting *must* be set and I would say it is an error that `set all&` does not set this setting.

// Though `modified` would actually be better be `v:modified` variable because buffer modification state is not a setting.

**Comment by ZyX-I** [comment]
I am marking this issue as INVALID, but will not close it until you confirm that this is one of the valid cases.

**Comment by Grimy** [comment]
You’re right. When the file is first read, `&fileencoding` is automatically detected (based on `&fileencodings`) to be `utf-8`. `set all&` then sets it to its default value, which is empty. Even though the file is not modified by this encoding change, this sets the modified flag. This is surprising behavior, but not actually a bug. It’s also consistent: `:%!sed ''` also sets the modified flag, even though is doesn’t change the file.

A way to fix my use-case would be to change the default value of `&fileencoding` to `utf-8`. This sounds like an overall good change, and it’s consistent with the new default for `&encoding`. Should I open an other ticket for that suggestion?

**Comment by justinmk** [comment]
Sure
