### ISSUE TITLE
Terminal cursor disappears

### ISSUE THREAD

**Issue by seblj** [neovim/neovim#31612]
### Problem

After the recent changes to the terminal cursor, I found a case where it disappears. So, I like to be able to hide my cursor and show a cursorline in some windows like startify and some popups in a `vim.ui.select` implementation I have for example.

I have these hacky autocmds that makes this possible, and it has worked pretty okay for me for quite some time.

After the recent changes, I saw that the cursor disappears in the terminal, and was able to come up with this minimal example.

It is probably not meant to hide the cursor like this, but I thought I would create an issue since I didn't really have an issue with this before the term cursor PR

### Steps to reproduce

```lua
vim.api.nvim_create_autocmd("TermOpen", {
	pattern = "term://*",
	callback = function()
		vim.cmd.startinsert()
	end,
})

local guicursor_saved = vim.opt.guicursor

function HideCursor()
	local bufnr = vim.api.nvim_get_current_buf()

	vim.api.nvim_set_hl(0, "CursorTransparent", { strikethrough = true, blend = 100 })
	vim.opt.guicursor = vim.opt.guicursor + "a:CursorTransparent/lCursor"
	vim.wo[0][0].cursorline = true
	vim.wo[0][0].winhighlight = "CursorLine:Error"

	local group = vim.api.nvim_create_augroup("HiddenCursor", { clear = true })
	vim.api.nvim_create_autocmd({ "BufEnter", "WinEnter", "CmdwinLeave", "CmdlineLeave" }, {
		group = group,
		buffer = bufnr,
		callback = function()
			vim.opt.guicursor = vim.opt.guicursor + "a:CursorTransparent/lCursor"
		end,
	})
	vim.api.nvim_create_autocmd({ "BufLeave", "WinLeave", "CmdwinEnter", "CmdlineEnter" }, {
		group = group,
		buffer = bufnr,
		callback = function()
			vim.schedule(function()
				vim.opt.guicursor = guicursor_saved
			end)
		end,
	})
end

```

1. Create a file `init.lua` with the contents (for example '~/.config/term/init.lua`
2. Open neovim: `NVIM_APPNAME=term nvim`
3. `:lua HideCursor()`
4. `:vs`
5. `:term`
6. `<C-\><C-n>`
7. Press `i` to enter insert mode and notice the cursor disappears

I noticed that if I remove the autocmd, then it doesn't seem to disappear

### Expected behavior

The cursor not to disappear

### Nvim version (nvim -v)

v0.11.0-dev-1372+g0dd933265f

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 15.1.1

### Terminal name/version

kitty 0.34.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by gpanders** [comment]
Thanks for the bug report. I'm able to reproduce and am investigating now.

**Comment by gpanders** [comment]
If you change

```lua
vim.schedule(function()
  vim.opt.guicursor = guicursor_saved
end)
```

to simply `vim.opt.guicursor = guicursor_saved` then the issue no longer reproduces.

This is what's happening:

1. On `:term`, the `BufLeave` autocommand fires, and schedules the change to `'guicursor'`
2. Before that change occurs, the `terminal_enter` function is called. This function saves the existing value of the terminal cursor in `'guicursor'` so that it can be restored when Terminal mode ends. At this point, `'guicursor'` hasn't been changed yet, so it still has `a:CursorTransparent/lCursor`. That is the value that gets saved
3. While Terminal mode is active, `'guicursor'` is modified
4. When Terminal mode ends (`<C-\><C-N>`) the saved terminal cursor value is restored (and so is assigned the `CursorTransparent` highlight group again)
5. When you re-enter terminal mode, the `CursorTransparent` highlight group is applied

If you remove the `vim.schedule` then the `'guicursor'` option is changed before step (2) above.

Still need to find the proper fix to prevent this from happening when vim.schedule is used.

**Comment by seblj** [comment]
Okay thanks! I added that vim.schedule back in the day because I was getting some race condition with the autocmds
