### ISSUE TITLE
LSP: get resolved config from vim.lsp.config

### ISSUE THREAD

**Issue by konradmalik** [neovim/neovim#31640]
### Problem

Was playing with the new `vim.lsp.config` functionality (https://github.com/neovim/neovim/pull/31031) and I've either found a bug or I misunderstand the behavior of this functionality.

The issue is that it seems like any configuration defined in `lsp/*.lua` cannot be retrieved afterwards. Namely - contents of `vim.lsp.config` are empty despite the fact that servers seem to start and work properly, as configured.

What's interesting is that if I call `vim.lsp.config('somelsp', {...})` outside `lsp/*.lua` (e.g. in `init.lua`) then I indeed can access it through `vim.lsp.config`.

So, TL;DR - configs defined in `lsp/*.lua` are not visible in `vim.lsp.config`, but the ones defined somewhere else are visible.

Is this a bug or a feature?

### Steps to reproduce

```lua
-- Given tree:
-- nvim/
-- ├── init.lua
-- ├── lsp
-- │   └── gopls2.lua
-- └── main.go -> just empty file

-- lsp/gopls2.lua
print("loading gopls2")
vim.lsp.config("gopls2", {
	cmd = { "gopls" },
	root_markers = { "go.work", "go.mod", ".git" },
	filetypes = { "go" },
})

-- init.lua
print("loading gopls1")
vim.lsp.config("gopls1", {
	cmd = { "gopls" },
	root_markers = { "go.work", "go.mod", ".git" },
	filetypes = { "go" },
})

vim.lsp.enable("gopls1")
vim.lsp.enable("gopls2")
```

Then:
```lua
-- at start prints
loading gopls1

-- output of :lua= vim.lsp.config
{
  _configs = {
    gopls1 = {
      cmd = { "gopls" },
      filetypes = { "go" },
      root_markers = { "go.work", "go.mod", ".git" }
    }
  },
  <metatable> = {
    __call = <function 1>,
    __index = <function 2>,
    __newindex = <function 3>
  }
}
```

Ok, so `lsp/*.lua` files seem to be loaded lazily. Let's open a `main.go` then:
```lua
-- execute :e main.go
-- it prints
loading gopls2

-- then output of :lua= vim.lsp.config
{
  _configs = {
    gopls1 = {
      cmd = { "gopls" },
      filetypes = { "go" },
      root_markers = { "go.work", "go.mod", ".git" }
    }
  },
  <metatable> = {
    __call = <function 1>,
    __index = <function 2>,
    __newindex = <function 3>
  }
}
```

Also note that `gopls1` is defined only for clarity and comparison. The behavior for `gopls2` is the same whether we include `gopls1` or not. 

### Expected behavior

I expected the output of `vim.lua.config` at the very end to be:
```lua
{
  _configs = {
    gopls1 = {
      cmd = { "gopls" },
      filetypes = { "go" },
      root_markers = { "go.work", "go.mod", ".git" }
    },
    gopls2 = {
      cmd = { "gopls" },
      filetypes = { "go" },
      root_markers = { "go.work", "go.mod", ".git" }
    }
  },
  <metatable> = {
    __call = <function 1>,
    __index = <function 2>,
    __newindex = <function 3>
  }
}
```

### Nvim version (nvim -v)

from https://github.com/neovim/neovim/commit/17383870dd3b7f04eddd48ed929cc25c7e102277

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

nixos

### Terminal name/version

alacritty

### $TERM environment variable

tmux-256color

### Installation

https://github.com/nix-community/neovim-nightly-overlay

**Comment by justinmk** [comment]
`_configs` is private so its contents shouldn't matter. Does `vim.lsp.config['gopls2']` return the correct thing, or not?

**Comment by konradmalik** [comment]
Nope:
```lua
-- vim.lsp.config['gopls1']
{
  cmd = { "gopls" },
  filetypes = { "go" },
  root_markers = { "go.work", "go.mod", ".git" }
}

-- while vim.lsp.config['gopls2']
{}
```

This is the same whether I open `main.go` or not.

**Comment by clason** [comment]
No, it won't. The issue here is that all these data structures do not hold the resolved config; for that you need the (private!) `vim.lsp._resolve_config()`. Nobody has provided a compelling use case for exposing that so far, so at the moment LSP config is "write only".

**Comment by konradmalik** [comment]
@clason 
Thank you, now is starts to make sense.

The problem I see is that `vim.lsp.config` is public. As a user, it's weird to me that I'm 'not meant to access this'. I mean, I've just written some data to it, it's confusing that it's not there. Where is it then? (now I know where 😄)

One use-case I'd see for accessing this is - let's say some plugin defines `vim.lsp.config['gopls']` in their `lsp/gopls.lua`.
Then I start this server and I don't know why it behaves this way (e.g. experimental feature or gopls is enabled but it's buggy), so I investigate my configuration but... I don't see it at all. Seems like I could use private `vim.lsp._resolve_config` for that but (even if it was public) it's not obvious that I **should not** use `vim.lsp.config` for this.

**Comment by clason** [comment]
> The problem I see is that vim.lsp.config is public.

This is just how tables work. The documented(!) interface is the  `vim.lsp.config()` _function_.

**Comment by konradmalik** [comment]
> > The problem I see is that vim.lsp.config is public.
> 
> This is just how tables work. The documented(!) interface is the `vim.lsp.config()` _function_.

but what about `:h vim.lsp.config` ?

```
    • Get configuration for luals: >lua
        local cfg = vim.lsp.config.luals
```
Seems like this is not true and should not be used.

**Comment by justinmk** [comment]
Is there a technical reason why we can't make `vim.lsp.config['foo']` return the resolved config (as a deep-copy, i.e. "immutable")?

**Comment by lewis6991** [comment]
If debug is all you need. Then use `:checkhealth vim.lsp` to view resolved configurations.

**Comment by lewis6991** [comment]
> Is there a technical reason why we can't make `vim.lsp.config['foo']` return the resolved config (as a deep-copy, i.e. "immutable")?

We could, but this does a potentially expensive rtp lookup which won't be obvious to users. I added the resolved configurations in to checkhealth for this reason.

And to note, because the configurations are resolved after running any Lua code, what you get from resolving configurations isn't guaranteed to always be the same that servers are started with. Especially if users run `lsp.config` in a `lsp/*.lua` file.

**Comment by mfussenegger** [comment]
>  Nobody has provided a compelling use case for exposing that so far

One use case is to allow users to use the config via `lsp.start` for more explicit control over when the session gets started. For example, if you don't want to have it auto-start. One could of course pass the full config to `lsp.start` instead of working via `lsp.config` but that means plugins which register `*` configurations or language specific extensions won't work out of the box. If either `lsp.config.luals` or `lsp.config("luals")` returned the full configuration one could use it with `lsp.start(lsp.config...)` 

Another use-case that I have is supporting `lsp.config` in `nvim-jdtls` and have `lsp.enable("jdtls")` "just work", while still using `lsp.start` myself - mostly because I have language specific logic in `ftplugin/<lang>` files and I would prefer keeping it that way for java. Switching to `lsp.config` and `lsp.enable` means I'd have to move that into `init.lua` or start some `lua/conf/java.lua` split.
(I could support lsp.config without using it myself, but that means I won't notice issues as easily)

---

> We could, but this does a potentially expensive rtp lookup which won't be obvious to users.

Given that most people won't have a table lookup in their configuration unless they want to see the full configuration, is the performance aspect really a problem?

Or looking at it from the other side - in which scenarios does one want to do a lookup _without_ seeing the rtp parts too?
