### ISSUE TITLE
`:vertical terminal` should open a vsplit

### ISSUE THREAD

**Issue by thirtythreeforty** [neovim/neovim#3192]
Currently, running any of the following has the same effect as just running `:terminal`:
- `:vertical terminal`
- `:split terminal`

I'm not sure if this is by design or not, but it's certainly unexpected.  It would be great if these would act similarly to other commands that begin with `vert`, such as `:vert help`.

As baumy pointed out in #neovim, a decent workaround is `:vert sp | term`.

**Comment by thirtythreeforty** [comment]
If someone could please point me at the relevant parts of the code, I might try implementing this myself.

**Comment by ZyX-I** [comment]
1. `:terminal` command does *not* open a new window. Thus `vertical terminal` behaves *exactly* as documented. `:help` command *does* open a new window, so `:vert help` works.
2. `split terminal` should open the window named `terminal` according to the documentation. It is exactly what it does. Unlike `vertical` `split` command is not a modifier.

@justinmk  Unless someone is going to decide that `terminal` should open a new window this issue should be closed because all commands behave as documented and their behaviour is compatible. I also remember seeing some other issues that can be considered duplicate. I think that since this feature is highly requested someone may open a feature request to add `:sterminal` and `:vterminal` commands. But this request is invalid and inconsistent.

**Comment by ZyX-I** [comment]
Duplicate of #2315. As `:vertical` `:tab` is also a modifier that works when command opens a new window, this is why I mark it as duplicate.

**Comment by Brokenhammer72** [comment]
how can i make this open horizontal?

**Comment by mhinz** [comment]
For usage questions, see https://neovim.discourse.group.

(The answer is `:sp +te` or `:sp | te` or `:sp | te cmd arg1 arg2`.)

**Comment by m-ocean-it** [comment]
@mhinz @nackjicholson But how to open a terminal to the right side?

**Comment by mhinz** [comment]
> For usage questions, see https://neovim.discourse.group.
