### ISSUE TITLE
write a plugin with Go

### ISSUE THREAD

**Issue by 7belrhalmia** [neovim/neovim#3218]
i wont to write a plugin for nvim with go language but idon't now how to get nvim run a plugin with Go code

**Comment by tarruda** [comment]
The first step is to get familiar with the remote plugin architecture: http://neovim.io/doc/user/remote_plugin.html#remote-plugin

Then write a plugin host for go. I think @myitcv already got started, maybe you can pick where he left off.

**Comment by myitcv** [comment]
@7belrhalmia I did make a start around this time last year which I've just given a small refresh. Still very much work in progress because of time constraints but please see https://github.com/myitcv/neovim for an idea of where things stand.

Any help much appreciated, otherwise I will happily try and field any questions/suggestions
