### ISSUE TITLE
strftime() ignores in-session $TZ value

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#3264]
Consider the following script:

```
let $TZ='UTC'
echo strftime('%H', 0)
```

. In Vim this will yield `00`. In NeoVim this yields `03` (TZ is unset when session starts, system timezone is Europe/Moscow). It would actually be better to have third (timezone) argument to `strftime()`, but current variant is not compatible in any case.

**Comment by tarruda** [comment]
I have taken a quick look at f_strftime and couldn't find why nvim has this behavior, but it has something to do with how it sets environment variables because `strftime(3)` clearly states that it uses the `$TZ` environment variable and both vim and nvim call that function.  Closing in favor of #3265.

**Comment by ZyX-I** [comment]
@tarruda I do not see how is #3265 related?

**Comment by justinmk** [comment]
Can't reproduce this on macos but maybe `$TZ` is not respected there (not mentioned in `Man strftime(3)`).

Can someone check this on linux?

**Comment by zeertzjq** [comment]
Cannot reproduce on Linux either.

**Comment by zeertzjq** [comment]
Cannot reproduce on Linux either.
