### ISSUE TITLE
problem integration with vim-go plugin

### ISSUE THREAD

**Issue by 7belrhalmia** [neovim/neovim#3336]
when i run :GoRun command i have no result 

![gifrecord_2015-09-12_191250](https://cloud.githubusercontent.com/assets/13202562/9833092/b05578b4-5982-11e5-894f-aedadf49e1af.gif)

**Comment by justinmk** [comment]
Looks like it is using `:!`. Did you check `:copen` after running `:GoRun`? vim-go may need to using `:term` instead of `:!` if it does not collect the results into the quickfix list.

The general problem of `:term` as a workaround for `:!` is covered in other issues, so closing this. Perhaps report to vim-go.
