### ISSUE TITLE
:bn and :bp not working with :terminal + 'nohidden'

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#3340]
I installed neovim on Ubuntu 15.04. It is generally really fast and recognized all the plugins immediately. However, I'm not sure the commands `:bn` and `:bp` are working correctly. This is what I do to reproduce the issue:
1. nvim
2. Type something in the current buffer: "abc"
3.  `:vsplit`
4. `<ctrl-w> <ctrl-w>` (to move to the recently created split)
5. `:term`
6. `:bp` (and this changes correctly the second split to the previous buffer containing "abc"
7. `:bn` (which doesn't return to the terminal as it should)

If I use buffers that are not terminals, `:bn` and `:bp` work correctly, though.

Can you reproduce this issue?

**Comment by brettanomyces** [comment]
I'm able to reproduce the issue with the latest version

    NVIM 0.0.0-alpha+201509121307 (compiled Sep 14 2015 09:48:07)
    Commit: 5c82ea8f9f9f3ef043d4f206ded223a89a3bd360

Seem like when `nohidden` is set and you use `:bn` or `:bp` so that the terminal buffer is no longer displayed within a window, it gets unloaded without warning.

    nvim -u NONE ~/.nvimrc
    :term
    <c-\><c-n>
    :ls
    :bp
    :ls
    # terminal buffer will now be unloaded

I'm unsure whether this is a bug or not since terminal buffers return  0 for `:echo &modified` so it is correct that they be unloaded when they are no longer displayed in a window.

**Comment by rsmith31415** [comment]
Thanks. I believe that this should be considered a bug because if terminals are buffers, they should behave as buffers under most circumstances (without surprising a reasonably experienced user) and this unloading is a bit unexpected. I can think of some situations in which the terminal contains important information (e.g. running tests) and losing that after `:bn`, `:bp` would be an unwanted event.

**Comment by justinmk** [comment]
@rsmith31415 But that is the purpose of `set hidden`, is it not? IIUC you are suggesting that we treat `:term` buffers always as "modified"? Or should they never be "unloaded"?

**Comment by rsmith31415** [comment]
I think `set hidden` would affect other buffers and probably that's not what users want by default. I think `:term` buffers shouldn't be unloaded unless explicitly closed.

**Comment by brettanomyces** [comment]
I tend to agree with @justinmk although the help docs could have it either way .

> The commands that move through the buffer list sometimes make a buffer
        hidden although the 'hidden' option is off: When the buffer is
        modified, 'autowrite' is off or **writing is not possible**, and the '!'
        flag was used

(emphasis mine)

**Comment by justinmk** [comment]
Recap: there's at least 1 bug here: terminal buffers are removed from `:ls` when they are left and `'nohidden'` is set. But there's an unanswered question about what we should do with terminal buffers for `'nohidden'`: 

- should we ignore `'nohidden'` and keep the terminal running (this is contrary to the normal operation of `'nohidden'`)?
- should we just restart the shell when the terminal buffer is revisited?

**Comment by eblade** [comment]
I believe this cannot be solved by looking backwards. I think it's a really nice feature to have a terminal buffer that I'm able to interact with within nvim, but if the application running in it (an ssh session for instance, or some interactive console) may be killed because it's not in a window, it defeats at least the purpose I use it for. Restarting the shell would therefore also not be useful.

I guess that people will use this differently, so configurability is probably the way forward. However, killing terminal sessions is not a desired default behaviour.

**Comment by mhinz** [comment]
Personally I'm against making terminal buffers more special than needed. They should be treated like any other buffers.

So, when abandoning a buffer, and that's what happens when a buffer is not active (thus not visible) anymore, I expect it to get unloaded if `nohidden` is set.

If anything, we could talk about making `hidden` a default, but I'm sure that was a discussion before.

**Comment by Shougo** [comment]
I think it should be killed after switch.
But the current behavior is very wonder.
Please read my example.

https://github.com/neovim/neovim/issues/5122#issue-168053755

It should be killed when first `:edit` state.

**Comment by jamessan** [comment]
Should terminal buffers always be considered modified?  That resolves the issue of the buffer being abandoned when `'nohidden'` is set.  From Neovim's perspective, there's no knowledge of what's happening in the terminal so it can't know if the shell should be killed or not.

By having that buffer modified while the shell is running, it means the user has to make the choice about whether and how to kill the processes that are running.

**Comment by mhinz** [comment]
(I assume `nohidden` set.)

- **Should an unloaded terminal buffer get removed from the buffer list?** To stay consistent, abandoning (and therefore unloading) a terminal buffer should never remove it from the buffer list. (*This is a bug currently.*)
- **Is a terminal buffer always modified or always unmodified?** A terminal buffer is something interactive and I like @jamessan's suggestion to just always assume `modified` (`nomodified` is hardcoded at the moment), so it throws an error when trying to switch. This would also be consistent with current behaviour of other buffers.
- **What to do when revisiting an unloaded terminal buffer?** As @justinmk suggested already, I think it should simply be restarted. (The buffer name contains the complete command-line as last part.)

**Comment by justinmk** [comment]
Followup to https://github.com/neovim/neovim/issues/3340#issuecomment-192812245 : 

> there's at least 1 bug here: terminal buffers are removed from `:ls` when they are abandoned and `'nohidden'` is set. 

Can't reproduce that anymore. Though https://github.com/neovim/neovim/pull/6280 seems like a more proper fix.

> what we should do with terminal buffers for `'nohidden'`: should we ignore `'nohidden'` and keep the terminal running (this is contrary to the normal operation of `'nohidden'`)?

That's still an open question.

But the main issue here appears to be resolved.
