### ISSUE TITLE
TUI: use OSC 52 for copy/paste

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#3344]
https://gitter.im/neovim/neovim?at=55f81362fe4ca46810e1bd53

> It is totally technically possible for `"+p` to ask the terminal what the state of the clipboard is, over an OSC
> They're also really easy to probe for and ask if it's supported, so you can fall back on some other mechanism if they're not

- Supported by xterm, iTerm2, possibly many others. 
- Note that this is different than "bracketed paste mode" which we already implement.

Test case for yank (set local OS clipboard from remote terminal):

    echo -e "\033]52;c;$(base64 <<< hello)\a"

**Comment by leonerd** [comment]
+1  :)

**Comment by tarruda** [comment]
@leonerd What would be the sane behavior for a terminal multiplexer such a tmux that aims to support this in the case multiple clients are connected?

**Comment by leonerd** [comment]
@tarruda that is an excitingly-interesting question indeed.

I could imagine that a simple multiplexer that is unaware of the content of OSCs might simply pass them through transparently. In such a case, a "foreground" neovim that had the user's input focus would react much as it would were the muxer not there, and all would be well and good for it. Other instances that were running on hidden windows would have this output suppressed and as such could not mutate the eventual terminal's clipboard, nor would they receive any response to a query for the current value. This is unlikely to matter, as such an unattended neovim is unlikely to want to interact with the clipboard without the user's specific request.

A slightly less naïve muxer that actually interpreted the sequences could do a little better here. It could realise that a query for the current value can be handled safely even by hidden windows, though it might want to leave to user policy via some configuration setting whether hidden windows can mutate the current value of the clipboard without being seen or interacted with directly by the user.

One key advantage of having the muxer understand these sequences is that it can work nicely during detach/reättach later on, without requiring the subtle and breakage-prone issues associated with X11 forwarding or other techniques used to access the clipboards. Without an attached terminal instance at all, the muxer would likely just drop any request to mutate the clipboard, and could give an error response to queries requesting it. This is also unlikely to matter to neovim, since again it's unlikely to make requests about the clipboard when not attended by a user attached via a terminal telling it to.

**Comment by leonerd** [comment]
However - that all being said, there are terminal muxers that support the idea that multiple terminals can be attached at once, giving multiple views on the same application. A request to set the clipboard is simple enough to handle here; that can be broadcast among them all much the same that any other side-effecting unresponded request is done. The only awkward case is how to handle a query for the clipboard when multiple terminals are attached.

There's no easy answer here, but I suspect that a clipboard query is not the only kind of query that such a muxer has to deal with - there are many more queries of "general state of the surroundings and context of the terminal" that a muxer also has to cope with. However it handles it, should be chosen in a consistent manner with respect to these other queries.

**Comment by leonerd** [comment]
However - that all being said, there are terminal muxers that support the idea that multiple terminals can be attached at once, giving multiple views on the same application. A request to set the clipboard is simple enough to handle here; that can be broadcast among them all much the same that any other side-effecting unresponded request is done. The only awkward case is how to handle a query for the clipboard when multiple terminals are attached.

There's no easy answer here, but I suspect that a clipboard query is not the only kind of query that such a muxer has to deal with - there are many more queries of "general state of the surroundings and context of the terminal" that a muxer also has to cope with. However it handles it, should be chosen in a consistent manner with respect to these other queries.

**Comment by tarruda** [comment]
> There's no easy answer here, but I suspect that a clipboard query is not the only kind of query that such a muxer has to deal with - there are many more queries of "general state of the surroundings and context of the terminal" that a muxer also has to cope with. However it handles it, should be chosen in a consistent manner with respect to these other queries.

That is exactly the part I was interested in because I wondered about this myself when putting together nvim client/server model: At first I wanted to implement the clipboard register by simply asking the attached UI for clipboard data, but there was the complicated scenario of multiple UIs attached and so I decided to use the "clipboard provider" approach, where any piece of vimscript can register a handler for returning clipboard data. This gave me more flexibility to deal with the problem later.

Right now the only implementation of the clipboard provider is a piece of vimscript that calls a program such as `xclip` or `xsel` to return the data, but later we can implement one that sends the request to the first attached UI for example(Since it would make little sense to ask for clipboard data from multiple clients)

**Comment by rumpelsepp** [comment]
> What would be the sane behavior for a terminal multiplexer such a tmux that aims to support this in the case multiple clients are connected?

This question seems answered for the tmux case: https://github.com/tmux/tmux/commit/c88e945bc5e59bed8eaa41f1e66a9b03a2dad807
tmux has support for OSC 52 since 2018 aka version 2.9a.

**Comment by rumpelsepp** [comment]
> Supported by xterm, iTerm2, possibly many others.

Supported terminal emulators, source: https://github.com/ojroques/vim-oscyank

| Terminal | OSC52 support |
|----------|:-------------:|
| [Alacritty](https://github.com/alacritty/alacritty) | **yes** |
| [GNOME Terminal](https://github.com/GNOME/gnome-terminal) (and other VTE-based terminals) | [not yet](https://bugzilla.gnome.org/show_bug.cgi?id=795774) |
| [hterm (Chromebook)](https://chromium.googlesource.com/apps/libapps/+/master/README.md) | [**yes**](https://chromium.googlesource.com/apps/libapps/+/master/nassh/doc/FAQ.md#Is-OSC-52-aka-clipboard-operations_supported) |
| [iTerm2](https://iterm2.com/) | **yes** |
| [foot](https://codeberg.org/dnkl/foot) | **yes** |
| [kitty](https://github.com/kovidgoyal/kitty) | [**yes**](https://sw.kovidgoyal.net/kitty/protocol-extensions.html#pasting-to-clipboard) |
| [screen](https://www.gnu.org/software/screen/) | **yes** |
| [tmux](https://github.com/tmux/tmux) | **yes** |
| [Windows Terminal](https://github.com/microsoft/terminal) | **yes** |
| [rxvt](http://rxvt.sourceforge.net/) | **yes** (to be confirmed) |
| [urxvt](http://software.schmorp.de/pkg/rxvt-unicode.html) | **yes** (with a script, see [here](https://github.com/ojroques/vim-oscyank/issues/4)) |

**Comment by nexplor** [comment]
+1

**Comment by rnhmjoj** [comment]
The copying part is really simple to implement:
```lua
function copy(sel)
  return function(lines, _)
    local data = vim.fn.system([[base64 | tr -d '\n']], lines)
    io.stdout:write('\027]52;'..sel..';'..data..'\a')
  end
end

vim.g.clipboard = {name='OSC-52', copy={['*']=copy's', ['+']=copy'c'}}
```
Pasting, on the other hand, is pretty involved: to do it properly you have to read from `/dev/tty` (without blocking!) for the reply from the terminal emulator. Also the screen settings must be changed to prevent the reply from messing up the output (disabling echo and such). 
I don't think it's possible to do it from lua/vimL, it probably has to be implemented in neovim or an external tool.

**Comment by gpanders** [comment]
I'm working on this now. There are a few prerequisites:

- [x] Base64 encoding/decoding support (https://github.com/neovim/neovim/pull/25843)
- [ ] Ability for plugins to read terminal responses (https://github.com/neovim/neovim/issues/25856)

**Comment by justinmk** [comment]
> It is totally technically possible for "+p to ask the terminal what the state of the clipboard is, over an OSC
They're also really easy to probe for and ask if it's supported,

@leonerd is there any way to "ask if OSC 52 is supported" other than actually trying to read/write to the clipboard? (which [may cause a dialog](https://github.com/neovim/neovim/pull/25872#issuecomment-1798864275))

**Comment by gpanders** [comment]
Some terminals include an `Ms` terminfo entry (WezTerm, kitty, Ghostty, and iTerm2 all do, perhaps others). We _could_ try that. However, terminfo is an especially bad method in this particular case because the primary use case of OSC 52 is in remote terminal sessions, where the terminfo entry of the host terminal emulator may not always be present (or up to date).

**Comment by emersion** [comment]
Maybe `XTGETTCAP` can help? See https://codeberg.org/dnkl/foot#xtgettcap

**Comment by gpanders** [comment]
XTGETTCAP could work. I'll put together a prototype.

**Comment by gpanders** [comment]
_Even if_ we can determine OSC 52 support automatically (via XTGETTCAP or other means) I am still unconvinced we should enable it by default, at least unconditionally. OSC 52 has security implications that other clipboard providers don't have. And some terminal emulators (e.g. Alacritty) simply disable reading via OSC 52 by default. So a user would have to know to first enable that feature in their terminal emulator. Other terminals show a prompt by default, but that's still more intrusive than other clipboard providers.

**Comment by emersion** [comment]
The security implications are to be managed by a good terminal emulator IMHO. Under Wayland, only focused windows can interact with the clipboard anyways.

**Comment by gpanders** [comment]
OSC 52 is conditionally enabled by default as of https://github.com/neovim/neovim/pull/26064.

**Comment by schiegl** [comment]
Is there a way to use OSC-52 such that yank/cut will automatically use it? In other words, I'd like to use `unnamedplus` in an SSH session, so that yanking/cutting on the remote computer automatically copies it to my local computer's clipboard. So far I've only been able to use `"+y`.

**Comment by justinmk** [comment]
> Is there a way to use OSC-52 ... I'd like to use `unnamedplus`

By default it's skipped if 'clipboard' is set: https://github.com/neovim/neovim/blob/e5d7003b02c9af96c51ea5638e07eea25057a216/runtime/plugin/osc52.lua#L5

But you can easily configure it like so:

https://github.com/neovim/neovim/blob/e5d7003b02c9af96c51ea5638e07eea25057a216/runtime/plugin/osc52.lua#L23-L35

**Comment by schiegl** [comment]
> But you can easily configure it like so:

Yes, I already tried that based on the documentation provided at: https://neovim.io/doc/user/provider.html#clipboard-osc52.

`:echo g:clipboard` shows the OSC 52 configuration you provided. However, only `"+y` and right click copy (from the neovim dropdown) yanks into the local clipboard for me, but not a simple yank with `y`. I tried it in Kitty and MacOS Terminal.

**Comment by tuxflo** [comment]
Could you map y and Y to "+y to achieve that?

**Comment by majutsushi** [comment]
There's a `TextYankPost` autocommand that you should be able to use to call the OSC 52 copy function.

**Comment by schiegl** [comment]
@majutsushi Thank you for the tip. But, I ended up using [smart-yank](https://github.com/ibhagwan/smartyank.nvim) with 0.9.4 since 0.10 is still too unstable for me.

**Comment by Aonodensetsu** [comment]
by default nvim copies into the 'unnamed' buffer, not into 'plus', if you set `vim.opt.clipboard=unnamedplus`, then it will work as you expected it to without a plugin

**Comment by name-snrl** [comment]
Hi @justinmk, I'm not sure if I need to open a new issue, but it seems that block pasting doesn't work with the osc52 provider. This is the same behavior as described in #1822, but for osc52. My understanding is that an internal mechanism was previously added to Neovim to mark a block clipboard, but this doesn't seem to work for osc52?

**Comment by name-snrl** [comment]
Just to be clear. I'm using `unnamedplus`. And when I added this snippet to the cfg, the block pasting stopped working properly inside Neovim.

```lua
vim.g.clipboard = {
  name = 'OSC 52',
  copy = {
    ['+'] = require('vim.ui.clipboard.osc52').copy '+',
    ['*'] = require('vim.ui.clipboard.osc52').copy '*',
  },
  paste = {
    ['+'] = require('vim.ui.clipboard.osc52').paste '+',
    ['*'] = require('vim.ui.clipboard.osc52').paste '*',
  },
}
```

**Comment by gpanders** [comment]
@name-snrl Yes, please open a new issue with reproduction steps.
