### ISSUE TITLE
CPSM matcher for CtrlP doesn

### ISSUE THREAD

**Issue by LemonBoy** [neovim/neovim#3401]
I'm having problems with the CPSM matcher [2] for CtrlP as it filters away all the results.
I'm running a fresh copy of nvim [1] and I've been able to reproduce the issue even with all the other plugins have been disabled.

[1] https://ptpb.pw/m_KG
[2] https://github.com/nixprime/cpsm

**Comment by justinmk** [comment]
please report `:version` and read https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md

**Comment by LemonBoy** [comment]
please read the whole ticket, the information you requested is in the first link

**Comment by justinmk** [comment]
The whole ticket (with an incomplete title) which doesn't mention these details requested in CONTRIBUTING.md:

- What operating system you're using.
- Whether the bug is present in Vim (not Neovim), and if so which version of Vim. It's fine to report Vim bugs on the Neovim bug tracker, but it saves everyone time if we know from the start that the bug is not a regression caused by Neovim.

We need reduced steps, we can't install and debug every plugin.

**Comment by LemonBoy** [comment]
I agree on the title being incomplete, but it's quite evident that the OS is Linux (not that you support many platforms). In case you meant what my Linux distribution is its Arch Linux).
And since this is the NeoVim bug tracker I'd also suppose the bug is only present in NeoVim and not the good old Vim, both the git head and the stable release.

**Comment by fwalch** [comment]
> I'd also suppose the bug is only present in NeoVim and not the good old Vim

So does it work with Vim (with the same `.vimrc`), or not?

Since I'm already using Ctrl-P, I actually went ahead and installed cpsm, which works fine for me (I'm also on Arch). I *can* reproduce behavior as described by you if I set `g:ctrlp_match_func` to a non-existing function.

Since cpsm uses `if_python`, do you have `python2-neovim` installed and working?

So, as @justinmk mentioned, we need reduced steps to be able to reproduce this.

**Comment by LemonBoy** [comment]
Rebuilding the python module fixed the problem, I'd appreciate some kind of error message though.

**Comment by fwalch** [comment]
> I'd appreciate some kind of error message though

There's nothing Neovim can do about this, as Ctrl-P silently ignores errors with the `g:ctrlp_match_func` (e.g. if it doesn't exist).
