### ISSUE TITLE
Hash repeatedly sourced files in 'runtimepath'

### ISSUE THREAD

**Issue by bohrshaw** [neovim/neovim#3411]
The primary motivation of this idea is to improve runtime file search performance.

Popular plugin managers #247, in contrast to the Vimball way, all put an entry to 'runtimepath' for each plugin. And this tendency probably would not change, nor need to. Thus as the the number of entries in 'runtimepath' grows tremendously, which is often the case nowadays for many users, the various delay would be noticeable.

When using shells, I learned that the builtin `hash` constructs an associative array to speed up command search. And as an avid Vim user, I couldn't help think to bring this kind of optimization to Vim. At least we could hash files in "ftplugin", "syntax", "indent", etc.

**Comment by tarruda** [comment]
I don't follow, how hashing would help search performance? Can you give an example?

**Comment by BohrShaw** [comment]
I just think the shell builtin `hash` exists for performance reason. And the 'runtimepath' situation is similar IMHO.

**Comment by tarruda** [comment]
Yes but I don't see how it would improve the performance of sourcing. As far as I understand, we'd still have to go through each directory in 'runtimepath' and search for files to source

**Comment by justinmk** [comment]
Bram did mention on vim_dev  https://github.com/neovim/neovim/pull/3125#issuecomment-126995540

> making 'runtimepath' very long is a bad idea.  Every time Vim searches for a runtime file it will 
visit those directories and request the contents. 

> A plugin manager better use another mechanism.  A dictionary to lookup what file is located where is a LOT faster.

**Comment by BohrShaw** [comment]
> we'd still have to go through each directory in 'runtimepath' and search for files to source.

We could modify `:runtime`(and related commands) to search in the hash table constructed from existing files in 'runtimepath'. And add a command like `:hash` to rehash files when needed, reminiscent of `:helptags`.

**Comment by ZyX-I** [comment]
Note: if you derive functionality from zsh then in addition to looking values in hash it also fall backs to plain old walking over `$path` should executable be not found. (Though for some reason it does not automatically rehash when it appears that executable was not found in hash, but found on FS. Most likely because it first `fork()`s and only then attempts search, see `command_not_found_handler` in `man zshmisc`.)

**Comment by BohrShaw** [comment]
So let's clarify some points (for Vim):

> fall back ... does not automatically rehash

If we hash `autoload/*`, `colors/*`, etc., then a falling back to search in 'runtimepath' is needed, and the new entry should be added to the hash table.

But the primary concern is to hash *repeatedly sourced files* including these in "ftplugin", "syntax" and "indent", in which case there is no falling back or auto-rehashing.

**Comment by justinmk** [comment]
What is being hashed? The contents? If so, why?

**Comment by BohrShaw** [comment]
> What is being hashed? The contents? If so, why?

I think it's clear that _only_ file paths be hashed. 

To be more specific, with file types "vim", "lua", etc., there would be:

    let v:runtime = {
          \ "ftplugin": {
          \ "vim": [absolute_path1, absolute_path2, ...],
          \ "lua": [absolute_path1, absolute_path2, ...],
          \ ...},
          \
          \ "syntax": {
          \ "vim": [absolute_path1, absolute_path2, ...],
          \ "lua": [absolute_path1, absolute_path2, ...],
          \ ...},
          \
          \ "indent": {
          \ "vim": [absolute_path1, absolute_path2, ...],
          \ "lua": [absolute_path1, absolute_path2, ...],
          \ ...},
          \
          \ "autoload": [absolute_path1, absolute_path2, ...],
          \ ...
          \ }

**Comment by ZyX-I** [comment]
@BohrShaw `autoload` files are normally sourced only once. Also let us set up an agreement:

- Hashing means that at some event *all entries in &runtimepath are walked over and put into a hash*, so that ideally `:runtime` or equivalent C function *never* falls back to walking over &runtimepath.
- Caching means that when `:runtime` or equivalent C function is called it first looks up whether path was already known, and if not then performs searching in `&runtimepath` and saves the result.

It looks like in the discussion such approaches are being mixed. “New entry is being added to the hash table” is from second approach, what I meant that in case of hash miss when requested file was found NeoVim performs *full* rescan because such event means that hash is outdated and there is good chance to miss something when next time calling `:runtime` or equivalent C function if no rescan is being done. Same thing if requested file was not found in runtimepath saved in hash.

Also in my opinion hash table should look like

```JSON
{
    "syntax/lua.vim": ["/usr/share/nvim/runtime", "/home/user/.nvim"],
    "indent/foo.vim": ["/home/user/.nvim"]
}
```

Note 1: strings inside may actually be pointers to `&runtimepath`. In any case hash needs to be recreated when `&runtimepath` changes, so this is safe. In addition it is better to be more sane and hold `&runtimepath` as `ArrayOf(String)` or equivalent and only convert it to the usual comma-separated list when some manipulations with `&runtimepath` are being performed: walking over `&runtimepath` is *far* more common operation then viewing its value, and this variant avoids both allocating memory (which is also true when holding pointers to inside old `&runtimepath`) and extra overhead on unescaping performed in `copy_option_part`.

Note 2: it is probably better to do scanning in a separate thread in all cases.

**Comment by BohrShaw** [comment]
> autoload files are normally sourced only once.

As we walk through the 'runtimepath', I think it's handy and cheap to include files even sourced only once in the hash table. But it may not be worth it should we encounter trouble after more things are considered.

> Full-rehash when a new file is found or &runtimepath is changed.

I assume you mean e.g. a _new file_ in `autoload/`. So are we going to hash single-sourced files in `&runtimepath`?

> Also in my opinion the hash table is linear.

I set on a two-dimensional one solely for performance reason because VimL is interpreted. Would operations on the hash table all implemented in C?

> Note1 and Note2

Efficient C implementation is indeed valuable.

**Comment by ZyX-I** [comment]
@BohrShaw 

> I set on a two-dimensional one solely for performance reason because VimL is interpreted. Would operations on the hash table all implemented in C?

First rule of VimL optimization is “less commands are faster”. Most of time it is even more efficient to call `map` with `copy()` then to use `:for`. One of my plugins optimizes its performance by squashing a `while` cycle with `:let` and `:if` commands inside into a `while` cycle with a single big condition with no commands in body.

Thus I see absolutely no reason for many-dimensional hash table have better performance in VimL.

> As we walk through the 'runtimepath', I think it's handy and cheap to include files even sourced only once in the hash table. But it may not be worth it should we encounter trouble after more things are considered.

This is bad idea unless job will be done in a separate thread: you may visit *far* more directories then needed if you simply visit everything. Especially given that indent, syntax and ftplugin files have a clear and limited depth (also colorscheme, but scanning their directory is pointless because `:colorscheme` is not run often), but plugin and autoload have no limit and some plugin authors like to put there various stuff.

Also note that one may do `runtime macros/….vim`.

**Comment by BohrShaw** [comment]
> First rule of VimL optimization is “less commands are faster”.

@ZyX-I Overall, I'm glad to know the performance implications of VimL.

> You may visit _far_ more directories then needed if you simply visit everything. ...

I also tend to exclude single-sourced files when hashing.

**Comment by justinmk** [comment]
Related:

- https://github.com/neovim/neovim/pull/15632

**Comment by lewis6991** [comment]
There's no concrete problem here to solve, and the suggested solution seems misguided. Closing.
