### ISSUE TITLE
Add support for marshalling JSON

### ISSUE THREAD

**Issue by dbarnett** [neovim/neovim#3417]
Could neovim have a built-in `jsondump({value})` and `jsonparse({json})` helpers to serialize and deserialize JSON?

JSON is used in lots of vim plugins like
  * https://github.com/Valloric/YouCompleteMe
  * https://github.com/google/vim-maktaba
  * https://github.com/MarcWeber/vim-addon-manager
  * and eventually Vundle (https://github.com/VundleVim/Vundle.vim/pull/560).

These can either use slow hacks or depend on python support, but it would be best if vim just had native, performant support for JSON marshalling built in.

Expected behavior
```vim
:echo jsondump({'a': [1, 'foo'], 'b': 2.1}) ==# '{"a": [1, "foo"], "b": 2.1}'
1
:echo jsonparse("[1.0, {}, []]") ==# [1.0, {}, []]
1
:echo jsondump(jsonparse('[null, true, false]')) ==# '[null, true, false]'
1
```

Note in the last example there needs to be a way to represent null, true, and 
false unambiguously even though vim doesn't have these primitives. Also, 
`fromjson()` could use an option to translate into standard vim equivalents like 
`''`, `1`, and `0`.

Note: This corresponds to the FR vim/vim#383 for JSON support in classic vim, but may be easier to implement in neovim. Also, having it in neovim would help compensate for the lack of `bindeval()`, which is currently breaking maktaba's neovim compatibility (google/vim-maktaba#158).

**Comment by justinmk** [comment]
I suppose good old cJSON would be straightforward to include, and it's hard to argue against this since we have `msgpackdump`/`msgpackparse`. For roundtripping, as you noted, we would need some sort of convention like @ZyX-I created for msgpack.

On the other hand Neovim has job control and [jq](https://stedolan.github.io/jq/) is available on most  systems including Windows. `curl` is also a really nice utility but we don't want to link to it, we want to shell out to it. On Windows, I would be in favor of shipping with `jq` or a similar utility. https://github.com/neovim/neovim/issues/1811

**Comment by ZyX-I** [comment]
@justinmk I think it is logical to use just the same convention for JSON values. For dumping it needs no cJSON, only the same thing I used in #3365, parsing will require either modifying `evalN`, something like cJSON or writing parser ourselves.

**Comment by ZyX-I** [comment]
@justinmk For parsing I found a good alternative: https://github.com/vurtun/zange. This can be simply copied to src/nvim/lib just as klib and mentioned in LICENSE (under “The externally maintained libraries used by Neovim are:”), without adding a dependency. Though this has a downside of requiring to parse string escape sequences ourselves.

**Comment by dbarnett** [comment]
Points to consider on the implementation:

  * If it doesn't handle sloppy JSON-isms like single-quoted strings, that may become a pain point since some hacky vimscript just uses `string(JSON)` to "serialize" JSON. (Hopefully that will stop once neovim and vim support are widely available).
  * Still need to map `null`, `true`, and `false` to vimscript and back. Guessing we'd be recursively traversing over the objects to translate them into vimscript value objects in any case, so that should be orthogonal from library?

**Comment by ZyX-I** [comment]
@dbarnett 

1. This is not JSON. `jsonparse()` function is *expected* to fail on things like `'string'`. Code using `string(json)` deserealizes it as `eval(json)` (e.g. like in https://github.com/MarcWeber/vim-addon-manager/blob/fda9d2f4522024aa8bd8b8305e6a71c4a4a28c07/autoload/vam.vim#L119-L142) and thus it will not suffer from `jsonparse()` failing on what is not JSON. If somebody needs parsing `'string'` it is much better to simply use libyaml in place of any JSON parsing library and name functions `yamlparse()` and `yamldump()`, AFAIK libyaml can be configured to dump JSON strings.
2. I was not going to recursively traverse anything: I would better use iterative JSON parser. But in any case convertion from whatever library outputs to VimL is needed.

    I suggest to translate `null`, `true` and `false` into `{'_TYPE': v:msgpack_types.nil, '_VAL': 0}`, `{'_TYPE': v:msgpack_types.boolean, '_VAL': 1}` and `{'_TYPE': v:msgpack_types.boolean, '_VAL': 0}` respectively, because this is just how `msgpackparse()` represents msgpack nil, true and false values.

---

There is also a question about what to do with `{"foo": 1, "foo": 2}`: `msgpackparse()` in this case returns `{'_TYPE': v:msgpack_types.map, '_VAL': [[{'_TYPE': v:msgpack_types.string, '_VAL': ['foo']}, 1], [{'_TYPE': v:msgpack_types.string, '_VAL': ['foo']}, 2]]}`. Python returns `{'foo': 2}`. Specification (https://tools.ietf.org/html/rfc7159#section-4) says literally:

> An object whose names are all unique is interoperable in the sense
> that all software implementations receiving that object will agree on
> the name-value mappings.  When the names within an object are not
> unique, the behavior of software that receives such an object is
> unpredictable.  Many implementations report the last name/value pair
> only.  Other implementations report an error or fail to parse the
> object, and some implementations report all of the name/value pairs,
> including duplicates.

, when creating msgpackparse() I used “report all of the name/value pairs, including duplicates” variant.

Also what to do with `{"foo\u0000bar": 1}`. `msgpackparse()` handles this in the similar fashion with special dictionaries.

Note that to be compatible with `msgpackparse()` and have all JSON strings having same semantics all strings that are *not* object keys (except when object is represented as a special dictionary for whatever reason) need to be represented as `{'_TYPE': v:msgpack_types.string, '_VAL': ['line1', 'line2', "line\nwith\nthree\nNULs"]}` which is obviously inconvenient (`jsondump()` though does not have to reject strings that do not look like this). This will be easier if some helper functions are added to `runtime/autoload/msgpack.vim` from #3270: specifically at least

- `msgpack#asstr` which converts all special dictionaries representing strings to a regular strings (terminating at NUL)
- `msgpack#keys`, `msgpack#values` and `msgpack#items`: `keys()`, `values()` and `items()` functions that work with special dictionaries.

I was thinking about them when writing #3270, but that PR is not about adding utility functions and these were not needed for ShaDa plugin.

**Comment by ZyX-I** [comment]
@neovim/core Vim recently added JSON marshalling support and it introduced a new type. I am wondering what to do with this and compatibility. Options:

1. Use new type for json\*() and v:vars, behaviour of msgpackparse will still be the same, dumping a new type is error.
2. Use new type for json\*() and v:vars, behaviour of msgpackparse will still be the same, dumping a new type dumps expected msgpack values.
3. Use new type for json\*() and v:vars, msgpackparse will parse to new type, dumping a new type dumps expected msgpack values.
4. Use existing special dictionaries for json\*() and v:vars, msgpack\*() behaviour does not change.

Note that in fourth case `if jsonparse('true')` will produce an error. Note also that we will have to convince plugin authors to use `jsonparse('true') is v:true` for being compatible with both Vim and Neovim, same for determining what `jsonparse()` parsed. But this avoids a new type and currently we are in good enough position to afford this inconsistency because this is new functionality.

**Comment by ZyX-I** [comment]
There is also an option to set up necessary coercions for special dictionaries.

**Comment by ZyX-I** [comment]
Apparently Bram did not bother himself with setting up any coersions, even `is` does not work. Cannot say whether he will do it later.

In any case I would be against merging patch 1154, this can be done better.

**Comment by ZyX-I** [comment]
There is also another option: make behaviour more or less compatible with Vim (except that `jsonencode()` will recognize special dictionaries), but add functions `jsondump()` and `jsonparse()` which behave like `msgpackdump()` and `msgpackparse()` (i.e. parser will accept readfile()-style string (though in case of JSON this is not needed) and emit special dictionaries and a list of parsed objects, dumper will accept a list of parsed objects and emit concat of JSON strings).

**Comment by ZyX-I** [comment]
Currently I think the best is

1. Add a new type, but without `v:none`.
2. Add jsonencode() and jsondecode().
3. Make jsonencode() and msgpackdump() recognize values of new type *in addition* to special dictionaries.
4. Make jsondecode() and msgpackparse() return values that use new type.
5. Make jsondecode() decode to special dictionaries in case of a) duplicate keys in mapping, b) empty key in mapping, c) NUL byte in string, d) mapping with key with NUL byte (two special dictionaries here: mapping and key).
5. Make new type also recognized by `msgpack#` functions.
6. When adding `string()` implementation for new type, fixing vim/vim#582.
7. Ignore Vim JSON implementation: for dumper use existing facility, what to use for parser is still undecided.
8. Our json\* functions will convert to/from unicode regardless of what Bram thinks here.
9. Our json\* functions will be more strict, specifically no `v:none`, error on encoding `function('tr')`, error on `jsondecode('[,]')` (Vim’s `jsondecode()` parses this), error on trailing comma.

**Comment by justinmk** [comment]
Yes x10. 

We should rename msgpacparse/dump to msgpackdecode/encode.

**Comment by ZyX-I** [comment]
@justinmk They have rather different API to get them renamed. parse/dump parses/dumps readfile()-style list and expect a list of msgpack objects, encode/decode parses/dumps a string and expect a single object.

**Comment by justinmk** [comment]
> encode/decode parses/dumps a string and expect a single object.

A single JSON `{...}` object? Why wouldn't it accept multiple sibling objects? And why would that necessitate a change in the jargon? 

Reason I suggest encode/decode is because it is far more common jargon, and I have never heard the details you mention being the distinguishing factor in choosing whether "encode" or "dump" is chosen

**Comment by ZyX-I** [comment]
@justinmk When talking about “object” here I meant “one value”. E.g. `{"1": {"2": 3}}` is one value, `true false` or `{"1": 2}[3, 4]` is two. encode/decode from Vim expect a single object thus, but parse/dump from Neovim expect a concat.

This is not a reason to prefer encode/decode over parse/dump, but I think this is good enough reason to keep both encode/decode for JSON and parse/dump for msgpack instead of unifying them.

**Comment by justinmk** [comment]
> encode/decode from Vim expect a single object thus, but parse/dump from Neovim expect a concat.

Wouldn't this be a good feature for jsonencode/decode? Maybe Bram would listen to an argument in favor of it.

**Comment by ZyX-I** [comment]
@justinmk It is highly uncommon to write pseudo-JSON like `{"1": 2} {"3": 4}`. I have only seen this in some stream APIs which Vim cannot normally work with anyway. I do not know how common it is for msgpack, but it is how ShaDa was written and this was why encode/decode was written the way it was (and also because there are really no good alternatives).

And note that this makes functions less convenient: `jsonparse(['{}'])` will return `[{}]`, but there are two unneeded lists here: list in arguments (can actually be avoided by a bit of C code making it accept `'{}'`) and list in return, not to mention that you now should care about function that can return more then one value or return no values at all.

**Comment by ZyX-I** [comment]
Patch that accepts readfile()-style list has better chances to be accepted, but the only thing it does is saving one `join()` function call in real life scenarios.

**Comment by justinmk** [comment]
Ok. Then given that concatenated JSON is not valid JSON, it is not surprising to the user that `jsondecode` would not allow it. So the difference in the encoded format is not a strong argument against making the names consistent. It's conceivable that we may offer more encode/decode support for other formats in the future; then the existence of msgpackdump/parse will be even more conspicuous.

**Comment by ZyX-I** [comment]
@justinmk Concat of msgpack objects is also not a valid msgpack object. Just C parser API clearly shows that even if this is not common, it is also not unexpected (or developers have developed API convenient enough to work with concats by accident). Msgpack specification does not state that you can achieve some specific result by concatenating two msgpack objects.

Also note that it is *Vim* that has no normal ways to work with streams. *Neovim* has job API, though this will not make pseudo-JSON streams more common. For working with streams though decode should better have `[[list of parsed so far objects], {"status": …, "state": saved parser state}]` return.

**Comment by justinmk** [comment]
@ZyX-I So are you saying that `msgpackdecode` should demand a single msgpack object?

**Comment by ZyX-I** [comment]
@justinmk If there will be one, then yes.

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/4131
