### ISSUE TITLE
:term insert mode completion

### ISSUE THREAD

**Issue by ggVGc** [neovim/neovim#3423]
Maybe I'm missing something, but it currently seems impossible to get any insert mode completion in a terminal buffer? I assume this is because of key combinations like ctrl-n being eaten or something.

**Comment by ZyX-I** [comment]
There is no *NeoVim* insert-mode completion. But if you use shell (or any other application which has *its own* completion), it will allow completion just like in other terminal emulators. Note that getting NeoVim insert-mode completion work properly is close to impossible:

1. You do not really know which of the descendant processes currently “owns” the screen meaning that you have problems with context.
2. You do not really know what needs to be done to replace some completed word with some other word: most of time sending `<C-h>` will work, but not always. *Especially* when you need to handle things like combining characters (which, depending on options, may require one `<C-h>` to delete combining character and character it combines with or two).
3. It may appear that sequences that trigger insert mode completion are *more* needed by user to be passed to the application untouched (which they currently are). This combines with 1.
4. No completion scripts for anything you may launch inside the terminal buffer currently exist, and most applications which may benefit from completion has their own completion mechanizm, which in turn means that completion plugins authors would likely write completion for the application and not NeoVim. Also because bash completion script will work in any terminal [emulator] where bash can be displayed while NeoVim compeltion script works only inside NeoVim.

**Comment by justinmk** [comment]
This is also requestd in https://github.com/neovim/neovim/issues/3013.

For the reasons @ZyX-I outlined, this would be a quagmire to support, but we _can_ at least expose completion in the API, so that plugins could attempt provide `:term` completion. I think there's an issue covering that already.
