### ISSUE TITLE
remapping keys

### ISSUE THREAD

**Issue by teamblubee** [neovim/neovim#3424]
http://stackoverflow.com/questions/16359878/vim-how-to-map-shift-enter

Seems to be an issue that dates back to the Vim source code where I can't seem to map Shift Enter. I am trying to map a simple key binding to add extra lines to the file that I am currently editing.

from this answer; http://superuser.com/a/607189

which is basically mapping these keys

    map <Enter> o<ESC>
    map <S-Enter> O<ESC>

I did nnoremap but Shift Enter does not work. I know this isn't neovim specific but since I am currently using neovim, i was wondering are you guys working on anything or have any solutions?

**Comment by ZyX-I** [comment]
You need to teach terminal to output something different on `<S-Enter>`. NeoVim *does* support these keys including in terminal after #1820, but terminals *do not*. And there is gitter and mailing list for such questions.

**Comment by justinmk** [comment]
Most terminals allow users to configuration any keypress to send arbitrary sequences. If you can configure your terminal to send a different sequence for shift-enter, then you can bind a "virtual key" such as `<s-enter>` to _that sequence_ like this:

    set <s-enter>=^[[13;2u

Then you can `nnoremap <s-enter> ...` and it will be distinguished from `<enter>` because your terminal is sending a different sequence.

However, I believe the `set <virtual key>=<sequence>` feature is actually broken in Neovim, currently. See https://github.com/neovim/neovim/issues/2204

See also http://www.leonerd.org.uk/hacks/fixterms/

**Comment by ZyX-I** [comment]
@justinmk If I am not mistaking all you need is to configure your terminal according to spec described in fixterms link. Then `set` will not be needed. For `<S-Enter>` this indeed works.

**Comment by justinmk** [comment]
@ZyX-I Good to know!

**Comment by teamblubee** [comment]
oh, yes thank you for the steps to fix this issue. I used the link provided by @justinmk with the help of @ZyX-I

**Comment by shmerl** [comment]
This indeed works for Shift + Enter (just tested it in konsole with keyboard setting handling Shift + Return as `^[[13;2u`.

If neovim supports it, is this extension somehow standardized? It would be good to propose for Konsole to handle it somehow better, since out of the box in the shell it doesn't handle such Shift + Enter nicely. But not sure how to propose it if it's not some commonly agreed standard.

**Comment by zeertzjq** [comment]
https://invisible-island.net/xterm/modified-keys.html
http://www.leonerd.org.uk/hacks/fixterms/
https://sw.kovidgoyal.net/kitty/keyboard-protocol/

**Comment by shmerl** [comment]
Thanks for the references! I see this was already proposed :) https://bugs.kde.org/show_bug.cgi?id=435975
