### ISSUE TITLE
Do not change vim mode when terminal input changes and key sequence is started

### ISSUE THREAD

**Issue by sschaef** [neovim/neovim#3438]
The problem can be reproduced with the following example:

``` sh
while [ 1 ]; do echo '.'; sleep 1; done
```

Once this is executed in a terminal window, the buffer is constantly updated. It looks like these updates prevent me from typing key sequences. When I type `<C-a><right>` for example, in order to move to another split, it doesn't work. If an update of the buffer occurs the moment after `<C-a>` is typed, the insert mode is immediately left and this seems to also break the key sequence. In case I'm fast enough and can type the entire sequence before a new update happens, everything works as expected.

`<C-a><right>` is defined as `tno <C-a><right> <C-\><C-n><C-w>l`

**Comment by rulex** [comment]
Good to see this already reported. It is quite annoying. :angry:

**Comment by tarruda** [comment]
This is a serious problem that I'm partially fixing in #3413. It is serious because it requires a lot of internal reorganization before it is fully fixed, but you can already use that branch if this problem is bothering too much.

There's only one caveat for now: If you have partially typed a mapping or multi-key command, the terminal won't update until the command is finished. This is something that will be fixed but probably not in #3413.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/pull/7230 https://github.com/neovim/neovim/issues/6166 https://github.com/neovim/neovim/issues/5685
