### ISSUE TITLE
Show an outline of the terminal cursor when not in :terminal mode

### ISSUE THREAD

**Issue by marrs** [neovim/neovim#3453]
At the moment, the terminal cursor is hidden if I exit `:term` mode and replaced with the `nvim` cursor. This is causing a number of cognitive problems for me.

For example, if I exit `:term` mode and navigate the buffer for a bit, I can easily forget that the cursor I see is not the `:term` cursor but the `nvim` cursor.  Now if I paste at this cursor location, I think that the text will go here, but it will probably go somewhere else.

It would be good if an outline of the cursor could remain on screen to always remind me where the cursor will be when I re-enter :term mode, or perform a paste operation.

**Comment by bobrippling** [comment]
This can be enabled by using the `TermCursorNC` highlight group, for example:
```vim
:highlight TermCursorNC ctermbg=gray
```

Perhaps having this (or reasonable dark and light colors depending on `'bg'`) as a default would close this.

**Comment by justinmk** [comment]
> Perhaps having this (or reasonable dark and light colors depending on `'bg'`) as a default would close this.

No objection, but let's close this in the meantime.  I think the current default is rather defensible: having cursors (even if light-colored) in multiple `:term` windows will be surely confusing for many users, since no other vim buffer works like that.

Meanwhile `TermCursorNC` resolves the original request here.
