### ISSUE TITLE
Get funny chars on terminal

### ISSUE THREAD

**Issue by sittim** [neovim/neovim#3462]
# System:

- Ubuntu 15.04
- Gnome terminal
- xterm256

#Issue:

I get funny stuff like the one in red box showing up randomly:

![selection_037](https://cloud.githubusercontent.com/assets/8825037/10541768/9b0b3e5c-73e1-11e5-852d-690fab9a27c3.png)

**Comment by tarruda** [comment]
Is this xterm or gnome terminal?  Gnome terminal is known to print unrecognized escape sequences, does this happen on xterm too?

**Comment by sittim** [comment]
OK, This never happened in VIM.  Not sure if it happened in plain xterm.

1. Start the terminal by executing `gnome-terminal`
2. Start tmux by executing `tmux -2`
3. in gnome-terminal `echo $TERM` returns `xterm-256color`

So my understanding gnome-terminal runs on top of xterm-256color.

**Comment by ZyX-I** [comment]
@sittim No. $TERM is pure informational thing, it tells underlying application which entry they should check out in terminfo/termcap databases. *Setting $TERM will be ignored by both tmux and gnome-terminal.*

In your case $TERM should actually be something like `screen-256color` because of tmux (on some systems there is also terminfo for `tmux-256color`, but most of time inside tmux screen terminfo is used; on my system there is even no such terminfo entry). This is controlled by `default-terminal` option in tmux.conf.

**Comment by ZyX-I** [comment]
Specifically TERM=xterm-256color is one of the most common $TERM values because almost all of terminal emulator authors

1. Say that they are compatible with xterm (most of time they are, but have new or missing features).
2. Are too lazy to create terminfo database entry, even if they are partly not compatible.

. This default $TERM does *not* mean that gnome-terminal is using xterm in any fashion. Only that gnome-terminal authors think that they are enough compatible with xterm (regarding sent/understood escape sequences) to use TERM=xterm-256color in place of their own terminfo.

**Comment by ZyX-I** [comment]
(Or, more likely, vte authors because gnome-terminal uses this terminal emulator library AFAIR; and they are not the only ones that use it.)

**Comment by tarruda** [comment]
@sittim can you post a file and nvimrc that reproduces the problem? I'd like to investigate this in my machine

**Comment by sittim** [comment]
@ZyX-I I force tmux to use xterm by adding `set -g default-terminal "xterm" ` to `.tmux.conf`, screen-256color does not support italics.

I do have the following lines in .bashrc
```bash
if [ "$TERM" = "xterm" ]; then
     export TERM=xterm-256color     
fi 
```
Maybe it is time to get rid of it.

**Comment by raichoo** [comment]
I have the same issue. Using `gnome-terminal` as well.

**Comment by sittim** [comment]
@tarruda

## .nvimrc

https://github.com/sittim/configs/blob/master/.nvimrc

Also that repo has other configs...

**Comment by sittim** [comment]
# Sample 1
### Is: ![selection_038](https://cloud.githubusercontent.com/assets/8825037/10543167/e195ac00-73ea-11e5-840a-2873e32f0064.png)

### Expected: ![selection_040](https://cloud.githubusercontent.com/assets/8825037/10543214/281fc340-73eb-11e5-9602-bb2ffa4a192b.png)

**Comment by ZyX-I** [comment]
@sittim This is one of the illustrations about lazy terminal emulator authors (tmux does contain terminal emulator). Tmux supports italics, but they do not have proper terminfo entry. (BTW, check whether your system has `tmux-256color` terminfo entry: it should be located in /usr/share/terminfo/t/tmux-256color.) Also rather strange situation when terminfo entries are distributed as a part of ncurses package (at least in Gentoo) instead of being part of screen/tmux/vte/xterm/… packages.

The sample looks like terminal emulator that parsed escape sequence only partly, specifically `\e[48;5;234m` is a sequence for setting background color to 234; most likely it was preceded by a sequence that sets foreground color (so the result should look something like `\e[38;5;{number};48;5;234m`). Can you use `script -t /tmp/script.timing -c 'nvim …' /tmp/script` (replace `…` with whatever is needed to show the bug) and post both files here?

**Comment by tarruda** [comment]
> Tmux supports italics, but they do not have proper terminfo entry

FWIW you can easily use italics with tmux by creating a custom terminfo file based on screen-256color and entries for the italics sequences used by your terminal emulator(It uses standout "slots" for italics). This is what I use for tmux and rxvt-256color:

```
#	Custom terminfo for better using tmux with urxvt and 256colors It imports the
#	screen-256color settings and fixes the sitm/ritm(italics) and
#	smso/rmso(standout) capabilities
screen-256color-it|screen/tmux with rxvt-unicode-256color client,
  use=screen-256color,
  smso=\E[7m, rmso=\E[27m,
  sitm=\E[3m, ritm=\E[23m,
```

Put this into a file(~/screen-256color-it.terminfo) and compile with `tic ~/screen-256color-it.terminfo`

If @ZyX-I is correct, this is a gnome-terminal(most likely libvte) bug. The `script` output is required to confirm.

**Comment by sittim** [comment]
So the interesting thing is, everything is displayed correctly, then all of a sudden bunch of escape sequences become visible.  Then once I click on the line with the escape sequences, the line updates and the issue disappears.

Yes, the terminal issue is crazy, I can never figure it out on Ubuntu, I do not have the `tmux-256color` see below:

```bash
/usr/share/terminfo$ find -name "xterm-color"
./x/xterm-color
/usr/share/terminfo$ find -name "xterm"
/usr/share/terminfo$ find -name "xterm-256color"
/usr/share/terminfo$ find -name "tmux-256color"
/usr/share/terminfo$ 
```
Then:

```bash
/$ sudo find -name "tmux-256color"
/$ sudo find -name "xterm-256color"
./lib/terminfo/x/xterm-256color
/$ sudo find -name "xterm"
./lib/terminfo/x/xterm
./usr/share/vte/termcap-0.0/xterm
./usr/share/vte/termcap-2.90/xterm
./usr/share/vte/termcap-2.91/xterm
./usr/share/menu/xterm
./usr/share/doc/xterm
./usr/share/icons/DMZ-Black/cursors/xterm
./usr/share/icons/whiteglass/cursors/xterm
./usr/share/icons/handhelds/cursors/xterm
./usr/share/icons/redglass/cursors/xterm
./usr/share/icons/DMZ-White/cursors/xterm
./usr/bin/xterm
/$ 
```

**Comment by sittim** [comment]
@tarruda

Following your recommendation above and compiling:

```bash
/$ sudo find -name "screen-256color-it"
./home/sporty/.terminfo/s/screen-256color-it
```
Added the tmux entry:
![selection_043](https://cloud.githubusercontent.com/assets/8825037/10544429/5fc082c0-73f1-11e5-9ee7-da6301c3bcdf.png)

Now there is no 256 colour and no italics.

Tried changing .tmux.conf entry to `set -g default-terminal "rxvt-unicode-256color"` and now:

 ```bash
$echo $TERM
rxvt-unicode-256color
```

 which seems to work fine.  I am going to try it for a while.

**Comment by sittim** [comment]
@tarruda 
@ZyX-I

This issue is elusive, escape sequences show up, move to the line and they disappear.  This is not a debilitating issue, it does not bother me too much, I am just going to ignore it.  So I am closing this issue.

thanks...

**Comment by vbauerster** [comment]
https://github.com/tmux/tmux/blob/2.1/FAQ#L355-L383
