### ISSUE TITLE
Consider adding new command `tvim` to open files in current session within neovim terminal

### ISSUE THREAD

**Issue by GregorySchwartz** [neovim/neovim#3464]
This command is essential to my workflow. There are many scripts which can do this, for instance https://gist.github.com/tarruda/37f7a3e22996addf8921. Having this command, especially an easy alias named `tvim` or an added option `nvim -t`, would be very easy to implement and would contribute to users such as myself who use neovim as a replacement for multiplexers such as tmux.

**Comment by justinmk** [comment]
blocked by https://github.com/neovim/neovim/issues/3119 . I am strongly against shipping anything with a python dependency.

**Comment by GregorySchwartz** [comment]
Can it be an optional dependency? Only included if python is installed along with it? I'm also all for doing a `nvim -t` as I realized that when `vimdiff` commands were removed in favor of the `vim -d` command the aim was to have arguments instead of separate commands.

**Comment by Pyrohh** [comment]
I don't see the need for yet another flag to `nvim`; is there any significant benefit to just renaming the script in question to `tvim` and putting it in your `$PATH`?

Since not everyone would use this, a less intrusive way to accomplish this could be shipping the script in `contrib/`, perhaps even installing it like this (edited for brevity):
```
/usr/local/share/nvim
|-- runtime
    |-- autoload
    ...
|-- contrib
    `-- scripts
        `-- tvim.py
```

**Comment by justinmk** [comment]
Vim traditionally ships with a `runtime/tools/` directory for things like this. I believe we removed it because all of the tools were outdated, but we could always add it back.

Ultimately though, yes, the goal is to make things like this so common and ubiquitous that a 2-line sample script in the help is all that is needed. Better to educate and enable, than to serve warm ice cream like `evim`.

**Comment by Pyrohh** [comment]
Given what's been said I'll close this; perhaps it can be touched on later.
