### ISSUE TITLE
.nvimlog is still being created in $HOME

### ISSUE THREAD

**Issue by jrobeson** [neovim/neovim#3561]
Whenever i edit a file with nvim I end up with `~/.nvimlog`. It should probably go in `$XDG_DATA_HOME/nvim`

**Comment by jrobeson** [comment]
I wonder if it should also be renamed to `nvim.log`

**Comment by Pyrohh** [comment]
Not sure about this. I thought the plan was to not have logs in release builds, so the majority of users (once there's a release) won't notice the lack of XDG-compliance for logging, and it might be preferable to just avoid the complexity in the first place.

**Comment by jrobeson** [comment]
I think the inconsistency creates complexity.

**Comment by Pyrohh** [comment]
> I think the inconsistency creates complexity.

Yes, but I was referring to the implementation. Anyways, that worry was misplaced given how #3562 is turning out, so please ignore.

**Comment by 5paceToast** [comment]
Neovim has a surprisingly sane XDG implementation.
However, now that someone has asked to add the capability to override the location it might be a bit more complex.

**Comment by tarruda** [comment]
Since we'll disable logging for release builds(#3318), there's no need for this issue to be in the 0.1 milestone

**Comment by 5paceToast** [comment]
Speaking of which, is there any particular reason we disable logging for release builds?

If it's in `~/.nvimlog` that's understandable, but if it's in `$XDG_DATA_HOME/nvim/log` I don't see a reason to disable it outright (maybe a `init.vim` option instead)?

Also, should we potentially default to use the system logger (e.g `/dev/log` ala `syslog(3)`?)

**Comment by Pyrohh** [comment]
> Speaking of which, is there any particular reason we disable logging for release builds?

AFAICT the logs aren't useful in most cases to end users... maybe someone else can expand on that.

> Also, should we potentially default to use the system logger (e.g /dev/log ala syslog(3)?)

Definitely not IMO: I almost never see that used by anything but system-wide userspace daemons & kernel related errors, i.e., things presumably important to all users. If a user running Nvim encounters an error, it's probably pertinent only to that user, so syslog(3) would be inapropriate (assuming that per-user syslogd instances are not being used).

This is of course not considering the possibility of Nvim acting as a daemon (like Emacs), so no comment there.

**Comment by 5paceToast** [comment]
>AFAICT the logs aren't useful in most cases to end users... maybe someone else can expand on that.

I don't see any reason to hide them away / restrict them though, especially not at compile time. What if some user wants logging, but also wants -O2, without -g? Add to that that most users will actually get binary variants, that will typically be compiled in Release mode... Maybe simply have a :set (no)logfile? Essentially I don't see the harm in including logging (even by default), as long as it's hidden away somewhere outside of $HOME.

>Definitely not IMO: I almost never see that used by anything but system-wide userspace daemons & kernel related errors, i.e., things presumably important to all users.

Typically, kernel logging goes into `/proc/kmsg` and similar. `/dev/log` is kept for userspace stuff (which typically includes daemons). Per-user logging from `syslog(3)` isn't really that complicated (e.g syslog). Moreover, proper logging systems also tend to divide / search through data, so user-specific stuff wouldn't end up in the same place as global logs; but I see the concern.

Then we add on the fact that nvim may eventually evolve into a daemon (potentially for all users to use?), and it makes much more sense.

The main reason I asked is because it's becoming clear we need a more standard way to log (and potentially perform globbing), and `syslog(3)` was the first thing that came to mind :)

**Comment by Pyrohh** [comment]
> Typically, kernel logging goes into /proc/kmsg and similar. /dev/log is kept for userspace stuff (which typically includes daemons)

Oh yeah, I mean that both of those logging facilities output to `/var/log/messages` on my machine; probably should have mentioned that, sorry.

> (and potentially perform globbing)

What do you mean here?

**Comment by 5paceToast** [comment]
>Oh yeah, I mean that both of those logging facilities output to /var/log/messages

Oh I see, my setup is rather interesting:
- `/var/log/logs` : global /dev/log, with subdirs for stuff like user logs, auth logs, etc (and an obligatory "everything" log.
- `/var/log/service/*` : each daemon that has logging gets its own log
- `$HOME/.local/log/*` : each user-started daemon log. (to be fair, I haven't implemented it yet, because I don't have enough daemons I start as a user to justify it, but I easily could at any time).

So from my perspective, with logs so separated, it wouldn't be a big deal (e.g it would just end up in `/var/log/service/nvim` at worst).

>>(and potentially perform globbing)

>What do you mean here?

Currently, we use `expand_env` to perform globbing (this is expanding `~`, `$variables` and similar (e.g `%APPDATA%` on windows) into their meanings).

I'm under the impression that `expand_env` is non-standard. Please see my [comment](https://github.com/neovim/neovim/pull/3562#issuecomment-152766255) on the relevant area.

**Comment by Pyrohh** [comment]
> So from my perspective, with logs so separated, it wouldn't be a big deal (e.g it would just end up in /var/log/service/nvim at worst)

To clarify, I think per-daemon log files are a good idea, I was just objecting to the use of the syslog(3) interface.

At least on OpenBSD (maybe FreeBSD too?) there are a finite number of [syslog logging facilities](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man3/closelog.3?query=syslog&sec=3), so it doesn't seem like you can use syslog(3) to log to, for example, `/var/log/services/cool_daemon.log`; you'd have to manually deal with logging in your application with fprintf() or something. This seems to be what samba and mpd do.

> Currently, we use expand_env to perform globbing (this is expanding ~, $variables and similar (e.g %APPDATA% on windows) into their meanings).
> 
> I'm under the impression that expand_env is non-standard. Please see my comment on the relevant area.

I understand, thanks.

**Comment by ZyX-I** [comment]
@Pyrohh How is logging facility related to the target file? You use LOG_USER facility in nvim, but in the syslog daemon configuration you tell it to put neovim logs into /var/log/nvim.log. Do not know about \*BSD, but rsyslog used in Gentoo (one of the variants of syslog daemon, other users may prefer other daemons) provides this feature. Syslog-ng also seems to allow this (at least, it has necessary filters described in documentation).

Not sure what exactly is meant by program name, but I think it is a value of the first argument to `openlog()`.

**Comment by ZyX-I** [comment]
@Pyrohh Man page http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man5/syslog.conf.5?query=syslog%2econf&sec=5 shows that in OpenBSD you can also put logs from different applications to different files.

**Comment by Pyrohh** [comment]
@ZyX-I 

> How is logging facility related to the target file?

By default (no syslog.conf), LOG_DAEMON-type messages, seem to be logged to /var/log/daemon, while LOG_USER, LOG_INFO, and probably other types are logged to /var/log/messages.

> Man page http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man5/syslog.conf.5?query=syslog%2econf&sec=5 shows that in OpenBSD you can also put logs from different applications to different files.

Thanks, I wasn't aware of that. I still don't think we should be offloading the responsibility of customizing syslog.conf to users, as opposed to just having per user logging in `$XDG_DATA_HOME/nvim/log` (less obtrusive), although you don't seem to be explicitly suggesting that.

**Comment by 5paceToast** [comment]
I'm not too familiar with *BSD logging (I personally use runit+socklog, so definitely not a "typical" setup either), so I'm fine with avoiding `syslog(3)`, just wanted comments.

I do think the globbing part is relevant, however : why reinvent the wheel (especially when it seems not to be functioning in all cases, as in #3562)?

**Comment by philix** [comment]
I'm the one who introduced the logging macros.

> I'd prefer a "top-level" location like $HOME for this, but that's just me.

@mreed1 that's exactly my rationale for creating `.nvimlog` in the $HOME. It's a debug tool that should be easily accessed by developers.

> I think the inconsistency creates complexity.

@jrobeson the log is not a config file. It's a development tool and shouldn't be available in the Release builds.

@5paceToast logs shouldn't be enabled in Release builds because they're not informative or especially useful to users. This log implementation is inefficient (open file, write, flush, close file) and we would be afraid to use the logging macros inside hot loops if they were supposed to be in the Release build.

**Comment by justinmk** [comment]
`Release`, `RelWithDebInfo`, and `MinSizeRel` builds have logging disabled:

https://github.com/neovim/neovim/blob/35d7b70d0fc00bca4a87bd2187b69719d060a7d7/CMakeLists.txt#L85-L94                                                       

And I tend to agree with @philix's rationale about the location of the log file: the location is the least of our worries. So let's close this.

**Comment by caesar** [comment]
It's a pity this was closed. I thought with Neovim I would finally be able to clear Vim's junk out of my home dir. No such luck.

**Comment by wsdjeg** [comment]
agree with @philix I need the log file in $HOME, it will be easily accessed.

**Comment by caesar** [comment]
Why is it so much easier to access in $HOME than anywhere else?

  

Anyway, if some people want it in $HOME maybe there should be an environment
variable to override the location; but it doesn't mean the default should be
to put it there and clutter up people's home directories.

  

(And if you are going to put stuff straight in $HOME regardless, please at
least remove the false claim about being XDG compliant.)

**Comment by wsdjeg** [comment]
@caesar because it is easily accessed by `nvm ~/`

**Comment by ZyX-I** [comment]
@wsdjeg It is much easier accessed by `nvim .nvimlog` without any `~/`. I also do not like this cluttering, and release builds are not an option if you are a developer.

**Comment by wsdjeg** [comment]
@ZyX-I you mean create .nvimlog in current dir or neovim repo root dir?
1. if you mean current dir, I think I need add `.nvimlog` into ~/.gitignore or add into each project's gitignore.
2. if you mean the root dir of neovim repo, it will be hard for user to easily accesse log file .
for example, it I use nvim as a tool to develop other project, how could I easily accesse the log file, when I get some bug?

**Comment by philix** [comment]
The log is a debugging tool used by the developers.

As an end user you don't see it. If you turn on logging in your release build (by forcing a #define), nvim may also slow down. It's not how it is supposed to be used.

**Comment by ZyX-I** [comment]
@wsdjeg Current directory. And just do not use development neovim for regular work.

**Comment by caesar** [comment]
@philix As an end user I do see it, because I'm using a nightly, because it has many features not yet available in the latest release.

Maybe logging should be optional in nightlies too?

**Comment by caesar** [comment]
@wsdjeg I just installed from Homebrew (head) using Neovim's tap (`neovim/neovim/neovim`). If it's possible to use those build types on head, maybe that should be fixed in the brew formula.

**Comment by ZyX-I** [comment]
To enable logging on regular basis syslog would really be better: it is faster then current “on *each* LOG call open log file, write, close log file”, it can receive new log message while writing previous one (currently I have 42 Vim instances open at once, guess what will occasionally happen with log if these were Neovim instances if Neovim does not even bother to `flock` the log file) and it does not clutter your home directory, current directory or whatever, also less code is needed. And this also does not require writing code to handle cases from “$XDG_\*” is undefined to “directory is not writeable”. The only bad things are 1) that log is harder to access in this case, but since this logging is for developers and to make access easy it is enough to do some setup once… And 2) that it may be trickier to set up on Windows.

All build types are possible to use on HEAD, AFAIR @jszakmeister’s CI service is building with release types as well.

**Comment by wsdjeg** [comment]
> currently I have 42 Vim instances,

if it is neovim, all nvim instances should not use only one log file.

> enable logging on regular basis syslog would really be better

ok I got it, but I use neovim build form source, the the build step is 
```p
make distclean
make clean
make
sudo make install
```
so if neovim change it's logfile to current dir,please let me know, I do not want push `.nvimlog` to my repo.
