### ISSUE TITLE
set paste causes pasted contents to be indented

### ISSUE THREAD

**Issue by myitcv** [neovim/neovim#3566]
I couldn't find an issue that reports this, and hopefully this isn't an error on my side. But the difference in behaviour between vim and neovim suggests there may be an issue.

```
NVIM 0.0.0-alpha+201510292110 (compiled Oct 30 2015 14:05:01)
Commit: 4abf108f4639af1c35bc0554a069d878a50fcea0
```

Terminal is xterm on Ubuntu 15.04. I also have the following defined in my `.Xresources`:

```
XTerm*VT100.Translations: #override \
    Mod1 <KeyPress> V               : insert-selection(CLIPBOARD,PRIMARY,CUT_BUFFER1) \n
```

Here are the repro steps:
- Copy the HTML below
- Open neovim using the config below in a file passed to the `-u` flag: `nvim -i config.vim test.html`
- Enter insert mode
- Press `Mod1 + v` to paste 

Notice that the contents are not indented.

Now repeat the above but `:set paste` before you enter insert mode. 

Notice now that when you paste the contents _are_ indented.

This seems to be the inverse of what should be happening according to `:help paste`. 

Indeed, running exactly the same test with vim correctly indents the contents when _not_ in `paste` mode and does not indent when in `paste` mode.

Config:

``` vim
" config.vim
filetype on
filetype indent on
```

The HTML:

``` html
<html>
<head>
<title>This is a test</title>
</head>
<body>
<div>
<p>My first test</p>
</div>
</body>
</html>
```

**Comment by justinmk** [comment]
Confirmed. Very annoying.

**Comment by myitcv** [comment]
No doubt [this comment](https://github.com/neovim/neovim/issues/4292#issuecomment-188227519) is related.

**Comment by justinmk** [comment]
Yep.

**Comment by bobbymcshane** [comment]
+1

**Comment by tgy** [comment]
I just switched to neovim and I confirm this is still happening today. 🐤  Waiting for you @justinmk!

**Comment by silenius** [comment]
same here (FreeBSD + tmux + urxvt)

**Comment by loolo78** [comment]
Confirm, NVIM 0.1.7

**Comment by KillTheMule** [comment]
You sure about that? I'm on 0.1.7 as well and can't reproduce it.

**Comment by jsermeno** [comment]
Can confirm on nvim 0.2.0. Just now tried out nvim on OS X. Downloaded it with brew.

**Comment by oslerw** [comment]
I can confirm this happens to me too. I'm using nvim v0.2.0 in tmux 2.2 on CentOS 7 over Mosh 1.2.5 on rxvt-unicode v9.21. I tried with `nvim -u NONE` to make sure it's not my `.vimrc`. It works properly for me with the same setup on Vim 7.4.

Repro:
1. `nvim -u NONE`
2. Copy and paste indented code from a web browser
3. Enter insert mode
4. Ctrl+Shift+v (rxvt's paste shortcut)

Result:  
Every line is more indented than the previous and doesn't match the source in the clipboard.

**Comment by justinmk** [comment]
Make sure 'paste' option is not set.

**Comment by tgy** [comment]
I confirm that everything works fine. In my previous vim (not nvim) workflow, I used to to `:set paste` before pasting to deactivate auto-indentation and then `:set unpaste` afterwards. nvim seems to be doing that automatically when pasting in a buffer. I feel like nvim **toggles** the auto-indentation before pasting and toggles it again after pasting. This means that if you `:set paste` in nvim, you disable auto-indentation but then nvim re-activates auto-indentation before pasting (because it's toggling), your clipboard is then pasted with auto-indentation **ON** (which, of course, is not what we want), before ironically re-disabling auto-indentation. Just need to change your pasting workflow when switching from vim to nvim I guess? 

Those are conclusions I drew from my user experience, which means I might be wrong. Someone actually working on neovim could potentially confirm this. I don't know if this 'feature' is documented. If it's not, it might be a good idea to make it available for disoriented people switching to neovim.

**Comment by oslerw** [comment]
I forgot to add the `:set paste` in my previous comment, I updated it. I can confirm it works just fine without `:set paste`, which is explained by the toggle behavior.

Is it possible instead of doing a toggle to set paste and then unset paste? I feel like this would be more intuitive and closer to what Vim users expect. That being said, it's good to know that `:set paste` isn't really necessary in the first place with Neovim.

**Comment by justinmk** [comment]
It's a known issue. This issue will be closed/updated when it's fixed.

**Comment by PrismaPhonic** [comment]
Still is an issue on my end.  This still hasn't been fixed?!

**Comment by tgy** [comment]
@PrismaPhonic have you read my previous comment? Maybe you just need to change your workflow
