### ISSUE TITLE
Improve NeoVim spelling feature

### ISSUE THREAD

**Issue by rainerborene** [neovim/neovim#3576]
I do remember seeing a discussion on IRC about refactoring spelling feature. I have decided to raise this issue again on GitHub. `spell.c` has over 13 thousands lines of code and removing it from NeoVim code base would be a real gain in maintainability. NeoVim should use an external spelling checker program like Aspell, Ispell or Huspell.

@tarruda what do think about adding a `spellprg` vim option?

**Comment by rainerborene** [comment]
ping @ZyX-I

**Comment by jalvesaq** [comment]
I like on the fly spell check, and Vim's spelling engine is better than any other that I know because it can highlight Rare words and Words of other regions (like British spelling if you are writing in American English and your spelling list includes both regions). I use the Rare words feature to highlight words correctly spelled but that I probably would only type by mistake. So, I hope that the Neovim team decides to keep the spell checking feature.

**Comment by ZyX-I** [comment]
@rainerborene How am I related?

**Comment by justinmk** [comment]
Yep, the buil in spell check has some unique features. What is the benefit of using external tool ?

BTW, this is covered in a very old, open issue.
