### ISSUE TITLE
Terminal mode and terminal titles

### ISSUE THREAD

**Issue by jordansissel** [neovim/neovim#3604]
I have found that in `:terminal` mode, neovim doesn't seem to pass terminal title settings up into neovim's buffer name nor to the terminal title.

Ideally, the terminal escape sequence indicating 'set the title' would do two things:
* set the buffer name to the title provided
* forward the sequence to the terminal running neovim to set the window title

Tested with neovim 0.1.0 via brew on osx 10.11.

Some screenshot examples of what I'm seeing not work:

![screen shot 2015-11-04 at 3 05 13 pm](https://cloud.githubusercontent.com/assets/131818/10955153/b2c3da7a-8306-11e5-8a68-e1f0a480ddac.png)

![screen shot 2015-11-04 at 3 12 31 pm](https://cloud.githubusercontent.com/assets/131818/10955154/b2c44064-8306-11e5-9f3b-cb6fbc5a1225.png)

**Comment by jordansissel** [comment]
cc @tarruda (based on some discussion on neovim gitter)

**Comment by jordansissel** [comment]
![screen shot 2015-11-04 at 3 20 38 pm](https://cloud.githubusercontent.com/assets/131818/10955290/a303fd26-8307-11e5-830b-1953b8f0eac0.png)

**Comment by jordansissel** [comment]
Reading the neovim code, I found that in a terminal, whenever the terminal title is set, it sets a buffer variable `b:term_title`. 

So I was able to achieve this was:

```
set statusline=%{b:term_title}
set titlestring=%{b:term_title}
```

**Comment by ZyX-I** [comment]
@jordansissel I think you do not understand what you are asking. Buffer name *must not* be equal to terminal title because it is saved in sessions. You can run `:edit term://.//47621:bash` and get terminal with bash open. You can’t do this with `edit hello\ world`. AFAIR it was already discussed somewhere, but I do not remember if there was a result: basically there are only two variants: save title as a *part* of a buffer name and saving it inside the buffer variable.

**Comment by ZyX-I** [comment]
Apparently the result was a buffer variable.

**Comment by jordansissel** [comment]
@ZyX-I I know what I am asking, I used the wrong vim-code-specific terminology. I found what I was looking for and thankfully it required no patches :)
