### ISSUE TITLE
buffers for help files saved to shada even though doc says no

### ISSUE THREAD

**Issue by ds26gte** [neovim/neovim#3635]
The documenation for 'shada' says that when % is included, buffers for help files are not written to the shada file. 

This is not currently true: such buffers are indeed saved. Either the behavior or the documentation should be changed.

**Comment by mhinz** [comment]
@ZyX-I Your opinion?

**Comment by ds26gte** [comment]
Difficult to decide. Although tradition argues for changing the behavior, changing just the doc would be easy (just delete the phrase), and probably easy enough to justify.

**Comment by justinmk** [comment]
Shouldn't save help buffers.

**Comment by ZyX-I** [comment]
Documentation has nothing to do with what was actually going on: initial condition was not saving

1. Buffers with NULL name (i.e. unnamed buffers).
2. Unlisted buffers (buffers with `&l:buflisted` option set to false).
3. Quickfix buffers (buffers with `&l:buftype` option starting with `q`).
4. Buffers on “removable media” (buffers whose name start is contained in `&viminfo` option prefixed with `r`).

Help buffers were not saved because they were unlisted, not because they were help buffers. I missed conditions 3 and 4.
