### ISSUE TITLE
Option to have gui_running set from start

### ISSUE THREAD

**Issue by rogual** [neovim/neovim#3646]
gui_running is not set until a GUI attaches to Neovim, which always happens after sourcing user config files. So, config files and plugins that check for gui_running will never be able to detect the GUI.

It would be good to have another flag to send alongside `--embed` that tells Neovim it's running inside a GUI app and so can set the flag from the very start.

**Comment by mhinz** [comment]
Vim only got away with this, because it has a less flexible architecture. Personally I'm in favour of convincing people to use the `GUIEnter` and `VimEnter` events instead, which is a technique that makes sense and already works.

**Comment by justinmk** [comment]
Though it is an unfortunate hack, I can't see a way around it. If we're going to support multiple displays (which we implicitly have committed to, by supporting client-server architecture), then we can't ignore the edge cases. 

Perhaps we should allow overriding arbitrary features via something like `--force-has='foo,bar'`? Or did I jump the shark?

**Comment by equalsraf** [comment]
@justinmk, in a related discussion a while back, @tarruda [suggested](https://github.com/equalsraf/neovim-qt/issues/50#issuecomment-144718773) Neovim can launch the UI rather than the UI start Neovim (in which case has(gui_running) can be true from the start), but that would not cover all cases.

@mhinz is GUIEnter working right now? It doesn't seem to work for me.

With regards to events and backwards compatibility wouldn't it be best to use a different event name (GUIAttach/Detach), after all Neovim UIs can attach/detach at any time, and firing GUIEnter multiple times might have unexpected results for existing plugins (might as well leave it as a noop).

I think the issue with colorschemes can be solved with events, by reloading the scheme when the UI attaches/detaches. The trickier issue is user settings, because everyone is expecting to use gui_running in vimrc ([search](https://github.com/search?l=vim&q=%27gui_running%27&ref=searchresults&type=Code&utf8=%E2%9C%93)). Even if we convinced users to move GUI settings to a separate file (like .gvimrc) what happens on detach?

**Comment by tarruda** [comment]
I'm currently implementing what was [discussed](https://github.com/equalsraf/neovim-qt/issues/50) in neovim-qt issue tracker. Besides having the builtin UI being spawned by neovim, it will also split UI initialization in two parts, where the first part happens before nvimrc is sourced. This will fix the problem because the nvimrc will have `has('gui_runnig')` set correctly.

**Comment by justinmk** [comment]
Will be covered by channel info/properties, which will include the ability to find out which channels (if any) are UI channels, and info such as "rgb".

Closing this since there are similar requests.

**Comment by justinmk** [comment]
`has('gui_running')` is now supported in Nvim 0.9 https://github.com/neovim/neovim/pull/22382
