### ISSUE TITLE
Double-clicking from insert mode brings you to "INSERT VISUAL" mode

### ISSUE THREAD

**Issue by compressed** [neovim/neovim#3659]
I noticed when I am in insert mode and want to delete some text by double clicking with the mouse (to go into Visual mode) and hitting `s` or `c`, those characters are actually inserted into the text instead of performing the visual mode action; in this scenario the mode shows as `INSERT VISUAL`.
Note, in vim, the selected text is deleted with `s`/`c`.

Interestingly, if you are in insert mode, and instead of double-clicking, but click and drag, you go into `(insert) VISUAL` mode where `s`, etc. will delete the text as expected.

**Comment by bfredl** [comment]
There is an even curiouser mode: "INSERT SELECT". `set slm=mouse` and then double click in insert mode. Type some text. Press `<esc>`. Type some more text. The later typed text will replace the earlier typed text.
I wonder if one could replicate this in vim in a terminal without mouse release events (or purposefully break mouse release in the terminal), otherwise https://github.com/neovim/neovim/pull/4419#issuecomment-208040117 works in vim.

**Comment by bfredl** [comment]
The relevant neovim bug is probably: #3182

**Comment by justinmk** [comment]
Assuming this is fixed by https://github.com/neovim/neovim/pull/4873
