### ISSUE TITLE
Consider removing arbitrary UI delays on certain actions.

### ISSUE THREAD

**Issue by Earnestly** [neovim/neovim#3673]
The main one which just serves to irritate is something I've been patching out of vim itself is the various UI delays, for example one of which is when editting files marked as read only:

```diff
diff -r 4d94c8a6758a src/misc1.c
--- a/src/misc1.c	Wed Jul 30 17:21:58 2014 +0200
+++ b/src/misc1.c	Sun Aug 03 21:58:18 2014 +0100
@@ -3302,7 +3302,6 @@
 	if (msg_silent == 0 && !silent_mode)
 	{
 	    out_flush();
-	    ui_delay(1000L, TRUE); /* give the user time to think about it */
 	}
 	curbuf->b_did_warn = TRUE;
 	redraw_cmdline = FALSE;	/* don't redraw and erase the message */
```

There are quite a few of these arbitrary limits, others such as limiting user commands to starting with an uppercase letter but these might be worth their own issue.

**Comment by ZyX-I** [comment]
Limiting users to start their commands (and functions) with an uppercase letter is a good thing from backwards compatibility point: this way Vim does not have to take existing plugins into account when creating new command. Otherwise adding *any* command *is* a backwards incompatible change, just in some cases it will not hit users because command was not defined by any plugin and in some cases it will. Normally such things are solved by scoping, but Vim has quite a few scopes, and no scopes at all for functions and commands (`s:` and anonymous functions are still global ones).

**Comment by ZyX-I** [comment]
Also note that Neovim has no file `src/misc1.c`.

**Comment by Earnestly** [comment]
Yes, this issue is about UI delays, not limitations on command naming.  The patch was for vim, as a demonstration.  I'm sure there's many `ui_delay`s scattered about.

**Comment by justinmk** [comment]
Covered by https://github.com/neovim/neovim/issues/1029 , we'll drive towards a general solution for this.
