### ISSUE TITLE
overflow in reltimestr

### ISSUE THREAD

**Issue by paretje** [neovim/neovim#3685]
According to the docs, reltimestr should return the result of reltime as a string. reltime itself does return the current time when no arguments are given. `reltimestr(reltime())` does not work in NeoVim, and does seem to cause an overflow. It returns for example 67429.475945.

I'm using the packages provided on the ppa targeting Ubuntu 14.04 on Debian Jessie.

**Comment by oni-link** [comment]
`reltime()` does not return "time of day". It is *relative* to an arbitrary time in the past.  This "point in the past" does not change until a restart. `67429.475945` could be your `uptime`.

**Comment by paretje** [comment]
According to the docs, it does:
```Without an argument it returns the current time.```

**Comment by oni-link** [comment]
> Without an argument it returns the current time.

Current time is used here only as something relative to a system dependent point in time, because `The format of the item depends on the system.` (according to the docs).

Vim uses on Windows `QueryPerformanceCounter()` and otherwise `gettimeofday()` as the value of `reltime()`. Nvim uses libuv's [uv_hrtime()](
http://docs.libuv.org/en/latest/misc.html?highlight=uv_hrtime#c.uv_hrtime). Only the "difference" of two values of `reltime()` should be meaningful to us.

**Comment by paretje** [comment]
Well, I don't think the fact the format is system dependent matters here, as I'm using `reltimestr` to format it. I understand the fact that it's not the intended use of reltime, and the plugin which uses this will be updated anyway, but it might be interesting to update the docs. `current time` is at least ambiguous.

**Comment by justinmk** [comment]
`:help reltime()` was updated to clarify correct usage.
