### ISSUE TITLE
Hangs when used via rlwrap's `rlwrap-call-editor`

### ISSUE THREAD

**Issue by zengargoyle** [neovim/neovim#3716]
NVIM 0.1.0 (compiled Nov  1 2015 14:42:16)

When using rlwrap http://utopia.knoware.nl/~hlub/uck/rlwrap/ to provide readline
capability to a program, and invoking the rlwrap-call-editor function to edit the
current commandline... neovim will hang with a blank screen except for the
statusline which reads something like:

"/tmp/rlwrap_perl6_TGMlsy.pl6" [noeol] 1L, 12C

This works fine with EDITOR=vim

The command that is being run is nothing extraordinary:

/usr/local/bin/nvim /tmp/rlwrap_perl6_TGMlsy.pl6

neovim does not respond to Ctrl-C, Ctrl-Z, Ctrl-G, Ctrl-\, nor can it be
kill -TERM or -QUIT.  It takes a kill -9 to get rid of it.

**Comment by rbong** [comment]
I had an issue where neovim would not load at all, and later the exact same issue as here.
Using ```nvim --noplugin``` I determined that it was not neovim's fault. It was at this point I disabled my plugins in a binary search to determine which ones were causing problems. Disabling ultisnips fixed my not loading at all issue, at which point I experienced the same behaviour as the issue. Disabling deoplete fixed this issue.
I solved this by entering this into my shell's rc file:
```
export RLWRAP_EDITOR=nvim\ --cmd\ "'let rlwrap = 1'"
```
then wrapping the offending plugins in this:
```
  if !exists('rlwrap')
    Plug '...'
  endif
```
A plugin manager is probably required here. Since I use vim-plug, I just wrap the line that enables the plugin.

**Comment by justinmk** [comment]
@rbong Are you saying rlwrap works with nvim, for you? If not, I'm confused about how `let rlwrap=1` solves the issue, because that would still enable the rlwrap plugin. The top post in this issue suggests that rlwrap doesn't work with `nvim`, and it looks like rlwrap's `munge_line_in_editor` is manipulating the tty.

I'm puzzled why anyone would want to use rlwrap with vim. https://github.com/tpope/vim-rsi fills in the missing keybindings, and if one wants to search e.g. bash history, it would be fairly trivial to write a completion function that slurps the contents of `~/.bash_history`.

**Comment by rbong** [comment]
@justinmk: rlwrap can use an external editor to edit commands. this is where nvim comes in. defining the rlwrap variable is only to disable certain plugins that prevent nvim from launching from rlwrap.

**Comment by justinmk** [comment]
Is this still an issue?

**Comment by rbong** [comment]
@justinmk I would say that since rlwrap worked for me after disabling certain plugins this was probably never an issue for nvim specifically, but just for those plugins. Note that I am not currently able to re-test to see if it now works for those plugins since I am having unrelated problems with rlwrap.
