### ISSUE TITLE
Delay when entering Insert mode in a terminal buffer

### ISSUE THREAD

**Issue by aandrieiev** [neovim/neovim#3743]
Not like this is the biggest issue ever, but there's a noticeable delay when entering insert mode in a terminal buffer. I'd estimate it 500ms. Can be easily reproduced with running `nvim -u NONE`, opening a new terminal buffer through `:vsp term://bash`, and then pressing `i` for entering insert mode.

I navigate among splits by this sort of mapping: `nnoremap <A-h> <C-w>hi` because I like terminal buffers in insert mode by default, and this delay can become quite annoying when quickly switching between two splits back and forth. Not sure if there's a setting allowing to customize this.

**Comment by timshannon** [comment]
Might not be related, but I have about the same delay every time I try to send `Ctrl-[`  (which I use instead of escape).  But the issue only seems to be present when I'm connecting via Putty.  If I run nvim directly in a terminal on my linux box it works fine.

The added ~500ms to each time I need to escape is a showstopper for me at this point.

**Comment by timshannon** [comment]
Hm, my issue may be a known one:
https://www.reddit.com/r/neovim/comments/35h1g1/neovim_slow_to_respond_after_esc/

**Comment by mhinz** [comment]
@timshannon That's the correct fix.

The problem is this: If you have to mappings `a` and `aa`, you'll get a delay after keying in the first `a`. The what's `'timeoutlen'` is for.

Now it happens all the ancestors of Neovim used <kbd>Esc</kbd> for switching to normal mode. Now the problem is that in terminals (you don't have this problem in GUIs like gvim etc.) use escape sequences to things like changes cursor position etc.

When you now hit `<esc>` in Vim, it doesn't know if you mean the default mapping for `<esc>` or whether you want to input an escape sequence. That's what `ttimeoutlen` is for.

Usually `set ttimeout ttimeoutlen=0` is a setting everyone wants.

**Comment by aandrieiev** [comment]
@mhinz wish this fixed the issue I described above too =)

**Comment by mhinz** [comment]
@aandrieiev I can't reproduce your issue with `nvim -u NONE`, so it's probably related to your terminal emulator or its configuration.

Anyway, I'd suggest using `autocmd BufEnter term:// startinsert`.

**Comment by aandrieiev** [comment]
@mhinz you're right, it seems to be iTerm2-specific, can't reproduce it in Terminal.app either. Thanks for the tip!
