### ISSUE TITLE
Could not find expected file uv.h, or uv.h for LIBUV (compile error on CentOS 7)

### ISSUE THREAD

**Issue by thercast** [neovim/neovim#3777]
I'm trying to compile neovim on a virtual server running CentOS 7.  I made sure that all of the build [prerequisites](https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites) were installed beforehand, and verified that the autoconf version is `2.69` per the instructions.  I'm installing it within a custom user directory (the goal is to copy this over to a RHEL 6.5 server which I don't have admin rights to) using `make prefix=/home/username/nvim`.  Here's the error I receive near the end of the procedure:

```
Error: Could not find expected file uv.h, or uv.h for LIBUV -- you may have to install LIBUV in your system and/or pass LIBUV_DIR or LIBUV_INCDIR to the luarocks command. Example: luarocks install nvim-client LIBUV_DIR=/usr/local
make[3]: *** [usr/lib/luarocks/rocks/nvim-client] Error 1
make[3]: Leaving directory `/lrlhps/users/c084511/apps/neovim/.deps'
make[2]: *** [CMakeFiles/nvim-client.dir/all] Error 2
make[2]: Leaving directory `/lrlhps/users/c084511/apps/neovim/.deps'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/lrlhps/users/c084511/apps/neovim/.deps'
make: *** [deps] Error 2
```

One solution I tried was installing libuv from source, and it was installed successfully.  However after running `make distclean` and `make prefix=/home/username/nvim` again, I got the same error as above.  Am I missing a step to set up the environment correctly?

**Comment by mhinz** [comment]
I'm not sure if you can specify the prefix like this, try this:

```
make distclean
make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=$HOME/neovim"
make install
export PATH="$HOME/neovim/bin:$PATH"
```

**Comment by ZyX-I** [comment]
If you wanted to create a neovim package I would suggest ignoring top-level makefile, install (and document as the package dependency) dependencies using package manager and use what you would normally use when building cmake-based project (`mkdir build; cd build; cmake -DCMAKE_INSTALL_PREFIX=/home/username/nvim ..; make`). Neovim correctly picks up system-wide libuv in this case: from the very beginning I never used top-level makefile for building neovim. Cannot say whether it will do the same thing if you install `libuv` using system package manager and use top-level `make`.

If you installed libuv from source to /home/username/nvim this will definitely not help because it will not be searched there.

**Comment by thercast** [comment]
Thank you @mhinz and @ZyX-I for your prompt replies!  I used the revised `make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=$HOME/neovim"` proposed by @mhinz and that indeed fixed the error.  Even better, I was able to use the same compilation procedure on the RHEL 6.5 corporate server to compile neovim to a user directory and it seems to be running perfectly, so I didn't need to copy it over from the CentOS7 virtual server.  I don't have a lot of experience with `cmake` so I wasn't aware of the difference in supplying custom flags.  Thanks again!
