### ISSUE TITLE
Multiple cursors

### ISSUE THREAD

**Issue by erf** [neovim/neovim#3845]
I'd really like to see multiple cursors as a part of core neovim. After using it on vis and atom i love it and It's just much more useful than the visual block mode. I know it's a huge feature request, but it is something you have thought of?

I would like to use Ctrl-j and Ctrl-k to add cursors above or below line. Ctrl-alt-k and Ctrl-alt-k to remove cursors. Go back to single cursor on Esc. Operations should work as normal in multi-cursor mode. I would also like to be able to create n numbers of cursors by pressing a number and then Ctrl-j or by selecting equal words.

**Comment by wsdjeg** [comment]
why do not use https://github.com/terryma/vim-multiple-cursors

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/211.

BTW, what many people don't get is that Vim `%s`, `:g`, and macros are really much more useful than they realize. You can ask for multi-cursor in Vim, but then why not ask for Vim regex in the other editors? I'm guessing most people aren't taking a close look at Vim's existing features.

**Comment by erf** [comment]
Read the thread. I know substitute and macros.. but what makes vim good is the modes, motions and operations - multiple cursors are a way of doing the same, just with n more power. So i find the concept more intuitive and faster. 

[https://github.com/terryma/vim-multiple-cursors](https://github.com/terryma/vim-multiple-cursors) is pretty good but lacking some features and the development seems slow. I also think multiple cursors  should be part of core.

**Comment by justinmk** [comment]
> but what makes vim good is the modes, motions and operations 

If that were the sum, then there would be zero reason not to use emacs+evil. There's a lot of utility in Vim regex and substitute.

That's not to say that multi-cursor is not also useful. But I'm still wondering: how much time have you spent with `:s` and `:g` and how familiar are you with Vim regex?

**Comment by erf** [comment]
I am not too familiar with those tools and i am sure i could and should learn more, at the same time i think most people find regex hard to learn and substitute also has new commands to learn and you have to type commands instead of just moving around in the code, using what is already memorized in your fingers whilst visually see what is going on. In the beginning it was a bit weird to get on board with the concept of multiple cursors (in those editors that supports it), but im really loving it now and i think a project such as neovim could benefit - making it a better editor and gaining more support.

**Comment by wsdjeg** [comment]
regex is the essence of vim

**Comment by erf** [comment]
For me, the essence im vim is the ability to move around the code effectively in normal mode, doing minor operations and repeating them with dot. Maybe i'll change my mind when i learn regex.

**Comment by wsdjeg** [comment]
if you want repeating someting,maybe complex-repeat is a good choice for you，you can use the q recording mode.

**Comment by erf** [comment]
Thanks, macros and vim-multiple-cursors are very nice indeed.

**Comment by gbersac** [comment]
@justinmk macro are such a pain to write. You have to write every single characters of the word to search ! I know regex, but I always get them wrong at the first time, always forget one char or that such character should be escaped...

With sublime, I type `ctrl+d` and it just works. I select one occurence, and then it selct one - or all - in one time. 

Another problem of macro. Let's say I am looking for the 3 next occurences of `int`, but there is 5 in the file. How do I select only the 3 next occurence ? 

As I explained [in reddit](https://www.reddit.com/r/neovim/comments/44g53k/multi_cursor_in_neovim/czrlqul) vim-multiple-cursor is far from being as good as sublime text. And doest not always work.

**Comment by justinmk** [comment]
@gbersac multicursors definitely fill a gap, but the point is that people aren't exploring Vim regex and `:global` enough to make an informed case. If multicursor is more useful and powerful than Vim-regex/`:global`/macros, then there's little reason to use Vim. These features _are the valuable parts_ of Vim. Stopping the world to add multicursor to Vim--instead of improving the core features as much as possible--makes no sense.

>  know regex, but I always get them wrong at the first time,

That's a usability problem that Vim or Neovim can improve (e.g. by showing live feedback, cf. emacs).

**Comment by gbersac** [comment]
@justinmk If you want me to say that vim is outdated (it and its overly verbose macros), I totally agree witht that. Unfortunally I am sometime stuck to terminal and vim is the best option when it comes to terminal only editor. So I really hope for a text base editor with multiple cursor. I bet on `neovim` ! 

You are doing a great work, but `noevim` won't be a modern editor if it doesn't provide multiple cursors. Since sublime text, I consider this a must-have.

**Comment by justinmk** [comment]
> Unfortunally I am sometime stuck to terminal and vim is the best option when it comes to terminal only editor.

So, add multicursor to Vim for the occasional quick edit by a casual user. That's why this is a low priority :)

**Comment by gbersac** [comment]
Sure, multi cursor is just one of the reason why I am less productive with vim than with sublime text. But I'd love to have a modern terminal editor for two reason :

- My fingers are hurting because of hitting the ctrl key too often. I sometime go back to vim just for that reason.
- I'd love to switch all of my workflow to a distant server. The lack of modern terminal based editor is the main reason why I don't.

I'd love to be a regular user of vim (and already am - I just use it less than sublime).

**Comment by erf** [comment]
Reading this discussion now, i'm just curious if you, @justinmk, have really given multiple cursors a try and what you think of them? It would be interesting to introduce some analytics to se some stats of how people use vim, what operations, motions, regex, macros etc are used the most etc. For my own case, i use vim for most of my backend dev. And i would say 95 % of the time i use motions and commands in normal mode and insert. Rarely i use macros, substitute, as i find mulltiple cursors more intuitive, but im learning regex now. I agree vim core features should be main priortiy - there is quite a large issue list, and multiple cursors would probably introduce lots more. Anyways you guys are doing a great job on a great editor.

**Comment by erf** [comment]
I do suspect however that the lack of enthusiasm for multiple cursor is much because of the huge work on refactoring and improving the legacy codebase of vim.

**Comment by erf** [comment]
As a sidenote, i understand the reason neovim project started initially, was because of lack of  possibilities for contributors to add new features.. Im not a contributor but its a bit ironic that you seem so opposed to this new idea..

**Comment by justinmk** [comment]
> I do suspect however that the lack of enthusiasm for multiple cursor is much because of the huge work

Certainly, but especially because of the (estimated) diminishing returns.

And yes, I haven't spent a lot of time with mutlicursor, but I've said numerous times I recognize the use-case as a powerful middle ground between "text objects" and "macros". E.g., one person mentioned that Sublime multicursor has context-sensitive undo _for each cursor_. That's obviously really powerful. But it would be a better use of our time to enable plugins to reliably implement this than to bake it into core any time soon. The incremental steps needed to get to that point may end up eventually making it trivial to implement in core, but _until then_ it would be better to incrementally improve things, e.g. for per-cursor undo we would need to rework the undo data structures and provide fine-grained access to plugins via the API.

> its a bit ironic that you seem so opposed to this new idea..

I'm not opposed to it.

**Comment by erf** [comment]
I do think it would be a good idea to replace visual block mode with multiple cursors in the future. It would be much more powerful and might actually be easier to implement, since you would reuse most cursor functionality.

**Comment by rsdenijs** [comment]
Multiple cursors + modal modes would be 

a) Faster than writing regexps for most mortals
b) Complement regexps. I can do some inserts, go to normal mode, move a word to the right, insert again...etc
c) Get live feedback of what is happening and if im screwing up. With regexps you just dont know what failed and you only see the result of the full operation. 

The vim-multiple-cursor plugin is useful but only supports an extremely small number of normal mode commands and get incredibly slow as the number of cursors increases.

**Comment by justinmk** [comment]
> c) Get live feedback of what is happening

Live feedback is orthogonal to multi-cursor, and is definitely something we want to add to n/vim.

**Comment by balta2ar** [comment]
> But it would be a better use of our time to enable plugins to reliably implement this than to bake it into core any time soon. The incremental steps needed to get to that point may end up eventually making it trivial to implement in core, but until then it would be better to incrementally improve things, e.g. for per-cursor undo we would need to rework the undo data structures and provide fine-grained access to plugins via the API.

I hope I will speak for many of those who's missing native multiple cursors support, that we don't want you to "stop the world and implement multiple cursors right now" but at least to keep this feature request in mind when you design your data structures, algorithms, architecture and APIs so that you don't end up forgetting about it and eventually saying something like "Sorry, everything is set in stone already, craft yourself another web of hacks called nvim-multiple-cursors if you really need it".

**Comment by justinmk** [comment]
Noted

**Comment by edricgarran** [comment]
It's just much faster to point the cursor at a name and do a bunch of C-n, some C-x here and there to skip the undesired occurrences, then c<replacement>, than to write the exact regexp that matches all the occurrences without the wrong ones.
Of course there are cases where the text structure is more complex than "find everything equal to this" in which regexp substitution is much more powerful, but for the common case of renaming variables and stuff like that, thinking about a regexp is a big mental overhead over simple muscle-memorized finger movements.

**Comment by balta2ar** [comment]
Pasting here just for inspiration. Today I stumbled upon a demonstration what similar plugin in Emacs can do:
http://emacsrocks.com/e13.html
http://emacsrocks.com/e08.html

**Comment by icholy** [comment]
I used sublime before vim and multiple cursors is the only thing I still miss. My usual workflow is to record a macro `qq`. Then use `:g/pattern/norm @q` to execute that macro on matching lines. The problem is that it usually takes multiple tries to get a macro that works on all the lines you're targeting. With multiple cursors I can backtrack and continue without going through the `record`, `execute`, `check` loop.

**Comment by erf** [comment]
I'm now using the [vis](https://github.com/martanne/vis) editor. It combines sam's structural regular expressions with multiple selections as part of core, making it a very effective text editor.

**Comment by ddickstein** [comment]
Maybe someone on this thread can help answer this question for me.  I still have a lot of difficulty doing things like the following in Vim:

From 
```
1 'apple'
2 'orange'
3 'pear'
4 $fruit1 = 
5 $fruit2 =
6 $fruit3 =
```
To
```
1
2
3
4 $fruit1 = 'apple';
5 $fruit2 = 'orange';
6 $fruit3 = 'pear';
```

The best I can come up with is record what I hope is a sound macro to make the first edit, then replay it multiple times to get the other lines.  Even if I nail that macro the first time, it's complicated enough to require more thought than say dropping multiple cursors, and it's certainly more time consuming.  How do you deal with this problem quickly and efficiently in Vim?

**Comment by justinmk** [comment]
Let's keep this thread on-topic, please. Ask questions at https://vi.stackexchange.com or https://gitter.im/neovim/neovim .

**Comment by ddickstein** [comment]
You're right, that's a better forum.
