### ISSUE TITLE
terminal buffer <=> job-control

### ISSUE THREAD

**Issue by vito-c** [neovim/neovim#3855]
This is feature request is for terminal and job-control functionality. I would like the ability to be able to `attach` a currently running job to a terminal buffer. I was thinking this might be easy to implement since there is a job_id and a shell object associated with the job. There would have to be a flag as well to indicate if you want to keep the callback functions intact or remove them.

Then there should be a way to `detach` a running job from terminal buffer. I think this would probably be a bit of work but it would essentially change  a terminal buffer into a job. It would probably be similar to job-start but it takes a terminal buffer instead of some commands though the opts would be the same so you could pass callback functions to the job.

**Comment by justinmk** [comment]
See also https://github.com/neovim/neovim/issues/5023

**Comment by justinmk** [comment]
If you're requesting the ability for another job to _drive_ the terminal buffer, I don't see how that is possible. The terminal job would be fighting the attached job(s) and the buffer would be nonsense.

Otherwise this request is covered by https://github.com/neovim/neovim/issues/5023, so merging with that.
