### ISSUE TITLE
:tab all opens wiped out buffers

### ISSUE THREAD

**Issue by polyzen** [neovim/neovim#3897]
Open several files -> :bw some -> :tab all -> wiped out buffers included

**Comment by geoffharcourt** [comment]
@polyzen, what platform and build of nvim are you using? I was unable to reproduce this problem on g91b8ab3.

**Comment by polyzen** [comment]
Arch Linux
NVIM 0.1.1

1) [Open several buffers](https://ptpb.pw/2bPw.png)
2) [:bw some](https://ptpb.pw/eH1G.png)
3) [:tab all](https://ptpb.pw/3o4X.png)

**Comment by ZyX-I** [comment]
@polyzen This is expected. `:bw` does not delete from an argument list and argument list ≠ buffer list. See `:h arglist`, `:h :all`, `:h :bw`. Though last one is not clear because it states that “everything related to buffer is lost”.

@geoffharcourt If you do not have this “problem” then *you* have a bug. To reproduce use `nvim -u NONE -i NONE a b c -c bw -c 'tab all'`.

**Comment by polyzen** [comment]
Sorry about that. Now I see vim has the same behavior.
