### ISSUE TITLE
Erros in the colorscheme blue.vim

### ISSUE THREAD

**Issue by Asher256** [neovim/neovim#3899]
Hi,

As you can see in the image below, it is difficult to see the errors in Neovim, because of the red color in the colorscheme blue.

(neovim = up, vim = down)
![neovim-vim](https://cloud.githubusercontent.com/assets/8672411/12004139/aa9bc412-ab0f-11e5-918e-fae8e4e41ea3.png)

Thank you in advance!

Asher256

**Comment by justinmk** [comment]
echo $TERM
    echo $NVIM_TRUE_COLOR

**Comment by Asher256** [comment]
The result is:
TERM=xterm
NVIM_TRUE_COLOR=

Do I need to modify them manually?

**Comment by justinmk** [comment]
Try `xterm-256color`

**Comment by Asher256** [comment]
I tried it and i didn't work.

I also tried NVIM_TRUE_COLOR=1. The result is: no color at all.

**Comment by Asher256** [comment]
Any idea?

**Comment by justinmk** [comment]
No.

**Comment by tomsmeding** [comment]
@Asher256 try setting your terminal to xterm-256color mode, and if needed also putting `export TERM=xterm-256color` in your shell rc file (`~/.bashrc` if you're using bash, something else otherwise) and opening a new terminal. You can try the same rc file trick with `export NVIM_TRUE_COLOR=1`. See whether that works out.

**Comment by justinmk** [comment]
Merging into https://github.com/neovim/neovim/issues/2912. If that's not the issue, then please provide minimal steps. Current repro steps are vague and incomplete.
