### ISSUE TITLE
How can I get the standard input file which the neovim terminal emulator connected to?

### ISSUE THREAD

**Issue by skt041959** [neovim/neovim#3905]
Just like the function of `tty` command of linux coreutils. Such as /dev/pts/6.
I prefer to do this in a plugin script

**Comment by ZyX-I** [comment]
Why do you need this? Also this question is not an issue, for questions there is either neovim mailing list or gitter. Tracker is for bugs or feature requests (cannot say how this should look like now because there may be more then one UI, each with a different tty; and I have no idea how to query them).

**Comment by skt041959** [comment]
Sorry for the mistake. I will go to mail list for further help.

**Comment by tarruda** [comment]
If you need to read data from the terminal, use `termopen()` to associate a vimscript callback that will be invoked when the attached process outputs anything. If you need to send data, you can use `jobsend()` on any terminal. The job id for a terminal can be obtained with the `b:terminal_job_id` variable.

**Comment by skt041959** [comment]
Thank you!
