### ISSUE TITLE
strange   <ffffffff> chars

### ISSUE THREAD

**Issue by epirus** [neovim/neovim#4053]
when I copy the content from browser  and paste to the terminal mode

![qq20160120-0](https://cloud.githubusercontent.com/assets/2031281/12439605/40e93e92-bf6d-11e5-862e-47bd5c130134.png)

anyone can help me ?

**Comment by tohou** [comment]
I reproduced this bug, but with `<7fff9c03>` chars at the beginning and end instead. There is a bug in zsh 5.2 that does exactly this when binding shortcuts to a unicode sequence ([Relevant zsh mailing list thread](http://www.zsh.org/mla/users/2015/msg01394.html)). I thought it was that at first but the same string, when pasted outside of neovim’s terminal, is not corrupted. I paste using Shift-Insert (not possible otherwise in gnome-terminal), so the bug may also be a Paste-x-selection-in-Wayland bug.

For reference, the pasted string is all ASCII, gnome terminal 3.18.2 on wayland. The bug was reproduced with latest neovim HEAD (ee0e214).

Sorry for the long, confused and probably unhelpful answer.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/3476
