### ISSUE TITLE
vim.current.buffer[1:1] = [''] throws NvimError: Index out of bounds

### ISSUE THREAD

**Issue by nicdumz** [neovim/neovim#4058]
Hey!

The following minimal test case:

```
:enew
:py vim.current.buffer[1:1] = ['']
```

works differently between vim 7.4 and neovim (current head 297075bf47d09437deb82266c61cd830dc8d72eb)

In vim 7.4 this inserts an empty line. In neovim, this throws an Index out of bounds error.

We discovered this in google/vim-maktaba#165
Is this difference intended?

Thanks!

**Comment by watiko** [comment]
```sh
vim -u NONE '+enew' '+py import vim' '+py vim.current.buffer[1:1] = [""]'
nim -u NONE '+enew' '+py import vim' '+py vim.current.buffer[1:1] = [""]'
```

These lines are related to this issue.
https://github.com/vim/vim/blob/master/src/if_py_both.h#L4575-L4576
https://github.com/neovim/neovim/blob/v0.1.1/src/nvim/api/buffer.c#L178-L181

**Comment by nicdumz** [comment]
https://github.com/vim/vim/blob/v7.4.1143/src/if_py_both.h#L4575-L4576 refers to buffer[i:j] (read)
https://github.com/vim/vim/blob/v7.4.1143/src/if_py_both.h#L4647-L4648 is the line that refers to buffer[i:j] = foo (set)

But yes, essentially for buffer[i:j] the bounds are being clamped in vim, whereas the nvim implementation does something closer to the native Python list[i:j] operator.

**Comment by mhinz** [comment]
@tarruda Should this be changed in the python client or in the API (`buffer_set_line_splice`)? I'd look into it if the latter is allowed.

**Comment by bfredl** [comment]
> But yes, essentially for buffer[i:j] the bounds are being clamped in vim, whereas the nvim implementation does something closer to the native Python list[i:j] operator

Actually, I think the native python list is closer to vim in this case, as
```
l = [''] # as an empy buffer
l[1:1] = ['new line']
l == [``, 'new line']
```

Essentially the same issue is neovim/python-client#155 . I think the proper fix is in `buffer_set_line_splice` to avoid an extra call for this special case.

**Comment by mhinz** [comment]
Agreed, I'm looking into it then.

**Comment by bfredl** [comment]
Probably that ship has sailed by now, but really I would rather change `buffer_set_line_slice` to not use the ad-hoc `include_start` / `include_end`, and used a pure offset-based indexing. To just directly use the python convention doesn't work, as there is no numeric value for the offset-past-the-end (without explicitly using the length of the sequence) . An alternative could be the, simpler but admittedly still ad-hoc, scheme where -1 instead means the offset-past-the-end, so that [0,-1] is the entire buffer and [0,-2] would be all except the last item. now the empty-range-past-the-end would be [-1,-1] which (correct me if I'm wrong) cannot be expressed in python without explicitly the length of the buffer.

**Comment by bfredl** [comment]
(correction, this kinda can be exprssed in python using `seq[SIZE_MAX:]` if one happens to know the size of the platform)

**Comment by mhinz** [comment]
Well, in this case I pass the ball to you. ;]

My solution would be adding something like:

```c
  // Append lines at the end of the buffer.
  int64_t buflines = (int64_t)buf->b_ml.ml_line_count;
  if (start > buflines) {
    // magic;
  endif
```

Fixing the problem at hand wouldn't be hard, but I'm not sure what's the best solution. I'd rather fix Vim's Python interface instead, but that's probably not gonna happen. (Appending to the end of the buffer, when the index is out of bounds, is more confusing than convenient, IMHO.)

**Comment by bfredl** [comment]
the index is not out of bounds, as an empty buffer still contains one empty line. This is really a special case of vim rather than vim's python interface (`ddP` is a no-op except when the buffer contains one line, in case it generates one extra blank line). 

The problem here is not lack of magic, rather that the bound check commutates badly with the handling of `include_start`, that's why i ranted about it :) (and more generaly becasue it multiplies the number of special cases, combining with normal/end-relative and two range endpoints gives eight different cases to check)

Python by itself is even sloppier, this is absolutely fine
```
l = ['a']
l[20:30]
l[30:20]
l[-30:20]
```
To really support both this _and_ stricter languages we would need a `coerce_out_of_bounds` flag to coerce out-of-bounds indicies to their closest valid value, or throw an error as we do now.

**Comment by bfredl** [comment]
Thinkning about it more allowing `INTEGER_MAX` as the past-the-end value even with boundcheck might be "conceptually" cleaner than shifting all negative indicies, but it means leaking this special vaule to the API which is not nice... 
Anyway, I will begin with seeing if the implementation could be simplified without changing the API.

**Comment by mhinz** [comment]
:+1: Thanks for the effort.

**Comment by justinmk** [comment]
> but really I would rather change buffer_set_line_slice to not use the ad-hoc include_start / include_end, and used a pure offset-based indexing

The ship has _not_ sailed. We _should_ deprecate `buffer_{g,s}et_line_slice` and provide a new functions: `buffer_get_lines` and `buffer_set_lines`. I would even suggest deprecating the single-line variants, `buffer_get_line`/`buffer_set_line`.

**Comment by nicdumz** [comment]
PR #4083 was merged. I just verified it indeed fixes the issue.
