### ISSUE TITLE
terminal title not restored after exit

### ISSUE THREAD

**Issue by teto** [neovim/neovim#4063]
Tried with nvim -u NONE in urxvt:
:set title
:q 
Leave neovim and the urxvt still has NVIM in its title. Vim restored the original title.

```
nvim --version   
NVIM v0.1.2-324-gbcbcf23
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/teto/neovim/config -I/home/teto/neovim/src -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include/luajit-2.0 -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include -I/usr/include -I/home/teto/neovim/src/nvim/auto -I/home/teto/neovim/include
Compilé par teto@teto-Mac

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   fichier vimrc système : "$VIM/sysinit.vim"
  $VIM par défaut : "/usr/local/share/nvim"
```

**Comment by mkoskar** [comment]
The problem here is that `title` is not set to `on` by default.

From `:help 'title'`:

    'title'                 boolean (default off, on when title can be restored)

It is set correctly in case of `vim -u NONE` but not for `nvim -u NONE` (tested with `xterm`, `urxvt`, `termite` and `st`).

Doing `:set title` explicitly will set the title but not restore original one since it wasn't able to retrieve it. This is usually not noticed because shell will often set new title as a part of issuing its prompt.

Also reading the `:help 'titleold'` it seems to me that in this case (`original title cannot be restored`) `titleold` should be used to restore the title, which is not the case.

It seems to me that support for restoring title was removed during UI refactorings.

Skimming through `vim` codebase, it retrieves title going to X window directly and then sets it if it can via terminal escape sequence. I've stumbled across this some time ago and it's problematic. In my case running `vim` in `tmux` and having `tmux` to prepend its session and window name before the title set by application running in tmux pane. `vim` will always restore the full title it got by bypassing `tmux`, resulting in doubled prefix. Removing such prefixing is workaround. For `nvim` it would be good for `TUI` to use some existing escape sequences (I don't know how they are supported though).

So to be consistent with `:help 'title'` and `:help 'titleold'`:

* `title` should default to `on` if UI successfully retrieved current title (in case of TUI `Report xterm window's title` escape sequence can be used?)
* else `title` defaults to `off` and when `:set title` is done explicitly so title is "forced" then on exit value of `titleold` should be used to set title

**Comment by justinmk** [comment]
@mkoskar Thanks, that is helpful. Yes, Vim has many special cases for different terminals including rxvt which we removed.

> Skimming through vim codebase, it retrieves title going to X window directly and then sets it if it can via terminal escape sequence. I

Does that require linking to X? Does it work in `vim-nox`? 

> - title should default to on if UI successfully retrieved current title (in case of TUI Report xterm window's title escape sequence can be used?)

Sounds good. Or we could just assume the title is always accessible?

**Comment by mkoskar** [comment]
> Does that require linking to X? Does it work in vim-nox?

It does require connection to X server. I've realized it's even mentioned in `vim(1)`:

    -X          Don't connect to the X server.  
    Shortens startup time in a terminal, but the window title and clipboard will not be used.

So running with `vim -X` indeed `title` defaults to `off` and title is not changed, setting manully `:set title` sets title, and on exit it is "reset" to `titleold` which is `Thanks for flying Vim`. So in other words my initial theory was right. If `titleold` is empty it will not be set.

> Sounds good. Or we could just assume the title is always accessible?

I'm not sure, I mean there are use-cases where `vim`/`nvim` as `$EDITOR` is started from other programs or scripts e.g., `mutt`, and some programs don't refresh its title on editor's return (like e.g., shells do when prompting). In that light current logic makes sense, and is quite comprehensive maybe even bit over-complicated, but can be helpful for somebody.

Regarding the escape sequence I was talking about. It is `printf $'\e[21t'` and it works in `xterm` but has to be enabled with `allowWindowOps` and in `urxvt` with `insecure`. I guess it's not feasible to use it since it has security implications which are not worth it. Seems like only way to do it is the Vim's way (by connecting to X server), though I don't like it much since it's kind of a hack. Simplest "solution" would be to say that no attempts for recovery of original title would be done, and possibly leave `titleold` (but defaulting it to empty string) to be used on exit if it is non-empty.

**Comment by egmontkob** [comment]
Whereas `\e[21t` does indeed have security implications, title stacking (`\e[22t` and `\e[23t`) might be another approach to consider. For me, it works in xterm; alas does not work in any other emulator I've tried (including vte, konsole, urxvt, terminology, pterm, st).

(vte feature request: https://bugzilla.gnome.org/show_bug.cgi?id=699819)

Regarding connecting to the X server: It's quite fragile; some emulators might have a custom window title format (somehow derived from the application-specified title, or not even including that one, e.g. konsole is very flexible here), and also goes wrong if a window has multiple tabs and vim is not starting up in the active one.

**Comment by blueyed** [comment]
There are relevant settings `&t_ts` and `&t_fs`, which are still documented in term.txt, but appear to not be used anywhere?
While I am setting the title in my shell after Vim exited manually, I've noticed that Neovim behaves different to Vim when it is being invoked during some process (`pacaur` in this case to edit PKGBUILD files).

**Comment by nateozem** [comment]
Update from last response and if somebody would like to chime, please do. `t_ts` & `t_fs` options have been removed and this is documented in `vim_diff.txt` about the removal of `t_XX` options & `<t_XX>` keycodes.

**Comment by nateozem** [comment]
With vim 8.0, if `titlestring` is set before or after switching `title` and then disable `title`, the terminal title has changed to "Thanks for flying Vim" without quitting. Should Neovim have the same implementation?

**Comment by justinmk** [comment]
@nateozem That's already explained in https://github.com/neovim/neovim/issues/7129#issuecomment-323288233

**Comment by ddddavidmartin** [comment]
This issue has been bugging me quite a bit as I rely on the terminal titles to determine what I have open in my tabs. As a workaround I have set the shell to delete the terminal title before a prompt is printed. The below is for zsh in `~/.zshrc` but I'm sure that bash has an equivalent. Maybe it helps someone else until this issue is resolved properly.

```
function precmd() {
    # Clear the terminal title before running any command.
    # This is a somewhat hacky workaround to Neovim not refreshing the title
    # after it exits.
    printf "\033]0;\a"
}
```

**Comment by justinmk** [comment]
#7191 restores 'titleold' feature, which closes #7129.

https://github.com/neovim/neovim/issues/4063#issuecomment-200355616 explains why detection (or alternative: stacking) is almost never available, so supporting that is a low priority. But we can keep this issue open.

**Comment by teto** [comment]
title stacking was pushed to VTE https://github.com/GNOME/vte/commit/23c44f1f18b7985d9fba3205500d8873ecde51aa \o/

**Comment by justinmk** [comment]
@egmontkob Thanks for mentioning that. I wonder if we should add it to our builtin (fallback) terminfo definitions too.

**Comment by oblitum** [comment]
This issue still happens for me with TMUX:

```
~ ❯❯❯ tmux display-message -p 'title:<#{pane_title}>'
title:<leibniz>
~ ❯❯❯ vim
title:<vim [No Name] +0 #1.1>

Press ENTER or type command to continue
~ ❯❯❯ tmux display-message -p 'title:<#{pane_title}>'
title:<>
~ ❯❯❯ nvim
~ ❯❯❯ tmux display-message -p 'title:<#{pane_title}>' 
title:<nvim [No Name] +0 #1.1>
```
Vim 8.1.751
NeoVim 0.3.4
tmux 2.8

ArchLinux

**Comment by oblitum** [comment]
I'm trying to use https://sunaku.github.io/tmux-select-pane.html, but due to the above issue, I can't. Vim clears it, but NeoVim doesn't.

**Comment by justinmk** [comment]
@oblitum 	As explained in https://github.com/neovim/neovim/pull/9408 , I tested this in tmux 2.7. Title stacking works. If it's not working, you need to figure out what's different about your environment.
