### ISSUE TITLE
Pascal syntax does not support // comments

### ISSUE THREAD

**Issue by jleclanche** [neovim/neovim#4065]
C-style `//` comments are valid in pascal ([ref](http://www.freepascal.org/docs-html/ref/refse2.html)). Vim syntax highlight does not support them.

**Comment by jleclanche** [comment]
`pascal.vim` hasn't been changed since 2004, by the way... I didn't bother contacting the maintainer about it.

**Comment by mhinz** [comment]
Try `:let pascal_delphi = 1 | set ft=pascal`. Does that work for you?

Otherwise you should ask for it on the `vim_dev` mailing list instead, since we try to simply take their runtime commits instead to stay as compatible as possible. (Maybe you could become the new maintainer of the Pascal syntax file!)

**Comment by jleclanche** [comment]
Yeah that worked.

**Comment by mhinz** [comment]
Cool, can this then be closed?

**Comment by jleclanche** [comment]
I'm not sure if it can be closed in the sense that it's a normal default behaviour, but I'm not a pascal dev - you'd have to ask one...

**Comment by mhinz** [comment]
Well, as I said above, it would have to be patched in Vim.
