### ISSUE TITLE
[[ in php overwrites search pattern

### ISSUE THREAD

**Issue by helbling** [neovim/neovim#4284]
runtime/ftplugin/php.vim has the lines

``` vim
exe 'nno <buffer> <silent> [[ ?' . escape(s:section, '|') . '?<CR>:nohls<CR>'
exe 'nno <buffer> <silent> ]] /' . escape(s:section, '|') . '/<CR>:nohls<CR>'
exe 'ono <buffer> <silent> [[ ?' . escape(s:section, '|') . '?<CR>:nohls<CR>'
exe 'ono <buffer> <silent> ]] /' . escape(s:section, '|') . '/<CR>:nohls<CR>'
```

which will overwrite the search buffer after typing [[ (or the others).

This could be solved similar as it is in runtime/ftplugin/python.vim:

``` vim
nnoremap <silent> <buffer> ]] :call <SID>Python_jump('/^\(class\\|def\)')<cr>
nnoremap <silent> <buffer> [[ :call <SID>Python_jump('?^\(class\\|def\)')<cr>
nnoremap <silent> <buffer> ]m :call <SID>Python_jump('/^\s*\(class\\|def\)')<cr>
nnoremap <silent> <buffer> [m :call <SID>Python_jump('?^\s*\(class\\|def\)')<cr>

if !exists('*<SID>Python_jump')
  fun! <SID>Python_jump(motion) range
      let cnt = v:count1
      let save = @/    " save last search pattern
      mark '
      while cnt > 0
      silent! exe a:motion
      let cnt = cnt - 1
      endwhile
      call histdel('/', -1)
      let @/ = save    " restore last search pattern
  endfun
endif
```

**Comment by justinmk** [comment]
This bug is in the runtime plugins (which we import from Vim). We can't afford to track every single problem with the runtime plugins in the Neovim issue tracker, because we aren't going to fork the runtime plugins in most cases (especially syntax plugins). 

Syntax plugins (e.g. for ruby/java/YAML) are maintained by the maintainer listed at the top of the plugin file. Please report to that person, or to https://github.com/vim/vim. Thanks!
