### ISSUE TITLE
deleted marks are not removed from shada

### ISSUE THREAD

**Issue by mbr42** [neovim/neovim#4288]
After I delete some marks from a file, then closing and reopening it, all previous deleted marks are still present.
Using master:
git log --pretty=format:"%h - %an, %ar : %s" -n1
f887037 - Justin M. Keyes, 23 hours ago : Merge pull request #4276 from justinmk/coverity135578%

**Comment by justinmk** [comment]
Please provide exact steps to reproduce using `nvim -u NONE`.

**Comment by mbr42** [comment]
Hi jisinmk,

to reproduce the error please do the following:
create and edit a file with nvim -u NONE filename.
set a mark with ma in command mode and save and exit
reopen file with nvim -u NONE filename
show marks with :marks
delete all marks with :delmarks!
save and quit
reopen file with nvim -u NONE filename
show marks with :marks and voila mark "a" is still present.

Thx,
mbr

**Comment by phanimahesh** [comment]
Can confirm that this is reproducible.

**Comment by justinmk** [comment]
This is by design (explained below). Note however that you _can_ achieve your goal by force-writing the shada file without reading the existing one (note the "!" bang): 

    :wshada!

Vim's `'viminfo'` behaves the same. It wouldn't make sense for Vim nor Nvim to delete marks after `:delmarks` upon exit, because there's no way to know if the marks in the existing file came from another Vim or Nvim instance. We don't annotate viminfo/shada records with anything that would identify the instance that the record came from.

**Comment by kdurant** [comment]
Has this problem been solved?

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/4295
