### ISSUE TITLE
Would it be possible to have a scroll autocmd?

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#4322]
A scroll autocmd which get triggered every time the view get scrolled would be useful for plugins that need bind the view of anthother app to neovim.

**Comment by bfredl** [comment]
I wonder if we should make it easier for plugins to monitor the ui update stream, because there already is the `ui_t->scroll` event. A UIEvent autocommand might have feedback loop issue if the autocmd triggers redraws, but for a remote plugin we  could make it as easy to subscribe to a specific ui event as it is to register an autocommand handler (if it isn't already and just need documentation)

**Comment by justinmk** [comment]
> I wonder if we should make it easier for plugins to monitor the ui update stream,

By all means, yes. But as usual I don't get the distinction of "UI events" vs "events". It's just an event. UIs are just clients with persistent connections. I suggest we move away from regarding UIs specially.

> for a remote plugin we could make it as easy to subscribe to a specific ui event as it is to register an autocommand handler

Why only remote plugins? The feedback-loop issue can be avoided with textlock and/or the typical autocmd nesting/recursion limits.

To listen to an event, the autocmd should require an _exact_ match of the event type:

    autocmd Event ui_scroll call <sid>on_scroll()

Patterns are not allowed. This should make it possible to avoid accidental performance problems.

**Comment by bfredl** [comment]
I think the difference is performance: ui updates might be clustered together and sent as a single msgpack message to the remote ui. But if you could extend that to autocommands in general...

**Comment by extr0py** [comment]
Oni is hitting this with extr0py/oni#543 - it looks like there's not an easy way to detect if there is a scroll. We can hit some of the cases if we listen to the `SCROLL` or `SET_SCROLL_REGION`, but this doesn't cover all of them. Having a `Scroll` autocmd would make this scenario easier for the external UIs.

**Comment by justinmk** [comment]
What fields should the event contain ?

**Comment by extr0py** [comment]
@justinmk - good question. I'm not sure it actually needs an argument, but if anything, the active window id would be helpful - since the scrolling is really specific to a window. 

With that, any VimL or msgpack client could then query for whatever additional information they need (in Oni's case, we'd listen for that autocmd event, and then grab some info - like the top line / bottom line of the window, in order to update the buffer scroll bar).

**Comment by justinmk** [comment]
> We can hit some of the cases if we listen to the SCROLL or SET_SCROLL_REGION, but this doesn't cover all of them

What cases are missing?

**Comment by extr0py** [comment]
It looks like there are certain cases where I'd use `zb` and then `zt` (or vice-versa), and not see the `SCROLL` or `SET_SCROLL_REGION` events (this is using NVIM v0.2.1-4-g9847be58). 

If I use `zz`, I see those scroll events coming through. I'm sorry that's not very specific or actionable - I'll see if I can get a more concrete repro and details for you. Thanks for your help!

**Comment by bfredl** [comment]
We should avoid unnecessary round-trips. It's better if the events contains the basic info most clients would need, such as the new viewport.

**Comment by ashu-22** [comment]
If is it possible then We would like to implement in which kind of tool.

**Comment by ashu-22** [comment]
If is it possible then We would like to implement in which kind of tool.

**Comment by romgrk** [comment]
Anyone is working on this? If not, any pointers where to start to implement it?
