### ISSUE TITLE
:terminal : set $TERM to something appropriate

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#4351]
I've bad experience with a new file inside the terminal buffer by command `nvim` and I would like to alias it to `nvr` command when inside terminal buffer, but I didn't figure out how to check whether the shell is running inside the terminal buffer :(

**Comment by ZyX-I** [comment]
There is no way to tell this for sure, but maybe just checking whether `$NVIM_LISTEN_ADDRESS` is defined is enough. Note that this is not going to distinguish between shells run from `:terminal` and shells run from `system()` or `:!`. Also if you open a new terminal emulator from within terminal window that emulator will inherit all environment variables. Both is mostly not a problem because `system()`/`:!` are non-interactive and terminal emulators are usually run by WM via keyboard shortuct or menu and not from shell though.

---

By the way, why your experience is bad?

**Comment by chemzqm** [comment]
@ZyX-I mostly because when I use `nvim` inside the terminal buffer, there's no color highlight, and since I bind `<esc>`  to quickly leave terminal buffer, by `tnoremap <Esc> <C-\><C-n>` , I can't leave the insert state when edit inside nvim started in terminal buffer.

**Comment by fmoralesc** [comment]
Why not just use `nvr` inside the terminal? It will redirect operations to the top-level `nvim` instance, bypassing those issues. I don't see much benefit in trying to call `nvim` as an alias for `nvr`. That said, you could probably create a shell function (not an alias, although in some shells it's the same, like in fish) that called `nvr` if `$NVIM_LISTEN_ADDRESS` is defined and `nvim` otherwise.

**Comment by chemzqm** [comment]
@fmoralesc I just don't like to think whether I'm inside direct terminal of terminal inside nvim. I tried to use `nvr` only, but I'm not satisfied with it's behaviour in common shell, it shows help when called without argument, it does nothing when there's no nvim process started, I have to manually jump to the terminal tab that contain running nvim process.
I use fish, an environment variable would be enough for me.

**Comment by ZyX-I** [comment]
@fmoralesc Fish does have aliases. Also I have never seen a shell where alias and function is the same thing, only one shell where you have aliases, but no functions (I speak about tcsh).

Main difference between an alias and a function is completion. If you create a function it is a new entity without completion (or with completion for the command with which function happens to share name if any, regardless of what function actually does). If you create an alias then when doing completion shell will *first* expand an alias and then perform completion *on the expansion*.

Thus for

```Shell
rm() {
  cp "$@"
}
alias mv='cp'
```

`rm -<Tab>` will show you things like `--dir` (which is `rm` argument, not accepted by `cp`), while `mv -<Tab>` will show you `--copy-contents` (which is `cp` argument, not accepted by `mv`).

**Comment by fmoralesc** [comment]
@ZyX-I aliases are functions in fish, see [the docs](https://fishshell.com/docs/current/commands.html#alias).

**Comment by fmoralesc** [comment]
@chemzqm Does this cover your use-case?

~~~ fish
function nvim
    if test -z $NVIM_LISTEN_ADDRESS
        /usr/bin/nvim $argv
    else
        if test -z $argv
            nvr -c new
        else
            nvr $argv
        end
    end
end
~~~

**Comment by ZyX-I** [comment]
Rechecked this: “aliases” in fish indeed break completion, as expected for functions. Yet another reason not to use fish.

**Comment by fmoralesc** [comment]
@ZyX-I functions in fish can wrap commands. For example, the `nvim` function above might be declared like this:
~~~
function -w nvim nvim
...
end
~~~

And then it would work as expected, as long as you have completion for the wrapped `nvim` set up. 

You just have to abandon the idea that it works like more classical (POSIX) shells.

**Comment by justinmk** [comment]
What if we set `TERM=nvim-vterm-256color` or something like that, for `:terminal`?

**Comment by fmoralesc** [comment]
@justinmk But wouldn't changing $TERM have side-effects for some programs? It's better to inherit it from the environment. Another variable, perhaps?

Anyway, the script I proposed works (if I understood @chemzqm use-case correctly), see https://www.youtube.com/watch?v=xMd6Iautr80

**Comment by justinmk** [comment]
NVIM_LISTEN_ADDRESS is a temporary hack, though probably can't get rid of it now.

I don't know if there is precedent for running a terminal inside a terminal (except screen/tmux). TERM has the same problems as "user agent" in web browsers: prepending `nvim-` to the existing `$TERM` might cover all cases.

It's not really "correct" to report TERM as the original term when clearly `:terminal` is _not_ the original term...

**Comment by fmoralesc** [comment]
> It's not really "correct" to report TERM as the original term when clearly :terminal is not the original term...

Yeah, but since in the tui the `:terminal` capabilities should (ideally) be the same as in the top-level terminal, I don't think we gain much by distinguishing them. In the general case, I agree; but for the TUI there is no benefit in reporting anything else.

**Comment by DarkDefender** [comment]
@fmoralesc I don't think it's that simple though... If I understand this correctly, then we have you make sure that the reported TERM matches the features in libvterm. Otherwise we will run into the same problems as if you run xterm with TERM set to rxvt.

**Comment by chemzqm** [comment]
@fmoralesc yep, just use $NVIM_LISTEN_ADDRESS would solve my problem, thanks for you tip!

**Comment by fmoralesc** [comment]
@DarkDefender That's my point! In the case of the TUI, where we are already running inside a terminal, the expectation is that the inner terminal behaves like the outer (see previous issues about the colors in `:terminal` not matching those of the outer terminal, and so on). The inner terminal should then mimic the outer one, and in this case, it doesn't make sense to me to report a different $TERM (this is the ideal behavior, of course).

If we introduced `nvim-term-256`, we should probably install a terminfo entry too. I've seen many terminal emulators that don't behave properly because they don't do this right (`st` in Arch, for example, has given me trouble because of this). But if nvim-term-256 enables, for example, italics, then it will fail in different ways if the outer terminal can't handle that.

**Comment by DarkDefender** [comment]
@fmoralesc but in this case the terminal is libvterm. Think of it as if you use a tiling WM and just have two terminals open beside each other. One is rxvt and the other xterm.

In this case neovim is running an other terminal (libvterm) and displaying the output in your current terminal. What I'm saying is that libvterm is libvterm not anything else.

**Comment by fmoralesc** [comment]
I get it ;) What I'm saying is libvterm *should* be able to mimic the outer terminal.

**Comment by ZyX-I** [comment]
> @DarkDefender That's my point! In the case of the TUI, where we are already running inside a terminal, the expectation is that the inner terminal behaves like the outer (see previous issues about the colors in :terminal not matching those of the outer terminal, and so on). The inner terminal should then mimic the outer one, and in this case, it doesn't make sense to me to report a different $TERM (this is the ideal behavior, of course).

Inner terminal, does not, cannot and will not behave like the outer one, so leaving $TERM intact is completely incorrect. Libvterm cannot know all extensions to the xterm escape sequences, there is simply no such database. More, Neovim also *must not* mimic the outer terminal, do not forget that Neovim allows detaching and attaching UIs at any point in runtime, so the fact that now “outer” terminal is konsole does not mean that a few minutes later there will be no “outer” terminal: e.g. because somebody finally implemented `:gui` from #4342.

Libvterm should simply choose one $TERM value, one set of terminal features and support this and only this, and that is all Neovim needs.

**Comment by ZyX-I** [comment]
By the way, tmux and screen have a way of passing some sequences directly to the outer terminal without interpreting them. I do not think this should be supported by `:terminal` though (because it is not guaranteed that there is a terminal to pass sequences to), but I do not remember this idea discussed.

**Comment by justinmk** [comment]
> By the way, tmux and screen have a way of passing some sequences directly to the outer terminal without interpreting them. I do not think this should be supported by :terminal though [...] but I do not remember this idea discussed.

@ZyX-I I made such a suggestion here: https://github.com/neovim/neovim/issues/4349

>  (because it is not guaranteed that there is a terminal to pass sequences to)

What if we raise an event named something like `PrintTermCode`: TUI can handle the event; GUIs can ignore it.

**Comment by ZyX-I** [comment]
@justinmk I do not see it suggested there. Unknown escape codes ≠ escaped escape codes, I would not ever suggest to forward unknown escapes because if unknown escape code contains position of some kind it is almost guaranteed to be wrong unless `:terminal` is the first window without any tabline shown.

On the other hand, Neovim-specific escaping (or, at least, same as screen: tmux requires escaping them in the way it is clear that escaping was done specifically for tmux) means that the origin probably knows what it is doing. Or, at least, the author have read documentation which tells him about the culprits and knows his responsibility.

**Comment by ticki** [comment]
I imagine that this could be achieved through an environment variable ($NVIM_IN_TERMINAL_BUFFER) telling if the session is currently in a terminal buffer. This would be set when the child process is spawned. `nvim`, when executed, will then check if this is set, and if so, it will execute a escape code and then exit. This escape code tells the `:te` buffer to open the file in that session.

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/3118

**Comment by justinmk** [comment]
`TERM=xterm-256color` in `:terminal` is unlikely to change. https://github.com/neovim/neovim/issues/3118 will address the original motivation for this issue.
