### ISSUE TITLE
windows binary not found for version 0.0,1

### ISSUE THREAD

**Issue by chantisnake** [neovim/neovim#4369]
- Neovim version: 0.0.1
- Operating system: MS windows 10
- Terminal emulator:

### Actual behaviour
on the wiki, there is a link to windows binary, I have clicked that, there is no `win64` there at all.
I have tried chocolatey, but I can only install 0.0.2, but not 0.0.1

**Comment by justinmk** [comment]
Windows support is experimental. YMMV

**Comment by equalsraf** [comment]
Cheers @chantisnake

Since it is experimental there are no tagged versions for the builds (all windows builds are based on #810, i.e. master branch+patches). So no, there is no 0.0.1 build (unless you want to manually check for the correct version that matches 0.0.1)

> I have clicked that, there is no win64 there at all.

Do you mean this link ? https://ci.appveyor.com/project/equalsraf/neovim/branch/tb-mingw

- You should see two entries, under "JOBS", click the one that says - Environment: GENERATOR=Visual Studio 14 **Win64**, DEPS_PATH=deps64.
- There should be an **Artifacts** tab with a zip link

> I have tried chocolatey, but I can only install 0.0.2, but not 0.0.1

I know there are packages on chocolatey, but I don't know who built them - https://chocolatey.org/packages?q=neovim - whoever it was :+1: it seems they are downloaded from appveyor (maybe including the job number as part of the version would be useful?).
