### ISSUE TITLE
Offline build from source

### ISSUE THREAD

**Issue by treythomas123** [neovim/neovim#4451]
I'm trying to install neovim from source without internet access (corporate secured environment).

I was able to get the github dependencies working by manually downloading and extracting them, but now I'm getting a failure for the luarocks manifest.

It'd be nice to have a download somewhere that bundles these dependencies, to make it easy to build from source without internet access. Does something like this exist?

**Comment by fwalch** [comment]
You can look at how the [PPA](http://launchpad.net/~neovim-ppa) does it (there's no internet access on the build machines): It puts the third-party sources from https://github.com/neovim/deps/tree/master/src into [deps-src](https://code.launchpad.net/~neovim-ppa/+recipe/neovim-unstable), [moves them to .deps/build/src](http://bazaar.launchpad.net/~neovim-ppa/neovim-ppa/neovim-packaging/view/head:/debian/rules), and then builds with [-DUSE_EXISTING_SRC_DIR=ON](http://bazaar.launchpad.net/~neovim-ppa/neovim-ppa/neovim-packaging/view/head:/local.mk).

**Comment by treythomas123** [comment]
That's helpful, thanks! Looks like I also need to install lua/luarocks separately, and globally install whatever lua packages neovim needs.

It'd be nice if that part could also be packaged up somehow, but this may be a rare enough use case that it's not worth setting something up. I'll leave this up to you guys on whether to close it or keep it open as a feature request.

**Comment by fwalch** [comment]
The last link of my previous comment shows flags to disable the use of Lua, as it is only required for the tests.

**Comment by wilywampa** [comment]
Is there still a way to disable Lua? Seems like the answer is no: https://github.com/neovim/neovim/blob/master/CMakeLists.txt#L439

I'm having a really hard time trying to compile Neovim offline. I was able to download the dependencies from @fwalch's link but had to edit their `Makefile`s in some cases (because e.g. the documentation is not included in that repo) and install them manually.

That's to be expected to some degree when compiling something in a restricted environment, but there are a couple problems that I couldn't find a workaround for, e.g. not being able to find the `Threads` package which is required and Lua missing the required packages.

**Comment by justinmk** [comment]
Either Lua 5.1 or Luajit is required. We'll provide pre-built "universal binaries" for linux soon (AppImage).

**Comment by BarrettLowe** [comment]
The problem is that some of these secure systems can't have any executables or binary files brought onto them so any piece of software that is needed has to be transferred as plain text and then built from source. I've just spent the past few hours trying to build neovim with a fresh distro of ubuntu in this manner and it's proven to be a huge pain - especially lua, luarocks, and the various rocks needed - mpack, lpeg, and bitop I believe. Has anyone written a script or something to save headache?

**Comment by ZyX-I** [comment]
@BarrettLowe If you use top-level `Makefile` it will download and build dependencies itself, but no separate “download” and “build” steps. I did not have any troubles with building lua and luajit myself though, but more with making Neovim use my built lua or luajit in place of system one. Luarocks is a bunch of lua scripts, it needs not be built, only placed. Other lua packages depend on luarocks being able to find a compiler, but given that you are not going to have internet, you will additionally need download them yourself and use different luarocks commands then what existing script uses.

**Comment by jamessan** [comment]
> If you use top-level `Makefile` it will download and build dependencies itself, but no separate “download” and “build” steps.

```sh
$ echo USE_BUNDLED_DEPS=OFF > local.mk
```

Now no downloading happens, just building.  Get the dependencies installed where tools expect them to be and they will automatically be detected.  Luarocks isn't needed unless you're building the dependencies through the build files in `third-party/`.

> The problem is that some of these secure systems can't have any executables or binary files brought onto them so any piece of software that is needed has to be transferred as plain text and then built from source.

They're secure systems, but they allow you to install arbitrary software as long as you can figure out how to build it on _that_ computer?  That seems rather contradictory.

You say the [appimage](https://github.com/neovim/neovim/wiki/Installing-Neovim#appimage-universal-linux-package) won't work because it's detected as a binary/executable file.  That means you can't transfer tarballs either?  Only individual files can be transferred?

I get that you're working under onerous circumstances, but I don't see how we can really help here.  There's no need to rely on our convenience functionality to download and build the dependencies for you, since that's not going to work in your environment.  Disable it and then treat the process like you would any other software you're trying to bring into this environment.

**Comment by ZyX-I** [comment]
Tarballs really contain headers and file contents verbatim. Depending on the definition of “binary” they may appear as “text” unless compressed. In any case one can always use base64, uuencode or whatever. Without somebody reviewing every “text file” such “security” is utterly useless.

@BarrettLowe Can you just build and pack Neovim (or take that appimage), base64 encode it; and then decode, unpack and install on the target? After applying base64 files are not normally recognized as binaries. There are also other less popular methods of representing binary data with ASCII.

**Comment by BarrettLowe** [comment]
Thanks for all the input. Most of the security stuff is a bunch of bureaucracy but I try to play by the rules when I can. I'll keep poking at it. Thanks again
