### ISSUE TITLE
Create a more convenient workflow to create error reports/dumps for plugins

### ISSUE THREAD

**Issue by tony** [neovim/neovim#4478]
This issue may apply to normal (n)vim use or other plugins, but for the sake of this I'll use completion. For the paste couple of years, I have been constantly perplexed by autocompletion on (n)vim.

I don't know where suggestions come from. I don't know why they sometime don't work.

If they don't work, I don't know if its the vim/neovim build or build settings, my system environment, a library not being installed or built, or being the right/wrong version, my plugin settings, etc. How do I begin to know who to file the bug with?  This process occurs over and over again.

What plugin maintainers ask for is a minimal vim configuration.  I think in practice, if bugs just happened once a year, it wouldn't be so bad. I think that ends up creating a wall since its a lot to go out of your way just to create a new config, simply to test a bug.  Imagine if you were to ask someone reporting a bug in Windows or Firefox to start with a minimal installation. It isn't practical to expect users to give decent error reports if they have to dump through hoops.

For example see: https://github.com/Shougo/deoplete.nvim/blob/master/.github/ISSUE_TEMPLATE.md

How could we give plugin maintainers better debug info without a minimal vim?

If we could create a dump of useful information for plugin maintainers, what could it include?

I think its important to have it in one `.txt` file, so you could [attach it to a GitHub issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). And of a size manageable to fit as an attachment (<25mB).
- vim/neovim info
- system info (OS, architecture, LSB release) 
- environmental variables
- client info (e.g. python, lua client, and their versions, interpreter versions)
- loaded settings/functions
- settings files
- error log (with the output of `NVIM_PYTHON_LOG_LEVEL=DEBUG` but w/o empty messages)

Does anyone have any input to make on something like this?

**Comment by justinmk** [comment]
https://github.com/tweekmonster/nvim-python-doctor might be a good start.

**Comment by tony** [comment]
@justinmk : Nice! https://github.com/tweekmonster/nvim-python-doctor is on track with what I was thinking about. Something to help troubleshooting and also be attached to on tracker issues for neovim and plugins.

If we get a best practice in place, we can get plugin maintainers to also add using the tool to their ``CONTRIBUTING.md`` for better bug reports.

**Comment by tjdevries** [comment]
@justinmk, I would like to pick this up, if no one else has started to do any work on it. My idea is shaping up to be something like this:

Create a system for people to be able to use their own `$PLUGIN/health/$PLUGIN.vim` files and easily combine the outputs.

Could also be used by authors to specify requirements of a plugin, system executable, etc. This could make it clear to users in an easily repeatable manner for them. 

We currently have a vim script / some other checkers that let us do `:CheckHealth`. However, I'm suggesting a change in the way that we restructure this. The new way would would generate a nice markdown report (or text) and provide wrapper functions for all the formatting, etc. This would create a common interface for plugin authors, future Neovim common gotchas, etc. With the wrappers, we could even create json output or something like that, as a different supported output, for easy computer parsing.

- `nvim/runtime/autoload/health.vim`: Sets up the health checker. Provides:
    - `g:enabled_doctors`: The health checkers list / dictionary that contains all the available doctors to run.
    - `g:disabled_doctors`: Option to blacklist checkers if you don't want to include them.
    - `health#check()`: Some report function that can be called. This will run all the enabled doctors, and compile the results into a nice report.
    - **Report functions** -  These will be used by people making their own `health.vim` files. Some examples could be something like the following:
        - `g:dictate()`: The harshest of recommendations. This plugin / feature will not work without it. The user must do this.
        - `g:prescribe()`: The recommended fix for a major problem.
        - `g:suggest()`: A less strict report function. Might be  a minor version of a plugin behind. Or some other small info message.
- `nvim/runtime/health/python.vim`: This is where the current `health.vim` file goes, unless there is something in there that does not relate to Python, then we could split that out.

If this seems like an interesting idea, I can create a pull and start working on it. These are just my initial thoughts about what could be done.

**Comment by justinmk** [comment]
@tjdevries Nice outline. Let's ship a first iteration before we get fancy with markdown/json. Just concatenating a list of messages is good enough; we would want to see if the idea gets traction with plugin authors before adding features.

> `$PLUGIN/health/$PLUGIN.vim`

Do you mean `$PLUGIN/autoload/$PLUGIN/health.vim`? Then `health#check()` can iterate through all `$PLUGIN#health#check()` functions, letting Vim's autoload system do the work of finding them.

`v:healthchecks` could be a dictionary of those discovered functions. Instead of a blacklist, the dict value for a given key can be set to `v:false` or something.

> Report functions

For the first iteration I suggest keeping it dead simple. Don't make plugin authors or users think about what kind of report they want. 

> nvim/runtime/health/python.vim: This is where the current health.vim file goes, unless there is something in there that does not relate to Python, then we could split that out.

We should leave the existing health.vim as it is, just one big (internally organized) blob, until we find a reason not to. For various reasons the stock runtime should not contain many separate files.

**Comment by tjdevries** [comment]
@justinmk, agreed on the simple first idea. I was just sort of shooting out some ideas we could have.

> Do you mean `$PLUGIN/autoload/$PLUGIN/health.vim`?

Yes, that is what I meant.

> `v:healthchecks` could be a dictionary of those discovered functions.

This seems like a better idea. This way we only have one object to look at, instead of two.

> Report functions

Okay, maybe we don't include different levels for the first level, but perhaps a specific command at least, it can act like echo for the first release. It just seems this would at least let anyone who does adopt the health check system to not have to modify their code too much if we add capabilities to it later. it could just be `health#record` or something like that.

> We should leave the existing health.vim as it is

Okay, sounds good to me. Maybe at some point we could just do `nvim/runtime/health/nvim.vim` and move all of the actually reporting type checks and tests there, and keep `nvim/runtime/health.vim` as the place where we set up the infrastructure.

**Comment by justinmk** [comment]
This was addressed by `:checkhealth`. #4932

In regards to the original report here, doing a full dump of env vars and other client info is risky because:

- It might contain private data
- It puts a big task on developers to dig into the user's state. We depend instead on users to minimize their state and provide a minimal test case, not the other way round.
