### ISSUE TITLE
Position of .swp file

### ISSUE THREAD

**Issue by xekoukou** [neovim/neovim#4481]
- Neovim version: 0.1.1
- Operating system: Debian
- Terminal emulator: stterm 0.4.1

Wouldn't it be better to put the.swp file in the folder that the file lies as in the original vim?
Is there a reason for such a transition?

Keeping the file locally makes sense because you can easily retrieve it. Imagine someone working on a USB stick. Then his computer crashes. All he has to do is put the USB stick to another computer and continue his work.

**Comment by ZyX-I** [comment]
@xekoukou It is the default that changed, you may still use current directory if you want. Example is not very good, it is not likely that crashing computer will force somebody move to another and not reboot (not to mention that Neovim crashing is usually more common, unless you live in a place where there are problems with electricity). This also exhausts the resources of the flash memory (though you probably will loose your stick earlier). There are reasons:

1. After computer crashes most of time I want to delete all swapfiles, not recover anything from them. I work with a single file at a time, but swap file is created for each loaded and edited at least once buffer, and number of loaded and edited buffers in a large project (like Neovim) is much greater then number of files in which I can have unsaved edits. It is easier to remove all swap files from one location, possibly recovering a single file before the removal. This also applies when Neovim crashes and not computer.
2. Slow media (e.g. remote file system) will make Neovim lag if swap files are also there. This may apply to a USB stick as well.
3. Swap files in VCS repositories need to be ignored or they will bloat the `status` output.
4. Swap files bloat `ls` output (given that you have a habit to *always* list all files, including those starting with dot).
5. Swap files may bloat archives should you use `tar … directory` and not something like `git archive`.
6. There are more tools then VCS which may need to be told to ignore the swap files: e.g. `ag` in some cases (i.e. when I do not like its choice of files to search) or `find`.

Everything here is not a problem if swap files live where they currently live.

AFAIR it was discussed somewhere in some of XDG-related threads.

**Comment by xekoukou** [comment]
In the cases you mention, what you do is that you just recover the file you want and then simply delete every .swp.

What happens if you forget to recover a file? 

As it was previously, it will pop up in your directory. You will see it and you will remember that something bad happened. As it is now, you will not see anything and you will continue programming. Then, out of a sudden, you will see that some parts of your code are different than the way you remember. So you will be forced to commit what you have in your current directory and then try to merge the changes you will find in the .swp file.

**Comment by xekoukou** [comment]
Sorry, you are right. It tells you to recover your changes, so all the above is wrong.

**Comment by lilydjwg** [comment]
ZyX-I: you are right except that you don't need to tell ag to also ignore swapfiles as ag reads .gitignore, svn ignore etc.

But they are other use cases where NeoVim's current setting will cause issues:

* After my computer crashes, I will only want to delete all swapfiles that says the original file is unmodified. I will have to recover and compare any modified files so that I won't lose any important changes. It's rare for my system to crash, so I can stand with this tedious procedure.
* On multiple-user servers, with Vim's default setting, I can be notified even when there is another user editing the file, so I can avoid conflicts.
* For USB storages, the mount point may change. One can even use different computers. For networked filesystems, or syncing folders like Dropbox, I prefer to be notified when other people are editing the files at the same time.
* For files on encrypted storages, this may leak sensitive data when one's /home isn't encrypted.
* And last, this imcompatible changes with Vim will cause different people using NeoVim and Vim working on the same server to override others' work without notification, even they are using the same account.

**Comment by ZyX-I** [comment]
> ZyX-I: you are right except that you don't need to tell ag to also ignore swapfiles as ag reads .gitignore, svn ignore etc.

Unless I told ag not to read them. Also when there is a VCS in first place. So no except, you need to tell ag to ignore swap files.

> After my computer crashes, I will only want to delete all swapfiles that says the original file is unmodified. I will have to recover and compare any modified files so that I won't lose any important changes. It's rare for my system to crash, so I can stand with this tedious procedure.

Any operation on *all* swapfiles including “check whether original file was modified and thus recovery is needed” is easier if all swapfiles are in one location.

> On multiple-user servers, with Vim's default setting, I can be notified even when there is another user editing the file, so I can avoid conflicts.

Too many ifs: if users uses Vim/Neovim, if user has not disabled swap files, if user has not put them into other location, *if user is accessing file from the same computer*. Last item is one of the most essential: I usually see one computer per user with some kind of network file system; if this is the case you will not be able to distinguish between “user is accessing file right now” and “user has quit editing without closing editor properly”. Basically this variant may only be useful for administrators configuring one computer through ssh, but if they have necessary conventions established (i.e. editing via Vim/Neovim only) it is easier to just modify settings in the system vimrc.

Also if you need to prevent parallel access to files this indicates that you need to change your workflow. And use proper tools like VCS, some of them support locks.

> For USB storages, the mount point may change. One can even use different computers. For networked filesystems, or syncing folders like Dropbox, I prefer to be notified when other people are editing the files at the same time.

For USB storages this is useless, you do not go to other PC without saving your work and unless crash was fatal you restart your work on the same PC in case of crash. About network FS I said above.

Also note that both Vim and Neovim are single-threaded. And writes to swap file are blocking. So network file systems are not the good place to place swap files, this may work fine only because of the system FS cache between Vim and remote.

> And last, this imcompatible changes with Vim will cause different people using NeoVim and Vim working on the same server to override others' work without notification, even they are using the same account.

I said regarding this situation above. You must not rely on swap files to prevent this kind of problem, I am mostly using Vim and you still would not see me editing this file because I have a similar setting to the Neovim default.

---

I see the only valid case in the list and it is rare. Three out of your five counter-examples are mostly a repetition. Current Vim behaviour causes more problems then it solves.

**Comment by justinmk** [comment]
> On multiple-user servers, with Vim's default setting, I can be notified even when there is another user editing the file, so I can avoid conflicts.

*If* that user didn't change the default, which many many users *do*. 

The default saves the *vast* majority of users from turning off what is normally a confusing annoyance. It is not a good trade-off to make the default serve uncommon cases.

**Comment by lilydjwg** [comment]
I'm not relying on swapfiles to prevent parallel access to files. It is there so that most of time I don't need to use alternative (also unreliable) methods. Not all people have good, solid workflows, and I have to stand with that.

Most users accessing servers don't change the default (of course they won't be using NeoVim now). The ones who do will try to change their workflow instead.

Anyway, since NeoVim is not Vim, let there be different behaviours. I just shouldn't expect them to behave compatibly.

**Comment by xiumingzhang** [comment]
@ZyX-I  You made a point. Thanks for explaining.

To change the default directory for .swp files, I presume I need to do something like `set backupdir=/foo/bar`?

What should `/foo/bar` be if I want it to be the same directory where original file lies?

**Comment by jamessan** [comment]
> What should /foo/bar be if I want it to be the same directory where original file lies?

Exactly what it says in `:help 'directory'`:

```
	- A directory "." means to put the swap file in the same directory as
	  the edited file.  On Unix, a dot is prepended to the file name, so
	  it doesn't show in a directory listing.  On MS-Windows the "hidden"
	  attribute is set and a dot prepended if possible.
```
