### ISSUE TITLE
Allow z= to correct spelling even with :set nospell

### ISSUE THREAD

**Issue by ChrisPenner** [neovim/neovim#4495]
This is a usability improvement request. I'd love to submit a patch for this when I have time, but I figure I'd get some feedback on the idea to see if people are in favour before implementing it.

The basic idea is that when I'm in a buffer and I mis-spell a word, I'd love to type `z=` to correct it, but oftentimes I'll have spell checking turned off (sometimes when doing technical writing all of the highlighted 'errors' get annoying). When spell check is turned off, typing `z=` just shouts an error at me rather than doing what I want. In my opinion the 'right thing' would be to perform the spelling correction anyways, since that's clearly what I intended by invoking the spell correct command. I suggest removing the error and proceeding with the spelling correction regardless of whether spell-check is enabled.

Note that this is technically a 'breaking change' but I'd be sincerely very surprised if anyone is depending on this behaviour for anything.

 If this is agreed upon I'll take a look at submitting a PR for it. Cheers!
### Actual behaviour

When typing `z=` with `:set nospell` we get the error: `E756: Spell Checking is not enabled`
### Expected behaviour

The same as running z= when spell checking IS enabled.
### Steps to reproduce

`:set nospell` Then type `z=` with the cursor on any word.

**Comment by fmoralesc** [comment]
Why wouldn't this argument apply to all the functionality that behaves this way? For example, to `<C-x><C-s>` (complete spelling suggestions) and so on? If it did, the `set spell` would be reduced to having to deal with the highlighting of spelling mistakes only.

**Comment by ChrisPenner** [comment]
Hrmm, good point. Upon reading up on `:h spell-remarks` it seems that the reason for the current behaviour is that when `:set nospell` is set the spell-check files aren't even loaded in memory (and thus spelling functionality is unavailable), which could still be a good behaviour to maintain.

For instance `<c-x><c-s>` and things like `]s` would still require all the spell-checking work to be done (potentially slowing things down on some machines, though likely negligible on a modern machine). For this reason they probably should just raise errors when `:set nospell` is set.

For this reason I suggest a new setting: `:set spellhl` and `:set nospellhl` which would allow the user to still enable/disable spell-check as desired, but would also have the option to leave spell-checking enabled and only disable the highlighting of errors. In this case `]s`, `<c-x><c-s>` and `z=` would all still work provided `:set spell` was on, but the highlighting could be hidden with `:set nospellhl`.

How does that sound?

**Comment by fmoralesc** [comment]
I like that better, but I think that for compatibility reasons, `set spell` should probably reset the `nospellhl` option.

The defaults should then be:
- `nospell` globally.
- `spellhl` globally. 
- `set nospellhl`/`spellhl` shouldn't affect the value of `'spell'`. 
- `set nospell` shouldn't affect the value of `'spellhl'`. 
- `set spell` should set `'spellhl'`.

**Comment by philix** [comment]
@ChrisPenner even though I hate adding more settings to Vim, this option makes some sense. I would call it `[no]hlspell` to be consistent with `[no]hlsearch`.

> set spell should set 'spellhl'.

If you set `nohlsearch`, searching for something doesn't activate `hlsearch`.

Spelling is different in that `set spell` already is expected to highlight all the spelling mistakes, but I think setting `hlspell` when `spell` is set is much more confusing to the user.

Let's expect the user of `nohlspell` knows that `spell` doesn't necessarily highlight the spelling mistakes.

**Comment by fmoralesc** [comment]
@philix As I see it, there's two reasons to make `set spell` set `hlspell`: 

1. Backwards compatibility. The expected behavior of `set spell` is to enable the spelling feature and highlight errors. With the proposed behavior the `hlspell` option doesn't alter this usage at all (and can still handle @ChrisPenner's use-cases properly, because setting `hlspell` doesn't alter the value of `spell`).
2. Status tracking. The user might not know that spell is enabled and where it was. So I think a way to reset the whole thing is convenient to have.

The `hlsearch` behavior is not necessarily a good analogue, because instead of a subsystem being enabled, it depends on the `/` register being set. The analogue of `set nospell` in that case is `let @/=''`, which I find far from intuitive.

**Comment by justinmk** [comment]
This can be done trivially with a mapping:

    :nn z= :set spell<CR>z=

The fact the `'spell'` is set after invoking that mapping, is a feature, since you may want to check other misspellings in the area before invoking `cos` (from [unimpaired.vim](https://github.com/tpope/vim-unimpaired)) to optionally disable spelling thereafter.

I could see this being a "default mapping" possibly, but I don't see a new option justified...

**Comment by justinmk** [comment]
Also, proposed `hlspell` option is problematic because it incurs the performance cost of spellcheck without actually using spellcheck except at specific times. Maybe someone can explain why the mapping I provided above is less than ideal.
