### ISSUE TITLE
Functional API for autocommands

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#4521]
Based on @tarruda's idea here about making functional API for listening to RPC events,

> allow vimscript to register listeners for msgpack-rpc calls that are not handled by C:
> 
> ``` viml
> function! s:Subscribe()
>   ...
> endfunction
> function! s:Unsubscribe()
>   ...
> endfunction
> call rpcregister(0, 'subscribe', 's:Subscribe')
> call rpcregister(0, 'subscribe', 's:Unsubscribe')
> ```
> 
> rpcregister could be used to register a handler to a specific channel number or to all channels(0)

What about offering an alternative API for `autocmd`s similar to the functional approach in the `rpcregister` idea above? For example,

``` viml
function handleWindowFocus()
  ...
endfunction

" then something like
call autoCmd('WinEnter', '*', function('handleWindowFocus'))
```

I know that's not incredibly far off from the command form, but it could be nice for someone coming from JavaScript. :D

I wish we didn't need the `function()` call to get the function reference. Is that possible? So,

``` viml
call autoCmd('WinEnter', '*', handleWindowFocus)
```

**Comment by trusktr** [comment]
Does `neovim-client` have things like `nvim.autoCmd(...)`? Would be cool to have!

**Comment by ZyX-I** [comment]
> I wish we didn't need the function() call to get the function reference. Is that possible?

Not at all. `foo()` uses function scope, `foo` uses variables. Vim code tries\* to make it impossible to have name conflicts between variables and function references (in first place because Vim code will prefer variables over functions, so putting a funcref in e.g. `g:input` will replace `input()` function in mappings with whatever is in the funcref), but it is always possible to have variable with the same name as a function as long as this variable does not contain a funcref.

`vim_*_autocmd` API (`*` = create, get) would be nice to have, there are plans to express all Ex commands functionality through API functions only. There was also an idea that it would be nice to provide direct access to Neovim API using `api_…` function set, so this issue will probably eventually be automatically resolved.

Documentation on API functions is available, you just need to see the documentation on src/nvim/api/*.c files (there is web version somewhere).

\* Not all hacks which break this were fixed: e.g. it is possible to use `vim.vars['input'] = vim.Function('string')`.

**Comment by trusktr** [comment]
Wow, it's so complicated. Thanks for sharing!

**Comment by gpanders** [comment]
Is this addressed by https://github.com/neovim/neovim/pull/14661? At least that provides this functionality in Lua.

**Comment by clason** [comment]
I think this is specifically for the remote/Neovim API (`nvim_*`)?
