### ISSUE TITLE
Feature request: allow arbitrary integer values for -nargs

### ISSUE THREAD

**Issue by nfischer** [neovim/neovim#4531]
It would be nice to be able to expand upon the allowed values for `-nargs` (see `:h command-nargs`).

I've often wanted a way to use `nargs` to do arity checks on my commands. If I have a command that takes exactly 2 arguments, it would be nice (and very intuitive) to be able to use `-nargs=2` or `-nargs=3` in the command declaration. Supplying any fewer or any more would be an error (similar to how if you use `-nargs=1` and don't pass any arguments`).

Unfortunately, the behavior of `-nargs=1` is very nonintuitive, since this allows multiple words, which are then bundled into one argument (preserving spaces). Nonetheless, I think other integers should behave in a more reasonable way (ex. if `-nargs=2` is used, then using either 1 or 3 arguments is an error).

Not sure if this is something that has already been discussed (I couldn't find any issues discussing it). But I figured this would be an extension worth bringing up.

**Comment by ZyX-I** [comment]
I do not see much sense in this: current `-nargs` values exist because they change parsing behaviour (like that thing with `-nargs=1`), `-nargs=2` will not do this compared to `-nargs=+`, it will just do additional validation. Which is not very useful because there are not much cases where you care about *only* number of arguments and not about argument values. It is also not much useful because most used cases (no, exactly one, any, one or more, one or no) were already covered. And it is not much useful because if you write command like

    function Foo(a, b)
    endfunction
    command -nargs=+ Foo :call Foo(<f-args>)

you will have number of arguments validation right away.

---

As a side note I think it would be good to provide some DSL for checking arguments: e.g. like the [FWC](http://vimcommunity.bitbucket.org/doc/FWC.txt.html) I have: thoroughly designed language will allow you to transform into a usable form, complete and validate command arguments with a few-liner script in place of lots of checks like `if !filereadable(arg1) | throw 'arg1 must be readable' | elseif …`. At least, this is much cleaner than `-complete=file` doing glob expansion and sucessive validation despite that it is `-complete`. (E.g. `command -nargs=1 -complete=file List :echo [<f-args>]` with `List foo/*` with `foo/a` and `foo/b` in filesystem will complain about too many arguments without running anything, even if my intention was to e.g. pass `foo/*` to `git` (which can perform glob expansions on its own) untouched.)

**Comment by justinmk** [comment]
> the behavior of -nargs=1 is very nonintuitive, since this allows multiple words, which are then bundled into one argument (preserving spaces)

How else would `:command` support treating user input as a single argument?

> Nonetheless, I think other integers should behave in a more reasonable way (ex. if -nargs=2 is used, then using either 1 or 3 arguments is an error

It will be inconsistent if `-nargs=N` behaves differently for N=1 than N=2.

Why not specify `-nargs=1` and then split on whitespace? It's a one-liner:

```vim
function! Baz(s)
  if 3 != len(split(a:s))|echom "invalid args"|return|endif
endfunction
command! -nargs=1 Foo call Baz(<q-args>)
```

**Comment by ZyX-I** [comment]
Actually there is a way to make this consistent: `-nargs=2` will treat `a1 a2 a3` as `['a1', 'a2 a3']`: whitespaces end first N-1 arguments, last argument consumes the rest. But I would find this behaviour rather confusing for the user and rarely needed.

**Comment by ZyX-I** [comment]
And, of course, anything can be emulated on top of `1` and `?`.

**Comment by nfischer** [comment]
Thanks for the quick reply!

> ```
> function Foo(a, b)
> endfunction
> command -nargs=+ Foo :call Foo(<f-args>)
> ```

I agree, this method is as concise as it could get, and provides the same arity check. It's probably the cleanest solution available. The only issue is that this is perhaps non-obvious to most programmers, which is counter productive (even @justinmk had a different solution at first). Maybe that trick could make its way into the docs for `-nargs` in case someone is looking for a way to specify an arity of some other number? Just a thought, since this is one place where the vimscript language is noticeably awkard, IMO. I could write a one liner in a PR against the help file if you think it's worth pursuing.

**Comment by justinmk** [comment]
> I could write a one liner in a PR against the help file if you think it's worth pursuing.

:+1:
