### ISSUE TITLE
Moving the &#%$&^%@ cursor back on exit of Insert mode

### ISSUE THREAD

**Issue by thegranddesign** [neovim/neovim#4542]
I'm sure that this had some sort of reasoning back when it was first put it, however I am annoyed by this literally dozens of times a day.  So I'm posting here to:

a) see if we can fix this in Neovim (or at least make it an option)
b) see if anyone knows why this may have been introduced

The behavior is thus:

* Type some text
* Exit insert mode
* Note cursor position
* Enter insert mode
* Exit insert mode
* Note cursor position

Effectively entering and exiting insert mode "walks" the cursor back one character each time.  Presumably entering and exiting insert mode should be an idempotent operation.

This is a tiny thing, but a huge nag that my muscle memory has gotten used to, but it shouldn't've had to.

**Comment by traycerb** [comment]
i think this has been discussed in multiple times over Vim's lifetime and it has to do with what the cursor in normal vs insert mode represents (on a char vs between one).  a fix is hard to define and thus implement, but if you mix 'a' into your usage, you'll get most of what you want.

**Comment by thegranddesign** [comment]
Thanks @traycerb! Yeah so using "a" has the same problem but just going the other way. 😂

I see no reason why Neovim couldn't just know what mode it's exiting from and put the cursor back such that entering the same mode again would allow the user to begin typing where they left off. The fact that if I type "hello", exit insert mode, enter insert, and type "hello" the resulting string is *not* `hellohello` blows my mind.

**Comment by justinmk** [comment]
It's been discussed before. No, I'm not going to search for the issue.

**Comment by thegranddesign** [comment]
@justinmk apologies.  I didn't mean to irritate you.  I did look for an issue, but there are a lot of them in regards to cursor problems.  I looked again and found a couple discussing this as well as a possible workaround.

Thank you for all your work on Neovim.

**Comment by justinmk** [comment]
> The fact that if I type "hello", exit insert mode, enter insert, and type "hello" the resulting string is not hellohello blows my mind.
 
@thegranddesign  Resulting string is "hellohello" if you use `a` to enter insert-mode. I don't get what you mean by:

> "a" has the same problem but just going the other way

The cursor won't "walk" if you use `a<esc>a<esc>...`.

Even if an option were added to address this request, it would break plugins. Using `a` or some one-liner autocmds as mentioned in other discussions gets close to a solution, and doesn't break plugins.

But this issue is really cosmetic, in my opinion.

**Comment by thegranddesign** [comment]
@justinmk I guess my point is that entering and exiting insert mode should be idempotent with regards to cursor position no matter how you do it.

You're right, I'm not sure what I was doing but `a` behaves correctly, so why can't `i` do the same thing?  Yes, if this gets fixed it will break plugins, but vim already has a method for now breaking plugins if a user makes a custom keymapping.  Couldn't `noremap` (which is the proper way to handle keystrokes in plugins) still perform the broken way?

Right now, if I fix `i` by doing something like

```
inoremap <silent> <esc> <esc>`^
```

then that breaks `a` by causing it to walk forward.

**Comment by bfredl** [comment]
A "fix" of sorts is to use a gui with cursor shape (such as a terminal that supports `$NVIM_TUI_ENABLE_CURSOR_SHAPE`). This makes it evident that one should think the cursor as being "between" two chars in insert mode while "on" a single char in normal mode as @traycerb noted, so no matter what happens (or what could be changed) the cursor has to "move". (When in doubt I use "a" because then "." most often does what I would expect it to do, but that is of course personal preference)
