### ISSUE TITLE
windows install not working with VC++ 2015 Runtime still failing

### ISSUE THREAD

**Issue by fobbyal** [neovim/neovim#4580]
I am still getting the **vcruntime140d.dll** message on windows 7. I installed the VC++ 2015 distribution from the following link. 
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by equalsraf** [comment]
Cheers @fobbyal 

If its complaining about `vcruntime140d.dll` then the build is wrong and installing the redistributables wont work. Were you using a recent build?

**Comment by equalsraf** [comment]
Try this one and see if it works https://ci.appveyor.com/project/equalsraf/neovim/branch/tb-mingw/job/ne63mp4j6jbjefk6/artifacts

**Comment by fobbyal** [comment]
yes i was using the latest green build.. i'll give a try and report back

**Comment by fobbyal** [comment]
That was actually the latest green build.. .I'll try to go down the history and see if i can find one that works. or there is something wrong with my windows?

**Comment by fobbyal** [comment]
I've tried 741,744,746 and 749 all of them complained about VCRUNTIME140.dll is missing from the computer. Not sure how to proceed.

**Comment by equalsraf** [comment]
Need some clarification. Notice the difference in the dll name - in the first message you said

> I am still getting the vcruntime140d.dll message

but the last one its

> complained about VCRUNTIME140.dll is missing from the

If its VCRUNTIME140.dll (no **d**) it should be fixed by installing the redistributables, it its VCRUNTIME140**d**.dll then its a problem with the build.

Did you install the redistributables for x86_64 or x86? Each job has two builds and the first one needs x86_64.

**Comment by fobbyal** [comment]
I did download both 64 and 86 vision of the vs2015 c++ distro and was trying with both. I had vs2013 previously installed. does that matter? I'm not on my computer, I will try again later tonight. Thanks again.

**Comment by fobbyal** [comment]
I am happy to report that i got it installed.
However, the lastest working build is **658**.
All compiled binary after that are linked to the D version of VCRUNTIME140d.dll upto **749**

Here is a link to the 658. If anyone runs to the same issue
https://ci.appveyor.com/project/equalsraf/neovim/build/658/job/notqv6akq02x45hw/artifacts

The latest build is 760 at the moment. I am sure this will be corrected soon. so If anyone is trying to install neovim you try the latest build after 760 before tyring with 658.

@equalsraf Thanks for your help again.

**Comment by equalsraf** [comment]
This is a bit of mystery the MSVC builds from appveyor are x86_64 builds. But even with the redistributables installed vcruntime140.dll is not in %PATH% (only the 32 bit version is). I think the 64 bit DLL is in c:\windows\syswow64 (but again this folder is not in the PATH).

For some some reason in my machine this all works, but this not comparable since I have VS2015 installed anyway. For now you can also:
- use the MinGW builds
- maybe try to play with the %PATH% and see if that helps

**Comment by fobbyal** [comment]
Sure. I'll give that a try.. since loading my _vimrc crashed neovim :(..  I'll try to find out which plugin is the culprit and report back. I might just bite the bullet and install Ubuntu via virtual box.
