### ISSUE TITLE
Remove char_u, long_u, short_u

### ISSUE THREAD

**Issue by tarruda** [neovim/neovim#459]
We should replace most occurrences of  `char_u` by `uint8_t`(where only characters are used it's ok to use plain `char`) and use standard C99 fixed-size types such as `uint16_t`/`uint_64t` instead of `long_u`/`short_u`

# Wiki: https://github.com/neovim/neovim/wiki/Integer-types-refactoring-guidelines#char_u

**Comment by mikeyjk** [comment]
"also C99 true/false instead of TRUE/FALSE"

Just a straight string replace?

**Comment by philix** [comment]
@mikeyjk no, the variable types should be changed from `int` to `bool`

**Comment by dundargoc** [comment]
I interpret that there are two remaining items that need to be resolved. Please correct me if I'm wrong.

- [ ] Replace all instances of char_u with either 
- char if it's meant to be used as a character or
- uint8_t if it's meant to be used as an integer

- [ ] (OPTIONAL) Replace macros TRUE/FALSE with C99 true/false. This wasn't originally mentioned but seems to be in the same category of change.

I'd like to start working on item number two (replace TRUE/FALSE with true/false) since it seems easier. Let me know if this is a change that isn't wanted. I'll create a [WIP] pull request with small changes to gauge intereset.
