### ISSUE TITLE
feature request: hl-IncSearch / hl-Search alternating during normal searches

### ISSUE THREAD

**Issue by atweiden** [neovim/neovim#4600]
With `hl-IncSearch` and `hl-Search` highlight groups set to alternate colors, during a search & replace, Neovim helpfully highlights the current match to replace with `hl-IncSearch`, as in this image:

![hl-IncSearch](https://i.imgur.com/bHSZ9kS.png)

This feature request is in regards to normal searching, where the default behavior is to not alternate between `hl-IncSearch` and `hl-Search`. I think the default should be customizable, so that users can get consistent behavior with normal searching and search & replace.

So far I've found [SearchParty](https://github.com/dahu/SearchParty) provides this feature, but the plugin is quite large.

If it is better to not adjust behavior of hl-IncSearch, then how about an `hl-CurSearch` so that users can declare this as the wanted behavior?

**Comment by justinmk** [comment]
> during a search & replace, Neovim helpfully highlights the current match to replace with hl-IncSearch

What exact steps do you mean? `cgn` or `:%s`?

> how about an hl-CurSearch so that users can declare this as the wanted behavior?

Seems fine but the request is ambiguous to me. Can you be more specific about the specific conditions for showing this highlight?

**Comment by atweiden** [comment]
By search & replace, I meant `:%s`.

> Can you be more specific about the specific conditions for showing this highlight?

In my example, the current match would turn red upon jumping to it with `n` or `N` (`hl-IncSearch` or `hl-CurSearch`), while other matches would be in blue (`hl-Search`).

**Comment by noahfrederick** [comment]
See also https://github.com/pgdouyon/vim-evanesco.

**Comment by atweiden** [comment]
Thanks for the recommendation.

The reason I bring this issue up is my terminal's (URxvt) distraction-free, thin underline cursor becomes nearly invisible during searches. In the absence of triggering hl-IncSearch on `N` / `n`, I frequently lose my place visually in the file. I'm blind to where my cursor is when there are multiple search matches on the same line.

I may be biased, but to me having this feature is critical. It's critical enough that I begrudgingly use plugins that remap vital keys (e.g. `/`, `?`, `n`, `N`) to achieve the result I want. What grates on me is that this highlighting behavior is Vim's default action during `:%s` search & replace operations.

It really feels like this should be available for customizing via a simple highlighting group or equivalent.

**Comment by noahfrederick** [comment]
@atweiden I agree that adding a feature like this is worthwhile (although evanesco.vim satisfies my need well enough). There are a couple benefits to not relying on a plugin here, including avoiding relatively intrusive maps and autocommands.

Rather I think @justinmk is prodding you to actually define the behavior in specific terms. It's not totally obvious how it should work, since it's not identical to the `:s///c` highlighting case where you don't have a cursor. For example, what *is* the current match? When should the special highlight be cleared?

I think evanesco.vim's policies are sound:

- Apply the IncSearch highlight to the match under the cursor after `/`, `?`, `n`, `N`, `*`, `#`, `g*`, `g#`, `gd`, and `gD`.
- Clear the special IncSearch highlight from the match on `CursorMoved` and `InsertEnter` events.

Then we need to define how the feature should interact with `:set [no]hlsearch` and `:nohlsearch`. And there are likely more details to work out beyond that.

**Comment by certik** [comment]
Where should this be implemented in the source code?

I switched to neovim from vim (so that `FocusLost` just works in `gnome-terminal` in Ubuntu 18.04, and I can autosave on it, and not need to install complicated plugins), but I noticed that I can't tell the current search term. So I just `set nohlsearch` for now, and that works. But it would be nice to do search highlighting with the current term as described in this issue.

**Comment by justinmk** [comment]
@certik there is no difference between nvim and vim for this particular issue. So your comment is confusing. Always mention exact Nvim version also.

**Comment by justinmk** [comment]
BTW, why can't this be done with a simple mapping?

**Comment by certik** [comment]
@justinmk how would you do it with a simple mapping? I only know how to do it this way:

https://github.com/pgdouyon/vim-evanesco/blob/48cd4a35ca4a349e7597081f9948f13c7e6e96cd/autoload/evanesco.vim
https://github.com/pgdouyon/vim-evanesco/blob/48cd4a35ca4a349e7597081f9948f13c7e6e96cd/plugin/evanesco.vim

Which is 382 total lines, that seems like a lot. If instead there was a simple mapping to do that, then that would be a solution.

I am using nvim 0.4.2. Yes, there is no difference between nvim and vim regarding this issue. The point I was trying to make is that I can get vim to do almost anything I want with plugins. For example, to get the `FocusLost` working, here is how it can be done with vim:

https://github.com/jacknagel/dotfiles/blob/3bc67e74faffaf946131a487225e27e158738b4b/vim/plugin/terminator.vim

But it might have some side effects, it's a plugin that I now have to install on all computers, etc. With nvim, this just works, all I have to do is to put this line in my `init.vim`:
```
au FocusLost * update
```
Also my `init.vim` is simpler than `.vimrc`, because the nvim defaults are better.

So that's why I think nvim should support some simple way to highlight the current search, not using a complicated plugin. That it would be in the spirit of nvim, as "Strong defaults" (per https://neovim.io/), as well as "Works the same everywhere: one build-type, one command". Because if you have to install plugins, it does not actually work the same everywhere.


Anyway, I would be happy to help implement it. I assume this would be done in https://github.com/neovim/neovim/blob/d9032308fbfd90eb71266bfe6d9a11930045f745/src/nvim/search.c, where we need to use a different (user configurable) color for the current highlight.

It looks like there is a `no_hlsearch`, and if it is false, things will get drawn in color. The drawing is done (scheduled) by `redraw_all_later(SOME_VALID)` (in `screen.c`). I noticed there are relevant functions in `screen.c`: `start_search_hl`, `end_search_hl`, `init_search_hl`, `prepare_search_hl`, `next_search_hl`, `next_search_hl_pos`. But I haven't yet figured out where the color is actually drawn, so that it can be extended to draw a different color for the current match.

If anyone is familiar with the source code, am I on the right track?

**Comment by certik** [comment]
Here is a start, this patch:
```diff
diff --git a/src/nvim/highlight_defs.h b/src/nvim/highlight_defs.h
index f9c2c03fc..222358009 100644
--- a/src/nvim/highlight_defs.h
+++ b/src/nvim/highlight_defs.h
@@ -54,6 +54,7 @@ typedef enum {
   , HLF_E           // error messages
   , HLF_I           // incremental search
   , HLF_L           // last search string
+  , HLF_CS          // current search string
   , HLF_M           // "--More--" message
   , HLF_CM          // Mode (e.g., "-- INSERT --")
   , HLF_N           // line number for ":number" and ":#" commands
@@ -109,6 +110,7 @@ EXTERN const char *hlf_names[] INIT(= {
   [HLF_I] = "IncSearch",
   [HLF_L] = "Search",
   [HLF_M] = "MoreMsg",
+  [HLF_CS] = "SearchCurrent",
   [HLF_CM] = "ModeMsg",
   [HLF_N] = "LineNr",
   [HLF_CLN] = "CursorLineNr",
diff --git a/src/nvim/screen.c b/src/nvim/screen.c
index 17a91f69d..0a1bef8f6 100644
--- a/src/nvim/screen.c
+++ b/src/nvim/screen.c
@@ -5604,7 +5604,8 @@ static void init_search_hl(win_T *wp)
   search_hl.buf = wp->w_buffer;
   search_hl.lnum = 0;
   search_hl.first_lnum = 0;
-  search_hl.attr = win_hl_attr(wp, HLF_L);
+  //search_hl.attr = win_hl_attr(wp, HLF_L);
+  search_hl.attr = win_hl_attr(wp, HLF_CS);
 
   // time limit is set at the toplevel, for all windows
 }
```
Allows one to specify this in `init.vim`:
```vim
hi Search ctermbg=blue ctermfg=red
hi SearchCurrent ctermbg=green ctermfg=red
```
And the `SearchCurrent` will not be used instead of `Search`.

Now the next step is to only use `SearchCurrent` for the current search highlight, but `Search` for the rest.

**Comment by certik** [comment]
So I posted a prototype at https://github.com/neovim/neovim/pull/11082. Here is how it looks like:

![nvim_search_current](https://user-images.githubusercontent.com/20568/65457967-ee900a80-de09-11e9-9496-e5d785e92200.png)

So I think it does what we want. Now we just need to iron out all the bugs. The main one (as indicated in the PR) is that when "n" or "N" is pressed to go to the next match, the colors do not get updated. One has to do another `/int<CR>` to get the colors updated at a new position.

Does anyone know how to fix that?

Judging from the amount of lines that had to be modified to get this working, this seems to be a much simpler approach than `evanesco.vim` (see above).

**Comment by justinmk** [comment]
`CurSearch` highlight was implemented. https://github.com/neovim/neovim/pull/18081
