### ISSUE TITLE
tab-local directory: coverity defects

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#4641]
@HiPhish if you have some time could you check these defects found by coverity (keep in mind they could be false-positives)?

```
New defect(s) Reported-by: Coverity Scan
Showing 2 of 2 defect(s)

** CID 144390:  Null pointer dereferences  (FORWARD_NULL)
/src/nvim/eval.c: 10829 in f_haslocaldir()

__________________________________________________
*** CID 144390:  Null pointer dereferences  (FORWARD_NULL)
/src/nvim/eval.c: 10829 in f_haslocaldir()
10823
10824       switch (scope) {
10825         case kCdScopeWindow:
10826           rettv->vval.v_number = win->w_localdir ? 1 : 0;
10827           break;
10828         case kCdScopeTab:
>>>     CID 144390:  Null pointer dereferences  (FORWARD_NULL)
>>>     Dereferencing null pointer "tp".
10829           rettv->vval.v_number = tp->localdir ? 1 : 0;
10830           break;
10831         case kCdScopeGlobal:
10832           assert(0);
10833           break;
10834       }

** CID 144389:  Null pointer dereferences  (FORWARD_NULL)
/src/nvim/eval.c: 9896 in f_getcwd()


__________________________________________________
*** CID 144389:  Null pointer dereferences  (FORWARD_NULL)
/src/nvim/eval.c: 9896 in f_getcwd()
9890         case kCdScopeWindow:
9891           from = win->w_localdir;
9892           if (from) {
9893             break;
9894           }
9895         case kCdScopeTab:  // FALLTHROUGH
>>>     CID 144389:  Null pointer dereferences  (FORWARD_NULL)
>>>     Dereferencing null pointer "tp".
9896           from = tp->localdir;
9897           if (from) {
9898             break;
9899           }
9900         case kCdScopeGlobal:  // FALLTHROUGH
9901           // The `globaldir` variable is not always set.
```

**Comment by HiPhish** [comment]
I got the first one. Calling `haslocaldir(-1, -1)` causes the `NULL` dereference. Having all scopes set to `-1` should either throw an error or return a default value. I'd go with the default value, we are asking "has the scope beyond scopes a local directory" and since that scope would be global the answer has to be "no". The only way that `tp` can become `NULL` is if the tab scope is `-1` or if the global variable `curtab` is `NULL`
```
tabpage_T *tp  = curtab;  // The tabpage to look at.
// The only other assignment later...
if (scope_number[kCdScopeTab] == -1) {
  tp = NULL;
} else if (scope_number[kCdScopeTab] > 0) {
```

**Comment by HiPhish** [comment]
The second one is the same, but it doesn't crash. If the tab number is -1 the scope is global, which in this case returns the global path printed by `getcwd(-1, -1)`. That would be a false positive then.

Even if I handle the case `haslocaldir(-1, -1)` I'm not sure that this would make the reported error go away, because even now `tp` cannot be null and `scope` be `kCdScopeTab` at the same time, so we will never run into that `NULL` dereference. Unless of course `curtab` is `NULL`, but that should not happen anyway, right?

What should I do now?

**Comment by justinmk** [comment]
> Having all scopes set to -1 should either throw an error or return a default value. I'd go with the default value, we are asking "has the scope beyond scopes a local directory"

:+1: Default value sounds good.

> I'm not sure that this would make the reported error go away, because even now tp cannot be null and scope be kCdScopeTab at the same time, so we will never run into that NULL dereference. 

If there's no better way to check or respond to the conditions, `assert(tp != NULL)` will satisfy coverity.

**Comment by onemanstartup** [comment]
Shouldn't it be closed if fix was merged?
