### ISSUE TITLE
:terminal colors do not match colors defined by host terminal emulator

### ISSUE THREAD

**Issue by jfelchner** [neovim/neovim#4696]
- Neovim version: v0.1.3-366-ga9e0d73
- Vim behaves differently? Vim version: N/A
- Operating system/version: OSX 10.11.4
- Terminal name/version: iTerm2
- `$TERM`: screen-256color

It appears as though, _somehow_ nvim is bypassing the color mapping that one defines in your emulator like iTerm and is instead using the standard default color mappings.  I'm not sure why it would be doing this considering the ANSI codes should be processed ultimately by the emulator, nonetheless it's happening.
### Actual behaviour (when run in terminal inside nvim)

![image](https://cloud.githubusercontent.com/assets/285582/14965916/870b18ba-1075-11e6-9787-2327bd43a0c3.png)
### Expected behaviour (when run in terminal outside of nvim)

![image](https://cloud.githubusercontent.com/assets/285582/14965925/a038abae-1075-11e6-8af7-e94ec3d3376b.png)

FWIW, I have truecolor enabled.

**Comment by justinmk** [comment]
I have a hard time explaining the behavior, but there is good reason for it, and it is discussed here: https://github.com/neovim/neovim/pull/4274#discussion_r53781733

Since I don't fiddle with my terminal settings I pretty much don't fully grok all the knobs being tweaked here, but if someone could write a succinct FAQ that we could add to the help, to address future questions about this, it would be greatly appreciated.

**Comment by jfelchner** [comment]
@justinmk Thank you!

@DarkDefender Ok, so I read that comment (as well as quite a few others).  Am I to assume that in truecolor mode, it's outputting (effectively `255,0,0`) instead of `\e[22;31m`?  And if that's the case, nothing in that issue made it clear to me why neovim's terminal behaves differently than every other terminal emulator out there.  Can you shed some light for me please?

**Comment by jfelchner** [comment]
Also, I didn't see the proper format for setting those values:

```vim
let g:terminal_color_0 = ?
```

**Comment by wsdjeg** [comment]
@jfelchner
I can get same colors in neovim with termite.and I will add a tip in my dotfiles issue.

**Comment by jfelchner** [comment]
@wsdjeg 👍🏻 Please let me know when it's done. I'd love to see a good solution. 😊

**Comment by ZyX-I** [comment]
I once wrote a script which gets hex codes for all 256 or 88 colors. Requires imagemagick, (Neo)Vim, and perl bindings to imagemagick (with perl itself, of course): https://bitbucket.org/ZyX_I/formatvim/src/424e045946fb76e74f0e9c6a1490695b35076116/doc/format.txt#format.txt-389. Works on screenshots like

![Color table with markers](http://img-fotki.yandex.ru/get/43572/9151298.6/0_bd5f8_c1216ae5_orig.png)

under most circumstances may create such screenshots itself. Output looks like

```YAML
---
- '#808080'
- '#ff6060'
- '#00ff00'
- '#ffff00'
- '#8080ff'
- '#ff40ff'
- '#00ffff'
- '#ffffff'
```

**Comment by ZyX-I** [comment]
(Note: marker at the top-left corner assumes alternating colors pattern, it does not require exact `#000000` or `#ffffff` cells. But it does require colors to be absolutely identical: do not try this on transparent window unless `import` from imagemagick can catch it as non-transparent or with transparency stored in alpha channel or thrown away without taking background into account (I do not actually know what `import` does with transparent windows). Script is not very fast, but given how often it is needed this is not much of a problem.)

**Comment by DarkDefender** [comment]
@jfelchner The terminal emulator neovim runs, always outputs it's colors in true color (RGB) mode. I'm guessing that this is the case with iTerm (an all other modern VTEs also) because our desktops do not run 256 color palette mode anymore...

If you do not run neovim in true color mode then we try to translate the RGB code to an indexed color. However this will not work if the user turns on true color mode in neovim. Because then, it will get a lot of false positives and the colors will be wrong when the user expects full true color.

So to get around this issue you have to define the terminal colors in your neovim config file (see the config file wsdjeg linked in his referenced issue).

This solution is needed anyways for people running neovim outside a VTE.

**Comment by jfelchner** [comment]
@DarkDefender ok so now I think I'm finally starting to understand, so let me ask one more question. 

Neovim can obviously access the colors that my VTE has defined in its color palette because when true color is _off_ I can see them, so why doesn't true color mode also use them when it encounters ANSI codes for the base 16 colors?

Surely we could fall back to the defaults only if the user is not running in a VTE?

The reason I'm asking is because I'm a fairly technical person and between the Term not outputting bold colors properly in non-true color mode and the term not respecting my VTE color palette, this is a _lot_ of "WTF" for most people on this feature. 

I _totally get_ that this thing is running in a buffer, but that's not people's perception. 

In my opinion term buffers should behave as much like the VTE that the user is using as possible. If the user is outside of one, then sane defaults (like red for red, green for green, etc) seem completely appropriate.

**Comment by DarkDefender** [comment]
Neither Neovim nor the terminal buffers knows what color you are using. As I said, in non true color mode, we wrap the default ANSI colors to terminal color index hints. So for example color (0,0,255) might become \e[22;31m or what have you. It is your VTE the transforms the terminal color hint to a color in the end.

In non true color mode, neovim (and vim) simply "asks" the terminal to display a color by a number in the range of 0-255. It is your terminal that then converts that number into a RGB color.

If you run in true color mode then you basically tell neovim that you do not want to let your terminal have a say in what the final color will be. So no conversion is done here.

IIRC, there were some requests before to have neovim emulate the user VTE. But this is not feasible because you would have to implement alot of different terminals for no good reason (IMHO).

**Comment by justinmk** [comment]
In true color mode, if some process (say `ls`) in `:term` emits `\e[22;31m`, in what form does it reach the host VTE?

**Comment by DarkDefender** [comment]
@justinmk in true color mode it will reach the host VTE as a true color terminal code.

**Comment by justinmk** [comment]
So that, in one sentence, explains why "the color mapping that one defines in your emulator" is "bypassed". Correct?

**Comment by DarkDefender** [comment]
Yes. IIRC in true color mode, neovim will try to only output true color terminal codes.

**Comment by jfelchner** [comment]
@justinmk @DarkDefender cool, so now I understand and I can write a little script to output a Neovim snippet and append it to my colorscheme file to set the `g:terminal_` variables, so no worries there 👍 Thank you for taking the time to explain it to me.

Below are just my comments about my concerns for other new people coming to the terminal buffer.  You can take it or leave it, other than #4274 I don't have a ton of context here like @DarkDefender obviously does!  Now that I have a resolution it's the last I'll say on the subject unless someone pings me about it. :)

#### Concern

My only concern now is for people onboarded to using the terminal inside of Neovim.  I think that the way it behaves right now (including this issue and the fact that "bold" text doesn't use the top 8 of the first 16 terminal colors) is going to cause a _ton_ of support issues.  Even with documentation, people tend to open an issue before they Google or type `:help terminal`.

And don't get me wrong, it's kind of nice to say:

> Hey, in true color mode, we always use true color output for every color

But I would guess that for every user who customizes their colors, this is going to be a WTF moment.  And if it's a WTF moment, it's going to be a support nightmare.  And it's going to make it look like there's a bug in Neovim _even if_ it's the intended behavior.

#### Scenarios

##### User has not modified their colors so `Pallet Red` == `True Red`

In this case, using the VTE red would not be any different than using the true color red.  These users don't even notice that there's currently any weird behavior.

##### User has modified their colors so `Pallet Red` != `True Red`

In this case, using the VTE colors will give the user the color that they would expect to get due to the modifications they've made to their terminal.

##### User is using color codes above the first 16

While it's certainly possible to customize these upper colors and change them, this is a _muuuuch_ less common practice and thus I think that mapping these to True Color codes is reasonable.

##### User is using True Color codes in their prompt or other output

In this case, it's not within the 0-255 range so these colors can be used verbatim

#### Suggestion

My suggestion would be that Neovim needs to have two options added for Terminal output.  These options need to correspond to the most used VTE options:

* Draw bold text in bright colors (defaulted to 'on' just like most VTEs do)
* Map Terminal colors (defaulted to 'off')

At the very least have an option to "ask" the VTE about the ANSI color codes rather than assuming that they haven't been mapped to other colors.

**Comment by yyt16384** [comment]
Another related bug: in 256 color mode (true color off), color 16 in terminal buffer becomes 0 in outer terminal. I assume this is because color 16 == color 0 in default palette.

**Comment by DarkDefender** [comment]
@yyt16384 I fixed that issue a while back, sadly it hasn't been merged yet: https://github.com/neovim/neovim/pull/4350

**Comment by justinmk** [comment]
As explained in https://github.com/neovim/neovim/issues/4696#issuecomment-216531960 :

> If you run in true color mode then you basically tell neovim that you do not want to let your terminal have a say in what the final color will be. So no conversion is done here.

With 'termguicolors' Nvim emits RGB colors instead of color indexes. But color indexes are the mechanism by which the host terminal's "configured colors" are decided. 

The `g:terminal_color_` colors are equivalent to configuring your host terminal's colors.  Just like you configured your host terminal, you can/must configure `:terminal`  (because `:terminal` itself is a terminal).

re @jfelchner suggestions: 

- we would need to capture color indexes from the shell program
    - _assuming_ libvterm exposes that (I think it doesn't: we configure the palette once via `vterm_state_set_palette_color` then we get RGB colors thereafter) 
- ...then in the Nvim TUI layer we would need to decide _per-cell_ whether we want to emit RGB sequences or color indexes,
- ...which means also that the choice of `gui{fg,bg}` vs `cterm{fg,bg}` must be decided _per-cell_.

That complexity seems like a bad tradeoff. The way forward is https://github.com/neovim/neovim/pull/7406 accompanied by better docs.
