### ISSUE TITLE
neovim-qt qa! doesn't close the window

### ISSUE THREAD

**Issue by yoava333** [neovim/neovim#4703]
- Neovim version:0.1.5-dev
- Vim behaves differently? Vim version: every gvim version
- Operating system/version: Windows 10 x64
- Terminal name/version: n/a
- `$TERM`: n/a
### Actual behaviour

issuing :qa! the window doesn't close, it requires another key stroke to make it close.
### Expected behaviour

after issuing the command the window should close
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:qa!
```

witness it's not quitting

**Comment by KillTheMule** [comment]
This kinda sounds like you should report it at https://github.com/equalsraf/neovim-qt/issues.

**Comment by justinmk** [comment]
Well, it's a known issue with neovim-qt, but I believe neovim-qt is blocked by a problem with the nvim API. Not sure if we know exactly what that problem is, yet. cc @equalsraf

**Comment by equalsraf** [comment]
This seems like https://github.com/equalsraf/neovim-qt/issues/53, I can confirm it. We had a similar issue before (fixed upstream in https://github.com/libuv/libuv/issues/27).

It would seem Neovim blocks waiting for another event that never arrives instead of quitting, or it arrives but does not trigger the end of the event loop. I have been unable to replicate in UNIX though.

Whichever the case this will require some deep debugging into either libuv or our use of the event loop, and I didn't get around to doing that yet.

**Comment by justinmk** [comment]
Just noticed that [this line](https://github.com/neovim/neovim/blob/master/src/nvim/msgpack_rpc/channel.c#L637) does `mch_exit()` if embedded nvim's stdio channel is closed. But `mch_exit()` is not a "normal" exit, `getout()` is the normal "full" exit.

**Comment by prabirshrestha** [comment]
@justinmk @equalsraf any updates on this?

**Comment by equalsraf** [comment]
A workaround has been added for this in nvim-qt, I've tagged a new release as v0.2.6 (still building).

**Comment by equalsraf** [comment]
This is fixed in the latest build.
