### ISSUE TITLE
Neovim cannot write to its own stderr

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#4772]
While `vim -c '!echo "foo" >&2' -c 'q'` will output `foo`, `nvim -c '!echo "foo" >&2' -c 'q'` won't.

This is used by e.g. Vader to display test results: https://github.com/junegunn/vader.vim/blob/e6209b07d3a07cd74c0ec8bd113178d8854e7516/autoload/vader.vim#L124-L129.

The use case is also very valid for scripting (Neo)vim in general: produce some output that could be used from/in a shell script.

**Comment by ZyX-I** [comment]
Neovim cannot allow anything like this by design: in Neovim `!` runs command connected to a created pipes because Neovim core cannot and should not know whether attached UI is connected to a terminal, so like GUI Vim (with which your example will not work) everything is displayed as the regular `:echo` message.

Neither Vim nor Neovim were ever supposed to be scriptable like this. There are some more or less dirty hacks which work under certain conditions, but if you want to script them better write VimL script. Next good thing is using only features described in documentation and I do not see `:h :!` stating something like “stderr of the running command is connected to stderr of the terminal Vim runs in”. Also I did not see help stating that Vim itself will *not* output to stderr escape sequences it uses to draw his UI; and I know that at least bash has such habit (so it is both possible, at least to some extent, and actually used).

---

BTW, in Neovim you can do

    nvim --headless  -c 'call setline(1, 123)' -c 'silent w! /dev/stderr' -c cq

or

    nvim --headless -c 'call writefile([123], "/dev/stderr")' -c cq

. This works in Vim also (note that in Vim if you use `-c` the result is drawn to the alternate screen by default so you will not see it; this fact does not affect redirection).

**Comment by blueyed** [comment]
@ZyX-I 
Thanks for this explanation!

However, the method you've mentioned does not work:

```
% nvim --headless  -c 'call setline(1, 123)' -c 'silent w! /dev/stderr' -c cq
Error detected while processing command line:
E503: "/dev/stderr" is not a file or writable device
```

The 2nd one works:
```
% nvim --headless -c 'call writefile([123], "/dev/stderr")' -c cq
123
```

NVIM v0.1.5-215-gc9b1ad3

**Comment by justinmk** [comment]
`w! /dev/stderr` reports `E503: "/dev/stderr" is not a file or writable device` which could be a bug in our `os_nodetype()` function.

**Comment by ZyX-I** [comment]
I should say it used to work some time ago. I have “system” Neovim which was not updated for months (still 0.0.0 in version and no commit hash) and there it works, but not at 0ccb90e.

**Comment by justinmk** [comment]
It's probably my fault then, I changed `os_nodetype()` recently.

**Comment by blueyed** [comment]
Thanks, @justinmk!

**Comment by bfredl** [comment]
Hmm, it doesn't seem writing to `/dev/stderr` words when stderr is an unnamed pipe, `/dev/stderr` is a link to `/proc/self/fd/2` which then is a link to something like `socket:[1077040]` which not is a valid path. I discovered this when debugging the test for #4723 , and tried to write to stderr in a nested embedded nvim instance to a handler in the tested instance.
I suppose nvim could special case the path `/proc/self/fd/2` (when writing or appending) to use the `stderr` stream.

**Comment by justinmk** [comment]
@bfredl what's `os_nodetype` returning in that case?

**Comment by bfredl** [comment]
Node type is `NODE_WRITABLE`, perhaps as this gets interpreted as `/proc/self/fd/socket:[1077040]` (which is not writable, but the permission bits of `/proc/` maybe makes it look so). 
The problem is that `/proc/self/fd/` (and thus `/dev/stdXXX`) is a leaky abstraction: it works for pty:s (as they exist as named devices in `/dev/pts/`) and (at least non-moved, non-unlinked) regular files, but not for pipes, sockets or named pipes I suppose (as only the connectable endpoint is "named", not the individual connected stream). The kernel still marks it as symlink still though it doesn't point to anything `open()`-able.

I mention this as I need to output stderr from an `--embed`ded nvim instance to test #4723. Alternative I could write a small lua fixture to do both rpc and stderr, but then I need a reliable way to spawn another lua process within busted/nvim with the correct paths for luarocks...

**Comment by bfredl** [comment]
#6844 will allow vimscript to write to stderr, and in headless mode also to stdout.

**Comment by justinmk** [comment]
>  The kernel still marks it as symlink still though it doesn't point to anything open()-able.

Wouldn't that also be a problem in Vim? So I think this issue can be closed.

`:w! /dev/stderr` works for me on macOS and linux. https://github.com/neovim/neovim/pull/7561 fixes a regression on macOS caused by https://github.com/neovim/neovim/pull/6860/files .

**Comment by blueyed** [comment]
Closing as per last comment(s)/question.

**Comment by blueyed** [comment]
@bfredl 

> #6844 will allow vimscript to write to stderr, and in headless mode also to stdout.

It seems to require headless mode always.  The following does not output anything, but only when using `--headless`:

`nvim -c 'call writefile(["stdout"], "/dev/stdout")' -c 'call writefile(["stderr"], "/dev/stderr")' -cq
