### ISSUE TITLE
:substitute "live" feedback

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#4794]
_[Note to reviewers: this is a 3-week project for a group of students. The goal is to get this feature shipped ~3 weeks from now. Please try to keep that in mind when making suggestions.]_

The [vim-over plugin](https://github.com/osyo-manga/vim-over#preview-in-the-over-command-line) is a Vim/Neovim plugin which implements "live" search-and-replace. But it has quirks because of limitations in Vim/Neovim. 

We can use the vim-over plugin as a basis for determining what parts of Neovim need to change in order to provide live search-and-replace _seamlessly_. For example, with 'incsearch' option enabled, `/` seamlessly highlights the next match as the user types. Similarly, we want `:substitute` to seamlessly search and replace as the user types.

Let's outline what is needed to provide this "natively" in Neovim, by comparing it to the vim-over plugin.
- vim-over gets user input from a custom input prompt. Instead, we want the built-in `:` prompt to listen for user key presses. This requires the implementation of a new event (say `CommandCharPre`; compare the existing `InsertCharPre` event), which fires on each keypress while the user is in command-mode. 
  - The implementation of `InsertCharPre` may be helpful as a starting point.
  - `CommandCharPre` should _not_ set "textlock".
  - Implementing `CommandCharPre` may trigger segfaults in cranky parts of the code. We have a robust CI system to deal with this. Don't let it discourage you.  
- vim-over works by editing the buffer, then `undo` to reset the view if the user cancels. This is a good enough approach to use, but may require moderate enhancement of the undo module in Neovim. 

There's probably a lot that I'm forgetting. I hope others (including @osyo-manga) can add thoughts.

**Comment by DesbyP** [comment]
Seems like _vim-over_ displays the result of the substitution next to the occurrence in the same window.

Our idea was to split the current window in order to display the search results, and dynamically display the result of the substitution, as the user types his command. You can see pictures attached for an example from _TextMate_.

What do you think?

![lives1](https://cloud.githubusercontent.com/assets/18722999/15421473/d246b1e8-1e73-11e6-86ba-73272b4317eb.png)
![lives2](https://cloud.githubusercontent.com/assets/18722999/15421476/d4eca52e-1e73-11e6-9a70-7ffe5d3e6e0e.png)

**Comment by KillTheMule** [comment]
> What do you think?

Just from a personal point of view, I dislike opening splits non-explicitly, I find it quite a bit disrupting. A third option would be to not open the split, but instead show what the split would show in the current window, i.e. "reducing" the buffer shown while typing.

You're going to put in a new option anyways, right? Say, "incsub"... you could let the user configure the exact behavior by letting this option be set to the right value, not just on/off (e.g. a string value, if tit contains "s" then split, if it contains "r" then reduce what's shown to search results...). But since you want to prioritize finishing your project, you could just decide on the option variable to keep it flexible, but just implement one of the variants

**Comment by justinmk** [comment]
It should replace the results in-place. But the mechansim to achieve this--a new event, CommandCharPre--gives enough flexibility that the choice of split or not is minor detail.

**Comment by HarmtH** [comment]
It would be nice to be able to real-time switch between highlighting the matching text and showing/highlighting the new text. For example by having ^T toggling it in `:s` mode.

**Comment by Robinhola** [comment]
> show what the split would show in the current window, i.e. "reducing" the buffer shown while typing.

@KillTheMule We came up with the idea of splitting the screen to be able to work freely on a new buffer and thus not modify the current one but we indeed prefer your idea; we just don't know yet how buffers properly work (we are currently working on changing that). But as @justinmk  said, it should only be a minor detail to implement one option over the other.

> It would be nice to be able to real-time switch between highlighting the matching text and showing/highlighting the new text.

@HarmtH That would be really nice indeed and even more so if we replace the results in-place (in the current window) so that the user could switch back and forth between the original buffer and the "preview" mode (i.e. only showing the lines containing the occurrences).

**Comment by bfredl** [comment]
> vim-over works by editing the buffer, then undo to reset the view if the user cancels. 

Just as `matchaddpos()` is now able to conceal text in the buffer, I wonder how hard it would be to also add text (the substitution in this case) to display between two characters in a buffer, without adding it to a buffer (note this is quite distinct from a jedi-vim style popup, which should float over the buffer, while this is in-line with the text and affects linebreaking etc just like `conceal`).

**Comment by bfredl** [comment]
> Implementing CommandCharPre may trigger segfaults in cranky parts of the code. 

I don't think so, or at least, we already allow event processing in cmdline mode, so we should already be exposed to these kind of bugs if they exist. So if this _increases_ the exposure and happens to find bugs, it will also help make event processing more robust in general.

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/5561
