### ISSUE TITLE
loadview clobbers :term height

### ISSUE THREAD

**Issue by mmlb** [neovim/neovim#4820]
- Neovim version: NVIM v0.1.5-280-g176f223
- [ ] Vim behaves differently? Vim version: N/A
- Operating system/version: Arch Linux
- Terminal name/version: gnome-terminal/3.20.2
- `$TERM`: xterm-256color

### Actual behaviour
All terminal buffer's height are restricted to 1/2 of full window height after running `loadview`
### Expected behaviour
terminal buffer height is unaffected
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NONE +'set hidden' /tmp/non-existent-file
:terminal
# note cursor is at bottom of screen
<C-\><C-n>
:bn
:bn
i #note cursor is still at bottom of screen
<C-\><C-n>
:bn
:mkview
(can go and verify cursor is still at bottom of screen in terminal in insert mode)
:loadview
:bn
i # (cursor is now at middle of screen)
```

See https://asciinema.org/a/07f8qqrb1dzbabzwo4lqb1e75

**Comment by mhinz** [comment]
Reproduced with above description.

The terminal buffer itself doesn't get corrupted (thus you can still move around or use `zb` etc.), but entering terminal mode makes the cursor gets fixed to the middle of the terminal buffer somehow.

**Comment by jbradaric** [comment]
Changing the height of the terminal window also resolves the issue.

This bug seems to be caused by the last line in the view file, `doautoall SessionLoadPost`. `doautoall` goes through all buffers and performs the autocmd. If the buffer is not visible in a window, a temporary window will be created and the buffer will be shown there while autocommand is being performed.

The temporary window is created in a horizontal split, with the height equal to half of the height of the current window. But it seems that the terminal buffer remembers its size from the temporary window and doesn't update it after being shown again by the user.

**Comment by mhinz** [comment]
Yup, the terminal size will get set to the size of the surrounding window during `:doautoall`, but not reset afterwards. The commit above should fix it.

**Comment by mmlb** [comment]
hooray :tada: thanks @mhinz
