### ISSUE TITLE
Detect if running --headless / get UI

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#4842]
To detect if it's possible to write to `/dev/stderr` (https://github.com/neovim/neovim/issues/4772) it would be required to know if `nvim` was started with the `--headless` option.

Additionally (or instead) there could be a variable holding the UI being used (which would be empty or "headless" then).

**Comment by ZyX-I** [comment]
@blueyed `--headless` does not affect the possibility to write to `/dev/stderr`. If you use  `--cmd` in place of `-c` then the effect will be the same with and without `--headless` because UI was not started yet, if you still use `-c` then you will need to use `>/dev/null` to avoid clobbering the view for the time Neovim is running, but this is not actually necessary because UI writes to stdout and thus redirection of stderr works absolutely fine.

Second variant makes more sense in this case: it will be empty in `--cmd` as well, but I still do not see what this is for, you do not need to know UI status to write to `/dev/stderr` and #4772 talks about using this in the shell scripts meaning that you have plenty of ways to tell your plugin or whatever to write to stderr (environment variable, `-c 'let g:var = 1'`, …).

**Comment by blueyed** [comment]
@ZyX-I 
It is for running Vader tests.

I am currently using `VADER_OUTPUT_FILE=/dev/stderr nvim --headless -u vimrc -i NONE -c 'silent Vader! *'`.
`--cmd` cannot be used here: `E492: Not an editor command: silent Vader! *`

I know in this place that I can write to `/dev/stderr`, but it would be useful to detect this automatically in Vader somehow (see https://github.com/junegunn/vader.vim/pull/75).

But regardless of this, I'd say it would still be useful to have information about the UI in Vimscript somehow, don't you think?

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/commit/9f994bb69925ed943b17d03f2cad7d5e2c21e992 introduces `nvim_list_uis()`. If it returns empty, that implies `--headless` (or `--embed`).

**Comment by HaleTom** [comment]
The `nvim_list_uis()` test must be made after `VimEnter`: [`--headless`](https://neovim.io/doc/user/starting.html#--headless)

**Comment by justinmk** [comment]
Note also that `has('gui_running')` #22382 was implemented since this issue, though that isn't exactly the same.
