### ISSUE TITLE
nmap <C-F12> can not work.

### ISSUE THREAD

**Issue by gngshn** [neovim/neovim#4862]
- Neovim version: the newest to 1st June 2016.
- [ yes ] Vim behaves differently? Vim version:7.4
- Operating system/version: Fedora 23
- Terminal name/version:GNOME Terminal 3.18.3
- `$TERM`:xterm-256color
### Actual behaviour

Ctrl+Fx(x=1~12) key map can not work, but work well in vim.
### Expected behaviour

Ctrl+Fx can work in neovim

**Comment by leomao** [comment]
I can confirm this issue.
Two more observations:
- Ctrl+Fx **will** work in tmux. (`$TERM` is `screen-256color`)
- In insert mode, pressing Ctrl + F9 will get `<F33>` instead of `<C-F9>`.

**Comment by justinmk** [comment]
> Ctrl+Fx will work in tmux

That indicates that this is a terminfo issue.

> In insert mode, pressing Ctrl + F9 will get `<F33>` instead of `<C-F9>`.

In tmux too?

**Comment by leomao** [comment]
No.
In tmux, it will be `<C-F9>` correctly.

BTW, I have `setw -g xterm-keys on` in my `.tmux.conf`.

**Comment by leomao** [comment]
An update on this issue:

The issue persists with the latest neovim. Latest vim(8.0.329) doesn't have this issue.

BTW, as of tmux 2.1+, there are two new terms:  `tmux` and `tmux-256color`.
This issue is present in tmux with these terms.

Actually, Ctrl + Fx (and Shift + Fx) only works when `$TERM` is either `screen` or `screen-256color`.

### Workaround

`map <C-Fx>` is equal to `map <Fy>` where y = x + 24.
`map <S-Fx>` is equal to `map <Fy>` where y = x + 12.

So if you want to map `<C-F12>` to something, you can also map `<F36>` to the same thing.

**Comment by nateozem** [comment]
I can add the implementation where pressing `mod`+`FNxx` keys will be mapped to `<C-Fxx>`. I just want to know if this is the expected behavior if `$TERM` is `xterm-256color` (or set to similar profiles) and should be done within `nvim`?

**Comment by justinmk** [comment]
merging with https://github.com/neovim/neovim/issues/7384
