### ISSUE TITLE
I can't edit my init.vim config because swap file in .local is created, how can I fix this?

### ISSUE THREAD

**Issue by nikitavoloboev** [neovim/neovim#4891]
Every time I try to edit my init.vim of nevoim, I get this issue. I tried googling for it but couldn't resolve it. I also tried deleting nevim folder in .local/ but that did not fix it either, it just gets created again. What should I do? None of my programs are editing the file, is this some kind of bug? This is the error message I get : 

![2016-06-07 at 18 37](https://cloud.githubusercontent.com/assets/6391776/15866447/ec14bc36-2cde-11e6-809a-7bb33a85a4ad.png)

I have done the steps that it asks, i.e. typing :recover whilst in nevoim. vim -r init.vim and also deleting the swap folder once again but I still get this message. Deleting the swap file fixed it temporarily but after some time this message comes back again and it is quite annoying.

I would appreciate any help. Thank you.

**Comment by KillTheMule** [comment]
You should really fill out that issue template

**Comment by jamessan** [comment]
```
process ID: 1934 (still running)
```
You have another nvim instance editing your init.vim.  Neovim is behaving exactly like it's supposed to by telling you the file is already being edited.

**Comment by nikitavoloboev** [comment]
All right, thank you. I deleted the share folder again and it seems to be working well. It was quite strange to see that process there though.

**Comment by ZyX-I** [comment]
Neither Vim nor Neovim does not bother (and on some systems can’t) to check whether PID of the process belongs to the (Neo)Vim instance. So if swap file exists and it states it was created by PID 1, then (Neo)Vim will just check whether PID 1 exists and not whether it belongs to (Neo)Vim and not init. AFAIR this was briefly discussed in the Vim mailing list — me or somebody else suggested to check whether PID belongs to a Vim instance — and such change was rejected because 1) all variants are not portable, 2) in some cases this is not only not portable, but also not possible and 3) chances that PID was taken by other process are not too high to bother.

**Comment by merlimmateus** [comment]
I already fixed this issue on my machine, you need to recover you "swp" file, but before you need to "install" the plug, so install this before:

- sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

- Next step you need to open your file, click to recover, install and update your plugs.

So, it's fixed your problem. Any questions send here!!
