### ISSUE TITLE
jemalloc download issue

### ISSUE THREAD

**Issue by whdxwym** [neovim/neovim#4906]
I pull the latest master banch, and I cannot download jemalloc-4.0.2 while doing make (maybe my network problem). even though i download the package myself,  put it in the neovim/.deps/build/downloads/jemalloc directory, and do make again, it will rewrite the package and download failed again.

**Comment by mhinz** [comment]
I can see why cmake tries downloading it again and this can be fixed easily.

As to your network troubles.. could be anything without more information. :)

**Comment by jamessan** [comment]
The [`USE_EXISTING_SRC`](https://github.com/neovim/neovim/blob/master/third-party/CMakeLists.txt#L29) variable controls whether to use pre-downloaded dependencies or not.

**Comment by mhinz** [comment]
`USE_EXISTING_SRC_DIR` doesn't help here, since it only checks if there are unpacked sources in `.deps/build/src`, but not for already downloaded sources in `.deps/build/downloads`. It's one step too late, so to say.

It's easy to fix, but do you prefer adding `USE_EXISTING_DOWNLOADS_DIR` or making `USE_EXISTING_SRC_DIR` also check the downloads dir?

The best solution for would be having one variable like `USE_EXISTING_DIRS` to check for both things, but I don't want to break backward compatibility either.

**Comment by jamessan** [comment]
Sure, we don't have anything to look in the downloads directory, but unpacking into the src directory and using USE_EXISTING_SRC_DIR allows one to build.

Do we need extra variables or just better documentation?

**Comment by mhinz** [comment]
I'd go for better documentation. It's actually cmake ([ExternalProject_Add](https://github.com/neovim/neovim/blob/master/third-party/cmake/BuildJeMalloc.cmake#L6-L22)) itself, that does the re-downloading. Only afterwards [DownloadAndExtractFile.cmake](https://github.com/neovim/neovim/blob/master/third-party/cmake/BuildJeMalloc.cmake#L17) is executed. So changing this behaviour is not _that_ easy.

It would probably need a depending subproject that checks the `downloads` directory first..

So, yeah, I vote for better documentation now.

**Comment by mhinz** [comment]
Actually I think we (me) should not overthink this and simply assume a working internet connection during build time.
