### ISSUE TITLE
fix os_file_exists or vim_rename

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#4939]
- it looks like os_file_exists should be named os_path_exists: if I am not mistaking, os_stat(name, &statbuf) is going to succeed if name is a directory and not a file. Not sure what if it is a broken symbolic link. And, of course, both cases are not tested.
- If I am wrong here, then vim_rename has a bug: it will fail should code encounter directory or broken symbolic link, without trying further n’s.

Followup of https://github.com/neovim/neovim/issues/4547#issuecomment-226970742

**Comment by danobi** [comment]
Hi,
I've spent some time looking into this issue and here are my findings:

- `os_file_exists` is correct in it's implementation and naming
- `os_stat(..)` succeeds when the path it's passed is an existing **file or directory**. That is to say, using `os_file_exists` will work on either a file or directory. This is because the underlying function, `uv_fs_stat`, is essentially a thin wrapper around the `stat(2)` system call.

**Comment by ZyX-I** [comment]
@danobi `os_file_exist` naming is not correct if it succeeds on a directory.

**Comment by danobi** [comment]
@ZyX-I I will fix that, then.

**Comment by z3t0** [comment]
This issue has been resolved, right?
