### ISSUE TITLE
Documentation cites XDG_CONFIG_HOME, not set on Ubuntu?

### ISSUE THREAD

**Issue by oconnore** [neovim/neovim#4951]
- `nvim --version`: 0.1.4
- Operating system/version: Linux
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

### Actual behaviour

The documentation for "changes from vim" explains the directories to use for XDG. But $XDG_CONFIG_HOME is not a variable on my Ubuntu 16.04 shell.

$XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg

Do I pick one of those? Where is it supposed to go? Why can't the nvim documentation just give me a path name instead of a variable?

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/wiki/FAQ#where-should-i-put-my-config-vimrc

The documentation might be off-putting because it is using not well-known shell features. `mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}` is creating `~ /.config` if XDG_CONFIG_HOME is blank. But then the `ln ...` lines are not using `${XDG_CONFIG_HOME:=$HOME/.config}` so this is actually invalid.

**Comment by fwalch** [comment]
> so they are actually invalid.

I thought so, too, but the variable actually gets set with this syntax:

```
$ echo $XDG_CONFIG_HOME

$ echo ${XDG_CONFIG_HOME:=$HOME/.config}
/home/florian/.config
$ echo $XDG_CONFIG_HOME
/home/florian/.config
```

**Comment by rscholer** [comment]
`(note it's :=, not :-)`
They are equivalent: [Parameter Substitutions](http://tldp.org/LDP/abs/html/parameter-substitution.html).

**Comment by fwalch** [comment]
>  They are equivalent: Parameter Substitutions.

No, they are not:

```
$ echo $A

$ echo ${A:-default}
default
$ echo $A

$ echo ${A:=default}
default
$ echo $A
default
```

**Comment by mhinz** [comment]
But there you go.. it led to confusion already. I'm in favour of changing it not to use any parameter expansion.
