### ISSUE TITLE
Result of fnamemodify("d:\\test.txt", ":h") is incorrect

### ISSUE THREAD

**Issue by imbear** [neovim/neovim#4955]
- `nvim --version`: 0.1.5-dev
- Vim (version: 7.4 patches 1-1952 ) 
- Operating system/version: Win7 Home
- Terminal name/version: nvim-qt v0.2.0

### Actual behaviour

Result is "d", which is a invalid path.

### Expected behaviour

In vim, result is "d:\", which is right.

**Comment by aristogatto** [comment]
I've traced the bug up to [this line](https://github.com/neovim/neovim/blob/56f178058a25d550568d9673b13f08cfa1510a75/src/nvim/eval.c#L21803)
The actual issue probably is deeper within _**after_pathsep**_ since other than the `(char *)` casts that line is identical to vim's but I haven't had the time to debug any further. 
A temporary fix is to add `&& s[tail-s-2] != ':'` to the while loop's condition.

**Comment by equalsraf** [comment]
`vim_is_pathsep` seems ok, `after_pathsep` could be wrong or maybe we are walking the wrong amount of bytes and jumping over the separator (seems unlikely the multibyte code is wrong for this example though).

Best way to figure it out is to have gdb track the calls to after_pathsep or the value of tail. I'll have a look at it eventually (cross compiler is building :D).

Also, this happens with the forward and back slash, so it doesn't seem to be related to the backslash defines.

**Comment by equalsraf** [comment]
Quick run for fnamemodify(''d:/test.txt", ":h")

```
after_pathsep(c:/test.txt, test.txt) -> 1
after_pathsep(c:/test.txt, /test.txt) -> 1
after_pathsep(c:/test.txt, :/test.txt) -> 0
After first loop tail=":/test.txt" *fnamelen=1
after_pathsep(c:/test.txt, :/test.txt) -> 0
```

I think the culprit here is `get_past_head()` that is supposed to return a string past `c:\` ensuring after_pathsep doesn't even get to the head of the path. Here is the the function [vim](https://github.com/vim/vim/blob/2932359000b2f918d5fade79ea4d124d5943cd07/src/misc1.c#L4918) and here is [neovim](https://github.com/neovim/neovim/blob/5f1a153831d480180b2203120cff776d771ec1a4/src/nvim/path.c#L180).

Quick patch
```diff
diff --git a/src/nvim/path.c b/src/nvim/path.c
index 0d6abf8..e994415 100644
--- a/src/nvim/path.c
+++ b/src/nvim/path.c
@@ -179,9 +179,14 @@ char_u *path_next_component(char_u *fname)
  */
 char_u *get_past_head(char_u *path)
 {
-  char_u  *retval;
+  char_u  *retval = path;
 
-  retval = path;
+#ifdef WIN32
+  // May skip "c:"
+  if (isalpha(path[0]) && path[1] == ':') {
+    retval = path + 2;
+  }
+#endif
 
   while (vim_ispathsep(*retval))
     ++retval;
```

**Comment by equalsraf** [comment]
This is fixed in master. But a functional test wouldn't hurt.
