### ISSUE TITLE
Language Server Protocol for IDEs and text editors

### ISSUE THREAD

**Issue by dumblob** [neovim/neovim#4982]
Just now news about Red Hat and others joining Microsoft's effort to "standardize" a protocol for communication between an IDE and an editor server reached me.

It would be wise to take this into consideration when doing some changes to RPC API, developing modules, etc.

https://github.com/Microsoft/language-server-protocol

**Comment by justinmk** [comment]
This is great to see. Steve Yegge long ago described something like this in the [grok project](https://en.wikipedia.org/wiki/Google_Kythe). Then he got swallowed up by sweet G. 

I think YCM also had similar ambitions, I wonder what @valloric thinks about this.

At any rate I'm not sure it _directly_ affects anything we've done up to this point, nor did we have plans to dictate something like this (I've advocated waiting for a winner to emerge, instead of inventing yet another [swank](https://github.com/astine/swank-client/blob/master/swank-description.markdown)).

**Comment by bfredl** [comment]
I would imagine the neovim side of this protocol could be implemented as a python (or lua) plugin, similar to how vim-ycm is a json client to ycmd, but with use of nvims better async capatibilities. (In fact I have imagined prototyping an async-aware nvim-ycmd myself, but never really got the time to do it)

**Comment by tbelaire** [comment]
It looks like Rust will be using it as well, and I'm thinking of trying to write a plugin to support it.  We'll see how it evolves.

**Comment by Valloric** [comment]
@justinmk We'll plug in the Rust RLS into ycmd once it's stable enough and better than the racerd integration we already have.

**Comment by justinmk** [comment]
Continued at #5522
