### ISSUE TITLE
timers: ":delfunction" on timer callback causes a segfault

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#5022]
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
call timer_start(1000, 'Foo', {'repeat':-1})
delfunction Foo
```

**Comment by ZyX-I** [comment]
This is because things like timers or jobs use `ufunc_T` for their callbacks. They must use what is stored in a regular VAR_FUNC object (i.e. just `char *` function names): current variant not only leads to SEGV’s in such cases, it forbids creating “default callbacks”: C “built-in” functions that can be used for callbacks (though this is currently not used, it may be useful to e.g. implement Vim jobs/channels without tainting our API much and yet without having too much differences: e.g. `expr` request handler implemented as a VimL callback function will use VimL function context, but caller expects that `['eval', 'l']` is `['eval', 'g:l']` and not `['eval', 'l:l']`).

**Comment by bfredl** [comment]
Maybe we should add a `callback_T` internal type that right now just is an owned `char *` but in the future could be extended to partials/lambdas/callable references without needing to refactor all users of it?

**Comment by ZyX-I** [comment]
@bfredl I also think that it is good idea, but not as an alias to `char`: this variant makes compiler not check many things AFAIK (not sure about aliasing `char *`, but if switched to something like my extended-funcrefs `FunctionReference` type would be a struct recorded as `FunctionReference*`, I do not remember any aliases to any `struct *`; also do not forget that style guide requires `CamelCase`, not `callback_T`).

I guess that the only variant which will make compiler give many warnings yet being basically the same thing as `char *` is `typedef struct {char name[]; } FunctionReference;`: while such struct is really just the same thing as `char *`  and can be casted from and to `char *`, compiler will not leave any place where `FunctionReference*` is assigned to `char *` or the opposite without an error.

**Comment by bfredl** [comment]
I would imagine it being a wrapping struct that preferably only need be accessed by consumers using `callback_call` and `callback_free`. Actually to accommodate @justinmk:s proposal #5023 to attach multiple handlers with different self-dictionaries, we could already make it a struct of a function name and a (nullable) self-pointer.

**Comment by ZyX-I** [comment]
I think it is better to reimplement `extended-funcref` Vim branch, this allows VAR_FUNCTION to be a struct like `{ FunctionMethods *meths; void *cookie; }` (though I now think it should be like Python’s PyObject’s: basically a PyObject one of the collection of structs, each having the same header which contains “public API” (i.e. reference to type object)).

**Comment by justinmk** [comment]
cannot reproduce on 8c7e41f596e6

After `:delfunction`, error is correctly reported:

    E117: Unknown function: Foo
