### ISSUE TITLE
change "nvim" to "ni" everywhere

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#5028]
Yes, this is a voting issue (we have not had one of these since early 2014). Everyone is encouraged to use "thumbs up" or "thumbs down" button to vote.

It's fine whichever way you vote. Please read [this comment and the comments below it](https://github.com/neovim/neovim/pull/4934#issuecomment-231551351) for discussion about why rename should be considered.

- If you vote against rename, meaning "I like `nvim` and want it to stay that way", that's a useful signal that tells me most users don't hate the name as much as I do.
- If you vote for the rename, meaning "`nvim` is an awkward name and something shorter like `ni` is worth considering", that's good to know also.

Thanks!

**Comment by ZyX-I** [comment]
Ref @neovim/core

**Comment by wsdjeg** [comment]
I hava two alise in my bashrc.
```
alias vim='nvim'
alias vi='/usr/bin/vim'
```
it is because nvim is too long for me.
BTW, `ni` LGTM

**Comment by PonderingGrower** [comment]
Completely pointless. Anyone can make an alias if they want to.

**Comment by tarruda** [comment]
I don't think names are important enough to justify this change. Long after the move to xdg directories we still got questions about why `nvimrc` stopped working, and even though change was a bit inconvenient, it had a good purpose in the end.

Changing the name to `ni` is going to be inconvenient(move config locations, have to uninstall existing executable and share dir), is going to confuse users, and brings no advantage.

As @PonderingGrower mentioned above, anyone that thinks `nvim` is too long can create aliases. Personally I have `nvim` aliased to `vi` which is already in muscle memory and available in every server I log into.

**Comment by timeyyy** [comment]
:-1:

**Comment by rumpelsepp** [comment]
:-1:

**Comment by chiedo** [comment]
:-1:

**Comment by hoffi** [comment]
👎

**Comment by the-kenny** [comment]
People. You're supposed to press the 'thumbs up' or 'thumbs down' button under the original issue comment. Not write your vote as a comment.

**Comment by PonderingGrower** [comment]
Don't tell me what to do.

**Comment by cfree3** [comment]
I find `nvim` really easy to type; `ni` would be an adjustment -- so I don't see "ease of typing" as a benefit of the change. (Aliases can remedy any such problems, though.)

Ultimately, though, I voted 👍🏼 (on the original comment). Make sure you follow the OP link and read up on the reasoning behind this suggestion before casting a vote either way.

I appreciate the _Monty Python_ reference (and amidst a film I don't particularly care for, I do like the Knights). But more importantly, I like how removing "Vim" from the project name makes Neovim (Ni?) its own entity: it takes the project from saying -- all in its name -- "Vim isn't good enough, so we forked it" to saying that "Vim is great, but we wanted to do something more/else with it". The most convincing snippet from [the OP link](https://github.com/neovim/neovim/pull/4934#issuecomment-231551351):

> And our constant mention of "vim" in our name I think appears a bit combative ("new vim"), as well as being pretty cliche (cf. "nvi").

**Comment by tpabst** [comment]
Bad idea !

**Comment by rgoulter** [comment]
I can't see any technical merit to the use of `ni` over `nvim` (or `neovim`).

And `neovim`/`nvim` do not seem abysmal in terms of marketing. (Is there concern that people won't try neovim, because ...?).

As for the 'cultural' aspect, whether neovim is far distinct from Bram Moolenar's vim to require that "neovim" is a misleading name: even the toplevel readme.md begins with "[this project] is a project that seeks to aggressively refactor Vim". neovim has cool things which vim doesn't have, like embedded terminals, and async job control, but the editor itself is still 'just the same' (from a user's perspective). -- Moreover, since neovim started out as a fork, inheriting the codebase, keeping 'vim' in the title references this.

Whether "new vim" is cliche or not is moot; this project has 19k stars and many months work put into it, the latter weighs more to the value of the project than "bad name".
Whether it's contentious, saying 'vim isn't good enough' ... no need to demand everyone think neovim is 'better' than vim (my understanding is the projects don't share the same goals/requirements), but there were non-superficial reasons why the project was forked + gained support. So even a cliche "it's a better vim" indicates a genuine perspective.

"Emacsen" is used to refer to the family of Emacs programs. (With a historical rift between "GNU Emacs" and "XEmacs"). -- I mean, neovim strikes me as still "a vim", so I don't see the merits of the project distancing itself from keeping 'vim' in the name.

(Sorry for the long comment; bike-shedding / Parkinson's Law of Triviality demands that there be many long comments about a renaming issue).

**Comment by PonderingGrower** [comment]
Completely agree with rgoulter@.  Neovim is already a well known name, I really don't think changing a name will bring some kind of marketing advantage or whatever you might call it.

Arguing whether neovim is a type of vim which is a type of vi is pointless, this project is already well known.

Open software never had good naming, but I don't see as Neovim as particularly abysmal example of that or anything, there are far worse out there.

**Comment by sagotsky** [comment]
-1

I just don't like the name "ni"

**Comment by m-abs** [comment]
It's an editor not a knight, don't say ni. :-1:

**Comment by codeinabox** [comment]
👎

**Comment by juddy** [comment]
👎 nay.

**Comment by ashwin** [comment]
:-1:

**Comment by ZyX-I** [comment]
@rgoulter Vim now does have job control. In fact, Bram started to reimplement our features: specifically he already added

- channels and jobs: long since we added ours, but it is not an easy task
- capture() (though under different name): almost immediately after we merged it
- timestamped viminfo entries, with back and forward compatibility: quite a bit after I created ShaDa

Nothing was implemented in a compatible manner though (capture() may be renamed, but we got this function first…).

**Comment by geowa4** [comment]
While I'm not the biggest fan if the name "ni", I can recognize the need to remove references to "vim". Neovim's aspirations are not aligned with Vim. To Neovim, Vim is a historical foundation upon which it will build new, great things. To keep the name, it will always be grounded in the reputation of Vim, for better or worse. As little as we would like to admit it, a name goes a long way toward letting this project forge it's own destiny and place in editor history. For this reason, I vote to consider a name change.

**Comment by ZyX-I** [comment]
@geowa4 Vim itself always lived with a name that connects him to Vi.

**Comment by justinmk** [comment]
Seems clear. Thanks everyone.

**Comment by ZyX-I** [comment]
Interesting. As core member I can comment and alter labels here, but yet emoji manipulations are locked.

**Comment by bfredl** [comment]
https://www.youtube.com/watch?v=zIV4poUZAQo
