### ISSUE TITLE
Emoji UI bug

### ISSUE THREAD

**Issue by alexgenco** [neovim/neovim#5149]
- `nvim --version`: master (v0.1.5-669-g2cd3a2d)
- Vim (version: 7.4) behaves differently? yes
- Operating system/version: osx 10.11.6
- Terminal name/version: Terminal.app 2.6.1 and iTerm2 3.0.5
- `$TERM`: screen-256color

### Actual behaviour
An emoji followed by a regular character displays the emoji overlapping the character.

### Expected behaviour
An emoji followed by a regular character displays the emoji followed by the character.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
i👍x
```

**Comment by timfeirg** [comment]
this may be a iterm2 issue, not a neovim one, as I see the overlapping already in iterm2

![image](https://cloud.githubusercontent.com/assets/4319104/17284935/c06460c6-57f1-11e6-90db-630b1d242087.png)

**Comment by timfeirg** [comment]
I see the same output on both vim and neovim @alexgenco.

**Comment by fornwall** [comment]
Is this due to that Unicode 9, which latest neovim and vim both support, [is marking emojis as having wcwidth=2, which is correct for most fonts](https://news.ycombinator.com/item?id=11963781) - but [iterm2 and most terminals does not support Unicode 9 yet](https://github.com/gnachman/iTerm2/pull/294)?

**Comment by jamessan** [comment]
This as also reported in #4976.  As previously stated, this is a mismatch between the Unicode knowledge in neovim and the terminal (and possibly other terminal related libraries in between).

**Comment by alexgenco** [comment]
I'm probably misunderstanding something, but why does the bug only appear in nvim and not vim on the same terminal?

**Comment by jamessan** [comment]
Are you using Vim 7.4.1960 or newer?

**Comment by alexgenco** [comment]
@jamessan yeah, 7.4.1993

**Comment by fornwall** [comment]
> I'm probably misunderstanding something, but why does the bug only appear in nvim and not vim on the same terminal?

`vim` and `nvim` from HEAD (=supports Unicode 9) both work when the terminal uses wcwidth=2 for emojis and uses a font that renders emojis with double width.

For (pre-Unicode 9) terminals that uses wcwidth=1 for emojis, but where the font renders emojis with double width (where e.g. `echo 👍x` shows an overlap outside the editor), `nvim` shows the overlap as reported here whereas `vim` manages to avoid it.

Perhaps vim uses cursor reporting and/or absolute cursor positioning to work around issues with terminals not displaying wide characters correctly? Seems so, since if I on Terminal.app copy the `👍x` text as shown by `vim` without overlap I actually get

1. 👍
2. ' ' (ascii space)
3. x

instead of the actual file content (which I do get when copying from the terminal when `nvim` shows the file):

1. 👍
2. x

If so, it's hopefully not necessary doing this for neovim, but I guess it depends on how fast terminal emulators are to adopt Unicode 9 and how important this issue is (and how elegant a fix is).

**Comment by kyrias** [comment]
I get the following when doing it with the taco emoji: https://imgur.com/a/7L0K7  While I could be fine with the overlapping, even if I don't like it, the rendering is completely broken.

**Comment by jamessan** [comment]
Can people try #5372 to see if that improves the situation?

**Comment by kyrias** [comment]
It does indeed fix my issue.

**Comment by joshuarubin** [comment]
I'm looking at possibly working on a patch to provide full unicode 9 support (via [JuliaLang/utf8proc](https://github.com/JuliaLang/utf8proc)). It would have to be a build-time option and would require that it be used with terminals that use unicode 9 widths. Looking through the code, it would probably override the stuff in `mbyte.c` with the utf8proc equivalents.

Would this be a welcome patch, or would I be wasting my time?

The relevant code in `mbyte.c` that would be build-time overridden would be:

```c
    if (!utf_printable(c))
      return 6;                 /* unprintable, displays <xxxx> */
    if (intable(doublewidth, ARRAY_SIZE(doublewidth), c))
      return 2;
```

**Comment by justinmk** [comment]
@joshuarubin readme at https://github.com/JuliaLang/utf8proc mentions intention to add support for Unicode 7. If that lands, would this need to be optional?

**Comment by joshuarubin** [comment]
> would this need to be optional?

Would what need to be optional?

utf8proc would only be necessary for its character width calculations. I did a similar thing with [tmux](https://github.com/tmux/tmux/blob/master/compat/utf8proc.c).

**Comment by joshuarubin** [comment]
Here is a better description of utf8proc: http://julialang.org/utf8proc/

**Comment by justinmk** [comment]
> Would what need to be optional?

You mentioned "It would have to be a build-time option". Why? 

> http://julialang.org/utf8proc/

That also means plans to add "Unicode 7 support".

When should users choose to enable the build-time option? You mentioned "terminals that use unicode 9 widths"; what happens if a user runs `nvim` in two different terminals, one with "unicode 9 widths" and one without? Do they need to rebuild `nvim` for the non-unicode-9 terminal?

**Comment by joshuarubin** [comment]
> You noted "It would have to be a build-time option". Why?

Oh, I just presumed you wouldn't want to have a new required dependency.

If you're OK having a new dependency for all builds, it could be a runtime configurable option.

> When should users choose to enable the build-time option? You mentioned "terminals that use unicode 9 widths"; what happens if a user runs nvim in two different terminals, one with "unicode 9 widths" and one without? Do they need to rebuild nvim for the non-unicode-9 terminal?

The option should be enabled if the user knows the terminal supports unicode 9 character widths and that feature is enabled.

This option should not be enabled by default (if a unicode 9 terminal could be "detected" somehow) until it has had enough time to incubate to identify potential rendering regressions it may introduce.

If it is enabled when the terminal doesn't support unicode 9 character widths, the user would see rendering issues (with emoji and other "interesting" chars) as neovim and the terminal would disagree on which characters are 1 and 2 columns wide.

It looks like vim (and neovim) have gone to some trouble to support emoji (which were officially listed as 1 col wide pre unicode 9, but most fonts displayed them as 2 col) properly. Using utf8proc and a full unicode 9 terminal should bypass the issue entirely and extend proper wide character detection beyond emoji .

**Comment by wayou** [comment]
@timfeirg I'm wondering what theme you are using for iterm2, looks cool!
