### ISSUE TITLE
CursorLine highlight isn't affected

### ISSUE THREAD

**Issue by joaopms** [neovim/neovim#5151]
- `nvim --version`: NVIM v0.1.5-683-gba70504
- Vim (version: 7.4) behaves differently? Yes
- Operating system/version: Ubuntu 16.04 Server VM via SSH on a Windows 10 Build 14393
- Terminal name/version: mintty 2.0.3 (x86_64-pc-msys) - Part of Git for Windows 2.9.2
- `$TERM`: xterm-256color
### Actual behaviour

CursorLine highlight isn't affected (stays default)
### Expected behaviour

CursorLine has a slighty brighter background, without the underline
#### Part 1
- Use this as your `init.vim`:

```
colorscheme ron
set cursorline
highlight CursorLine cterm=None ctermbg=234 ctermfg=None
```
- Open `nvim`, notice how the CursorLine still has an underline and the background didn't change
- Run `:highlight CursorLine cterm=None ctermbg=234 ctermfg=None`
- Notice the changed CursorLine highlight
#### Part 2
- Use this as your `init.vim`:

```
set cursorline
highlight CursorLine cterm=None ctermbg=234 ctermfg=None
```
- Open `nvim`, notice the changed CursorLine highlight

---

I already used Vim for some server file editing, but now I'm moving from Atom/SublimeText to Neovim, which means this issue might just be a noobie mistake.

**Comment by joaopms** [comment]
I "fixed" it with the help of [this example](https://github.com/drahosp/dotfiles/blob/324d4b957e8ea6acb6cdc758d7dcdfe94b4086b3/config/neovim#L197-L203). I'm not sure if this is supposed to be like this, so I'm not closing the issue.

**Comment by sudavid4** [comment]
hi joaopms, this fix didn't work for me, having the same problem

**Comment by P4Cu** [comment]
Hi, I've the same issue with my config. Vim takes 'highlight' option from vimrc into account but nvim does not.
As I wanted to start developing nvmi maybe that could be a task which I could take?

**Comment by justinmk** [comment]
@P4Cu sure

**Comment by P4Cu** [comment]
Funny story. I've just realised my vim also stopped to process 'highlight' correctly... after upgrade. So I've double checked (downgraded) and that's my results:

this does not work
vim 2:7.4.2156-1~ppa1~t·

does not work
NVIM v0.1.6-72-gfe06e2a
Build type: Debug
* 6e9f329 - (34 hours ago) perf: Skip foldUpdate() in insert-mode. #5299 - Shougo (origin/master, origin/HEAD)

this WORKS:
vim 2:7.4.052-1ubuntu3 -

Guess it's a vim problem then

**Comment by P4Cu** [comment]
That's the vim issue:
https://github.com/vim/vim/issues/542

**Comment by joelostblom** [comment]
Changing the highlight color of the cursorline is working as expected for me in Vim 8.0.329, but not in Nvim 0.1.7. Tested with the following:

```vim
:autocmd InsertEnter * hi CursorLine term=none cterm=none ctermbg=16 ctermfg=none
:autocmd InsertLeave * hi CursorLine term=none cterm=none ctermbg=0 ctermfg=none
```

**Comment by justinmk** [comment]
Comparing the bleeding edge of vim vs a frozen Release of nvim doesn't help.

**Comment by joelostblom** [comment]
Since this has been labelled as a Vim bug, I thought it would be helpful to know that it is actually working on Vim, at least as of version 8.0.329. The linked Vim issue is also working for me, so it seems like that bug has been fixed. I am using the packages from the Arch repos (vim-extra, neovim-community), which I don't know how they compare in terms of distance to their respective bleeding edge versions.

In any case, I was incorrect in my previous comment. I tested again (now with an empty `init.vim`, apologies for not doing that initially), and changing the highlight of the cursorline is working for me on both Vim and Nvim. Initially on Nvim, I used `set termguicolors`, but forgot to change `ctermfg` to `guifg` etc.

To be clear, the following couple of `init.vim` files both achieve highlighting of the cursorline for me on Nvim, and change the highlight color when entering and leaving insert mode.
```vim
set termguicolors
set cul
hi CursorLine guifg=red guibg=blue
autocmd InsertEnter * hi CursorLine guibg=white guifg=black
autocmd InsertLeave * hi CursorLine guibg=black guifg=white  
```

```vim
" set termguicolors
set cul
hi CursorLine ctermbg=white ctermfg=yellow
autocmd InsertEnter * hi CursorLine ctermbg=green ctermfg=yellow
autocmd InsertLeave * hi CursorLine ctermbg=yellow ctermfg=green
```
