### ISSUE TITLE
`:Man` has display problems if `gdefault` is set

### ISSUE THREAD

**Issue by telemachus** [neovim/neovim#5181]
- `nvim --version`: NVIM v0.1.5-703-g64013a5
- Vim (version: ) behaves differently? 7.3 (works correctly without formatting problems)
- Operating system/version: OS X El Capitan 10.11.6
- Terminal name/version: Same problem occurs in iTerm2 and Apple's Terminal.app
- `$TERM`: xterm-256color

### Actual behaviour

If `gdefault` is set in `init.vim` or invoked afterwards, the `Man` command has badly garbled output (see images below).

### Expected behaviour

Display of `:Man printf` should be the same regardless of the setting of `gdefault`.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:Man printf " Should look normal
:bd
:set gdefault 
:Man printf "Should look garbled
:bd
:set nogd
:Man printf " Should look normal again
```

Make sure to clear the buffer between views. Otherwise the changes to `gdefault` may appear to have no affect on the output.

Visual examples (with output of `:set gdefault?` as well)

![Clear :Man command and output of :set gdefault?](http://i.imgur.com/N01CrG0.jpg)

![Garbled :Man command and output of :set gdefault?](http://i.imgur.com/uEx5mzy.jpg)

Ping @nhooyr

**Comment by justinmk** [comment]
I thought we got rid of gdefault..

**Comment by telemachus** [comment]
@justinmk Wow. If that's a possibility, let me put in my -1. I think it's a great option to leave available to users. (And it shouldn't be too hard to script around it for plugin writers, I hope.)

**Comment by ZyX-I** [comment]
@telemachus It can be scripted around only by using `:execute` and only if plugin writer remembers that this option exists. Makes `:substitute` calls less readable. It is a horrible option for plugin writers because there already is too much cognitive load due to loads of options affecting your code and `:substitute` command is rarely or not used at all in most plugins I know.

I.e. problem is not that scripting it around is hard. It is *remembering* to script it around what is hard. And it requires the use of `:execute` which (as well as eval) is considered a bad practice for many reasons: starting from performance (not so bad in Vim with the current interpreter: there are no intermediate representations (e.g. AST or bytecode) involved) and ending with security (easier to ban `:execute` and `eval()` than to make sure that next its occurrence will introduce no vulnerabilities).

**Comment by telemachus** [comment]
@ZyX-I I understood it as an unfortunate but general rule of vim-plugins that users may have changed anything that can be set *otherwise*, so to speak. But I didn't realize that `gdefault` was especially hard to work around.
