### ISSUE TITLE
has('ruby') always returns 1

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#5238]
- `nvim --version`: v0.1.6-5-g46475a1, `neovim-ruby` 0.3.0
- Operating system/version: Arch Linux, Ubuntu Trusty
### Actual behaviour

`has('ruby')` returns 1 even if the neovim Ruby gem is not installed.
### Expected behaviour

`has('ruby')` should return 0 if the neovim Ruby gem is not installed.
### Steps to reproduce using `nvim -u NORC`

```
$ which neovim-ruby-host
neovim-ruby-host not found
$ gem list | grep neovim || echo 'none'
none
$ nvim -u NORC -c 'CheckHealth'
## Ruby provider
  - ERROR: Missing Neovim RubyGem
      - SUGGESTIONS:
        - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found
$ nvim -u NONE -i NONE --headless -c "echo has('ruby')" -c 'quit'
1
```

Ping @alexgenco.

**Comment by alexgenco** [comment]
@justinmk I believe this is expected behavior for now, yes? See this comment: https://github.com/neovim/neovim/pull/4980#issuecomment-230117373

**Comment by fwalch** [comment]
Oh, sorry, didn't see that.. as a "high-performance" solution, maybe we could just check if `neovim-ruby-host` is in PATH?

**Comment by tjdevries** [comment]
What if we added a variable to the rplugin manifest if a correctly configured executable was found for the remote host.

The variable could be something like:

```
" ruby plugins
let g:_has_ruby_provider = v:true
```
and `eval_has_provider` could check this variable. If it's not defined, then we don't have support for that remote host.

This could be generated during `:UpdateRemotePlugins` or add a new command `:UpdateRemoteHosts` (I would expect this to get run during `:UpdateRemotePlugins` as well). `:UpdateRemoteHosts` could also update the variable, so that you could update your remote host and the current neovim session's `has('host')` would return `1`.

It seems like a good place to put the variable. We could of course do a different naming scheme or use a dictionary of valid providers, whatever would be easier, but it seems like the variable would be fine.

**Comment by justinmk** [comment]
Seems reasonable for now.

**Comment by justinmk** [comment]
closed by https://github.com/neovim/neovim/pull/7944
