### ISSUE TITLE
cscope does not support the `a` option

### ISSUE THREAD

**Issue by lifepillar** [neovim/neovim#5247]
- `nvim --version`: NVIM 0.1.5
- Vim (7.4p2235) behaves differently? Yes
- Operating system/version: OS X 10.11
- Terminal name/version: Terminal.app
- `$TERM`: xterm-256color

### Actual behaviour

NeoVim raises error `E561` when `cscope find a ...` is used. It raises error `E474` when `cscopequickfix` contains `a-`. In short, Cscope's “find assignments” feature is not supported.

### Expected behaviour

`cscope find a ...` should work; `cscopequickfix` should accept `a-`, as Vim does.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set cscopequickfix=a-
:cscope add /path/to/cscope.out
:cscope find a someVar
```

**Comment by justinmk** [comment]
Was this a feature recently added to Vim?

**Comment by chrisbra** [comment]
Am 2016-08-24 16:59, schrieb Justin M. Keyes:
> Was this a feature recently added to Vim?

Yes: https://github.com/vim/vim/pull/882

**Comment by KillTheMule** [comment]
Should be easy to port.  Origins in https://github.com/vim/vim/releases/tag/v7.4.1952 as chrisbra said, then also needs https://github.com/vim/vim/releases/tag/v7.4.1990. Possibly https://github.com/vim/vim/releases/tag/v7.4.1975 should be included as well.

Since there's a request, I'd work on it tonight or so, if no one else beats me to it.

**Comment by chrisbra** [comment]
and also https://github.com/vim/vim/releases/tag/v7.4.2033

**Comment by KillTheMule** [comment]
Oh yeah, I did not see that since it does not modify `if_cscope.c`. Thanks!

**Comment by lifepillar** [comment]
Thanks!
