### ISSUE TITLE
how do you install source offline?

### ISSUE THREAD

**Issue by chagara** [neovim/neovim#5248]
helo,

I'm trying to install from the tar.gz and I'm in the step that you do ```make``` but, it looks it tries to go to github.com to download some files but, i'm using an offline pc. I'm installing in centos 7 version 0.1.2

**Comment by ZyX-I** [comment]
As usual, I would not recommend ever using top-level makefile. You basically need to

1. Install all dependencies yourself. You may find a list in third-party/CMakeLists.txt and in third-party/cmake/BuildLuarocks.cmake (latter contains a list of dependencies installed by luarocks). Some of them are optional though: jemalloc. Some are needed for testing only: luv, busted, luacheck, nvim-client, maybe something else.
2. (in Neovim repository root) `mkdir build && cd build`
3. `cmake ..`. Maybe you will need additional switches here, my development builds use

        CC=clang CFLAGS=" -O0 -g -DEXITFREE " cmake .. \
            -DMIN_LOG_LEVEL=0 \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUSTED_OUTPUT_TYPE=utf \
            -DCMAKE_INSTALL_PREFIX=$PWD/root \
            -DJEMALLOC_USE_BUNDLED=1 \
            -DCLANG_ASAN_UBSAN=ON
4. `make`.
5. `make install` (refer to your distribution’s documentation or forums regarding how to make this without “turning your system into slackware”; I personally would just use `-DCMAKE_INSTALL_PREFIX=$HOME/.local-neovim` so that “uninstalling” Neovim is as easy as`rm -rf ~/.local-neovim`).
