### ISSUE TITLE
Windows: swapfile uses wrong path

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#5255]
- `nvim --version`: 0.1.6
- Vim: no
- Operating system/version: Windows 8.1
### Actual behaviour

Calling `:swapname` prints `$LOCALAPPDATA\nvim-data\swap\\e%%BUG.swp`. Swapfiles are not written.
### Expected behaviour

?? 
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:w BUG
:swapname
```

**Comment by equalsraf** [comment]
It would seem `expand_env_esc()` sometimes fails to expand $LOCALAPPDATA.

**Comment by justinmk** [comment]
> It would seem expand_env_esc() sometimes fails to expand $LOCALAPPDATA.

Sounds related to https://github.com/neovim/neovim/pull/4964. Does reverting that fix the issue?

**Comment by equalsraf** [comment]
> Is this a regression, or it's always been like this?

At the very least it wasn't like this before the introduction of XDG.

> Sounds related to #4964. Does reverting that fix the issue?

Yes, reverting the PR causes $LOCALAPPDATA to be expanded. And swap files are written in the correct path.

**Comment by justinmk** [comment]
Is this getting setting externally (by nvim-qt?) somehow, or it's happening with just the nvim source on master?

Maybe @ZyX-I can comment.

**Comment by Mariappan** [comment]
This one was really annoying, Creating swap folders all over the place.
I tried to debug a bit. Expansion fails at 
https://github.com/Mariappan/neovim/blob/tb-fix-windows-xdg-path/src/nvim/os/env.c#L306
. 
vim_isIDc(*tail) is failing due to which it is trying to expand L, O, C, A... instead of LOCALAPPDATA

Then i saw the comment in 
https://github.com/Mariappan/neovim/blob/tb-fix-windows-xdg-path/src/nvim/option.c#L718

 /* Must be before option_expand(), because that one needs vim_isIDc() */
didset_options();

So I tried to move the set_string_default("directory", stdpaths_user_data_subpath("swap", 2, true), true)
below didset_options() which did not solve the issue.

Since I dont have developemnt environment, not able to debug further. I was (ab)using appveryor to add messages and debug. Finally added this workaround which solves the issue:

https://github.com/Mariappan/neovim/commit/6de3e7202cdb3318202f932793fac4c8e181c1c5

**Comment by equalsraf** [comment]
@Mariappan ouch that probably took a long while. I came to a similar conclusion late last night.

If we can't have environment vars in `xdg_defaults` then we can move windows initialization into `stdpaths_get_xdg_var()` which is the only function using xdg_defaults.

```diff
diff --git a/src/nvim/os/stdpaths.c b/src/nvim/os/stdpaths.c
index 10b3f4c..d50852c 100644
--- a/src/nvim/os/stdpaths.c
+++ b/src/nvim/os/stdpaths.c
@@ -16,28 +16,19 @@ static const char *xdg_env_vars[] = {
   [kXDGDataDirs] = "XDG_DATA_DIRS",
 };
 
-/// Defaults for XDGVarType values
+#ifndef WIN32
+/// Defaults for XDGVarType values in Linux, BSD, CYGWIN, Apple
 ///
 /// Used in case environment variables contain nothing. Need to be expanded.
 static const char *const xdg_defaults[] = {
-#ifdef WIN32
-  // Windows
-  [kXDGConfigHome] = "$LOCALAPPDATA",
-  [kXDGDataHome]   = "$LOCALAPPDATA",
-  [kXDGCacheHome]  = "$TEMP",
-  [kXDGRuntimeDir] = NULL,
-  [kXDGConfigDirs] = NULL,
-  [kXDGDataDirs] = NULL,
-#else
-  // Linux, BSD, CYGWIN, Apple
   [kXDGConfigHome] = "~/.config",
   [kXDGDataHome] = "~/.local/share",
   [kXDGCacheHome] = "~/.cache",
   [kXDGRuntimeDir] = NULL,
   [kXDGConfigDirs] = "/etc/xdg/",
   [kXDGDataDirs] = "/usr/local/share/:/usr/share/",
-#endif
 };
+#endif
 
 /// Return XDG variable value
 ///
@@ -48,7 +39,19 @@ char *stdpaths_get_xdg_var(const XDGVarType idx)
   FUNC_ATTR_WARN_UNUSED_RESULT
 {
   const char *const env = xdg_env_vars[idx];
+
+#ifdef WIN32
+  const char *fallback = NULL;
+  if (idx == kXDGConfigHome) {
+    fallback = os_getenv("LOCALAPPDATA");
+  } else if (idx == kXDGDataHome) {
+    fallback = os_getenv("LOCALAPPDATA");
+  } else if (idx == kXDGCacheHome) {
+    fallback = os_getenv("TEMP");
+  }
+#else
   const char *const fallback = xdg_defaults[idx];
+#endif
 
   const char *const env_val = os_getenv(env);
   char *ret = NULL;

```

I did notice while testing this patch that nvim does crash if the fallback for kXDGConfigHome is NULL. Which is possible, though unlikely. So maybe we could include your fallbacks there too, but `~` likely depends on $HOMEDRIVE(init_homedir()).

**Comment by equalsraf** [comment]
@Mariappan FWIW you can access appveyor via RDP https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

**Comment by Mariappan** [comment]
@equalsraf Thanks for the RDP information :laughing: . Somehow I am not able to connect to RDP. Anyway I need to create a development environment in VM, online or something, since I could not install MSVC in office laptop :smile:   

>  So maybe we could include your fallbacks there too, but ~ likely depends on $HOMEDRIVE(init_homedir())

Is there a chance that HOMEDRIVE will not be proper? According to the following link,
https://support.microsoft.com/en-us/kb/841343
HOMEDRIVE will be updated automatically. So it should be always available.

**Comment by equalsraf** [comment]
@Mariappan I haven't been able to to use MSVC lately either, It might be best to use MSYS2, specially because of dependencies.
