### ISSUE TITLE
functional tests for plugins/configuration bundles

### ISSUE THREAD

**Issue by cweagans** [neovim/neovim#5264]
I really like the functional testing stuff that's currently in the neovim repo (I'm looking at https://github.com/neovim/neovim/blob/6ea2bde065016d4cb2600aa2252daa83f66f09c4/test/functional/clipboard/clipboard_provider_spec.lua#L9-L21). Is there a way to use that same style/syntax for doing automated testing of plugins or other things?

My use case is that I want to write tests for specific behaviors that I want my neovim config to have and I definitely want to know if I ever break those behaviors (via including some other plugin or changing a config value or something).

I searched around quite a bit and couldn't see a straightforward way to handle this, but it looks like the functional tests are run (somehow?) after the nvim binary is built. Is there some way to do the same with my Homebrew-installed nvim?

**Comment by equalsraf** [comment]
The tests use are lua scripts executed by [busted](https://github.com/Olivine-Labs/busted). The functional tests in particular use the [lua-client](https://github.com/neovim/lua-client) to start nvim and call the API. I you check test/functional/helpers.lua, those are mostly helper functions build aroud lua-client.

Incidentally if you want this to test plugins, there is also [Vroom](https://github.com/google/vroom) - but I think I just spotted a bug in its Neovim support, probably because API changes in python-client.

**Comment by cweagans** [comment]
I know about Vroom, but it's completely broken on Mac OS (at least for me) when running against Neovim. I'll give Busted a try. Thanks!

**Comment by equalsraf** [comment]
> I know about Vroom, but it's completely broken on Mac OS (at least for me) when running against Neovim. 

I suspect vroom was actually broken with any recent version of the Neovim python-client. I did a quick test with the changes from  google/vroom#104 in Mac OS X and it seemed to be working.

**Comment by justinmk** [comment]
Spinning off the test infrastructure as a separate project would have the nice benefit of encouraging a moderate cleanup of the interface. A medium sized task that will have value for everyone. Also would be the flagship application of the remote lua client.

**Comment by lewis6991** [comment]
There now exists:

- https://github.com/lewis6991/nvim-test (closest to Nvim's test infra as it was forked from it).
- https://github.com/nvim-neotest/neotest
- https://github.com/klen/nvim-test
- https://github.com/echasnovski/mini.test
