### ISSUE TITLE
Hide the vertical split bar

### ISSUE THREAD

**Issue by code-hunger** [neovim/neovim#5275]
(removing template as this is not about a bug, it's rather a feature request)

It'd be nice to have an option to turn off the vertical bar between split windows.
I searched about this and found people saying it was impossible as it was hard-coded into vim so I thought it could happen in neovim.

**Comment by Shougo** [comment]
You can change the vertical split bar using `highlight VertSplit` feature.
I think it is no need to hide the split bar.

**Comment by justinmk** [comment]
We could "externalize" the vertical split bar as in https://github.com/neovim/neovim/pull/4432

Of course that would require major work on the layout engine, but we can file this under "api".

**Comment by bfredl** [comment]
@justinmk but that would be more or less equivalent to externalizing the entire window layout?

This is something that could be very simple (force `w_vsep_width` to zero and be done with it) but also be very complicated (because surrounding code expects the separator, what do I know). I know we don't like adding options, but if it turns out to be simple (i e more or less just exposing an internal option) why not make it a global/window-local option? (we could even make it numeric, so people could have double-width separators :P)

**Comment by justinmk** [comment]
> why not make it a global/window-local option?

If zero people use it that would be a reason for it not to exist. I am wondering if @code-hunger will not be satisfied with split windows where the text from one window is immediately adjacent to text from the next window, and will then ask for some graphical separator.

In other words, I am wondering if this request has been fully thought out. So it should be clearly specified before adding any option.

**Comment by bfredl** [comment]
I thought of usecases like [codi.vim](https://github.com/metakirby5/codi.vim). The screenshot I think makes it invisible in the color scheme, but I imagine more than zero people would like to both use that, _and_ a normal, visible, vsplit in the same instance.

> In other words, I am wondering if this request has been fully thought out. 

A way of thinking stuff out is to actually try them, rather than assuming what people will think. I'm sure there will redraw glitches in first attempt, but as I hinted the logic around `w_vsep_width` seem not terribly complicated for someone to just prototype it.

> and will then ask for some graphical separator.

Different background colors? That is something people have been asking for before. I know I would use that if it was available, though primarily for special buffers and not for avoiding split bars.

**Comment by code-hunger** [comment]
@justinmk I don't really needed it, just while exploring the `laststatus` setting I thought if it was possible to turn on/off the vertical bar.

Not sure but after thinking again I don't see if there will be any practical benefit.
Perhaps it was just a bad idea and the issue could be closed.
Your choise.

**Comment by balta2ar** [comment]
Let me chime in and say that I've always wanted to get rid of vertical split bar and I still do. My windows aways have line numbers which are very good visual separators for me on their own. Vertical bar is a waste of one character to me (I'm using console nvim, no GUIs). I wish there were a switch to turn it off.

**Comment by bfredl** [comment]
As noted by @azbshiri in #5353 (merged into this issue), an external ui could draw a vertical line between grids cells to indicate the split.

**Comment by code-hunger** [comment]
I

**Comment by code-hunger** [comment]
When I posted this issue my problem was that I had 2 vertically split windows; both had `relativenumber` and gitgutter.

I'm using the 80-column code-style, so for each window I need at least 3 (relativenumber) + 2 (gitgutter) + 80 (code) = 85 characters. 2 windows need 85 * 2 + 1 = 171 characters.
My screen contained 170 charactes. What an irony. *But it was a fact.*

So everywhere I had a 80-character long line it had either to wrap on new line or to hide on the right.
That was *very* annoying untill I got the idea to make my font a little bit smaller.

But perhaps there are users with narrower screens who can't afford a smaller font so my solution would be unacceptable.

**Comment by philix** [comment]
@code-hunger that looks like a very small thing to justify the increased complexity of yet another configuration option. Can we close the issue?

**Comment by bfredl** [comment]
Can we just leave it as "unplanned"? I though our policy was to favor general extension points over specific options whenever possible, but that doesn't  mean we should disregard feature requests because the feature happen to be naturally expressed by a specific option... (If "smart ui" (the general extension point) actually was in progress it would be another thing, of course)

While not perfectly "entry level" this seems to be kind of issue where someone with a bit C experience but maybe not very familiar with the code base could dive in and analyse all the places `w_vsep_width` are set and used. There _could_ turn out to be hard to solve edge cases but I see no reason disregard this _a priori_ because of "complexity".

**Comment by philix** [comment]
> While not perfectly "entry level" this seems to be kind of issue where someone with a bit C experience but maybe not very familiar with the code base could dive in and analyse all the places w_vsep_width are set and used. There could turn out to be hard to solve edge cases but I see no reason disregard this a priori because of "complexity".

I'm not concerned about the complexity of implementing the setting. That's low. The lifetime support, documentation, troubleshooting and interactions with other settings is where the real and always under-estimated cost of more settings is.

With that said, I will leave it as unplanned.

**Comment by code-hunger** [comment]
@philix yes; like I said I solved my problem, so it's fine to close the issue.

**Comment by cstsunfu** [comment]
Years passed. Is there anything new to this?

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/issues/33052

**Comment by JJJHolscher** [comment]
This might be out of scope, but horizontal splits are already just separable by the useful statusline.
Vertical splits have a dull bar and an optional statuscolumn (that [to some's aesthetic displeasure](https://github.com/neovim/neovim/issues/33052) only goes as far down as the buffer).
I don't know why [Chesterton](https://en.wiktionary.org/wiki/Chesterton%27s_fence) put both a bar _and_ a column in vim, but I naively think it'd be neat if there was but one.
