### ISSUE TITLE
Errors with HOME=/dev/null and `-i /dev/null`

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#5277]
I am using `HOME=/dev/null` in tests to not create any temporary data.

This fails in two places:

```
tests % HOME=/dev/null nvim -u vimrc
Error detected while processing function remote#host#LoadRemotePluginsEvent[2]..remote#host#LoadRemotePlugins[1]..<SNR>32_GetManifest[1]..<SNR>32_GetManifestPath:
line   15:
E739: Cannot create directory /dev/null: file already exists
E886: System error while opening ShaDa file /dev/null/.local/share/nvim/shada/main.shada for reading: not a directory
```

The `vimrc` file is short, and adding the plugin to be tested to the `&rtp` triggers the issue with the manifest file.

1. As for the manifest file: is this necessary, or only used for performance reasons?  In the first case, it should not be tried to be written, in the second case a temporary file should be used (and removed in the end probably).

2. For the ShaDa file: it should not be tried to be read from a non-dir location (`/dev/null`).
When using `nvim -i /dev/null`, it tries to write there in the end also (`E886: System error while opening temporary ShaDa file /dev/null.tmp.a for writing: permission denied`).

Regarding 2. there are two issues in there, depending on if you use `-i`.

**Comment by fwalch** [comment]
What about using `-i NONE`?

**Comment by blueyed** [comment]
> What about using `-i NONE`?

Yes, that helps with the ShaDa issue(s).

**Comment by tweekmonster** [comment]
I'm not an expert in all things *nix, but wouldn't setting `$HOME` to `/dev/null` be considered user error and not a problem for the program?  I think it's reasonably expected that `$HOME` points to a directory.  IMO, the error is appropriate and setting `$HOME` to `/dev/null` is being disingenuous.

> As for the manifest file: is this necessary, or only used for performance reasons? In the first case, it should not be tried to be written, in the second case a temporary file should be used (and removed in the end probably).

I don't remember the exact reason, but it might be because there were two places where the file might be written (on update and to upgrade the file location of an existing manifest).  I suppose the directories could be created when the manifest is actually written instead.  Though, the same problem would occur in the given scenario if the manifest is ever written.  If it helps, `NVIM_RPLUGIN_MANIFEST` is used for Neovim's tests.  It's taken at face value and doesn't create directories.

> For the ShaDa file: it should not be tried to be read from a non-dir location (/dev/null).
When using nvim -i /dev/null, it tries to write there in the end also (E886: System error while opening temporary ShaDa file /dev/null.tmp.a for writing: permission denied).

I think the problem is that it's trying to create a file in `/dev/` for an atomic write without permissions.  The same will happen with `nvim -i /etc/shada`.  Though not expected, I think the error message is appropriate here too.

Side note: `nvim -i /etc/shada` will segfault if the file doesn't exist because of permissions.  If it does exist (`sudo touch /etc/shada`) and is empty or has msgpack data, it will display the error you mentioned above.

**Comment by jamessan** [comment]
To summarize, I think using either `env -u HOME nvim -i NONE ...` or `env HOME=/nonexistent/dir nvim -i NONE` is the right way to achieve what you're trying to do.

I agree with @tweekmonster that the errors you're getting seem appropriate.  I think this can likely be closed, since my above suggestions should solve the issues for you.

**Comment by blueyed** [comment]
Thanks for your explanations!  Makes sense.

**Comment by blueyed** [comment]
Well.. with `env -u HOME` Neovim/Vim will still `expand()` `~/.local/share`.

The point of forcefully setting HOME here is to not interfere with any of the user's files.

**Comment by jamessan** [comment]
> Well.. with env -u HOME Neovim/Vim will still expand() ~/.local/share.

I did give two options. :) Did you try setting `HOME=/nonexistent-dir`?  This is what's also done on the Debian build daemons to catch when things try to access `$HOME`.

**Comment by tweekmonster** [comment]
> Did you try setting HOME=/nonexistent-dir?

The manifest file's directory would still be created, and `/nonexistent-dir` might cause a permission error since it starts at `/`.  `env -u HOME` won't work for the manifest since it creates `~/.local/share/nvim`.

@blueyed I still think a good partial solution would be to only create the directory when the manifest is written, but even then your tests would be based on an assumption.  I think it was mentioned that the goal is to have the manifest be self-managed.

In addition to setting `HOME`, the variables you may want to consider for tests are `XDG_CONFIG_HOME` and `XDG_DATA_HOME`; which had to be set in [RunTests.cmake](https://github.com/neovim/neovim/blob/0ade1bb7067d0cdb9b059fb66a8c4b868408be9c/cmake/RunTests.cmake#L5-L7) since they are what actually influences the files that are created (that I know of).  Your tests may still affect the user's files if those variables are in the environment, even if you set `HOME=/tmp`.  Setting `NVIM_RPLUGIN_MANIFEST=/tmp/dummy_manifest` would still be needed in case it's used by the user as well.

**Comment by blueyed** [comment]
@jamessan 
> Apparently that's already being done for nvim. Why don't you do the same for vim?

Vim is fine with HOME=/dev/null, and I've changed to using a temp dir for Neovim because of the first issue mentioned here.  The ShaDa one was a red herring: I was using `-i NONE` already.

**Comment by jamessan** [comment]
> Vim is fine with HOME=/dev/null, and I've changed to using a temp dir for Neovim because of the first issue

Vim may be fine with it, but it's not semantically correct because HOME should be a directory, not a file, if it exists.

**Comment by justinmk** [comment]
> Side note: nvim -i /etc/shada will segfault if the file doesn't exist because of permissions

fixed in https://github.com/neovim/neovim/pull/5296

**Comment by justinmk** [comment]
Is there a request here, or can this be closed?

**Comment by blueyed** [comment]
Closing, thanks again.
