### ISSUE TITLE
reltime() in Neovim is very different from Vim's

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#5301]
```
% for v in nvim vim; do echo $v; \
    $v -es --cmd 'verb echom strftime("%Y-%m-%d %H:%M:%S", reltimestr(reltime()))' \
    --cmd q; echo; done    
nvim
1970-01-02 09:26:42
vim
2016-09-05 21:59:09
```

This is used in e.g. tagbar for its debug file: https://github.com/majutsushi/tagbar/blob/7b36c46d17d57db34fdb0adac9ba6382d0bb5e66/autoload/tagbar.vim#L4069-L4072.

I wonder where Neovim's value is coming from.  The uptime of the system is "up 2 days, 18 hours, 4 minutes".

The help for `reltime()` says:

> Without an argument it returns the current time.

Possibly a related issue: https://github.com/neovim/neovim/issues/2567

**Comment by oni-link** [comment]
`current time` is not time of day. The meaning of this `current time` **depends on the system** (could be anything). The timer we use just starts at a random point in time (see src/nvim/os/time.c: os_hrtime()) and `reltime()` gives you the nanoseconds since then (in a strange format,  a 64bit number stored in two 32bit numbers).  That is okay, because `reltime()` is used to measure time differences.

**Comment by blueyed** [comment]
> current time is not time of day

That should be clarified in the docs then probably, and appears to be Neovim specific (that was discussed in #2567 already IIRC).

**Comment by justinmk** [comment]
The tagbar use seems odd. Why use nanosecond precision to display a seconds-precise timestamp?

`localtime()` is the thing to use for the current time, right?

**Comment by blueyed** [comment]
Thanks, @justinmk!
