### ISSUE TITLE
Draw a vertical line (for example; Emacs) to separate splits

### ISSUE THREAD

**Issue by azbshiri** [neovim/neovim#5353]
- `nvim --version`: NVIM 0.1.5
- Vim (version: ) behaves differently? no
- Operating system/version: Darwin Kernel Version 14.1.0
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

### Actual behaviour
Vertical splits are sperated with :set fillchars
### Expected behaviour
Vertical splits would be sperated with a drawn vertical line (for example; Emacs)
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by cloudhead** [comment]
Why is this better than `set fillchars=vert:│`?

**Comment by azbshiri** [comment]
It takes up too much space than a drawn line and if you ever seen Emacs it splits the whole window including the mode-bar (status bar) which doesn't happen in Vim and Neovim and also the space it takes is different in various OS with their font rendering engines also it's prettier.

**Comment by justinmk** [comment]
@azbshiri I guess you are comparing GUI emacs, not terminal emacs. Terminal emacs it uses a `|` char for a vertical split.

This change would require externalizing parts of the UI similar to https://github.com/neovim/neovim/pull/4432 so that Nvim GUIs can draw the split differently. 

> also the space it takes is different in various OS with their font rendering engines

To support variable-width columns would be a massive change to N/Vim and it probably will never happen. Variable-pitch fonts are one of the [main drags on emacs performance](https://github.com/neovim/neovim/issues/3508#issuecomment-187017835).

- https://lists.gnu.org/archive/html/emacs-devel/2015-12/msg00385.html
- http://debbugs.gnu.org/cgi/bugreport.cgi?bug=13675

**Comment by azbshiri** [comment]
How about just be able to change the font size of `fillchars`?

**Comment by bfredl** [comment]
You can't "just change the font size" as things are drawn on a monospace grid currently, and as @justinmk noted that will not change anytime soon. What is planned (on an indefinite time scale, I would look into it myself if I had more free time...) is to draw different windows on different (still monospace) grids, so a ui could do multi-window layout, different font size of different buffers etc.

It would be possible in the shorter term for the separator take zero grid cells, that is essentially #5275: allowing the split column to not be added, by change the `w_vsep_width` logic in `window.c`. That would be the hard part, while additionally telling the ui that "here is a vsplit between two windows, please draw a thin line between the cells" would be the "easy" part. I could be wrong of course, but given the overlap of the feature requests I will merge this into #5275.
