### ISSUE TITLE
Thai language  display not correct

### ISSUE THREAD

**Issue by wisaruty** [neovim/neovim#5403]
- `nvim 0.2.3`:
- Vim (version: ) behaves differently?
- Operating window 7:
- Terminal name/version:
- `$TERM`:

On Edit  thai language  display not correct

**Comment by brcolow** [comment]
> nvim 0.2.3

The latest nvim version is 0.1.6-dev. Furthermore the description of the bug is too sparse - what did not display correctly? What was expected? Is it different from Vim? Can you provide screenshots? Also, don't leave out your $TERM environment variable and shell environment. 

Basically: You need to provide much more information, and more accurate information.

**Comment by wisaruty** [comment]
![10-2-2016 6-47-23 pm](https://cloud.githubusercontent.com/assets/12456804/18990768/50fe05bc-873e-11e6-9e8e-f6b382d85355.jpg)

**Comment by brcolow** [comment]
And what is it supposed to look like? No spaces?

**Comment by justinmk** [comment]
Not enough information, and 0.2.3 isn't a valid version.
