### ISSUE TITLE
Incorrect parenthesis with Julia lang.

### ISSUE THREAD

**Issue by abhi18av** [neovim/neovim#5438]
- `nvim --version`: 0.1.4
- Vim (7.3: ) behaves differently?

Yes, the `/usr/local/vim` behaves as expected with Julia parenthesis
- Operating system/version: macOS Yosemite ( 10.10.5)
- Terminal name/version: iTerm 3.0.4

### Actual behaviour
The editor automatically adds a space between the `print` and the accompanying `( ` which raises syntax errors in Julia since the correct way of writing this would be `print("....") `

### Steps to reproduce using `nvim -u NORC` 

Using this the behaviour is the same as vanilla vim so i guess it's 'cos of a package.

Here are the contents of my vimrc

``` vim
set number
syntax on





call plug#begin()


Plug 'JuliaLang/julia-vim'
Plug 'neovim/node-host'
Plug 'flazz/vim-colorschemes'
Plug 'tpope/vim-speeddating'
Plug 'radenling/vim-dispatch-neovim'
Plug 'https://github.com/tpope/vim-fireplace'
Plug 'https://github.com/snoe/nvim-parinfer.js'
Plug 'guns/vim-clojure-static'
Plug 'junegunn/rainbow_parentheses.vim'
Plug 'guns/vim-clojure-highlight'
Plug 'tpope/vim-sexp-mappings-for-regular-people'
Plug 'guns/vim-sexp'
Plug 'tpope/vim-repeat'
Plug 'kassio/neoterm'
Plug 'https://github.com/Shougo/neocomplete.vim'
Plug 'terryma/vim-multiple-cursors'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'mileszs/ack.vim'
Plug 'tpope/vim-abolish'
Plug 'vim-scripts/Align'
Plug 'terryma/vim-expand-region'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'scrooloose/nerdcommenter'
Plug 'justinmk/vim-sneak'
Plug 'tpope/vim-surround'
Plug 'sjl/gundo.vim'
Plug 'godlygeek/tabular'
Plug 'wellle/targets.vim'
Plug 'maxbrunsfeld/vim-yankstack'
Plug 'vim-airline/vim-airline'
Plug 'mhinz/vim-signify'
Plug 'jceb/vim-orgmode'
Plug 'easymotion/vim-easymotion'
Plug 'ervandew/supertab'
Plug 'majutsushi/tagbar'


Plug 'rsmenon/vim-mathematica'
Plug 'petRUShka/vim-sage'
Plug 'editorconfig/editorconfig-vim'

call plug#end()


let g:mma_candy=1
let g:mma_candy=2


colorscheme kalisi
set background=dark


if exists('g:loaded_sensible') || &compatible
  finish
else
  let g:loaded_sensible = 1
endif

if has('autocmd')
  filetype plugin indent on
endif
if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif

" Use :help 'option' to see the documentation for the given option.

set autoindent
set backspace=indent,eol,start
set complete-=i
set smarttab

set nrformats-=octal

set ttimeout
set ttimeoutlen=100

set incsearch
" Use <C-L> to clear the highlighting of :set hlsearch.
if maparg('<C-L>', 'n') ==# ''
  nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
endif

set laststatus=2
set ruler
set wildmenu

if !&scrolloff
  set scrolloff=1
endif
if !&sidescrolloff
  set sidescrolloff=5
endif
set display+=lastline

if &encoding ==# 'latin1' && has('gui_running')
  set encoding=utf-8
endif

if &listchars ==# 'eol:$'
  set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
endif

if v:version > 703 || v:version == 703 && has("patch541")
  set formatoptions+=j " Delete comment character when joining commented lines
endif

if has('path_extra')
  setglobal tags-=./tags tags-=./tags; tags^=./tags;
endif

if &shell =~# 'fish$'
  set shell=/bin/bash
endif

set autoread

if &history < 1000
  set history=1000
endif
if &tabpagemax < 50
  set tabpagemax=50
endif
if !empty(&viminfo)
  set viminfo^=!
endif
set sessionoptions-=options

" Allow color schemes to do bright colors without forcing bold.
if &t_Co == 8 && $TERM !~# '^linux\|^Eterm'
  set t_Co=16
endif

" Load matchit.vim, but only if the user hasn't installed a newer version.
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime! macros/matchit.vim
endif

inoremap <C-U> <C-G>u<C-U>


```

**Comment by phanimahesh** [comment]
@abhi18av Can you please provide a _minimal_ config file that can be used to reproduce the issue? Delete anything from that config that you can, without changing the behaviour.

can you clarify if vim behaves differently with the exact same config file?

**Comment by justinmk** [comment]
Please try stackoverflow for configuration questions.

**Comment by abhi18av** [comment]
Wow, @justinmk that fast! The force is strong here :) Anyways no issues, I understand.

@phanimahesh, I did try debugging by commenting out all the s-exp plugins with no success. You think the problem is in rest of the config.

Actually, I'm quite new to come so I used the vim-sensible by tpope  https://github.com/tpope/vim-sensible

Should I report it there then, 'cos SO answers would be too advanced for a n00b (

**Comment by justinmk** [comment]
@abhi18av vim-sensible plugin is not needed in Neovim, we incorporated most of those defaults into Neovim itself: see #2676 and `:help nvim-defaults`.

**Comment by abhi18av** [comment]
Thanks @justinmk this has saved me a a lot of time! NeoVim rocks of it absorbs things like this.

I'll just experiment more with the config then)

**Comment by phanimahesh** [comment]
The project gets many issues, and this looks very much like a configuration issue, so @justinmk closed it. There's just not enough bandwidth to provide support for issues in plugins and configuration. Especially ones where we* have to look at a huge wall of plugins. Nothing personal about it.

However, people will take an interest in this if:
 - you can provide a minimal configuration, and 
 - the same configuration does something different in vim and neovim, and
 - the difference is not intended by any plugin (`has('nvim')` guards in code, for example), and
 - the difference is not by design in neovim. (Any changes by design should be documented on wiki).

hence I asked for the clarification. Yes, I think this may be a config or plugin issue.

Here's what you can do to debug this:

By the process of systematic trial and error, identify minimal config. By minimal, I mean it should only have the lines that are necessary to cause the buggy behavior. If you can remove something without affecting the behaviour, remove it.

Test it in vim and neovim to confirm that they behave differently. Report it to the plugin authors, they can debug it better than us. (usually it'll be just one or two plugins that remain in config) If it puzzles them, we'll then have something interesting.

`*I'm not affiliated or even active here, we refers to the contributors in general`

**Comment by abhi18av** [comment]
@phanimahesh, thanks! 

And actually I was able to solve it yesterday using the same thing, what @justinmk pointed about defaults was plenty helpful.

I dived into the config, remived the settings ich already were in defaults fir NeoVim. Found that `vim-sexp` was the cause for problems. Commented ut out and boom, it's awesome again :)

*It's open source man, every user is a contributor! :)
