### ISSUE TITLE
Question about compatibility with Vim

### ISSUE THREAD

**Issue by lifepillar** [neovim/neovim#5471]
Sorry if this issue has been raised before (I couldn't find anything on this specific topic).

Quoting NeoVim's home page:

>Neovim is an extension of Vim: feature-parity and backwards compatibility are high priorities.

At this point in time, this is not true. I make three examples I've stumbled upon, although there may be more differences:

1. Jobs use a different interface;
2. no lambda syntax (i.e., `{ x -> y }` syntax);
3. no `matchit` in `runtime/pack` (why, btw?).

I know that NeoVim already provides similar features (and more) and has provided them even before Vim, but watch this from a user's perspective: for example, I had to define a wrapper around `jobstart()` and `job_start()` in my vimrc. If a script lands in Vim's `runtime` using lambda syntax or jobs, it will break in NeoVim. And this is also a burden for plugin developers who aim at being compatible with both programs.

So, I'd like to know whether you are still committed to your statement, that is, such incompatibilities are just a matter of getting up to date with Vim 8 (and I am referring especially to 1. and 2. above).

(Please note that I am *not* against either course of action. This is just a request for information from a user of both Vim and NeoVim whose scripts are getting more complicated to write.)

**Comment by justinmk** [comment]
> Jobs use a different interface;

We are focusing making a better, more intuitive, more reliable jobs interface. We already have that, but we want to make it better. Spinning our wheels to match Vim's interface isn't a good use of time and it will be a poor user experience, too.

> no lambda syntax

We'll merge that in eventually.

> no matchit in runtime/pack

It's in `runtime/plugin` because we enable it by default.

> At this point in time, this is not true.

The existence of some small percentage of incompatibilities does not change the fact that Vim-compat is a high priority. If it did, it's basically "can't win" because there's always someone who takes issue with some minor difference. 

The operative comparision--and the one which Neovim project operates under--is to compare Neovim's compatibility with any other "vi-like or vim-like" editor: it's no contest. Neovim is 98% compatible. Neovim is the only editor besides Vim which runs vimscript. Neovim passes Vim's own test suite.

> If a script lands in Vim's runtime using lambda syntax or jobs, it will break in NeoVim. 

That's unlikely to happen in the next 10 years given that Vim's runtime tries to be backwards-compatible. Vim8 jobs aren't supported on Amiga, for example. And lambda syntax won't be a problem because we'll merge it sooner or later.

> And this is also a burden for plugin developers who aim at being compatible with both programs.

It's a burden caused by Vim. If Neovim suffers for it, we'll have to live with it. But I don't think it will be a big problem. Vim plugin authors have exerted [ridiculous effort](https://github.com/tpope/vim-dispatch) to work around Vim limitations. Wrapping Neovim's job API is trivial.

> So, I'd like to know whether you are still committed to your statement,

Goals and roadmap remain as written.

**Comment by lifepillar** [comment]
Thanks for the prompt, crystal-clear, response.

Re:
>Wrapping Neovim's job API is trivial.
