### ISSUE TITLE
`:new [foo-bar]` E16: Invalid range error

### ISSUE THREAD

**Issue by fszymanski** [neovim/neovim#5508]
- `nvim --version`: NVIM 0.1.5
- Vim (version: ) behaves differently? No (7.4.1989)
- Operating system/version: Fedora 25 beta
- Terminal name/version: GNOME Terminal 3.22.0, Guake Terminal 0.8.7
- `$TERM`: xterm-256color

### Actual behaviour
`:new` or `:split` with `[foo-bar]` file/buffer name pattern throws `E16: Invalid range` exception.

### Expected behaviour
Create a new window and start editing the file/buffer in it.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:new [foo-bar]
```

**Comment by jamessan** [comment]
The window is still created, with the appropriately named buffer.

Now, when you specify a file name you can include wildcards (see `:help wildcard`) and the `[foo-bar]` syntax is a recognized wildcard.  If you escape the `[`, then the `E16` doesn't happen, so some part of the wildcard handling is raising an incorrect error.

Since this also happens with Vim, it would be good to report it there.

**Comment by justinmk** [comment]
Actually this prints E16 as well:

    :echo 'foo' =~# '\v[foo-bar]'

I'm guessing Bram won't consider this a bug. Maybe `:help E16` could be clarified though.

**Comment by fszymanski** [comment]
@justinmk Thanks.
