### ISSUE TITLE
Online :help link broken for:  "|index.txt| alphabetical index of all commands"

### ISSUE THREAD

**Issue by HaleTom** [neovim/neovim#5511]
On the page:

https://neovim.io/doc/user/index.html

The link in the line
> |index.txt|	alphabetical index of all commands

returns 404. The broken target is:
https://neovim.io/doc/user/vimindex.html

**Comment by HaleTom** [comment]
Also, I note the title is:
> Vim documentation: help

I understand changing the context of the `.txt` files themselves is a mammoth task, but perhaps the HTML `title` and `h1` could say `Neovim` to confirm that it is indeed the `Neovim` documentation being viewed?

**Comment by justinmk** [comment]
@HaleTom I want to blame the first on the awk script used to generate the doc HTML, but it isn't present on http://vimdoc.sourceforge.net/htmldoc/index.html. We have a task at https://github.com/neovim/bot-ci/issues/12 to switch to  https://github.com/c4rlo/vimhelp/blob/master/vimh2h.py which generates much better results. 

Help with that would be welcome. Closing this since it's more relevant to the bot-ci project.
