### ISSUE TITLE
Syntax highlight gone after using :edit in BufWritePost autocmd

### ISSUE THREAD

**Issue by renstrom** [neovim/neovim#5579]
- `nvim --version`: v0.2.0-52-g0213e99
- Vim (version: 8.0.71) behaves differently? Yes
- Operating system/version: macOS Sierra 10.12.1
- Terminal name/version: iTerm2 v3.0.5
- `$TERM`: xterm-256color

### Actual behaviour

Buffer content refreshed *but* syntax highlighting is missing.

### Expected behaviour

Buffer content refreshed with syntax highlighting still present.

### Steps to reproduce using `nvim -u NORC`

```
$ nvim -u NORC <some file with syntax highlight>
```

```
:au! BufWritePost * silent edit!
```

Then save the file and watch the syntax highlight disappear. The background for this is I ran a program on-save (`clang-format`) that altered a file outside of Vim and just wanted to refresh my buffer, but the syntax highlighting disappears. This works as expected in Vim.

For completeness, this is basically what I wanted:

```vim
function! ClangFormat()
  call system('clang-format -i ' . expand('%:p'))
  silent edit!
endfunction

:au! BufWritePost *.c call ClangFormat()
```

**Comment by jamessan** [comment]
I'm surprised that you say it works in Vim (haven't tested), since by calling `edit` you're reloading the buffer.  The code that determines what the filetype is and what syntax highlighting to apply is triggered by an autocmd.  However, since the `edit` call is happening inside an autocmd, the code to prevent nested autocmds is probably kicking in and blocking the one to trigger syntax highlighting.

I'm not sure if replacing `edit` with `checktime` would help.

**Comment by jamessan** [comment]
Yeah, see `:help autocmd-nested`.

**Comment by renstrom** [comment]
Ah, I see. Funny how it works (or don't, depending on how you look at it) in Vim. Anyway, I guess Neovim's behaviour is correct here, so I'm gonna close this issue.

This works in Neovim:

```vim
:au! BufWritePost *.c nested call ClangFormat()
```
