### ISSUE TITLE
inccommand does not work with terminal split

### ISSUE THREAD

**Issue by raichoo** [neovim/neovim#5584]
- `nvim --version`: NVIM v0.2.0-52-g0213e99
- Vim (version: ) behaves differently? N/A
- Operating system/version: Archlinux
- Terminal name/version: GNOME Terminal 3.22.1 Using VTE version 0.46.1 +GNUTLS
- `$TERM`: gnome-256color

### Actual behaviour

Split for substition does not show up even though `inccommand` is set to `split`. So
interactive substitution as well.

### Expected behaviour

Works a in all other window configurations.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:set inccommand=split

vertial split window / open terminal in one of them
do a substitution in the non terminal window on some text

```

**Comment by justinmk** [comment]
This can be fixed by keeping the preview window open instead of closing it and depending on the "stale" screen state, which was a bit of a cheat (the same cheat that causes https://github.com/neovim/neovim/issues/4466).

Keeping the window open also fixes the unfinished task in https://github.com/neovim/neovim/pull/5561 regarding "window id" spam.

**Comment by barries** [comment]
Perfect. Thanks, @justinmk !
