### ISSUE TITLE
inccommand should highlight only within the selected range

### ISSUE THREAD

**Issue by scampi** [neovim/neovim#5598]
- `nvim --version`:

```
NVIM v0.2.0-52-g0213e99
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/build/config -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/src -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/build/src/nvim/auto -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/build/include
Compiled by yfful@troy

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Operating system/version: Linux troy 4.8.6-2-ck #1 SMP PREEMPT Fri Nov 4 22:25:35 EDT 2016 x86_64 GNU/Linux
- Terminal name/version: XTerm(327)
- `$TERM`: xterm-256color

### Actual behaviour

- select a range of text in visual mode (tested with `V`)
- type `:'<,'>s/foo`
- every matches of `foo` are highlighted.

### Expected behaviour

Only the matches within the selected range should be highlighted.

### Steps to reproduce using `nvim -u NORC +'set icm=nosplit'`

- Test file:

```
foo1
foo2
foo3
foo4
foo5
foo6
```

- Steps:

```vim
nvim -u NORC +'set icm=nosplit'
Vjj " select two lines
:'<,'>s/foo " all six matches are highlighted, but should be only the first two
```

**Comment by tssm** [comment]
I guess you already know it but just in case `:s/foo/bar` also highlights every matches of foo.

**Comment by KillTheMule** [comment]
I can fix this, but there's a tradeoff. Look here: https://imgur.com/a/xwbp0. While it all looks the same the 'X's are highlighted by the inccomand code (as the result of a substitution), while the 'a's are highlighted by the search highlighting code, which is enabled by the substitution command.

Now, to fix the issue above we'd need to disable search highlighting (that's what's causing it) temporarily, and do our own. Now our own highlighting would be the correct thing while typing the match (i.e. as above `s/foo`). But once you're typing the substitution (i.e. you have a second slash) and the global option is not set (either by virtue of gdefault or ending the command in `/g` or having the flag from a previous substitution), the above image would change so that the 'X's are still highlighted, but the 'a's won't be.

At least, that's what I think would be feasible. Fixing the issue above *and* having the 'a's highlighted will be a lot of work (both in producing the code, and in actually running it during a substitution), so I'm shying away from that.

Any opinions?

**Comment by justinmk** [comment]
> Now, to fix the issue above we'd need to disable search highlighting (that's what's causing it) temporarily, and do our own

@KillTheMule Could the 'incsearch' logic be changed to limit itself to the range? To start with, could add 2 new globals (next to `search_match_lines`) to store the start/end lines. Then in `win_line()`, check `(State & CMDPREVIEW)` and skip `next_search_hl()` if `lnum` is outside of that range. This should be a total of 10-20 lines of code.

OTOH it is _crazy_ how much code in screen.c exists just for 'incsearch'.

**Comment by KillTheMule** [comment]
I don't know, I have never looked at the incsearch code. I'd investigate, but only after I finished the multiline stuff.

There's another optione mentioned by bfredl, I'll put it in the post above.

**Comment by KillTheMule** [comment]
I've found another problem with the way we currently do it: https://imgur.com/a/6UvYl. Restricting incsearch to certain line numbers won't help here... 

Would it be possible to disable search highlighting for the preview buffer only? Doing out own highlighting there will be easy. Otoh that would mean a disconnect between the search results in the original buffer and in the preview buffer.

My take is still (or again...) that we should do our own highlighting, but not highlight the 'a's from the example above.
