### ISSUE TITLE
inccommand: hl-Substitute remains after substitution is completed

### ISSUE THREAD

**Issue by tssm** [neovim/neovim#5629]
- `nvim --version`:
```
NVIM v0.2.0-97-gacbce46
Build type: Dev
Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161118-1338-uh65lo/build/config -I/tmp/neovim-20161118-1338-uh65lo/src -I/tmp/neovim-20161118-1338-uh65lo/deps-build/usr/include -I/tmp/neovim-20161118-1338-uh65lo/deps-build/usr/include -I/tmp/neovim-20161118-1338-uh65lo/deps-build/usr/include -I/tmp/neovim-20161118-1338-uh65lo/deps-build/usr/include -I/tmp/neovim-20161118-1338-uh65lo/deps-build/usr/include -I/tmp/neovim-20161118-1338-uh65lo/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161118-1338-uh65lo/build/src/nvim/auto -I/tmp/neovim-20161118-1338-uh65lo/build/include

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
```

- Operating system/version: OS X El Capitan (10.11.6)
- Terminal name/version: iTerm2 3.0.12
- `$TERM`: xterm-256color

### Actual behaviour

The matching pattern remains highlighted after the substitution on a line or range was accepted.

### Expected behaviour

Matching pattern shouldn't remain highlighted.

### Steps to reproduce using `nvim -u NORC`

test.vim:
```
highlight Substitute cterm=NONE ctermfg=black ctermbg=9
set inccommand=nosplit
```
test.txt:
```
foo
bar
foo2
bar2
foo3
bar3
foo4
bar4
```
Steps:
```
nvim -u test.vim test.txt
:s/foo/bar<cr>
```

**Comment by justinmk** [comment]
Can't reproduce this on master. Do you mean the `Search` pattern? `Substitute` only appears during preview, for me.

**Comment by tssm** [comment]
I'm going to try to compile master using Nix, but in the current version (0.2.0) if I have something like:

```
onepattern
otherpattern
onepattern again
```

And I'm on the first line and execute `:s/onepattern/whatever` then in the third line `onepattern` is still highlighted, for example in this screenshot I executed `:s/last/lala` while on the seventh line:

<img width="1440" alt="screen shot 2017-10-31 at 09 26 45" src="https://user-images.githubusercontent.com/1188977/32223812-b92da0d6-be1d-11e7-9f91-e11baa8f512e.png">

**Comment by KillTheMule** [comment]
That's expected, you're having `hls` set, and that does that last highlighting. Substitution also sets the search buffer, this is why you still see that highlighting.

What we do is disable `hls` during incsub, and do our own highlighting. After we're done, we restore your `hls` setting, and in that moment nvim realizes the search buffer isn't empty and highlights the matches.

As far as I can see, that's the behavior we want. It's exactly the same thing if you're doing a 'normal' substitution (`icm=`), and i don't see any alternative. We really need to restore `hls` after the incsub, and we really don't want to clear the search buffer after incsub. We could do some shenningans like calling `set nohls` which temporarily disables the highlight, but as I said, this is surprising since it deviates from the way nvim behaves with 'normal' substitution.

I'd say, leave it like that.

**Comment by justinmk** [comment]
> And I'm on the first line and execute :s/onepattern/whatever then in the third line onepattern is still highlighted, 

If by "execute" you mean "hit enter" to apply the `:s`, then that's by design of 'hlsearch' option.
