### ISSUE TITLE
Enable -Wconversion file by file

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#567]
As illustrated here: https://github.com/tarruda/neovim/commit/86ea80dbd3b2a704c897e02d1d6ed8f01b92c96b#commitcomment-5984214 it often easy to make mistakes like assigning a variable of a wider type to a variable of a smaller type (`size_t` to `uint32_t` for example). The compiler doesn't warn about this without the `-Wconversion` flag. (in this case it wouldn't have warned even with the flag on on travis, which is 32-bits, but it would warn for anyone with a 64-bits OS, where `size_t` is usually 64-bits wide).

Sadly, the vim/neovim codebase has a lot (1000s of warnings) of things like this, and I'd wager that 99% of these assignments and over-casting are not really a problem (vim seems to be rather stable and works on a lot of platforms), but it's a class of issues that's easy to detect before they even take hold.

Since it's unfeasible for one person to do all this work on him/herself, it was proposed that this would be done on a file by file basis. With the workflow like this:
1. Create a branch
2. Enable `-Wconversion` for a file and fix the resulting warnings (1 commit)
3. Find another file that doesn't have `-Wconversion` enabled yet and goto 2 as long as you feel like it
4. Send PR

Also: any new files should be `-Wconversion` checked from the beginning.

Any takers just inform the rest of the team here!

@jszakmeister will hopefully be able to conjure up the groundwork for file-by-file enabling of certain flags once he's back from vacation :).

**Comment by Numkil** [comment]
So I had enabled -Wconversion for ui.c and did not get a single warning. Could any1 confirm this? It seems fishy

**Comment by elmart** [comment]
That is already done at https://github.com/neovim/neovim/pull/1979.
When I did it, there was a single warning. Now, after changes in #1820, no warning remains (I've maintained a little variable refactoring I had done, anyway).

**Comment by Numkil** [comment]
K thanks for warning me, it's hard checking every single pr and commit for stuff that might have been done already when you are trying to get your feet wet in a project like this.

**Comment by elmart** [comment]
No worries. :-)
After some time you will know which keywords to search for (-Wconversion is this case).

**Comment by Numkil** [comment]
I have taken a look at popupmenu.c, I don't think any1 has already

**Comment by Ragnis** [comment]
I'll be taking tag.c; it seems no-one has done it yet.

**Comment by glindste** [comment]
I'll take a look at if_cscope.c, looks like it's unclaimed.

**Comment by justinmk** [comment]
@glindste :+1:

**Comment by codonnell** [comment]
I'll take a look at charset.c.

**Comment by wreed4** [comment]
Hi all!

This is my first time contributing to an open source project.  Also my first time using Git for large-scale collaboration. So please feel free to yell at me if I'm doing anything wrong! :)

I am super excited about neovim and would like to help out.  This issue seemed like a good place to start.  

So, my understanding is that I should notify everyone that I'm looking into this, so that's what I'm doing now :).  

Thanks! and super excited to start working on this.

**Comment by splinterofchaos** [comment]
Thanks for your interest, @wreed4! Please also let us know what file(s) you intend to work on, either by posting here or opening a PR prefixed with `[WIP]` and referencing this issue.

**Comment by wjh** [comment]
At the top of pos.h, column/line number types are defined as being signed. Now, I was working on enabling -Wconversion in misc1.c and came across a comparison between unsigned and a column, which threw a warning. I could fix this with a cast, but I'm trying to avoid that.

I was wondering, would it be safe to change the line number/column types to being unsigned? It would make sense that they are never negative, but I guess with a codebase this huge anything is possible really.

**Comment by bfredl** [comment]
@wjh arguably it is wrong as well, as one should be able to take the difference between two lines without first converting _both_ linenrs to signed (remember, unsigned is a stronger type in C than signed)

**Comment by phanimahesh** [comment]
Can we have a wiki page with all files and the status of -Wconversion on them? It will make it easier to identify which files need work at a glance, and to track progress centrally. It also minimizes the chance of multiple people working on the same file, duplicating the work. Searching this issue is not exactly easy.

I'll create the page if it is okay. My plan is to take recursive listing and convert it into a checklist, and then tick off any files with the flag already enabled. Anyone starting to work will add their name and PR against the file name in the wiki.

**Comment by Antoine-H** [comment]
Hey I have worked on charset.c, just opened a pull request https://github.com/neovim/neovim/issues/567
