### ISSUE TITLE
mobile help

### ISSUE THREAD

**Issue by natebass** [neovim/neovim#5680]
A better ```:help``` format for small screens.

Ideas: [gist.github.com/natebass/fe1744b2a38fdf8f31b083d5025177f9](https://gist.github.com/natebass/fe1744b2a38fdf8f31b083d5025177f9)

**Comment by justinmk** [comment]
> I am going to try and implement this as a language, as described in :h help-translated.

Seems like a clever idea. The process should be automated though, so that the narrow version can be regenerated from the up-to-date documentation by the build system.

**Comment by justinmk** [comment]
Since https://github.com/neovim/doc/pull/27 , various help docs HTML pages are now generated with "flow" (non-fixed-width) layout: https://github.com/neovim/neovim/blob/dcf8a71b85d248a76f013afb67ff54c42697e6c1/scripts/gen_help_html.lua#L42-L48

Also even legacy fixed-width docs have "flow" behavior wherever the parser finds a "list".
