### ISSUE TITLE
Setting clipboard+=unnamed, but v:register keep " until first yanked

### ISSUE THREAD

**Issue by pocari** [neovim/neovim#5697]
- `nvim --version`: NVIM v0.2.0-1-g9956bee
- Vim (version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 20 2016 09:29:19)) behaves differently? yes
- Operating system/version: macOS/el capitain(10.11.6)
- Terminal name/version: iTerm2 3.0.12
- `$TERM`: xterm-256color

### Actual behaviour
there is "set clipboard+=unnamed" in _vimrc, but v:register returns `"` until first yanked.
 
### Expected behaviour
v:register returns `*`

### Steps to reproduce using `nvim -u NORC`

In neovim

```
% cat vimrc_test
set clipboard+=unnamed

% nvim -u vimrc_test
:echo v:register
=> returns "
:yy
:echo v:register
=> return *

```

Strangely , `set clipboard` after nvim started, it's works.
```
% nvim -u NORC
:set clipboard+=unnamed
:echo v:register
=> returns *
```

In macvim

```
% /Applications/MacVim.app/Contents/MacOS/Vim -u vimrc_test
:echo v:register
=> returns *
```

**Comment by justinmk** [comment]
I fail to see why this is a problem.

**Comment by bfredl** [comment]
> I fail to see why this is a problem.

This will be an issue with plugins that wraps clipboard/register functionality. In a mapping `v:register` is the only way to check a preceeding `"x`. Because vim, it is impossible to see if the map was invoked without any `"x` (for instance by making `v:register` then the empty string, like our`v:event.regname`) rather `v:register` will then be `"` or `*` depending on `&clipboard`. Such a plugin will yank/put the wrong register if it is the first thing that is invoked after startup. 

It is because we only `set_reg_var(get_default_register_name())` in `normal_finish_command`, (which also handles option setting, events etc _at runtime_, but not startup). It must be done also when normal mode is entered first time after startup.

**Comment by pocari** [comment]
> Such a plugin will yank/put the wrong register if it is the first thing that is invoked after startup.

I am in trouble with it.
