### ISSUE TITLE
arch: migrate to "mpack", remove "msgpack"

### ISSUE THREAD

**Issue by vext01** [neovim/neovim#5724]
Hi,

We were discussing in #neovim irc, how neovim uses both mpack and msgpack libraries, and that it could just use one. I don't know the ins and outs of the two libraries, but it would certainly make porting easier to have fewer dependencies.

Thanks.

**Comment by justinmk** [comment]
Let's try to switch to libmpack for 0.3. cc @tarruda

**Comment by tarruda** [comment]
Switching neovim to use libmpack was one of my goals when I first started developing it, but I ended up not finding time to focus on this task :(

This will require a bit of refactoring to the RPC modules since libmpack will directly create neovim types. In the end we'll probably have shorter and more efficient code.

I will try to have a look at this later today.

**Comment by justinmk** [comment]
@tarruda Pinged you just as a "heads up" in case you knew of any reason we should _not_ commit to libmpack.

**Comment by maisiliym** [comment]
There *may* be some work done on this. Are there any dusty, old branches laying around?

**Comment by clason** [comment]
Closed by #15566 🎉
