### ISSUE TITLE
Lots of QB failures under Linux...

### ISSUE THREAD

**Issue by jszakmeister** [neovim/neovim#5727]
It looks like the last 30 builds or so for PRs and a number on master have been failing for a while now in the "jobs running tty-test program calling jobclose()" test:

```text
test/functional/core/job_spec.lua @ 484
Failure message: test/functional/core/job_spec.lua:487: Expected objects to be the same.
Passed in:
(table) {
[1] = 'notification'
[2] = 'exit'
*[3] = {
[1] = 0
*[2] = 0 } }
Expected:
(table) {
[1] = 'notification'
[2] = 'exit'
*[3] = {
[1] = 0
*[2] = 1 } }
stack traceback:
test/functional/core/job_spec.lua:487: in function <test/functional/core/job_spec.lua:484>
```

I don't know if it's because the test is racy or if there is something else unexpected happening here.  It appears that this started happening with #5624 (http://neovim-qb.szakmeister.net/build/9323/github).

**Comment by bfredl** [comment]
Hmm, it seems inconsistent whether killing a process with SIGHUP ( the tty-test doesn't catch or ignore SIGHUP) exits it with 1 or 0. I wonder if it is different on different systems or there is some racyness (If libuv somehow affects the result). The quick fix could be to allow both 0 or 1, or maybe we should try with, say, `cat` instead of tty-test.

**Comment by justinmk** [comment]
@bfredl Is the exit code important for that test?

**Comment by justinmk** [comment]
We are handling `SIGWINCH` in tty-test, could we add a handler for SIGHUP and return a consistent error code.

**Comment by bfredl** [comment]
yes we could, but maybe it simpler with trying with `cat` first. I wound assume the default exit code for SIGHUP to be consistent according to POSIX standard, and maybe `uv_tty` module is affecting SIGHUP.

**Comment by justinmk** [comment]
Added SIGHUP handling to https://github.com/neovim/neovim/pull/5488 in https://github.com/neovim/neovim/pull/5488/commits/cdab06aaa0e78d3037ee48807c9b00072aa064dd. But it's still returning `0`, not `1`.

This is because `main()` exits before SIGHUP is handled. Adding a infinite `while(1);` loop before the end of `main()` lets the test pass.

**Comment by bfredl** [comment]
Hmm, so a tty child has a small time slot between stdin is closed (so that the event loop waiting only on stdin will exit?) and SIGHUP actually is received? Then I guess `sleep()` would be the simplest.
