### ISSUE TITLE
"set exrc" not working

### ISSUE THREAD

**Issue by Pieter-Jan** [neovim/neovim#5784]
In neovim when I add "set exrc" to the end of my .vimrc file, local project .vimrc files are not picked up. In normal vim, this is working.

**Comment by tweekmonster** [comment]
That's because neovim is looking for `.nvimrc`.  See `:h 'exrc'`.  If you want to continue using `.vimrc`, consider using this plugin: https://github.com/MarcWeber/vim-addon-local-vimrc

**Comment by Pieter-Jan** [comment]
ah you are right ... the decision not to use .vimrc saddens me every time

**Comment by justinmk** [comment]
I suppose we could use .vimrc for this case.

**Comment by przepompownia** [comment]
Currently I have to keep `.nvimrc` linked to `.vimrc` if I do not want to install the `vim-addon-local-vimrc`. Additionally, this issue was the first search result with the explanation why my `.vimrc` is not processed with enabled `exrc` option. [Neovim documentation](https://github.com/neovim/doc/blob/gh-pages/user/options.html#L2400) needs to be updated for `exrc` (`secure` tells about `.nvimrc`).

**Comment by justinmk** [comment]
Ignoring the giant warning in Vim's latest help that 'exrc' should not be used, all we need is a patch...

**Comment by xals** [comment]
Actually, I use `exrc` and `secure` options to be able to define a session name in $PROJECT/.exrc (which is the same for vim and neovim).

**Comment by justinmk** [comment]
@xals You could use an autocmd instead, as explained in `:help 'exrc'`.

**Comment by justinmk** [comment]
'exrc' option is deprecated in https://github.com/neovim/neovim/pull/10177. You should not use it. 

The recent `2019-12735` 'modeline'  vulnerability should make it clear why this feature sucks (it is even worse that 'modeline'):

- https://github.com/numirias/security/blob/master/doc/2019-06-04_ace-vim-neovim.md
- https://nvd.nist.gov/vuln/detail/CVE-2019-12735
- https://access.redhat.com/security/cve/cve-2019-12735
