### ISSUE TITLE
Remote plugin autocmds don't load initially

### ISSUE THREAD

**Issue by alexgenco** [neovim/neovim#5821]
- `nvim --version`: NVIM v0.2.0-149-gaa4ef89
- Vim (version: ) behaves differently? n/a (no remote plugins)
- Operating system/version: OSX 10.11.6
- Terminal name/version: iTerm2 Build 3.0.13
- `$TERM`: xterm-256color

### Actual behaviour

With a remote plugin that defines an autocmd via the rplugin API (tested on Ruby and Python), the autocmd only triggers after a remote plugin function or command is called first.

### Expected behaviour

The autocmd triggers even when no other remote plugin commands or functions have yet been called.

### Steps to reproduce using `nvim -u NORC`

1. Add the following remote plugin:

```ruby
# ~/.config/nvim/rplugin/ruby/plug.rb
Neovim.plugin do |p|
  p.function(:Hi) do |nvim|
    nvim.command("echom 'hi'")
  end

  p.autocmd(:BufEnter, :pattern => "*.rb") do |nvim|
    nvim.command("echom 'ruby!'")
  end
end
```

2. Load plugins with `nvim +UpdateRemotePlugins`.

3. Loading `nvim foo.rb` doesn't output `ruby!`. However, if you call `call Hi()` first, and then `:e foo.rb`, it works as expected.

This was reported on neovim-ruby a while ago and I just got around to reproducing: https://github.com/alexgenco/neovim-ruby/issues/24

**Comment by mhinz** [comment]
@alexgenco I guess it should be `nvim +UpdateRemotePlugins +q` in the second step, eh?

If so, I can't reproduce it with neither v0.1.7 nor master. I get the expected `ruby!` message on `nvim foo.rb`.

```vim
" ~/.local/share/nvim/rplugin.vim
call remote#host#RegisterPlugin('ruby', '/Users/mhi/.vim/rplugin/ruby/plug.rb', [
      \ {'sync': v:false, 'name': 'Hi', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'BufEnter', 'type': 'autocmd', 'opts': {'pattern': '*.rb'}},
     \ ])
```

```vim
" ':au BufEnter' snippet
RPC_DEFINE_AUTOCMD_GROUP_4  BufEnter
    *.rb      call remote#define#AutocmdBootstrap("ruby", "/Users/mhi/.vim/rplugin/ruby/plug.rb:autocmd:BufEnter:*.rb",
v:false, "BufEnter", {'group': 'RPC_DEFINE_AUTOCMD_GROUP_4', 'pattern': '*.rb'}, "\"doau RPC_DEFINE_AUTOCMD_GROUP_4 BufE
nter \".expand(\"<amatch>\")")
```

**Comment by chemzqm** [comment]
Not a bug, restart is required whenever the generated file changes

**Comment by mhinz** [comment]
> Is something in your startup eagerly loading remote plugins?

You're right. Unfortunately I can't say what it is exactly. It has to do with autoloading, though. Sourcing `rplugin.vim` and `autoload/remote/define.vim` (which defines the autocmds for `RPC_DEFINE_AUTOCMD_GROUP_*`) happens when one of my plugins calls an autoload function. But even when I put `return` in the first line of the called function, move the function to the top of the file, and put a `finish` after it, it still happens. Basically no code is run, just the sourcing of the autoload file itself seems to trigger it.

This seems to be another bug to me. I see no reason why calling an empty autoload function should trigger sourcing `rplugin.vim` and `autoload/remote/define.vim`.

This itself seems to be another bug, though.

---

I have to read up exactly on how all this stuff works. My guess it's a bit too smart for its own good and simply tries to defer sourcing until certain things happen.

**Comment by chemzqm** [comment]
@mhinz here is the magic:
``` vim
augroup nvim-rplugin
  autocmd!
  autocmd FuncUndefined *
        \ call remote#host#LoadRemotePluginsEvent(
        \   'FuncUndefined', expand('<amatch>'))
  autocmd CmdUndefined *
        \ call remote#host#LoadRemotePluginsEvent(
        \   'CmdUndefined', expand('<amatch>'))
augroup END
```
at `runtime/plugin/rplugin.vim`, so the command regsit would happen when any command/function is missing.

I think it's over optimized, the regist is just souce the file `rplugin.vim` and it takes no more than `3ms` on my machine, it should be run only once on vim startup  IMO.

**Comment by mhinz** [comment]
Ah, I see. This explains why it also happens for normal autoload functions, because then functions aren't defined as well. Then again I'm not sure how to work around that, since rplugins can surely add autoload functions, too.

> I think it's over optimized, the regist is just souce the file rplugin.vim and it takes no more than 3ms on my machine, it should be run only once on vim startup IMO.

Sounds reasonable to me, but others have more insight about this particular code than I do. ;-)

What do you think, @neovim/core?

**Comment by chemzqm** [comment]
I've tried setting `$NVIM_RPLUGIN_MANIFEST`, the souring time for `rplugin.vim` is less than `2ms` now (regist 18 functions/commands)

**Comment by garyburd** [comment]
Autocomplete on command and function names is also broken by this optimization.

**Comment by chemzqm** [comment]
@garyburd the autocomplete is actually related to another optimization.

The completion only works after the command/function is defined, the call to `LoadRemotePlugins ` would result in call to `remote#host#RegisterPlugin` but this function just regist some definition to some variable, the actual code of remote plugin is not runned.

The call to `remote#host#LoadRemotePluginsEvent` would trigger another `FuncUndefined/CmdUndefined` command, and then the autocmd registered by `remote#host#RegisterPlugin` would fired and related autocmd//command/function would be actually defined and get called.  User would only have the completion works after the command/function defined.

This optimization is needed to make vim start fast, since the start of a remote host would cost hundreds of milliseconds.

**Comment by garyburd** [comment]
@chemzqm I don't understand why the issue with command and function completion is related to a different  optimization than the one in rplugin.vim. The call to `remote#host#LoadRemotePlugins` creates bootstrap commands and functions for all remote plugin commands and functions.  Completion on command and function names works after the bootstrap commands and functions are created.

**Comment by chemzqm** [comment]
@garyburd the command part works just as what you said, it defined in `define.vim` like this:

``` vim
  exe s:GetCommandPrefix(a:name, a:opts)
        \ .' call remote#define#CommandBootstrap("'.a:host.'"'
        \ .                                ', "'.a:method.'"'
        \ .                                ', '.string(a:sync)
        \ .                                ', "'.a:name.'"'
        \ .                                ', '.string(a:opts).''
        \ .                                ', "'.join(forward_args, '').'"'
        \ .                                ')'
```
A one time command is created but not called, so we can get command completion.

But the function part not, it defines like this:

``` vim
function! remote#define#FunctionOnHost(host, method, sync, name, opts)
  let group = s:GetNextAutocmdGroup()
  exe 'autocmd! '.group.' FuncUndefined '.a:name
        \ .' call remote#define#FunctionBootstrap("'.a:host.'"'
        \ .                                 ', "'.a:method.'"'
        \ .                                 ', '.string(a:sync)
        \ .                                 ', "'.a:name.'"'
        \ .                                 ', '.string(a:opts)
        \ .                                 ', "'.group.'"'
        \ .                                 ')'
endfunction
```
It relies on `FuncUndefined` autocmd to trigger the bootstrap, it looks we can create a one time function like command for bootstrap instead of rely on `FuncUndefined`, so we get the completion for function.

**Comment by justinmk** [comment]
Does #5856 fix this issue?

**Comment by chemzqm** [comment]
@justinmk No, they're different issues.
The problem of this issuse is caused by the regist functions only get called when a undefined function or autocmd get triggered, so the autocmd could be missed.
The code of this comment https://github.com/neovim/neovim/issues/5821#issuecomment-270688157 could fix this issue, I've been working with that code for some time and it works well.

**Comment by alexgenco** [comment]
It seems like it's partially fixed, as `:e foo.rb` now hooks into the rplugin without calling another rplugin function first (that might have been the behavior before, can't quite remember). However launching with `nvim foo.rb` still doesn't activate the rplugin. Also worth noting that this is the current behavior on master as well.
