### ISSUE TITLE
Python f-string syntax highlighting

### ISSUE THREAD

**Issue by carlwgeorge** [neovim/neovim#5943]
- `nvim --version`:
```
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
```
- Operating system/version: Arch Linux
- Terminal name/version: gnome-terminal 3.22.1
- `$TERM`: xterm-256color

### Actual behaviour
Python 3.6 includes a new feature called [formatted string literals (f-strings)](https://docs.python.org/3.6/whatsnew/3.6.html#pep-498-formatted-string-literals).  It is fantastic.  However, nvim, [like most other editors](https://twitter.com/raymondh/status/819085176764366848), does not yet perform syntax highlighting in between the brackets inside an f-string.

### Expected behaviour
Nvim gains the feature of properly highlighting Python code (variables, operators, etc) within the brackets of an f-string.  For a visual example, check out this screenshot of pycharm:

![pycharm python36](https://www.jetbrains.com/pycharm/whatsnew/img/2016.3/python36.png)

**Comment by justinmk** [comment]
Thanks for the report! 

This feature is determined by the Vim "runtime" files, in this case `syntax/python.vim`. We don't want to fork the Vim runtime plugins in most cases (especially syntax plugins), unless there's a very good reason. Because if Vim changes something in the same file, it takes time to figure out the differences.

Please send this report to the maintainer, listed at the top of the file:  `syntax/python.vim`

Also report to https://github.com/vim/vim, mentioning that you already reported to the maintainer.
