### ISSUE TITLE
CI: problem with Tab converted into space in screen.lua

### ISSUE THREAD

**Issue by teto** [neovim/neovim#5982]
I am trying to convert some tests to neovim style (currently the '045_folding_spec' one) and I have nearly finished except for one test that fails due to some tabs being converted to space I think (but I am not sure yet as I could not find the cause).

### Actual behaviour
Here is a simple test:
```
it('simple test', function()
    r2=[[
    	toto
    test ]]
    print("R2\n"..helpers.dedent(r2))
    execute('set noai nosta ')
    insert(r2)
    execute('')
    screen:snapshot_util()
  end)
```
Right before toto, there is `<Tab>` character but `snapshot_util` displays spaces instead, which is why my test fail IMO. I tried to investigate where the conversion happens but I couldn't find where.

Bonus question: is there a helper to check a block of text is present in the buffer content (lie screen:expect(any=True) but on the whole buffer and not just the displayed screen ?

**Comment by justinmk** [comment]
There are existing tests with tab characters, so that's unlikely to be the problem. What matters is that the leading indentation is the same. Or to make things simpler, don't indent at all:

```
local r2=[[
	toto
test]]
```

- Reminder to use `local` for all local variables in lua.
- There's a space after `test` (`test ]]`), was that intentional?

> is there a helper to check a block of text is present in the buffer content (lie screen:expect(any=True)

Screen test isn't needed for that, just use the normal helper functions (e.g. ``helpers.eval()`). There's also `helpers.expect()` which checks the entire contents of the current buffer.
