### ISSUE TITLE
`clipboard+=html` on Windows

### ISSUE THREAD

**Issue by mmikeww** [neovim/neovim#6013]
It would be nice if `set clipboard^=html` worked on Windows

http://vimhelp.appspot.com/options.txt.html#clipboard-html
^ that says GTK only

http://stackoverflow.com/questions/9777862/pasting-styled-text-from-system-clipboard

When you `CTRL+C` to copy from a webpage on Windows, 2 different formats are saved in the clipboard: a plaintext version is copied, as well as the HTML code representing the formatted text. This is how you can copy from a webpage, and paste into Word or Outlook or even a Gmail msg and you get the formatted HTML. 

As I understand it, the target application of the paste (in this case Vim) would need to enum the different formats inside the clipboard, and choose the appropriate one. So if `clipboard=html` is present, then `"*p` would use the HTML version of the clipboard contents instead of the plaintext

**Comment by equalsraf** [comment]
Switching to a provider that can get the right clipboard should fix this.

I don't think there is a way to currently switch clipboard providers at runtime, or to influence the current provider in general. I assume the only method to afect the current provider after startup is using environment variables.

For now the only available provider for windows is [win32yank](https://github.com/equalsraf/win32yank). I would not object to a patch to support this :D, but I confess I'm having issues finding a normative reference other than https://blogs.msdn.microsoft.com/jmstall/2007/01/21/copying-html-on-the-clipboard/

BTW this issue is not windows specific since clipboard=html works fine in X11, and the X11 clipboard does support other mimetypes.

**Comment by mmikeww** [comment]
Yeah that link looks about right, except the link to his code is now dead. 

Here are a few other resources:

https://support.microsoft.com/en-us/help/274308/how-to-add-html-code-to-the-clipboard-by-using-visual-c

https://msdn.microsoft.com/en-us/library/aa767917.aspx

http://code.activestate.com/recipes/474121-getting-html-from-the-windows-clipboard/

I guess when yanking/deleting to the `"*` or `"+` registers, you'd also need to generate the header and put the HTML into the windows clipboard as well, when this `clipboard=html` option is on

**Comment by mmikeww** [comment]
There's also this:

https://github.com/hluk/CopyQ

**Comment by justinmk** [comment]
Can be done in a plugin. Out of scope for core.
