### ISSUE TITLE
crash with TERM=dumb

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#6025]
- `nvim --version`: NVIM 0.2.0-dev
- Vim (version: ) behaves differently? yes, does not crash
- Operating system/version: macOS 10.12.2, I also reproduced on nixOS (linux distro)
- Terminal name/version: iTerm 3.0.13
- `$TERM`: xterm-256color

### Actual behaviour
`env TERM=dumb nvim` and neovim segfaults

Watch https://asciinema.org/a/e98gikeaptd4gs7iwi0dpvxfq

Error is
`fish: Job 1, 'env TERM=dumb nvim -u NORC' terminated by signal SIGSEGV (Address boundary error)`

### Expected behaviour
Should not segfault

**Comment by nhooyr** [comment]
Obviously `TERM=dumb` is not something that should really be set, but I don't think neovim should not segfault.

**Comment by justinmk** [comment]
This is a very old bug, I thought it was already fixed. https://github.com/neovim/neovim/issues/3471

Should be easy to (1) fix it or (2) confirm that it's a libtermkey or unibilium bug.

**Comment by svaante** [comment]
The crash caused by setting TERM to a value where unibilium fails to find a value for "key_dc" and libtermkey calls tui_tk_ti_getstr("key_dc", NULL, void *data) which does a strcmp with a null pointer. 

The comparison is done as to referred in the comment  // Vim: "If <BS> and <DEL> are now the same, redefine <DEL>."  <BS> is still being defined because it does not rely on the value parameter.

Because "key_dc" is not defined in the terminfo for the specified TERM the proposed solution returns null to libtermkey which it results in insert_seq not being called for sequence "key_dc"

Suggested fix #6128
