### ISSUE TITLE
create "AppImage"

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#6083]
https://appimage.org is a way to provide pre-built binaries for many linux distributions in a single package. This could be used as the [nightly build](https://github.com/neovim/neovim/releases/tag/nightly). Currently the nightly build isn't very useful because it expects a very specific ubuntu environment.

We could start by forking https://github.com/chrisbra/vim-appimage

**Comment by AdnoC** [comment]
I'll take a stab at this. Not quite sure how to test that it can work with travis, but I'll cross that road when I get there.

**Comment by probonopd** [comment]
If you can build on Ubuntu trusty locally, then it should build on Travis CI too.

**Comment by justinmk** [comment]
Don't worry about Travis, this is for end users. @sander2 we're you working on this?

**Comment by AdnoC** [comment]
My fork of vim-appimage is here: https://github.com/AdnoC/nvim-appimage

I was able to generate an AppImage for neovim that lets you just download and run it. I was able to take an AppImage created on Ubuntu 16.04 ([can be found in this release](https://github.com/AdnoC/nvim-appimage/releases/tag/2017-04-30)) and it ran on a freshly created Arch Linux VM.

Isn't 100% yet. Files are opened in the AppImage filesystem instead of cwd. Trying to get around that by `cd`ing to a different directory causes it to loose track of `$VIMRUNTIME`.

**Comment by justinmk** [comment]
Nice! I don't think we need a separate repo do we?

**Comment by probonopd** [comment]
Runs on `ubuntu-16.04-desktop-amd64.iso`. If you want to have it work on older distributions, too, then use e.g., trusty for compiling. It will work on later ones too, but not earlier ones than the one you had compiled it on.

**Comment by AdnoC** [comment]
New release [here](https://github.com/AdnoC/nvim-appimage/releases/tag/2017-05-01). I thought it was 100%, but playing around with it using my vimrc and plugins it seems like it won't find remote plugin providers, so things like deoplete doesn't work.

Once that is done I want to clean up the build process so it doesn't create unnecessary files and that files from intermediary steps are cleaned up.

**Comment by AdnoC** [comment]
I know that the issue is AppImage related and not something with my ArchLinux setup, since the normally installed neovim reports a clean bill of `:CheckHealth`.

**Comment by probonopd** [comment]
Btw, the filename is a bit strange, I think it should have the glibc version just once an no double dashes.

**Comment by AdnoC** [comment]
Release can be found [here](https://github.com/AdnoC/nvim-appimage/releases/tag/2017-04-30v2)

I think its good to go this time.

I solved the issue - AppRun was appending to `PYTHONPATH`. If `PYTHONPATH` is empty, like it is by default, neovim can no longer find the default `pip` module installation directory.

So, I decided not to use the pre-built AppRun and just use a script that runs neovim. It doesn't seem to cause any problems. The only potential issue would be if we needed the `LD_LIBRARY_PATH` to be set, but I didn't see any libraries in the AppDir folder so I think we're ok.

I also changed the naming scheme. Since we don't bump the version number like vim does it makes more sense to go by the build date. Also fixed the duplicated glibc version.

**Comment by probonopd** [comment]
You are installing stuff to `usr/local/` inside the AppDir. Is that intentional? While it (mostly) works some software such as the optional `appimaged` daemon may pick up resources only if they are installed to `usr/` inside the AppDir.

**Comment by justinmk** [comment]
@AdnoC Is there something about AppImage that requires the git submodule or can we add the scripts to the main repo? (if so, can you send a PR?)

What are the steps to generate the final artifact? We could add those as a cmake/Makefile target.

**Comment by AdnoC** [comment]
@probonopd It installs to `/usr/local` inside the AppDir since that is where `make install` puts it when I pass it `DESTDIR=$APPDIR`. I couldn't figure out how to use `CMAKE_INSTALL_PREFIX` or `prefix` to remedy that, though I suppose I could have just `mv`ed it.

@justinmk The git submodule is just to have the neovim source in the tree. I'll transition it to the neovim repo and make a pull request.

Creating the final artifact is done by running `scripts/appimage.sh`. It currently assumes that the neovim source is available at the submodule location.

**Comment by AdnoC** [comment]
Running `make appimage` from a newly `git clone`ed repo builds the executable without issue.

Pull request is ready.

**Comment by probonopd** [comment]
@AdnoC did you try
```
cmake . -DCMAKE_INSTALL_PREFIX=/usr
make DESTDIR=appdir install ; find appdir/
```
