### ISSUE TITLE
neovim won't use ~/.vimrc (while vim does)

### ISSUE THREAD

**Issue by niko** [neovim/neovim#6130]
- `nvim --version`:
```
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 24 2017 17:27:32)
Included patches: 1-237
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
[…]    
```
- Vim (version: 8.0) behaves differently? Yes!
- Operating system/version: Arch Linux
- Terminal name/version: termite

### Actual behaviour

neovim 0.1.7 won't use `~/.vimrc`, while vim 8.0 does.

### Expected behaviour

Neovim should load `~/.vimrc` if present.

**Comment by justinmk** [comment]
Neovim is a different editor. Trying to use the same config for different editors is not something we want to support. However, you can do it explicitly (opt-in) by using symlinks, see `:help nvim-from-vim`. Though I recommend copying the config files rather than symlinking.

Using the same config files for two different editors is a temporary thing for people just trying out Neovim. It's not something we want to encourage as a long-term practice. (Just choose an editor...)

**Comment by niko** [comment]
Sorry. Missed that part of the documentation.
