### ISSUE TITLE
terminal-mode abbreviations (:tabbr)

### ISSUE THREAD

**Issue by uri** [neovim/neovim#6155]
It would be great if abbreviations would work in a terminal buffer. For example

```vimscript
:abbr ufbe User.find_by(email: "")<left><left>
```

And then using `ufbe<C-]>` to expand it in the terminal buffer.

**Comment by nhooyr** [comment]
For anyone who wants this right now, fish supports it http://fishshell.com/docs/current/commands.html#abbr though it works a bit differently.

**Comment by justinmk** [comment]
`:tnoremap` is already supported. `:tabbr` seems unnecessary.

**Comment by uri** [comment]
This does work but there's a delay if you start typing a character that is the beginning of a mapping. Also if you don't perform the mapping fast enough you can't expand it like an abbreviation with <C-]>.

**Comment by justinmk** [comment]
Patch welcome

**Comment by vlelo** [comment]
I'm not entirely convinced this is something actionable without big workarounds.
By their nature, abbreviations require (neo)vim to have access to the (memory) buffer the cursor is currently writing in, so that it can look for _lhs_ and replace it with _rhs_. In terminal mode, however, neovim simply sends keycodes over to another running process.

Personally, I can imagine this feature being desired **only** when interacting with a shell prompt, in which case a native (of the shell) solution would be much more fitting.

NB all I just said stems from three days of looking at the vterm source code in the neovim repo trying to get something out of this issue and no prior experience. Do  not trust blindly anything I say.

**Comment by justinmk** [comment]
> By their nature, abbreviations require (neo)vim to have access to the (memory) buffer the cursor is currently writing in, so that it can look for _lhs_ and replace it with _rhs_. In terminal mode, however, neovim simply sends keycodes over to another running process.

True. There is `:help prompt-buffer`. Also, it's planned to support full Nvim editing of shell prompts in a `:terminal`. Might require some hacks to yank (and later replace) the shell prompt input. However, neither of those cases would need terminal-mode mappings.
