### ISSUE TITLE
column number and Unicode characters

### ISSUE THREAD

**Issue by roxma** [neovim/neovim#6161]
```
你|好
```

Where `|` is the cursor position, I got `col(.)` == 4

I know that the first character "你".encode('utf-8')  is b'\xe4\xbd\xa0' , has a length of 3, which is why the next character `好`  gets the `col(.)` as 4

But from the user's perspective, the `col(.)`  should be 2 for `h` or `l` motion keys.

Is this intentional? Things get tricky for completion plugin when Unicode character is present.

**Comment by fmoralesc** [comment]
It is intentional, since `col()` is supposed to return the byte, not the visible column.

Moving to `virtcol()` doesn't help, though, I think, because that returns the position of the last column a character occupies. In the example above, it returns 2 when the cursor is above `你` and 4 above `好`, but I think it would be more consistent if it returned 1 and 3. 

As far as I can tell, there is no function to get the character position in a line, as opposed to the byte or the visible column it might occupy.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/68#issuecomment-255693061

> As far as I can tell, there is no function to get the character position in a line, as opposed to the byte or the visible column it might occupy.

It was added a few months ago in Vim (and merged to Nvim), see `:help strgetchar`, `:help strchars`, `:help strwidth`, etc.

**Comment by fmoralesc** [comment]
@justinmk  what about the behavior of `virtcol()`? Do you think it is sensible as is?

**Comment by justinmk** [comment]
> In the example above, it returns 2 when the cursor is above 你 and 4 above 好, but I think it would be more consistent if it returned 1 and 3.

Seems weird, but as long as it's consistent it doesn't matter, right? It's funny that `:set ruler` agrees with you. It's too late to change virtcol(), though.
