### ISSUE TITLE
[feature] c++14 digit separator and binary literals highlight support.

### ISSUE THREAD

**Issue by Socapex** [neovim/neovim#6175]
macOS NVIM 0.1.7

Any chance we can get the new digit separator and binary literals support in highlighting?
ex:
```
int t = 0b0001;
int t2 = 1'000'000;
```
Thank you.

**Comment by justinmk** [comment]
Thanks for the help! 

We don't want to fork the Vim runtime plugins in most cases (especially syntax plugins), unless there's a very good reason. Because if Vim changes something in the same file, it takes time to figure out the differences.

Please send this change to the maintainer, listed at the top of the file: 

And also send the change to https://github.com/vim/vim, mentioning that you already sent the change to the maintainer.

**Comment by Socapex** [comment]
No problem! What file though?

**Comment by nhooyr** [comment]
It's `runtime/syntax/c.vim`
