### ISSUE TITLE
cannot use close brace in cpp file

### ISSUE THREAD

**Issue by wsbky** [neovim/neovim#6193]
- `nvim --version`: 0.1.7
- Vim (version: ) behaves differently? No, not really.
- Operating system/version: MacOS Sierra version 10.12.4 beta
- Terminal name/version: Terminal.app (default)
- `$TERM`: zsh: command not found: xterm-256color

### Actual behaviour

When I push the close brace key, neovim issues error message.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

##### picture
![Screen Shot](https://github.com/wsbky/picture/blob/master/img/screenshot2.png)

**Comment by jamessan** [comment]
The screenshot shows that the error is from a plugin's function, `<SNR>108_getmap`.  Since you're also seeing this in Vim, then this is likely a bug in whatever plugin that is.

If you hit this again, then look at `:scriptnames` and see which plugin matches the number after `<SNR>`.  That's the plugin that's raising the error.

**Comment by wsbky** [comment]
The plugin which raised the issues was tweekmonster/deoplete-clang2. I deleted it and I can use the close brace key normally, but I'd like to use deoplete-clang2. What should I do?

**Comment by fmoralesc** [comment]
@wsbky You should report the issue at deoplete-clang's tracker. I think you will need to change https://github.com/tweekmonster/deoplete-clang2/blob/46b8e84170241d78d8b84d7ccc3398648a257713/autoload/clang2.vim#L266 to 

```vim
if has_key(m, 'expr') && m.expr
```

**Comment by wsbky** [comment]
Thank you.
