### ISSUE TITLE
pre-process Vim patches with uncrustify / clang-format

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#6226]
https://github.com/uncrustify/uncrustify could be used to dynamically format Vim sources to make them more compatible with Neovim for patch application.

Strategy:

- generate the git diff for the vim-patch (or just `git log --name-only foo..bar`)
- for each file listed in the git diff, 
    1. save the previous version of the file to some temporary location
    2. save the patch version of the file to some temporary location
- run uncrustify on (1) and (2)
- generate a diff from the uncrustify'd partial trees

**Comment by justinmk** [comment]
@blueyed for reference

**Comment by dundargoc** [comment]
I have a strong feeling that spending time on this won't be a worthwhile investment due to the ever growing divergence between vim and neovim. Don't get me wrong, I'm not against the idea, but I'd like us to re-evaluate if there's still interest in this.

I'd like some of the regular vim-patchers (@clason @seandewar  @zeertzjq ) to chime in and hear their thoughts since they're more familiar with the process.
