### ISSUE TITLE
jumplist placement

### ISSUE THREAD

**Issue by Ainoss** [neovim/neovim#6284]
- nvim any version
- Vim behaves the same 

### Actual behaviour
When new jump is generated (any code surfing, * key) in the middle of jumplist, it is placed to the end of jumplist (:ju), so you need to do many Ctrl-O to return back. 

### Expected behaviour
New jump, generated in the middle of jumplist, should overwrite all subsequent ones. 

Typical workflow with neovim as IDE heavily uses jumps, and actual behaviour is quite annoying.
Some patch already done by me, for setpcmark(). Could this be useful?

**Comment by justinmk** [comment]
If you make it optional somehow, and add sufficient test-coverage, patch welcome.

**Comment by ZyX-I** [comment]
Current ShaDa code assumes that window jump and change lists are sorted on timestamp, so `setpcmark()` patch is definitely not enough.

**Comment by ZyX-I** [comment]
More, how you are going to merge jump lists from different Neovim instances (what ShaDa is for) without that sorting? Though I think that it is OK to always sort jump/change lists by timestamp when reading/writing ShaDa file: by the time it is read you normally have already lost the context and do not require `<C-i>` to work like you expect.

**Comment by Ainoss** [comment]
Result jumplist will be sorted right. List will be shrinked to the current position, and old position will be added here. Should I add detailed example? 
I doesn't know how ShaDa works for now, but I will check this. Thank for this point.

**Comment by ZyX-I** [comment]
@Ainoss All positions in the list contain timestamp. If you are inserting in the middle of the list then it appears that item N has timestamp that is greater then item N+1. This is not going to work well with ShaDa, specifically its ability to merge jump lists: consider that you have jump list `<C-o> <-- A B C (D) E F --> <C-i>` and created a new jump G: `A B C D (G) E F`. Now you want to read ShaDa file which was created previously by the same editor instance, it contains list `A B C D E`. Normally it uses `O(N)` search to find the position, so when inserting `E` it would check `A`, `B`, `C`, `D` and then find out that `E` from the file is the same jump as `E` in the current instance. But with `A B C D G E F` it would merge like following:

    A => A B C D G E F = (dropped: equal to A)
    …
    D => A B C D G E F = (dropped: newer then A B C, equal to D)
    E => A B C D G E F = A B C D E G E F

There is also some code to clean duplicates which will remove some of the instances of E, but I am not sure which one. Also ShaDa does not run this code (`cleanup_jumplist`) after reading the ShaDa file because it is not supposed to contain any, it only runs it before writing. Aside from that cleaning up is done before displaying `:jumps` (so duplicates will not be easy to see) and by `movemark()` (used only by `<C-o>`/`<C-i>`).

**Comment by Ainoss** [comment]
@ZyX-I I see there is some misconception about the expected behaviour. So let me explain this:
```
 A B C D E ( ),   several <C-o>: 
 A B C (D) E F, let jump from here:
 A B C D (G), so E and F jumps were deleted.
```
As you see, new list sorted by time correctly. If you read ShaDa file with 'A B C D E F', you will get correct list with 'A B C D E F G' (if I understand merge mechanism correctly). This is actual behaviour of jumplist. I suppose that it is acceptable behaviour in case of reading ShaDa. In other case, new behaviour should be more convinient.

**Comment by ZyX-I** [comment]
Yes, if you delete these jumps ShaDa code should be fine. I thought you would just insert a jump in the middle.

**Comment by Ainoss** [comment]
I'm not good in lua and nvim tests. Could you give some points where to place my tests and what api to use? 
I found shada/marks_spec.lua and shada/merging_spec.lua files for now. Is it a good places to add new tests?

**Comment by justinmk** [comment]
Yes

**Comment by ZyX-I** [comment]
shada/\* is for ShaDa tests only. If you are dropping the tail you do not need to add any tests there. I think that you need test/functional/normal/jumps_spec.lua.

**Comment by muniter** [comment]
This usecase seems to be resolved with https://github.com/neovim/neovim/pull/11530 should this issue be closed?

**Comment by zeertzjq** [comment]
The author of this issue hasn't had any activity on GitHub in the past two years anyway.
