### ISSUE TITLE
`source $MYVIMRC` doesn't "remove" commands from previous `source`

### ISSUE THREAD

**Issue by kreedz** [neovim/neovim#6314]
- `nvim --version`: 0.1.7
- Vim (version: 7.4) behaves the same as nvim 
- Operating system/version: Debian 8.7 Jessie
- Terminal name/version: urxvt 9.20
- `$TERM`: rxvt-unicode-256color

### Actual behaviour
1. Add to empty $MYVIMRC (~/.config/nvim/init.vim) only this:
`set nu`
2. Write current buffer to the file :w and source current file :so %.
3. The line numbers must appear on left side of nvim.
4. Comment out or remove that added line on step 1.
Repeat step 2.
5. Now the line numbers doesn't disappear. (It disappears only if restart nvim).
### Expected behaviour
5. Now the line numbers disappear.

Yes, you can remove `set nu` and add `set nonu`. But when I remove `set nu` from $MYVIMRC and then source that file I expecting disappearing that column numbers.

The same can be done with `nmap <F5> :bp<cr>`. I.e. when I remove that mapping from config file and source that file I expecting that mapping will not work. But it works until restarting nvim.

As I understand `source file` just read commands from file and perform them.
I.e. `source file` doesn't "remove" commands that was performed on last `source`.

And is it possible to "remove" commands that was performed on last `source` without restarting nvim?

Is it normal behaviour or I'm just missing something?

**Comment by ZyX-I** [comment]
It is normal behaviour. It would be technically too hard to “undo” any state changes that are introduced by sourcing some script and additionally it is not making much sense because restarting editor is not expensive. So I know exactly no languages which allow this kind of task without some work from developers: e.g. rewriting your vimrc on top of my frawor framework and caring about undoing option changes right when you add them (even if frawor allowed undoing options it would require you to replace `set nu` with `call s:_f.options.set({'number': 1})`, but I never needed this so there is no such option). Normally such work is done when you are running a service and don’t want to loose uptime, just I once thought it would be good idea to resource my plugins safely without restarting.

Consider the consequences: &number is an option which is local to window, new windows inherit it from the current one. So if you want to undo `set number` you need to iterate over all windows and undo it everywhere. But it may appear that in some windows you undid this option yourself while in another this option was set by a plugin and numbers are part of the plugin’s interface. So you additionally need to care about `verbose set number?`, specifically information about where it was last set. Additionally this information is provided in a line which is translated. And some plugins may use `let saved_number = &number|set nonumber|try|{do stuff}|finally|let &number = saved_number` which will mess up `verbose set number?`. And this is just one option. You may make an agreement that “undoer” does not care about some things because 90% of time ignoring them does not cause any problems, but there is a case when you *can’t* ignore and it is still technically hard to undo something right:

Now consider that you are seeing strange messages and figured that they are coming from some Python plugin, but do not know which. To find out you import `sys` Python package and mock `sys.stdout` so it saves traceback to a log when being written to. You found out which was the offending plugin, removed the mock from your vimrc and want to undo the changes by doing `source ~/.vimrc`. Question: how should Neovim know that you did them, where it is going to take information about original `sys.stdout` (it could’ve been mocked by the time, and even more the once: you would not see the messages without mocking `sys.stdout` in first place), what should it do if your mock was mocked by some plugin later, what should it do if your mock was saved somewhere (e.g. received by the `logging.StreamHandler` as a stream to write to), …?

You can solve all problems by writing your vimrc in a way so that it could be undone and agreeing that you will ignore some things, while Neovim cannot work out how to more or less safely undo some simple constructs with some restrictions. And obviously hit bug reports from users when their use-cases do not meet “some restrictions”. Language which requires to restart editor after editing vimrc or face problems like you do is more maintainable.
