### ISSUE TITLE
shell commands return `inappropriate ioctl for device`

### ISSUE THREAD

**Issue by FliiFe** [neovim/neovim#6336]
- `nvim --version`: 
```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/var/tmp/portage/app-editors/neovim-0.1.7/work/neovim-0.1.7_build/config -I/var/tmp/portage/app-editors/neovim-0.1.7/work/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.1.7/work/neovim-0.1.7_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.1.7/work/neovim-0.1.7_build/include
Compiled by root@fliife-computer

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "/etc/vim/sysinit.vim"
     fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: 8.0.386) behaves differently? Yes it does: the error doesn't show up.
- Operating system/version: Gentoo (rolling release)
- Terminal name/version: rxvt-unicode v9.21 with tmux 2.2
- `$TERM`: rxvt-256color, set through `.tmux.conf`

### Actual behaviour

Whenever a command is run using `:!`, implicitly or explicitly, a warning shows up before the command's output:
```
stty: standard input: inappropriate ioctl for device
stty: standard input: inappropriate ioctl for device
```

Please note only one of these lines show up outside of tmux, and that this is true for all the terminals I have tested (konsole, qterminal, xterm, gnome-terminal), with their respective `$TERM` values. Also, I don't think it can be linked to Gentoo since I have the exact same issue under Archlinux.

### Expected behaviour

Command output is shown without additional warnings/errors

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

Then inside neovim:

```
:!echo whatever
```

**Comment by jamessan** [comment]
As noted in `:help vim-diff` and the [FAQ](https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes):

> |:!| does not support "interactive" commands. Use |:terminal| instead.
(GUI Vim has a similar limitation, see ":help gui-pty" in Vim.)

This is an intentional difference in behavior.  Neovim uses pipes to run external commands.

Also, your shell init files really shouldn't be trying to run `stty` in non-interactive shells.

**Comment by FliiFe** [comment]
Then tell me, how is `echo` an interactive command ? This doesn't happen on any of my other machines. Also, I have no direct control over what netrw uses under the hood to save a file. Same applies for every single vim plugin

**Comment by jamessan** [comment]
> Also, your shell init files really shouldn't be trying to run stty in non-interactive shells.

This is the important part.  The `echo` command is being run in a shell that's not attached to a terminal, but something in your shell init files is causing `stty` to run.  It doesn't make any sense to use `stty` in a non-interactive shell.

Maybe you've mistakenly changed `'shellcmdflag'` to pass the `-i` switch to your shell, or maybe the shell init files that are only used for non-interactive shells are incorrectly calling `stty`.

Either way, the reason this is exhibiting in nvim is because we run the commands connected to a pipe instead of a terminal.

**Comment by FliiFe** [comment]
Added a check for interactivity in `.config/fish/conf.d/omf/fish`. Fixed it. Thanks
