### ISSUE TITLE
crash: update_debug_sign .. win_line

### ISSUE THREAD

**Issue by guyzmo** [neovim/neovim#6402]
- `nvim --version`: NVIM v0.2.0-52-g0213e99
- Operating system/version: Archlinux (compiled from sources)
- Terminal name/version: GNOME Terminal 3.20.2
- `$TERM`: xterm-256color

### Actual behaviour

I have four splits:

* three vsplit:
 * code (left)
 * code
 * one horizontal split: (right)
   * term (top)
   * term (bottom)

on the bottom split, I loaded a file into a buffer using `nvr`, and used @shougo's unite to switch back to the terminal. The command is: `Unite -no-split -buffer-name=buffers -start-insert buffer`.

When the switch happened to the `term://` it crashed.

### Expected behaviour

it should not crash.

### Steps to reproduce using `nvim -u NORC`

this is an exceptional crash and I'm not sure it can be reproduced easily. Though I got a coredump and a backtrace to share for what's worth.

You can blame me for not keeping up to date with releases, shougo for his script, or the codebase. Either way, I though I'd share the backtrace 😉

attached is a zip (because github has no love for tarballs) with both the backtrace and the coredump.
HTH. Thank you and ♥

[NVIM-v0.2.0-52-g0213e99.core.zip](https://github.com/neovim/neovim/files/881782/NVIM-v0.2.0-52-g0213e99.core.zip)

**Comment by justinmk** [comment]
Thanks, but we fixed many crashes since then....

**Comment by justinmk** [comment]
0213e99 is 5 months old. I see the backtrace ends with `win_line` and you mentioned it happens when switching to a terminal buffer. The backtrace doesn't have state information or line numbers. Could you pull the backtrace with `thread apply all bt full`? see https://github.com/neovim/neovim/wiki/Development-tips#backtrace-linux for how to get the gdb backtrace output into a file.
