### ISSUE TITLE
[feature request] off-by-none mode

### ISSUE THREAD

**Issue by ewtoombs** [neovim/neovim#6415]
What I'm about to propose is going to break a lot of people's muscle memory and it's going to attract a lot of controversy, but please hear me out on this. This is a real chance to make things better for new users.

### _a cursor on character vs in between two characters_

New users will often say that editing in vim is full of spurious off-by-ones, out of ignorance that the cursor may be on a character or between two characters. This cursor behaviour is maintained partly for historic but mostly for dogmatic reasons. Vim is dogmatic. Right. Tell you something you don't know. But this is different... Right? Well... The dogma goes that the cursor may be on a character or between two characters, and sometimes one make sense and sometimes the other makes sense. The reality, every new user will tell you, is that this is total bullshit, and a cursor between characters is the only thing that ever ever ever makes sense. It's painfully obvious the only reason this dogma ever arose in the first place was that old terminals couldn't render a cursor in between characters. For about four years, I thought the dogma was true, but then one day, I started looking for real situations where the distinction is useful, and six years later, I still have nothing. I then looked back on the confusion and hatred spawned by these apparently intentional off-by-one errors during my vim learning process, and came to the inescapable conclusion that there is a better way of doing things.

## A game without character classes
My solution is one option that would allow the user to choose between legacy mode and a new mode that I'm going to call off-by-none mode. This switch will change several editing controls and behaviours. Please bear in mind I do not want this to be default behaviour, at least not until after off-by-none mode has undergone lengthy testing. I also understand that we'll probably always have legacy mode.

I'm not going to go into enormous detail over rationale behind each change because the rationale for the changes is the same every time. The cursor is always between two characters in off-by-none mode. In a terminal, the two characters the cursor is in between are exactly the characters everybody expects the cursor to be between: the character the block is rendered on top of and the character to its left. I will not explain why these are so much better. That's why I'm asking you do this before reading the list:

_Do an honest appraisal of all of the common editing patterns that come up regularly in your work and write them all down, along with the vi commands needed to make these happen. Do this, perhaps over a day's work, keeping a frequency count. Revisit these patterns in off-by-none mode. If you do, you will see the advantages, or at least you will see equivalent efficiency._

_Think honestly about your learning experience with vim and what problems you had while learning. How much easier would it have been if you had learned off-by-none vim? Monitor the independent learning process of somebody learning vim for the first time. Where are they having difficulties? What parts of the editing process are causing problems? Would off-by-none fix those problems?_

OK, let's begin.

1. When you escape from an insertion, the cursor stays where it is, such that hitting i and not a effectively continues where the last insertion left off.

1. e/E moves the cursor past the end of the word, so that i and not a starts inserting at the end of that word.

1. $ moves the cursor past the last character on the line such that $i would have the same effect as A. (As a result of this, lines will need to be wrapped at 79 characters instead of 80 to leave space for a cursor which is not being rendered on an actual character, but vim already has troubles with lines exactly 80 characters long to the extent that in practice everybody I know formats to or under 79 characters anyway.)

1. a appends to the end of a line instead of A. A is unmapped.

1. When % moves to a closing delimiter, the cursor is placed after it.

1. p pastes to the cursor's current location. P is unmapped. Wait, don't freak out! I haven't forgotten about line-wise pasting! See next change.

1. All text properly formatted text files end with a \n. This will be rendered as an undeletable empty line at the end of every file, such that Gp pastes lines past the last unempty line in the file.

1. When a length of text is highlighted in character-wise visual mode and the cursor is at the end, the character under the cursor is NOT in the highlighted text. In other words, if the cursor starts in the middle of the second word of a line of 8 words separated by whitespace, if you do bvWWWWd, this deletes four whitespace-separated words, leaving correct spaces around the remaining words:
```
before d:
alpha beta gamma delta epsilon theta eta iota
      _______________________________#
after d:
alpha theta eta iota
```

1. s deletes a line and starts an insert instead of S. S is unmapped.

1. When the cursor is between the last and second last characters of a word, hitting e/E does not skip the last character and move to the end of the next word. It instead move to the end of the current word. I'd consider this last rule obvious, but this is one place where vi e/E behaviour just really messes with people's expectations.

## And so forth
There is probably a lot more I'm forgetting, and some of what I proposed may not be a good idea after all, but the changes I have outlined give you the general idea. For now, just consider the spirit of the changes and what they could become. My own investigation into my vi usage patterns has taught me these changes do not impact usability, often improve usability, and _dramatically_ improve learnability, making vi editing make a _lot_ more sense. Please, please, _please_ take these changes seriously, along with the problems they would solve for new users, and even for old users. Break from this piece of dogma that has haunted vim for so many years.

## On a practical note
How hard would it actually be to enact these changes in neovim? I know it is completely impossible in vim for reasons everybody who has ever seen its code should be familiar with. I am a programmer after all, and if these changes are actually possible, I'd be happy to contribute to the development of off-by-none.

**Comment by justinmk** [comment]
It's not dogma, it's a design choice. Changing it would be a lot of work. It's been discussed before, this is a duplicate.

How long have you used vim? Try getting used to the current model, then see if your opinion changes.

**Comment by ewtoombs** [comment]
Ten years, and the fact that this has been brought up before kind of proves my point.

**Comment by jamessan** [comment]
There's a reason that the behavior is different in normal mode (cursor on character) and insert mode (cursor between character) and it has nothing to do with how the terminal displays the cursor.  It's because those are the positions that make sense for executing commands vs. inputting text.

**Comment by justinmk** [comment]
> The reality, every new user will tell you, is that this is total bullshit

New users shouldn't drive design choices. Because users are new for only a small fraction of the lifetime usage. 

> , and a cursor between characters is the only thing that ever ever ever makes sense. 

That sounds like dogma. 

> It's painfully obvious the only reason this dogma ever arose in the first place was that old terminals couldn't render a cursor in between characters

The entire video editing model was an accident of old limitations. Whether it's still relevant is an old debate, rendered moot by the fact that thousands of other editor choices exist. If vi's model isn't good then just use another editor instead of making vi the same as every other editor.

That being said, we're definitely open to adding extension points that make it possible to achieve your goal. But this won't be a core feature.

**Comment by ewtoombs** [comment]
Like I said, just try common patterns in legacy and in off-by-none. You'll see equivalent or better efficiency every time. And if not, present the list of patterns that are made considerably less efficient by my suggestions.

**Comment by ewtoombs** [comment]
My changes would not make vi like every other editor, except on this one point, where the other editors actually got it right and you should pay attention.

**Comment by ewtoombs** [comment]
Does neovim have the instrumentation for this to be implemented as an extension?

**Comment by justinmk** [comment]
We're open to PRs with sufficient test coverage. But this isn't going to be put on the roadmap.

**Comment by justinmk** [comment]
> Does neovim have the instrumentation for this to be implemented as an extension?

No, that's why new extension points would be needed (e.g. hooks that change cursor behavior at a low level).

**Comment by ewtoombs** [comment]
These extensions points will probably be useful for other things. Any chance you could help with them?

**Comment by ewtoombs** [comment]
oh right you already answered that lol. Sorry. Well, awesome then. I'll definitely help with said extension points.

**Comment by ewtoombs** [comment]
As for off-by-none itself, though, if you really want to put this to bed forever, just provide that list of common editing patterns made less efficient by my proposed changes. It will save you the trouble of undergoing this argument again in the future. Don't think I won't take your list seriously, because I will.

**Comment by ewtoombs** [comment]
Could you leave this open so that anybody else who does want to help with off-by-none can do so?

**Comment by justinmk** [comment]
I'll do that as soon as I finish the 9000 other things I have to do

**Comment by justinmk** [comment]
No, because this is not on the roadmap.

**Comment by ewtoombs** [comment]
> thousands of other editor choices exist
afaik, nothing like off-by-none exists. Otherwise, believe me, I'd be using it.

**Comment by bfredl** [comment]
Large parts of this are already achievable by options and mappings.  On the top of my head, 3. can be done using `virtualedit=onemore` + `noremap $ $l` and 8. is already implemented, `set selection=exclusive` (arguably this mode should change the cursor shape to narrow as well). 5. can be implemented in `matchit.vim` without changes to C code. TBH I don't see any "radical change how the cursor behaves" here, It wouldn't surprise me if most of this already can be done by mappings + maybe small additions to the core, like allowing cursor shape to be set to narrow in arbitrary modes...

**Comment by ewtoombs** [comment]
Well, awesome! The less C needing to be changed, the better! That's what I was hoping for in the first place, really. But surely changing escape-from-insert and e/E behaviour would be more tricky...

**Comment by aidancz** [comment]
I feel excited and delighted, because there are users who share the same feelings as I do.

The fundamental design flaws of Vim led to later chaos.

The first major design flaw is hiding EOL and EOB.

EOL is the LF character. Vim hides this character on non-empty lines.
In other editors, it is usually displayed as a space.

Consequences of hiding it:
	•	When leaving Insert mode, the cursor is forcibly moved one character to the left.
	•	You cannot treat this character with normal means; for example, x cannot delete it.

Later remedies:
	•	It can be selected in Visual mode.

EOB is not a character, but a position. When opening an empty buffer, the cursor is located at this position. Once Vim adds any character to the buffer, this position becomes hidden.
In other editors, it is usually displayed as a space.

Consequences of hiding it:
	•	It is impossible to determine whether a buffer ends with an EOL.
	•	Some APIs support this position while others do not, which causes confusion, for example #33935.

The second major design flaw is the ambiguity of the cursor position: is it between characters or on top of a character?
Here, a cursor that is between characters is called a bar cursor, and a cursor that is on top of a character is called a block cursor.

The cursor position is important because it determines the selected region.
If it is a bar cursor, Vim calls it exclusive.
If it is a block cursor, Vim calls it inclusive.

I believe the bar cursor is better than the block cursor, because a bar cursor can select an empty region, whereas a block cursor always selects at least one character.
Empty regions are useful—for example, with ci". If a plugin wants to implement the c operator and there are no characters between the quotes, it could operate on an empty region. But currently this can only be done using hacks, because at least one character must be selected.

(This is still true even when using set selection=exclusive.)

At present, the vast majority of motions and APIs are exclusive, which also shows that the bar cursor is superior.
However, the current situation is that both cursor models are mixed together, which leads to confusion (the first flaw also plays a role here—for example, $ is inclusive entirely because EOL is hidden).

Some hacks seem to solve the problem, such as preventing the cursor from moving when leaving Insert mode:

set virtualedit=onemore
set listchars+=eol:\ ,
autocmd InsertLeave * :normal! `^

But in my experience, the more such hacks are used, the more things break, because they are essentially fighting against everyone else’s assumptions and defaults.

**Comment by ewtoombs** [comment]
I just gave up on this and started using kakoune instead.
They mostly fixed this by default.

**Comment by justinmk** [comment]
> But in my experience, the more such hacks are used, the more things break, because they are essentially fighting against everyone else’s assumptions and defaults.

Those are not "hacks". And yes, any plugins that make invalid assumptions will break. That is the case for kakoune also.

**Comment by aidancz** [comment]
> > But in my experience, the more such hacks are used, the more things break, because they are essentially fighting against everyone else’s assumptions and defaults.
> 
> Those are not "hacks". And yes, any plugins that make invalid assumptions will break. That is the case for kakoune also.

I call it a hack because it doesn’t solve the problem at the correct layer.

For a question like whether LF should occupy a screen cell, there must be only one answer. Because changing something this **fundamental** will cause far more problems than other assumptions.

Every character should occupy at least one screen cell that the cursor can move onto. There is only one exception: LF.
