### ISSUE TITLE
write_list: Slowdown in Docker because of fsync

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#6420]
I have noticed a slowdown when running Neovim in Docker.

It turned out that https://github.com/neovim/neovim/commit/31cdb227ba60e8867b3cb8e60ae8215290dd85a4#commitcomment-21508188 is causing it.

Reverting that commit on master fixes the regression.

I've used the following method to test it:
```vim
function! Bisect()
  let start = reltimefloat(reltime())
  let file = tempname()
  for i in range(1, 50)
    call writefile([i], file, 'a')
  endfor
  let duration = reltimefloat(reltime()) - start
  echoerr printf('duration: %.3f', duration)
endfunction
```

The time difference is around 0.1s for those 50 runs: 0.352 vs 0.445

(This seems not too much, but it somehow caused Neomake's test suite too take twice as long, since it does a lot of logging.  Although I am not sure about how I've noticed this, since normally logging to a file is not enabled during the tests, but only one test is using it.)

@ZyX-I mentioned in https://github.com/neovim/neovim/commit/31cdb227ba60e8867b3cb8e60ae8215290dd85a4#commitcomment-21508188 that the fsync would be done when freeing the fp, and maybe that the issue/diff here after all: previously fsync would be done just once, while its done now after each write?!

Docker info:
```
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Kernel Version: 4.10.6-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
```

**Comment by ZyX-I** [comment]
0.02s per fsync() syscall is rather strange. Though that is switch to kernel mode for sure plus three or four levels of abstraction (fileio.c, os/fs.c, libuv, possibly libc then: do not know what libuv uses).

**Comment by blueyed** [comment]
I have tried it with https://github.com/neovim/neovim/commit/518f28f537971c70d7781ce30c5de0c829e01464 (#6422), and while it seems to be a bit better, it's still rather slow, and the Neomake test with the single `writefile` might take `0.01` seconds still.

The above `Bisect` function takes 0.324-0.35s, so it seems to behave as before 31cdb22 (where I noticed the test failure with initially).

When using the pre-built Neovim 0.1.7 from Alpine's repos (or building it myself), it takes `0.037s` for 5000 loops only!

So I've bisected it again, based only on the `Bisect` function above (and not the Neomake test), and it found: commit fe0eecf9: eval: writefile: Give more adequate IO errors and do not call putc()

There the 5000 loops take 33.011s vs 0.03s before.

Sorry for the confusion!

**Comment by ZyX-I** [comment]
This is interesting. Main change there is that libc buffered write implementation was replaced with Neovim buffered write implementation. Second main change is that previously code did not bother calling `fsync()` at all (actually, `FILE*` API does not have a wrapper for this syscall), my buffered write always uses `fsync()`.

Two main differences between libc and my implementations: libc (at least, on my system) uses different buffer size (4k vs 1k AFAIR) and second is irrelevant to writes: when reading I am using readv to populate both rbuffer and ret_buf, file_write does not use writev.

Since I would not expect three orders of magnitude difference due to different buffer sizes or write buffer implementations I guess that what you are seeing is flushing writes to disk.

**Comment by ZyX-I** [comment]
@blueyed Can you check with #6427? Do not forget to modify code to include `S` in the third argument to `writefile()`.

**Comment by blueyed** [comment]
Thanks, #6427 (https://github.com/neovim/neovim/pull/6427/commits/b10880dadcbd3b3ad368621f95a0f4be7e30dc0d) with `S` takes only 0.034s again.
