### ISSUE TITLE
UI: mode_info_set (cursor) enhancements

### ISSUE THREAD

**Issue by tweekmonster** [neovim/neovim#6428]
Just noticed this redraw instruction and it looks pretty great.  But, some things that would make it better:

- Docs for `*rpc-remote-ui*`
- Send the actual colors instead of `hl_id`.  Setting the cursor style should be a one-way trip.

**Comment by justinmk** [comment]
:+1:

**Comment by teto** [comment]
There is room for improvement:
- changing the highlight doesn't necessarily update the cursor https://github.com/neovim/neovim/issues/6425. I suppose there should be some code in highlight_changed.
- @frangio wanted to be able to hide the cursor:

> For example, incsearch.vim uses a NONE highlight group to hide the cursor. I don't think that one comes by default in Neovim. Maybe the TermCursorNC group could be used for the same purpose.

I am not sure that should be linked to guicursor but it could.

**Comment by justinmk** [comment]
> @frangio wanted to be able to hide the cursor:

Can't that be done by temporarily setting 'guicursor'?

**Comment by teto** [comment]
hiding the cursor is a special CSI, hence I don't think it is possible currently. incsearch.vim specialcased the None hl group to hide the cursor IIRC. I wish one could document the highlight vs attr thing in syntax.c (or point me to some doc, couldn't find anything interesting).

**Comment by teto** [comment]
> Docs for *rpc-remote-ui*

what could be nice on top of text documentation is to upload some pcaps so that people can check directly with wireshark the format. Too bad the msgpack dissector is not good enough yet.

**Comment by justinmk** [comment]
>  incsearch.vim specialcased the None hl group to hide the cursor IIRC.

Can't it temporarily set 'guicursor' to use such a highlight group?

> upload some pcaps so that people can check directly with wireshark the format. Too bad the msgpack dissector is not good enough yet.

Is the [lua client result](https://github.com/neovim/neovim/blob/master/test/functional/ui/cursor_spec.lua#L23-L144) not sufficient?

**Comment by teto** [comment]
@zhou13 @frangio I've started working on this (hide/show cursor) ; waiting for https://github.com/neovim/neovim/pull/6539 to push. It's trickier than I thought because flush_buf makes visible any hidden cursor.

> Can't it temporarily set 'guicursor' to use such a highlight group?

So I've done a bit of digging as I never used that feature: whatever group is set for guicursor, it is created. Thus incsearch.vim doesn't specialcase the `None` hl, it could be named to anything, as long as the hl group doesn't have guibg set, cursor will stay hidden.

> Send the actual colors instead of hl_id. Setting the cursor style should be a one-way trip.

There might be the need to check other hl parameters such as gui=inverse ? In fact I wonder how UIs can get a specific highlight description ? From what I saw, the current hl is pushed via ui_start_highlight/ui_stop_highlight, which means that UIs would not be able to set the cursor color as it stands, only the TUI because it can query the hl specifics ?!

> Is the lua client result not sufficient?

That's good enough. pcap files would be the icing on the cake :)

**Comment by justinmk** [comment]
> UIs would not be able to set the cursor color as it stands, only the TUI because it can query the hl specifics ?!

FWIW, we could expose an async API function that allows querying "hl specifics".

**Comment by teto** [comment]
> FWIW, we could expose an async API function that allows querying "hl specifics".

How would that look like ? when would it query the hl ? could the UI subscribe to be notified of HL modifications. I could add it to #6566.

**Comment by justinmk** [comment]
> Send the actual colors instead of hl_id. Setting the cursor style should be a one-way trip.

AFAICT the only way it can be a one-way trip is if the color info is sent with `mode_info_set` UI event. Anything wrong with that?

**Comment by bfredl** [comment]
`mode_info_set` is meant to be extended. Just send the colors there.

**Comment by teto** [comment]
Some precisions:
-  for setting cursor foreground color, VTE api allows it (termite has a cursor_foreground parameter for instance) but there is no OSC yet. https://bugzilla.gnome.org/show_bug.cgi?id=695011 proposes OSC20 for this purpose but rxvt has a pre-existing use of OSC 20 (for background pixmap). Thomas Dickey (xterm maintainer) seems ok with a patch that would set cursor foreground color, so anyone interested can  propose such a patch.
- can't find the issue asking for inverted colors under the cursor. In a previous comment I said it would be hard but in fact it seems to be the default behaviors for xterm/VTE (if you don't change the cursor colors) so that's possible if no application fiddles with the terminal cursor color.

**Comment by justinmk** [comment]
> Docs for `*rpc-remote-ui*`

This was done.

> Send the actual colors instead of `hl_id`.  Setting the cursor style should be a one-way trip.

This was done by @bfredl.
