### ISSUE TITLE
nvim slow after build 12233

### ISSUE THREAD

**Issue by raghur** [neovim/neovim#6437]
- `nvim --version`:
```
NVIM v0.2.0-1148-gddfa0359
Build type: Release
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Optional features included (+) or not (-): -acl   +iconv    -jemalloc -tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```
- Vim (version: ) behaves differently? NA
- Operating system/version: Windows 8.1
- Terminal name/version: NA
- `$TERM`: NA

### Actual behaviour
After build [12233](https://ci.appveyor.com/project/neovim/neovim/build/12233/job/y3owt9or7ljc8nvv/artifacts), nvim on windows has become terribly slow to startup. Also, resizing the window takes forever and in general feels sluggish (ex. noticeable delay with denite)
 
Profiling startup time (starting `nvim --startuptime file` and then connecting with `nvim-qt --server`). 

- with latest, startup time is 10s [pastebin](https://pastebin.com/TDmaegZp)
- with 12233, startup time is 655ms [pastebin](https://pastebin.com/U2UGKU43)
 
More details on this [reddit thread](https://www.reddit.com/r/neovim/comments/62xje8/neovim_on_windows_startup_takes_really_long/)

### Expected behaviour
Should be fast as before.
### Steps to reproduce using `nvim -u NORC`

Without init.vim, startup is fast - however something's changed that startup profiles are so widely different.

**Comment by justinmk** [comment]
@raghur Could you try with 'fsync' option disabled?

    nvim-qt.exe -- --cmd "set nofsync"

**Comment by raghur** [comment]
Tried it - no change in behavior with latest nvim.

**Comment by justinmk** [comment]
> Also, resizing the window takes forever

@raghur Can you check if there are any VimResized handlers (and paste them here):

    :new|put =execute('au VimResized')

@raghur Also did you ever try it antivirus disabled (or exception added)?

@ZyX-I This report was narrowed down to #5119, can you think of anything there that would affect IPC performance or affect filesystem performance on Windows?

**Comment by ZyX-I** [comment]
Except for moving some functions from eval.c this PR mainly alters types to `[const ]char *`, this had some collateral damage. Specifically IPC was mainly not touched: it is a new addition so was already using `[const ]char *`, only typval_T and related types-manipulation function were affected. Filesystem *performance* should not be altered as well: I did change types in the os/\*, there was also something related to AFAIR symlink resolution. What other comes to mind and should affect performance are some functions in `eval.c` which after adding `const` required a huge refactoring including removing `p[idx] = NUL`, but that should’ve already been seen because of being universal.

So only if os/\* symlink-resolution-related functions, yet there is a problem: I remember me doing huge refactoring of os_resolve_shortcut or something like this, yet `git diff c60e409{'^',}` shows nothing in that function, only types changing.

**Comment by ZyX-I** [comment]
By the way, is logging enabled?

**Comment by justinmk** [comment]
Logging isn't enabled on the Windows artifacts, I'll create a temporary build with logging.

**Comment by AlexMasterov** [comment]
I have the same problem on Windows 10 (15063) and SSD.

build | startuptime |
------|-------------|
[nvim-v0.2.0-999-g99a95100](https://pastebin.com/fc1Gept6) | 032.059
[nvim-v0.2.0-1087-g3cccb848](https://pastebin.com/U5vVAfuP) | 110.141

Some plugins started to throw exceptions or freeze the UI.
Everything has become slower and has a visual delay; `BufEnter` 2-3s, typing is lagged.

Сlear events? nothing changes.

**Comment by justinmk** [comment]
@AlexMasterov Are you running anti-virus software, and if so, can you try to see if disabling it or adding an exception for the nvim directory, changes anything?

**Comment by AlexMasterov** [comment]
@justinmk I didn't install and Windows Defender is turned off.

**Comment by raghur** [comment]
>@raghur Another thing to check: do you have network drives mapped? Is startup fast if you disconnect all mapped network drives?

No - no networked drives.

>Also did you ever try it antivirus disabled (or exception added)?

Yes - entire Neovim folder has been excluded.

>`:new|put =execute('au VimResized')`

Seems like vim-airline has an au
```
--- Auto-Commands ---
airline  VimResized
    *         unlet! w:airline_lastmode | :call <sid>airline_refresh()
```

**Comment by tweekmonster** [comment]
> Yes - entire Neovim folder has been excluded.

Have you tried disabling it altogether?  I'm not exactly sure how anti-virus and malware scanners work, but their exclusions might not extend to the subprocesses that are spawned.  If any of those plugins are using Python, the Python process is probably being scanned as well as all the modules it loads.

**Comment by justinmk** [comment]
I'm fairly convinced anti-virus is irrelevant here. I've noticed some slowdowns as well, will get some measurements tomorrow.

**Comment by janlazo** [comment]
Did anything change after #6497? I'm experience slowdowns as well even with filepaths without spaces.
At least 10 seconds and a couple of retries on the initial run. If I close it and run another instance, the slowdowns are reduce to about 5 seconds. It's worse with the debug build. Made scrolling in nvim-qt as slow as Nyaovim.

**Comment by justinmk** [comment]
@ZyX-I VimL evaluation in general is slower since #5119. (I will update this comment as I gather more measurements)

- 15% slower on my ubuntu VM
- 200%-300% slower on Windows 32-bit VM
- Measurements are average of multiple samples
- Sourcing [sexp.vim](https://github.com/guns/vim-sexp/blob/b4c7f55b499f00326751c1bc20c9f64e7301bd56/plugin/sexp.vim) 
- built with `make CMAKE_BUILD_TYPE=RelWithDebInfo`
- using `:Time` command from [scriptease.vim](https://github.com/tpope/vim-scriptease)

```
:edit plugin/sexp.vim
:Time unlet g:sexp_loaded|source %
```

| ubuntu-saucy-64 VM | | Windows 32-bit VM | |
|-|-|-|-|
| `v0.2.0-996` c35420558bed (just before #5119) | `v0.2.0-1220` 26bf6e6f6f88 | c35420558bed | 26bf6e6f6f88 |
|-|-|-|-|
| 0.070s | 0.079s | 0.015s | .100s |

**Comment by ZyX-I** [comment]
This needs a C profiler, not simple `Time`.

**Comment by justinmk** [comment]
Yeah, I'm working on it. This is just what I found now.

**Comment by justinmk** [comment]
@ZyX-I callgrind results on ubuntu:

    valgrind --tool=callgrind --log-file=valgrind-prof.log build/bin/nvim -n -u NONE -i NONE +":e ~/.local/share/nvim/bundle/vim-sexp/plugin/sexp.vim" +"so %"
    callgrind_annotate

- [c354205](https://gist.github.com/justinmk/e6204e7cbe2c36c32dae780ee5242343) (before #5119)
- [c60e409](https://gist.github.com/02f771cb3b22aac800a1c7193392d753) (merge of #5119)

2nd trace has 3x as many `strlen` calls. `getenv` saw a 10x increase. And gettext dominates.

On Windows, profiling mingw-compiled nvim with debug symbols is difficult. Still trying.

**Comment by ZyX-I** [comment]
@justinmk Can you post original profiling data? About gettext I have an idea: I have moved gettext call for `{funcname} argument` to the top of a bunch of functions while it previously was needed for errors only. This made the code clearer, but apparently unoptimal.

**Comment by justinmk** [comment]
> Can you post original profiling data?

I'll post it but I'm not sure if it's portable.
