### ISSUE TITLE
guicursor isn't working (multiple terminals)

### ISSUE THREAD

**Issue by shmerl** [neovim/neovim#6655]
Cursor doesn't change shape, when going in and out of insert mode. Instead it shows `q` under the block shaped cursor when Ins is pressed.

NVIM v0.2.1-dev, installed on Ubuntu 14.04.5, accessed remotely from current Debian testing and Konsole. TERM is set to xterm-256color.

Before this breaking cursor change it all worked fine with `let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1`
Here is my current setting in init.vim:

    "let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
    set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor
    let $TERM_PROGRAM="Konsole"

```
NVIM v0.2.1-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-vFc2DX/neovim-0.1.7ubuntu1+git201705021853+3395+23~ubuntu14.04.1/build/config -I/build/neovim-vFc2DX/neovim-0.1.7ubuntu1+git201705021853+3395+23~ubuntu14.04.1/src -I/build/neovim-vFc2DX/neovim-0.1.7ubuntu1+git201705021853+3395+23~ubuntu14.04.1/.deps/usr/include -I/build/neovim-vFc2DX/neovim-0.1.7ubuntu1+git201705021853+3395+23~ubuntu14.04.1/.deps/usr/include -I/build/neovim-vFc2DX/neovim-0.1.7ubuntu1+git201705021853+3395+23~ubuntu14.04.1/.deps/usr/include -I/build/neovim-vFc2DX/neovim-0.1.7ubuntu1+git201705021853+3395+23~ubuntu14.04.1/.deps/usr/include -I/build/neovim-vFc2DX/neovim-0.1.7ubuntu1+git201705021853+3395+23~ubuntu14.04.1/.deps/usr/include -I/build/neovim-vFc2DX/neovim-0.1.7ubuntu1+git201705021853+3395+23~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-vFc2DX/neovim-0.1.7ubuntu1+git201705021853+3395+23~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-vFc2DX/neovim-0.1.7ubuntu1+git201705021853+3395+23~ubuntu14.04.1/build/include
```

**Comment by cwlbraa** [comment]
I have the same issue with terminator under ubuntu 16.04

**Comment by physkets** [comment]
I'm using GNOME Terminal and have the same issue with all mouse functionality broken. i.e., I can no longer move between split screens by clicking, etc. I think this is a bigger issue.

**Comment by brocaar** [comment]
I'm having issues too with the cursor. With version 0.1.7 it was taking the same cursor as set by my terminal (iTerm, OS X) (vertical blinking line), with 0.2.0 the cursor changes to a non-blinking block. After exiting nvim, this non-blinking cursors remains.

I'm also experiencing the issue as @physkets is mentioning since upgrading from 0.1.7 to 0.2.0.

**Comment by justinmk** [comment]
@brocaar Cursor shaping is enabled by default (where possible) in 0.2. As mentioned at `:help 'guicursor'`, to disable it, set it to empty in your config:

    set guicursor=

"Mouse functionality" is controlled by the 'mouse' option, the default changed (sorry, it caused problems for other users, we're going to improve the behavior so that it can be enabled by default again, in the future). Add this to your config:

    set mouse=a

> Before this breaking cursor change it all worked fine with let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1

@shmerl The guicursor setting that you added, also sets cursor coloring. Maybe that's not supported by your terminal. Try using the default setting instead, which doesn't attempt to color the cursor:

    set guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20

NB: `$TERM_PROGRAM` is irrelevant for anything except iTerm.

**Comment by justinmk** [comment]
> accessed remotely from current Debian testing and Konsole

If `$KONSOLE_PROFILE_NAME` is empty, try setting it to something. That's the only way that I know of, for nvim to detect Konsole.

**Comment by brocaar** [comment]
@justinmk cheers, unsetting it and addind `set mouse=a` did the trick!

**Comment by shmerl** [comment]
Setting `let $KONSOLE_PROFILE_NAME="something"\ fixed it for me! That variable is naturally not set in remote case.

**Comment by cwlbraa** [comment]
`set guicursor= `solved my problem with terminator. previously I had `set guicursor=n-v-c:block-Cursor-blinkon0,ve:ver35-Cursor,o:hor50-Cursor,i-ci:ver25-Cursor,r-cr:hor20-Cursor,sm:block-Cursor-blinkwait175-blinkoff150-blinkon175` copy-pasted in my config from ages ago, and something about that broke when I updated to 1.7
