### ISSUE TITLE
Sessions don't restore tab-local directories

### ISSUE THREAD

**Issue by mhinz** [neovim/neovim#6678]
Window-local directories work already. Shouldn't be too hard to add tab-local support as well, if `&sessionoptions` contains `tabpages`.

**Comment by justinmk** [comment]
cc @HiPhish

**Comment by HiPhish** [comment]
I'll look into it over the weekend. My uneducated guess is that the file format of sessions does not store the working directory of tab pages since Vim does not have that information. Adding that information would make sessions incompatible between Vim and Nvim, but I guess that's not a concern for us?

**Comment by chrisbra** [comment]
you can wrap it into `has('nvim')` conditionals.

**Comment by jamessan** [comment]
Vim already has problems with portability of session files if you create one in a more featured Vim and then try to use it in a less featured Vim.

Using `has('nvim')` seems like a good approach.

**Comment by HiPhish** [comment]
Do you pointers as to where sessions are written and read? Otherwise I would have to go source-code diving blindly.

**Comment by jamessan** [comment]
`ex_mkrc()` handles creating the session file.  At startup, if a session file is specified, Vim just runs `:so /path/to/file`.

**Comment by HiPhish** [comment]
OK, found the function. How do I do `has('nvim')` in C?

**Comment by jamessan** [comment]
You don't.  A session file is just a bunch of normal Vim commands, so you just wrap the `:tcd` related commands with `if has('nvim')`.

**Comment by mhinz** [comment]
@HiPhish *\*ping\**

**Comment by HiPhish** [comment]
Sorry, I haven't forgotten, I just haven't yet had the time 😞

**Comment by HiPhish** [comment]
I have found the function of interest, it's `makeopens` in `src/nvim/ex_docmd.c`, this function is responsible for writing the bulk of the session file. Two questions:

- Is it OK if I clean up the function a bit by changing the comments to our style? I.e. `//` instead of `/* */`, that way we save two lines per comment block and with a function this large that would be a benefit.
- Where do I best insert the code?

There is this for-loop in the function:
```c
  tab_firstwin = firstwin;      /* first window in tab page "tabnr" */
  tab_topframe = topframe;
  for (tabnr = 1;; ++tabnr) {
```
This seems like an appropriate place since it loop through all the tab pages (there is a check at the bottom for `SSOP_TABPAGES`). Does it matter where exactly the `:tcd` appears? I would have put it at the top before any window-specific options.

**Comment by justinmk** [comment]
> Does it matter where exactly the :tcd appears? 

Whatever most closely matches the user expectations w.r.t. how tcd works.

> I would have put it at the top before any window-specific options.

Seems reasonable. 

Is `:lcd` restored...?

**Comment by HiPhish** [comment]
>Is `:lcd` restored...?

Yes, that one is handled by the `put_view` function which is called for every window inside the tabpage loop. I think I got it now, but how and where should I write the test?

**Comment by HiPhish** [comment]
PR is up as RFC: #6859
