### ISSUE TITLE
'pastetoggle' with more than 1 char interferes with operator pending more

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#6716]
- Vim (version: 8.0.586) behaves differently? yes

### Steps to reproduce

minimal.vimrc:
```vim
set runtimepath+=~/.vim/plugged/vim-sneak
omap t <Plug>Sneak_t
set pastetoggle=,sp
normal! ifoo, bar
normal! 0
```

Run `nvim -u minimal.vimrc`, and type `dt,`: it should delete to the ',', resulting in `, foo`, but instead it waits for the next key, and displays `d:,` in the bottom right.

I've bisected this to commit 337b6179d:

    Author: Matthew Malcomson
    Date:   Sat Apr 1 20:50:29 2017 +0100

    'pastetoggle': support value >1 char (#6421)
    
    If we `set pastetoggle=abcde`, and manually type it, then `vgetorpeek()`
    sees part of the option before it has all been inserted into the
    typebuffer.
    To signify this it sets `keylen = KEYLEN_PART_KEY`, but the condition
    about whether to return the current key from `vgetorpeek()` only checks
    for `keylen = KEYLEN_PART_MAP`.
    Add a check for `KEYLEN_PART_KEY` to account for the `'pastetoggle'`
    option.

I think this should be special-cased for operator (pending) mode or something like that.

/cc @hardenedapple

**Comment by ZyX-I** [comment]
@blueyed This is not specific to operator-pending mode, `t,` without `d` behaves the same way. More, other built-in  multikey commands like `g,` behave the same way now.

**Comment by hardenedapple** [comment]
Thanks for nice repro -- when writing that patch I completely missed the fact that vim has a bunch of special cases for whether or not to wait for `ttimeout`.

For this specific case, (`t,`) I think the difference in behaviour is due to the difference in how `ttimeoutlen` behaves between vim and neovim. In `vim` the default of `ttimeoutlen = -1` means use the value of `timeoutlen` but in `neovim` it means never time out.

If I run that testcase in original vim (though I used default `t` instead of `sneak` for my tests), with the extra line `set ttimeoutlen=9999` in the `minimal.vimrc` then I see the same behaviour -- the same for things like `g,` etc.

With the following `minimal.vimrc`
```vimL
set ttimeoutlen=9999
set pastetoggle=,sp
normal! ifoo, bar
normal! 0
```

Using the commands
 `vim -N -u NONE --cmd 'source minimal.vimrc'` and `nvim -u NONE --cmd 'source minimal.vimrc'`
 for `vim` and `nvim` respectively.
With `t,` I saw the same wait in vim as neovim.
