### ISSUE TITLE
:terminal inherits VIM, VIMRUNTIME, NVIM_LISTEN_ADDRESS

### ISSUE THREAD

**Issue by jdebp** [neovim/neovim#6764]
Justin M. Keyes said in #2977 : 
> Why are you exporting `VIMRUNTIME`? Even the Vim docs mention that it is not recommended,

The nvim documentation actually says:
> You don't normally set `$VIMRUNTIME` yourself

Contrary to this recommendation, nvim itself _does_ export this environment variable, to everything run in a terminal.  This of course could include vim or even another instance of nvim.  It similarly exports `VIM`.

See `:terminal printenv VIMRUNTIME`  and `:terminal printenv VIM`

**Comment by justinmk** [comment]
Yes, we shouldn't do this.

**Comment by ZyX-I** [comment]
Vim, BTW, also does this (to `system()`, `:!`, `:shell`).

**Comment by justinmk** [comment]
@ZyX-I Do you think we should unset it in those cases also? That would be a departure from Vim.

Should `system()` also gain https://github.com/neovim/neovim/issues/4970 ?

**Comment by ZyX-I** [comment]
Actually based on my observations Vim adds VIM and VIMRUNTIME environment variables while Neovim adds VIMRUNTIME and NVIM_LISTEN_ADDRESS environment variables if you check at `--cmd`. `VIM` environment variable is added by Neovim if it was somehow accessed (e.g. `nvim -u NONE -i NONE -c '!env > /tmp/nvim.env' -c cq` does not add it, but without `-u NONE` it does), same for `MYVIMRC` (with my setup without `-u NONE` I see adding VIMRUNTIME, NVIM_LISTEN_ADDRESS, VIM, MYVIMRC in Neovim (only standard plugins plus powerline which now fails with exception because I am not on editors-refactor branch currently); VIMRUNTIME, VIM, MYVIMRC, XDG_DATA_HOME, LC_MESSAGES, LC_ALL in Vim (many plugins)).

**Comment by ZyX-I** [comment]
@justinmk These variants are not for running interactive apps which Vim is. So the question is whether you expect somebody running Vim “in a batch mode” without `-u NONE` from system() (possible in some plugins) and whether you expect to run terminal emulator from `:!` or `system()` and run Vim there. If you do then these should be taken out. If not, better keep them. Then also needed to take into account if there are some scripts which expect to be run from `:!` / `system()` / `jobstart()` and see environment variable there.

Actually I would say that Vim is right in doing so because it does not and should not expect these variables to be used not from Vim. We would be also right if we were using `NVIM` and `NVIMRUNTIME`, but we chose not to and are now facing various problems.

Though “right thing to do” (but highly incompatible) here in my opinion is removing use of $VIM, $VIMRUNTIME, $MYVIMRC in editor and replacing that with `v:` variables: this way you are not special-casing any environment variables read access: i.e. `echo $VIM` will not make new environment variable suddenly emerge from the void as well as there will be no situation where `:echo $VIM` shows one thing and `:!echo $VIM` another.

**Comment by justinmk** [comment]
- fix for $NVIM_LISTEN_ADDRESS https://github.com/neovim/neovim/pull/11009 
- fix for VIM, VIMRUNTIME: #18388
