### ISSUE TITLE
BCE issue under tmux.

### ISSUE THREAD

**Issue by raghur** [neovim/neovim#6845]
- `nvim --version`: 0.2.1-dev
- Vim (version: ) behaves differently? Yes (8.0 - patches - 1 - 601)
- Operating system/version: KDE Neon User
- Terminal name/version: tmux 2.3
- `$TERM`: xterm-256color

### Actual behaviour
With nvim, BCE issues running under tmux. Vim, with the following snippet, works fine
```
if &term =~ '256color'
   set t_ut=
endif
```
 
### Expected behaviour
nvim terminal UI also works fine under tmux and BCE issue is resolved.

### Steps to reproduce using `nvim -u NORC`
Start tmux
start nvim and set colors to a 256 color scheme. I have `:colors kalisi`
try `:h =~`

![screenshot_20170604_211102](https://cloud.githubusercontent.com/assets/516267/26763134/325c9016-496b-11e7-84bf-fea06d5fa30f.png)

**Comment by justinmk** [comment]
This is a regression compared to 0.2 , right?

**Comment by raghur** [comment]
I'm not sure - I just tried this now under tmux and then compared with vim 8.

**Comment by jdebp** [comment]
From [the very top of the tmux FAQ document that comes with it](https://github.com/tmux/tmux/blob/2.3/FAQ#L4):

```
******************************************************************************
* PLEASE NOTE: most display problems are due to incorrect TERM! Before       *
* reporting problems make SURE that TERM settings are correct inside and     *
* outside tmux.                                                              *
*                                                                            *
* Inside tmux TERM must be "screen" or similar (such as "screen-256color").  *
* Don't bother reporting problems where it isn't!                            *
```

`tmux` does not, out of the box, set your `TERM` environment variable to `xterm-256color`, nor should you be doing so within a `tmux` session.  You are seeing the results of your making this error.  The `xterm-256colour` terminfo description is wrong for your tmux terminals, and _says the wrong things about them_.  In particular, as this shows ...

```sh
jdebp %infocmp -d xterm-256color tmux-256color|head -n 8
comparing xterm-256color to tmux-256color.
    comparing booleans.
        bce: T:F.
        ccc: T:F.
        hs: F:T.
        mc5i: T:F.
        npc: T:F.
    comparing numbers.
jdebp %
```

... it says that your terminal has BCE.  Ironically, you are having to cope with that in vim, too.  That's what your explicitly setting `t_ut` is doing, turning off a capability that you said was on because _you are telling programs the wrong terminal type for your terminal_.

nvim does not have a `t_ut` option that you can turn off in order to override what is in terminfo.  This is a difference from vim that you will find documented under `:help termcap-options`.  What is in terminfo is authoritative, and if you told nvim with an incorrect terminfo type that your terminal has BCE, then nvim is going to think that your terminal has BCE, and you will get the results as above.  Your little script snippet using `&term` and `set t_ut` _has zero effect_ on nvim.  You cannot bddge around your erroneous terminal type with this like you were bodging around it on vim.

tmux sets the `screen` terminal type in your `TERM` environment variable.  Strictly speaking, this is wrong too.  There's [a real terminfo entry named `tmux`](http://invisible-island.net/ncurses/terminfo.ti.html#tic-tmux) that is there for tmux terminals and that describes them correctly. There's also a `tmux-256color` entry.  These were [added to terminfo by the tmux author in 2015](http://invisible-island.net/ncurses/terminfo.ti.html#t20150502).

You get away with misdescribing `tmux` as `screen` more often because there are fewer differences between the terminfo entry for `screen` and what a tmux terminal actually does than there are between the terminfo entry for `xterm` and what a tmux terminal actually does.  In particular, the `screen` entry ...

```sh
jdebp %infocmp -d screen-256color tmux-256color|head -n 4
comparing screen-256color to tmux-256color.
    comparing booleans.
        hs: F:T.
    comparing numbers.
jdebp %
```

... agrees with the `tmux` entry about BCE. They both say that the terminal does not have BCE.  But they disagree on shifted function and cursor movement keys, status line control sequences, standout, and italics.  All of these will function oddly if you misdescribe a tmux terminal by pointing programs at the `screen` terminfo entry with `TERM`.  (As of version 2.1, you can tell tmux to pretend to be a `screen` terminal.  But tmux won't know to do this if all that you are doing is changing your `TERM` environment variable for the programs running on the tmux terminal.  That's not the way to _tell tmux_ to pretend that it is a screen terminal.)

This is why the tmux manual states, under the description of the `default-terminal` option:

> For tmux to work correctly, this must be set to `screen`, `tmux` or a derivative of them.

Not `xterm`.  Not anything `xterm`-derived.  `tmux` for preference, or `screen` if you must.

Your steps to reproduce do not exhibit this behaviour when you use `term-256color` or `screen-256color`.  nvim properly handles BCE if you tell it the right terminal type.

**Comment by justinmk** [comment]
Thanks @jdebp , I should have noticed that. TERM absolutely must be set to `screen-256color` or `tmux-256color` with nvim, this is covered by `:CheckHealth`.

**Comment by raghur** [comment]
@jdebp thanks for the detailed explanation. Setting `tmux-256color` in .tmux.conf does the trick.
