### ISSUE TITLE
Rendering artifacts

### ISSUE THREAD

**Issue by gmile** [neovim/neovim#6849]
- `nvim --version`: NVIM v0.2.1-279-g01838309
- Operating system/version: macOS Sierra / 10.12.2 (16C68)
- Terminal name/version: Version 2.7.1 (388)
- $TERM: xterm-256color

### Actual behaviour

Artifacts are rendered. See gif:

![bug_with_master](https://cloud.githubusercontent.com/assets/207112/26791364/87631314-4a1f-11e7-9fed-b131fbb397fe.gif)

### Expected behaviour

Visual artifacts are not rendered.

### Steps to reproduce using `nvim -u NORC`

No yet. This seem to work fine under `nvim -u NORC`.

On gif I'm using Ctrl+d / Ctrl+u to jump over text.

---

Anything I could run to extract more out info this issue?

**Comment by jamessan** [comment]
This is likely the same as https://github.com/neovim/neovim/issues/6802 which should be improved by https://github.com/neovim/neovim/pull/6816, if you're able to test that out.

**Comment by gmile** [comment]
@jamessan thanks for pointing out the issues, I just didn't know what keywords to search for before opening this one.

For the record, after looking at #6802 I tried the following to work around the problem (I use fish-shell):

```
env TERM="" nvim
```
I can definitely live with this until #6816 while is being worked on.

**Comment by jdebp** [comment]
Note that per jwilm/alacritty#578 alacritty has its own terminal type and terminfo entry.  It's not correct to use the `xterm` or `xterm-256color` terminfo entries to describe it.  

I mention this because it looks like you have some sort of BCE mis-match, there, in addition to the known and fixed scrolling problem.  I don't know whether alacritty has BCE or not, although looking at that screen I suspect not.  

For the reasons that I have just laid out in #6845, it is important to use the `alacritty-256color` (or whatever they settle upon) terminfo entry with alacritty in order to avoid any problems caused by differences between the terminfo entry for Xterm and what alacritty actually does.
