### ISSUE TITLE
change nvim intro language

### ISSUE THREAD

**Issue by jysuk7394** [neovim/neovim#6864]
I want change nvim intro and error message language

![default](https://user-images.githubusercontent.com/17741877/26912059-cc84844e-4c4c-11e7-916b-fb03fe75c789.png)

I want to change that sentence like this. 
E492: Not an editor command: dfs  --------> E492: 편집기 명령이 아닙니다: dfs (Korean language)

I tried to use ko.UTF-8.po file and tried using neovim's localization and google but it failed.
How can I apply this file to change the language of the intro screen and error message?

**Comment by jdebp** [comment]
I cannot reproduce this problem (in current master, although I suspect that to be irrelevant) on FreeBSD.

`LC_ALL= LC_MESSAGES=ko_KR.UTF-8 nvim -c 'dfs'`
when invoking nvim from a shell works as desired in FreeBSD.

These environment variables are as documented in the operating system's `environ(7)` user manual page, and are also already documented in the nvim doco under `:help language` and `:help v:lang`.

I _can_ however reproduce the problem on Debian Linux, which documents the variables in `locale(7)` as well.  This is because the C runtime library refuses to set that as a locale.

```
jdebp %LANG= LANGUAGE= LC_ALL= LC_MESSAGES=ko_KR.UTF-8 locale | head -n 2 
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=
LANGUAGE=
jdebp %
```

This is not an nvim problem.  Make sure that your operating system is configured so that the C runtime library accepts this locale.

**Comment by justinmk** [comment]
This was already answered in https://github.com/neovim/neovim/issues/6857#issuecomment-306820583
