### ISSUE TITLE
jemalloc v.5.0 , nvim compatibilty issues?? jemalloc v4.5 works perfectly ??

### ISSUE THREAD

**Issue by narutowindy** [neovim/neovim#6895]
NVIM v0.2.0
Arch linux - Operating system/version:
URXvt- Terminal name/version:

### Actual behaviour
it didnt even start
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by jamessan** [comment]
Since you only hit this when using a newer jemalloc, it's unlikely to be a neovim issue.  Also, there is an existing jemalloc [issue] and ArchLinux [bug] that seem to be tracking this, so I'm going to close this in favor of those.

[issue]: https://github.com/jemalloc/jemalloc/issues/907
[bug]: https://bugs.archlinux.org/task/54447
