### ISSUE TITLE
vim syntax error

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#6909]
- `nvim --version`: master
- Vim (version: ) behaves differently? no, this error also happened in vim8
- Operating system/version: arch
- Terminal name/version: termite
- `$TERM`: xterm-termite

### Actual behaviour
![2017-06-18_937x151](https://user-images.githubusercontent.com/13142418/27260792-5696f0fa-5467-11e7-89f3-c704b48d1c49.png)

### Expected behaviour

should same as 

![2017-06-18_901x74](https://user-images.githubusercontent.com/13142418/27260796-711ae53a-5467-11e7-87eb-eb47c59cd0e7.png)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

here is example vim file

```vim
    let g:_spacevim_mappings_g['m'] = ['call feedkeys("gm", "n")', 'go to middle of screenline']
    nnoremap gm gm
    let g:_spacevim_mappings_g['o'] = ['call feedkeys("go", "n")', 'goto byte N in the buffer']
    nnoremap go go
    let g:_spacevim_mappings_g["s"] = ['call feedkeys("gs", "n")', 'goto byte N in the buffer']
    let g:_spacevim_mappings_g['s'] = ['call feedkeys("gs", "n")', 'goto byte N in the buffer']
    nnoremap gs gs

```

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim.

Syntax plugins (e.g. for ruby/java/YAML) are maintained by the maintainer listed at the top of the plugin file. Please report to that person, or to https://github.com/vim/vim. Thanks!

**Comment by wsdjeg** [comment]
@justinmk ok, thanks, I this this issue has not been fixed in latest version of vim, so I will report it to vim mail list.
