### ISSUE TITLE
Output from system('cmd') includes error from shell with non-existing cwd

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#6918]
- `nvim --version`: v0.2.1-338-g18e7cd9e9
- Vim (version: 8.0.628) behaves differently? Yes
- Operating system/version: Arch Linux

### Actual behaviour

Using `system()` in a non-existing current working directory will include an error from the shell at the top of the output (on stdout).

### Steps to reproduce using `nvim -u NORC`

```
1. mkdir /tmp/foodir
2. cd /tmp/foodir
3. nvim -u NORC
4. `:let &shell = '/usr/bin/bash'`
5. `:!rmdir /tmp/foodir`
6. `:echo system('echo 1')`
```

Output with Bash as shell:
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file
or directory                                                                                          
1
```

Output with Dash as shell:
```
sh: 0: getcwd() failed: No such file or directory
1                                                
```

With `zsh` as shell there is no error.

In Vim, the "shell-init" / "sh" error gets not displayed, even when redirecting stderr (`system('echo 1 2>&1')`).

When using a list for the args (`system(['echo', '1'])`) it is not a problem.

**Comment by blueyed** [comment]
Ok, it is a problem with `:echo system('sh -c "echo 1"')` in Vim, too - so it depends basically on if the shell is used or not (`system('echo 1')` in Vim behaves like `system(['echo', '1'])` in Neovim).

Therefore it boils down to `system('echo 1')` using the shell in Neovim, but not Vim - and that is known / by design IIRC.

**Comment by ZyX-I** [comment]
@blueyed Vim uses the shell *always*, there is no way to avoid that:

```
% strace -f -e execve vim -u NONE -i NONE -N --cmd 'echo system("echo 1")' --cmd cq
execve("/home/zyx/bin/vim", ["vim", "-u", "NONE", "-i", "NONE", "-N", "--cmd", "echo system(\"echo 1\")", "--cmd", "cq"], [/* 81 vars */]) = 0
strace: Process 2779 attached
[pid  2779] execve("/bin/zsh", ["/bin/zsh", "-c", "(echo 1) > /tmp/vt4EjDC/0"], [/* 83 vars */]) = 0
[pid  2779] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=2779, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
1

+++ exited with 1 +++
```

The difference should be either along the lines which shell is used exactly or how code is decorated for the shell (I mean `(` and `) > /tmp/…` parts). The Neovim is using pipes so there is much less decoration and you can’t ignore stderr by simply setting wrong `&shellredir` setting:

```
% strace -f -e execve bin/nvim -u NONE -i NONE -N --cmd 'echo system("echo 1")' --cmd cq
execve("bin/nvim", ["bin/nvim", "-u", "NONE", "-i", "NONE", "-N", "--cmd", "echo system(\"echo 1\")", "--cmd", "cq"], [/* 108 vars */]) = 0
strace: Process 7037 attached
[pid  7037] execve("/bin/zsh", ["/bin/zsh", "-c", "echo 1"], [/* 110 vars */]) = 0
[pid  7037] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=7037, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
1
strace: Process 7054 attached
[pid  7054] execve("/usr/bin/llvm-symbolizer", ["/usr/bin/llvm-symbolizer", "--inlining=true", "--default-arch=x86_64"], [/* 110 vars */]) = 0
[pid  7035] +++ exited with 1 +++
+++ exited with 0 +++
```

**Comment by ZyX-I** [comment]
Though it is still not a bug on our side by any means, but this as well *is* a bug on Vim side because &shellredir is supposed to include stderr by default. I do not know why it does not.

Though there is a note: shell may print something to stderr *before* actually running a command and thus before redirections have any chance to be set. With Neovim using pipes such additional output will be caught. With Vim using temporary files and `&shellredir` it is not possible. Most of time there is no difference, but e.g. fish has a bad habit of sourcing all its user configuration files always (the only major player which does I know about, others either do not source any configuration when invoked as `shell -c cmd` or source only a small selected subset like e.g. zshenv files) which means that possibility of something going wrong is significantly higher.
