### ISSUE TITLE
No true colors in TERM=tmux-256color after recent tui refactors

### ISSUE THREAD

**Issue by sakhnik** [neovim/neovim#6982]
- `nvim --version`: [105d680 Merge #6816 'TUI improvements'](https://github.com/neovim/neovim/commit/105d680aea9f449c118520597a822e834a00c0ac)
- Vim (version: ) behaves differently? [1ae7744 lint](https://github.com/neovim/neovim/commit/1ae7744f42fe60ebc2caa383be4d17e714c71c5f)
- Operating system/version: Arch testing
- Terminal name/version: gnome-terminal-3.24.2, tmux-2.5
- `$TERM`: tmux-256color (inside xterm-256color)

### Actual behaviour
Monochrome when `termguicolors` is set, basic colors when `nvim -u NORC`

### Expected behaviour
True colors when `termguicolors` is set.

### Bisect result

```
16300d02c7fbe95396697fc6c09012e2c2b47b69 is the first bad commit
commit 16300d02c7fbe95396697fc6c09012e2c2b47b69
Author: Jonathan de Boyne Pollard <J.deBoynePollard-newsgroups@NTLWorld.com>
Date:   Sat May 27 12:38:14 2017 +0100

    tui: Improvements to RGB colour support.
    The details are in the on-line help under :help true-color .
    
    The brief precis is that nvim is (I hope.) converging with tmux and libvte.
    It is taking the same approach with setrgbf and setrgbb terminfo capabilities
    that it does with the Ss and Se terminfo capabilities.
```

**Comment by justinmk** [comment]
This is something I feared. @jdebp what are you plans here? `termguicolors` is a directive that isn't really optional.

**Comment by DarkDefender** [comment]
If I understand the code correctly then the only terminals that use the  "standard" rgb with colons instead of semicolons are xterm and all VTE based terminals.

But I found this page that seems to have other information:
https://gist.github.com/XVilka/8346728

If this page is to be trusted, then all terminals including VTE support semicolons. Most only supports semicolons but some supports both (I don't see any that just supports colons). So I don't really get why we would have two different code paths if we just could use semicolons always...

I can confirm that semicolons works with VTE (I tested this in xfce4-terminal):
```
printf "\x1b[38;2;255;100;0mTRUECOLOR\x1b[0m\n"
```
Because true color is toggled on by the user and not a standard setting, I don't think we should guard the true color support with a term check. Because as it says in the code, it's really hard to see if the terminal really supports true color or not. So I think this should be left to the end user to handle

**Comment by DarkDefender** [comment]
https://github.com/neovim/neovim/pull/6816/commits/16300d02c7fbe95396697fc6c09012e2c2b47b69

I think just reverting the above commit that changed this should be fine. But I guess that the old terminal "if guard" could be removed because the rgb stuff is not called if true color support is not enabled, right?

**Comment by kazuoteramoto** [comment]
I think tmux is getting wrong detect was `has_standard_rgb`, trying to print rgb with colons inside st+tmux don't work for me.

I workaround that works for me is setting `COLORTERM=truecolor`. Again, I'm using st and tmux.

**Comment by jdebp** [comment]
There's a lot of confusion in this bug report.  First of all, the TUI subsystem does not set `termguicolors`.  It _reads_ it.  It is set by the user.  Second, the code does not "guard the true colour support".  Please read and digest `:help true-color` which explains things.

If you have the new (i.e. since 2013) `setrgbf` and `setrgbb` in your terminfo, then none of the terminal type testing is involved at all.  That _only_ happens when your terminfo omits these capabilities.  I originally had the `has_non_standard_rgb` and `has_standard_rgb` booleans inside the if statements, which made this _very_ clear.  But that did make the code longer and involve calculating both flags twice.

So what is actually happening here is:
* You've specified true colour with `termguicolors` in your `init.vim`.
* You've told nvim that your terminal type is `tmux-256color`.
* But you have confused it into thinking that it is _also_ libvte by allowing the `VTE_VERSION` environment variable to propagate down into your tmux session.
* There are no `setrgbf` and `setrgbb` capabilities for the `tmux-256color` entry in your terminfo database.
* nvim does not include `tmux` on the list of terminal types where it makes up `setrgbf` and `setrgbb` entries.
* But it does include libvte, and use the proper way of doing things that the VTE people themselves encourage.
* So nvim turns on the true colour support for libvte.

The libvte check is clearly too aggressive; and tmux needs to be on the list.

I have fixed these as 139abca7e9792217af3ac20d812d233dbce2f10f .

**Comment by DarkDefender** [comment]
@jdebp This is not only a problem with tmux, I also do not get colors anymore when using alacritty.

As I said before, I don't see the need to have two code paths (colon,semicolon) when it seems like all terminals supports semicolons.

I also feel that because the user has to manually specify `termguicolors` in `init.vim`, we can simply the code and not check for any terminal types. After all, if the user has specified it, it is highly likely that the terminal they are running can render rgb colors with semicolons in the code.

If they do not have terminal that supports true color, then it should be obvious that it is not working as intended anyways.

So what I'm saying is that I don't really see the point of having a huge if else statment block if it seems like everything should work with one code path.

**Comment by jdebp** [comment]
We have _two_ if statements, one in the TUI subsystem, which has had a lot of testing done on it and does the right thing; and one in everyone's `init.vim` which looks like what you can see under `:help term-dependent-settings` and which most people are going to do a half-hearted job of.

What I would like to see is the _latter_ gone, _not_ the former.  The TUI subsystem is working out what terminals support true-colour, using definitive information in terminfo and a fallback of looking at environment variables.  Really there is no need to have users repeating exactly the same logic in their `init.vim`.  Badly.  Especially since they lack the ability to inspect terminfo from `init.vim`.

The problem is that the communication over the UI boundary seems to go only one way.  The TUI layer has worked all this out, but has not the means to tell upper layers about it.  Rather, and somewhat perversely, _they_ try to tell _it_ whether indexed or direct colour is in use.

More succinctly: #5089 is in fact still a bug.

Using the standards-conformant output where it is known to be possible _is_ the right thing to do, and using non-conformant output _is not_.  The non-conformant output is ambiguous.  Consider this part of the push, [by the Xterm people](http://invisible-island.net/xterm/xterm.log.html#xterm_282), [by the iTerm2 people](https://gitlab.com/gnachman/iterm2/issues/218#note_1158345), [by the VTE people](https://bugzilla.gnome.org/show_bug.cgi?id=685759), [by the Konsole people](https://bugs.kde.org/show_bug.cgi?id=107487), [by the TeraTerm people](https://osdn.net/projects/ttssh2/scm/svn/commits/5073), and now by the Neovim people, to actually _make this right_.  It is wrong to push for regression back to doing the wrong thing.

**Comment by DarkDefender** [comment]
I still do not get why we have two code paths for colon codes and semicolon codes.
I've tested with both xterm and libvte, and they seem to support semicolons also. And it also seems like this is the case for iterm. So why do we even have `has_standard_rgb` and `has_non_standard_rgb` to begin with?

To me, it seems like the semi color is now the standard so to speak, because that is what works with most if not all true color terminals.

If i understand the current TUI code correctly, then the current truecolor support is guarded by either getting a high enough VTE version or specific `TERM` names. I think this is the wrong way to solve this. Or do you want a push to force all true color terminals to set `COLORTERM=truecolor`. Otherwise I feel that it will be a pain in the ass to have a long list of terminals when it seems like most modern ones now supports true color out of the box.

**Comment by DarkDefender** [comment]
I think we should do a black list instead of a white list for this...

**Comment by caiocutrim** [comment]
colors like oceanic-next only works with sudo nvim after this update :(

**Comment by fszymanski** [comment]
Regression after 8898793.

**Comment by DarkDefender** [comment]
@fszymanski You have to be a bit more specific than that.

**Comment by fszymanski** [comment]
I have almost the same setup as @sakhnik (but i'm on Fedora). Monochrome when `termguicolors` is set (exactly as in the [#1](https://github.com/neovim/neovim/issues/6982#issue-241426875) comment). After 6725667 everything was fine.

**Comment by DarkDefender** [comment]
If you do `VTE_VERSION=0 nvim` does the colors work then?

**Comment by fszymanski** [comment]
Yes.

**Comment by DarkDefender** [comment]
@fszymanski #7037 should fix it.
