### ISSUE TITLE
Release/distribution strategy

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#700]
Our release model affects the way we organize/separate repositories. It may be too early to decide any of this, but I think we should at least begin collecting ideas. @tarruda may have a vision for this already, in that case this issue will serve to clarify.

related: #633

- What will the installable Neovim package include? Will we deliver only the core, which downloads the appropriate GUI for the system it's being installed on? 
    - **Decision [0.1 milestone]:** the core includes a TUI. On Windows, we will package a GUI.
- Will we offer GUI/frontend updates through the plugin manager (so that user running core version X may update the frontend to version Y)? 
    - **Decision [0.1 milestone]:** not any time soon.
- Will the core and GUI versions be identical, or will we have core version A, Windows GUI B, terminal frontend version C, etc.?
    - **Decision [0.1 milestone]:** the Neovim core will be versioned separately from the API. 
- Will the docs repo contain GUI-specific docs, or will there also be GUI-specific docs repos?
    - **Decision [0.1 milestone]:** docs distributed by the Neovim project will be the same for all targets.

**Comment by tomprince** [comment]
> I deeply want this to happen. We'll need to just figure out some licensing issues (?). 

As long as the software is just being provided side-by-side (not linked together), you can bundle software that uses different licenses together, as long as the over license allows all the things required by the individual licenses, for each of the parts. This is what Linux distributions do, for example. See
- http://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation
- http://www.gnu.org/licenses/gpl-faq.en.html#GPLInProprietarySystem

**Comment by justinmk** [comment]
Updated original post with decisions, which are also written in the project guidelines (yet to be published).

**Comment by timofonic** [comment]
Why the core must include a TUI? Isn't a better approach to modularize? I don't mean separate repositories, but separate packages. There could be different TUIs too.

- Different language: C, C++, Lua, Python.

- Different toolkit: [STFL](http://www.clifford.at/stfl/) [libtcodt](http://roguecentral.org/doryen/libtcod/), [Slang](http://www.jedsoft.org/slang/) ...
  * Many of them have bindings for different programming languages: C, C++, Lua, Python, Ruby, Rust...
- https://github.com/pupnik-/luajittcodA TUI developed in Slang

Or many environments would chose to use some lightweight GUI approach such as [Agar GUI](http://libagar.org).

Why do you prefer a BSD-like license? I see it dangerous, because NeoVim could someday become enough interesting a company can fork it and do something like a Sublime Text product but more lightweight (for example). Making it LGPL could avoid that issue.

Acording Richard Stallman, the Vim license is GNU GPL compatible. Would it be LGPL compatible too?
