### ISSUE TITLE
Tutor: remapped "n" key  doesn't work 

### ISSUE THREAD

**Issue by GeneralFailer** [neovim/neovim#7005]
I'm using jooize/vim-colemak plugin to remap keys and "n" seems to get mapped to left instead of down when using Tutor. When editing documents this mapping works fine.

- `nvim --version`: 0.2.0
- Operating system/version: Arch Linux

**Comment by justinmk** [comment]
Is Tutor really all that useful if the keys have been changed?

**Comment by GeneralFailer** [comment]
Well, I don't think there's any good alternative. Beats sticking to the default mapping I suppose.

**Comment by fmoralesc** [comment]
Hm... there are some quirks to the way Tutor works that required this, but they could be fixed if I finally split the documents and the metadata (I hide the metadata in the document itself, so there was a need to adjust navigation in some cases - I never tested for thoroughness or considered different keyboard layouts, I must admit.). I wish I had more time to work on this!

**Comment by GeneralFailer** [comment]
[This plugin](https://github.com/unlmtd/coleremak.vim) seems to be handled properly for some reason.

**Comment by fmoralesc** [comment]
(So, I made time to sort this and the other problems in Tutor-mode)

@GeneralFailer Does this issue go away if the calls to `s:MapKeyWithRedirect` in `tutor#SetNormalMappings` (in `autoload/tutor.vim`) are commented out? 

What those do is to map h, l, left and right so that they skip concealed characters in the buffers, and I would like to know what happens if you execute `call tutor#ForwardSkipConceal(1)` directly.

**Comment by GeneralFailer** [comment]
Yes, it does.
Nothing, it seems.
