### ISSUE TITLE
UI: Support partially transparent colours

### ISSUE THREAD

**Issue by zacps** [neovim/neovim#7064]
Currently (neo)vim supports completely transparent colours with:
```vim
hi Normal guibg=none
```
It would be nice to be able to use partially transparent colours for areas such as the status line or number column. This would require supporting a new colour format, namely ARGB or RGBA.
Then you could do something like:
```vim
hi LineNr guibg="argb:E6D3D3D3"
```

**Comment by zacps** [comment]
As far as I can tell no terminals currently support partially transparent colours so this would only be useful for GUI frontends. I still think this is a useful feature, it's even possible it could serve as motivation for terminals implementing partially transparent colours.

**Comment by jep-dev** [comment]
I'm interested in this topic even if any possible 'solutions' are impractical. A quick disclaimer - I just installed Neovim and don't know what it does under the hood, so I'm not sure how much of this is relevant.

With regular ANSI escape codes, you can specify rgb24 (r8+g8+b8); in theory you could reinterpret those as a6+r6+g6+b6 or a3+r7+g7+b7 depending on your priorities. If you take visual accuracy into account, a better 16-bit distribution is r5+g6+b5.
At this point you can use principals from (naive) steganography: instead of encoding the alpha channel as a contiguous N bits at the head or tail of the color, and effectively guaranteeing incompatibility between alpha-encoded colors and regular RGB, you can distribute those N bits over the least significant bits of the original RGB channels, e.g. r5a3+g6a2+b5a3 = a8+r5+g6+b5 for alpha decoders and r8+g8+b8 (with r5+g6+b5 real color and some "noise".) Obviously you would have to fill these bits when importing color schemes.

When it comes to rendering these bits, I would start with SIXEL for xterm/screen and then look at Alacritty/Kitty/etc. to bridge the gap between emulators and GUI's. I never got Kitty to build, but Alacritty worked great, faster than Tilda and Guake and capable of 24bit color and SIXEL if I recall correctly. It had some quirks that I assume are being addressed already. In any case, it's supposed to be a muxer at the framebuffer level, instead of the terminal level like Tmux, so compositing, blitting, etc. should be no problem. I definitely got SIXEL working properly in xterm after building from the source, but for me it was a proof of concept - I didn't put in the time to see if it could emulate X, stream videos, and everything else it's capable of.

Sorry for the wall of text, especially if I'm completely off base. I just can't help but think there's a way around limitations like that, especially after I saw [8088 MPH](https://www.youtube.com/embed/hNRO7lno_DM).

**Comment by justinmk** [comment]
Source code for the TUI is in `src/nvim/tui/` if you want to send a patch.

In general though I don't understand why you would want to implement an "impractical" GUI-like features in a terminal if you can do it the other way around. Projects like https://github.com/rhysd/NyaoVim/ and https://github.com/extr0py/oni/ , and many other (even your own) custom UIs that embed `nvim` can add whatever features they want, while still being able to multiplex terminals using the nvim `:terminal` command.

**Comment by jep-dev** [comment]
Well, it would be 'impractical' if the implementation turned out to be slow, but that doesn't have to be the case; in any case, I wasn't saying I would want the features added if they turned out to be impractical, but that I would want to know if and how it can be done, and why it would be impractical otherwise, at least academically. At best I was hoping my response would be a good lead toward implementation, or an opportunity for someone to tell me why it's a dead end before I try to hack it alone.
As for 'GUI-like features in a terminal' - why else do we have 8- and 24-bit colors and transparency in Vim instead of just GVim, not to mention the terminals themselves? I see it as a separation of concerns - ideally my emulator or GUI is just a viewport into the TUI, which I aim to make self-sufficient and fully portable without discrepancies. I basically feel the opposite - if the terminal is capable of GUI-like features, why would you rely on a GUI anyway? I don't expect Neovim to operate on the same principals, but that was certainly what attracted me to Vim and its incarnations. If only the fringe of users are interested in a feature like this, or it's prohibitively difficult to implement, so be it, I'm more justifying the interest than the necessity of the feature. Thanks for the links, hopefully I'll be able to contribute.

**Comment by justinmk** [comment]
The ['pumblend' feature](https://www.reddit.com/r/neovim/comments/aoeai3/semitransparent_popupmenu_is_awesome/) in Nvim 0.4.0 demos how this "fake alpha" feature could work.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/9923 adds `:highlight blend=...`.
