### ISSUE TITLE
Add list of recommended neovim/vim plugins and settings for Neovim developers in CONTRIBUTING.md

### ISSUE THREAD

**Issue by docwhat** [neovim/neovim#7075]
As a developer who is new to working on Neovim, I would like a recommended list of plugins and settings I use.

This would:

- Speed up my development in Neovim.
- Ensure I meet the style preferred by the Neovim team.

Some ideas:

- `Shougo/deoplete.nvim` — Completion
    - `tweekmonster/deoplete-clang2` — clang2 completion support
- `tweekmonster/nvimdev.nvim` — Neovim plugin for working on Neovim
- `tweekmonster/helpful.vim` — A plugin for plugin developers to get the version of Vim and Neovim that introduced or removed features.
- `tbastos/vim-lua` — Enhanced Lua 5.3 syntax indentation
- `neomake/neomake` — Listing
- `dbakker/vim-lint` — Lint VimL
- `editorconfig/editorconfig-vim` — Helps developers define and maintain consistent coding styles. http://editorconfig.org/

**Comment by Shougo** [comment]
Wiki exists though...
https://github.com/neovim/neovim/wiki/Related-projects#plugins

**Comment by docwhat** [comment]
@Shougo: I'm sorry, I wasn't clear.  I meant only for _contributing_ to Neovim.  Not general plugins.  I'll clarify my text above.

**Comment by mhinz** [comment]
This shouldn't be put in the repo, but in the wiki. This makes it easier to maintain those lists without flooding the git history.

E.g. https://github.com/neovim/neovim/wiki/Development-tips mentions nvimdev already.

**Comment by justinmk** [comment]
We should have some sort of plugin (or "pack") that can be easily installed, if not part of the repo.

**Comment by docwhat** [comment]
That'd be a cool place to add the list of plugins.

I moved my list into there.

**Comment by justinmk** [comment]
Does the "Enhanced Lua 5.3 syntax indentation" help with 5.1? We don't use 5.3...

**Comment by docwhat** [comment]
I'm not sure.  I don't speak enough Lua to be sure.  But I was dinged on a lack of indentation in a PR and the plugin fixed it. #6272 (near the end)

**Comment by justinmk** [comment]
Though this is planned, I don't want to keep this issue open, because I'll never remember to close it, and no one seems to be taking it as a call to action, either.

**Comment by deadlysyn** [comment]
hi folks,

i know this has been closed... but wonder if you still need a volunteer.  i've been working on updating and optimizing my 20+ year vim config to be "neovim-optimized" so tweaking out on configs and doing a lot of research to try and optimize performance balanced with functionality.  as part of that, a random google search brought me here.

i doubt you'd want my full config (still very much in progress, lots of completion/linting tuning WIP and optimized for go+javascript), but based on what i learn i could perhaps provide a "neovim-dev" similarly optimized but tuned specifically for neovim development.

assuming there's interest, i would have the following questions:

- @docwhat provided a good starting point, but are there other plugins, shortcuts, etc other neovim devs find indispensable?
- what platforms are folks developing on?  is there common ground, or ?
- terminal vs gui -- my config is optimized for term, any gui users?
- colorschemes (holy war time) -- any common ground, ux thoughts, light/dark preferences, etc.

i know this is not all plugin related, but my thinking is more in line with @justinmk on a "pack" where new neovim devs simply run a script and have env configured in such a way it's easy to follow similar styling, best practices and even key combos when pairing.

if this is already take care of, sorry for the noise...  just trying to find a way to contribute back to neovim since it is freaking awesome and i love the project.  :-)  if help is needed, then i'd like to treat this as a "product" and start with lots of user feedback.

thanks!

**Comment by KillTheMule** [comment]
Check out https://github.com/neovim/neovim/wiki/Development-tips#neovim-plugins, if you're interested in the dev environment.
