### ISSUE TITLE
Unable to set titlestring during VimLeave

### ISSUE THREAD

**Issue by silvioricardoc** [neovim/neovim#7129]
### Version info
- `nvim --version`: 0.1.7
- Vim (version: 8.0) behaves differently? Yes and no (it restores the original title, but also ignores an explicit titlestring).
- Operating system/version: Ubuntu 17.04
- Terminal name/version: GNOME Terminal 3.20.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```vim
:set title
:set titlestring=InsideNvim
:autocmd VimLeave *  set titlestring=Terminal
:q!
```

### Expected behaviour
The title should change to "Terminal" on vim exit. This is intended as a hack to work around issue #4063.

### Actual behaviour
The title stays as "InsideNvim" when neovim exits. I also tried with VimLeavePre, including explicit `set title` and `set notitle` commands inside the autocmd: same results. With any other autocmd group, it does work.

**Comment by justinmk** [comment]
0.1.7 is almost 1 year old, I don't think this is an issue on 0.2.0, based on https://github.com/neovim/neovim/issues/6942#issuecomment-312433764

**Comment by nateozem** [comment]
I'm looking into this and I have a few thoughts on this from my debug session.
First is my report from what I'm seeing:
* When call `set titlestring`,  the application will call `resettitle()` twice. One with the old title and one with the new one that I had given.
* With `VimLeave` set and before the application quits, I do a call to `resettitle()`, but not with the correct title. My guess, this is the effect caused by my previous point.

Please let me know if any one had seen this.

I believe I'm getting close to the problem and it must within these frames. 
```
frame #6: nvim`do_cmdline(cmdline=0x0000000000000000, fgetline=(nvim`getnextac at fileio.c:7061), cookie=0x00007fff50c00d80, flags=7) at ex_docmd.c:608
frame #7: nvim`apply_autocmds_group(event=EVENT_VIMLEAVE, fname="", fname_io=0x0000000000000000, force=false, group=-3, buf=0x00007fb4b401f800, eap=0x0000000000000000) at fileio.c:6889
frame #8: nvim`apply_autocmds(event=EVENT_VIMLEAVE, fname=0x0000000000000000, fname_io=0x0000000000000000, force=false, buf=0x00007fb4b401f800) at fileio.c:6534
```
I'll supply more details later.
Please let me know if I'm getting close or not.

**Comment by justinmk** [comment]
Actually the `titleold` option exists for this purpose. Looks like it was unintentionally removed in 3baba1e7bc66 (look for `mch_restore_title`). Should be trivial to restore that functionality.

**Comment by nateozem** [comment]
Good to know. Thanks for the tip.
