### ISSUE TITLE
4k screen and scrolling messing up text

### ISSUE THREAD

**Issue by lukatendai** [neovim/neovim#7133]
NVIM v0.2.1-660-g2753d61e4
Build type: Release

When scrolling on 4k screen, some text gets messed up. 

See the screen shot.

![screenshot from 2017-08-08 07-43-35](https://user-images.githubusercontent.com/3442034/29070770-ae812a82-7c0e-11e7-9c1f-0981e9bbe550.png)

**Comment by lukatendai** [comment]
oh, 97;32H731   case "tab": comes from a few lines above

**Comment by lukatendai** [comment]
I tested with Gnome Terminal, Tilix and Konsole and everywhere is the same behavior... it also does not matter if you scroll or moving cursor down or up with down/up arrows or Page Down/Up

**Comment by justinmk** [comment]
As requested by the issue template, we need to know 

- the exact value of `$TERM` 
- the name and version of your terminal emulator
- also: are you using tmux or screen?

**Comment by lukatendai** [comment]
Oh, yes... I forgot about $TERM... I am using xterm-256color but when I run `TERM="" nvim` then the problem disappears... I just thought that we fixed it recently.... but I guess I was wrong.

**Comment by justinmk** [comment]
> I tested with Gnome Terminal, Tilix and Konsole and everywhere is the same behavior.
> ...
> but when I run TERM="" nvim then the problem disappears... 

Sounds more like your terminfo database is broken.

> I just thought that we fixed it recently.... but I guess I was wrong.

Probably we should stop listening to people's terminfo databases ...

**Comment by dumblob** [comment]
>Probably we should stop listening to people's terminfo databases ...

IMHO a better (but annoying) solution would be to listen to people's terminfo databases, but detecting whether something is suspicious - in which case nvim would **not** recover using some "hack", but just let the user precisely know what the culprit is and show him steps how to solve it with the goal to spur the users to "spam" terminfo DB package maintainers and upstreams with bug reports, because many terminfo DBs on many systems are OK, so what's missing is to persuade the ones not being OK.

**Comment by justinmk** [comment]
can you try https://github.com/neovim/neovim/pull/7624 ?

Merging this issue with https://github.com/neovim/neovim/issues/7618
