### ISSUE TITLE
Keep the terminal buffer open after the shell closes

### ISSUE THREAD

**Issue by mox-mox** [neovim/neovim#7144]
:question: 
- `nvim --version`: NVIM v0.2.0
- Vim (version: ) behaves differently? ??
- Operating system/version: Current Archlinux
- Terminal name/version: urxvt
- `$TERM`: zsh

### Steps to reproduce using `nvim -u NORC`

In nvim:

    :tabnew | te

In Terminal:

    exit

### Actual behaviour
nvim prints `[Process exited 0]` and the next key press closes the buffer.

### Expected behaviour
Keep the buffer open until I enter `:bd` oder `:q`.

### Why and when?
I use the terminal window to run tests on my program using
		
    autocmd FileType cpp,c,ada,make nnoremap <buffer> <leader>lv :wa \| tabnew \| te make run <CR>

Where the make run target will run my program and then exit. To compare the output to the code, I would like to be able switch tabs, but the next key press kills the window.
Matters get even worse, when I use

    autocmd TermClose * bd!

as now I cannot even see the output before the window is closed. I usually I like the automatic closing, so a trick to make only certain buffers 'persist' would be even better.

p.S.: I really love nvim! Thank you for all the great work!

**Comment by justinmk** [comment]
To avoid the auto-close, just exit to normal-mode via `CTRL-\ CTRL-N`. See also `:help terminal-emulator` for tips on easier ways to exist terminal-mode.

**Comment by poige** [comment]
> To avoid the auto-close, just exit to normal-mode via `CTRL-\ CTRL-N`. See also `:help terminal-emulator` for tips on easier ways to exist terminal-mode.

In the same spirit one could tell "run shell in terminal, not in editor". Just switching to "normal mode" keeps all the PTY associated programs running and thus it's _not a proper solution_ to the question in question which was titled as "Keep the terminal buffer open **after the shell closes**".

**Comment by msaher** [comment]
you can use an autocommand to disable mappings that switch to terminal-mode.

```lua
vim.api.nvim_create_autocmd("TermClose", {
	callback = function(data)
        if not api.nvim_buf_is_loaded(data.buf) then
            return
        end
        vim.keymap.set("n", "i", "<nop>", { buffer = data.buf })
        vim.keymap.set("n", "I", "<nop>", { buffer = data.buf })
        vim.keymap.set("n", "o", "<nop>", { buffer = data.buf })
        vim.keymap.set("n", "O", "<nop>", { buffer = data.buf })
        vim.keymap.set("n", "a", "<nop>", { buffer = data.buf })
        vim.keymap.set("n", "A", "<nop>", { buffer = data.buf })
	vim.cmd.stopinsert()
    end
})
```

**Comment by pocomane** [comment]
Can you re-open this issue?

The `CTRL-\ CTRL-N` is not actually a solution since I use the terminal to run an interactive process that automatically exits at ends.

The autocommand to disable the mode switch after the terminal close is sub-optimal since I can not edit the buffer.

My use case is similar to the OP: a test program (that asks what to test at the begin). I want to be able to edit the result to make a more human readable report before send it by mail. Currently I have to copy-paste all the session in another buffer.

Moreover, keeping the buffer until the user explicitly ask to close it, just seems the correct behaviour to me (and it would be simple to write a configuration that revert to the current behaviour).
