### ISSUE TITLE
Neovim hang after/when copying large amount of data to clipboard

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7184]
- `nvim --version`:  v0.2.1-696-gbdc72c7
- Vim (version: ) behaves differently? Don't know
- Operating system/version: WSL
- Terminal name/version: conhost
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

I'm actually running `nvim -u minimal.vim` with minimal.vim containing the following:

```vim
if !empty(matchstr(system("uname -a"), "Microsoft"))
	let g:clipboard = {
	\ 'name': 'win32yank',
	\ 'copy': {
	\	'+': 'win32yank.exe -i --crlf',
	\	'*': 'win32yank.exe -i --crlf',
	\	},
	\ 'paste': {
	\	'+': 'noerr win32yank.exe -o --lf',
	\	'*': 'noerr win32yank.exe -o --lf',
	\	},
	\ 'cache_enabled': 1,
	\ }
endif
```
to get clipboard support on Windows

Afterwards, 

`:redir @+> | :echo system("cat /usr/share/dict/words") | redir END`

When the pager with the contents of `/usr/share/dict/words` appears, press `q` to close it and return to the editor.

The log reveals an endless stream of the following error:

```
5427 E474: Invalid argument
5428 Error detected while processing function 1[12]..provider#clear_stderr:
5429 line    1:
5430 E731: using Dictionary as a String
```

Presuming the error is the cause of the hang, I believe it's only a symptom of the actual problem and while it should be fixed, I think the real problem is that Neovim is blocking on this operation in the first place.

Note that there is no error when executing `cat /usr/share/dict/words | win32yank.exe -i --crlf` in the terminal.

### Actual behaviour
Neovim is hung and unresponsive to all commands.

### Expected behaviour
Neovim runs normally.

**Comment by justinmk** [comment]
>  the real problem is that Neovim is blocking on this operation in the first place.

Not sure what you mean, but deferring explicit clipboard operations that were requested by a script--or `:redir` in this case--may not be feasible. I attempted to explain in this commit message:

https://github.com/neovim/neovim/pull/7193/commits/cc7e344f8357d07b1df17df0b322152d5c50739b

`:redir @+>` internally (`ex_echo()`) is writing to the clipboard in a loop. Maybe this could be refactored, I'm not sure. 

Even in Vim writing to the clipboard can be slow, e.g. on forwarded X11. So scripts should never do this, they should batch the collection, and then do a single write to the clipboard. 

Though I agree `:redir @+>` seems like an obvious case that should be handled. But it's not so obvious, because user can do this:

```
:redir @+>
<do any random things for an entire editing session>
:redir END
```

The command executor is too dumb to anticipate the `:redir END` until the moment it sees it--even in a script. Remember: VimL is not compiled, there's no AST, and no structure.

**Comment by justinmk** [comment]
Thanks for the attentive reports. I merged https://github.com/neovim/neovim/pull/7193 somewhat in haste since you are giving close attention to this area, hopefully then you will notice if anything went wrong :)

**Comment by mqudsi** [comment]
This still needs some work, I'm afraid. (if you could please re-open).

The problem isn't with the errors that are generated, there's a separate hang that is triggered by those errors that leads to a hang in neovim which culminates in a `SIGSEGV`, and it's still in the latest `master`.

I can trigger it with the following:

```nvim -u clipboard.vim -V9/tmp/nvim.log #attached
:redir @+> | verb not_a_real_cmd | redir END
```

Depending on how quickly you escape the error, you can get ~1 second of usable interaction with the editor before it hangs, after which it will invariably SIGSEGV once enough time has passed.

The log ends with a flood of `Key not present in dictionary` errors stemming from `provider#clear_stderr`.

Same clipboard.vim as last time:

```vim
if !empty(matchstr(system("uname -a"), "Microsoft"))
    let g:clipboard = {
	\ 'name': 'win32yank',
	\ 'copy': {
	\	'+': 'noerr win32yank.exe -i --crlf',
	\	'*': 'noerr win32yank.exe -i --crlf',
	\	},
	\ 'paste': {
	\	'+': 'noerr win32yank.exe -o --lf',
	\	'*': 'noerr win32yank.exe -o --lf',
	\	},
	\ 'cache_enabled': 1,
	\ }
endif
```

nvim.log: http://termbin.com/y5i8

Unfortunately, `gdb` under WSL is garbage and hangs when the child process hangs, leaving me unable to `SIGINT` or break into the debugger to see what is happening. When a debugger is attached, the SIGSEGV does not happen (though the hang does).

**Comment by justinmk** [comment]
> Going only by the log, the hang, and the crash and absolutely nothing else, I would venture to say that there's some sort of recursion happening leading to stack exhaustion and SIGSEGV.

You nailed it. As hinted in https://github.com/neovim/neovim/commit/9882e25dc44f1165e1edc8b3898356e493b6b3fe , raising an error during `:redir @+>` tends to be recursive, because `:redir` is capturing any and all (error) messages, then it invoke the clipboard, which then again causes another error.

The `silent!` in `provider#clear_stderr()` doesn't help because `:redir` still captures `:silent!` messages.

**Comment by mqudsi** [comment]
Thanks @justinmk
