### ISSUE TITLE
How do you look up help on functions with the same name as commands?

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7196]
I haven't been able to figure out how to view the `:help` for functions that share names with native vim commands. For example, to see the documentation on the `glob()` function, I can just type in `:h glob`. But to do try and figure out how to use the `split()` function, typing in `:h split` takes you to the documentation for `:split` (like `:vs`) and not `split()` the VimL function.

I tried inserting a "man page" number into the `:h` command but that obviously doesn't work.

Any hints?

**Comment by justinmk** [comment]
Add a paren.

    :h split(

This is a partial tag. Use tab to get completion hints about tags. 

Please consider https://vi.stackexchange.com for usage questions.

**Comment by jamessan** [comment]
`:help help-context`

Basically, provide enough context to uniquely identify what type of item you're looking up.

Alternatively, since the help is all tag-based, after `:help split` opens the help window, you can use `:tselect /split` to show all the help topics that match `splt` and select which one to jump to.  Then you can use all the normal tag commands.  Note, this is described in `:help :help`.

**Comment by mqudsi** [comment]
Thanks.
