### ISSUE TITLE
Neovim Windows installer: Add "Edit with Neovim" to right click menu similar to gVim

### ISSUE THREAD

**Issue by frankie-loves-jesus** [neovim/neovim#7222]
Like the one in gVim: https://davidvielmetter.com/tricks/context-menu-issues-with-gvim-in-windows-7-x64/

Courtesy of ROFLLOLSTER @ Reddit: https://www.howtogeek.com/howto/windows-vista/add-open-with-notepad-to-the-context-menu-for-all-files/

**Comment by justinmk** [comment]
There's no installer. Instead an optional script can be shipped in the runtime. This is covered in another issue.

**Comment by frankie-loves-jesus** [comment]
Sorry, I meant upcoming installer. You guys are planning one right? Like some other user mentioned in another issue, it would drastically increase Neovim's userbase.

**Comment by justinmk** [comment]
Why is an installer needed? There are pre-built packages already (.zip for windows, .tar.gz for macOS, .appimage for linux)

**Comment by frankie-loves-jesus** [comment]
Installers offer a one-click solution I think many Windows users would appreciate, everything working straight outta the box like gVim.

**Comment by justinmk** [comment]
As a windows user, I found myself using 7-zip to unpack the gvim installer so that it wouldn't try to "install". What's missing from the Neovim .zip ?

**Comment by chrisbra** [comment]
> What's missing from the Neovim .zip ?

I usually don't care for an installer, however what I like about the gvim Windows installer is the **Edit With Vim** menu entry, that it automatically creates.

**Comment by justinmk** [comment]
I like that feature too, but why does it need an installer? In https://github.com/neovim/neovim/issues/6649 I suggested implementing a new command.

**Comment by chrisbra** [comment]
Because the command has nothing to do with editing text at all, but will do something to setup nvim in the current environment. It doesn't feel like it belongs conceptionally into the editor itself. If you don't want to use an installer, ship with at least with a `.reg` script that can be installed (probably needs admin rights) or creates a link in the `sendto` folder.

**Comment by justinmk** [comment]
`:CheckHealth` has nothing to do with editing text. Neither does `:terminal` nor job-control. Yet all of those things are good ideas, which Vim will eventually adopt.

**Comment by justinmk** [comment]
The main problem with an installer or .reg file is that it's a different process for every system. `:Install` is a command that can be used on win/mac/unix. Having to dig around in the runtime files (or help files), for system-specific tweaks is just really unpleasant.

**Comment by artur233945** [comment]
This thread is # 1 in google for "edit with neovim", the first thing I missed after "installing".

### **If you guys think _hell, I'll make an explorer item myself_, then don't waste your time.**

This is an insanely confusing and frustrated app that I just figured out how to workaround. `nvim.exe` does something very wrong right at the start, so win10 shows a popup dialog for program selection, probably thinking that first one crashed. `nvim-qt.exe` inherits that behavior. Vanilla gvim doesn't do that, nor does notepad. Also, it has to be called as `nvim-qt -- -- "%1"` for reasons that are out of reach for both mere mortals and `--help` popup. You cannot even associate it with filetypes, since default shell association goes as `program "%1"`, not as some retarded `-- --` that you must add manually via regedit. I spent entire two hours for digging that from top to bottom thanks to `:Install` theorists who didn't even care to scratch the real problem.

The registry file below is the only **way that works**:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Classes\*\shell\Open with Neovim]

[HKEY_CURRENT_USER\SOFTWARE\Classes\*\shell\Open with Neovim\command]
@="cmd /c start nvim-qt.exe -- -- \"%1\""

```

Your PATH should contain `c:\Program Files\Neovim\bin`, obviously.
I also tried and failed with these:

```
nvim-qt.exe "%1"
nvim-qt.exe -- "%1"
nvim-qt.exe -- -- "%1"
nvim.exe "%1"
# all four just open windows program selection dialog

cmd /c nvim-qt.exe -- -- "%1"
# works but retains black console window

runas /trustlevel:0x20000 "nvim-qt.exe -- -- %1"
# works but cannot manage paths with spaces
```

Even after that success, you **cannot** open the same file twice; it just shows small empty qt window with no buffer and does not indicate what happened in any way.

I'm sticking with vanilla Vim on windows and hope I'll never be fooled by new-cool-neo apologets again. Not being able to *start* an editor via file explorer and/or command line command is very disappointing.

**Comment by justinmk** [comment]
@artur233945 please mention exact versions in your rants.

> nvim.exe does something very wrong right at the start, so win10 shows a popup dialog for program selection, 

On win7 when I double-click `nvim.exe` (current HEAD fa285bde45d0a123), it runs Nvim in a cmd.exe window. 

> nvim-qt.exe inherits that behavior

That's unusual. Maybe win10 is flagging it because it was downloaded from the web?

> it has to be called as `nvim-qt -- -- "%1"` for reasons that are out of reach

That was a choice made by Neovim-Qt, I don't like it either. I don't think it's necessary.

**Comment by artur233945** [comment]
@justinmk: it was https://github.com/neovim/neovim/releases/tag/v0.3.1

> On win7 when I double-click nvim.exe (current HEAD fa285bd), it runs Nvim in a cmd.exe window.

Running nvim.exe and nvim-qt.exe by double-clicking them in explorer does work, but it is not the case of this thread. It is about explorer context menus and file associations, i.e. double- or right-clicking on *edited files*, not on exe-s.

**Comment by MrGibbage** [comment]
FWIW, I was able to add "Open with Neovim" option to my W10 explorer shell integration, and not have to use the strange "-- --" options.

I just included the whole path to nvim-qt.exe

Computer\HKEY_CLASSES_ROOT\*\shell\Open with Neovim\command
C:\Users\Skip\LocalApps\Neovim\bin\nvim-qt.exe "%1"

I do not have quotes in the command other than those around the %1. That may be because I don't have any spaces in my command, but I noticed that the command for Sublime text also did not have any quotes around the path and it did include spaces.
C:\Program Files\Sublime Text 3\sublime_text.exe "%1"

So far it is working fine. I hope it helps!

**Comment by yzlnew** [comment]
Feel like a `Neovim Here` when clicking the background of the folder is more helpful entering a project home.
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\Neovim Here]

[HKEY_CLASSES_ROOT\Directory\Background\shell\Neovim Here\command]
<full_path_to_nvim-qt.exe> .
```

**Comment by TamaHobbit** [comment]
For Neovim Here, I needed `@="cmd /c start nvim-qt.exe"` as the command, instead of your `<full_path_to_nvim-qt.exe> .`

**Comment by xylix** [comment]
I got it working with yzlnew's instructions. Will be adding a script to my own dotfiles after I fgure out how windows registry edits are scripted.

**Comment by ashfinal** [comment]
I did some work in https://github.com/mhinz/neovim-remote/pull/136 and https://github.com/mhinz/neovim-remote/pull/135, so far it works perfect for me.

![nvim-qt](https://user-images.githubusercontent.com/6827900/71800107-260d8480-3092-11ea-842f-8219c3a63f80.png)

1. It will try to attach to existing neovim GUI. If no neovim instance is found, it will automatically help launch one.
2. It's flexible enough to run multiple neovim instances.
3. It should work with other GUIs besides nvim-qt(not tested yet).

My PRs are not merged yet, due to @mhinz's inactivity these days. If you are curious, you can merge them, then run `python setup.py install`. 

My Windows registry entry is more like:

```
Windows Registry Editor Version 5.00
[HKEY_CLASSES_ROOT\*\shell\Open with Neovim]

[HKEY_CLASSES_ROOT\*\shell\Open with Neovim\command]
"%ProgramFiles%\Python38-32\Scripts\gnvr.exe" "%1"

[HKEY_CLASSES_ROOT\Directory\shell\Open with Neovim]

[HKEY_CLASSES_ROOT\Directory\shell\Open with Neovim]
"%ProgramFiles%\Python38-32\Scripts\gnvr.exe" "%1"
```

**Comment by xylix** [comment]
Great that some desired changes have already been done :). I'll check them out as well.

**Comment by w-tr** [comment]
I've successfully managed to get my window environment to open with nvim. However I was wondering if anyone know how to do the following

Highlight multiple files right click and get "Edit with single nvim".
Gvim 8 has this feature.

**Comment by xeyownt** [comment]
@ashfinal Thanks for your work on this. Is there a branch I could checkout on your repository with all the changes included? It seems there are multiple pull request pending, not sure which one I should take.

**Comment by w-tr** [comment]
> [HKEY_CLASSES_ROOT\Directory\shell\nvim-qt\command]
> @="\"C:\\Program Files\\Python38-32\\Scripts\\gnvr.exe\" \"%1\""

What is gnvr.exe?

**Comment by xeyownt** [comment]
That's the (gui) executable from https://github.com/mhinz/neovim-remote.

**Comment by medwatt** [comment]
Here's mine:



```
Windows Registry Editor Version 5.00


[HKEY_CLASSES_ROOT\*\shell\Edit with Neovim]
"Icon"="D:\\PortableApps\\Neovim\\bin\\nvim-qt.exe"

[HKEY_CLASSES_ROOT\*\shell\Edit with Neovim\command]
@="\"D:\\PortableApps\\Neovim\\bin\\nvim-qt.exe\" \"%1\"" 
```

**Comment by ashfinal** [comment]
> Is there a branch I could checkout on your repository with all the changes included?

@xeyownt Please refer to https://github.com/mhinz/neovim-remote/pull/155 .

**Comment by andis-sprinkis** [comment]
I put together a one-click solution for it https://github.com/andis-sprinkis/neovim-qt-win-shell

**Comment by comiluv** [comment]
Don't forget you need to modify registry address in HKEY_CLASSES_ROOT\Directory\Background\shell for the context menu to appear when you right click in Explorer.

For example you need
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\nvim-qt]
@="&Neovim here"
"Icon"="\"C:\\Neovim\\bin\\nvim-qt.exe\""

[HKEY_CLASSES_ROOT\Directory\Background\shell\nvim-qt\command]
@="cmd /c start c:\\neovim\\bin\\nvim-qt.exe"
```
Above will make Neovim here to appear in context menu when you right click empty space while browsing a folder in Explorer

**Comment by redfox-mx** [comment]
Join comments below. I create my .reg file. This add neovim for file, folder and background context menu

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\nvim-qt]
@="Open Neovim"
"Icon"="\"C:\\tools\\neovim\\Neovim\\bin\\nvim-qt.exe\""

[HKEY_CLASSES_ROOT\*\shell\nvim-qt\command]
@="\"C:\\tools\\neovim\\Neovim\\bin\\nvim-qt.exe\" \"%1\""

[HKEY_CLASSES_ROOT\Directory\shell\nvim-qt]
@="Open Neovim Here"
"Icon"="\"C:\\tools\\neovim\\Neovim\\bin\\nvim-qt.exe\""

[HKEY_CLASSES_ROOT\Directory\shell\nvim-qt\command]
@="\"C:\\tools\\neovim\\Neovim\\bin\\nvim-qt.exe\" \"%1\""

[HKEY_CLASSES_ROOT\Directory\Background\shell\nvim-qt]
@="&Neovim here"
"Icon"="\"C:\\tools\\neovim\\Neovim\\bin\\nvim-qt.exe\""

[HKEY_CLASSES_ROOT\Directory\Background\shell\nvim-qt\command]
@="\"C:\\tools\\neovim\\Neovim\\bin\\nvim-qt.exe\" \"%v\""
```

**Comment by evadeflow** [comment]
This is awesome—thanks to everybody who posted hints here! In case I'm not the only one who's running `nvim.exe` from Windows Terminal, here's the version I adapted from what @redfox-mx posted above:

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\nvim]
@="Edit with Neovim"
"Icon"="\"C:\\Users\\evadeflow\\Apps\\Neovim\\bin\\nvim-qt.exe\""

[HKEY_CLASSES_ROOT\*\shell\nvim\command]
@="wt -p \"Windows PowerShell\" --title neovim C:\\Users\\evadeflow\\Apps\\Neovim\\bin\\nvim.exe \"%1\""

[HKEY_CLASSES_ROOT\directory\shell\nvim]
@="Neovim Here"
"Icon"="\"C:\\Users\\evadeflow\\Apps\\Neovim\\bin\\nvim-qt.exe\""

[HKEY_CLASSES_ROOT\directory\shell\nvim\command]
@="wt -p \"Windows PowerShell\" --title neovim C:\\Users\\evadeflow\\Apps\\Neovim\\bin\\nvim.exe \"%v\""

[HKEY_CLASSES_ROOT\directory\background\shell\nvim]
@="&Neovim Here"
"Icon"="\"C:\\Users\\evadeflow\\Apps\\Neovim\\bin\\nvim-qt.exe\""

[HKEY_CLASSES_ROOT\directory\background\shell\nvim\command]
@="wt -p \"Windows PowerShell\" --title neovim C:\\Users\\evadeflow\\Apps\\Neovim\\bin\\nvim.exe \"%v\""
```

It's so *pretty* I can hardly believe it:

![image](https://user-images.githubusercontent.com/195848/149637716-3cdc6b0f-3765-464e-80dd-2ca2e8f7d676.png)
