### ISSUE TITLE
Undo should restore visual selection (feature request)

### ISSUE THREAD

**Issue by sullyj3** [neovim/neovim#7250]
Hi!

Suppose I have a very small buffer;

`word`

... and my cursor is on the w. If I type `viwd`, followed by `u`, the current behaviour is such that the cursor will be back on the w of the restored `word`.

However, it seems like it would be cool if, after pressing `u`, `word` was now visually selected again.

Is this behaviour a possibility at all? Are there disadvantages I'm missing?

**Comment by justinmk** [comment]
After `u`,  type `gv` to restore the selection.

**Comment by sullyj3** [comment]
Sure, you can do that, but that's not as convenient and user friendly. It's two extra keystrokes every time. I'm arguing that it should happen automatically. Reasons:

- There's precedent. Why is that relevant? If a lot of other editors have considered the issue and decided to do it this way, taking an outside view, that's a strong indication that it's a good design choice. Sublime, Atom, VS Code, Kakoune, Gedit all work this way. I'm sure many more of the editors I haven't checked operate this way. Most word processors work this way
- Taking a more direct argument: If you've visually selected some text, done something to that text, then undone that thing, it's almost always the case that you do in fact want to operate on the text, but you made the wrong operation. For instance, you selected a paragraph, deleted it, then realized you actually wanted to yank it. It's rare that you apply an operation to a selection, then realize you actually don't want to bother doing anything to that region. In other words, the common case for undo is *refining mistakes*, rather than *reversing decisions*.

**Comment by justinmk** [comment]
> If you've visually selected some text, done something to that text, then undone that thing, it's almost always the case that you do in fact want to operate on the text, but you made the wrong operation.

In that one very narrow case where no edits were performed since then, yes, maybe. In all other cases, of course, it wouldn't make sense. If someone does `uuu` they'll be very annoyed when some selection in the chain _lowercases_ the selected text instead of undoing an operation. 

AFAICT your feature request can be solved by a trivial plugin that temporarily maps `u`, and later changes its behavior on `TextChanged`. 

Or if you really want behavior like other text editors, you could map `<c-z>` to always behave like this:

    nnoremap <c-z> ugv

More generally, what you're asking for is DWIM ("do what I mean") behavior, whereas Vim generally behaves as "do exactly what I say". The problem with DWIM is that it is context-sensitive, which tends to break macros and dot-repeat.

**Comment by sullyj3** [comment]
All good points. Retracted.
