### ISSUE TITLE
startinsert is deferred if invoked from an autocmd triggered by RPC

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#7254]
- `nvim --version`: NVIM v0.2.1-857-g06f8ad5b2
- Operating system/version: Linux 4.12.5-gentoo x86_64
- Terminal name/version: rxvt-unicode (urxvt) v9.21
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`
Use the following as init.vim:
```vim
au TermOpen * au WinEnter <buffer> startinsert

function Do_move()
	silent execute('!echo -ne "import neovim\\nn=neovim.attach(\"socket\", path=\"' . $NVIM_LISTEN_ADDRESS . '\")\nn.command(\"wincmd l\")\nn.stop_loop()" | python3 &')
endfunction
```
Then move into the terminal window through rpc. 
```
nvim -u init.vim -O hello term://sh
:call Do_move()
```

### Actual behaviour
Neovim doesn't enter insert mode until input (for example `h`). However if moving into the window from Neovim instead of using the RPC interface, insert mode will be entered right away. Also, if the autocommand is replaced with something else, e.g. `echo 'hello'`, "hello" is displayed immediately.

### Expected behaviour
Insert mode should be entered immediately.

**Comment by glacambre** [comment]
This bug is caused by this line:
https://github.com/neovim/neovim/blob/a7a56293aad9427720fc72b86220dd65a79f6778/src/nvim/normal.c#L931
Removing it doesn't seem to make any test fail and makes the bug disappear. I have a hard time figuring out what this line is supposed to do. @tarruda , git blame says you wrote it, do you remember why it is needed?

**Comment by justinmk** [comment]
@glacambre thanks for debugging this. Going back further in the blame will show that code was from Vim originally, but was later refactored.

I think the more relevant line is https://github.com/neovim/neovim/blob/a7a56293aad9427720fc72b86220dd65a79f6778/src/nvim/normal.c#L8004
 which was carried over from Vim's `nv_cursorhold` (which was adapted into `nv_event` in Nvim). I assume this is needed because of potential un-processed keys in the typeahead buffer. But we could try removing it.
