### ISSUE TITLE
Issue with syntax highlighting for bib files

### ISSUE THREAD

**Issue by sga001** [neovim/neovim#7324]
When using the dollar sign ($) to signify the actual currency instead of a math expression inside a bib entry in a bibtex file (e.g., in the title field) the rest of the document loses all highlighting. For example, everything in my bib file after the "title" line in the following bib entry loses its highlighting.

```
@misc{helloworld,
  author = {nobody},
  title = {I wish I had \$1000},  % also breaks if you do "I wish I had \$1000" or {{I wish I had \$1000}}
  year = {2017},
}
```
I believe the issue is the following matching rule which interprets *any* instance of $ (escaped or not) as math mode.

https://github.com/neovim/neovim/blob/126b2ca077718a02c086039c8f98ef267cf9eb3e/runtime/syntax/bib.vim#L84

The solution is to add a negative lookbehind (something like the following), which ensures that the "$" is not preceded by a "\\" when matching for math mode.

```vim
syn region bibMath contained start=/\(\\\)\@<!\$/ end=/\$/ skip=/\(\\\$\)/
```

**Comment by jamessan** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim.

Syntax plugins (e.g. for ruby/java/YAML) are maintained by the maintainer listed at the top of the file (@berndf in this case).  Please work with him to get this fixed.  Thanks!
