### ISSUE TITLE
Copy-paste (GUI copy paste; not y/p) long lines inserting newlines

### ISSUE THREAD

**Issue by Riamse** [neovim/neovim#7369]
- `nvim --version`: NVIM v0.2.0, Build type: Release
- Vim (version: ) behaves differently? Yes. Expected behaviour actually happens
- Operating system/version: Arch Linux
- Terminal name/version: GNOME Terminal 3.24.2 Using VTE version 0.48.3 +GNUTLS
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC <(perl -e 'print "hello" x 300')
(highlight all the text using the cursor and hit ctrl+shift+c)
(go to some gtk textbox and ctrl+v)
```

### Actual behaviour

The line wrapping shown in the terminal is reflected in when I paste the line too; newlines are inserted every 80 characters, basically, for a standard 80x24 terminal.

The problem I have is basically this: https://unix.stackexchange.com/questions/126577/copy-a-long-single-line-text-from-a-terminal-with-undesired-change-line

### Expected behaviour

No newlines are inserted.

**Comment by justinmk** [comment]
is this the same as https://github.com/neovim/neovim/issues/4421  ?

**Comment by Riamse** [comment]
I don't think so, but I honestly don't know why #4421 is happening either. Also, I forgot to mention, my vim version is 8.0.1176.

**Comment by justinmk** [comment]
Did you try the workaround in #4421? Add this to init.vim:

    highlight Normal ctermbg=NONE

**Comment by justinmk** [comment]
@Riamse could you check whether this happens with 0.2.1 (released today)?

**Comment by dai-github** [comment]
I tried 0.2.1 on Konsole and xterm but didn't see the problem fixed. The workaround doesn't help, either.

**Comment by rickyz** [comment]
This bug seems to have regressed with the migration to the msgpack-based UI protocol. The issue seems to be that the `flags` argument to `ui_call_raw_line()` (which is used to communicate the need to wrap a line) is silently discarded  in `remote_ui_raw_line()`, and the UI client hardcodes a 0 value at:
https://github.com/neovim/neovim/blob/2bdef6dd2a7572602aeb2efec76812769bcee246/src/nvim/ui_client.c#L214-L215.

The following patch restores TUI line wrapping behavior for me. It attempts to follow the contract described at https://neovim.io/doc/user/api.html#api-contract by appending a new parameter to "grid_line" events, but I am not sure if there are additional compatibility considerations that are needed to change what appears to be a public-facing RPC protocol:

[0001-ui-Propagate-line-flags-on-grid_line-events.patch](https://github.com/neovim/neovim/files/11624247/0001-ui-Propagate-line-flags-on-grid_line-events.patch)

**Comment by rickyz** [comment]
> @rickyz thanks! can you send a PR?
Sure, I sent a draft of a PR at https://github.com/neovim/neovim/pull/23891 - it still has some questions about what the appropriate RPC protocol change should be, but hopefully we can work that out - thanks!
