### ISSUE TITLE
lua require('nonexistent') gives unnecessarily verbose error with unprintable chars

### ISSUE THREAD

**Issue by bfredl** [neovim/neovim#7388]
- `nvim --version`: NVIM v0.2.1-581-g253f6f3bb
- Vim (version: ) behaves differently? Irrelevant, does not support `require()`
- Operating system/version: Arch Linux
- Terminal name/version: pangoterm
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:lua require('nonexistent')
```

### Actual behaviour

E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:1: module 'nonexistent' not found:^@^Ino field package.preload['nonexistent']^@^Ino file '/home/bjorn/.config/nvim/lua/nonexistent.lua'^@^Ino file '/home/bjorn/.config/nvim/lua/nonexistent/init.lua'^@^Ino file '/etc/xdg/nvim/lua/nonexistent.lua'^@^Ino file '/etc/xdg/nvim/lua/nonexistent/init.lua'^@^Ino file '/home/bjorn/.local/share/nvim/site/lua/nonexistent.lua'^@^Ino file '/home/bjorn/.local/share/nvim/site/lua/nonexistent/init.lua'^@^Ino file '/home/bjorn/.local/share/flatpak/exports/share/nvim/site/lua/nonexistent.lua'^@^Ino file '/home/bjorn/.local/share/flatpak/exports/share/nvim/site/lua/nonexistent/init.lua'^@^Ino file '/var/lib/flatpak/exports/share/nvim/site/lua/nonexistent.lua'^@^Ino file '/var/lib/flatpak/exports/share/nvim/site/lua/nonexistent/init.lua'^@^Ino file '/usr/local/share/nvim/site/lua/nonexistent.lua'^@^Ino file '/usr/local/share/nvim/site/lua/nonexistent/init.lua'^@^Ino file '/usr/share/nvim/site/lua/nonexistent.lua'^@^Ino file '/usr/share/nvi

### Expected behaviour

Short and readable error message. Or at least one that does not contain non-printable characters.

**Comment by AlexandreDubray** [comment]
Hi, I am interested to work on this. If I understood correctly, the problem is that the whole error message is given to `emsgf` and it contains `\n` and `\t` (which are non-printable). I think that the most reasonable and easiest way to handle that is to truncate the message to leave only the first line. It assumes that the first line contains enough information about the error. In this particular case it gives

`E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:1: module 'nonexistent' not found:`

but I don't know if it would have some bad implications on other error message. What do you think?

**Comment by ZyX-I** [comment]
Stack trace is essential in a number of cases, the way I chose to represent the error is exactly what it is because unlike Vim you can not only view the whole message (though it is not readable), but also catch the whole message (in Vim you catch only the first line). What I would suggest is creating some alternative to emsgf that behaves exactly the same, except that it echoes message like `:echo`.

**Comment by AlexandreDubray** [comment]
Okay I'll try to do that, thanks!

**Comment by AlexandreDubray** [comment]
@ZyX-I While playing with the code, I found that changing [this line](https://github.com/neovim/neovim/blob/0851057a8deaa1197bd0af22babb62c1146d836c/src/nvim/message.c#L1241) to something like

`if (s[1] != NUL && *str != '\n' && *str != '\t') {`

seems to do the job (or maybe there is some implication that I do not see). Creating a new function might be overkill no? I don't know exactly how the `...` in the parameters of function works, but I was thinking that passing an array of non-printable character that need to be consider as printable and just check for this is the `if` statement

**Comment by ZyX-I** [comment]
@AlexandreDubray No, it won’t. Check `ex_echo`, there is *no* function currently which behaves like `:echo` as it has its behaviour written there. What you are suggesting will alter behaviour of other printing commands. And as I saw that you could not possibly go away with creating just one new function: I would go with

1. Replacing `emsg` with `_emsg`: same as `emsg`, but function from final return statement (that is `msg_attr`) is to be replaced with function from additional argument. `emsg` itself in this case would be a wrapper with single-line `return _emsg((const char *)s, msg_attr);` (note: new functions should not use `char_u`).
2. Extracting code from `ex_echo` (note: `has_mbyte` is a constant kept solely to avoid too much refactoring, `mb_*` macros are also deprecated) to `msg_echo_attr` in `message.c` (new function). I tend to rewrite such cycles from something which operates on single characters to something which operates on whole strings: basically, don’t process character-by-character (grapheme cluster-by-grapheme cluster here), use strpbrk to find next NUL, NL, TAB or CR, echo string up to next special character, echo special character (or break in case of NUL), repeat. This tends to produce faster code, especially if you deal with I/O, especially if it happens to be unbuffered.
3. Creating actual new function which is a replacement for `emsgf`, but which uses `_emsg` with function created on step 2 as an second argument rather then `msg_attr`.
