### ISSUE TITLE
Zero byte in strings

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#74]
In vim there is a problem with nul bytes: you cannot have them inside a string and they are replaced with `\n`, `\x01` or just truncate string. Wondering what are the plans on handling this in NeoVim. Lua allows zero bytes in strings and most of the plugin code does not care about NULs, so new VimL can rather safely allow zero bytes. Sucha change is certain to break some of my code though, but I can handle this.

**Comment by justinmk** [comment]
@ZyX-I @tarruda If binary data is sent over msgpack API, plugins can work with it without any intermediate `NUL` => `NL` hack, as long as vimscript and Nvim itself is not involved. Right?

**Comment by tarruda** [comment]
> @ZyX-I @tarruda If binary data is sent over msgpack API, plugins can work with it without any intermediate NUL => NL hack, as long as vimscript and Nvim itself is not involved. Right?

Yes, msgpack can deal with binary data just fine

> This is another reason why non-autocmd API events would be valuable--plugins could bypass VimL "typeval" conversion.

I don't see how skipping the autocmd API would help. What could be done to skip the `NL` => `NUL` conversion by plugins is add a flag to `vim_to_object` that takes care of converting the "line list format" to binary strings before sending via msgpack-rpc. To make things a bit cleaner, this flag could also be added to `rpcnotify`/`rpcrequest` and used when a plugin explicitly needs to send binary data(since most times we will be dealing with plain text)

**Comment by MarcWeber** [comment]
I implemented xdebug long time ago:
https://github.com/MarcWeber/vim-addon-xdebug
It's based on vim-addon-async which encodes 'a\0b' as  ['a','b'].
But I don't like it.
Now if I want to upgrade my code I can't use jobstart beacuse stdout won't
return 0 bytes or don't know what will happen but xdebug uses it as
separator.
So could rewrite parts or all using lua or vim.loop.spawn or libuv or
such.
But honestly I'd love to see hacks to be gone also because Vims regex
enginen is much nicer than lua's. So calling a vim function from lua
actually sometimes makes sense :-) And PHP shows that if strings are
binary you at least can handle all types of data and be done.

**Comment by justinmk** [comment]
@MarcWeber  Lua strings support NUL bytes, as does the Nvim RPC API.
