### ISSUE TITLE
v0.2.0 for Debian Stretch

### ISSUE THREAD

**Issue by cemsbr** [neovim/neovim#7460]
I'm trying to install v0.2.0 in Debian Stretch (currently 0.1.7) an couldn't find it in backport and there's no AppImage in the release page, only for 0.2.1-dev. Is there a way or could there be a way to install 0.2.0 in Debian Stretch?

**Comment by KillTheMule** [comment]
I'd compile the latest master if I were you (actually, that's what I'm doing when at my own machine).

You could also check out https://github.com/hotgloupi/nvim.

**Comment by jamessan** [comment]
Since the 0.2.1 release will be happening "soon", I've been holding off on backporting the current neovim so I can spend that time on other things I need to do.

Once I get 0.2.1 into Buster, I'll backport it to Stretch, since there have been a few requests for that now.

A better place to ask these types of questions is on the backports mailing list, though, since you're asking for something to happen within Debian.
