### ISSUE TITLE
inccommand executes commands following bar without pressing return

### ISSUE THREAD

**Issue by tecywiz121** [neovim/neovim#7494]
- `nvim --version`: NVIM v0.2.1-dev
- neovim APT version: 0.2.0ubuntu1+git201711051611+3715+26~ubuntu16.04.1
- Operating system/version: Ubuntu 16.04.3 LTS
- Terminal name/version: GNOME Terminal 3.6.2
- `$TERM`: xterm-256color
- `$VTE_VERSION`: 3409

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set inccommand=nosplit<CR>
ihello world<ESC>
:s/hello/goodbye/g|q!
```

### Actual behaviour

Neovim exits.

### Expected behaviour

`hello` should be replaced with `goodbye`, neovim should exit after pressing `<CR>`

**Comment by KillTheMule** [comment]
The reason is that [`cmd_can_preview`](https://github.com/neovim/neovim/blob/master/src/nvim/ex_docmd.c#L9889) only checks the first command for its 'liveness' (after skipping some thing).We'll need to modify that.

The question is, what should happen for say "cmd1 | cmd2 |cmd3", how is the liveness of a compound command determined by the individual commands? I see 2 options

1. compounds commands aren't live
2. compound commands are live if and only iff the last command is

Nr. 2 sounds nice, although I'm not sure we can make that work in finite time (maybe it will 'just work' if we change `cmd_can_preview`?).

Other thoughts?

**Comment by bfredl** [comment]
I would expect only the first command to be live (if it can be), not the rest of the compound.

**Comment by KillTheMule** [comment]
So that would be option 1.

**Comment by bfredl** [comment]
Or possibly the largest live-able prefix. Preview stops at the first command that aren't live.

**Comment by bfredl** [comment]
I interpreted option 1 as "give up on compunds"

**Comment by KillTheMule** [comment]
> I interpreted option 1 as "give up on compunds"

That's what I interpreted what you said as as well. Maybe need to clarify :)

So, when typing cmd1, it's live of course if it's live, we've got that down. What happens when typing `|`? Preview stays? When happens then when you type cmd2 which isn't live? What if it is? What if cmd1 wasn't live, but cmd2 is?

**Comment by KillTheMule** [comment]
A little test shows that right now `:%s/int/KKK | %s/KKK/wargl` does not show anything in the preview right now, although the window stays open.

**Comment by bfredl** [comment]
I just interpreted "compounds commands aren't live" as "compounds commands aren't live _at all_" not "compounds are partially live" (in any sense)
 While what I'm suggesting is, preview proceeds until a non-live command is found so if `cmd1 | cmd2 | cmd3 | cmd4` and cmd1,2,4 can be previewed but not 3. Then cmd1 and cmd2 are actually previewed, but not cmd4.

**Comment by KillTheMule** [comment]
Ok so that's option 3. "compound commands are live if and only if all individual commands are".

Might be hard to implement? Pretty niche? I'd still got for option 1 to save people from what's reported here, and not put in a lot of work unless someone can convincingly argue this really happens.

**Comment by bfredl** [comment]
And when you you say option 1 you mean "largest previewable prefix"?  "compound commands are live if and only if all individual commands are" Is yet another option neither mentioned by me or you far...

**Comment by KillTheMule** [comment]
> And when you you say option 1 you mean "largest previewable prefix"?

No, option 1 is "it's live if it's just 1 command that is live", i.e. no `|`.

> "compound commands are live if and only if all individual commands are" Is yet another option neither mentioned by me or you far...

That's from you:

>  While what I'm suggesting is, preview proceeds until a non-live command is found so if cmd1 | cmd2 | cmd3 | cmd4 and cmd1,2,4 can be previewed but not 3. Then cmd1 and cmd2 are actually previewed, but not cmd4.

**Comment by bfredl** [comment]
"Then cmd1 and cmd2 are actually previewed, but not cmd4." is clearly different from "compound commands are live if and only if all individual commands are" which would imply "no commands are previewed in this situation"

**Comment by KillTheMule** [comment]
> which would imply "no commands are previewed in this situation"

No it would imply "commands are previewed as long as cmd1 and cmd2 are typed, and not after that".

Let's take this to gitter and leave this issue for other people who want to chime in. I think we're scaring them away :D

**Comment by bfredl** [comment]
I certainly never talked about the order of typing, only whether a _specific state_ of the of the command line should be previewed or not, which is what  `cmd_can_preview` is deciding. cmd1 and cmd2 can be edited after cmd3 is typed, my proposal would handle this case differently than either of yours. Also a compound can be instantiated at once by a paste or edit in cmdline window, which also will be different.

**Comment by KillTheMule** [comment]
> "Then cmd1 and cmd2 are actually previewed, but not cmd4."

That implies an ordering, as long as you're not suggesting to preview the result of "cmd1 | cmd2" while typing the rest of the command line. Also, without an ordering, what do you mean by "but not cmd4", you surely would never want to preview the result of "cmd4" alone, just the result of "cmd1|cmd2|cmd3|cmd4" (which ofc you can't because of "cmd3", I guess).

**Comment by bfredl** [comment]
This was discussed on gitter, but for posterity: of course `cmd_can_preview` should the consider ordering of the actual command line, which is its input, I just mean the order stuff are typed should remain irrelevant to its decision, as we cannot rely on the way/order the command-line got to its current state.

**Comment by justinmk** [comment]
I think only the first command needs to be previewable. Can't imagine anyone would actually use something more complicated. Using `|` is like pressing `<Enter>`.

Note that `:global` (and anything else like it) is a special case, because a series of commands following it, is semantically an argument to `:global`. 

    :g/^/p|#|d

`p|#|d` is executed per-line by `:global`, it is _part of_ the `:global` command.

**Comment by nimitbhardwaj** [comment]
I have an other option too, it may be easy to implement and is using option 2, there will be a dummy command, which do nothing, like its example, `:%s/hello/goodbye/g | dummy | q!` this will not be quit because dummy was non-previewable and will only quit on <CR>

**Comment by bfredl** [comment]
@nimitbhardwaj But how does that solve the original problem, which is what happens when the command line contains `:XX|YY` where XX is previewable but YY is non-undoable/destructive ( or more in general, situations like `:'<,'>normal! diwZQ`). The user will not type `:XX|dummy|YY`, no?

**Comment by nimitbhardwaj** [comment]
yes, was thinking user will type, `:XX|dummy|YY`, although it doesn't sounds good, other idea left for now is option 1 as were discussing before,  or making previewable only those which are is also good, though difficult

**Comment by nimitbhardwaj** [comment]
I am taking this under my custody, I will fix it.
I am planned to use option 1 as discussed above.
One important thing I want to clarify, suppose there is cmd, `:s/hello/goodbye/g|q!` then in preview mode, hello will be replaced as preview does, but will not be quit, but when the cmd is entered, i.e. <CR> is feeded, the text will be replaced and nvim will exit.

**Comment by justinmk** [comment]
> I want to clarify, suppose there is cmd, `:s/hello/goodbye/g|q!` then in preview mode, hello will be replaced as preview does, but will not be quit, but when the cmd is entered, i.e. `<CR> `is feeded, the text will be replaced and nvim will exit.

Makes sense to me. Is there another behavior that would make sense?

**Comment by blueyed** [comment]
This causes https://github.com/neovim/neovim/issues/8796.
I guess it should not apply to commands being executed while in CMDPREVIEW state, i.e. I've seen this happening with the `FocusGained` event initially.
