### ISSUE TITLE
Lua: support VimL callbacks for jobstart() on_stdout, etc.

### ISSUE THREAD

**Issue by ciarand** [neovim/neovim#7607]
- `nvim --version`: v0.2.1
- Vim (version: ) behaves differently? N/A
- Operating system/version: N/A
- Terminal name/version: N/A
- `$TERM`: N/A

## Feature request

I'd like to be able to specify a Lua function directly as a VimL callback.

### Actual behaviour

Currently using Lua callbacks with the job-control APIs requires writing a VimL wrapper function:

```vim
function! s:stupidVimLWrapper(job_id, data, event) dict
  call luaeval('my_lua_callback', {'job_id': a:job_id, 'data': a:data, 'event': a:event})
endfunction

let s:callbacks = {
\ 'on_stdout': function('s:stupidVimLWrapper'),
\ 'on_stderr': function('s:stupidVimLWrapper'),
\ 'on_exit': function('s:stupidVimLWrapper')
\ }

jobstart("echo foobar", s:callbacks)
```

### Desired behaviour

Ideally this would be unnecessary and Lua functions could be specified directly:

```vim
let s:callbacks = {
\ 'on_stdout': lua_function('my_lua_callback'),
\ 'on_stderr': lua_function('my_lua_callback'),
\ 'on_exit': lua_function('my_lua_callback'),
\ }

jobstart("echo foobar", s:callbacks)
```

**Comment by bfredl** [comment]
Not only that, we also plan to make `jobstart` directly available in lua, so that you can pass in any lua closure, and not just a name. #6844 does some work of disentangling jobs/channels from vimL, what is needed after that is to add a lua variant to the `Callback` enum struct.

**Comment by ciarand** [comment]
Hi folks! Now that both #6743 and #6844 have landed, what's the status of this?

**Comment by bfredl** [comment]
it is planned. Hard to give an ETA though.

**Comment by wbthomason** [comment]
Is this still the state of interactions between `jobstart` and Lua? If so, what would be necessary to make `jobstart` available in Lua? I'd be happy to help work on it once I have time (which might be a few weeks from now), but I'm not really sure where to start.

**Comment by justinmk** [comment]
@wbthomason I would start by looking at the impl of `nvim_buf_attach()` `opts.on_lines` parameter. Also

    git grep -E '\bLuaRef\b'

**Comment by wbthomason** [comment]
For what it's worth, I've found that `vim.loop` already provides pretty much what I wanted from `jobstart` - perhaps `vim.jobstart()` would make sense as a convenience wrapper around `vim.loop.spawn`/some machinery to hook up and tear down `stdout` and `stderr`?

**Comment by justinmk** [comment]
Yes!

**Comment by wbthomason** [comment]
I'm still too busy at work to push this issue forward, but I ran across https://github.com/TravonteD/luajob, which seems like it could be a reasonable starting point to merge in and provide a `jobstart`-like `vim.loop.spawn` convenience wrapper (assuming, of course, that @TravonteD is OK with the idea). 

From a quick glance at the code, it looks like it would need a few changes (in particular, merging environment variables, supporting the full set of options valid in `jobstart`'s `{opts}` parameter (if this is desirable), probably moving away from OOP to match the guidelines in `:h dev`, etc.), but it has the basic API/concept.

Otherwise, I'll still come back to this as soon as I've time.

**Comment by TravonteD** [comment]
Thanks for mentioning me @wbthomason I'm definitely okay with using luajob as a base, since the reason I wrote it was to get this sort of interface. I could start by extending the opts to support the rest of jobstarts options. I'll read through :h dev to get a better idea of what the api should look like.

**Comment by wbthomason** [comment]
It's still true that I don't have time to shepherd this issue to completion right now, but I did just throw together a (completely untested, but theoretically complete) possible implementation for the Lua side of things: https://github.com/wbthomason/neovim/blob/lua-jobstart/src/nvim/lua/vim.lua#L389. It does address some of the changes I noted from @TravonteD's implementation. However, it still does not handle the `pty` and `rpc` options (or their associated options, e.g. `width`) from `jobstart()`.

@TravonteD, if you have time and willingness to work on this, perhaps you can use something between our two versions as a starting point?

**Comment by dlukes** [comment]
FWIW, neovim/nvim-lsp currently also uses a hand-rolled wrapper over `vim.loop.spawn` for running jobs:

https://github.com/neovim/nvim-lsp/blob/26e633f6113bd0783e2491596e5ef1507580bec1/lua/nvim_lsp/util.lua#L411-L472

The drawback is that the output is sent to a regular buffer, so e.g. carriage returns end up displayed as `^M` characters instead of moving the cursor etc., see neovim/nvim-lsp#207.
