### ISSUE TITLE
Version 0.2.2 is not described on roadmap page but it has released already

### ISSUE THREAD

**Issue by hexum** [neovim/neovim#7609]
[Roadmap page](https://neovim.io/roadmap/) doesn't contains info about yet released version 0.2.2.

**Comment by justinmk** [comment]
0.2.2 was a bufix release, we don't plan to describe every minor release on the roadmap page. There were seven (7) release between 0.1 and 0.2.

To be honest, 0.2.1 should have been released as 0.3. Live and learn.

**Comment by hexum** [comment]
Ye, 0.2.1 should be released as 42 =)
Semantic versioning is only applicable for shared libs.

**Comment by justinmk** [comment]
> Semantic versioning is only applicable for shared libs.

Libs should never break, that's why we version the public API as an incrementing number ([API level](https://neovim.io/doc/user/api.html#api-metadata)).

Semantic versioning is a human signal. A single number carries less information, so we do try to convey the weight of a release in the semantic version. But we failed to do that with 0.2.1.

**Comment by hexum** [comment]
OK, just kidding =)
I'm glad that someone still thinks about versioning (I've just update to systemd-235).
