### ISSUE TITLE
exists('#TermOpen') returns 0

### ISSUE THREAD

**Issue by lambdalisue** [neovim/neovim#7647]
- `nvim --version`: 0.2.2
- Vim (version: ) behaves differently? Vim does not have `TermOpen` autocmd
- Operating system/version: macOS High Sierra
- Terminal name/version: zsh/tmux
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:echo exists('#BufRead')
1
:echo exists('#TermOpen')
0
```

### Actual behaviour

The followings returns 0 even they exists

- `TermOpen`
- `TermClose`
- `TermChanged`
- `TermResponse`

### Expected behaviour

I'm not sure while `TermXXX` is neovim's special autocmd but I think `exists('#<autocmd>')` should return 1 if they exists.

**Comment by Shougo** [comment]
Reproduced for me.
But it is 1 in my init.vim.

I think the result is changed after some feature is loaded or some configuration.

**Comment by ZyX-I** [comment]
This is expected, and works just the same in Vim: `vim -u NONE -i NONE --cmd 'echo exists("#BufRead")' --cmd cq` will report zero because no autocommands were *defined for that event*. This is not a check whether certain event exists, it is a check whether there are actual autocommands defined for the event. `nvim -i NONE -u NONE -N --cmd 'au TermOpen * foo' --cmd 'echo exists("#TermOpen")' --cmd cq` works fine.

**Comment by Shougo** [comment]
Ah, OK.

It should be `echo exists('##TermOpen')`.

**Comment by lambdalisue** [comment]
ic. Sorry I totally mis understood the command behavior.
