### ISSUE TITLE
cursorline CTERM highlight blocks `set spell` highlight

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7715]
- `nvim --version`: v0.2.3-99-g873af01
- Vim (version: ) behaves differently? no
- Operating system/version: n/a
- Terminal name/version: conemu
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set spell
:set cursorline
:hi cursorline cterm=none ctermbg=yellow ctermfg=red
```

### Actual behaviour
The cterm/ctermbg/ctermfg for spelling errors is overridden by the cursorline highlight configuration, and spelling errors on the current line are not visible until the cursor is moved to another line.

### Expected behaviour
The spell color highlight overrides the cursorline highlight such that it can be configured to show up nicely in the presence of a cursorline highlight.

**Comment by justinmk** [comment]
Yes, this was fixed by #6380 . But it had to be reverted (partially) because of #7383 .

Could be revisited by an alternative approach: https://github.com/neovim/neovim/issues/7383#issuecomment-336702567

Note that #6380 is still in effect for 'colorcolumn', and 'cursorcolumn'. So only 'cursorline' has the issue your reported.

**Comment by andreyorst** [comment]
I'm experiencing something similar. Or may be not similar, but still a cursorline issue, but because I'm not sure, I've decided to post it here, if not, please don't hesitate.

On this screenshot [ALE](https://github.com/w0rp/ale) adds underscore to curly brace, because `;` is missing.
![image](https://user-images.githubusercontent.com/19470159/37905189-b92a9af6-3106-11e8-9226-83878a09172b.png)
If I place cursor on that line, cursorline will get the underscore too.
![image](https://user-images.githubusercontent.com/19470159/37905195-bdcb2206-3106-11e8-9dce-bd0b3833e300.png)
however in Vim nothing is wrong.
![image](https://user-images.githubusercontent.com/19470159/37905196-c2ddac78-3106-11e8-81bd-d5473159c194.png)

The theme that I use is from [base16-vim](https://github.com/chriskempson/base16-vim), and I've found that if SpellBad is set like so:
```vim
call <sid>hi("SpellBad",     "", "", "", "", "undercurl", s:gui08)
```
The issue with cursor line shown above persists. But not in Vim.

**Comment by justinmk** [comment]
#8578 addresses this if you don't set foreground (`ctermfg` / `guifg`) (or if you _unset_ it by assigning `NONE`):

```
nvim -u NORC
:set spell
:set cursorline
:hi cursorline cterm=none ctermbg=yellow ctermfg=NONE
```
