### ISSUE TITLE
Python Syntax Highlighting does not support Non-ASCII identifiers

### ISSUE THREAD

**Issue by sedrubal** [neovim/neovim#7733]
- `nvim --version`: NVIM v0.2.0
- Vim (version: ) behaves differently? With `-u NORC` vim does no syntax highlighting at all. Otherwise there is the same problem with vim
- Operating system/version: Linux / Fedora 27
- Terminal name/version: konsole 17.08.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
echo -e "def möp():\n    pass" > test.py
nvim -u NORC test.py
```

### Actual behaviour

![broken Syntax highlighting](https://user-images.githubusercontent.com/5571650/34080749-4da4c56a-e343-11e7-8710-94a1af9f1775.png)

### Expected behaviour

In Python3 the list of valid characters for names was extended. It is valid to use non-ASCII characters. So the complete function name `möp` should be highlighted as function.  The same applies to classes and other names.

- https://docs.python.org/3/reference/lexical_analysis.html#identifiers
- https://www.python.org/dev/peps/pep-3131/

There are plugins / configurations to fix this, but I think this should be fixed directly in the default nvim configuration.

As / If it is not possible to find out whether a file is python2 or python3, this behavior should be default for both, 2 and 3.

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim (we track Vim runtime updates very closely).

Syntax plugins (e.g. for ruby/java/YAML) are maintained by the maintainer listed at the top of the plugin file. Please report to that person, or to https://github.com/vim/vim. Thanks!

**Comment by sedrubal** [comment]
Thanks. I wrote a mail to the python.vim maintainer.
