### ISSUE TITLE
Difference of meaning for `TextYankPost` in Vim

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#7743]
- `nvim --version`:      NVIM v0.2.0 Build type: Release
 - Vim (version: 8.0 patches 1-1400) behaves differently? Yes.
 - Operating system:     Ubuntu 16.04.3 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.3
 - `$TERM`:              screen-256color
 - Shell:                zsh 5.3.1

According to the documentations of Neovim and Vim, it seems there's a difference in the meaning of the event `TextYankPost`. For Neovim, it's defined like this:

    Just after a |yank| or |deleting| command

But for Vim, it's:

    After text has been yanked or deleted in the current buffer.

When I visually select some text then get back to normal mode by pressing Escape or `y`, Vim [emits `TextYankPost`](https://github.com/vim/vim/issues/2459), because it copies the text in the [selection register](https://imgur.com/a/IiLL3) (`:h "*`).
However, it seems Neovim doesn't emit `TextYankPost`, probably because no yank command has been executed by the user.

I prefer the meaning used in Vim, because it seems to allow the emulation of the `VisualLeave` event and the implementation of a [selection ring](https://github.com/lacygoill/vim-selection-ring).
That is a way to reselect not just the last selection (like with `gv`), but any past selection.

Would you agree to change the meaning of `TextYankPost`, and adopt the one used in Vim?

I suspect you won't, as, maybe, it would break existing plugins relying on the event, and I think you plan to introduce the `ModeEnter` and `ModeLeave` events in the future. I still thought it was worth asking the question to attract your attention on the difference in Vim.

**Comment by bfredl** [comment]
It it is `VisualLeave` you want, why not ask for VisualEnter/Leave on vim-dev (or even sketch the PR yoursel)f?  bram recently implemented CmdlineEnter/Leave, so this does not sound too far fetched.

Silently firing TextYankPost on visual leave with `v:event.operator ==# 'y' && v:event.regname ==# '*'` seems weird, ostensibly there is no way to distinguish whether it happened automatically or the user explicitly `v..."*y`. Or maybe `mode()` only gets set in the automatic case? Preferably `operator` would have a different value like `v` in this case. I will need to check later, otherwise it will cause trouble in nvim-miniyank if someone starts to use it in vim 8...

**Comment by lacygoill** [comment]
@bfredl Thank you for the answer. Yes, it's true that the code is a little weird.  I can't submit a PR to ask for `VisualLeave` because I don't know `C`, but you're right, I should have asked on `vim-dev` first. I will try to ask them later.

**Comment by bfredl** [comment]
Also note, `TextYankPost` will fire whenever visual mode is active and another X11 program wants to paste it. Not necessarily completely wrong to fire an autocmd in this situation, but quite unexpected for many consumers of `TextYankPost` I think. I might post a suggestion of reasonable behaviour (or even PR) to vim/vim tomorrow...
