### ISSUE TITLE
"qx" does not process the query string in the URL

### ISSUE THREAD

**Issue by dtcyganok** [neovim/neovim#7763]
- `nvim --version`: v0.2.2
- Vim (version: ) behaves differently? Not tested
- Operating system/version: Linux 4.14.8-1-ARCH
- Terminal name/version: kitty
- `$TERM`: xterm-kitty

### Steps to reproduce

```
nvim -u NORC
```

Paste this text:
```
https://duckduckgo.com/?q=neovim
```
Move cursor to the first symbol of URL
Press "gx"

### Actual behaviour
Browser opens new tab with "https://duckduckgo.com"

### Expected behaviour
Browser opens new tab with "https://duckduckgo.com/?q=neovim"

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. 

Please report to https://github.com/vim/vim. Thanks!

**Comment by dtcyganok** [comment]
This bug is fixed in https://github.com/vim/vim/issues/2493, but still exists in neovim. Probably missed the related patch.
