### ISSUE TITLE
":syntax on" during startup skips implicit ":filetype plugin indent on"

### ISSUE THREAD

**Issue by lilydjwg** [neovim/neovim#7765]
- `nvim --version`: v0.2.2
- Vim (version: 7.2+) behaves differently?
- Operating system/version: Arch Linux
- Terminal name/version: xfce4-terminal
- `$TERM`: tmux-256color

### Steps to reproduce

```
# put `nmap <buffer> <CR> <C-]>` in `~/.config/nvim/ftplugin/help.vim`
# run nvim
# :help
# place the cursor on a tag, then press Enter
```

### Actual behaviour
Moves to the beginning of next line.

PS: Using `au FileType help ...` works.

### Expected behaviour
jump to the tag.

**Comment by lilydjwg** [comment]
It seems that all scripts in ~/.config/nvim/ftplugin isn't loaded.

**Comment by justinmk** [comment]
Sounds like runtimepath is being mangled by your config.

**Comment by lilydjwg** [comment]
I just checked and ~/.config/nvim is in &rtp.

**Comment by justinmk** [comment]
Works for me. Unlikely to be a Nvim bug. 

Try `: checkhealth` .

**Comment by wsdjeg** [comment]
@lilydjwg It also works well for me.

**Comment by lilydjwg** [comment]
Minimal config:

init.vim:
```
syntax on
```

ftplugin/help.vim:
```
nmap <buffer> <CR> <C-]>
```

**Comment by justinmk** [comment]
You are missing`filetype detect`

**Comment by justinmk** [comment]
filetype on

**Comment by justinmk** [comment]
You are missing `filetype plugin on`.

Explanation:

If the user invokes `:syntax on` or `:filetype ...` then Nvim skips automatic enabling of `:filetype plugin indent on` and `:syntax on` , to avoid overriding the user's preference.

**Comment by justinmk** [comment]
However with `nvim -u <(echo 'syntax off')` we _do_ continue with automatic enabling of `:filetype plugin indent on`.

This is horribly confusing. 

The reason it works this way is because during startup we are detecting whether the user invoked `:filetype ...` but `:syntax on` _itself_ invokes `:filetype on` (without `plugin indent`), so we then assume that's what the user wants.

I think we could handle this case better.
