### ISSUE TITLE
slow startup with unnamedplus register used as default without x-server

### ISSUE THREAD

**Issue by meijieru** [neovim/neovim#7792]
- `nvim --version`: NVIM v0.2.3-dev
- Vim (version: ) behaves differently? yes
- Operating system/version: Ubuntu 16.04
- Terminal name/version: moba
- `$TERM`: xterm-256color

### Actual behaviour

With a linux without X-server
```
set clipboard^=unnamedplus      " use + register for usual operation
```

result in a slow startup, while vim does not.

### Expected behaviour

Start up quickly

**Comment by justinmk** [comment]
What clipboard tool does `: checkhealth` report?

**Comment by justinmk** [comment]
Also, is `xsel` or `xclip` installed on the remote machine?

**Comment by meijieru** [comment]
They are OK. xsel is installed.

**Comment by justinmk** [comment]
Is `$DISPLAY` defined?  And you answered only half of my previous questions.

**Comment by meijieru** [comment]
```
## Clipboard (optional)
  - OK: Clipboard tool found: xsel
```

`$DISPLAY` is `localhost:10.0`

**Comment by justinmk** [comment]
So you have DISPLAY set and a clipboard tool available. And you have told Nvim to use the clipboard for every single register operation (`unnamedplus`). This, of course, will be slow. It's not slow in Vim because Vim just ignores `unnamedplus` in this particular case.

If you don't want Nvim to use the clipboard ... don't tell it to use the clipboard.
