### ISSUE TITLE
Corruption when using neovim through SSH in Konsole

### ISSUE THREAD

**Issue by pgkos** [neovim/neovim#7868]
- `nvim --version`:
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

    system vimrc file: "$VIM/sysinit.vim"
   fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  3 2018 07:15:12)`) behaves differently? Works correctly
- Operating system/version: Arch Linux
- Terminal name/version: Konsole 17.12.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Open a SSH connection.
2. Open neovim through this SSH connection.
3. Repeatedly enter and leave insert mode.

### Actual behaviour

A `q` replaces the character under the cursor. When exiting, instead of `:q`, `:qq` appears.

This bug occurs only when using Konsole, so I am not sure if this is a Neovim or Konsole bug.

### Expected behaviour

`q` does not replace the character under the cursor.

**Comment by justinmk** [comment]
Nvim 0.2.3 now understands `TERM=konsole-256color`, so the correct sequences will be sent even over SSH (because `$TERM` is mirrored by ssh to the remote).

In the meantime, you can define `$KONSOLE_PROFILE` on the remote, and this should fix Nvim.  Otherwise Nvim thinks your terminal is xterm-compliant, but it's not (otherwise it wouldn't should the "q").

See https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes
