### ISSUE TITLE
Using vertical splits with cmder causes glitches

### ISSUE THREAD

**Issue by krystalgamer** [neovim/neovim#7900]
- `nvim --version`: 0.2.3 (same happens with 0.2.2)
- Vim (version: ) behaves differently? 8.0.1305, yes, works correctly
- Operating system/version: Windows 10 x64 Education Creators Update
- Terminal name/version: ConEmu 171025 alpha
- `$TERM`: cmder

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

Open two files, one with more lines than the other

```

### Actual behaviour

That's it, the text from the longer one is duplicated on the smaller one. Also the left-most side is mirrored on the right side.

Picture: https://imgur.com/YP9ex6Y

As you can see the bigger file got cut and the text that was suposed to be on the left side now is on right side.

### Expected behaviour

Their text shouldn't overlap.

**Comment by justinmk** [comment]
> $TERM: cmder

Do you really have a terminfo file for "cmder" ?

What does `:echo &term` say from Nvim?

With Nvim 0.2.3+ you can see terminal debugging info when the 'verbose' level is >=3 (see `:help 'verbose')`.  Try this:

    nvim -V3log
    :q

Then the file named `log` will have a `--- Terminal info ---` section. Please post it.

(Note: invoke `:q` manually, so that the builtin UI has a chance to start up. Don't add `-c "q"` in the command-line args.)

**Comment by krystalgamer** [comment]
> Do you really have a terminfo file for "cmder" ?

No, I was unsure of what to put on that field.

> What does :echo &term say from Nvim?

builtin_ansi


> Then the file named log will have a --- Terminal info --- section. Please post it.

[log.txt](https://github.com/neovim/neovim/files/1657441/log.txt)

I added a txt extension so github would accept it.

**Comment by justinmk** [comment]
Our builtin_ansi happens to have guessed wrong, Vim's builtin-whatever was more conservative.  In either case you need to supply a valid TERM. Try TERM=xterm-256color , but really read the documentation of cmder or whatever terminal you're using.
