### ISSUE TITLE
Subprocess output (eg. ":!ps fax") cut off in the middle (4k-48k)

### ISSUE THREAD

**Issue by phmarek** [neovim/neovim#7915]
- `nvim --version`: 0.2.3 + 8b1f7d8774b235ae4f0dc0fa64d58e3cad9f8283
- Vim (version: ) behaves differently? yes
- Operating system/version: Linux Debian amd64
- Terminal name/version: xterm, tmux
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:!ps fax
```

### Actual behaviour
The output is cut off after the 4096 byte, and resumed at the ~49000 byte.

Happens with every program, not just "ps".

Example for "ps fax":
```
  312 ?        S      0:27  \_ [dmcrypt_write]
  313 ?        I<
.
89:1|190:1|193:1|196:0|197:0|198:1|199:1|200:0|201:1|202:1|203:1|205:0|206:0|208:0|217:1|218:1|219:0|220:0|221:0| -stringPrefs 3:7;default|97:0;|142:3;1.0|154:332;             ??
```

### Expected behaviour
Coherent printing of the subprocess' output.

**Comment by justinmk** [comment]
This is intentional, and documented at `:h nvim-features-changed` and `:!`:

```
                        If the command produces too much output some lines may
                        be skipped so the command can execute quickly.  No
                        data is lost, this only affects the display.  The last
                        few lines are always displayed (never skipped).
```

If you want to barf thousands of lines to the screen reliably, use `:terminal`.  Most people use `:!` to check the last few lines of output, and printing megabytes of data just slows down your terminal for no benefit.

Try this in Vim, and compare the performance to Nvim:

    vim -u NORC -N
    :!grep -r a ~/

Nvim is limited by your disk speed, Vim is limited by your terminal speed and will take 10-100x longer.

Besides this (massive) performance benefit, throttling TUI output is required in Nvim's case in order to capture CTRL-C, otherwise the TUI event queue gets flooded and will take minutes or hours to receive the CTRL-C input event.

**Comment by phmarek** [comment]
Okay, that's a good reason. Understood.

How about improving the implementation? For example, ending with a whole line, the last part shouldn't start in the middle of a line but as a fresh whole line, and the cutting in the middle could be made visible in some way.

Ie., instead of
```
  311 ?        I<     0:00  \_ [kcryptd]
  312 ?        S      0:28  \_ [dmcrypt_write]
  313 ?        I<
1|18:0|28:1000|34:20|35:5|36:10|45:128|46:10000|51:0|53:400|54:1|55:0|56:0|61:
21048 ?        Ss     0:00 /usr/sbin/cupsd -l
21049 ?        Ssl    0:00 /usr/sbin/cups-browsed
```

how about this?

```
  311 ?        I<     0:00  \_ [kcryptd]
  312 ?        S      0:28  \_ [dmcrypt_write]
<nvim: too much data, lines skipped here>
21048 ?        Ss     0:00 /usr/sbin/cupsd -l
21049 ?        Ssl    0:00 /usr/sbin/cups-browsed
```

(As for the "no data is lost" help text, I'd like to ask "how to see the whole output?"
Perhaps this should better read "The command will run normally" - if the output that got cut out was the result of a few days of calculation [because ":terminal" or ":make" got mixed up with ":!", some data _is_ lost ;)

Thanks for the quick answer!
