### ISSUE TITLE
Why are there two gitcommit.vim's?

### ISSUE THREAD

**Issue by AndrewSB** [neovim/neovim#7938]
I was browsing the neovim source code, and I was surprised to see two files that accomplished the same task -- namely styling gitcommit files.

I found both [neovim/runtime/syntax/gitcommit.vim](https://github.com/neovim/neovim/blob/master/runtime/syntax/gitcommit.vim) and [neovim/runtime/ftplugin/gitcommit.vim](https://github.com/neovim/neovim/blob/master/runtime/ftplugin/gitcommit.vim). Can someone help me understand why there are two files that are both supposed to style git commit messages?

Thanks!

**Comment by jamessan** [comment]
"syntax" scripts define the syntax highlighting for a filetype.  "ftplugin" scripts define filetype specific behavior.  You can see more at ":help ftplugin" and ":help syntax".

In the future, for questions like this please use one of the resources listed at https://neovim.io/community/ instead of filing a bug.  Thanks.

**Comment by AndrewSB** [comment]
Gotcha, thanks for answering!

Thanks for the link, I'll make sure to post there in the future
