### ISSUE TITLE
Esc key not registered (dictation)

### ISSUE THREAD

**Issue by dopey** [neovim/neovim#7972]
Quick note since i found similar questions: i am not using tmux or screen.

- `nvim --version`: 0.2.0-1 -> 0.2.2
- Vim (version: ) behaves differently? 8.0.642
- Operating system/version: macosx/10.13.3
- Terminal name/version: iterm2/3.1.5
- `$TERM`: xterm-256color

I use dictation software to control neovim. So when I speak a command a series of keypresses occur in very quick succession. I have a command that saves the current buffer by pressing `Esc + ':w\n'`. In version 0.2.0-1 of neovim this works fine. However, upon updating to version 0.2.2, the escape key is no longer processed when followed by other keys. In vim 8.0.642 the key sequence works as expected. Feels to me like some timing constant has changed recently.

**Comment by justinmk** [comment]
> Feels to me like some timing constant has changed recently.

Yes, https://github.com/neovim/neovim/pull/6969

Seems like we don't have a way to _disable_ meta-as-escape. These don't seem to do that:

```
:set nottimeout
:set ttimeoutlen=-1
:set ttimeoutlen=0
```

**Comment by james64** [comment]
Hey,

I want to find out whether this is my bug. I have nvim 0.2.2 installed and every time when I  leave insert mode with esc (I use ^[ instead) I need to wait for half a second to be able to input other cmds. Otherwise those commands are just considered as input and esc is ignored. It sounds like this is the same issue here but I am not sure. This is because the bug here is considered minor issue even though it is critical from my usability point of view.

I think it is considered as minor because
* It was introduced in November with 0.2.2 release (as by discussion above)
* It is now assigned to 0.2.4 which has no date assigned so probably few months of wait still

I consider it critical because nvim is about speed of editing and this is adding half a second wait between every other mode switch. Since one switch between modes like few times a minute it is very annoying.

Am I missing something here? Is this different issue?

Thanks

Disclaimer: This is a constructive question. I am not angry or something :) I would dig in a code myself but I am not a C programmer. I am looking more for creating some plugins in some jvm language in future. I like neovim already. Keep it up!

**Comment by KillTheMule** [comment]
Does ist happen with `nvim -u NORC`? Sounds like a mapping issue.

**Comment by james64** [comment]
I am not using any rc for nvim so far. I tried with `nvim -u NORC` to be sure and it is the same still.

I am running manjaro and nvim 0.2.2 is installed from manjaro repos. Let me know if this is eligible for a separate ticket.

**Comment by justinmk** [comment]
Are you using tmux? 

https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed

**Comment by justinmk** [comment]
> I want to find out whether this is my bug. I have nvim 0.2.2 installed and every time when I leave insert mode with esc (I use ^[ instead) I need to wait for half a second to be able to input other cmds

Are you saying ctrl-^ does not have the problem? That doesn't make sense.

**Comment by james64** [comment]
No esc and ctrl-[ behave the same. Ie they both didn't work. I only wanted to specify that I use ctrl-[ in case that matters and I chose ambiguous wording...

But now it works since yes I use tmux and that was indeed my issue. Tmux setting helped. Thanks a lot!

**Comment by justinmk** [comment]
@dopey #8226 should mostly address this issue.

Though I still plan to support some way of explicitly disabling ESC-means-META.

**Comment by dopey** [comment]
awesome! I will see if this fixes things in the next release. Thanks!
