### ISSUE TITLE
setting pwsh as shell

### ISSUE THREAD

**Issue by jmwatte** [neovim/neovim#7976]
- `nvim --version`:
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEV
EL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATI
ONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/inclu
de -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Gecompileerd door builduser

- Vim (version: ) behaves differently?
- Operating system/version:antergos arch
- Terminal name/version:
- `$TERM`: here is the problem have zsh but want pwsh

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
at   46 :set shell= /usr/bin/pwsh
E518: unknown  option: /usr/bin/pwsh

### Expected behaviour
settting it to pwsh

**Comment by jamessan** [comment]
You have an extra space after the `=`.  That's not allowed, since multiple options can be set in one `set` command -- `set shell=/usr/bin/pwsh expandtab ...`.

Remove that space and you'll get the expected behavior.

In the future, please use the [community resources](https://neovim.io/community/) to help determine if an issue is a bug.
