### ISSUE TITLE
Lua support issue

### ISSUE THREAD

**Issue by duytrung** [neovim/neovim#8204]
- `nvim --version`:0.2.3.911
- Vim (version: ) behaves differently?
- Operating system/version: Win10
- Terminal name/version: CMD
- `$TERM`:

### Actual behaviour
No lua support: 
![image](https://user-images.githubusercontent.com/2046672/38090776-2d5022a6-33ab-11e8-9a2a-f6afe8b6bb16.png)

I copied the lua binaries dll into neovim's "bin" folder.

### Expected behaviour
Support Lua.

**Comment by justinmk** [comment]
I'm going to make some inferences, because your report is lacking the steps (which were requested by the issue template) showing what you did and what you expect. The exact steps, not "support Lua".

I am guessing:

- you're referring to the fact that `has("lua")` returns 0.
- you didn't try `:lua`, `:luafile`, `:echo luaeval('...')`
- you didn't read `:help lua` or at least didn't try any of the sample code mentioned there.

`has("lua")` returns 0 because the full legacy interface isn't implemented. This has nothing to do with Nvim's built-in lua support.

- `:lua`, `:luafile`, `luaeval()`, all work.
- The API function `nvim_execute_lua()` also works.
- Lua module loading/discovery works very well (it was non-trivial to get this right).
    - 'runtimepath' is automatically updated when the Lua package path is updated.
- The `vim` module is available in Lua scripts, and `vim.api` exposes the full Nvim API (`:help api`) to Lua scripts.

The following things are missing from the "legacy" Vim `if_lua` interface:

- sugar for buffers/windows
- referencing VimL objects from within Lua

In the meantime Lua is always included with Nvim, and you can write plugins using all of the features mentioned at `:help lua`.

> I copied the lua binaries dll into neovim's "bin" folder.

That's not required and won't accomplish anything.

**Comment by duytrung** [comment]
it displayed a message that neocomplete required .... with lua support. (+lua), but in the screen above showed that "-lua".

**Comment by Shougo** [comment]
> it displayed a message that neocomplete required .... with lua support. (+lua), but in the screen above showed that "-lua".

You should use deoplete instead.

**Comment by ZyX-I** [comment]
@justinmk Lua package path should be updated after `&runtimepath`, not the other way around. If it is not the case then something is wrong.
