### ISSUE TITLE
Access remote directory through SCP

### ISSUE THREAD

**Issue by Stephane-T** [neovim/neovim#8233]
NVIM v0.2.3-955-g60e96a45b

NVIM 0.1.7 behaves differently.

Linux Debian 9.4 

Terminal Xterm
### Steps to reproduce using `nvim -u NORC`

:e scp://.......whatever a SSH remote account folder

First time, it works fine.

:e scp:// .... the same SSH remote account folder 

Get error during the second call:  --No lines in buffer--

In NVIM 0.1.7, it just refresh as it's expected.

**Comment by mhinz** [comment]
It works the same in a recent Vim. Using `:e scp://...` a second time empties the buffer, and using it a third time, will work as expected again.

It's most probably a regression in the standard plugin netrw, but it could also be due to a change in Vim itself. Anyway, since we merge patches from Vim, it would be better patched there first.

Could you create an issue for it? https://github.com/vim/vim/issues

**Comment by mhinz** [comment]
It broke when netrw was updated to `v156`.

Commit in Neovim: https://github.com/neovim/neovim/commit/60e306368d5b6261acdcd88128461259663d8418

Commit in Vim: https://github.com/vim/vim/commit/aa3b15d

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim.

Please report to  https://github.com/vim/vim. Thanks!
