### ISSUE TITLE
Make `resize` and `vertical resize` respect `belowright` and `aboveleft`

### ISSUE THREAD

**Issue by I60R** [neovim/neovim#8270]
- `nvim --version`: v0.2.3-901-ga9c94f7bb
- Vim (version: 1-1542) behaves differently? no
- Operating system/version: Manjaro Linux
- Terminal name/version: alacritty
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```viml
nvim -u NORC
split
split
<C-w>j
resize 10
aboveleft resize 20
```

```viml
nvim -u NORC
vert split
vert split
<C-w>l
vert resize 10
vert aboveleft resize 20
```

### Actual behaviour
`aboveleft` has no effect, window always resizes at below|right side

### Expected behaviour
`aboveleft` makes window to resize at above|left size

**Comment by justinmk** [comment]
Can you send this to https://github.com/vim/vim ? People there are interested in enhancements like this, and we don't want to spend time on it here, because then we have to reconcile things if Vim later gets the same or similar behavior. Also if Vim intentionally doesn't want this behavior, it's likely there's a reason for it, so Nvim might not want it either.

We'll merge the patch as soon as Vim implements it.
