### ISSUE TITLE
Mouse doesn't work with $TERM=xterm or xterm-256color

### ISSUE THREAD

**Issue by Cerule** [neovim/neovim#8315]
- `nvim --version`: neovim-0.2.2+git20180421.7a13611ba, 0.2.2-2.2
- Vim (version: ) behaves differently? vim-8.0.1568-4.1.x86_64 works as expected
- Operating system/version: openSUSE Tumbleweed
- Terminal name/version: xterm-331-1.1.x86_64
- `$TERM`: happens with: xterm-256colors or xterm. works with 'xterm-color'.

### Steps to reproduce using `nvim -u NORC`

TERM=xterm
or
TERM=xterm-256color

```
nvim -u NORC <any text file>
```
issue command :set mouse=a
go to Insert mode, left/right click text or use mouse wheel

### Actual behaviour
left click inserts text like ';1M;1m' , '1;2M1;2m'
right clicking text or mouse wheel gives error: E73: tag stack is empty

### Expected behaviour
left clicking should move mouse cursor, mouse wheel should scroll text.

same behaviour with different terminals: xterm, xfce4-terminal-0.8.7, terminator
- maybe caused by some other package being updated since it has worked before with 'xterm-256color'

**Comment by justinmk** [comment]
> TERM: happens with: xterm-256colors or xterm. works with 'xterm-color'.

`xterm-256colors` is likely not a valid terminfo file on your system. Did you try with `xterm-256color` (no "s")?

With Nvim 0.3 (download it [here](https://github.com/neovim/neovim/releases) if you don't want to build from source) you can see terminal debugging info when the 'verbose' level is >=3 (see `:help 'verbose')`.  Try this (with the TERM that works _and_ the TERM that doesn't):

    nvim -V3log
    :q

Then the file named `log` will have a `--- Terminal info ---` section. Please post it. 

(Note: invoke `:q` manually, so that the builtin UI has a chance to start up. Don't add `-c "q"` in the command-line args.)

**Comment by Cerule** [comment]
> xterm-256colors is likely not a valid terminfo file on your system. Did you try with xterm-256color (no "s")?
It's a typo in report, should be 'xterm-256color'.
With Nvim 0.3, mouse seems to work as expected with all those $TERM values. Probably no need for logs then?
