### ISSUE TITLE
python os.chdir() takes no effect!

### ISSUE THREAD

**Issue by Yggdroot** [neovim/neovim#8336]
- `nvim --version`: v0.3.0-dev
- Vim (version: ) behaves differently? yes
- Operating system/version: all
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`
This issue is similar with https://github.com/neovim/neovim/issues/3636, but with some differences.

```vim
:python import os
:pwd
:python print os.getcwd()

:python os.chdir( SOME_OTHER_DIRECTORY )
:pwd
:python print os.getcwd()

```

### Actual behaviour
The pwd is still the same as before.

### Expected behaviour
The pwd should be `SOME_OTHER_DIRECTORY`.

**Comment by justinmk** [comment]
> This issue is similar with #3636

It's the _inverse_ of #3636. Now that #3636 you're asking for the opposite.

The only reason any of this works in Vim is because python runs in the same process as Vim.

To "fix" this in Nvim we would need to monkey-patch Python `os.chdir()`.

Or you could instead simply use `:cd` to change the directory instead of Python `os.chdir()`.

**Comment by Yggdroot** [comment]
`vim.chdir(*args, **kwargs)` works, I can use it as the workaround.
