### ISSUE TITLE
Redraw issues when scrolling one line or column at a time

### ISSUE THREAD

**Issue by snoblenet** [neovim/neovim#8390]
I'm using:
- the latest Alacritty, Rust & Cargo
- the latest Neovim, plug-ins and Python adapter
- the latest ZSH
- the latest Tmux
- the latest Mac OS X

I only see the following error in Neovim. However, the error only occurs when I scroll one line or column at a time (`h`, `l`, `j`, `k`) after long periods of use.

The problem that occurs is that each column or row is initially redrawn one row or column out when I scroll through it. See the picture:

![image](https://user-images.githubusercontent.com/62277/40039363-726499bc-5859-11e8-8358-0981f2b47761.png)

Is this likely to be a Neovim issue?

Cross-posted: https://github.com/jwilm/alacritty/issues/1310

**Comment by KillTheMule** [comment]
Writing "the latest" isn't particularly helpfull, things move to fast, and it's ambiguous besides (do you mean "latest release" or "latest HEAD" or "latest stuff that comes from my package manager").

This will be hard to go after, since there's basically no reproduction steps. Can you nail it down some more? How reliable does it occur? You should start eliminating factors, e.g. I don't think it would be very hard for you to simply replace alacritty with another terminal for some extended testing time, or remove tmux from the equation (depending on how reliably you can reproduce the issue). Good luck!

**Comment by snoblenet** [comment]
Confirmed to an issue when using double-byte fonts (e.g. the double-byte version of a Nerd Fonts patched font) with Alacritty

**Comment by justinmk** [comment]
@snoblenet Thanks for the followup.
