### ISSUE TITLE
silent! exec not executing silently

### ISSUE THREAD

**Issue by snoblenet** [neovim/neovim#8448]
- Tmux 2.7
- ZSH 5.5.2
- Mac OS X 10.13.4
- Alacritty @ 24e8a19e7d981fbc8853891ad4a17a9de2ac36bd
- Neovim v0.2.2 (full details below)
- $TERM: `xterm-256color`

### Steps to reproduce 

Type `:exec('silent! !ls')` or `:silent! exec('!ls')`.

### Actual behaviour

The screen flashes from the bottom, where console output appears.

### Expected behaviour

Nothing should flash on screen.

Note, there is no flash with `:silent! system('ls')`.

**Comment by justinmk** [comment]
`exec()` is not a function, and functions are called with `:call`. I assume you mean `:silent echo execute('!ls')` or something like that.

Cannot reproduce on `NVIM v0.3.0-1283-gf1bc152fa081`.

```vim
:silent echo execute('silent! !ls')  " no output
:echo execute('silent! !ls')  " shows output
```

**Comment by ZyX-I** [comment]
`:execute` accepts an expression, so writing `:exec(string)` is completely valid, though misleading about what is going on here. What is *not* working as OP expects completely is `:silent! system('ls')`: it would never possibly flicker *because it never runs `ls` in first place*. It just throws error about `system` being not a editor command which is then ignored by `silent!`. I do not see any flickering with either of `:exec('silent! !ls')` or `:silent! exec('!ls')`, though I would still suggest to not use use this misleading syntax and write `:execute 'silent! !ls'` or `:silent! execute '!ls'` without any parenthesis.
