### ISSUE TITLE
API: nvim_buf_add_highlight "priority"

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#8449]
There is a `priority` param in `matchaddpos` function that could overrule other highlight at same position, but it's not exists in `nvim_buf_add_highlight`

### Actual behaviour

* Highlight some text by using `*`.
* Run command like `call nvim_buf_add_highlight(1, 0, 'Error', 1, 0, 100)`.
* The previous highlight would be be overruled.

### Expected behaviour

I would expect a param to give highlight from nvim_buf_add_highlight higher priority. Or maybe make 
highlight from nvim_buf_add_highlight overrule other highlights.

BTW: I can't use `matchaddpos` because I found `matchdelete` would not work on BufLeave.

**Comment by RRethy** [comment]
Was this ever implemented? I don't see it in the docs so I assume no, but wondering if this may be looked into again in the future? Right now the use case is described by this [issue someone posted on reddit](https://www.reddit.com/r/neovim/comments/kiwrf6/treesitter_color_issue/). Essentially, plugins like vim-hexokinase and nvim-colorizer don't play nicely with treesitter since they all use `nvim_buf_add_highlight`, so whoever adds the highlight second wins and overshadows the previous highlight.

**Comment by vigoux** [comment]
I have implemented it but I don't think docs reflect this atm, I am not even sure `nvim_buf_add_highlight` actually can fiddle with the priority.
I'll try to check that at some point.

**Comment by bfredl** [comment]
`nvim_buf_set_extmark` has "priority" flag but it was never documented :D

**Comment by RRethy** [comment]
Interesting, I found the priority flag you mentioned and realized treesitter is highlighting with `nvim_buf_set_extmark` and a priority of 100.
