### ISSUE TITLE
If `loaded_python_provider` is invalidated, an error occurs in `checkhealth`.

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/neovim#8542]
If `loaded_python_provider` is invalidated, an error occurs in `checkhealth`.

### NeoVim version
0.3

### Environment
brew on Mac

### init.vim
```
let g:loaded_python_provider = 1
```

```
## Python 2 provider (optional)
- INFO: Disabled (g:loaded_python_provider=1).  This might be due to some previous error.
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          /usr/bin/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help provider-python
  - INFO: Executable: Not found
```

Is there a substitute for `g:loaded_python_provider`?

**Comment by justinmk** [comment]
You intentionally set the variable, so it's assumed you understand why checkhealth says python isn't working. And the first line says:

    INFO: Disabled (g:loaded_python_provider=1)

It is a bit confusing to see all of the other warnings, but there's not really much we can do.

We can't necessarily skip the checks if `loaded_python_provider==1` because (as checkhealth mentions) ` This might be due to some previous error.`.

We could set up a `dictwatcheradd(g:, 'loaded_python_provider'`, ...)` to try to make a smart decision. But that sounds like a lot of complication.
