### ISSUE TITLE
Consider implementing Vim 8 jobs and channels API

### ISSUE THREAD

**Issue by ryvnf** [neovim/neovim#8547]
Vim 8 has added jobs and channels which allows to execute scripts asynchronously.

The functions added for Vim 8 job control are the following:

	ch_canread()		check if there is something to read
	ch_open()		open a channel
	ch_close()		close a channel
	ch_close_in()		close the in part of a channel
	ch_read()		read a message from a channel
	ch_readraw()		read a raw message from a channel
	ch_sendexpr()		send a JSON message over a channel
	ch_sendraw()		send a raw message over a channel
	ch_evalexpr()		evaluates an expression over channel
	ch_evalraw()		evaluates a raw string over channel
	ch_status()		get status of a channel
	ch_getbufnr()		get the buffer number of a channel
	ch_getjob()		get the job associated with a channel
	ch_info()		get channel information
	ch_log()		write a message in the channel log file
	ch_logfile()		set the channel log file
	ch_setoptions()		set the options for a channel
 
	job_start()		start a job
	job_stop()		stop a job
	job_status()		get the status of a job
	job_getchannel()	get the channel used by a job
	job_info()		get information about a job
	job_setoptions()	set options for a job

Neovim already has an implementation of asynchronous jobs. The functions names used for that API does not conflict with the ones described above.

I think it would be nice for plugin developers to have one API which works for both Vim and Neovim. And I therefore think it would be a good idea to consider if it is possible to add the Vim API for jobs and channels to Neovim. A big downside of this is of-course that is redundant to implement 2 different API:s, and it would make it a lot more confusing when both functions like `job_start` and `jobstart` exist. If it is decided to implement the Vim 8 API, maybe the Neovim API could be deprecated and eventually removed.

What do you think about this?

**Comment by bfredl** [comment]
This ignores the biggest part of Nvim's API, namely the RPC API exposed to channels, see `:help api-global` and so forth. Until vim implements something as powerful, I see no reason to spend time on unification of some surface bits.

**Comment by KillTheMule** [comment]
https://github.com/prabirshrestha/async.vim might be of interest.

**Comment by justinmk** [comment]
When would this happen , with what resources, and what was gained after all of that effort? (I know,  I sound like you know who ;)

It's okay to use Vim. It's okay if plugins choose one or the other. 

Meanwhile it's not difficult for plugins to support both. FFS many vim plugins still support vim 7.2 etc. There's a long tradition of compatibility in vim plugins.

Also the Nvim API is totes better.  Spend an equal amount of effort with both before drawing a conclusion.

**Comment by wsdjeg** [comment]
@ryvnf you should ask vim's mantainer to implement the neovim's job API which is better and earlier.

**Comment by janlazo** [comment]
Vim had the opportunity for a compatible async API with neovim prior to 8.0 release but opted for a different approach that is increasingly hard to reconcile with. 8.1 is released already and Neovim is behind on the Vim 8.0 patches.

If anyone wants this (and `:Termdebug`),
1. Resolve all vim patches from initial `job_start` patch from Vim 7.4 to the first `:terminal` patch (8.0.0693). Some are likely marked N/A so you would have to traverse `version.c` history or go through all vim-patch PRs. Vim uses C89 while Neovim uses C99. Both have different code styles.
2. Figure out how to have `:terminal` compatibility since both implementations are async.
3. Once all job and channel patches from Vim 8.0 are resolved, then consider job/channel API compatibility while keeping up with Vim 8.1 patches.
4. Maintain both APIs or deprecate Neovim's API and fix all affected tests.
5. Go back to step 3 for the remaining Vim 8.x patches. At this point, Vim might have released 8.2 or 9.0.

Good luck to anyone who has the guts to undertake this because I'm don't and I'm still at step 1.

**Comment by bfredl** [comment]
Termdebug is already in good progress being ported to nvim `:terminal` (#8364), it doesn't need any of this.
