### ISSUE TITLE
statusline erased with wildmode=list

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#8611]
Using `set wildmode=list` and triggering the menu using `:e …<tab>` will erase the statusline:

![2018-06-21-152230_379x110_escrotum](https://user-images.githubusercontent.com/9766/41721714-f51614ba-7566-11e8-80f0-44f65d93a8b3.png)

Related: https://github.com/neovim/neovim/issues/8251

NVIM v0.3.1-85-g7ae7da8fb (master)

**Comment by wsdjeg** [comment]
As I know `wildmenu` is a boolean option, why you can use `list`?

**Comment by bfredl** [comment]
`set display-=msgsep`

**Comment by jamessan** [comment]
Pretty sure @blueyed means `wildmode=list`.

**Comment by blueyed** [comment]
@bfredl 
> `set display-=msgsep` should recover the old behavior if that is preferable.

Do you mean that it's not a regression then, but expected? - in contrast to what @justinmk marked?
Or is it just a workaround (like I'd assume, and @justinmk also marked :D)?

**Comment by bfredl** [comment]
It is intentional change of behavior (that the top of the screen is preserved and not the bottom), which by definition will break someone's workflow, but whether it is an general regression in usability is a question of judgement. We made sure to add an option so that the user could choose for themselves.

It might be worth noting, that my initial ~5-line hack [ab-]used the bottom statusbar as separator. However, this will of course be be misleading if messages cause it to be moved above a split, hence why we changed it to a fillchars separator. Though if a uses has context info there relevant for the completion, it might still be preferable, of course.

**Comment by blueyed** [comment]
I've noticed that I often rely on the bufname from the statusline during completion.

So I've gone back to using `set display-=msgsep` myself, but would rather like to just use the statusline instead of a blank line as the separator.

Would it be possible to have something like `set display+=msgsep_status` for this?

**Comment by justinmk** [comment]
But even with that proposed feature, the message pane could still obscure statuslines of other windows.  

Have you tried `wildmode=full` ?

**Comment by blueyed** [comment]
> Have you tried wildmode=full ?

Will try that, thanks.

Was using `wildmode=list:longest,list:full` before.
