### ISSUE TITLE
Handle OOM for specific cases

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#863]
Handle OOM for specific cases.

Known cases:
- undo/redo for very large changes: https://github.com/neovim/neovim/pull/708#discussion-diff-12956470

**Comment by fmoralesc** [comment]
This is not currently actionable, so I think it's safe to close. @justinmk Should I label issues like this as such, so we can clean up?

**Comment by justinmk** [comment]
I would consider this actionable. If we find many non-actional issues, we might need a separate meta-milestone so that they don't clutter up our list of non-triaged items. Milestones are the most important buckets.

**Comment by fmoralesc** [comment]
I considered this wasn't actionable because:

1) there's been no updates on this for a year, and the only related item was merged, 
2) there are no specific issue related to this, and 
3) as a consequence, there is nothing to do.

I feel this is more of a "note to self" than a real issue. These could be moved to the wiki.

**Comment by justinmk** [comment]
It is actionable. The action item is to implement OOM handling for certain cases. See https://github.com/neovim/neovim/pull/708#discussion-diff-12956470 for details.

I can remove the "TODO" thing if that is confusing the purpose.

**Comment by lewis6991** [comment]
Doesn't look like there's anything here to do anymore.
