### ISSUE TITLE
Switch project to Rust, is that possible at all?

### ISSUE THREAD

**Issue by zekefast** [neovim/neovim#8669]
I know that sounds very strange to change language for such a big code base. Proposals like this usually perceived as an utopia, but I still would like ask the question.

Neovim was started as a revamp of old code base to avoid issues and reboot community. I very apprecate your effort! Unfortunately old language can not solve many memory problems, but nowadays language like Rust pretty good at it.

Even better, that you can compile it in a way compatible with C. That should be very handy for transition period.

Except of solving issues and speeding up of development Rust should attract more people to Neovim community as many developers nowdays very curious about it.

Evaluation could be started with a small module to try it out and gather more experience about Rust.

So, what are thoughts of author and core community members on Rust in neovim code base?

**Comment by justinmk** [comment]
@zekefast How long do you estimate that it would take to migrate the project to rust? 

> Evaluation could be started with a small module to try it out and gather more experience about Rust.

Please let us know when that's complete.

**Comment by zekefast** [comment]
> @zekefast How long do you estimate that it would take to migrate the project to rust?
@justinmk, I have not done any estimation yet as I am not very familiar with Neovim code base yet.

> Earlier discussion about changing language: #153 (focus is on C++, but alternatives are also mentioned)
@bfredl Thank you!

**Comment by Shatur95** [comment]
> In Nvim we have begun to implement core features in Lua, to reduce the C footprint.

I am not in favor of rewriting the project in Rust, but wouldn't this greatly affect the performance of the editor?
We already have slow VSCode, despite the fact that Javascript is executed much faster then lua.

Sorry for necrobumping :) Just wondering about feature.

**Comment by glacambre** [comment]
On 2020-07-29 15:02, Hennadii Chernyshchyk wrote:
> We already have slow VSCode, despite the fact that Javascript is 
> executed much faster then lua.

Lua has implementations that are as fast as JavaScript's fastest 
implementations: https://gist.github.com/spion/3049314

Language speed doesn't matter much IMO. What's really important is 
allocation patterns and algorithmic complexity, problems that also exist 
in C unfortunately (see https://github.com/neovim/neovim/issues/3508 for 
example).

**Comment by Shatur95** [comment]
Yes, I agree. But honestly I do not know any good fast application that written in script languages. Usually there is native solutions that just works faster.
BTW, I using current LSP from the master and it works much better then any other implemented by third-party plugins for Vim.

**Comment by justinmk** [comment]
> I am not in favor of rewriting the project in Rust, but wouldn't this greatly affect the performance of the editor?

Vimscript is implemented in C. And Vim itself internally uses much of the slow parts of the Vimscript engine. So this comparison makes no sense at all.

**Comment by bfredl** [comment]
Rewrite it in https://github.com/ziglang/zig is the new Rewrite It In Rust.

**Comment by bfredl** [comment]
but seriously luajit cffi code (manipulating cdata and pointers) is just as fast as C after jit warmup latency (one time cost)

**Comment by Shatur95** [comment]
> kitty has a C core and Python shell. It's pretty fast.

I suppose that performance critical sections are written in C. But to me URxvt feels faster.

> So that's a counter-example ...?

No, I meant faster than Neovim. LSP in Neovim implemented in lua, isn't it? Of course this may be related to the implementation itself, not the language.

> but seriously luajit cffi code (manipulating cdata and pointers) is just as fast as C after jit warmup latency (one time cost)

Hope you are right.

**Comment by bfredl** [comment]
@Shatur95 have you tried the lua client yourself? plz report any concrete speed issues when you find them.

**Comment by Shatur95** [comment]
> @Shatur95 have you tried the lua client yourself? plz report any concrete speed issues when you find them.

Of course! I used 0.5 with built-in LSP. And it's **not slow**. But it feels **slower** to me than VSCode. At least for `clangd` (diagnostics and header parsing is slower) and `Godot LSP` (this server produce a lot of diagnostics, Neovim tries to show it instantly and becomes noticeably slow). I have used other LSP servers in Neovim as well, but only these I used in VSCode, so I can compare.
For clangd, this is not very noticeable, so I did not open an issue.
For Godot LSP this is very noticeable, but my [another issue](https://github.com/neovim/neovim/issues/12633) for this LSP server was closed because with `Not going to install every LSP to debug every LSP issue`. I can't fix the issue myself because I do not have a good knowledge in lua :(

**Comment by bfredl** [comment]
First thing is that we gonna fix incremental update (logic fix, no lang change needed)

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/question-including-rust-code-in-neovim/2653/3

**Comment by ii14** [comment]
We recently had a discussion about this on Matrix, specifically about Rust vs C++, so I figured I might as well include my take here. First of all, I'm not sure if moving to a different language is really necessary at all, and if it is then in my opinion Zig would be the perfect candidate, if it wasn't for the fact that it's not 1.0 yet. But if I had to pick between the two options then in my opinion C++ is the way to go.

The question is what really is the goal here. Is the goal actually improved memory safety? Or is it "we don't like C, we also don't like C++, but we do like Rust"? If that's the case then fair enough, it's a matter of preference and I can't argue with that. But if the goal is to move the *already existing* C code base to a safer language that prevents memory related bugs, then C++ seems to be the obvious choice for me.

The top 2 most common software bugs related to C (also the most relevant to us, what a coincidence) are out of bounds memory access and use after free. In C++ use-after-free bugs are solved with unique pointers and reference counting with shared pointers, that ensure you don't have any dangling pointers and free the resources when all references go out of scope. Out of bounds reads and writes can be solved by introducing runtime checks. And you don't need to change the containers we're using right now, just like with "smart pointers" or `std::span` we could have wrapper classes for the klib stuff that just add runtime checks on top of it. Simply refactoring the code to do these two things gets you 90% of the way there as far as memory safety is concerned.

I haven't written a single line of Rust in my life, so someone correct me if I'm wrong. From what I have heard about the language, it sounds to me like you wouldn't really be able to express some (or actually probably most) of the code we have right now. Rust could make sense for a new project or for implementing new functionality, but in my opinion it makes much less sense for porting the already existing C code, as Rust just wouldn't allow the stuff we're doing with C. And rightfully so. But this means introducing Rust wouldn't be just an incremental refactor, but a complete rewrite.

C++ on the other hand has a partial source compatibility with C. We can adjust the boundary of when to stick with C-style C++ and when to use safer C++ alternatives. This means we can potentially still port patches from vim, while with Rust we're abandoning vim entirely and are on our own.

I've made a simple experiment: converted one of the C source files (namely `buffer.c`, 4k lines) into C++ and made it compile (although with some warnings, because technically some stuff there were not permitted by the standard), and it took me about an hour. And that's only because I did it in the most inefficient way possible, trying to manually find where the problems in included header files are, instead of just trying to compile it and letting the compiler tell me what the issue is.

The problems in that particular case were implicit casts from `void *`, the use of C++ keywords as identifiers and the use of struct initializers that were introduced to C++ in C++20. Once I fixed the header files and got the ball rolling, converting the next file (`change.c`, 2k lines) took me no more than 10-15 minutes. Doing this for some of the other files could be a little bit harder though, but still you don't have to outright rewrite the entire thing from scratch.

Also, two observations: First, both C++ and Rust mangle symbol names, which I believe would make using LuaJIT's FFI in tests not viable anymore, unless we want to mark all the functions that need to be tested with `extern "C"` or whatever the equivalent in Rust is. Second, I don't know how the situation looks like with Rust, but C++ is hard to parse, which could be a problem for code and documentation generation. Not sure what the quality of the C++ treesitter parser is. I guess there is always the option of using libclang, but that's a huge dependency.

**Comment by jokeyrhyme** [comment]
I don't believe that Zig currently provides the same memory-safety guarantees that Rust offers: Zig's primary value over C (in my opinion) is that it forces the developer to handle memory allocation errors (which stable Rust does not yet do, but the Rust-for-Linux-kernel effort inevitably has to tackle), and having to handle OOM faults is definitely critical for certain use cases like OSes

Zig and Carbon both seem designed as low-hanging-fruit migration targets for existing C and C++ projects, but do not move the needle much in terms of memory-safety as a consequence of valuing compatibility/convenience so highly

> Doing this for some of the other files could be a little bit harder though, but still, you don't have to outright rewrite the entire thing from scratch and 99% of the code remains as it was.

This is similar to Mozilla's project to improve memory-safety in Firefox: replacing components with those written in other languages (i.e. Rust) piece by piece, see https://4e6.github.io/firefox-lang-stats/

> From what I have heard about the language, it sounds to me like you wouldn't really be able to express some (or actually probably most) of the code we have right now.

This is often the case: Rust's ownership model makes it very difficult to express error-prone data structures (e.g. circular references) or error-prone data access patterns (e.g. potentially changing the length/indices of a collection whilst iterating over it)

So, migration will often force one to reconsider such patterns (which may or may not be worth it depending on the project)

**Comment by ii14** [comment]
Yes, only Rust can make *guarantees* about memory safety. At the same time this doesn't mean that there isn't anything in between inherently broken C programs and rewriting the entire world in Rust. At least in terms of memory safety, moving from C to pretty much *any* language would be a huge improvement. Even if that safety is not always statically enforced by the compiler like in Rust.

C makes it hard to write safe code. Rust makes it hard to write unsafe code. C++ is somewhere in the middle and allows both. Of course this is going to be different when you have to deal with legacy C code, but in practice when I personally write new C++ code I almost never run into these memory related bugs that I do when writing C code.

**Comment by cathaysia** [comment]
Does anyone have considerations other than security? Compared with c and c++, rust provides more functions out of the box. And cargo is obviously better at managing external dependencies.
