### ISSUE TITLE
Restrict Wiki Editing to Known Collaborators only

### ISSUE THREAD

**Issue by InsidiousMind** [neovim/neovim#8738]
Not sure if it was intentional to make the wiki editable by any lonesome Github user who stumbles upon it, but I think Wiki Editing permissions should be restricted.

Stumbled upon the wiki from here: https://github.com/neovim/neovim/issues/3375, but was greeted by the edit page of the (now non-existent) 'troubleshooting' section

**Comment by mhinz** [comment]
We had no problems with people going postal so far.

Since there's no finer-grained access model, letting all people edit the wiki is better than the alternative. 

People add how to do things with their systems all the time and it's also useful for letting them add their own plugins in [Related projects](https://github.com/neovim/neovim/wiki/Related-projects) etc.

**Comment by wsdjeg** [comment]
I agree with mhinz, since neovim's users who never contribute code to neovim should be able to edit the wiki.

**Comment by mhinz** [comment]
Okay, we won't change this, so I'm closing this issue.

We appreciate the concerns though! ✨
