### ISSUE TITLE
defaults: disable 'joinspaces'

### ISSUE THREAD

**Issue by ds26gte** [neovim/neovim#8795]
The option `'joinspaces``  is set by default. Having two spaces after every sentence is no longer a majority preference, and should arguably be opt-in rather than opt-out.

(Vim also sets `'js'` by default, but Neovim is known to part ways when it comes to its default option settings.)

**Comment by justinmk** [comment]
Vim's own help files (traditionally) use two spaces after a sentence (though we don't always follow this in Nvim help docs).

I think two spaces are seeing a resurgence in popularity, especially for fixed-width fonts. It's certainly not a majority but we generally don't change things unless the change supports a "super majority" or if a Nvim maintainer is willing to fight endless battles to defend the change :)

**Comment by janlazo** [comment]
With `set joinspaces`, is there a buildup of spaces after breaking and joining the same lines multiple times?

**Comment by justinmk** [comment]
@janlazo depends on how you break the line. I use:

    nnoremap gj i<c-j><esc>k$

**Comment by venthur** [comment]
I also wonder about this option. Because `joinspaces` seems to be effective only when you join lines or paragraphs. So if you write you text without the double spaces after a sentence, you'll see it **only** at the point where you joined two paragraphs like so:

```
this is some paragraph. observe the single spaces! and so on. HERE!

HERE! this is the second paragraph. lorem ipsum.
```

becomes:

```
this is some paragraph. observer the single space! and so on. HERE!  HERE! this is the second paragraph. lorem ipsum.
```

AFAIK there is no other command that will actually **add** the two spaces after a sentence when reformatting right (like: `gq`)?

So from this point of view I'd also be in favor of disabling `joinspaces`.

**Comment by mjlbach** [comment]
This was closed in https://github.com/neovim/neovim/pull/15410
