### ISSUE TITLE
Visually lags when using auto-closers

### ISSUE THREAD

**Issue by ryanleh** [neovim/neovim#8812]
Hi,
I'm running NVIM v0.3.1 inside Konsole on Arch Linux.  I just switched over from Vim and noticed some visual lag when holding down keys (holding down the backspace probably caused the most amount of lag).  Through process of elimination I found that removing delitmate solved the issue.  Sadly, installing Auto-close and Auto-pairs had identical results.  
[vimrc.txt](https://github.com/neovim/neovim/files/2259191/vimrc.txt)

**Comment by ryanleh** [comment]
Ok, the lag does not happen in Gnome Terminal (or at least much less noticeably)

**Comment by justinmk** [comment]
Sounds like an interaction with `getchar()` (probably used internally by the auto-closer) or `timeoutlen` option. I don't know why you wouldn't see it in Vim. 

If you can provide minimal steps to reproduce the issue starting with `nvim -u NORC`, we can look into it. Otherwise this isn't actionable.
