### ISSUE TITLE
:Tutor custom statusline disables ruler

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#8842]
The tutor's custom statusline probably is more confusing than helpful, because it doesn't allow the user to see the typical vim statusline.

In particular, it mentions the ['ruler'](https://github.com/neovim/neovim/blob/f1bc152fa081f5d630ea1a027aa5bd00bdbb78f0/runtime/tutor/en/vim-01-beginner.tutor#L469) option but `:set ruler` has no effect because of the custom statusline.

@fmoralesc what do you think?

**Comment by fmoralesc** [comment]
Hi! I think it would be fine to change this, leaving the default statusline instead of changing it. I liked the idea of having a "clean" statusline in the tutorial, but it doesn't really matter all that much. Consistency is more important. Also, I guess hiding the default statusline is not a good idea when it comes to teaching new users how the editor behaves...
