### ISSUE TITLE
system-wide configuration file

### ISSUE THREAD

**Issue by pfactum** [neovim/neovim#8994]
- `nvim --version`:

```
[~]$ nvim --version
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

[~]$ nvim -e --cmd 'echo $VIM|quit'
/usr/share/nvim

[~]$ nvim -e --cmd 'echo $VIMRUNTIME|quit'
/usr/share/nvim/runtime
```

- Vim (version: 8.1) behaves differently?

Yes, vim has `/etc/vimrc`.

- Operating system/version:

Arch Linux

- Terminal name/version:

Konsole

- `$TERM`:

`xterm-256color`

### Steps to reproduce

No system-wide configuration file is used from `/etc`. Instead, the one in `/usr` is used.

### Actual behaviour

nvim reads `/usr/share/nvim/sysinit.vim` as a system-wide configuration file, but this is a vendor-provided file, thus it shouldn't be touched by the user.

### Expected behaviour

nvim should read a system-wide configuration file from `$XDG_CONFIG_DIRS/nvim/sysinit.vim` so the user can customise it.

**Comment by jamessan** [comment]
>     * Vim (version: 8.1) behaves differently?
> 
> 
> Yes, vim has `/etc/vimrc`.

No, Vim also defaults to a file under /usr.  However, most packagers either change Vim's configuration or install a symlink.  The packagers could do the same thing for Nvim.

However, I agree that Nvim should have a sane default instead of requiring packagers to do this.

I can't work on this in the short-term (due to lack of computer), but if no one else picks it up once that resolves, I will.

**Comment by justinmk** [comment]
Isn't this covered by `XDG_CONFIG_DIRS` (which is supported by Nvim, see `:help xdg`). Therefore Nvim will search for

    /etc/xdg/nvim/init.vim

by default.

- `:help 'runtimepath'`
- https://wiki.archlinux.org/index.php/XDG_Base_Directory
- `:help xdg` or `:help base-directories`

Note that `/etc/xdg/nvim/init.vim` is not sourced if `~/.config/nvim/init.vim` exists.

**Comment by jamessan** [comment]
```
$ nvim --version
...
   system vimrc file: "$VIM/sysinit.vim"
...
```

_This_ is what I'm suggesting changing.  It should use `$XDG_CONFIG_DIRS/nvim/sysinit.vim` instead.

There's also a small documentation issue currently at `:help system-vimrc` since it refers to `$VIM/vimrc` rather than `$VIM/sysinit.vim`.  That could be fixed independently, but it would need to be changed again with my proposed change.

**Comment by jdhao** [comment]
In Neovim version 0.5, `nvim --version` still shows the following message:

> system vimrc file: "$VIM/sysinit.vim"

However, according to `:h sysinit.vim`, `/etc/xdg/nvim/sysinit.vim` will be used as system Neovim config if it exists. So the above message a bit misleading.
