### ISSUE TITLE
buffer enhancements

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#901]
Make buffers (or a specialized buffer type, say `set buftype=log`) less expensive and easier to work with.
### Less expensive:
- ~~One thing that makes buffers relatively expensive is: undo. There is a patch floating on vim_dev which supports buffer-local undolevels~~ **edit:** _This patch seems to have been accepted in Vim 7.4.073._

In Emacs, buffers are cheap and ubiquitous. They are the fundamental data structure: it is sane and idiomatic to store small bits of data or lots of text in a buffer to pass it around and manipulate it. I'm not suggesting that Neovim needs to reach for that, but there is a gap in Vim currently that makes it difficult to work with buffers other than the current buffer.

We may be able to achieve "inexpensive" buffers by combining the existing Vim options: `setlocal undolevels=-1`, `buftype= "nofile"`, `noswapfile` (also `bufhidden` and `buflisted` may be useful). But there are some other considerations: 
- need to preserve jumplist 
- need to preserve "alternate" buffer
- need to preserve "previous window"
- avoid unwanted/unexpected autocmd triggering
### Easier to work with:

Currently, to work with buffers you must use something like `:noau tabdo windo` and you must remember the tab/window you started on and return to it. This is extremely difficult to work with, and it causes flicker.
- It should be easy to insert text into any buffer, from any other buffer. 
  - E.g. `call bufputlines(<buffer id>, line5, ["foo", "bar"])`
- It should be easy to read text from any buffer, from any other buffer. 
  - E.g. `call bufgetlines(<buffer id>, line5, line11)`
- [too risky/not worth it?]: It should be easy to execute a function in any buffer, from any other buffer.
  - E.g. `let g:foo = bufeval(<buffer id>, 'foo()')`
- It should be easy to create a new buffer and get the new buffer id (instead of using `:keepalt enew` and switching back to the previous buffer)
  - E.g. `let g:newbuf = bufnew(<options>) | call bufputlines(g:newbuf, 0, ["foo", "bar"])`
### More useful:
- It is currently difficult for users to access the output of `:messages`. There's no good reason for this.
  - Example: if user wants to see the errors/results of the last command, user must re-run the command with `:redir`. User should be able to `bufgetlines(<message buffer id>, ...)`.
- Rather than popping up a log window (which is a constant problem on Emacs), I suggest providing a `'statusline'` token that will show activity or even a count of unread log messages.
- Sending `:!` shell output to a log buffer could allow us to completely remove the dreaded "Press ENTER or type a command to continue" message. The results would be sent passively to the associated log buffer and consumed easily (after the enhancements suggested by this issue)
  - similar for `system()`, `gx`, etc.

**Comment by jalvesaq** [comment]
It would be good if it was possible to change the contents of a buffer without moving the cursor to it. For example, things may not happen smoothly if Neovim receives a message and this message triggers a function that opens a new tab, inserts some contents in the new buffer and moves the cursor back to the original buffer. If the user is in Insert mode, typing text, the letter typed immediately before (or after?) the message was received will be put in front, instead of behind, the cursor. That is, if the text being typed is "abcdefgh" and the message is received while the letter "d" is being pressed the result will be "abcefgh|d", where the bar indicates the cursor position. Below is a code to check the problem:

```vim
function! OpenNewTab()
    tabnew NewTab
    " Pretend to do something complex
    sleep 20m
    normal! gT
endfunction

call jobstart(['sh', '-c', 'sleep 2'], {'on_exit': function('OpenNewTab')})
" Do
"    :so %
" Then, go to Insert mode and type quickly below while waiting the job exit...
"
```

Since this limitation was inherited from Vim, and the changes necessary to solve it were classified by @justinmk as "too risky/not worth it" in the message opening this issue, I think that it should be addressed only after the first release.

**Comment by justinmk** [comment]
## Resolution/Summary

Most of this was implemented, or covered by other tickets.

> We may be able to achieve "inexpensive" buffers by combining the existing Vim options

Nvim 0.4 API has `nvim_create_buf({listed}, {scratch})`.

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a ticket if you have new information/topics to discuss._
