### ISSUE TITLE
NeoVim super buggy on Windows?

### ISSUE THREAD

**Issue by keithn** [neovim/neovim#9029]
I thought I'd give NeoVim a go since it's supposed to be an improvement, but on windows nearly every step I take things just don't seem to work

the version I got via chocolatey (as the docs for NeoVim recommend) is NVIM v0.3.1

Installed and instead of trying to haul in my vim config I thought I'd start from scratch, install vim-plug...

- First thing I noticed is if the init is wrong in the slightest way, you can't load nvim via the command line, it says "Press Enter to continue", but you can't, you have to break out of the program.  Oh well, just use vim to fix it up.

- If I try to start the nvim-qt via the command line, it doesn't load the file on the command line, but it thinks it has but the terminal is blank

I'm a bit lost now, it's kind of unusable like this.  Maybe I've somehow gone down the wrong path getting started.

**Comment by justinmk** [comment]
1. it's an old and somewhat difficult/multi-layered problem (#1984) which we've recently begun addressing in https://github.com/equalsraf/neovim-qt/pull/463 and https://github.com/neovim/neovim/pull/9024.
2. I don't know what that means but maybe you're running into https://github.com/equalsraf/neovim-qt/issues/417 which was fixed but maybe chocolately is using an old version of nvim-qt (probably because Nvim hasn't released a new stable version which would include the new version of Nvim-Qt). Try the development (HEAD) version if chocolately supports that.

There's at least one other old annoying bug on Windows regarding clipboard. Since a few months ago, Nvim now fully supports building on MSVC, so it would be nice if we had some Windows devs spend time debugging a few of the Windows issues (there aren't that many, and fixing a few of them would make the Windows experience pretty solid).
