### ISSUE TITLE
`MANWIDTH=9999` breaks `:Man` on FreeBSD

### ISSUE THREAD

**Issue by raichoo** [neovim/neovim#9065]
I've been having issues with `:Man` on FreeBSD recently. Manpages won't get displayed anymore and neovim just spins in an endless loop in `put_page` in the `man.vim` file.

The problem is that `MANWIDTH` is being set to `9999`, this setting yields an error under FreeBSD.

```
$ env MANPAGER=cat MANWIDTH=9999 man ls
mandoc: -O width=9999 is too large
mandoc: -O width=9999: Bad argument
```
I'm currently setting the value to 80 to work around this issue.

**Comment by justinmk** [comment]
What's the biggest it will allow? Is it checking $COLUMNS ? (IE controlled by terminal size ?)

**Comment by raichoo** [comment]
Apparently `mandoc` expects a range between 1 and 1000. https://github.com/freebsd/freebsd/blob/master/contrib/mandoc/manpath.c#L309-L312

**Comment by raichoo** [comment]
Just a side note: the range mandoc expects is inclusive so `MANWIDTH=1000` should also work. I've tried it on the command-line and it started bailing at 1001. 1000 was still fine.

**Comment by raichoo** [comment]
Okay, I've tried the patch on my system and manpages can come out pretty ugly.

![2018-09-30-201419_564x364_scrot](https://user-images.githubusercontent.com/151506/46260980-82781080-c4ed-11e8-96ef-1b9df1ad940e.png)

**Comment by justinmk** [comment]
@raichoo That should not happen, [this line](https://github.com/neovim/neovim/commit/3999aa755e28302b03b1a8db5ecd9cf627c01de9#diff-2451f3ce2ccfcf4300067af16309cd75R173) replaces those big whitespaces in the header/footer.  What are the exact contents of that header in your screenshot? I'm wondering if it is made of tabs instead of spaces, then  199 is too big to match it.

**Comment by raichoo** [comment]
Sorry, my bad. I've forgot that one line in the commit.
