### ISSUE TITLE
API: nvim_set_keymap method to add key bindings/mappings

### ISSUE THREAD

**Issue by svermeulen** [neovim/neovim#9136]
- `nvim --version`:  NVIM v0.3.2-707-g082e14557, LuaJIT 2.0.5
- Operating system/version: Windows 10

I sometimes add bindings directly inside lua, and have noticed that it's over 2x slower compared to doing this in vimL.  See [here](https://github.com/neovim/neovim/issues/9135) for my testing setup

I discussed this with @justinmk in gitter and he suggested that part of the difference could be explained by vimL parsing, and that it might be worthwhile to add a new api method to avoid this.  Either something like `nvim_map` or a more general purpose `nvim_command_2({command}, {arg1}, ...)`

**Comment by KillTheMule** [comment]
See https://github.com/neovim/neovim/pull/8677 for current efforts to improve the lua API. Right now, mapping calls out to vimscript, which could of course be changed and backed by C code. I don't think it's worthwhile to do so for bindings though.

**Comment by bfredl** [comment]
> I sometimes add bindings directly inside lua, and have noticed that it's over 2x slower compared to doing this in vimL. 

When making claims like this it is useful to specify absolute numbers also. If I understand the linked issue correctly, we are talking about 98ms for 4000 mappings, or 24 μs per mapping. I agree that an API method for mappings would be useful, but I would say the main concern there would be convenience and correctness (one layer of string escaping less to think of) or feature additions (plugin namespaces?), rather than speed.
