### ISSUE TITLE
build: BuildLibuv.cmake: use libuv upstream CMakeLists.txt

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#9182]
Since #7506 our "bundled"  version of libuv now [includes CMakeLists.txt](https://github.com/libuv/libuv/commit/7e6681f733629cec91116dab8f9e72059e00e91e).

Currently our `third-party/cmake/BuildLibuv.cmake` uses the old libuv `autogen.sh` script. Instead, we should use libuv's `CMakeLists.txt`. Then at least we don't need to [track upstream tree changes](https://github.com/neovim/neovim/pull/7506/commits/8480b74010254a23768085796ef0518becce1df6).

A starting point might be `third-party/cmake/BuildMsgpack.cmake` .

**Comment by clason** [comment]
We no longer use bundled libuv on Windows.

**Comment by erw7** [comment]
The main focus of this issue is to change  to use [`CMakeLists.txt`](https://github.com/libuv/libuv/blob/v1.x/CMakeLists.txt) included in libuv instead of our [`third-party/cmake/BuildLibuv.cmake`](https://github.com/neovim/neovim/blob/master/third-party/cmake/LibuvCMakeLists.txt). But, we are still using [`third-party/cmake/BuildLibuv.cmake`](https://github.com/neovim/neovim/blob/master/third-party/cmake/LibuvCMakeLists.txt). Therefore, I think this still needs to be kept open.

**Comment by dundargoc** [comment]
Damn. Our minimum version is currently 3.10, seems like fetchcontent is from 3.11. @jamessan is probably the goto person to ask if it's worth upgrading.

**Comment by jamessan** [comment]
Whether or not to use FetchContent is covered by #11123.  This issue is purely about switching our libuv build from autogen.sh to CMake, which can be done at any time.
