### ISSUE TITLE
Nested nvim instances in :terminal

### ISSUE THREAD

**Issue by Flying-Toast** [neovim/neovim#9334]
### Steps to reproduce using `nvim -u NORC`

`nvim -u NORC`
`:terminal`
`nvim` (run inside the the new `:terminal`)

### Actual behaviour
Neovim runs a (very buggy) nested instance of itself from within the terminal emulator.

### Expected behaviour
Neovim should open a new tab instead of running a new nvim inside of the terminal emulator (or provide a way to set this in config).

**Comment by justinmk** [comment]
> Neovim runs a (very buggy) nested instance of itself

Do I really need to ask what "very buggy" means? That obviously is not an actionable bug report. And obviously it's not a common problem, otherwise we would have heard many reports about this. I certainly can't reproduce it, and we have hundreds of tests that depend on it not being very buggy.

> Neovim should open a new tab instead of running a new nvim inside of the terminal emulator (or provide a way to set this in config).

It's planned in some form. Search existing issues.
