### ISSUE TITLE
Synthax highlight for gnuplot scripts is incorrect

### ISSUE THREAD

**Issue by marespiaut** [neovim/neovim#9375]
- `nvim --version`: `NVIM v0.3.1` and `NVIM v0.3.2-1027-g7a8dadbed`
- Vim (version: ) behaves differently? No
- Operating system/version: Arch Linux
- Terminal name/version: `XTerm(337)`
- `$TERM`:  `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC ./script.gp
```

Script I am using:
```
reset

set multiplot layout 5, 1 title "Analysis of the evolution" font ",12"
set key top center

# set multiplot           # engage multiplot mode
# set size 1.0,1.0        # sets the size of the first plot

pl 'et.dat' u 1 w l lc 2 lw 3 title sprintf("Taille de la population (à la fin %d)", last_pop), \

pl 'et.dat' u ($3/$4) w l lc 1 lw 3 title "Rapport Moyenne / Variance", \
    1 lc 0 lw 1 lt 2 notitle

set bmargin at screen 0.05
stats 'et.dat' using (last_pop=$1) nooutput
stats 'et.dat' using (last_nb=$2) nooutput

set xl "Nombre de générations"
pl   'et.dat' u 2 w l lw 3 lc 3 title sprintf("Nombre d'ET (à la fin %d)", last_nb), \
# pl 'et.dat' u ($2/$1) w l lw 3 title sprintf("Nombre moyen d'ET")

unset bmargin
set size 0.35,0.35        # set the size of the second plot in plot units
set origin 0.06,0.2     # set the origin for the second plot in plot units

set title sprintf("Distribution des %d ET dans la population à la fin de la simulation", last_nb)
unset xl
stats 'population.dat' using 1 nooutput name 'pop_'
set xrange [pop_min:pop_max+1]
binwidth = 1
binstart = 00
load 'hist.fct'
plot 'population.dat' i 0 @hist ls 1 notitle
unset multiplot
```

### Actual behaviour

Syntax highlight is incorrect. Comments are not grayed out.

### Expected behaviour

Correct syntax highlight.

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim.

Syntax plugins (e.g. for ruby/java/YAML) are maintained by the maintainer listed at the top of the plugin file. Please report to that person, or to https://github.com/vim/vim. Thanks!
