### ISSUE TITLE
executable() bug if $PATH has whitespace

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#9391]
- `nvim --version`: 

```
NVIM v0.3.2-1015-gaec096fc5
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently? yes
- Operating system/version: win7
- Terminal name/version: NONE
- `$TERM`: cmd.exe

### Steps to reproduce using `nvim -u NORC`

1. In install google vimdoc. 

in cmd.exe windows:

```
git clone https://github.com/google/vimdoc.git
cd vimdoc
python setup.py config
python setup.py build
python setup.py install
```
now in cmd windows I can use `python -m vimdoc -h` to get vimdoc help info. in windows user should not be able to use `vimdoc -h`, because `vimdoc` is not executable file in windows.

```
nvim -u NORC
:echo executable('vimdoc')
It return 1
```

### Actual behaviour

In neovim, `:echo executable('vimdoc')` return 1, but in vim8 it return 0.

EDIT:

now `exepath('vimdoc')` return `C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Scripts\vimdoc`

### Expected behaviour

I think, in window os, It should return 0.

**Comment by justinmk** [comment]
> neovim in windows executable function is broken

Based on what? It depends on `PATHEXT` and `PATH`. 

>  in windows user should not be able to use vimdoc -h, because vimdoc is not executable file in windows.

It is executable. Every file in Windows is executable.

> I think, in window os, It should return 0.

Why?

**Comment by wsdjeg** [comment]
@justinmk But I can not use `system('vimdoc .')`, it show me vimdoc is not a executable command.

**Comment by bfredl** [comment]
Even if all absolute paths can be, I think only files with ending in `$PATHEXT` can be executed via `$PATH`. The docs mention:

    If $PATHEXT is not set then ".exe;.com;.bat;.cmd" is used.

**Comment by janlazo** [comment]
Is `vimdoc` executable for sh/bash? If yes, then do you want `executable` to depend on the shell?
If cmd.exe, require file extensions such that `vimdoc` should provide a batchfile shim `vimdoc.cmd`.

Current behavior is a compromise for cmd.exe/powershell and sh/bash. `PATHEXT` behaviour is inherited from Vim but is misleading because `PATHEXT` is for omitting file extensions and these file extensions should refer to cmd.exe batchfiles or `*.exe` executables only. It is intended as a subset of extension->filetype->executable association. If `*.py` is associated with the `python.exe` executable, then the user can run `.\foo.py` or `foo.py` if in `%PATH%`.

**Comment by wsdjeg** [comment]
@bfredl In neovim, after run `:terminal` I can use `ctags`

```
C:\Users\Administrator\.SpaceVim>ctags
ctags: No files specified. Try "ctags --help".
```

but in neovim `:echo executable('ctags')` returen 0

Should I open new issue or just edit this issue?

**Comment by wsdjeg** [comment]
here is how I change my PATH, I do not set it in windows os, I use vimrc;

```
    if s:SYS.isWindows
        " Downloads gun global from:
        " http://adoxa.altervista.org/global/
        " GLOBAL 6.6.3 Win32 (938k)
        let $PATH .= ';D:\Program Files\gtags\bin'
        " Downloads coreutils from
        " https://nchc.dl.sourceforge.net/project/gnuwin32/coreutils/5.3.0/coreutils-5.3.0-bin.zip
        " coreutils-5.3.0-bin.zip
        let $PATH .= ';D:\Program Files\coreutils\bin'
        " Downloads grep from
        " https://nchc.dl.sourceforge.net/project/gnuwin32/grep/2.5.4/grep-2.5.4-setup.exe
        let $PATH .= ';D:\Program Files\GnuWin32\bin'
        " Add bin path, in this path, there are ag, rg, pt, etc.
        " ag: 
        "   sources: https://github.com/ggreer/the_silver_searcher
        "   bin:     https://github.com/k-takata/the_silver_searcher-win32/releases
        " rg:
        "   sources: https://github.com/BurntSushi/ripgrep
        "   bin:     https://github.com/BurntSushi/ripgrep/releases
        " pt:
        "   sources: https://github.com/monochromegane/the_platinum_searcher
        "   bin:     https://github.com/monochromegane/the_platinum_searcher/releases
        let $PATH .= ';D:\bin'
        "
        " When using neovim in windows the only var need to be set is:
        " PYTHON_HOST_PROG 
        " C:\Python27\python.exe
        " PYTHON3_HOST_PROG
        " C:\Users\Administrator\AppData\Local\Programs\Python\Python37\python.exe
    endif
```

**Comment by janlazo** [comment]
https://github.com/vim/vim/commit/8295666dc2c65e42135b91d5c61e2a140d002333 
Vim's `executable` uses `mch_can_exe` which checks if the shell is `sh`.

**Comment by wsdjeg** [comment]
Ok， I got it, after I run following command, executable('ctags') return 1


```viml
let $PATH = substitute($PATH, ' ', '\\ ', 'g')
```

**Comment by wsdjeg** [comment]
vimdoc, is just a python script, if I run:

```vim
exe 'e '.  exepath('vimdoc')
```

I can see:

```
#!C:\Users\Administrator\AppData\Local\Programs\Python\Python37\python.exe

import vimdoc.__main__

vimdoc.__main__.main()
```

**Comment by wsdjeg** [comment]
Hi, I do not knwo if it is a bug of neovim's `executable()`, my reproduce step is:

1. open neovim, run `:echo executable('rg')`, it return 1
2. run flygrep, or just run denite
3. `:echo executable('rg')` then return 0, `:echo executable('cmd')` return 1
4. run `let $PATH= 'D:\bin;'. $PATH`, then `:echo executable('rg')` then return 1

NOTE: my rg.exe whole path is `D:\bin\rg.exe`

________________________________
wsdjeg@outlook.com

**Comment by wsdjeg** [comment]
@justinmk here is how I config path:

https://github.com/neovim/neovim/issues/9391#issuecomment-450289864

**Comment by justinmk** [comment]
@wsdjeg is your resulting `$PATH` the same in Vim and Nvim? And is the `substitute($PATH, ' ', '\\ ', 'g')` needed in Vim?

**Comment by wsdjeg** [comment]
same config in neovim and vim. in Vim it works well.

**Comment by janlazo** [comment]
If you create a batchfile to set environment variables instead of using your vimrc, does `executable` work?
nvim appends the current directory to `PATH` for `executable`. I want to confirm that modifying `$PATH` with vimrscript in nvim is not causing the problem.

**Comment by erw7** [comment]
@wsdjeg You are using spacevim. Automatic directory change is enabled by default in the [spacevim document](https://github.com/SpaceVim/SpaceVim/blob/81e09ceae968c201f87e3b8e0efb6f2de3af4d01/doc/SpaceVim.txt#L684). And in Windows, `executable()` prepend current working directory to `$PATH`(see [src/nvim/os/fs.c#L341](https://github.com/neovim/neovim/blob/c4c74c3883aa3122c0c877ca8dd7b26beb5cc4aa/src/nvim/os/fs.c#L341)). Is not the result of `executable()` changed due to change of current working directory?

**Comment by wsdjeg** [comment]
I do not switch dir when using this function. and there is no space in the path of current working dir.

**Comment by erw7** [comment]
@wsdjeg You wrote in https://github.com/neovim/neovim/issues/9391#issuecomment-450339681 that the result of executable will be different before and after run flyagrep or run denite. Is not the current working directory changed due to the execution of flyagrep or denite and the result is different?

> and there is no space in the path of current working dir.

In this case, what you need to check does not mean there is no space in the current working directory. Make sure that the current working directory and the file rg* do not exist there before and after run fly grep or run denite.

If you think there is a bug about `$PATH` that contain spaces in `executabe()` of neovim, why do not you confirm the following? What you write is missing what we need.

```
set SAVED_PATH=%PATH%
set PATH=%PATH%;D:\Program Files\gtags\bin;D:\Program Files\coreutils\bin;D:\Program Files\GnuWin32\bin;D:\bin
dir D:\Program Files\gtags\bin\ctags*
dir D:\bin\rg*
"C:\Program Files\nvim\bin\nvim" -u NORC
:echo $PATH
:echo glob('ctags*')
:echo executable('ctags')
:echo glob('rg*')
:echo executable('rg')
:q
```

```vim
" minimal.vim
let $PATH .= ';D:\Program Files\gtags\bin'
let $PATH .= ';D:\Program Files\coreutils\bin'
let $PATH .= ';D:\Program Files\GnuWin32\bin'
let $PATH .= ';D:\bin'
```

```
set PATH=%SAVED_PATH%
"C:\Program Files\nvim\bin\nvim" -u minimal.vim
:echo $PATH
:echo glob('ctags*')
:echo executable('ctags')
:echo glob('rg*')
:echo executable('rg')
:q
```

This https://github.com/neovim/neovim/issues/9391#issuecomment-450463913 is also so. Before answering you need to compare the results of `:echo $PATH` with vim and neovim.

**Comment by erw7** [comment]
@wsdjeg If `:echo executable('ctags')` returns 1, what is the result of `:echo exepath('ctags')` and `:echo $PATH`?

**Comment by wsdjeg** [comment]
@erw7 I need to create mini reproduce step, my current evn is hard to debug.
