### ISSUE TITLE
API: receive mouse hover events

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#9534]
I hope that there's some way neovim could send mouse hover event (including window id, line number and column number) to client. The event could be used for open a floating window nearby which improves debug experience.

**Comment by justinmk** [comment]
@bfredl 	Any reason this could not be another `action` for `nvim_input_mouse` ?

**Comment by justinmk** [comment]
"not" should not have been in my comment, mistaken edit :)

**Comment by drewboardman** [comment]
Is there a click event? It would be nice to use coc.nvim to Ctrl+click to get documentation.

**Comment by dsych** [comment]
Is there any plan to implement this? Maybe I could have a crack at it if someone where to point me in the right direction?

**Comment by bfredl** [comment]
@dsych well there are two pieces here

1) defining the API, probably an event inside nvim_input_mouse, and an ui_option to turn on/off.
2) provide the terminal implementation of this api in tui/input.c

The first one should be pretty straightforward (I and other core devs can easily help fill the gaps).  The second one would require a little bit of research. are there standard sequences in termcap/terminfo for this? what does vim do to implement it efficiently?

**Comment by dsych** [comment]
@bfredl I looked into how vim is handling mouse hover for terminal first (this is my use case) and it seems to be piggy-backing off of existing logic for timers. It appears that timers are part of the main event loop for vim. I looked at how vim implements `beval` functionality, I know that nvim is not going to support that particular feature, but it helps to see how it is implemented in the original.

If you look at the [ui_wait_for_chars_or_timer](https://github.com/vim/vim/blob/339c1bdbdfb823c4ea36242f0a4f083cbc010b84/src/ui.c#L426), which is used to read characters from keyboard **OR** trigger any available timers. Finding line [447](https://github.com/vim/vim/blob/339c1bdbdfb823c4ea36242f0a4f083cbc010b84/src/ui.c#L447) you can observe the call to the `check_due_timer` function that in turn is triggering mouse hover if the timer is past due [right here](https://github.com/vim/vim/blob/22286895fce0e45e42126c7f2e35ebf43bc625d9/src/time.c#L565).

Consequently, this approach does not seem to be a viable one for nvim, since it is using `libuv` for all of the async stuff. However, we could do something similar:
1. Register a timer in the main event loop once during initialization.
2. Check if we exceeded the user defined `hover_timeout`.
3. Trigger an autocommand event? User would than be able to subscribe to it and determine the position of the mouse pointer.

**Comment by bfredl** [comment]
@dsych we can use either a `TimeWatcher` for c code, or the luv timer api if we implement hover logic in lua. What we need to do before that is getting the mouse events from the terminal to nvim in the first place. I e we need to replicate the code in vim's term.c to (1) send a sequence request mouse position events without click and (2) extend the event parsing code to parse the new events the terminal sends.

**Comment by dsych** [comment]
@bfredl  Sorry for long delay, but I got a chance to debug the event parsing code of nvim and try to figure out what I need to modify. This is what I got so far:

To me, it seems like an event callback is registered with libuv that is going to be fired every time there is user input (sorry can't find the exact registration anymore) and keystrokes will be written into a `read_buffer`. From there, the `TermInput` struct is eventually passed down to the [handle_raw_buffer](https://github.com/neovim/neovim/blob/97ffa158aa9ae6c80a48b3ceea91270f0a179743/src/nvim/tui/input.c#L558), which in turn is where **raw bytes are checked** for specific patterns.
For instance, there is a call to [handle_focus_event](https://github.com/neovim/neovim/blob/97ffa158aa9ae6c80a48b3ceea91270f0a179743/src/nvim/tui/input.c#L368) that is going to check for `focus in/out` events and schedule an appropriate autocmd.

The point I am trying to make is that we will need to introduce another function that will check for _mouse moved_ events and allow the if statement to fall through, so that the keys could be handled the same way as other mouse keys, [see](https://github.com/neovim/neovim/blob/97ffa158aa9ae6c80a48b3ceea91270f0a179743/src/nvim/tui/input.c#L613).

There is a problem, though. I am not able to receive control characters for mouse moved event on Gnome Shell ([as specified here](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking)), for some reason. All I get is _focus in_ followed by _focus out_. I am definitely missing something, since `beval` is working just fine on vim.

Any clues? I am new to the whole terminal emulation process, so I apologize for hand-holding)

**Comment by GBeauregard** [comment]
I eventually found this when trying to figure out porting compatibility with vim's `balloonevalterm` so I wanted to link that closed issue to here in case anyone else is confused about where the mouse hover part of the `balloonevalterm` support went: https://github.com/neovim/neovim/issues/8646

This also needs the compatibility label maybe since it's needed to make something with feature parity?

**Comment by zeertzjq** [comment]
A problem with implementing this as a pseudokey is that it can interrupt partial mappings, which means it cannot be always allowed.

**Comment by zeertzjq** [comment]
When there is a mouse hover handler, there also needs to be away to indicated that mouse has moved away from the hovering position. Therefore a UI only sending mouse hover events in not enough. There needs to be a way to tell a UI that it should send mouse movement events. I have implemented such a UI option `'mousemoveevent'` for TUI in #19481.

**Comment by lewis6991** [comment]
Can this be closed now we have `'mousemovement'` implemented?

**Comment by gpanders** [comment]
I think so: `'mousemoveevent'` makes it possible to implement mouse hover handlers. I'm not sure a separate "mouse hover" event would add much (especially considering @zeertzjq's comment above about needing yet another event to indicate that the mouse has stopped hovering).

As an example, I've implemented a mouse hover handler to display LSP hover information [here](https://github.com/gpanders/dotfiles/blob/master/.config/nvim/plugin/mouse.fnl).
