### ISSUE TITLE
No XAML syntax highlighting

### ISSUE THREAD

**Issue by bbrach** [neovim/neovim#9537]
- `nvim --version`: 0.3.4
- Vim (version: 8.1.751) behaves differently? No
- Operating system/version: Arch Linux on Windows Subsystem
- Terminal name/version: Termite 14
- `$TERM`: xterm-termite

### Steps to reproduce

Open a XAML file. This file should not have an XML declaration, which most do not have. I uploaded an example XAML file on [gist](https://gist.github.com/bbrach/78d8b69e821fa285aa34a66ce7c2e23b)

### Actual behaviour

Syntax is not highlighted

### Expected behaviour

Code should be highlighted. Visual Studio highlights xaml in the most cases like xml. There are few exceptions to that like data binding assignments.

**Comment by justinmk** [comment]
Thanks for reporting. This request is for the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim.

Syntax plugins (e.g. for ruby/java/YAML) are maintained by the maintainer listed at the top of the plugin file. Please report to that person, or to https://github.com/vim/vim. Thanks!

**Comment by chrisbra** [comment]
Note, Vim detects XML files by extension only (see e.g. here: https://github.com/vim/vim/blob/master/runtime/filetype.vim#L1850-L1879)
I would suggest posting a patch against runtime/filetype.vim for `*.xaml` files (similar to the other ones there). I guess that should fix your issue.
