### ISSUE TITLE
Wrong syntax highlighting in `perldoc` output

### ISSUE THREAD

**Issue by XVilka** [neovim/neovim#9544]
- `nvim --version`:
```
NVIM v0.3.3
Build type: RelWithDebInfo
Lua 5.3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/build/BUILD/neovim-0.3.3/build/config -I/builddir/build/BUILD/neovim-0.3.3/src -I/usr/include -I/builddir/build/BUILD/neovim-0.3.3/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.3.3/build/include
Compiled by mockbuild

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) no
- Operating system/version: Fedora 29
- Terminal name/version: Konsole
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
I just ran `perldoc perldata` (I have `nvi` set as default editor and pager (with vimpager plugin))

### Actual behaviour
![screenshot_20190124_191459](https://user-images.githubusercontent.com/203261/51674749-81bf3900-200c-11e9-9221-96864f01bc48.png)

### Expected behaviour

Not resetting the color after `/x`

**Comment by XVilka** [comment]
See also numbers parsing
![screenshot_20190124_193852](https://user-images.githubusercontent.com/203261/51675813-c3051800-200f-11e9-80e4-907d29a4e6d4.png)

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim.

Syntax plugins (e.g. for ruby/java/YAML) are maintained by the maintainer listed at the top of the plugin file. Please report to that person, or to https://github.com/vim/vim. Thanks!
