### ISSUE TITLE
RST ftplugin undocumented options

### ISSUE THREAD

**Issue by a-vrma** [neovim/neovim#9558]
- `nvim --version`: 0.3.4
- Vim (version: ) behaves differently?
- Operating system/version: macOS
- Terminal name/version: iTerm
- `$TERM`: xterm-256color-italic

### Changes

The rst ftplugin changes the tabstop and a few other values. It also has an option to disable these changes called `g:rst_style`. I helpgrepped and it doesn't look like it's documented so here's a `git format-patch` for it:

<https://0x0.st/zraz.patch>

**Comment by justinmk** [comment]
Thanks for the help! 

We don't want to fork the Vim runtime plugins in most cases (especially syntax plugins), unless there's a very good reason. Because if Vim changes something in the same file, it takes time to figure out the differences.

Please send this change to the maintainer, listed at the top of the file: 

And also send the change to https://github.com/vim/vim, mentioning that you already sent the change to the maintainer.

**Comment by a-vrma** [comment]
Gotcha, thanks.
