### ISSUE TITLE
Get/set the tag stack

### ISSUE THREAD

**Issue by baskerville** [neovim/neovim#9595]
I'd like to see [this patch](https://github.com/vim/vim/commit/f49cc60aa802862c595ff619dccc11271633a94b) being merged.

**Comment by mhinz** [comment]
We too! And it will happen, since we merge all upstream patches that also apply to Nvim.

Usually we merge them in-order though, since patches often rely on earlier patches. So, as long as no one takes the time to [port that patch](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim) right now, it will take a bit longer, but it will happen eventually.

**Comment by Shougo** [comment]
If you need the feature, you can port it.
