### ISSUE TITLE
No italics in Terminal.app

### ISSUE THREAD

**Issue by programble** [neovim/neovim#9598]
- `nvim --version`: v0.3.4
- Vim (version: ) behaves differently?
- Operating system/version: macOS 10.14.2
- Terminal name/version: Terminal.app 2.9.1
- `$TERM`: `xterm` or `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:hi StatusLine cterm=italic
```

### Actual behaviour

Status line does not become italic.

### Expected behaviour

Status line becomes italic.

Terminal.app does support italics, for instance I can `printf '\33[3mfoo\33[23m'`, but `sitm` and `ritm` caps are missing from terminfo. It seems like neovim patches these in if iTerm is detected, but not Terminal.app.

**Comment by justinmk** [comment]
> Terminal.app does support italics, for instance I can `printf '\33[3mfoo\33[23m'`, but `sitm` and `ritm` caps are missing from terminfo. It seems like neovim patches these in if iTerm is detected, but not Terminal.app.

Cool, didn't know that! Should be easy to add.

**Comment by justinmk** [comment]
#9601 adds italics support for Terminal.app if `TERM=nsterm` (see `:help $TERM`). "nsterm" is ncurses' official name for Terminal.app.

We have avoided using `$TERM_PROGRAM` to detect Terminal.app because that won't work over SSH. `TERM=nsterm` works over SSH.

Alternatively, #9601 also works in tmux if tmux is running on a system with the "tmux-256color" terminfo (recent Linux distros, but not macOS).

**Comment by programble** [comment]
Would it not be better to patch in `sitm` and `ritm` for any `TERM=xterm`? On systems other than macOS, terminfo always has them set. It's part of the ANSI standard SGR codes, so it should be safe.

**Comment by justinmk** [comment]
Maybe. The existing logic was written by someone more knowledgable than I, so I wanted to preserve their careful [opting-in](https://github.com/neovim/neovim/blob/69bdc4f0726ae0f3a2610dadbaf4156acfe74f49/src/nvim/tui/tui.c#L1584-L1591) rather than just blindly assuming we could emit italics everywhere. 

But since you mention it, I'm also ok with just blindly assuming :)

**Comment by programble** [comment]
As a workaround for this issue until either solution is applied, nvim can be made to use a more up to date terminfo database, for example installed with `pkgsrc` by creating a link:

```sh
ln -s /opt/pkg/share/terminfo ~/.terminfo
```
