### ISSUE TITLE
nvim as manpager leads to E20

### ISSUE THREAD

**Issue by tim241** [neovim/neovim#9631]
- `nvim --version`:
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe  -g -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/neovim-0.3.4/build/config -I/builddir/neovim-0.3.4/src -I/usr/include -I/builddir/neovim-0.3.4/build/src/nvim/auto -I/builddir/neovim-0.3.4/build/include
Compiled by void-buildslave@a-hel-fi

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: `Void GNU/Linux` (glibc version)
```
> ~ uname -a
Linux desktop 4.19.23_1 #1 SMP PREEMPT Fri Feb 15 09:35:13 UTC 2019 x86_64 GNU/Linux
> ~ 
```
- Terminal name/version:
```
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
```
- `$TERM`:
```
> ~ echo $TERM
rxvt-unicode-256color
> ~ 
```
### Steps to reproduce using `nvim -u NORC`

```
> ~ export MANPAGER="nvim -u NORC -c 'set ft=man' -"
> ~ man echo # can be any manpage, echo is just an example 
```

### Actual behaviour
![screenshot1](https://i.imgur.com/YQZgmPp.png)
```
Error detected while processing command line:
E20: Mark not set
Press ENTER or type command to continue
```
when I press ENTER, it isn't formatted.

![screenshot2](https://i.imgur.com/lOfdzQ5.png)

### Expected behaviour
It should show me the manpage correctly without any errors/formatting issues.

### Notes
```
> ~ export MANPAGER="nvim -u NORC -"
> ~ man echo
```
and then manually doing `set ft=man` works fine
![screenshot3](https://i.imgur.com/SH1egCJ.png)

**Comment by nuntapeecha** [comment]
Sent from my Mi phone
On Feb 20, 2019 8:07 PM, Tim Wanders <notifications@github.com> wrote:

  *   nvim --version:

NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe  -g -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/neovim-0.3.4/build/config -I/builddir/neovim-0.3.4/src -I/usr/include -I/builddir/neovim-0.3.4/build/src/nvim/auto -I/builddir/neovim-0.3.4/build/include
Compiled by void-buildslave@a-hel-fi

Features: +acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info


  *   Operating system/version: Void GNU/Linux (glibc version)

> ~ uname -a
Linux desktop 4.19.23_1 #1 SMP PREEMPT Fri Feb 15 09:35:13 UTC 2019 x86_64 GNU/Linux
> ~


  *   Terminal name/version:

rxvt-unicode (urxvt) v9.22 - released: 2016-01-23


  *   $TERM:

> ~ echo $TERM
rxvt-unicode-256color
> ~


Steps to reproduce using nvim -u NORC

> ~ export MANPAGER="nvim -u NORC -c 'set ft=man' -"
> ~ man echo # can be any manpage, echo is just an example


Actual behaviour

[screenshot1]<https://camo.githubusercontent.com/d5c21455fca28bf9011a96afcc9bf88770749436/68747470733a2f2f692e696d6775722e636f6d2f59515a676d50702e706e67>

Error detected while processing command line:
E20: Mark not set
Press ENTER or type command to continue


when I press ENTER, it isn't formatted.

[screenshot2]<https://camo.githubusercontent.com/4eb267e538f70c66412e4e2a6e24893ddfbf0b53/68747470733a2f2f692e696d6775722e636f6d2f6c4f66647a51352e706e67>

Expected behaviour

It should show me the manpage correctly without any errors/formatting issues.

**Comment by justinmk** [comment]
export MANPAGER="nvim -u NORC -c 'set ft=man' -"

Your system manpage tool (mandoc) has a bug in its MANPAGER parsing, so it doesn't understand the single-quotes. To work around this, follow the steps in `:help :Man` :

         export MANPAGER='nvim +Man!'

**Comment by tim241** [comment]
Thank you!
