### ISSUE TITLE
API: spurious/missing nvim_buf_detach_event

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#9642]
Docs state

```txt

nvim_buf_detach_event[{buf}]                           *nvim_buf_detach_event*

  When buffer is detached (i.e. updates are disabled). Triggered explicitly by
  |nvim_buf_detach()| or implicitly in these cases:
  - Buffer was |abandon|ed and 'hidden' is not set.
  - Buffer was reloaded, e.g. with |:edit| or an external change triggered
    |:checktime| or 'autoread'.
  - Generally: whenever the buffer contents are unloaded from memory.

  Properties:
    {buf} API buffer handle (buffer number)
```

Instances in the code:

- In [close_buffer](https://github.com/neovim/neovim/blob/master/src/nvim/buffer.c#L595)
- In [free_buffer_stuff](https://github.com/neovim/neovim/blob/master/src/nvim/buffer.c#L808)
- In [do_ecmd](https://github.com/neovim/neovim/blob/master/src/nvim/ex_cmds.c#L2488)

For now, I'm concerned with the last one. Generally, I think we need to detach once the buffer gets into a new state we can't send a `lines_event` for, e.g. when reloading the file from disk, or the buffer vanished for whatever reasons. Are there other instances where we need to detach?

Questions:

- It does run on `enew!`. Is that really intended? I don't see why, we're just opening a new empty buffer, our attached one will stay there in it's given state, won't it?
- It runs on `edit!` if and only if the undo info [gets saved](https://github.com/neovim/neovim/blob/master/src/nvim/ex_cmds.c#L2478). That can't be correct, can it? Need to be on every such call I think.

Generally, I'm pretty unsure what are the exact circumstances under that we need to detach. Can we somehow make a definitive, concrete list? I'd work on implementing it.

**Comment by justinmk** [comment]
> It does run on `enew!`. Is that really intended?

seems wrong. which buffer handle is given in that case?

>  It runs on `edit!` if and only if the undo info [gets saved](https://github.com/neovim/neovim/blob/master/src/nvim/ex_cmds.c#L2478). That can't be correct, can it?

seems wrong.

> Can we somehow make a definitive, concrete list?

The list in the help doc is definitive. The "concrete" part can live in test cases. But I think just fixing the cases you found will be quite an improvement.

**Comment by KillTheMule** [comment]
> seems wrong. which buffer handle is given in that case?

The one we're attached to.

> The list in the help doc is definitive. The "concrete" part can live in test cases.

I did not express myself correctly. The list might be definitive, but I personally can't derive an exhaustive test suite from it that covers all those cases, because I don't fully understand how you "abandon" a buffer or which are the possible ways to reload it.

> But I think just fixing (and test-covering) the cases you found will be quite an improvement.

I'll do that.

**Comment by KillTheMule** [comment]
Oh, @phodge any thoughts on this I might be missing?

**Comment by justinmk** [comment]
> The list might be definitive, but I personally can't derive an exhaustive test suite from it that covers all those cases, because I don't fully understand how you "abandon" a buffer

Yes. Finding an exhaustive list is not something we need to worry about. Just adding coverage for the cases you found, is a good improvement. 

Nevertheless,  grepping for `can_abandon` in the C source might give clues.

**Comment by phodge** [comment]
> Generally, I think we need to detach once the buffer gets into a new state we can't send a `lines_event`

Your statement there is 100% correct. We send detach events not because we like to, but because the buffer has been removed or reached some state where we can't work out what the change delta would be. For example, we have to detach any time a buffer's `b_ml` gets emptied.

A huge part of the original development was grepping through the codebase for things like `b_changedtick` or `b_ml`, examining every single reference to them and asking "Does this part of the code need to send a buffer update, or send a detach?" Often the function modifying `b_changedtick` or `b_ml` wasn't an appropriate place to send an event, so I would have to look at the function's callsites and work out if *those* functions should send events. And so on.

I would've loved to implement a really robust system of guarantees (e.g. some sort of garbage-collector-driven events) such that it's really easy to eyeball the code and be certain that if the events are working in one place, they must by definition be working everywhere. But that's really not possible with the vim's C spaghetti code, there's just so little encapsulation of anything.

> It does run on `enew!`. Is that really intended?

`:enew!` discards your current buffer and loads a new one so I'd expect a detach event, **unless** you have the original buffer open in another window, in which case it should **not** detach. If a buffer sends a detach event while it's still open in a visible window, that's almost certainly a bug.

> It runs on `edit!` if and only if the undo info [gets saved](https://github.com/neovim/neovim/blob/master/src/nvim/ex_cmds.c#L2478).

It should always run on `:edit!` because the buffer contents are cleared and reloaded from disk and we can't send a change delta in that scenario. If the detach event is only sent when `undoreload` is turned on, then that would be a bug. I'd imagine that's crept in via an upstream patch that wrapped that chunk of code in a conditional clause, but it may have been there since day 1.

**Comment by KillTheMule** [comment]
Thanks for your comments, @phodge, I appreciate you taking the time explaining :+1:

Re `enew`: You're right of course, unless `hidden` is set, in which case the original buffer stays untouched. The behavior you implemented was fully correct.

Re `edit`: Hope you don't mind me not investigating when the bug crept in, I simply fixed it and added a test. Not a biggie, but I ran precisely into this because my plugin works with large files.
