### ISSUE TITLE
lua 5.3: libmpack build failure / gen_api_ui_events.lua:174: can't serialize object on 32bit platforms

### ISSUE THREAD

**Issue by cryptomilk** [neovim/neovim#9760]
When trying to package neovim-0.3.4 for Fedora it fails to build on i686 and armv7hl.

The issue is probably: https://github.com/libmpack/libmpack-lua/issues/14 which I reported in 2017 already.

I guess I'm not the only packager running into this issue. I'm building with lua 5.3 instead of luajit, because luajit is:

a) Mostly unmaintained
b) Doesn't build on all platforms Fedora supports

because of the above it is unlikely that luajit will be fixed. However lua-mpack seems to be something nevoim cares about.

**Comment by justinmk** [comment]
> I'm building with lua 5.3 instead of luajit, because luajit is:
> a) Mostly unmaintained
> b) Doesn't build on all platforms Fedora supports

luajit is not unmaintained. Neovim also supports Lua 5.1 . 

Lua 5.3 is not supported. Lua 5.1 is a different, complete language than Lua 5.3. Lua 5.3 is not an "upgrade" to Lua 5.1, it's a different language.

In any case, @tarruda does libmpack-lua have any requirement on Lua versions?

**Comment by cryptomilk** [comment]
lua-5.1 doesn't seem to get updates anymore. Does that mean it is even completely bug free? The last release was in 2012.

luajit got a stable release in 2017, then a beta which didn't move since then.

I'm building neovim with lua 5.3 since several years now. The only problem is a bug in lua-mpack, otherwise it works just fine.

**Comment by justinmk** [comment]
I'm not aware of any  bugs in Lua 5.1 . It's designed to be embedded (i.e. crammed into software), so the "upgrade train" is not the intended use-case. Like lisp, it's the libraries that upgrade, not the language.

> I'm building neovim with lua 5.3 since several years now. The only problem is a bug in lua-mpack, otherwise it works just fine.

As we gain more Lua code this becomes risky.

**Comment by jrwats** [comment]
> Lua 5.3 is not supported. Lua 5.1 is a different, complete language than Lua 5.3. Lua 5.3 is not an "upgrade" to Lua 5.1, it's a different language.

What about say, [ephemeron tables](https://www.i-programmer.info/news/98-languages/3515-lua-520-released.html), as an example, introduced in 5.2?  This is a fairly core feature to the language - at least as I understand it.  i.e. this is not an example of associated libraries "upgrading", but of the core altering table behavior central to the language.

**Comment by bfredl** [comment]
> Another new addition to 5.2.0 is the concept of ephemeron tables. An ephemeron table is one with weak keys and strong values, where the value is only reachable if its key is reachable.

How is this different from a table in 5.1 with weak keys? `setmetatable({}, {__mode='k'})`

**Comment by jrwats** [comment]
### Thesis
I don't want to get too far off topic, but my *main* point was calling the Lua version updates "different languages" rather than "upgrades", seems like its playing with definitions here a bit. To a casual observer Lua 5.1, 5.2, 5.3 appear, on the surface, to be largely the same language except for pointed specifics the implementors/language designers have purposefully spent the time to add:

* 5.2 
  * ephemeron tables (and others I've probably forgotten)
* 5.3
  * integers
  * bitwise operators

That said I agree with
> It's designed to be embedded (i.e. crammed into software), so the "upgrade train" is not the intended use-case.

### Ephemeron tables
> How is this different from a table in 5.1 with weak keys? `setmetatable({}, {__mode='k'})`
Essentially in 5.2, you have a "smart weak key table" that catches cycles, and in 5.1 you have a strictly-by-the-definition weak-key table.

In Lua 5.1, it will abide by the strict interpretation of "strong" and "weak".  When a strong value refers back to a weak key, that table entry is essentially locked into the table and never reaped.  In Lua 5.2, such cycles are detected and, essentially, not "counted" towards the weak keys references.  It won't keep alive those keys if the values for cycles with them.

The canonical example from _Programming Lua 4th edition_ is 
```lua
do
  local mem = {}
  setmetatable(mem, {__mode = "k"})
  function factory (o)
    local res = mem[o]
    if not res then
      res = (function () return o end)
      mem[o] = res
     end
     return res
  end
end
```

"In Lua **(5.2)**, a table with weak keys and strong values is an _ephemeron table_.  In an ephemeron table, the accessibility of a key controls the accessibility of its corresponding value.  More specifically, consider an an entry _(k, v)_ in an ephemeron table. The reference to _v_ is only strong if there is some other external reference to _k_.  Otherwise the collector will eventually collect _k_ and remove the entry from the table, even if _v_ refers (directly or indirectly) to _k_."

**Comment by bfredl** [comment]
I cannot be 100% sure about anything anymore but it sounds like 5.1 weak weak tables should be enough e.g. for internal tree-sitter nodes.

**Comment by bfredl** [comment]
And I, suppose  a fairer statement would be that 5.1 and 5.3 be more like python 2 and 3 or major version for semver langs (and luajit be like pypy except that people actually use it)

**Comment by jrwats** [comment]
> I cannot be 100% sure about anything anymore but it sounds like 5.1 weak weak tables should be enough e.g. for internal tree-sitter nodes.

Yeah the *weak key table* => *ephemeron table* is a subtle "upgrade" for a particular brand of "edge case".  But that's why I called it out as an example.

### My main question
Anyways, I ultimately stumbled onto this thread largely because ***I*** also wanted to know
**_Why are we on Lua 5.1 (2006), when Lua 5.4 is out?_**

If I understand things correctly, this answer largely boils down to:
**_LuaJIT supports 5.1 (and some of 5.2) is core to Neovim's architecture_**

It looks like ***when*** it does support any 5.3+ constructs, you'll need to take care in knowing where semantics diverge.  Some example discussion here https://github.com/LuaJIT/LuaJIT/issues/63, suggests they may change how certain operators perform for performance, for instance.

**Comment by bfredl** [comment]
Short answer: luajit. If there is a luajit for 5.4 stable enough for us and the major distros we will seriously reconsider but not before that

**Comment by jamessan** [comment]
> I don't want to get too far off topic, but my _main_ point was calling the Lua version updates "different languages" rather than "upgrades", seems like its playing with definitions here a bit.

https://www.lua.org/versions.html#numbering is what our phrasing is informed by.  There's no specific consideration for compatibility (source or binary) between versions.

**Comment by maisiliym** [comment]
> Short answer: luajit. If there is a luajit for 5.4 stable enough for us and the major distros we will seriously reconsider but not before that

Is it because of luajit FFI? Which part of luajit does neovim depend on otherwise?
The luajit FFI code was ported over here https://github.com/q66/cffi-lua
> aiming to be mostly compatible with LuaJIT FFI,

**Comment by bfredl** [comment]
>  Which part of luajit does neovim depend on otherwise?

The "jit" part. Core doesn't need it, but plugins are free to assume jit performance for an acceptable user experience.

**Comment by tmccombs** [comment]
> luajit is not unmaintained

Luajit hasn't had a release since 2.1-beta3 over four years ago, and I haven't seen any indication that an official release is forthcoming. Yes, there are still commits being made, but that doesn't do much good if they don't make it to distributions.  (And archlinux for example doesn't even have the 2.1 beta in the official repos).

Otoh, the openresty luajit2 fork seems better maintained, and sort of has releases.

**Comment by clason** [comment]
First, if distributions don't bundle LuaJIT, that's on them -- the build scripts provided by Neovim build against a curated commit, which has served us well enough. (And the question of releases is completely orthogonal to that of being maintained -- which we care more about -- so this is a strawman argument.)

Also, as you coyly allude to, LuaJIT2 does _not_ have releases -- it just has tags, which some (but not all) distros accept in lieu of actual releases. I also wouldn't at all say that it's better maintained -- in fact, activity has dropped off markedly in the last months, while LuaJIT has been going steady. [And I am keeping track of this](https://github.com/neovim/neovim/pull/13741).

**Comment by bfredl** [comment]
>  (And archlinux for example doesn't even have the 2.1 beta in the official repos).

The version of arch linux where this actually matters, i e arch linux ARM, certainly has it.

**Comment by tmccombs** [comment]
> First, if distributions don't bundle LuaJIT, that's on them

Bundlng dependencies like luajit with the  package that uses it is pretty unusual for most linux distributions, and ignoring that fact is irresponsible IMO. And it's also very uncommon for them to package some untagged version of a project. Are there major distributions that don't build with `USE_BUNDLWD=off`, or have a package of luajit that uses the "curated commit"?

> The version of arch linux where this actually matters, i e arch linux ARM, certainly has it.

Why do you think it only matters for ARM?

**Comment by bfredl** [comment]
> Why do you think it only matters for ARM?

If you don't know the basic facts about the question that has been discussed for a very long time, you won't be able to contribute anything new to the discussion, sorry.

**Comment by tmccombs** [comment]
@bfredl maybe we are talking past each other. I'm primarily concerned about the broader issue of lua 5.3 vs luajit/lua 5.1 not this specific segfault on x86 and arm. Maybe this wasn't the best issue to comment on, I wasn't aware of https://github.com/neovim/neovim/pull/13741 when I first commented. I'm mostly trying to understand why neovim went with luajit instead of PUC lua. 

I'll continue in #15737

**Comment by clason** [comment]
Please don't -- that has nothing to do with Lua(JIT) 5.1 vs. 5.3; that decision is made and done.

**Comment by bfredl** [comment]
> And why LuaJIT? Simple: performance. (The difference can be several orders of magnitude.)

Another way to put it, we chose lua because of luajit, not the other way around. The alternative to luajit would rather have been some other high performance runtime (possibly targeting another lang altogether) rather than puc lua without jit. But it is all hypothetical at this point as luajit has been serving a growing ecosystem well for a long time.

**Comment by clason** [comment]
Neovim targets Lua 5.1, and Lua 5.3+ is _not_ an upgrade path. (Lua is a different beast than Python or Perl.)

Should there ever be a JIT runtime for one of the later language versions that is comparable in quality to LuaJIT, we might reconsider, but that should be a fresh discussion if and when it happens.

**Comment by cryptomilk** [comment]
At Fedora we just use the released beta tarball and apply the changes from the v2.1 branch. We also have a patch to add the testsuite so we can check if something goes wrong. For platforms where luajit isn't supported (s390x, ppc64le) you can use lua 5.1. Archlinux can just do the same.

https://src.fedoraproject.org/rpms/luajit/tree/rawhide

**Comment by cryptomilk** [comment]
Here is my branch with additional patches on top of the v2.1 branch we have in Fedora:

https://github.com/cryptomilk/LuaJIT/commits/v2.1-fedora
