### ISSUE TITLE
yacc syntax breaks if comment on section seperator

### ISSUE THREAD

**Issue by mjsir911** [neovim/neovim#9781]
File `test.y` looks like this:
```yacc
%{
#include <stdio.h>
%}

%token x /* why am I needed for syntax highlighting? */

%% /* syntax breaks because of me */
line        : /* empty */
            ;
%%

void yyerror(const char *str)
{
  fprintf(stderr,"error: %s\n",str);
}

int yywrap()
{
  return 1;
}

int main()
{
  printf("> "); 
  yyparse();
  return 0;
}
```

syntax highlighting breaks after line 7 due to comment `/* syntax breaks because of me */`

this is caused by the line in `syntax/yacc.vim`:
```
SynFold syn	region	yaccInit2      start='\%^.'ms=s-1,rs=s-1	matchgroup=yaccSectionSep	end='^%%$'me=e-2,re=e-2	contains=@yaccInitCluster	nextgroup=yaccRules	skipwhite skipempty
```
specifically, the `end='^%%$'`

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim.

Syntax plugins (e.g. for ruby/java/YAML) are maintained by the maintainer listed at the top of the plugin file. Please report to that person, or to https://github.com/vim/vim. Thanks!
