### ISSUE TITLE
[Question] vim-patch:8.0.0702: Should a timer stop after 3 errors occur?

### ISSUE THREAD

**Issue by LTKills** [neovim/neovim#9830]
I'm porting [`vim-patch:8.0.0702`](https://github.com/vim/vim/commit/c577d813b7978345dec4310b2d8f5d5624a681f6?diff=split#diff-28790a430300cd187bda51bd6a014757). According to the code changed in `test_timers.vim` the patch requires timers to stop after failing 3 times.

[The way we test it](https://github.com/neovim/neovim/blob/a011f8a3211cfc3369437d8686c6999d491ba290/src/nvim/testdir/test_timers.vim#L203) is exactly the opposite. Should this be implemented? Maybe caught errors should be ignored and non-caught ones should stop the timer when they happen more than three times

**Comment by justinmk** [comment]
use `git blame` (or `:Gblame` from fugitive) to see that was added in https://github.com/neovim/neovim/commit/090008f3110fa48e7e09fefc950e60c384aff70d .

Not sure why that test passes, but in any case the first thing to do is to port the _test_ from 8.0.0702, then see if it fails, and work from there.

And yes, we want timers to stop after 3 errors occur. At least until someone presents an argument for why we should do otherwise.
