### ISSUE TITLE
SSH Terminal Display Size is Automatically changed.

### ISSUE THREAD

**Issue by KZYSAKYM** [neovim/neovim#9931]
- `nvim --version`:
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-AqTbY4/neovim-0.3.4/build/config -I/build/neovim-AqTbY4/neovim-0.3.4/src -I/usr/include -I/build/neovim-AqTbY4/neovim-0.3.4/build/src/nvim/auto -I/build/neovim-AqTbY4/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently?: Yes
- Operating system/version: Linux 4.14.77-70.59.amzn1.x86_64 (SSH Target)
                                              Windows 7 (Host)
- Terminal name/version:
   RLogin 2.23.0
- `$TERM`:
   ```
    $ echo $TERM
     xterm
    ```

### Steps to reproduce using `nvim -u NORC`

1. Using RLogin, do ssh login to the target.
2. Execute vertical split display on RLogin.
3. Open some file with nvim
```
nvim foo.txt
```

### Actual behaviour
the width of the window using nvim is made bigger.

### Expected behaviour
the width is not changed.

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? This should have been fixed by https://github.com/neovim/neovim/pull/9645 which is not part of 0.3.4.

The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)
