### ISSUE TITLE
Feature: zoom windows.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#997]
The ability to zoom a window (a toggle) so it fills up the whole space inside a tab would be nice. There could be a command like `:zoomtoggle` to fulfill the need. This would be similar to what tmux and screen do.

**Comment by marlun** [comment]
Anyone who has taken a look at ZoomWin and why it's not working in neovim?

**Comment by khalidchawtany** [comment]
@marlun I have no idea why it was not working for me. However, I gave up trying to make it work. Currently, I use [ZoomWinTab](https://github.com/troydm/zoomwintab.vim) which zooms the buffer into a new tab.

**Comment by marlun** [comment]
@khalidchawtany ZoomWinTab seems to work great when trying it out, thanks!

**Comment by tarruda** [comment]
ZoomWinTab is a nice replacement for tmux zoom feature

**Comment by asgeo1** [comment]
The ZoomWin error messages mentioned above can be avoided, by setting a custom list of options for ZoomWin to save when it saves the window state:

    if has('nvim')
        " removed 'key', 'oft', 'sn', 'tx' options which do not work with nvim
        let g:zoomwin_localoptlist = ["ai","ar","bh","bin","bl","bomb","bt","cfu","ci","cin","cink","cino","cinw","cms","com","cpt","diff","efm","eol","ep","et","fenc","fex","ff","flp","fo","ft","gp","imi","ims","inde","inex","indk","inf","isk","kmp","lisp","mps","ml","ma","mod","nf","ofu","pi","qe","ro","sw","si","sts","spc","spf","spl","sua","swf","smc","syn","ts","tw","udf","wfh","wfw","wm"]
    endif

However, this does not fix the main issue - ZoomWin still hangs for 20 seconds or so when activating it.

I don't know what's causing the hanging unfortunately.

**Comment by marlun** [comment]
I'm not sure how ZoomWin solves the problem but using a tab seems like the perfect use of tabs since it's there to create alternative "views" in vim?

**Comment by trusktr** [comment]
ZoomWinTab is nice, but still a hack of sorts. The nicest solution will be
when windows zoom natively inside a tab (without making a new tab and
hiding the tab bar).

But :+1:! I'm using ZoomWinTab for now. :D

**Comment by mattboehm** [comment]
I use `:tab split` when I want to 'zoom' and have not had any problems with this approach so far.

**Comment by justinmk** [comment]
@mattboehm Nice tip

**Comment by tarruda** [comment]
Zooming in/out would be the same as switching the current `frame_T` structure, which is already what happens when switching  to another tab, so there's no point in having another command just for this.

**Comment by trusktr** [comment]
@tarruda I disagree from a user experience perspective. Opening a new tab isn't conceptually the same as zooming a window inside of a tab and keeping all window layouts untouched when zooming back out. 

In all current vimscript implementations I've tried, it's possible to do something or other to end up with a window layout that wasn't the same as you would expect when zooming back out. They are hacks, not solutions.

**Comment by justinmk** [comment]
@trusktr `:tab split` *does* preserve the window layout. Simply close the new tab, and return to the previous tab, and the layout was not modified.

**Comment by hoschi** [comment]
When you treat your tabs as a containers for a bunch of buffers which belongs to a task, you get a new anonymous task with `:tab split`. ZoomWin for example gives you more screen spacen without modifying your currated tab list. Unfortunately it breaks in several circumstances, and imo this issue was to come up with an idea to get the same benefits of ZoomWin without the negatives.

**Comment by marlun** [comment]
I only used ZoomWin to temporarily get more viewing space and for that the `:tab split` solution works great and it works wherever you go since there's no need to install a plugin. As I understand it tabs are actually in vim to do this (not only this but this included). I much prefer learning to use something which is in n/vim by default instead of depending on a plugin.

I do however understand that it's weird if you're coming from other editors where opening a new file always means opening a new tab.

**Comment by justinmk** [comment]
> ZoomWin for example gives you more screen spacen without modifying your currated tab list. Unfortunately it breaks in several circumstances, and imo this issue was to come up with an idea to get the same benefits of ZoomWin without the negatives

@hoschi What negatives? The tab is temporary. Once you close the tab your tab list is restored.

**Comment by hoschi** [comment]
@marlun @justinmk Tabs are the only way to group buffers together in vim, hence I wouldn't want to use them for a cheap "solution" for zooming a window. I actually use `:tab split` all day, since ZoomWin has its problems and there is no other way at the moment, but it would be great if there is a solution for this which only works with windows.

**Comment by justinmk** [comment]
@hoschi I use tabs to group buffers/windows as well. But I still do not understand your dissonance. `:tab split` is an elegant solution IMO.

**Comment by trusktr** [comment]
A UX designer might not agree. :D Opening a new tab isn't the same as zooming, otherwise it wouldn't be called opening a new tab. x) Tmux has the "zoom" feature down.

**Comment by hoschi** [comment]
@justinmk the negative is the additional tab itself. When you have 7 tabs and each of it has 3 windows, you get 14 tabs when you "zoom" one window of each original tab. This leads to additional negative points:
* tab list is very long and get cut because the neovim window is too small
* your tabline shows the active tab, so you don't know which tab holds your zoomed buffer and which tab holds the original 3 windows, this breaks `[count]gt` movements 
* you can't cycle through tabs/groups any more, because you have now groups and "one thing of a group which seems to be a group with just one item"

As I said, I use `:tab split` every day, but only because it is the best *current* solution .. not (imo) the best solution.

**Comment by trusktr** [comment]
@hoschi has it. We want to be able to zoom inside of as many tabs as we want, without duplicating the number of tabs. That'd be a nice actual "zoom" feature. :D

**Comment by trusktr** [comment]
`:tab split` breaks spacial organization.

**Comment by trusktr** [comment]
I can see that `:tab split` works for people who memory map their buffers, but other people like to have a visual representation of their workspace.

**Comment by Pyrohh** [comment]
I think I understand, as I use tmux's zoom feature frequently and it's indeed very useful IMO

**Comment by marlun** [comment]
@hoschi if you have 7 different views for the same project I do understand that it gets hard to work with. Isn't that kind of an extreme though? Out of curiosity, how come you have that many? I'm not against a feature like tmux zoom though.

**Comment by justinmk** [comment]
I can't imagine why one would zoom more than *one* window at the same time, or longer than briefly--but at least now there are *details* which describe the shortcomings of `:tab split`. That's what was missing before.

**Comment by marlun** [comment]
How does sessions fit in to this problem? Could one not use sessions for the different tasks?

**Comment by trusktr** [comment]
@marlun I've had ~90 windows in a single tab.

**Comment by trusktr** [comment]
The problem is the vi sessions aren't really... sessions. They are just scripts that open a bunch of windows, tabs, and set options.

**Comment by asgeo1** [comment]
I'm with @hoschi and @trusktr - this is exactly how I work too:

I have multiple tabpages open at once.  Each tabpage has multiple split windows.  Sometimes the same buffer may be visible across multiple tabpages.

So each tabpage is effectively a "view" - a group of windows and buffers which I am currently working on, in a particular arrangement which makes sense for the task I'm working on.

I am constantly cycling between my tabpages (views) as I'm working.  I don't like to disrupt my tabpage window arrangements, other than to zoom in or out on a particular window if needed.


As others have said, `:tab split` sucks because it creates a new tabpage - this stuffs me up when I'm trying to cycle between my tabpages.   It breaks the mental model of my project that I had carefully arranged into tabpages and windows, because now there is an extra tabpage in the list which makes it very difficult to adjust how I had ordered my tabpages in my head.



I would *love* a native zoom feature in Vim!  Please make this happen :)

**Comment by hoschi** [comment]
@marlun 
* one tab for terminals, one terminal buffer for advanced git commands and others for long running programms e.g. `gulp server` or something
* one tab for project wide setting files, e.g. Grunt, .jshintrc, .git/config/exclude, ...
* one tab for a module, which has windows to show files which are used in this module and one window for the testfile

As it is really unusual that fixing a ticket includes only one module, I go usually have 4 to 8 tabs opened. This is not only the case for one projects, I work at 4 different projects recently and I use this workflow for all of it.

@justinmk The use case for zooming more than one window is for focusing of a part of a module tab. E.g. zoom at test file in module tab 1 because one test fails, zoom into source file of module tab 2 to see how to mock it correctly and eliminate side effects.

**Comment by marlun** [comment]
It makes sense and I can see how a more tmux like zoom feature could be really helpful for some people. Especially when neovim added the :terminal feature and people will start using it like tmux.

**Comment by hoschi** [comment]
> Especially when neovim added the :terminal feature and people will start using it like tmux

Thats also right, I actually evaluate if neovim terminals could replace tmux and the missing zoom feature is one problem here.

**Comment by marlun** [comment]
I'm still where I feel neovim replacing tmux is a bad thing but a lot of people are loving it.

**Comment by tarruda** [comment]
> @justinmk the negative is the additional tab itself. When you have 7 tabs and each of it has 3 windows, you get 14 tabs when you "zoom" one window of each original tab. This leads to additional negative points:

Zooming more than one tab isn't really useful since you can only see one tab at a time, and even if you need that for your workflow, such thing would be achievable as a plugin. But it is not our goal to support every possible workflow as native commands/features, which is why vimscript exists.

> Opening a new tab isn't conceptually the same as zooming a window inside of a tab and keeping all window layouts untouched when zooming back out

It might not be conceptually the same, but it is the same from an implementation POV. Even if we were to add a command dedicated for zooming, it would simple invoke something like `tab split` under the hoods. I'd consider adding a plugin that manages zooming more efficiently than using `tab split`/`tabclose` directly, but won't implement a new zooming feature in C when vimscript can deal with it just fine.

**Comment by trusktr** [comment]
> But it is not our goal to support every possible workflow as native commands/features, which is why vimscript exists.

But every attempt in vimscript has always been a hack. There's always some downside to the plugin, whereas a simple native zoom similar to tmux wouldn't have any such downsides.

> it would simple invoke something like tab split under the hoods.

I think you're not imagining exactly what we are. We want to be able to have the views of tab of any number of tabs to be able to contain a zoomed window, while not affecting tab layout. `:tab split` doesn't follow this rule.

Every current plugin that "zooms a window" inside of a tab has to actually *close* all the windows in the tab except for one, then (hopefully) restore all those windows when "zooming back out". That is by far a hack, it won't work with sessions (saving a session while a window is zoomed), and will certainly cause frustration when original windows aren't restored due to some user action that destroyed the plugin's state (f.e. splitting a "zoomed" window). It's definitely not a simple `:tab split` under the hood.

**Comment by justinmk** [comment]
> But every attempt in vimscript has always been a hack.

Let's focus on making the API powerful and stable, so that plugins can implement these ideas.

**Comment by trusktr** [comment]
:+1:

**Comment by hoschi** [comment]
I'm a bit confused now.

from @tarruda 
> I'd consider adding a plugin that manages zooming more efficiently than using tab split/tabclose directly, but won't implement a new zooming feature in C when vimscript can deal with it just fine.

from @justinmk 
> Let's focus on making the API powerful and stable, so that plugins can implement these ideas.

So here is my question: Is it already possible to do a tmux like zoom feature (without creating new tab)  with the current API (by e.g. vimscript)?

**Comment by justinmk** [comment]
> Is it already possible to do a tmux like zoom feature (without creating new tab) with the current API (by e.g. vimscript)?

No. Let's focus on making the API powerful and stable, so that plugins can implement these ideas.

**Comment by hoschi** [comment]
Thanks for clarification.

**Comment by davidsteinberger** [comment]
@justinmk What's the timeline of this? Neovim is awesome, though I really like ZoomWin.

In the meantime I'm using a simple resize: http://stackoverflow.com/questions/13194428/is-better-way-to-zoom-windows-in-vim-than-zoomwin. Has somebody found a better solution?

    " Zoom / Restore window.
    function! s:ZoomToggle() abort
      if exists('t:zoomed') && t:zoomed
        execute t:zoom_winrestcmd
        let t:zoomed = 0
      else
        let t:zoom_winrestcmd = winrestcmd()
        resize
        vertical resize
        let t:zoomed = 1
      endif
    endfunction
    command! ZoomToggle call s:ZoomToggle()
    nnoremap <silent> <C-A> :ZoomToggle<CR>

**Comment by justinmk** [comment]
@davidsteinberger Stabilizing the API with its current (minimal) feature set will hopefully be done this calendar year. Adding new features that would make zooming a window in the core, easy to do via the API, could happen next year.

**Comment by mattboehm** [comment]
Just out of curiosity, what would people expect `:split` to do when zoomed in? Or `:q`? If you can't split the zoom, you're missing out on a lot of capability. If you can, then people may expect to zoom again at some point. There are multiple answers to these questions, and I think each one might violate some peoples'/plugins' expectations. I agree with @justinmk that the exact behavior of zooming should therefore fall into the plugin territory.

Here's my current take on the issue:

While many people see tabs as a way to contain different arrangements of windows, they can hold a lot of other state too (file lists via ctrl-space and the behavior of various other plugins with tab-specific settings like accordion.) Some people want to separate the concept of views and tabs so that they can switch between multiple views within the same tab.

I think the ideal solution would be something like `:mkview`, but capable of dumping window layout/position into a vim variable. Plugins (or included commands) could then then provide a way to manage this list of views and switch between them (perhaps storing a stack of views in a `t:` variable).

No matter what happens, I'd probably continue to use `:tab sp` as I find it much simpler and less restrictive, but I understand why others would want alternative behavior. As someone else mentioned, splitting inserts a tab after the current tab and closing also goes to the next tab, which is a bit annoying. To circumvent this, you can split the current window into a new tab before the current one with `tab split | execute 'tabmove '. (tabpagenr() - 2)`

**Comment by trusktr** [comment]
@mattboehm 

> what would people expect :split to do when zoomed in? Or :q?

The same things that happens in tmux.

**Comment by davidsteinberger** [comment]
I think *ZoomWin* would be an ideal interim solution. Does anyone know what's causing the hang in *NeoVim*?

**Comment by davidsteinberger** [comment]
*ZoomWinTab* is indeed a good solution. I'm still curious what makes *ZoomWin* so slow in NeoVim. Does anyone know?

**Comment by willhoag** [comment]
*ZoomWinTab* doesn't seem to work on unnamed buffers unfortunately. I'll be sticking with `:tab split` and `:tab close` for now.

**Comment by steadystatic** [comment]
Just a heads up Janus ships ZoomWin.vim by default (I'm slowly migrating away from it and cleaning up my vimrc), so you'll get that error with it and a slight hang in Neovim. What I did was this `call janus#disable_plugin('zoomwin')` and update any of my mappings like so `map <leader>z :ZoomWinTabToggle<CR>`

**Comment by eeowaa** [comment]
`zoomwintab` is not a sufficient replacement for `ZoomWin`.

- By default, `zoomwintab` hides the tab bar when you zoom a window. This is unacceptable when your workflow depends on visible tabs, and is especially disorienting if you do a `:tabnew` when zoomed in.
- Disabling the `g:zoomwintab_hidetabbar` setting will show tabs when zooming, but then you see the temporary tab used for the "zoomed window". This breaks the semantic, user-defined layout of tabs in a tab-based workflow, both for visual recognition and quick navigation between tabs.

I have used `ZoomWin` for a decade in `vim` with other plugins and have had zero problems. It is a crucial part of my personal `tmux`/`vim` workflow that I have stuck with for my entire career. Why Neovim can't just zoom a window in the current tab is beyond me. Vanillia Emacs can easily do this by saving a window layout to a register (`C-x r w <register>`), maximizing a window (`C-x 1`), and restoring the old window layout from the register (`C-x r j <register>`). Does Neovim really have nothing like this that doesn't involve saving a session to disk?

**Comment by bfredl** [comment]
> Vanillia Emacs can easily do this by saving a window layout to a register

Neovim can save window layouts as well. we call them "tabs".
